metabrainz/musicbrainz-server

- INSTALL.md
The rest of your manual uses dumps/
> Fix path in gpg command

- lib/MusicBrainz/Server/Edit/Release/ReorderMediums.pm
- t/lib/t/MusicBrainz/Server/Edit/Release/ReorderMediums.pm
Before accepting the edit, check if there exist any mediums which are already in positions we want to move into (unless those mediums themselves are being moved out of those positions). If so, throw a `FailedDependency` exception to cause the edit to fail and to have ModBot leave a note.
> MBS-8580: (release, position) conflict in "Reorder mediums" edit

- root/layout/menu.tt
*http://tickets.musicbrainz.org/browse/MBS-8588* :link:
Related to https://github.com/metabrainz/metabrainz.org/pull/201.
cc: @mayhem
> MBS-8588: Point "Contact us" link to a page on MetaBrainz website

- HACKING.md
> Add info about reports into HACKING.md

- HACKING.md
- lib/MusicBrainz/Server/Report/NotVariousArtists.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/index.tt
- root/report/not_various_artists.tt
\+ more info in HACKING.md and some cleanup.
*Related to [MBS-2255](http://tickets.musicbrainz.org/browse/MBS-2255).*
> MBS-2255: Add report that lists recordings incorrectly linked to Various Artists

- lib/MusicBrainz/Server/Report/RecordingsWithoutVACredit.pm
- lib/MusicBrainz/Server/Report/RecordingsWithoutVALink.pm
- lib/MusicBrainz/Server/Report/ReleaseGroupsWithoutVACredit.pm
- lib/MusicBrainz/Server/Report/ReleaseGroupsWithoutVALink.pm
- lib/MusicBrainz/Server/Report/ReleasesWithoutVACredit.pm
- lib/MusicBrainz/Server/Report/ReleasesWithoutVALink.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/index.tt
- root/report/release_groups_without_va_credit.tt
- root/report/release_groups_without_va_link.tt
- root/report/releases_without_va_credit.tt
- root/report/releases_without_va_link.tt
*http://tickets.musicbrainz.org/browse/MBS-2255*
> VA reports for releases and release groups

- lib/MusicBrainz/Server/Report/ArtistsDisambiguationSameName.pm
- lib/MusicBrainz/Server/Report/LabelsDisambiguationSameName.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/artists_disambiguation_same_name.tt
- root/report/index.tt
- root/report/labels_disambiguation_same_name.tt
> MBS-8489: Incorrect disambiguation reports

- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Work.pm
- t/lib/t/MusicBrainz/Server/Controller/Work/Show.pm
- t/sql/controller_work.sql
Last bit of feedback from our Google contact.
> Output medleys as musicArrangements in JSON-LD

- lib/MusicBrainz/Server/Controller/WS/2/Instrument.pm
Instrument browse requests aren't actually implemented (and I'm not sure any would make sense at the moment).
> Remove unused cruft from WS::2::Instrument

- lib/MusicBrainz/Server/Controller/Tag.pm
- lib/MusicBrainz/Server/Controller/WS/2/Rating.pm
- lib/MusicBrainz/Server/Data/Search.pm
- lib/MusicBrainz/Server/Data/Statistics.pm
- lib/MusicBrainz/Server/Filters.pm
- lib/MusicBrainz/Server/WebService/Validator.pm
Just a bit of cleanup, continuing on commit 3cf6e7c8eb0f27a7ca3600bd38eb6cff8a27d4fc.
> Remove more url-or-name fallbacks

- lib/MusicBrainz/Server/Data/Edit.pm
This was the winner in the performance tests: `SELECT * FROM edit JOIN ($subquery) re ON edit.id = re.edit` It’s the only one where the default selectivity is not applied.
> MBS-8368: Use a better-performing query for collection edits

- root/static/scripts/edit/MB/Control/ArtistCredit.js
The first argument is the input element:
https://github.com/metabrainz/musicbrainz-server/blob/1838455/root/components/forms.tt#L358
> MBS-7012: Join phrase cleanup not running

- root/components/relationship-editor.tt
Trying to close old tickets that have been assigned to me since forever.
> MBS-7907: Warning about pending edits on a relationship is missing

- lib/MusicBrainz/Server/Data/Edit.pm
The query for edits by subscribed editors took too long time after the recent changes to it; the cause and the cure are the same as for the subscribed entities (commit 0dc12b9177f97a24cd29b093c2e55226c8ad92a2).
> MBS-8691: Avoid “subscribed editor edits” timeouts

- root/user/tag.tt
Related ticket: http://tickets.musicbrainz.org/browse/MBS-8658
> MBS-8658: Include tag name on user/tag/tagname pages

- lib/MusicBrainz/Script/RemoveExpiredSessions.pm
According to https://github.com/metabrainz/musicbrainz-server/pull/181#issuecomment-166477520, retrieving all relevant keys with `KEYS` did work, but subsequently retrieving 4.8 million values with a single `MGET` failed. Therefore, split the keys into smaller batches of configurable size and `MGET`/`DEL` each batch separately.
> Let RemoveExpiredSessions work in batches

- lib/MusicBrainz/Server/Test.pm
After `use utf8` was added to some test modules, queries that were passed into `prepare_test_database` directly as strings, not via files in `t/sql`, were already marked as UTF-8 text and not as bytes. It led to an exception when the `_load_query` helper function subsequently tried to decode them.
Remove the decoding step altogether and tell Perl to treat the files as UTF-8 text via an encoding layer. Also remember to close the handle after reading the file, and check for I/O errors.
> Don’t double-decode UTF-8 queries in tests

- lib/MusicBrainz/Server/Edit/Medium/Edit.pm
- lib/MusicBrainz/Server/Edit/Recording/RemoveISRC.pm
- lib/MusicBrainz/Server/Edit/Release/Merge.pm
- lib/MusicBrainz/Server/Edit/ReleaseGroup/SetCoverArt.pm
- lib/MusicBrainz/Server/Edit/Role/Insert.pm
- lib/MusicBrainz/Server/Edit/Work.pm
- lib/MusicBrainz/Server/Edit/Work/AddISWCs.pm
- lib/MusicBrainz/Server/Edit/Work/RemoveISWC.pm
- lib/MusicBrainz/Server/Plugin/Diff.pm
- root/edit/details/edit_alias.tt
- root/edit/details/edit_area.tt
- root/edit/details/edit_artist.tt
- root/edit/details/edit_event.tt
- root/edit/details/edit_label.tt
- root/edit/details/edit_medium.tt
- root/edit/details/edit_place.tt
- root/edit/details/edit_recording.tt
- root/edit/details/edit_release_label.tt
- root/edit/details/merge_releases.tt
A number of improvements in edit display; some with ticket, some without ticket, some only internal (e.g. silencing warnings). See the individual commits, they are all independent.
> Edit display improvements (includes MBS-4575, MBS-8012, MBS-8161, MBS-8210)

- root/static/scripts/relationship-editor/common/dialog.js
- root/static/scripts/relationship-editor/common/entity.js
- root/static/scripts/relationship-editor/common/fields.js
- root/static/scripts/tests/relationship-editor.js
- root/static/scripts/tests/typeInfo.js
This changes `getRelationshipGroup` to consider direction in addition to the link type.
> MBS-8730: Reordering of sub work parts causes unwanted reordering of main work parts

- lib/MusicBrainz/Server/Email.pm
- lib/MusicBrainz/Server/Email/NewReleases.pm
- lib/MusicBrainz/Server/Email/Subscriptions.pm
- root/account/donation.tt
- root/account/lost_password_sent.tt
- root/account/lost_username_sent.tt
- root/account/register.tt
- root/email/subscriptions.tt
- root/main/index.tt
- root/static/search_plugins/opensearch/musicbrainz_artist.xml
- root/static/search_plugins/opensearch/musicbrainz_label.xml
- root/static/search_plugins/opensearch/musicbrainz_release.xml
- root/static/search_plugins/opensearch/musicbrainz_track.xml
- t/lib/t/MusicBrainz/Server/Email.pm
That's all I found, except for admin/nginx/mbserver-rewrites.conf which I'd rather not touch without confirmation that it's safe.
> MBS-8771: Update multiple links to our old Contact Us page

- lib/MusicBrainz/Server/Data/Collection.pm
- lib/MusicBrainz/Server/Data/CollectionType.pm
- lib/MusicBrainz/Server/Form/Collection.pm
- root/collection/edit_form.tt
Fixes the issues described in http://tickets.musicbrainz.org/browse/MBS-8007?focusedCommentId=34417&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#action_34417
> MBS-8007: Allow changing the type of an existing collection

- entities.json
- lib/MusicBrainz/Server/Controller/Area.pm
- lib/MusicBrainz/Server/Data/Editor.pm
- root/area/users.tt
- root/components/entity-tabs.tt
- t/lib/t/MusicBrainz/Server/Controller/Area/Users.pm
I named the tab/page "Users" and not "Editors" to prevent confusion with "Edit" tab. Let me know if it shouldn't be like that.
> MBS-6511: List of editors in the area

- root/account/register.tt
- root/layout.tt
- root/layout/components/Footer.js
- root/main/index.tt
http://tickets.musicbrainz.org/browse/MBS-8841
Disclaimer: I didn't actually test this.
> MBS-8841: Update links to forums.

- lib/MusicBrainz/Server/Data/Editor.pm
This makes it so that if I say I'm from Chicago, I show up in the editors tab for Illinois (and USA) too.
> Respect area containments for MBS-6511

- lib/MusicBrainz/Server/Edit/Medium/Edit.pm
- t/lib/t/MusicBrainz/Server/Edit/Medium/Edit.pm
This is kinda masking the underlying problem, but at least edits won't get stuck anymore.
> Fail edit medium edits using cached deleted recordings (MBS-8858)

- HACKING.md
* Added a note about potential problems with loading of Wikimedia Commons images.
> Update for HACKING.md

- root/static/gulpfile.js
Prints out something when a file is added, changed, or unlinked, and when it's done rebuilding.
> Print gulp watch events

- admin/sql/updates/20160516-mbs-8656.sql
*Addition to #283. See [comment in JIRA](http://tickets.musicbrainz.org/browse/MBS-8288?focusedCommentId=35878&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#action_35878).*
> MBS-8288: Drop existing indexes on *_gid_redirect tables

- lib/MusicBrainz/Server/Controller/Admin.pm
- lib/MusicBrainz/Server/Form/User/EditProfile.pm
- root/admin/edit_user.tt
Tested by hand and it seems to work (inasmuch as I can test it since rika doesn't seem to send emails)
> MBS-6406: allow admins to skip the email verification process

- lib/MusicBrainz/Server/Controller/CDTOC.pm
- lib/MusicBrainz/Server/Controller/OAuth2.pm
- lib/MusicBrainz/Server/Controller/Root.pm
- lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
- lib/Sql.pm
- root/layout.tt
The read-only phase revealed some issues with the read-only mode. See the individual commits for details.
> Multiple issues with read-only mode (MBS-8943)

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
- Limit BookBrainz relationship to BookBrainz entity URLs
- Cleanup BookBrainz entity URLs (along with tests)
> MBS-8925: Limit BookBrainz relationship to BookBrainz URLs

- lib/MusicBrainz/Server/Data/Role/InsertUpdateDelete.pm
I think this should cover all the types which we added gids for.
> MBS-8959: Generate gids for admin-added types

- admin/EditEdit.pl
- lib/MusicBrainz/Server/Data/Edit.pm
Commits seem self-explanatory.
> Two small edit data fixes

- lib/MusicBrainz/Server/WebService/XMLSerializer.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupArtist.pm
Already fixed mmd-schema to recognize this.
> MBS-8968: Output gender MBIDs in /ws/2 XML

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
- Fix CPDL score `match` regular expression
- Add CPDL score `clean` function
- Update tests accordingly
> MBS-8985: Fix CPDL URLs matching and clean it up

- lib/MusicBrainz/Server/Data/WebService.pm
- lib/MusicBrainz/Server/WebService/Validator.pm
> MBS-8994: Allow &dismax=true in search queries

- INSTALL.md
This seems like a useful thing to mention, since so many people ask about it.
> Mention rate limiting and the search server in INSTALL.md

- root/static/scripts/edit/URLCleanup.js
Removes the whitelist as per http://tickets.musicbrainz.org/browse/STYLE-674
> MBS-9110: Remove the score whitelist

- lib/MusicBrainz/Server/WebService/JSONSerializer.pm
Makes Accept: application/json work for submissions.
> Added output_success() to the JSON serializer.

- lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Artist.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Label.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Role/ISNIs.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseArtists.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseLabels.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupArtist.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupLabel.pm
Seemed fairly straightforward. Did not add a role (as exists for the IPIs) because AFAIK only Artists have ISNIs.
> MBS-8762: JSON: Serialize the ISNIs for artist and labels.

- INSTALL.md
- cpanfile
- lib/MusicBrainz/Server.pm
- t/lib/t/MusicBrainz/Server/Data/CoreEntityCache.pm
- t/lib/t/MusicBrainz/Server/Data/Recording.pm
This is what I noticed when setting up a server, except the `npm` version issue is older, and the difficulty to change server types after the fact came up twice on IRC recently.
> Some fixes related to installation and tests

- lib/MusicBrainz/Server/Report/TracksWithSequenceIssues.pm
The `TracksWithSequenceIssues` report had a number of syntax errors in its SQL and therefore failed to run. Even if it had run, the third part of the test would have included all mediums with pre-gap tracks because it did not account for the additional track.
Rewrite the SQL for the WHERE clause to fix these problems. At the same time, remove the additional check that pre-gap tracks can only be used with certain medium types; while having pre-gap tracks on, e.g., vinyl is also wrong, this is a very different type of problem and should have its own report.
(Because the code from commit e002c4d4830502b314e42d178eba8f29ef8e1cd2 never actually worked, this can’t be considered a regression.)
> MBS-9136: Fix the TracksWithSequenceIssues report

- lib/MusicBrainz/Server/Entity/CDStub.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/2/CDStubTOC.pm
- lib/MusicBrainz/Server/WebService/XMLSerializer.pm
- t/lib/t/MusicBrainz/Server/WebService/Serializer/JSON/2/CDStubTOC.pm
Don't think this will impact any tests.
> MBS-9117: Serialize correct trackcount for CDStub.

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
Avoid adding a second slash at the end when there is one already
> MBS-9232: Fix Pinterest URL clean-up

- lib/MusicBrainz/Server/Controller/Statistics.pm
- lib/MusicBrainz/Server/Data/Statistics.pm
- root/statistics/index.tt
Collect and display distribution of labels by type. Fix [MBS-8168](https://tickets.metabrainz.org/browse/MBS-8168).
> MBS-8168: Add distribution of labels by type to /statistics

- lib/MusicBrainz/Server/Controller/Account.pm
- lib/MusicBrainz/Server/Controller/Admin.pm
- lib/MusicBrainz/Server/Data/Editor.pm
- lib/MusicBrainz/Server/Form/User/EditProfile.pm
- lib/MusicBrainz/Server/Form/User/Register.pm
- lib/MusicBrainz/Server/Form/Utils.pm
- root/account/edit.tt
- root/admin/edit_user.tt
Tested on local sandbox and it seems to work just fine, but let me know if something seems off!
> MBS-9135: Allow admins to modify usernames

- lib/MusicBrainz/Server/Controller/WS/2/URL.pm
This adds the same search interface the other entities have.
> MBS-9261: Handle URL search requests.

- root/components/medium.tt
Tiny fix for [MBS-9267](https://tickets.metabrainz.org/browse/MBS-9267).
> MBS-9267: Display works disambiguation comment in release page

- root/components/relationships-table.tt
Implement [MBS-9268](https://tickets.metabrainz.org/browse/MBS-9268), branched from PR #466.
> MBS-9268: Hide empty columns in relationships table

- root/components/relationships-table.tt
i.e. on
- Work overview page
- Artist relationships page
- Label relationships page
- Place performances page
> MBS-9255: Show recordings length in relationships tables

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
Baidu Baike introduced a new URL format which has to be validated as well.
Note: This new format does not replace/apply to previously existing URLs.
> MBS-9295: Update Baidu Baike URLs validation rule

- admin/ExportAllTables
- admin/InitDb.pl
- admin/MBImport.pl
- admin/replication/BundleReplicationPackets
- admin/replication/ImportReplicationChanges
- admin/replication/LoadReplicationChanges
- admin/replication/ProcessReplicationChanges
- entities.json
- lib/MusicBrainz/Script/MBDump.pm
- lib/MusicBrainz/Script/Utils.pm
- lib/MusicBrainz/Server/Constants.pm
- lib/MusicBrainz/Server/Role/FollowForeignKeys.pm
- lib/MusicBrainz/Server/Sitemap/Builder.pm
- lib/MusicBrainz/Server/Sitemap/Incremental.pm
- lib/MusicBrainz/Server/Sitemap/Overall.pm
- lib/MusicBrainz/Server/Sitemap/Utils.pm
- script/create_test_db.sh
- t/lib/t/MusicBrainz/Server/Sitemap.pm
- t/script/ExportAllTables.t
I haven't finished MBS-8736 yet, but that branch contains other useful refactoring which I'm just going to get out of the way and submit now. The "Factor out role to traverse FKs" commit in particular would now also be useful for creating a script that can generate a list of recently updated entities in our main web service (rather than for JSON-LD).
There's also a test for admin/ExportAllTables now, which is good to have.
> MBS-8736 prerequisites

- lib/MusicBrainz/Server/Form/Role/ToJSON.pm
- lib/MusicBrainz/Server/Form/Work.pm
- root/edit/details/add_work.tt
- root/static/scripts/relationship-editor/common/dialog.js
- root/static/scripts/work.js
Includes MBS-9338, so I'll hotfix this once it's accepted.
> Work languages fixes (including MBS-9338, MBS-9341, MBS-9345)

- lib/MusicBrainz/Server/Controller/WS/2/Event.pm
Just a simple typo in the code.
> MBS-8757: Fix WS browse-event-by-area requests.

- lib/MusicBrainz/Server/Controller/Collection.pm
- lib/MusicBrainz/Server/Controller/User.pm
- lib/MusicBrainz/Server/Form/User/EditProfile.pm
- root/account/edit.tt
- root/user/profile.tt
- t/lib/t/MusicBrainz/Server/Controller/User/Edit.pm
- [MBS-9353](https://tickets.metabrainz.org/browse/MBS-9353): Do not show collections or user profiles to people not logged in
- <s>[MBS-9354](https://tickets.metabrainz.org/browse/MBS-9354): Block `/collection` as per `robots.txt`</s> (see https://github.com/metabrainz/musicbrainz-server/pull/519#discussion_r120005672 instead)
- [MBS-9355](https://tickets.metabrainz.org/browse/MBS-9355): Do not allow limited user to set bio/link
> Reduce spammer motivation (MBS-9353, MBS-9354 MBS-9355)

- lib/MusicBrainz/Server/Entity/URL/YouTube.pm
https://tickets.metabrainz.org/browse/MBS-9434
> MBS-9434: change "watch" to "play" on YouTube

- docker/musicbrainz-tests/DBDefs.pm
- docker/musicbrainz-tests/chrome.service
- docker/musicbrainz-tests/run_tests.sh
- docker/musicbrainz-tests/template-renderer.service
- docker/musicbrainz-tests/website.service
- docker/templates/Dockerfile.tests.m4
- docker/templates/macros.m4
- package-lock.json
- package.json
- root/release/edit/tracklist.tt
- root/static/scripts/tests/react-macros.js
- root/static/scripts/tests/release-editor/trackParser.js
- t/create_test_db.t
- t/selenium.js
- t/selenium/Create_Account.html
- t/selenium/Log_In.html
- t/selenium/Log_Out.html
- t/selenium/MBS-7456.html
- t/sql/selenium.sql
Resurrects Selenium, but with a somewhat simpler setup. Allows for proper UI integration tests once again.
> Resurrect Selenium

- lib/MusicBrainz/Server/Constants.pm
- lib/MusicBrainz/Server/Data/Relationship.pm
- lib/MusicBrainz/Server/Edit/Relationship.pm
- root/components/relationship-editor.tt
- root/static/scripts/common/MB.js
- root/static/scripts/common/constants.js
I think this is all that needs doing. Tested manually by entering/editing a few relationships.
> MBS-9019, MBS-9459: Extend relationship credits to areas, places

- root/static/scripts/edit/URLCleanup.js
https://tickets.metabrainz.org/browse/MBS-9469
Unless I'm forgetting something that's all that is required? (I don't currently have a local DB set up for testing)
> MBS-9469: Add autoselect for VIAF for places

- lib/MusicBrainz/Server/Controller/Artist.pm
https://tickets.metabrainz.org/browse/MBS-9496
> MBS-9496: Modbot "AC being changed" edit note is confusing

- lib/MusicBrainz/Server/Data/Vote.pm
- root/components/common-macros.tt
- root/user/profile.tt
- t/lib/t/MusicBrainz/Server/Controller/User/Edit.pm
https://tickets.metabrainz.org/browse/MBS-9488 - I think I caught it all but I can't test stuff locally because no local DB.
> MBS-9488: Changing "Limited editor" to "Beginner"

- lib/MusicBrainz/Server/Translation.pm
- po/mb_server.et_EE.po
- po/update_translations.sh
Fix bug [MBS-9513](https://tickets.metabrainz.org/browse/MBS-9513) and move UI locale _Estonian (Estonia)_ to just _Estonia_ as requested by @reosarevok.
> MBS-9513: Fix UI locale with country code

- root/static/scripts/edit/externalLinks.js
- root/static/styles/forms.less
> MBS-9515: Block anchors in new Wikipedia URLs

- root/static/scripts/edit/URLCleanup.js
https://tickets.metabrainz.org/browse/MBS-9560
AFAICT this is the only change this requires, but shout if I'm wrong!
> MBS-9560: Add http://laboiteauxparoles.com/ to the lyrics whitelist

- .flowconfig
- package-lock.json
- package.json
- root/components/forms.js
- root/entity/tags.tt
- root/layout/sidebar/sidebar-tags.tt
- root/static/scripts/common/components/TagEditor.js
- root/static/scripts/common/components/TagLink.js
- root/types.js
immutable-js had to be updated because the old version can't type Records properly. Not sure when it'll go out of RC, it's been months already.
> Add flow types to the tag editor

- root/static/scripts/release-editor/trackParser.js
https://tickets.metabrainz.org/browse/MBS-9575
> MBS-9575: Make vinyl track numbers opt-in for new users in track parser

- lib/MusicBrainz/Server/Report/ReleasesMissingDiscIDs.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/index.tt
- root/report/releases_missing_disc_ids.tt
Just some small grammar, whitespace, and capitalization fixes.
> Small disc ID report fixes

- root/static/scripts/guess-case/modes.js
- root/static/scripts/tests/GuessCase.js
Add regex to `runPostProcess` for French mode, plus tests.
> MBS-5345: Enhance French capitalization

- root/static/scripts/guess-case/modes.js
- root/static/scripts/tests/GuessCase.js
This is a resubmission of PR #594 mistakenly merged (by me) without tests completion.
- Code change commit from @naiveaiguy is untouched.
- Test commit from @naiveaiguy is the same, except it doesn’t contain the faulty test (requested by me) which is replaced in a distinct third commit.
>  MBS-5345: Enhance French guess-case for short noun phrases

- lib/MusicBrainz/Server.pm
- lib/MusicBrainz/Server/Data/WebService.pm
- lib/MusicBrainz/Server/Log.pm
- lib/MusicBrainz/Server/Validation.pm
Commits should be fairly self-explanatory.
> Log improvements

- .babelrc
- .eslintrc.yaml
- package.json
- root/components/forms.js
- root/layout/components/ExternalLinks.js
- root/layout/components/Footer.js
- root/layout/components/Head.js
- root/static/scripts/common/components/EntityLink.js
- root/static/scripts/edit/components/ArtistCreditBubble.js
- root/static/scripts/edit/components/ArtistCreditEditor.js
- root/static/scripts/edit/components/forms.js
- yarn.lock
It can't be typed properly with Flow, so it just makes development harder and gets in our way of refactoring things.
> Remove jsx-control-statements

- .eslintrc.yaml
- package.json
- yarn.lock
Addresses some behavior I've noticed where it warns or errors about things which I believe should be allowed.
I'd like our `.eslintrc` to be normative, so if you see it complain about anything else which is silly or invalid, further patches would be welcome. :)
> Eslint updates

- admin/nginx/mbserver-rewrites.conf
Will need a manual update once merged into `master`.
> MBS-9671: Redirect /index.html to /

- admin/sql/CreateConstraints.sql
- admin/sql/updates/20180331-mbs-9664-non-loop-checks.sql
- upgrade.json
> MBS-9664: Add database constraints to disallow loop relationship

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
https://tickets.metabrainz.org/browse/MBS-9639
> MBS-9639: Extend Soundcloud relationship to places

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
https://tickets.metabrainz.org/browse/MBS-9692
> MBS-9692: Normalize UtaiteDB and VocaDB URLs to use HTTPS

- root/layout/components/BottomMenu.js
Requested by ruaok in #metabrainz
> Add link to redbubble shop from about menu

- lib/MusicBrainz/Server/Constants.pm
- root/static/scripts/common/constants.js
- t/lib/t/MusicBrainz/Server/Data/Relationship.pm
https://tickets.metabrainz.org/browse/MBS-9630
Tested manually locally, seems to work.
> MBS-9630: adding credits for label rels

- docker/templates/DBDefs.pm.ctmpl
It is currently defined as CODE_DEF. It should be STRING_DEF.
> Fix consul template definition for DB_STAGING_SERVER_DESCRIPTION

- root/components/common-macros.tt
- root/statistics/languages_scripts.tt
https://tickets.metabrainz.org/browse/MBS-9755
> MBS-9755: Fix unknown search link for script stats

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
TouhouDB regex should be touhoudb.com, not touhoudb.net
> Fix TouhouDB URL handler (.com instead of .net) originally added for MBS-9694

- lib/MusicBrainz/Server/Data/Recording.pm
- lib/MusicBrainz/Server/Data/Search.pm
- lib/MusicBrainz/Server/Data/WebService.pm
According to https://github.com/metabrainz/mb-solr-cloud/pull/2#issuecomment-413768128
> Solr edismax endpoint was renamed to advanced

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
See [comment to MBS-9742](https://tickets.metabrainz.org/browse/MBS-9742?focusedCommentId=46853#comment-46853)
> MBS-9742(ter): Allow LC Authority File URL for Place

- INSTALL.md
Sample DB is very useful IMO for developing. Submodule issues might happen if someone (talking about a friend here) forgets the "--recursive" option when cloning and it makes sense IMO to quickly mention the easy solution to those.
> Update INSTALL.md to mention sample DB and issues with submodules

- lib/MusicBrainz/Server/Data/Search.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/js/Autocomplete.pm
As per @mwiencek, this is what was missing for the dates to show up on label direct search (and of course, it works)
> MBS-9804: Load dates for (direct) label search

- docs/CodingStyle.pod
I have removed several grammatical errors.
> Grammatical errors removed.

- root/layout/components/sidebar/CollectionLinks.js
https://tickets.metabrainz.org/browse/MBS-9889
> MBS-9889: Fix collection link on sidebar

- root/static/scripts/edit/URLCleanup.js
https://tickets.metabrainz.org/browse/MBS-9892
> MBS-9892: Allow Amazon Australia links

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
https://tickets.metabrainz.org/browse/MBS-9901
Dailymotion itself redirects to https nowadays.
> MBS-9901: Change Dailymotion cleanup to https

- t/selenium.js
The previous code tried to proxy all requests to `WEB_SERVER`, even if they were intended for a different host (e.g. gravatar.com, the webpack dev server at localhost:8080). `WEB_SERVER` would then 404.
This is cherry-picked from the Webpack PR.
> Proxy requests correctly in t/selenium.js

- lib/MusicBrainz/Server/Entity/Util/JSON.pm
- root/components/Paginator.js
Those warnings were harmless but to logs size.
> Fix some warnings from search result pages

- root/utility/releaseGroupType.js
https://tickets.metabrainz.org/browse/MBS-9986
> MBS-9986: Fix RG types not being translated on sidebar

- lib/MusicBrainz/Server/Entity/ReleaseGroup.pm
- root/static/scripts/common/MB/Control/Autocomplete.js
- root/types.js
https://tickets.metabrainz.org/browse/MBS-9943
Change-Id: If3f1fa6982f8c809f49211c0030d840e130c5559
> MBS-9943: Make Autocomplete.js translatable

- root/layout/components/sidebar/LastUpdated.js
- root/types.js
https://tickets.metabrainz.org/browse/MBS-9985
Change-Id: Icb6fb511010adc094a1b38b65debd25ca4af3915
> MBS-9985: Edit LastUpdated to deal with null "dates"

- lib/MusicBrainz/Server/Controller/Role/Alias.pm
- root/release_group/ReleaseGroupAliases.js
- root/release_group/ReleaseGroupLayout.js
- root/release_group/aliases.tt
Change-Id: I413df4ab3d022ebd2d9d0dba1f4bd0836cb6f136
> MBS-9849 (IV): Port RG Alias tab to React

- po/extract_pot_db
https://tickets.metabrainz.org/browse/MBS-9991
> MBS-9991: Make relationship type names translatable

- root/search/components/PaginatedSearchResults.js
- root/search/components/SearchForm.js
- root/static/scripts/tests/Control/URLCleanup.js
- root/static/scripts/tests/CoverArt.js
- root/static/scripts/tests/GuessCase.js
- root/static/scripts/tests/autocomplete.js
- root/static/scripts/tests/common/immutable-entities.js
- root/static/scripts/tests/edit.js
- root/static/scripts/tests/entity.js
- root/static/scripts/tests/external-links-editor/utils.js
- root/static/scripts/tests/guessFeat.js
- root/static/scripts/tests/i18n.js
- root/static/scripts/tests/i18n/expand2.js
- root/static/scripts/tests/relationship-editor.js
- root/static/scripts/tests/release-editor/actions.js
- root/static/scripts/tests/release-editor/common.js
- root/static/scripts/tests/release-editor/dialogs.js
- root/static/scripts/tests/release-editor/edits.js
- root/static/scripts/tests/release-editor/fields.js
- root/static/scripts/tests/release-editor/trackParser.js
- root/static/scripts/tests/release-editor/utils.js
- root/static/scripts/tests/release-editor/validation.js
- root/static/scripts/tests/utility.js
> MBS-9936: Move from CJS style to ES6 (imports, exports) (III)

- script/database_configuration
The password on my development DB has some non-friendly shell characters in it.
>  Shell-quote database_configuration output

- script/setup_development_db.sh
- t/lib/t/MusicBrainz/Server/Controller/Release/AddCoverArt.pm
- t/lib/t/MusicBrainz/Server/Controller/Release/ReorderCoverArt.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/js/CoverArtUpload.pm
- t/lib/t/MusicBrainz/Server/Data/Artwork.pm
- t/lib/t/MusicBrainz/Server/Data/CoverArtArchive.pm
- t/sql/caa.sql
- t/sql/cover_art_types.sql
- t/sql/initial.sql
- t/sql/release.sql
- t/sql/webservice.sql
> Move image_type inserts to t/sql/initial.sql

- package.json
- root/components/common-macros.tt
- root/layout/components/sidebar/AreaSidebar.js
- root/layout/components/sidebar/ArtistSidebar.js
- root/layout/components/sidebar/EventSidebar.js
- root/layout/components/sidebar/InstrumentSidebar.js
- root/layout/components/sidebar/LabelSidebar.js
- root/layout/components/sidebar/PlaceSidebar.js
- root/layout/components/sidebar/SeriesSidebar.js
- root/layout/components/sidebar/WorkSidebar.js
- root/static/scripts/common/components/CommonsImage.js
- root/static/scripts/common/components/WikipediaExtract.js
- root/static/scripts/edit/components/ArtistCreditEditor.js
- yarn.lock
Just trying to not lag too far behind before it becomes a pain to update.
There should be no breaking changes for us. There are a ton of bug fixes, a few new features, and a couple fixed vulnerabilities.
> Bump React to 16.7.0

- lib/MusicBrainz/Server/Controller/Statistics.pm
- root/statistics/NoStatistics.js
- root/statistics/StatisticsLayout.js
- root/statistics/no_statistics.tt
Layout + NoStatistics
Part 1 from https://github.com/metabrainz/musicbrainz-server/pull/609/
>  MBS-9632: Convert Stats to React (I+II)

- lib/DBDefs.pm.sample
- lib/MusicBrainz/Script/JSONDump.pm
- lib/MusicBrainz/Script/Role/TestCacheNamespace.pm
- lib/MusicBrainz/Server/Sitemap/Incremental.pm
- lib/MusicBrainz/Server/Sitemap/Overall.pm
This is the logical follow-up to d26c649.
> Set CACHE_NAMESPACE during JSONDump/Sitemap tests

- root/elections/ElectionDetails.js
- root/elections/ElectionTable/ElectionTableRows.js
https://tickets.metabrainz.org/browse/MBS-9995
I don't have any election data to test this with locally, but it should be trivial enough.
> MBS-9995: Add missing space between election status and date

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
as requested in comment to MBS-9742, https://tickets.metabrainz.org/browse/MBS-9742
> MBS-9742 (from comment):  Allow LC Authority File URL for Label

- root/static/scripts/edit/URLCleanup.js
Step one of many of making this less messy
Includes the tiny one line from https://github.com/metabrainz/musicbrainz-server/pull/840 since it's the same file and I fully expect that to be merged way before this :)
> Run eslint --fix on URLCleanup

- root/static/scripts/release-editor/actions.js
- root/static/scripts/release-editor/bindingHandlers.js
- root/static/scripts/release-editor/bubbles.js
- root/static/scripts/release-editor/dialogs.js
- root/static/scripts/release-editor/duplicates.js
- root/static/scripts/release-editor/edits.js
- root/static/scripts/release-editor/fields.js
- root/static/scripts/release-editor/init.js
- root/static/scripts/release-editor/recordingAssociation.js
- root/static/scripts/release-editor/seeding.js
- root/static/scripts/release-editor/trackParser.js
- root/static/scripts/release-editor/utils.js
- root/static/scripts/release-editor/validation.js
- root/static/scripts/release-editor/viewModel.js
- root/static/scripts/tests/release-editor/actions.js
Release editor
This is messier than previous ones so it'll require more review.
> MBS-9936: Move from CJS style to ES6 (imports, exports) (IV)

- root/static/scripts/common/i18n.js
This is cherry-picked from #801.
> Run eslint on i18n.js

- root/static/scripts/tests/Control/URLCleanup.js
Includes #840 since it touches the same file and I fully expect that to be merged before this :)
> Eslint fixes for URLCleanup test

- root/static/scripts/common/utility/formatDatePeriod.js
This is cherry-picked from #801.
> Add Flow types to formatDatePeriod

- root/layout/components/BottomMenu.js
- root/layout/components/Footer.js
- root/layout/components/Head.js
- root/layout/components/MergeHelper.js
- root/layout/components/MetaDescription.js
- root/layout/components/Search.js
- root/layout/components/TopMenu.js
- root/layout/components/sidebar/CollectionSidebar.js
- root/layout/components/sidebar/ReleaseSidebar.js
- root/layout/components/sidebar/SidebarRating.js
- root/layout/components/sidebar/WorkSidebar.js
Ran this since I was seeing a few easy-to-fix errors and warnings here
> /layout/components eslint

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
https://tickets.metabrainz.org/browse/MBS-9998
This will clash with some of my other open PRs, depending on what gets merged first - I'll just fix any PRs that need fixing :)
> MBS-9998: Remove unneeded /pg/ section on Facebook URLs

- root/static/scripts/edit/URLCleanup.js
The diff is a mess, but basically: I just collapsed every object in CLEANUPS in my IDE, then put them in the right order (while collapsed so that they moved as a block).
> URLCleanup eslint fixes: fix key sort for CLEANUPS

- lib/MusicBrainz/Server/Controller/Role/Details.pm
- lib/MusicBrainz/Server/Controller/Role/Tag.pm
- root/area/AreaLayout.js
- root/static/scripts/common/components/EntityLink.js
- root/static/scripts/common/i18n/localizeAreaName.js
- root/utility/chooseLayoutComponent.js
https://tickets.metabrainz.org/browse/MBS-10005
> MBS-10005 (I): Use React Details and Tags tabs for area

- lib/MusicBrainz/Server/Controller/Role/Details.pm
- lib/MusicBrainz/Server/Controller/Role/Tag.pm
- root/event/EventLayout.js
- root/utility/chooseLayoutComponent.js
https://tickets.metabrainz.org/browse/MBS-10005
> MBS-10005 (III): Use React Details and Tags tabs for event

- root/edit/components/Vote.js
https://tickets.metabrainz.org/browse/MBS-9893
These were dropped with https://github.com/metabrainz/musicbrainz-server/commit/af16d01b7755020fda19946339c0e2602c772739#diff-29d2b5df055ec08b310c1090bb7b4ae7 for some reason but the EditList code for batch voting depends on them.
> MBS-9893: Readd missing attributes to fix EditList batch voter

- lib/MusicBrainz/Server/Controller/Role/Details.pm
- lib/MusicBrainz/Server/Controller/Role/Tag.pm
- root/utility/chooseLayoutComponent.js
- root/work/WorkLayout.js
https://tickets.metabrainz.org/browse/MBS-10005
> MBS-10005 (VIII): Use React Details and Tags tabs for work

- root/layout/components/sidebar/ReleaseSidebar.js
- root/layout/components/sidebar/SidebarType.js
https://tickets.metabrainz.org/browse/MBS-10009
> MBS-10009: Fix untranslated sidebar types

- root/edit/details/AddAnnotation.js
- root/static/scripts/common/components/Annotation.js
- root/types.js
As suggested in https://github.com/metabrainz/musicbrainz-server/pull/879#discussion_r253324735
> MBS-10007: Create specific Flow type for Add Annotation edits

- lib/MusicBrainz/Server/Controller/Artist.pm
- root/artist/CannotSplit.js
- root/artist/cannot_split.tt
https://tickets.metabrainz.org/browse/MBS-10017
> MBS-10017: Convert artist/cannot_split.tt to React

- root/static/scripts/common/ratings.js
- root/utility/escapeClosingTags.js
- root/utility/formatUserDate.js
- root/utility/ratingTooltip.js
- root/utility/uriWith.js
> MBS-9936: Move from CJS style to ES6 (imports, exports) (VII)

- root/user/report.tt
<https://tickets.metabrainz.org/browse/MBS-10035>
I'm not sure about any (coding) style I need to adhere to for this, so please let me know of any changes I may need to make.
> MBS-10035: Add text to "report user" page asking for links

- lib/MusicBrainz/Server/Data/Event.pm
- lib/MusicBrainz/Server/Data/Work.pm
- root/components/EventsList.js
- root/static/scripts/common/components/ArtistRoles.js
- root/static/scripts/common/i18n/localizeArtistRoles.js
https://tickets.metabrainz.org/browse/MBS-10021
> MBS-10021: Make artist roles translatable

- root/static/scripts/guess-case/MB/Control/GuessCase.js
- root/static/scripts/guess-case/MB/GuessCase/Handler/Area.js
- root/static/scripts/guess-case/MB/GuessCase/Handler/Artist.js
- root/static/scripts/guess-case/MB/GuessCase/Handler/Base.js
- root/static/scripts/guess-case/MB/GuessCase/Handler/Label.js
- root/static/scripts/guess-case/MB/GuessCase/Handler/Place.js
- root/static/scripts/guess-case/MB/GuessCase/Handler/Release.js
- root/static/scripts/guess-case/MB/GuessCase/Handler/Track.js
- root/static/scripts/guess-case/MB/GuessCase/Handler/Work.js
- root/static/scripts/guess-case/MB/GuessCase/Input.js
- root/static/scripts/guess-case/MB/GuessCase/Main.js
- root/static/scripts/guess-case/MB/GuessCase/Output.js
- root/static/scripts/guess-case/flags.js
- root/static/scripts/guess-case/modes.js
- root/static/scripts/guess-case/utils.js
- root/static/scripts/work.js
> MBS-9936: Move from CJS style to ES6 (imports, exports) (VIII)

- root/collection/index.tt
- root/components/EventsList.js
- root/components/LabelsList.js
- root/components/SortableTableHeader.js
https://github.com/metabrainz/musicbrainz-server/pull/895 got merged before I could add the things I found out during https://github.com/metabrainz/musicbrainz-server/pull/894 - so doing it here. The sortable bit isn't too important, but as it is label collections are just broken in master, so let's get this merged before we release any of this? :)
> MBS-10026 fixup

- root/static/scripts/relationship-editor/generic.js
https://tickets.metabrainz.org/browse/MBS-9013
> MBS-9013: Removing specific ordering of relationships doesn't create an edit

- root/static/scripts/common/components/Annotation.js
- root/static/scripts/common/components/AreaContainmentLink.js
- root/static/scripts/common/components/AreaWithContainmentLink.js
- root/static/scripts/common/components/ArtistRoles.js
- root/static/scripts/common/components/Autocomplete.js
- root/static/scripts/common/components/CritiqueBrainzReview.js
- root/static/scripts/common/components/DescriptiveLink.js
- root/static/scripts/common/components/EditorLink.js
- root/static/scripts/common/components/EntityLink.js
- root/static/scripts/common/components/TagEditor.js
- root/static/scripts/common/components/TagLink.js
- root/static/scripts/common/components/WikipediaExtract.js
Fixes most basic eslint issues. Eslint really dislikes we're declaring multiple classes in TagEditor, but I haven't touched that for now.
> Eslint fixes for script/common/components

- lib/MusicBrainz/Server/Entity/URL/AnisonGeneration.pm
https://tickets.metabrainz.org/browse/MBS-10045
> MBS-10045: Remove force https for Anison (https not supported)

- .eslintrc.yaml
- package.json
- yarn.lock
This fixes the issue referenced at https://github.com/metabrainz/musicbrainz-server/pull/952#discussion_r260594372
I updated the deps first to see if it was a bug that got fixed (TBH, the behavior without this configuration still seems inconsistent to me and might be a bug, but at least adding the config fixes it). Although updating stuff didn't help, it doesn't hurt to get any other bug fixes the updates have.
> Bump eslint deps and fix indent issue

- root/search/components/AnnotationResults.js
- root/search/components/AreaResults.js
- root/search/components/ArtistResults.js
- root/search/components/CDStubResults.js
- root/search/components/DocResults.js
- root/search/components/EventResults.js
- root/search/components/InstrumentResults.js
- root/search/components/LabelResults.js
- root/search/components/PaginatedSearchResults.js
- root/search/components/PlaceResults.js
- root/search/components/RecordingResults.js
- root/search/components/ReleaseGroupResults.js
- root/search/components/ReleaseResults.js
- root/search/components/ResultsLayout.js
- root/search/components/SearchForm.js
- root/search/components/SeriesResults.js
- root/search/components/WorkResults.js
- root/search/types.js
While checking my old code for examples of form implementation I figured out there were a bunch of unused vars and stuff. This fixes that and makes eslint happy.
> Eslint fixes for search/

- lib/MusicBrainz/Server/Controller/Tag.pm
- t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
https://tickets.metabrainz.org/browse/MBS-7463
> MBS-7463: Add redirect from /tag to /tags

- script/xgettext.js
following the switch to Webpack in commit 1c9f19ef16fdc2faf09fc59f0bf2255a0ac78019.
> Use Babel plugin dynamic import in xgettext.js

- flow-typed/npm/lodash_v4.x.x.js
- root/components/EntityHeader.js
- root/components/ReleaseCatnoList.js
- root/components/ReleaseLabelList.js
- root/layout/components/sidebar/AttendanceLinks.js
- root/layout/components/sidebar/CDStubSidebar.js
- root/layout/components/sidebar/CollectionLinks.js
- root/layout/components/sidebar/PlaceSidebar.js
- root/layout/components/sidebar/ReleaseSidebar.js
- root/static/scripts/account/components/PreferencesForm.js
- root/utility/age.js
- root/utility/subfieldErrors.js
- t/lib/t/MusicBrainz/Server/Controller/Area/Tags.pm
Only one I couldn't fix was in root/static/scripts/common/components/CodeLink.js
> Fix a bunch of $FlowFixMes

- root/static/scripts/release-editor/fields.js
I expected there'd be more needed but this seems to be the only one at the moment. Still making a quick PR to make sure we do want to make the change :)
> Eslint fix for no-unneeded-ternary

- root/main/index.js
https://tickets.metabrainz.org/browse/MBS-10080
> MBS-10080: MusicBrainz blog is now the MetaBrainz blog

- root/static/scripts/area/places-map.js
- root/static/scripts/common/MB/Control/Autocomplete.js
- root/static/scripts/common/coverart.js
- root/static/scripts/common/tagger.js
- root/static/scripts/global.js
- root/static/scripts/place.js
- root/static/scripts/series.js
- root/static/scripts/statistics.js
- root/static/scripts/tests/react-macros.js
- root/static/scripts/timeline.js
- root/static/scripts/url.js
- root/static/scripts/voting.js
- root/static/scripts/work.js
Final missing bits
https://tickets.metabrainz.org/browse/MBS-9936
As far as I can tell, this should be the last part of this. Anything I've missed can be pointed out for me to fix now with this PR, or we can just fix it as we see it in the future :)
> MBS-9936: Move from CJS style to ES6 (imports, exports) (X)

- .eslintrc.yaml
- lib/MusicBrainz/Server/Controller/Admin/Attributes.pm
- lib/MusicBrainz/Server/Entity/MediumFormat.pm
- root/admin/attributes/Attribute.js
- root/admin/attributes/Index.js
- root/admin/attributes/Language.js
- root/admin/attributes/Script.js
- root/layout/components/sidebar/SidebarType.js
- root/report/RecordingsSameNameDifferentArtistsSameName.js
- root/server/components.js
- root/static/scripts/common/i18n.js
- root/static/scripts/common/i18n/expand2.js
- root/static/scripts/common/i18n/expand2react.js
- root/types.js
I took too long to review #979, so submitting my suggested changes as a PR.
As luck would have it, when I was doing b95f79700d1d980f5faffff1a304ecbb8790ce57 I ran into a crazy Flow issue which made some unrelated and previously-invisible errors visible. I fixed them all in a084116e999c86f6edac0d179ec1ac7bab47add6 and 9a5bad2538d494cb4e2edfe05fa50614a97df74f.
> MBS-10086 tweaks

- root/edit/index.tt
- root/edit/list.tt
- root/release/edit/tracklist.tt
- t/lib/t/MusicBrainz/Server/Data/Collection.pm
- t/lib/t/MusicBrainz/Server/Edit/ReleaseGroup/SetCoverArt.pm
> Fixing all cases of 'occured' to 'occurred'

- lib/MusicBrainz/Server/Edit/Work/Create.pm
- lib/MusicBrainz/Server/Edit/Work/Edit.pm
https://tickets.metabrainz.org/browse/MBS-10063
> MBS-10063: Create and edit work edits should display [No lyrics] for zxx

- lib/MusicBrainz/Server/Report/SuperfluousDataTracks.pm
- root/report/SuperfluousDataTracks.js
https://tickets.metabrainz.org/browse/MBS-9932
Chose to just update it.
To be reviewed and merged after https://github.com/metabrainz/musicbrainz-server/pull/934
> MBS-9932: Update "Releases with superfluous data tracks" report

- root/report/AnnotationsArtists.js
- root/report/AnnotationsLabels.js
- root/report/AnnotationsPlaces.js
- root/report/AnnotationsRecordings.js
- root/report/AnnotationsReleaseGroups.js
- root/report/AnnotationsReleases.js
- root/report/AnnotationsSeries.js
- root/report/AnnotationsWorks.js
- root/report/constants.js
https://tickets.metabrainz.org/browse/MBS-9935
To be reviewed and merged after https://github.com/metabrainz/musicbrainz-server/pull/934
> MBS-9935: Indicate what to do with annotation reports

- lib/MusicBrainz/Server/Controller/Role/Details.pm
- lib/MusicBrainz/Server/Controller/Search.pm
- root/entity/Details.js
- root/search/components/ResultsLayout.js
https://tickets.metabrainz.org/browse/MBS-10081
> MBS-10081: formatUserDate needs datetime_to_iso8601(last_updated)

- root/search/components/ReleaseResults.js
https://tickets.metabrainz.org/browse/MBS-10074
> MBS-10074: '-' on release search format/tracks if no medium exists

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
https://tickets.metabrainz.org/browse/MBS-10101
https://tickets.metabrainz.org/browse/MBS-9082
I still suck at regexes, so please take a good look at those :)
>  MBS-10101 / MBS-9082: SecondHandSongs cleanup and autoselect additions

- lib/MusicBrainz/Server/Data/Area.pm
- lib/MusicBrainz/Server/Data/Artist.pm
- lib/MusicBrainz/Server/Data/Editor.pm
- lib/MusicBrainz/Server/Data/Event.pm
- lib/MusicBrainz/Server/Data/Label.pm
- lib/MusicBrainz/Server/Data/Place.pm
- lib/MusicBrainz/Server/Data/Statistics.pm
- lib/MusicBrainz/Server/Data/Utils.pm
For the purposes of artist/label country statistics, count these entities as being of a particular country by their containing area, not just from being linked directly.
Here are the results of the new query for artists, from queen: https://gist.github.com/mwiencek/44dd9858ac81235a2b427d6f08ff9e51
> MBS-10102: Artist/label containing country stats

- lib/MusicBrainz/Server/Data/Relationship.pm
- lib/MusicBrainz/Server/Entity/LinkAttributeType.pm
- lib/MusicBrainz/Server/Entity/LinkType.pm
- lib/MusicBrainz/Server/Entity/LinkTypeAttribute.pm
- lib/MusicBrainz/Server/Entity/Relationship.pm
- root/components/StaticRelationshipsDisplay.js
- root/static/scripts/common/linkedEntities.js
- root/static/scripts/edit/utility/linkPhrase.js
- root/static/scripts/relationship-editor/common/fields.js
- root/types.js
- root/utility/groupRelationships.js
This PR fixes [MBS-10111](https://tickets.metabrainz.org/browse/MBS-10111) and various other display issues I ran into while trying to fix that.
> Fix relationship display issues (inc. MBS-10111)

- root/static/scripts/edit/utility/guessFeat.js
This should solve https://sentry.metabrainz.org/metabrainz/musicbrainz-server/issues/60198/
It also solves the ACs not updating on the release editor, with the same hack as https://github.com/metabrainz/musicbrainz-server/pull/1025
This does *not* fix https://tickets.metabrainz.org/browse/MBS-10137 - which is already in prod and seems to require larger fixes.
> Name guessFeat function so it can be called in the same file

- admin/sql/CreateTables.sql
- admin/sql/updates/20190422-mbs-1658-collection-text.sql
- admin/sql/updates/schema-change/25.slave.sql
- upgrade.json
SQL for https://tickets.metabrainz.org/browse/MBS-1658
> MBS-1658 (SQL): Add free comment field to collection entries

- root/static/scripts/release-editor/actions.js
https://tickets.metabrainz.org/browse/MBS-10149
Another of the same issue as https://github.com/metabrainz/musicbrainz-server/pull/1025
> MBS-10149: Update displayed track ACs when swapping artist/title

- lib/MusicBrainz/Server/Controller/CDTOC.pm
https://tickets.metabrainz.org/browse/MBS-10146
> MBS-10146: Load number of releases in RG for header

- root/static/styles/statistics.less
> MBS-10153: Fix stats table icon URLs

- lib/MusicBrainz/Server/Controller/Area.pm
- root/area/AreaIndex.js
- root/area/index.tt
- root/server/components.js
https://tickets.metabrainz.org/browse/MBS-10104
> MBS-10104: Convert the area index page to React

- lib/MusicBrainz/Server/Entity/URL/YouTube.pm
- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
https://tickets.metabrainz.org/browse/MBS-10160
It's unclear to me ATM if we should just clean those up to remove /c/ (the one case I tried worked without it), but this shouldn't hurt in the meantime.
> MBS-10160: Display username on sidebar for youtube/c/ links

- docker/templates/Dockerfile.webservice.m4
- lib/MusicBrainz/Server/Controller/WS/2.pm
- lib/MusicBrainz/Server/ControllerBase/WS/2.pm
- lib/MusicBrainz/Server/ControllerBase/WS/js.pm
- lib/MusicBrainz/Server/WebService/Validator.pm
- t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
Fixes https://tickets.metabrainz.org/browse/MBS-8826 plus an issue related to the git_info script failing.
> WS container fixes

- lib/MusicBrainz/Server/Controller/WS/js.pm
https://tickets.metabrainz.org/browse/MBS-10167
Also fixed https://tickets.metabrainz.org/browse/MBS-10171 which I found when testing, let me know if that looks right.
> MBS-10167: Display the right medium position when reusing existing media

- lib/MusicBrainz/Server/Form/Collection.pm
https://tickets.metabrainz.org/browse/MBS-10148
> MBS-10148: Allow changing empty collection to any type

- lib/MusicBrainz/Server/Controller/WS/2/Recording.pm
- lib/MusicBrainz/Server/Data/Recording.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/BrowseRecordings.pm
https://tickets.metabrainz.org/browse/MBS-10124
> MBS-10124: Allow to browse recordings by work

- lib/MusicBrainz/Server/Constants.pm
- lib/MusicBrainz/Server/Entity/Language.pm
- lib/MusicBrainz/Server/Form/Admin/Attributes/Language.pm
- lib/MusicBrainz/Server/Form/Admin/Attributes/Script.pm
- root/admin/attributes/Language.js
- root/admin/attributes/Script.js
- root/admin/attributes/form.tt
- root/relationship/linkattributetype/form.tt
- root/relationship/linktype/form.tt
- root/user/contact.tt
https://tickets.metabrainz.org/browse/MBS-10100
This might not be the right way to do this (it works here, but it might break something else). If so, please do let me know what would be the right way - Perl forms still confuse me.
Also includes https://tickets.metabrainz.org/browse/MBS-10210 and https://tickets.metabrainz.org/browse/MBS-10215
> MBS-10100: Don't require non-required fields for language

- root/artist/edit_form.tt
https://tickets.metabrainz.org/browse/MBS-10217
> MBS-10217: Explain AC renaming in artist/edit_form

- root/static/scripts/guess-case/utils.js
- root/static/scripts/tests/GuessCase.js
https://tickets.metabrainz.org/browse/MBS-8867
All eslint fixes except for the first commit (+7|-1) and the last one (which just fixes a couple typos etc in comment strings)
> MBS-8867: Don't uppercase "C'mon"

- root/recording/edit_form.tt
https://tickets.metabrainz.org/browse/MBS-10139
> MBS-10139: Indicate why recording length can't be edited

- lib/MusicBrainz/Server/Controller/Artist.pm
- root/artist/index.tt
https://tickets.metabrainz.org/browse/MBS-10222
Also includes a commit for https://tickets.metabrainz.org/browse/MBS-8569 and one for https://tickets.metabrainz.org/browse/MBS-10224
> MBS-10222: Show legal name aliases of legal name artist

- root/release/caa_darkened.tt
- root/release/cover_art.tt
https://tickets.metabrainz.org/browse/MBS-10218
> MBS-10218: Fix page param (cover_art -> cover-art)

- root/edit/cancel.tt
https://tickets.metabrainz.org/browse/MBS-10233
> MBS-10233: Use React templates when canceling edit

- lib/MusicBrainz/Server/Report/PossibleCollaborations.pm
- root/report/PossibleCollaborations.js
https://tickets.metabrainz.org/browse/MBS-9981
https://tickets.metabrainz.org/browse/MBS-10278
> MBS-9981 / MBS-10278: PossibleCollaborations improvements

- lib/MusicBrainz/Server/EditSearch/Predicate/Role/Subscribed.pm
- root/edit/search_macros.tt
- root/static/scripts/common/MB/edit_search.js
https://tickets.metabrainz.org/browse/MBS-2663
I don't quite understand how the whole edit search code works yet, so let me know if something feels weird - but I tested it and it seems to work fine.
> MBS-2663: Search edits by non-subscribed entity

- lib/MusicBrainz/Server/Controller/ReleaseEditor.pm
https://tickets.metabrainz.org/browse/MBS-1679
> MBS-1679: Hide Merge Process in release editor

- lib/MusicBrainz/Server/Data/Search.pm
https://tickets.metabrainz.org/browse/MBS-10162
> MBS-10162: Use aliases in release/RG/recording direct search

- lib/MusicBrainz/Server/Controller/WS/2/Recording.pm
https://tickets.metabrainz.org/browse/MBS-8521
> MBS-8521: work-level-rels for recording browse

- lib/MusicBrainz/Server/Controller/WS/2/DiscID.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupDiscID.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupDiscID.pm
https://tickets.metabrainz.org/browse/MBS-10143
> MBS-10143: Allow querying for tags/genres on discid ws requests

- root/components/list/AreaList.js
- root/components/list/ArtistList.js
- root/components/list/EventList.js
- root/components/list/InstrumentList.js
- root/components/list/LabelList.js
- root/components/list/PlaceList.js
- root/components/list/RecordingList.js
- root/components/list/ReleaseGroupList.js
- root/components/list/ReleaseList.js
- root/components/list/SeriesList.js
- root/components/list/WorkList.js
- root/release_group/ReleaseGroupIndex.js
- root/static/styles/layout.less
https://tickets.metabrainz.org/browse/MBS-10273
This was accidentally dropped when converting to React.
> MBS-10273: Readd missing "pos" class to ReleaseGroupList

- root/recording/RecordingIndex.js
https://tickets.metabrainz.org/browse/MBS-10336
> MBS-10336: Clarify disc#.track# cell in recording page

- lib/MusicBrainz/Server/Controller/Artist.pm
- root/artist/recordings.tt
https://tickets.metabrainz.org/browse/MBS-10337
Also https://tickets.metabrainz.org/browse/MBS-10338 (Show ratings on artists' recordings tab)
> MBS-10337: Load recording ISRCs and ratings on artist overview

- root/static/scripts/edit/components/ArtistCreditBubble.js
https://tickets.metabrainz.org/browse/MBS-10269
Some changes made in https://github.com/metabrainz/musicbrainz-server/pull/1126 also affected this, so rebased it on top of that.
> MBS-10269: Open AC bubble artists in new window

- lib/MusicBrainz/Server/Controller/WS/2/Release.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/BrowseRelease.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupReleaseGroup.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelease.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupReleaseGroup.pm
- t/sql/webservice.sql
https://tickets.metabrainz.org/browse/MBS-10353
> MBS-10353: Enable ratings for release browse

- root/static/scripts/common/MB/edit_search.js
To be merged after https://github.com/metabrainz/musicbrainz-server/pull/1151
> Eslint for edit_search.js

- entities.json
- lib/MusicBrainz/Server.pm
- lib/MusicBrainz/Server/Controller/Release.pm
- lib/MusicBrainz/Server/Data/Artwork.pm
- root/components/EntityTabs.js
- root/types.js
https://tickets.metabrainz.org/browse/MBS-4913
In order to easily see whether we have only one or two pieces of cover art or an entire scanned booklet, it's useful to have the number of images listed as part of the cover art tab name.
> MBS-4913: Indicate the number of CAA pieces on tab

- .circleci/config.yml
- lib/MusicBrainz/Server/Controller/Artist.pm
- root/artist/ArtistIndex.js
Another place I forgot to add back the pagers
> MBS-10414: beta: add back artist index paging

- root/static/scripts/edit/utility/linkPhrase.js
> MBS-10419: Beta: Unbreak historical attributes display in edits

- root/account/applications/Edit.js
- root/account/applications/Register.js
- root/account/applications/Remove.js
- root/account/applications/RevokeAccess.js
- root/elections/Nominate.js
Removing unused imports (and a space between imports)
> Eslint fixes for /account/applications

- lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Recording.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Utils.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
- t/script/DumpJSON.t
https://tickets.metabrainz.org/browse/MBS-10428
While at it, I also did https://tickets.metabrainz.org/browse/MBS-10429 which makes the result more consistent with the XML WS without (AFAICT) dropping any info.
> MBS-10428: Show artist aliases for recording ACs

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
https://tickets.metabrainz.org/browse/MBS-10431
> MBS-10431: Remove 'yourmusic' from 7digital URLs

- lib/MusicBrainz/Server/Constants.pm
- root/static/scripts/common/constants.js
https://tickets.metabrainz.org/browse/MBS-10425
> MBS-10425: Allow rel credits for instruments

- docker/Dockerfile.tests
- docker/musicbrainz-tests/DBDefs.pm
- docker/templates/macros.m4
- po/attributes.sq.po
- po/countries.sq.po
- po/instrument_descriptions.sq.po
- po/instruments.sq.po
- po/languages.sq.po
- po/mb_server.sq.po
- po/relationships.sq.po
- po/scripts.sq.po
- po/statistics.sq.po
Albanian localization just started last month, displaying it on test website helps with seeing progress.
Note: test website must be updated after a further change to our internal docker server configuration.
> Add Albanian (sq) to tested languages

- .circleci/config.yml
- .eslintrc.yaml
- .gitignore
- babel.config.js
- package.json
- root/server.js
- root/utility/writeCoverage.js
- t/selenium.js
- t/selenium/Artist_Credit_Editor.html
- t/selenium/MBS-7456.html
- webpack.tests.config.js
- yarn.lock
Generates JavaScript test coverage for our Selenium tests using Istanbul. If all goes well, should be saved as a build artifact on CircleCI for viewing.
> JavaScript test coverage for Selenium

- .eslintignore
- HACKING.md
- script/check_eslint_rule
This can be invoked like
```sh
./script/check_eslint_rule \
'block-scoped-var: [warn]' \
root/
```
to check a specific rule under a specific directory
> Add a script to check a specific eslint rule

- root/artist/ArtistMerge.js
- root/components/FormRowCheckbox.js
- root/static/styles/forms.less
- root/user/ReportUser.js
https://tickets.metabrainz.org/browse/MBS-10382
> MBS-10382: Explain when to use the Update checkbox

- lib/MusicBrainz/Server/Data/URL.pm
- lib/MusicBrainz/Server/Entity/URL/DynamicRangeDB.pm
- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
https://tickets.metabrainz.org/browse/MBS-10448
No favicon added because it just doesn't seem to have any.
> MBS-10448: Add Dynamic Range DB to otherdbs whitelist

- lib/MusicBrainz/Server/Controller/Artist.pm
- root/area/merge.tt
- root/artist/ArtistMerge.js
- root/components/RemoveFromMergeTableCell.js
- root/components/RemoveFromMergeTableHeader.js
- root/components/common-macros.tt
- root/components/list/ArtistList.js
- root/components/list/RecordingList.js
- root/event/merge.tt
- root/instrument/merge.tt
- root/label/merge.tt
- root/layout/components/MergeHelper.js
- root/place/merge.tt
- root/recording/RecordingMerge.js
- root/release/merge.tt
- root/release_group/merge.tt
- root/series/merge.tt
- root/static/scripts/common/components/ArtistListEntry.js
- root/static/scripts/common/utility/renderMergeCheckboxElement.js
- root/types.js
- root/work/merge.tt
https://tickets.metabrainz.org/browse/MBS-3839
While working on it I also implemented https://tickets.metabrainz.org/browse/MBS-10456
> MBS-3839: Allow removing from queue during merge

- package.json
- root/components/Paginator.js
- root/context.js
- root/static/scripts/common/components/FilterForm.js
- root/static/scripts/common/i18n/expand2react.js
- root/utility/uriWith.js
- yarn.lock
I asked in their Discord if the computed property stuff is a bug, but didn't get a response yet. Should be fine to merge either way.
> Flow 0.111

- root/utility/formatUserDate.js
I used the alternatives suggested at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
Additionally, we now fall back to UTC if nothing else works.
> MBS-10465: Beta: Handle legacy time zones in formatUserDate

- package.json
https://tickets.metabrainz.org/browse/MBS-10473
> MBS-10473: Make terser-webpack-plugin a full dependency

- root/layout/index.js
It formats the current date with timezone set in user preferences, and compares with user birth date.
>  MBS-10466: Wish a happy birthday in user timezone 

- lib/MusicBrainz/Server/Controller/User/Edits.pm
- root/static/styles/layout.less
- root/user/UserProfile.js
- t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
https://tickets.metabrainz.org/browse/MBS-10204
Depends on https://github.com/metabrainz/musicbrainz-server/pull/1089
>  MBS-10204: Sum accepted/rejected edits in stats

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
> MBS-10482: Block and skip changing Patreon posts

- lib/MusicBrainz/Script/EntityDump.pm
- lib/MusicBrainz/Script/SampleDataDump.pm
- script/dump-entities-sql.pl
Splitting these out from #1148, but with some more commit messages this time
> Improvements to script/dump-entities-sql.pl

- root/search/components/InstrumentResults.js
https://tickets.metabrainz.org/browse/MBS-10491
> MBS-10491: Add "Add instrument" to search results

- root/layout/components/Head.js
- root/server.js
- root/server/createServer.js
- root/static/scripts/common/MB/Control/Autocomplete.js
- root/static/scripts/common/components/ArtistCreditLink.js
- root/static/scripts/common/utility/getBooleanCookie.js
- root/static/scripts/common/utility/reactTextContent.js
- root/static/scripts/edit/components/ArtistCreditEditor.js
- root/static/scripts/edit/components/forms.js
- root/static/scripts/edit/utility/guessFeat.js
- root/static/scripts/relationship-editor/common/entity.js
- root/static/scripts/relationship-editor/common/viewModel.js
- root/static/scripts/release-editor/edits.js
- root/static/scripts/release-editor/init.js
- root/static/scripts/tests/react-macros.js
- root/static/scripts/tests/utility.js
- root/static/scripts/timeline.js
- root/static/scripts/voting.js
Changes:
- let converted to const when appropriate across multiple files
Head.js(let pager) & server.js(let timeout) files were left with let, because of code readability.
> REFACTOR: Convert var or let to const

- lib/MusicBrainz/Server/Controller/Recording.pm
- root/recording/RecordingIndex.js
https://tickets.metabrainz.org/browse/MBS-10479
> MBS-10479: Show RG types on recording page

- root/components/EnterEditNote.js
https://tickets.metabrainz.org/browse/MBS-10489
> MBS-10489: Make EnterEditNote text less redundant

- root/release/edit/recordings.tt
https://tickets.metabrainz.org/browse/MBS-10255
> MBS-10255: Explanations for "copy all" checkboxes

- lib/MusicBrainz/Server/Edit/Release/Merge.pm
- root/components/list/ReleaseList.js
- root/edit/details/merge_releases.tt
- root/release_group/ReleaseGroupIndex.js
- root/search/components/ReleaseResults.js
- root/static/scripts/release-editor/duplicates.js
https://tickets.metabrainz.org/browse/MBS-10228
https://tickets.metabrainz.org/browse/MBS-10243
https://tickets.metabrainz.org/browse/MBS-10244
>  MBS-10228 /  MBS-10243 /  MBS-10244: Various fixes for no-media releases

- lib/MusicBrainz/Server/Form/Utils.pm
https://tickets.metabrainz.org/browse/MBS-10304
Reverting commit b645483e87b0a08f150a59d813fe807245680d08 as requested
by several editors, including our community manager.
> MBS-10304: Reallow special codes as editor language

- root/edit/details/merge_releases.tt
https://tickets.metabrainz.org/browse/MBS-10512
> MBS-10512: Do not show [missing media] for deleted/merged releases

- lib/MusicBrainz/Server/Controller/Release.pm
- t/lib/t/MusicBrainz/Server/Data/ReleasePackaging.pm
- t/selenium.js
- t/selenium/MBS-10510.html
- t/sql/initial.sql
- t/sql/mbs-10510.sql
https://tickets.metabrainz.org/browse/MBS-10510
Broken in commit 434f499f57238420b586c091d6c152d85cd737c4
Added a Selenium test.
> MBS-10510 (regression): Fix ISE merging releases with different recording artists

- .gitignore
Dev setup refers to pull request metabrainz/musicbrainz-docker#118
> Ignore files created by slave script and dev setup

- root/components/list/AreaList.js
- root/static/scripts/common/components/DescriptiveLink.js
- root/user/UserCollections.js
- root/utility/tableColumns.js
https://tickets.metabrainz.org/browse/MBS-10365
Pretty much all @yvanzo's code, just fixed one bug I found. Putting it up since it seems good enough to merge to me as a second step on react-table work.
> MBS-10365: Convert AreaList to React Table

- .eslintrc.yaml
- package.json
- root/static/scripts/common/components/Autocomplete2.js
- root/static/scripts/common/components/FingerprintTable.js
- root/static/scripts/common/hooks/useOutsideClickEffect.js
- script/check_eslint_rule
- yarn.lock
https://www.npmjs.com/package/eslint-plugin-react-hooks
Seems useful to avoid errors like the one in https://github.com/metabrainz/musicbrainz-server/pull/1305#discussion_r356432008
> Add eslint-plugin-react-hooks

- lib/MusicBrainz/Server/Controller/User.pm
- lib/MusicBrainz/Server/Data/Collection.pm
https://tickets.metabrainz.org/browse/MBS-10526
> MBS-10526: Only show private collab collections to collaborators

- root/layout/components/sidebar/SidebarBeginDate.js
- root/layout/components/sidebar/SidebarIpis.js
- root/layout/components/sidebar/SidebarIsnis.js
- root/static/scripts/common/utility/formatDatePeriod.js
- root/static/scripts/common/utility/formatEndDate.js
- root/types.js
- root/utility/age.js
Fixes related to the change to SeriesT in https://github.com/metabrainz/musicbrainz-server/pull/1257 that should be reviewed after that one.
> Make entity types read only + few Eslint fixes

- entities.json
- lib/MusicBrainz/Server/Controller/Instrument.pm
- lib/MusicBrainz/Server/Data/Artist.pm
- lib/MusicBrainz/Server/Data/Recording.pm
- lib/MusicBrainz/Server/Data/Release.pm
- root/components/InstrumentRelTypes.js
- root/components/list/ArtistList.js
- root/instrument/artists.tt
- root/static/scripts/common/components/ArtistListEntry.js
- root/types.js
https://tickets.metabrainz.org/browse/MBS-10316
On top of (and to be checked after) https://github.com/metabrainz/musicbrainz-server/pull/1134
> MBS-10316: Add "Artists" tab for instruments

- flow-typed/npm/react-table_v7.x.x.js
- lib/MusicBrainz/Server/Data/Label.pm
- root/components/list/AreaList.js
- root/components/list/InstrumentList.js
- root/components/list/LabelList.js
- root/components/list/PlaceList.js
- root/components/list/SeriesList.js
- root/components/list/WorkList.js
- root/static/styles/layout.less
- root/utility/tableColumns.js
https://tickets.metabrainz.org/browse/MBS-10365
This is turning out a bit too big to do (and maybe review?) all in one go, so putting this one up for review and possible merge already, with a bunch of the simpler entity types.
> MBS-10365: Convert entity lists to react-table (I)

- lib/MusicBrainz/Server/Controller/Place.pm
- root/place/PlaceMap.js
- root/place/map.tt
- root/server/components.js
This should be the last bit needed for https://tickets.metabrainz.org/browse/MBS-9919
> MBS-9919: Convert the place map tab to React

- lib/MusicBrainz/Server/Data/Editor.pm
https://tickets.metabrainz.org/browse/MBS-10501
> MBS-10501: Display avatars for collaborators on collections

- lib/MusicBrainz/Server/Data/Release.pm
- root/components/InstrumentRelTypes.js
- root/components/list/RecordingList.js
- root/components/list/ReleaseList.js
- root/static/scripts/common/components/ArtistListEntry.js
- root/utility/tableColumns.js
> MBS-10365: Convert entity lists to react-table (II)

- root/edit/details/add_release.tt
- root/edit/details/edit_release_label.tt
Fixes a regression introduced by #1242
> MBS-10560: Show full country names in release edits

- root/components/list/EventList.js
- root/utility/tableColumns.js
MBS-10365
Also fixes MBS-10583
After https://github.com/metabrainz/musicbrainz-server/pull/1355
> MBS-10365: Convert entity lists to react-table (III)

- cpanfile
- cpanfile.snapshot
- docker/Makefile
- docker/generate_cpanfile_snapshot.sh
- docker/musicbrainz-test-database/cpanfile.snapshot
- po/update_pot.sh
* Fix bug spotted by @reosarevok in `update_pot.sh`.
* Add support for `DOCKER_CMD` to allow running `sudo docker`.
* Move `Locale::PO` Perl dependency from production to development.
> Fix development scripts

- lib/MusicBrainz/Server/Data/LinkType.pm
- lib/MusicBrainz/Server/Data/Relationship.pm
- lib/MusicBrainz/Server/Entity/LinkType.pm
- root/components/GroupedTrackRelationships.js
- root/components/RelationshipTargetLinks.js
- root/components/Relationships.js
- root/components/StaticRelationshipsDisplay.js
- root/components/medium.tt
- root/server/components.js
- root/static/scripts/common/i18n/expand2.js
- root/static/scripts/common/i18n/semicolonOnlyList.js
- root/static/scripts/common/linkedEntities.js
- root/static/scripts/common/utility/arrays.js
- root/static/scripts/common/utility/compare.js
- root/static/scripts/common/utility/compareDates.js
- root/static/scripts/common/utility/displayLinkAttribute.js
- root/static/scripts/edit/components/edit/RelationshipDiff.js
- root/static/scripts/edit/utility/linkPhrase.js
- root/static/scripts/relationship-editor/common/fields.js
- root/static/scripts/tests/edit/utility/linkPhrase.js
- root/static/scripts/tests/index.js
- root/static/scripts/tests/relationship-editor.js
- root/types.js
- root/utility/areDatePeriodsEqual.js
- root/utility/areDatesEqual.js
- root/utility/groupRelationships.js
- root/utility/relationshipDateText.js
https://tickets.metabrainz.org/browse/MBS-7678
> MBS-7678: Combine display of multiple relationships to the same entity

- lib/MusicBrainz/Server/Report/ReleaseRGDifferentName.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/ReleaseRgDifferentName.js
- root/report/ReportsIndex.js
- root/report/types.js
- root/server/components.js
https://tickets.metabrainz.org/browse/MBS-3873
To avoid false positives (which would be quite likely otherwise), only release groups with only one release inside of them are checked for this report.
> MBS-3873: Report: non-matching RG/release titles

- root/components/StaticRelationshipsDisplay.js
- root/static/scripts/common/constants.js
- root/utility/groupRelationships.js
https://tickets.metabrainz.org/browse/MBS-10622
https://tickets.metabrainz.org/browse/MBS-10627
https://tickets.metabrainz.org/browse/MBS-10630
> Fix MBS-10622, MBS-10627, MBS-10630 (regressions from MBS-7678)

- package.json
- root/static/scripts/edit/utility/guessFeat.js
- root/static/scripts/tests/guessFeat.js
- yarn.lock
To be reviewed after https://github.com/metabrainz/musicbrainz-server/pull/1191
I guess the last commit fixes MBS-10504 actually.
> Eslint fixes for guessFeat

- root/release_group/edit_form.tt
- root/static/scripts/common/MB/Control/Autocomplete.js
- root/static/scripts/edit/ExampleRelationships.js
- root/static/scripts/edit/MB/CoverArt.js
- root/static/scripts/edit/utility/similarity.js
- root/static/scripts/guess-case/MB/GuessCase/Main.js
- root/static/scripts/guess-case/MB/GuessCase/Output.js
- root/static/scripts/jquery.flot.musicbrainz_events.js
- root/static/scripts/place.js
- root/static/scripts/relationship-editor/common/dialog.js
- root/static/scripts/relationship-editor/common/fields.js
- root/static/scripts/release-editor/duplicates.js
- root/static/scripts/release-editor/fields.js
- root/static/scripts/release-editor/init.js
- root/static/scripts/release-editor/recordingAssociation.js
- root/static/scripts/release-editor/trackParser.js
- root/static/scripts/release-editor/utils.js
- root/static/scripts/tests/react-macros.js
- root/static/scripts/tests/release-editor/edits.js
- root/static/scripts/tests/release-editor/fields.js
- root/static/scripts/timeline.js
I've started fixing eslint issues rule by rule (mostly the ones that are auto-fixable). This is the first bit, quite a few more to come (48 commits total).
> Eslint fixes by rule, pt. 1

- root/static/scripts/release-editor/duplicates.js
> Fix MBS-10586 / MBS-10587 / MBS-10588: Release Duplicates medium format fixes

- .circleci/config.yml
- docker/Dockerfile.tests
- lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Utils.pm
- lib/MusicBrainz/Server/WebService/XMLSerializer.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseArtists.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseReleaseGroups.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupDiscID.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupDiscID.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupTagsRatings.pm
Goes with https://github.com/metabrainz/mmd-schema/pull/21
To be reviewed after https://github.com/metabrainz/musicbrainz-server/pull/1064
> MBS-9491: Add genre MBIDs to the WS

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
MBS-10643
A new relationship for CPDL has been added, and this matches artist CPDL links to use that relationship.
> MBS-10643: Add autoselect for artists for CPDL

- lib/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm
- root/edit/details/edit_release_label.tt
> MBS-10593 / MBS-10649: Edit Release Label bugfixes

- lib/MusicBrainz/Server/Controller/WS/2/Genre.pm
- lib/MusicBrainz/Server/ControllerBase/WS/2.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Utils.pm
- lib/MusicBrainz/Server/WebService/XMLSerializer.pm
- root/entity/Details.js
- t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseArtists.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseReleaseGroups.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupDiscID.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupTagsRatings.pm
- t/sql/webservice.sql
https://tickets.metabrainz.org/browse/MBS-10166
Goes with https://github.com/metabrainz/mmd-schema/pull/21
> MBS-10166: Add genre entity to the WS

- lib/MusicBrainz/Script/MBDump.pm
Allow to choose a different trade-off between computing time and dump size when server is busy.
> Add compression level to MBDump

- po/update_pot.sh
- po/update_translations.sh
- script/tag.sh
- script/update_containers.sh
Document usage of the environment variable `LIST_METABRAINZ_HOSTS` for the deployment script.
> Help on LIST_METABRAINZ_HOSTS environment variable

- lib/MusicBrainz/Server/Controller/Edit.pm
- lib/MusicBrainz/Server/Data/Artist.pm
- lib/MusicBrainz/Server/Edit/Release.pm
- lib/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm
- lib/MusicBrainz/Server/EditSearch/Query.pm
- t/selenium/release-editor/The_Downward_Spiral.html
Fix a bunch of warnings about uninitialized values in Perl code.
> Reduce noise in website server logs

- root/components/Table.js
- root/components/list/ReleaseGroupList.js
- root/utility/tableColumns.js
> MBS-10365 (IV): Convert entity lists to react-table

- root/components/list/ArtistList.js
- root/components/list/EventList.js
- root/components/list/LabelList.js
- root/components/list/PlaceList.js
- root/components/list/RecordingList.js
- root/components/list/ReleaseGroupList.js
- root/components/list/ReleaseList.js
- root/components/list/WorkList.js
- root/utility/tableColumns.js
> MBS-10722: Entity list regression fixes

- lib/MusicBrainz/Server/Controller/Role/CORS.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupArtist.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/SubmitRecording.pm
https://tickets.metabrainz.org/browse/MBS-10360
> MBS-10360: Whitelist User-Agent header in CORS preflight requests

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
> MBS-10755: Validate Musik-Sammler.de URL rels

- lib/MusicBrainz/Server/Data/EntityTag.pm
Currently, if the 5 most voted tags for an entity are non-genre tags the sidebar will make it look as if the entity has no genre tags at all, since only the top 5 tags overall are displayed there. This changes it so that both the top 5 genres and the top 5 non-genre tags are displayed on the sidebar - it doesn't take that much space and is useful to make sure genres don't drown tags nor vice versa.
> MBS-10772: Show top 5 genres and other tags on sidebar

- root/layout/components/BottomMenu.js
> MBS-10785: Remove FreeDB Gateway from menu

- .circleci/config.yml
- admin/cleanup/MergeDuplicateArtistCredits
- admin/cron/hourly.sh
- t/script/MergeDuplicateArtistCredits.t
https://tickets.metabrainz.org/browse/MBS-7781
> MBS-7781: Add script to merge duplicate artist credits

- root/components/list/AreaList.js
- root/components/list/ArtistList.js
- root/components/list/EventList.js
- root/components/list/InstrumentList.js
- root/components/list/LabelList.js
- root/components/list/PlaceList.js
- root/components/list/RecordingList.js
- root/components/list/ReleaseGroupList.js
- root/components/list/ReleaseList.js
- root/components/list/SeriesList.js
- root/components/list/WorkList.js
- root/user/UserCollections.js
- root/utility/tableColumns.js
Hopefully this makes things more readable and understandable, to begin with.
Also: a couple tiny fixes to related files.
> MBS-10822: Change tableColumns tables to use named parameters 

- INSTALL.md
It follows https://blog.metabrainz.org/2020/05/16/musicbrainz-docker-composes-with-solr-7/
> Replace musicbrainz-vm with musicbrainz-docker

- root/user/UserCollections.js
> MBS-10836: Fix edit / remove collection links

- root/static/styles/entity.less
> MBS-10887: fix country/date text CSS alignment

- lib/MusicBrainz/Server/Controller/Area.pm
- lib/MusicBrainz/Server/Controller/Artist.pm
- lib/MusicBrainz/Server/Controller/Place.pm
> MBS-10937: Run load_meta on event lists for ratings

- lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
- lib/MusicBrainz/Server/Data/Track.pm
- lib/MusicBrainz/Server/Edit/Medium/Create.pm
- lib/MusicBrainz/Server/Edit/Medium/Edit.pm
- lib/MusicBrainz/Server/Entity/Medium.pm
- root/components/medium.tt
- root/edit/details/add_medium.tt
- root/release/edit/recordings.tt
- root/release/edit/tracklist.tt
- root/release/edit_relationships.tt
- root/release/index.tt
- root/static/scripts/release-editor/edits.js
- root/static/scripts/release-editor/fields.js
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelease.pm
- t/sql/webservice.sql
https://tickets.metabrainz.org/browse/MBS-8725
> MBS-8725: Allow mediums to have an unknown tracklist

- lib/MusicBrainz/Server/Edit/Generic/Delete.pm
- root/edit/details/RemoveEntity.js
- root/edit/details/remove_entity.tt
- root/server/components.js
- t/lib/t/MusicBrainz/Server/Controller/Edit/Show.pm
> MBS-10980: Convert Remove Entity edit to React

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
> MBS-10989: Update VocaDB cleanup to support new Es (series) format

- .eslintrc.yaml
- script/check_eslint_rule
Just fixes a few issues I've run into while coding that always annoy me.
> A few eslint config updates

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
> MBS-11004: Support laboiteauxparoles label links

- root/edit/details/EditAlias.js
- root/edit/details/EditArtist.js
- root/edit/details/EditEvent.js
- root/edit/details/EditLabel.js
- root/edit/details/EditPlace.js
- root/edit/details/EditRecording.js
- root/edit/details/EditSeries.js
Two small commits improving our diffs. The first is only refactoring, but makes sense to me at least. The second fixes what I think is probably a tiny bug, unless it was intended like that for some reason.
> Edit diff improvements

- lib/MusicBrainz/Server/Edit/Artist/EditArtistCredit.pm
- root/edit/details/EditArtistCredit.js
- root/edit/details/edit_artist_credit.tt
- root/server/components.js
> MBS-11051: Convert Edit Artist Credit edit to React

- .eslintrc.yaml
- root/entity/Tags.js
- root/layout/components/Head.js
- root/layout/components/globalsScript.js
- root/layout/components/sidebar/SidebarTags.js
- root/static/scripts/common/DBDefs-client.js
- root/static/scripts/common/components/TagEditor.js
- root/utility/hydrate.js
- root/utility/sanitizedContext.js
- root/vars.js
- t/selenium/release-editor/The_Downward_Spiral.html
- webpack/definePluginConfig.js
These commits were cherry-picked from my React relationship editor branch. They're aimed at reducing the size of the JSON for `$c` and props embedded into the HTML.
> Hydrate improvements

- contrib/ssssss.psgi
This was helpful in testing https://github.com/metabrainz/musicbrainz-server/pull/1216 to allow thumbnails to be displayed.
> Support GET requests in ssssss.psgi

- root/edit/components/IntentionallyRawIcon.js
- root/edit/details/AddInstrument.js
Sometimes it's not untranslated, but unformatted.
> Generalize IntentionallyRawIcon

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
See ticket’s description for example.
> MBS-11098: Fix validating Big Cartel URL for label

- root/static/scripts/edit/externalLinks.js
> MBS-11109 / MBS-10961 / MBS-11001/ MBS-11007 / MBS-11008: Block more smart/short links

- root/static/scripts/edit/externalLinks.js
> MBS-11068: Block redirect links: page.link

- lib/MusicBrainz/Server/Controller/Recording.pm
- lib/MusicBrainz/Server/Controller/Role/Merge.pm
- lib/MusicBrainz/Server/Controller/Work.pm
- root/work/WorkMerge.js
- t/lib/t/MusicBrainz/Server/Data/ISWC.pm
This just mirrors the approach for recordings with different ISRCs.
> MBS-3116: Warn when merging works with different ISWCs 

- lib/MusicBrainz/Script/JSONDump.pm
- t/script/DumpJSON.t
If we're running a full JSON dump, we can delete any rows older than the full dump sequence, provided there exists at least 1 row per entity newer or equal to that sequence. Previously we would be using the sequence of the /previous/ full dump, so the number of rows in these tables is double what they should be. We'll need to VACUUM FULL once the fix is in place.
> Delete unneeded json_dump rows faster

- root/components/Aliases/index.js
- root/entity/alias/edit_form.tt
As two commits because I'm lazy and did it through the web UI. We can squash for merging.
> MBS-11149: Fix ironic mis(s)pelling

- docker/scripts/start_template_renderer.sh
Forgot to add this to the docker starting script on https://github.com/metabrainz/musicbrainz-server/pull/1714
> MBS-4118 (fixup): Also use full-icu on docker

- root/static/scripts/release-editor/trackParser.js
- script/reset_selenium_env.sh
- t/selenium.js
- t/selenium/release-editor/MBS-10221.html
- t/selenium/release-editor/MBS-11156.html
- t/sql/selenium.sql
> MBS-10221, MBS-11156: Track parser doesn't update track artists, unsets VA track artists

- lib/MusicBrainz/Server/Data/Editor.pm
> MBS-11174: Add historic release adds to added_entities_counts

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
> MBS-11199: Remove superfluous 7digital parameters

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
> MBS-11200: Add works to VGMdb autocleanup

- admin/BuildIncrementalSitemaps.pl
- admin/DumpIncrementalJSON
- admin/DumpJSON
- lib/Catalyst/Plugin/ErrorInfo.pm
- lib/MusicBrainz/Errors.pm
- lib/MusicBrainz/Server.pm
- lib/MusicBrainz/Server/Controller/Root.pm
- lib/MusicBrainz/Server/EditQueue.pm
- root/main/info/error.tt
- t/lib/t/MusicBrainz/Server/Controller/Errors.pm
- t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
https://tickets.metabrainz.org/browse/MBS-10281
https://tickets.metabrainz.org/browse/MBS-11160
https://tickets.metabrainz.org/browse/MBS-11161
> MBS-10281, MBS-11160, MBS-11161: ISE fixes

- root/artist/ArtistRecordings.js
Simplify new messages for localization.
> Remove unneeded placeholder from message

- root/static/scripts/edit/utility/dates.js
- root/static/scripts/tests/utility.js
Added this during work on MBS-11168 but I'd rather get it checked separately and merged already, since that's going to be big anyway.
> Add flow types to utility/dates.js

- lib/MusicBrainz/Server.pm
🙇 Sorry for this very dirty PR where I cannot make sure that it works by muself. 🙇 
Problem from [MBS-11220](https://tickets.metabrainz.org/browse/MBS-11220)
-------
My browser setting: 
Accept-Language: fr-FR,fr;q=0.9,en-GB;q=0.8,en;q=0.7,vi;q=0.6,ja;q=0.5
My MBS selected language:
Cookie: {…}; lang=en
Using any external release editor seeding\*, release editor page is displayed in French instead of English.
Cause
-----
External (non-MBS) release editor seeding can no longer know
what is the user selected language because it cannot
access the lang Cookie in the request.
Solution
---
Trying to create the lang cookie as SameSite=None; Secure.
As I found that same issue was fixed for musicbrainz_server_session
by 54337c254c1cfe45d5c544be8c17be535af0b496 by @mwiencek.
Action
------
Please …
> MBS-11220: Allow external release editor seeding in user selected language

- lib/MusicBrainz/Server/Controller/Relationship/LinkType.pm
- lib/MusicBrainz/Server/Edit/Relationship/EditLinkType.pm
Companion to https://tickets.metabrainz.org/browse/MBBE-24
> Store name in EditLinkType attributes

- root/release/edit_relationships.tt
- root/static/scripts/relationship-editor/release.js
> MBS-11223 /  MBS-11224: Relationship editor fixes for missing tracklists / media

- lib/MusicBrainz/Server/Entity/Medium.pm
- root/components/medium.tt
Generally follows what we do on the JS side for groupedRelationships.
> MBS-11169 / MBS-11214: Fixes for bottom rel credits for mediums

- lib/MusicBrainz/Server/Report/InstrumentsWithoutAnImage.pm
- root/layout/components/sidebar/InstrumentSidebar.js
- root/report/InstrumentsWithoutAnImage.js
- root/static/scripts/common/components/IrombookImage.js
On top of https://github.com/metabrainz/musicbrainz-server/pull/1786
> MBS-10590: Implement IROMBOOK images for instruments

- root/utility/formatUserDate.js
Very obviously broken and not populating the cache at all.
> Fix broken date formatter cache set

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
> MBS-11263: Allow % (for encoded stuff) on beatport URLs

- root/static/scripts/guess-case/modes.js
- root/static/scripts/guess-case/utils.js
- root/static/scripts/tests/GuessCase.js
> MBS-11264: Guess case apostrophe fixes

- root/static/scripts/relationship-editor/common/viewModel.js
> MBS-11233 / MBS-11237: Fixes to relationship editor seeding

- lib/MusicBrainz/Server/Controller/WS/2/Recording.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/SubmitRecording.pm
Companion: https://github.com/metabrainz/mmd-schema/pull/24
> MBS-6048: Allow edit notes when submitting ISRCs

- root/edit/details/AddStandaloneRecording.js
> MBS-10913: Show removed standalone recordings as such

- lib/MusicBrainz/Server/Controller/CDTOC.pm
- root/cdtoc/remove.tt
>  MBS-8141 / MBS-10954: Small improvements to Remove DiscId page

- lib/MusicBrainz/Server/Edit/Release/ReorderMediums.pm
> MBS-11265: Load ACs for Reorder medium edits

- root/static/scripts/relationship-editor/common/fields.js
- root/static/scripts/tests/relationship-editor.js
> MBS-11181 / MBS-11281: Improvements to date merging in the relationship editor

- root/components/SelectField.js
- root/release/CoverArtFields.js
This seems to fix the issue, although testing perfectly is hard locally since I don't have a CAA server set up. For testing I made it so that an edit is created even if the image fails to upload, and then made sure the edit actually got created with the change.
The second commit fixes a warning. I think it's correct (we should never need to pick a default value for a multiple, I expect, so I skipped adding an analog function to getSelectValue) but do let me know if it doesn't seem right :)
> MBS-11319: Fix adding cover art in beta

- root/release/edit/tracklist.tt
We are able to add more of these, we should also be able to easily remove them.
> MBS-10915: Show "Remove track" button for data tracks even with discid

- lib/MusicBrainz/Server/Controller/Search.pm
- lib/MusicBrainz/Server/Data/Release.pm
- lib/MusicBrainz/Server/Data/Search.pm
- root/search/components/ReleaseResults.js
We show these on release pages elsewhere, it's probably sensible to show them here as well.
> MBS-11327: Show CAA icons on release search results

- root/components/GroupedTrackRelationships.js
Tested by checking http://localhost:5000/release/edf339dc-bb0e-4446-8365-966ebeb3c064 (with pink tunnel)
> MBS-11332: Don't double-bracket ended in track rels view

- lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
- root/static/scripts/common.js
- root/static/scripts/common/focusin-focusout-polyfill.js
- root/static/scripts/edit/MB/edit.js
- t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
https://tickets.metabrainz.org/browse/MBS-10964
(See commits for details.)
> MBS-10964: Prevent and handle empty artist credit name submissions in the release editor

- lib/MusicBrainz/Server/Controller/Artist.pm
- lib/MusicBrainz/Server/Data/ReleaseGroup.pm
- root/artist/ArtistIndex.js
> MBS-1459: Only display links at bottom of artist overview when relevant

- lib/MusicBrainz/Server/Report/InstrumentsWithoutAnImage.pm
- lib/MusicBrainz/Server/Report/InstrumentsWithoutWikidata.pm
CatQuest requested this and IMO it gives a better overview of what's missing - in any case, they're the main user of this, so it makes sense to make it easier for them.
> MBS-11351: Sort instrument reports by name before type

- root/artist/ArtistIndex.js
As done to ArtistRecordings in commit 5c826bb
> Simplify bottom links to avoid translation parameters

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
> MBS-11365: Allow Resident Advisor /podcast URLs for releases

- root/static/scripts/common/components/EntityLink.js
- root/static/scripts/edit/externalLinks.js
- root/url/utility/isGreyedOut.js
See commit titles/messages for info.
> MBS-11352 / MBS-11366: Malware blocking improvements

- root/layout/components/sidebar/ArtistSidebar.js
- root/user/UserProfile.js
> MBS-10744 / MBS-11378: Use lp_attributes for gender

- root/static/scripts/common/utility/compareDates.js
- root/static/scripts/tests/utility.js
This is cherry-picked from my relationship editor branch. I'm not sure yet how to describe this in a ticket, if it warrants one, because there's no actual issue currently.
See the commit message for details.
> compareDates / compareDatePeriods changes

- lib/MusicBrainz/Server/Controller/Admin/Attributes.pm
- lib/MusicBrainz/Server/Data/Role/Attribute.pm
- root/admin/attributes/CannotRemoveAttribute.js
- root/admin/attributes/in_use.tt
- root/server/components.js
I converted the in_use file to React as a more general error page that takes a message so I could reuse it for this error too.
> MBS-10076 / MBS-11403: Friendlier error when deleting attribute that has children 

- root/static/scripts/edit/externalLinks.js
> MBS-11402: Block smart links: many.link

- root/static/scripts/edit/externalLinks.js
> MBS-11422: Block smart links: gate.fm

- root/layout/components/BottomMenu.js
- root/main/index.js
New addition to the tagger affiliate program.
> MBS-11433: Add Mp3tag to Products menu and main page tagger list

- lib/MusicBrainz/Server/Edit/Label/Create.pm
> MBS-11444: Beta: Pass Label->new() call through to_json_object

- lib/MusicBrainz/Server/Edit/Area/Create.pm
- lib/MusicBrainz/Server/Edit/Artist/Create.pm
- lib/MusicBrainz/Server/Edit/Event/Create.pm
- lib/MusicBrainz/Server/Edit/Instrument/Create.pm
- lib/MusicBrainz/Server/Edit/Place/Create.pm
- lib/MusicBrainz/Server/Edit/Recording/Create.pm
- lib/MusicBrainz/Server/Edit/Series/Create.pm
- lib/MusicBrainz/Server/Edit/Work/Create.pm
> MBS-11448: Pass Place->new() call through to_json_object

- lib/MusicBrainz/Server/Entity/AutoEditorElection.pm
https://tickets.metabrainz.org/browse/MBS-11445
> MBS-11445: Fix 502 on auto-editor election pages

- lib/MusicBrainz/Server/Report/NoLanguage.pm
> MBS-11486: Load release info in NoLanguage before JSON conversion

- lib/MusicBrainz/Server/Edit/Work.pm
This breaks otherwise since $_->type unsurprisingly expects a blessed reference.
> MBS-11472: Do partition_by before converting attribute to JSON

- lib/MusicBrainz/Server/Controller/User.pm
- root/components/UserAccountTabs.js
> MBS-11452 /  MBS-11462: Fixes to user tabs display

- lib/MusicBrainz/Server/Report/ReleasesWithEmptyMediums.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/ReleasesWithEmptyMediums.js
- root/report/ReportsIndex.js
- root/server/components.js
On top of https://github.com/metabrainz/musicbrainz-server/pull/1787
> MBS-11222: Add a report for releases with media without a tracklist

- lib/MusicBrainz/Server/Data/Area.pm
- lib/MusicBrainz/Server/Data/Search.pm
> MBS-11386: Load area containment for indexed search

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
MBS-11524: Disallow https://*.bandcamp.com/ URLs at release and recording level
Restrict Bandcamp artist links
> MBS-11524: Disallow https://*.bandcamp.com/ URLs at release and recording level

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
[MBS-10534](https://tickets.metabrainz.org/browse/MBS-10534): Automatically turn DNB search link into permalink
Update `URLCleanup.js` to cleanup DNB search link
> MBS-10534: Cleanup DNB search link

- root/release/edit_relationships.tt
[MBS-9833](https://tickets.metabrainz.org/browse/MBS-9833): Link relationship style guide within release edit relationships tool
Add relationship style guide link to edit relationships tool 
1. Should we update the corresponding .po file for translation?
2. I'm sure if this message is the best choice, so please let me know if it can be better :)
> MBS-9833: Link relationship style guide within release edit relationships tool

- root/edit/details/historic/EditReleaseEvents.js
Found/tested with http://localhost:5000/edit/9384618
> Add keys to EditReleaseEvents to stop warning

- root/static/scripts/edit/externalLinks.js
> MBS-11533: Block smart links: snd.click

- root/static/scripts/edit/externalLinks.js
> MBS-11527: Block smart links: music.indiefy.net

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
This uses the same regex used for DNB identifiers on Wikidata: https://www.wikidata.org/wiki/Property:P227#P1793
> MBS-11603: Finetune DNB validation

- lib/MusicBrainz/Server/Controller/Artist.pm
- lib/MusicBrainz/Server/Controller/Event.pm
- lib/MusicBrainz/Server/Controller/Label.pm
- lib/MusicBrainz/Server/Controller/Recording.pm
- lib/MusicBrainz/Server/Controller/ReleaseGroup.pm
- lib/MusicBrainz/Server/Controller/Work.pm
This one was missed by https://github.com/metabrainz/musicbrainz-server/pull/2022/ it seems.
> MBS-11573: Load collections for ratings sidebars

- lib/MusicBrainz/Server/Report/CatNoLooksLikeISRC.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/CatNoLooksLikeIsrc.js
- root/report/ReportsIndex.js
- root/server/components.js
> MBS-10899: Report for releases with catnos that look like ISRCs

- root/genre/GenreLayout.js
> MBS-11604: Add genre name to genre index title

- root/static/scripts/edit/externalLinks.js
> MBS-11587: Block smart links: hypel.ink

- admin/sql/updates/20210406-mbs-11459.sql
- admin/sql/updates/schema-change/26.slave.sql
- upgrade.json
This is already on CreateFunctions but it should also be added to existing mirrors.
> MBS-11459: Create edit_data_type_info function on mirrors

- .circleci/config.yml
- INSTALL.md
- README.md
- cpanfile
- cpanfile.snapshot
- docker/Dockerfile.tests
- docker/scripts/start_template_renderer.sh
- docker/templates/Dockerfile.cpanfile-snapshot.m4
- docker/templates/macros.m4
- docker/templates/server_base.m4
- package.json
- script/start_renderer.pl
- yarn.lock
https://blog.metabrainz.org/2021/03/17/schema-change-release-may-17-2021/
Note: This switches the underlying Ubuntu base image to focal.
> Require Perl v5.30, Node v16

- lib/MusicBrainz/Server/Constants.pm
- lib/MusicBrainz/Server/Controller/Series.pm
- lib/MusicBrainz/Server/Data/Artist.pm
- root/components/list/ArtistList.js
- root/series/SeriesIndex.js
- root/static/scripts/common/constants.js
This wasn't really finished - without several of the changes in here, nothing would display and the series page would just give a 400, or it would load but fail to display properly once that first bug was fixed.
> MBS-11670: Finish implementation of artist series

- lib/MusicBrainz/Server/Controller/CDTOC.pm
> MBS-11663: Load RGs also when moving CDTOCs

- lib/MusicBrainz/Server/Controller/Work.pm
> MBS-11637: Show event-work rels on work page

- lib/MusicBrainz/Server/Report/ArtistCreditReport.pm
- lib/MusicBrainz/Server/Report/ArtistCreditsWithDubiousTrailingPhrases.pm
- lib/MusicBrainz/Server/Report/FilterForEditor/ArtistCreditID.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/artist_credit/ArtistCreditIndex.js
- root/artist_credit/ArtistCreditLayout.js
- root/components/Aliases/ArtistCreditList.js
- root/edit/details/EditArtistCredit.js
- root/report/ArtistCreditsWithDubiousTrailingPhrases.js
- root/report/ReportsIndex.js
- root/report/components/ArtistCreditList.js
- root/report/components/ReportLayout.js
- root/report/types.js
- root/server/components.js
- root/static/scripts/common/components/ArtistCreditUsageLink.js
On top of https://github.com/metabrainz/musicbrainz-server/pull/1787
> MBS-11305: Report for erroneous looking trailing join phrases

- root/admin/components/UserList.js
> MBS-11627: Don’t show "delete" link in UserList for deleted editors

- lib/MusicBrainz/Server/Controller/ReleaseEditor.pm
- root/static/scripts/common/constants.js
- root/static/scripts/common/linkedEntities.js
- root/static/scripts/common/utility/arrays.js
- root/static/scripts/common/utility/parseIntegerOrNull.js
- root/static/scripts/edit/externalLinks.js
- root/types/relationship.js
- root/types/series.js
Collects some small commits from my relationship editor branch which tweak our Flow types.
> Small Flow type changes from the relationship editor branch

- root/static/scripts/common/components/TagEditor.js
Rather than just showing the value as the label, this defines specific labels for the genres - just the name in most cases, but when there's a disambiguation comment we show it too. It won't be actually added to the tag list since it's not part of the value.
jQuery Autocomplete doesn't really support HTML labels by default, took the code for that from https://stackoverflow.com/questions/3488016/using-html-in-jquery-ui-autocomplete which seems to just take it from an extension last updated in 2013. Given that fact, we might as well just skip the extension.
> MBS-11609: Show genre disambiguation on autocomplete dropdown

- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Artist.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/Show.pm
This just reuses the member code since everything is the same except for the actual property name.
> MBS-9098: Add "memberOf" relationships to JSON-LD

- lib/MusicBrainz/Server/Form/Work.pm
- root/static/scripts/work.js
- root/types/knockout.js
- root/work/edit_form.tt
See commit messages for details
Tested manually by creating the relevant situations on local data.
> MBS-11638 / MBS-11639 / MBS-11640: Fixes for the work attribute form

- root/static/styles/forms.less
> MBS-11710: Beta: Position the "Add a new entity" dialog on top

- root/report/CDTocNotApplied.js
> MBS-11724: Fix typo

- lib/MusicBrainz/Server/Controller/Artist.pm
- lib/MusicBrainz/Server/Data/Artist.pm
- root/artist/CannotSplit.js
- root/artist/split.tt
- t/lib/t/MusicBrainz/Server/Controller/Artist/Split.pm
See commit messages
Tested manually by visiting an artist's split page while transitioning it through various states (fully empty, only one event rel, only one recording credit, both event rels and recording credits).
> MBS-8678 / MBS-8866 / MBS-11421: Split artist improvements

- package.json
- root/components/list/ReleaseGroupList.js
- root/layout/components/ExternalLinks.js
- root/server/gettext.js
- root/static/scripts/common/MB/Control/Autocomplete.js
- root/static/scripts/common/components/TagEditor.js
- root/static/scripts/common/i18n/expand2.js
- root/static/scripts/common/i18n/expand2html.js
- root/static/scripts/common/i18n/expand2react.js
- root/static/scripts/common/i18n/expand2text.js
- root/static/scripts/common/linkedEntities.js
- root/static/scripts/common/utility/arrays.js
- root/static/scripts/common/utility/cloneDeep.js
- root/static/scripts/common/utility/deepEqual.js
- root/static/scripts/common/utility/hasOwnProp.js
- root/static/scripts/common/utility/parseCookie.js
- root/static/scripts/edit/components/edit/RelationshipDiff.js
- root/static/scripts/edit/components/edit/ReleaseEventsDiff.js
- root/static/scripts/edit/externalLinks.js
- root/static/scripts/edit/utility/linkPhrase.js
- root/static/scripts/relationship-editor/common/dialog.js
- root/static/scripts/relationship-editor/common/viewModel.js
- root/static/scripts/release-editor/edits.js
- root/static/scripts/release-editor/fields.js
- root/static/scripts/tests/autocomplete2.js
- root/static/scripts/tests/i18n/expand2.js
- root/static/scripts/work.js
- root/vars.js
- script/generate_edit_data_flow_type.js
- yarn.lock
See associated commits for details
> Upgrade Flow to 0.155.0

- lib/MusicBrainz/Server/Report/FeaturingRecordings.pm
- lib/MusicBrainz/Server/Report/FeaturingReleaseGroups.pm
- lib/MusicBrainz/Server/Report/FeaturingReleases.pm
See commit messages. Tested by adding relevant entities locally and rerunning the reports.
On top of https://github.com/metabrainz/musicbrainz-server/pull/2163
> MBS-11772 / MBS-11774: Add more phrases to the featuring reports

- lib/MusicBrainz/Server/Data/Statistics.pm
- root/statistics/Index.js
- root/statistics/stats.js
> MBS-11765 / MBS-11769: Add / display some recording and work stats

- lib/MusicBrainz/Server/Report/RecordingTrackDifferentName.pm
- root/report/RecordingTrackDifferentName.js
- root/report/types.js
- root/utility/tableColumns.js
On top of https://github.com/metabrainz/musicbrainz-server/pull/2068
> MBS-11578: Link tracks in RecordingTrackDifferentName report

- root/static/scripts/release/components/MediumTable.js
This will be useful for userscripts and doesn't hurt us in any way.
> MBS-11781: Add class to the "load all tracks" link on large mediums

- root/entity/NotFound.js
> MBS-11832: Add missing NotFound params for artist_credit

- root/release/merge.tt
> MBS-11810 / MBS-11812: Small changes to release merge page

- lib/MusicBrainz/Server/Report/MislinkedPseudoReleases.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/MislinkedPseudoReleases.js
- root/report/ReportsIndex.js
- root/server/components.js
> MBS-11689: Report for pseudo-releases marked as the original tracklist

- root/static/styles/forms.less
> Fix margin of link action icons

- lib/MusicBrainz/Server/Controller/OAuth2.pm
- lib/MusicBrainz/Server/Data/Utils.pm
- t/lib/t/MusicBrainz/Server/Controller/OAuth2.pm
https://tickets.metabrainz.org/browse/MBS-11933
> MBS-11933: Validate the code parameter in /oauth2/token

- lib/MusicBrainz/Server/Controller/ReleaseEditor.pm
- root/static/scripts/edit/externalLinks.js
- MBS-11931: Beta: Link type option "Discogs" appears under the "get music" heading
- MBS-11929: Beta: Untouched URL missing a relationship type may block editing
- MBS-11927: Beta: URL relationship editor doesn't display invalid relationship type
> MBS-11931, MBS-11929, MBS-11927: Beta fixes for URL editing

- root/static/scripts/edit/externalLinks.js
> MBS-11907: Block vyd.co link aggregator

- root/area/AreaPlaces.js
... good job, me from the past :)
> MBS-11944: Fix label on button for place merges

- lib/MusicBrainz/Server/Controller/WS/2/Tag.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/Authenticated.pm
https://tickets.metabrainz.org/browse/MBS-11940
> MBS-11940: Properly error for invalid XML sent to /ws/2/tag

- root/static/scripts/edit/externalLinks.js
- root/static/styles/forms.less
- t/selenium/External_Links_Editor.json5
Move edit icons of external links editor to the left side
> MBS-11978: Move edit icons of external links editor to the left side

- lib/MusicBrainz/Server/Data/Statistics.pm
My bad when implementing this.
> MBS-11998: Also include places on rating stats sum

- root/static/scripts/edit/externalLinks.js
We were blocking submissions if any links hit an error, without checking whether they had changed at all.
This changes it so that submissions are blocked only if a change has happened to the links in question.
Cherry-picked from https://github.com/metabrainz/musicbrainz-server/pull/2301 since it's blocking users from editing so we should fix it soonish.
> MBS-12010: Don't block editing entity if pre-existing URLs error

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
> MBS-12065: Also allow "gakki_illustration" for gakki other database links

- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Release.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Role/SameAs.pm
The most-referenced [silence] recording has over 2,000 gid redirects.  These are all outputted in the `sameAs` property in its JSON-LD, including on release pages that reference it.  If the release contains [silence] multiple times, as https://musicbrainz.org/release/86427535-9abb-4681-8c88-5c651e55d62a does for example, then this is multiplied.  (The linked release references [silence] more than 50 times, and contains a 7.75 MB chunk of JSON-LD.)
It also so happens that Google reports "Structured data with syntax errors" on this page, with "Incorrect value type" as the reason (but the part of the source it highlights as having an error makes no sense).  So we're wondering if this is just due to the size of the page hitting some internal limits that Google has.
This patch limits the …
> MBS-12079: JSON-LD for releases with a lot of [silence] is too big

- INSTALL.md
Reading the installation notes, everything was crystal clear until I got to the "Setup PostgreSQL authentication",
- I didn't understand at first that I needed to change PostgreSQL config (I looked up the files mentioned in the doc inside the project).
- I didn't know how to force the changes in PostgreSQL to take effect.
I added the info I found online about those matters.
> Give more details about changing PostgreSQL config

- root/entity/Details.js
- root/layout/components/MergeHelper.js
- root/layout/index.js
- root/static/scripts/common/artworkViewer.js
- root/static/scripts/common/utility/request.js
- root/static/scripts/edit/components/HelpIcon.js
- root/static/scripts/edit/components/URLInputPopover.js
- root/static/scripts/edit/externalLinks.js
@alastair [asked](https://github.com/metabrainz/musicbrainz-server/pull/2333#discussion_r749438055) why we use 'conditions && action' instead of an if statement or ternary in some files, and both @mwiencek and I didn't have any good reasoning and prefer the alternative option. So this changes the few cases I could find to use if statements or ternaries. I feel this makes things a lot more clear.
I also moved some conditions to a constant in index.js for readability.
> Replace && with if/ternary

- script/update_containers.sh
Deployment failure occurred on `yehudi` (also preventing deployment on next node: `zappa`) because the website container is currently disabled on that node.
In the (current) event where a service is disabled on a specified host, this patch prevents deployment failure due to trying to set maintenance mode for a non-existing service/container.
> Fix updating settng maintenance mode (again)

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
> MBS-11980: Test relationship types restriction in external links editor

- package.json
Fixes the comment from @mwiencek on https://github.com/metabrainz/musicbrainz-server/pull/2363
> Revert private to true in package.json file

- root/static/scripts/edit/components/ArtistCreditBubble.js
I have no idea why we weren't allowing this already, but it seems to be as trivial as this.
> MBS-12127: Allow batch-changing all blank artist credits

- lib/MusicBrainz/Server.pm
- lib/MusicBrainz/Server/CoverArt/Provider/WebService/Amazon.pm
- lib/MusicBrainz/Server/Data/Edit.pm
- lib/MusicBrainz/Server/Data/Editor.pm
- lib/MusicBrainz/Server/Edit/ReleaseGroup/SetCoverArt.pm
- lib/MusicBrainz/Server/Email.pm
- lib/MusicBrainz/Server/Entity/Medium.pm
- lib/MusicBrainz/Server/Form/Field/ArtistCredit.pm
- root/static/scripts/release/components/MediumTable.js
- root/static/scripts/release/components/TracklistAndCredits.js
- root/types/medium.js
In another PR I'll resolve the "Failed to lookup cover art" warnings by removing support for Amazon cover art and other providers.
> Fix various warnings found in the musicbrainz-website-prod logs on hip

- lib/MusicBrainz/Server/Data/Statistics.pm
- root/static/scripts/account/components/EditProfileForm.js
- root/statistics/Index.js
- root/statistics/stats.js
Two small changes needed to complete support for our newly-added non-binary gender option, since they are hardcoded.
> MBS-12203 / MBS-12204: Changes for new non-binary gender option

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
> MBS-12202: Allow parens on JazzMusicArchives URLs

- lib/MusicBrainz/Server/Controller/Edit.pm
- lib/MusicBrainz/Server/Controller/Role/EditListing.pm
- lib/MusicBrainz/Server/Controller/User/Edits.pm
Also add a missing refinement for subscribed editor edits.
> MBS-11481 (MBS-10847): Add refine link to edit/subscribed 

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
> MBS-12246: Enable Genius links for Labels as "lyrics" and Places as "other databases"

- script/update_containers.sh
Skip updating containers which are running the latest built image for this service already.  This change only helps with resuming an update, by fastening further runs of the script after it has been interrupted for some reason.
> MBS-12258: Skip updating up-to-date containers

- flow-typed/npm/@fortawesome/free-solid-svg-icons_v6.x.x.js
- package.json
- root/components/home/About.js
- root/components/home/Facts.js
- root/main/index.js
- root/static/styles/common.less
- root/static/styles/extra/homepage.less
- yarn.lock
Two major sections have been added:
- The general about section is accompanied by a MeB video, which is a great introduction to the MetaBrainz world. (Can be replaced with a MusicBrainz specific video in the future)
- The Facts sections where the numbers have been hardcoded. We can look to make this dynamic.
> About Section in the Homepage

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
See commit messages. I also found yet another silly mistake in my `expected_error` test implementation, sigh.
> MBS-12275 / MBS-12276: YouTube playlist cleanup / validation improvements

- lib/Catalyst/Plugin/ErrorInfo.pm
- lib/MusicBrainz/Errors.pm
- lib/MusicBrainz/Server/Controller/WS/js.pm
We have at least one editor consistently getting "InternalError" / "Failed to get necessary short term bucket lock", and I'd like to collect more data on this.
> Log bucket creation failures to Sentry

- root/components/home/Explore.js
- root/main/index.js
- root/static/styles/extra/homepage.less
Added the explore section in the Homepage.
Available at https://test.musicbrainz.org
> Explore Section in Homepage

- lib/MusicBrainz/Server/Controller/Relationship/LinkAttributeType.pm
- po/extract_pot_db
- root/relationship/linkattributetype/RelationshipAttributeTypeIndex.js
- root/relationship/linkattributetype/RelationshipAttributeTypesList.js
> MBS-12305: Allow editing/translating instrument (root) rel attribute

- admin/GenerateSQLScripts.pl
- admin/InitDb.pl
- admin/sql/CreateFunctions.sql
- admin/sql/CreateTables.sql
- admin/sql/CreateTriggers.sql
- admin/sql/CreateTypes.sql
- admin/sql/DropAll.sql
- admin/sql/DropTypes.sql
- admin/sql/updates/20220322-mbs-12256-mirror.sql
- admin/sql/updates/20220322-mbs-12256-standalone.sql
- admin/sql/updates/schema-change/27.mirror.sql
- admin/sql/updates/schema-change/27.standalone.sql
- lib/MusicBrainz/Server/Data/Rating.pm
- script/create_test_db.sh
- t/lib/t/MusicBrainz/Server/Controller/Artist/Ratings.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/Show.pm
- t/lib/t/MusicBrainz/Server/Data/Rating.pm
- t/pgtap/aggregate_ratings.sql
- t/sql/controller_artist.sql
- upgrade.json
MBS-12256
This mostly follows a similar implementation to https://github.com/metabrainz/musicbrainz-server/pull/2434.
> MBS-12256: Keep meta rating columns up-to-date with triggers

- .circleci/config.yml
- cpanfile.snapshot
- docker/Dockerfile.tests
* SIR `2.y.z` is not compatible with MB DB schema sequence `27`
* Tests do not use the same version of MB Solr as in production
* Chrome Driver is outdated compared to the current stable
As a result, Selenium tests are failing.
* Rebuild cpanm snapshot for the occasion
* Bump MB Solr version to `3.2.4` ([release notes](https://github.com/metabrainz/mb-solr/releases/tag/v3.4.2))
* Bump Chrome Driver version to `101.0.4951.41`
* Bump SIR version to `3.0.0` ([release notes](https://github.com/metabrainz/sir/releases/tag/v3.0.0))
Fix installing its requirements:
* Self-upgrade PIP to the latest `20.3.4` version supporting Python 2
* Install `typing` package which seems to be now missing otherwise
* Fix the URL to install `ultrajson` from its git repository
* Refer to a new tag for the …
> Update SIR and MB Solr in CI tests

- po/attributes.pot
- po/countries.fr.po
- po/instruments.es.po
- po/instruments.ja.po
- po/languages.pot
- po/languages_notrim.pot
- po/mb_server.pot
- po/relationships.pot
- po/statistics.pot
Some changes to translatable messages have been made in both `master` branch and `schema-change-2022-q2` branch. Translators needed to get these source messages ahead of release time to have a chance to translate those.
- Merged the current `master` branch (4e72165b8a4097c5be45ffd75d076c78c66bed22) into the current `schema-change-2022-q2` branch (0b7ff5556524e68371a38734eee6d86d18ceffee).
- Ran `./po/update_translations.sh --commit` then `./po/update.sh` and finally `tx push musicbrainz.attributes,musicbrainz.instruments,musicbrainz.languages-9,musicbrainz.server,musicbrainz.relationships,musicbrainz.statistics`
After the `schema-change-2022-q2` branch has been merged into the `master` branch:
After merging this branch into the `master` branch (as part of the release process):
1. Get new …
> Updated translations on 2022-05-13

- lib/MusicBrainz/Server/Report/ReleasesWithMailOrderRelationships.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/ReleasesWithMailOrderRelationships.js
- root/report/ReportsIndex.js
- root/server/components.js
Similar to non-digital releases with download rels, this should never be correct AFAICT.
> MBS-12385: Add report for digital releases with mail order rels

- root/event/edit_form.tt
- root/label/edit_form.tt
- root/place/edit_form.tt
- root/work/edit_form.tt
Somehow I missed quite a few last time!
> MBS-12280 (II): Add target _blank to more edit form links

- lib/MusicBrainz/Server/Entity/URL/Tower.pm
That's what they call themselves, so it makes sense to use it.
> MBS-12393: Change TOWER RECORDS to all-caps as per store Japanese usage

- root/static/scripts/alias/AliasEditForm.js
This probably should not be recording-name.
> Fix the hydrate div name for AliasEditForm

- lib/MusicBrainz/Server/Controller/Genre.pm
- root/genre/GenreIndex.js
- t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
Plus a tiny preemptive bug fix where I had missed passing a prop.
> MBS-12474: Display Wikipedia extracts for genres

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
> MBS-12475: Add autoselect for Wikidata and RYM genre URLs

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
> MBS-12490 / MBS-12491 / MBS-12492: More genre autoselects

- package.json
- root/static/scripts/common/components/Autocomplete2/recentItems.js
- root/static/scripts/edit/externalLinks.js
- yarn.lock
https://github.com/facebook/flow/releases/tag/v0.183.0
The first changelog entry is a bit vague but we did encounter some new
errors which I've fixed here; mostly by adding additional annotations to
help Flow and fixing some incorrect type parameters.
> Upgrade Flow to 0.183.0

- lib/MusicBrainz/Script/SampleDataDump.pm
> MBS-12512: Dump genre_alias_type for sample DB

- root/components/list/RecordingList.js
- root/components/list/WorkList.js
- root/layout/components/sidebar/RecordingSidebar.js
- root/layout/components/sidebar/WorkSidebar.js
- root/search/components/RecordingResults.js
- root/static/scripts/common/components/IsrcList.js
- root/static/scripts/common/components/IswcList.js
- root/static/scripts/common/components/WorkListEntry.js
- root/utility/tableColumns.js
- webpack/client.config.mjs
> MBS-12334: Collapse ISRCs and ISWCs when there are too many

- lib/MusicBrainz/Server/Report/BadAmazonURLs.pm
- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
These do not seem to have working Amazon Music pages yet, so not adding it to those.
> MBS-12544: Support Egypt and Saudi Arabia ASINs

- root/static/scripts/guess-case/modes.js
- root/static/scripts/tests/GuessCase.js
It seems sensible to treat this the same way we already do YouTube.
> MBS-12543: Add a TikTok exception for guess case

- root/components/common-macros.tt
- root/server/components.mjs
As far as I could tell, all these components are no longer used in TT, and all these TT macros have had all their uses ported over.
> Clean unused embed components and TT macros

- root/static/scripts/edit/utility/isShortenedUrl.js
> MBS-12584 / MBS-12585: Block smart links: onerpm.link / withkoji.com 

- lib/MusicBrainz/Server/WebService/JSONSerializer.pm
Calls to `ws/js/entity/$track_mbid` were failing with a can't locate `WS::js::Track` error. Tracks are apparently unsupported
and that's fine, but we should error gracefully. This uses the same `critical_error` method we already use elsewhere in `ws/js`.
> MBS-12567: Fail gracefully when loading unsupported class

- root/static/scripts/relationship-editor/components/DialogAttribute/BooleanAttribute.js
- root/static/scripts/relationship-editor/components/DialogAttributes.js
- root/static/scripts/relationship-editor/hooks/useRangeSelectionHandler.js
- root/static/scripts/release/components/MediumRelationshipEditor.js
- root/static/scripts/release/components/ReleaseRelationshipEditor.js
- root/static/scripts/release/components/TrackRelationshipEditor.js
https://tickets.metabrainz.org/browse/MBS-12594
> MBS-12594: Add shift-click selection in relationship editor

- root/static/scripts/relationship-editor/utility/updateRecordingStates.js
- root/static/scripts/release/components/ReleaseRelationshipEditor.js
- root/utility/invariant.js
https://tickets.metabrainz.org/browse/MBS-12601
> MBS-12601: Limit batch work creation to where works aren't linked

- root/static/scripts/relationship-editor/components/RelationshipDialogContent.js
https://tickets.metabrainz.org/browse/MBS-12619
> MBS-12619: <Enter> on a button shouldn't accept the relationship dialog

- root/static/scripts/common/components/Autocomplete2.js
https://tickets.metabrainz.org/browse/MBS-12605
I've also taken the magnifying glass icon out of the sequential tab index.
> MBS-12605: Autocomplete2: Tab to select items

- root/static/scripts/relationship-editor/components/RelationshipEditor.js
- root/static/scripts/relationship-editor/types.js
- root/static/scripts/relationship-editor/types/actions.js
- root/static/scripts/relationship-editor/utility/cloneState.js
- root/static/scripts/relationship-editor/utility/findState.js
- root/static/scripts/relationship-editor/utility/updateReleaseRelationships.js
- root/static/scripts/relationship-editor/utility/updateWorkStates.js
- root/static/scripts/release/components/ReleaseRelationshipEditor.js
- root/static/scripts/release/components/TrackRelationshipEditor.js
- t/selenium/Artist_Edit_Form.json5
- t/selenium/Series_Relationship_Editor.json5
https://tickets.metabrainz.org/browse/MBS-12603
Adds a red "X" icon next to work names in the right column.  Clicking
that will remove all relevant recording-work links.  (Pending links will
be removed outright, and existing links will be marked for removal.)
> MBS-12603: Allow removing work relationships from the works column

- lib/MusicBrainz/Server/Data/ReleaseGroup.pm
- root/components/list/ReleaseGroupList.js
> MBS-12647 / MBS-12648: Fix RG collection artist credit sort

- root/static/scripts/common/components/Autocomplete2/formatters.js
- root/static/scripts/edit/components/HelpIcon.js
- root/static/scripts/edit/components/Multiselect.js
- root/static/scripts/edit/components/Tooltip.js
- root/static/scripts/relationship-editor/components/DialogAttribute/MultiselectAttribute.js
- root/static/scripts/relationship-editor/components/DialogEntityCredit.js
- root/static/scripts/relationship-editor/components/DialogLinkType.js
- root/static/scripts/relationship-editor/components/DialogSourceEntity.js
- root/static/scripts/relationship-editor/components/DialogTargetEntity.js
- root/static/styles/forms.less
- root/static/styles/relationship-editor.less
- t/selenium/Artist_Edit_Form.json5
- t/selenium/Genre_Edit_Form.json5
- t/selenium/Release_Relationship_Editor.json5
This pull request tries to improve elements of the relationship editor dialog to take up less space.  Some of the feedback came from MBS-11847 and MBS-12635, though I'm not sure if it resolves the latter issue.
> Relationship editor dialog layout improvements

- po/Makefile
- po/countries.pot
- po/instrument_descriptions.it.po
- po/instruments.it.po
- po/relationships.it.po
This was removed from here with 1feff5c since it was looking at the wrong table.
ef1e431 made it look in the right place but I guess Ian forgot to actually add countries.pot back. Whoops.
> MBS-12639: Also update countries.pot from the DB 

- lib/MusicBrainz/Server/Data/ReleaseGroup.pm
Amend commit dbfd10b from pull request #2669.
> Fix warning when starting the server

- lib/MusicBrainz/Server/Controller/Dialog.pm
- lib/MusicBrainz/Server/Controller/Role/EditRelationships.pm
- root/static/scripts/common/utility/catalyst.js
- root/static/scripts/edit/components/AddEntityDialog.js
- root/static/scripts/edit/externalLinks.js
- root/static/scripts/relationship-editor/components/DialogPreview.js
https://tickets.metabrainz.org/browse/MBS-12632
> MBS-12632: Fix cases where [removed] is displayed in the relationship editor dialog preview

- root/static/scripts/relationship-editor/components/RelationshipItem.js
https://tickets.metabrainz.org/browse/MBS-12643
> MBS-12643: Hide non-editable link orders in the relationship editor

- .flowconfig
- package.json
- root/static/scripts/common/i18n/expand2.js
- root/utility/generateFlowType.js
- yarn.lock
Only minor changes necessary: https://github.com/facebook/flow/releases
> Upgrade Flow to 0.190.0

- root/edit/search_macros.tt
> MBS-12672: Add "Genre" to edit search like other entities

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
New unique identifiers called handles will be available at YouTube.
These are almost the same as usernames and channel names but preceded with an at symbol (`@`).
Add cleanup for YouTube handle.
No change is needed for sidebar display.
See the specs at: https://support.google.com/youtube/answer/11585688#tns
> MBS-12681: Support YouTube Handle

- root/static/scripts/edit/utility/isShortenedUrl.js
> MBS-12687: Block smart links: allmylinks.com

- lib/MusicBrainz/Server/Data/WikiDoc.pm
Links on images in the transcluded documentation are currently removed, because images didn't have to be zoomed anyway.  The rare large images (such as database schema) were linked through additional links that had to be added manually in the wiki. Now that there are more large images, it is necessary to allow zooming in.
This patch allow linking a thumbnail to the original image simply by adding the option "class=zoomable" to the wanted "Image" WikiLinks.
It's cheaper than MediaWiki's MultiMedia Viewer extension but it works.
Tested manually on the page `/doc/MusicBrainz_Database/Schema`, using the remote production standby database and a local flushed Redis cache.
There is no CI test for it, and it wouldn’t be worth adding any given that it's just a bandage.
> MBS-12984: Link zoomable image in the documentation

- admin/replication/LoadReplicationChanges
Small regression in `master`/`beta`/`production`
The following warning was output when running this script:
print (...) interpreted as function
at ./admin/replication/LoadReplicationChanges line 357.
Drop unneeded parenthesis.
- Propagate to `beta` and `production` branches (used for tagging today’s release).
- No need to deploy in containers though.
> Fix innocuous warning in LoadReplicationChanges

- root/admin/LockedUsernameUnlock.js
- root/admin/wikidoc/DeleteWikiDoc.js
A pair of confirmation messages were hardly shortened, using inappropriate typewriter apostrophe, needlessly duplicating messages to be translated.
Use “Yes, I am sure” for all.
Manually opened both pages locally using sample data.
> Reword: Use the same writing as in other component

- lib/MusicBrainz/Server/Constants.pm
- root/static/scripts/tests/index-web.js
- root/static/scripts/tests/utility/sanitizedEditor.js
- root/utility/sanitizedEditor.mjs
The ``PUBLIC_PRIVILEGE_FLAGS `` has been wrongly constructed using the bitwise AND operator. It should be constructed using the bitwise OR operator instead.
> MBS-13087: Change bitwise AND to OR for combining privileges

- .perlcriticrc
- bin/delete-old-fullexports
- lib/MusicBrainz/Server/Controller/Artist.pm
- lib/MusicBrainz/Server/Controller/ArtistCredit.pm
- lib/MusicBrainz/Server/Controller/Role/Tag.pm
- lib/MusicBrainz/Server/Controller/Tag.pm
- lib/MusicBrainz/Server/Controller/User.pm
- lib/MusicBrainz/Server/Controller/WS/2/Collection.pm
- lib/MusicBrainz/Server/Controller/WS/js.pm
- lib/MusicBrainz/Server/Data/Artist.pm
- lib/MusicBrainz/Server/Data/Editor.pm
- lib/MusicBrainz/Server/Data/ISWC.pm
- lib/MusicBrainz/Server/Data/Utils.pm
- lib/MusicBrainz/Server/Data/WikiDoc.pm
- lib/MusicBrainz/Server/Edit/Event/Merge.pm
- lib/MusicBrainz/Server/Edit/Historic/EditReleaseAttrs.pm
- lib/MusicBrainz/Server/Edit/Historic/MergeRelease.pm
- lib/MusicBrainz/Server/Edit/Instrument/Merge.pm
- lib/MusicBrainz/Server/Edit/Release/RemoveCoverArt.pm
- lib/MusicBrainz/Server/Edit/Work/Merge.pm
- lib/MusicBrainz/Server/Form.pm
- lib/MusicBrainz/Server/Translation.pm
- lib/MusicBrainz/Server/Validation.pm
- lib/MusicBrainz/Server/WebService/JSONSerializer.pm
- lib/Plack/Middleware/Debug/ExclusiveTime.pm
- lib/Plack/Middleware/Debug/TemplateToolkit.pm
- t/hydration_i18n.t
- t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
- t/lib/t/MusicBrainz/Server/EditRegistry.pm
- t/script/DumpJSON.t
On top of https://github.com/metabrainz/musicbrainz-server/pull/2714
> Follow more Perl::Critic::Policy::BuiltinFunctions rules

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
We now have a BookBrainz relationship for series too, so we should handle it like the others.
Added a basic test - we don't do much validation with these so it's very basic.
> MBS-13168: Add autoselect for BookBrainz series

- root/account/ChangePassword.js
- root/account/LostPassword.js
- root/recording/DeleteRecording.js
- root/static/scripts/account/components/RegisterForm.js
- root/user/Login.js
Noticed a few minor issues while translating new messages in `beta`.
See commit messages.
> Fix translatable messages

- docker/Dockerfile.tests
- docker/config/services/dev.musicbrainz-server.json
- docker/musicbrainz-tests/DBDefs.pm
- docker/templates/macros.m4
The list of UI languages has not been updated for a while.
* Keep the current UI languages even though some have not been maintained.
* Add Hebrew to UI languages for `beta.mb.o` as it passed 60% of completion (for both MB Server messages and all MB messages)
* Add Italian (which is already part of the main UI languages in production) to the development config (which I’m not sure it is currently used) for `git2consul`/`gitzconsul`.
1. Same changes to be made in `musicbrainz-docker`
2. Same changes to be made in `docker-server-configs`
> Update UI languages

- lib/MusicBrainz/Server/Data/Release.pm
- lib/MusicBrainz/Server/FilterUtils.pm
- lib/MusicBrainz/Server/Form/Filter/Release.pm
- root/static/scripts/common/components/FilterForm.js
- t/lib/t/MusicBrainz/Server/Controller/Artist/Filtering.pm
- t/sql/filtering.sql
See commit messages
I hadn't added release filtering tests (probably forgot it was possible) so this adds some.
> MBS-12269 / MBS-12460: Allow filtering artist releases by label and status 

- INSTALL.md
In the section "Building static web resources" in `INSTALL.md`, running the command `./script/compile_resources.sh`, as suggested in the instruction, causes this error.
```
Error: ENOENT: no such file or directory, stat '/musicbrainz-server/po/javascript.vi.po'
```
Following the section "Translations" first will solve the error since it creates the files needed.
Therefore, I updated the README so the readers will follow the translation section first.
I don't think there's any other action needed than reviewing this PR.
> Update INSTALL.md's building static resources section

- lib/MusicBrainz/Server/Report/LowDataQualityReleases.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/LowDataQualityReleases.js
- root/report/ReportsIndex.js
- root/server/components.mjs
This report was misleadingly worded about the quality of releases, which can actually be shared with ratings and critiques.
This patch clarifies that this report is about the quality of the data for these releases, by using the same wording as in the release page.
```sh
./admin/RunReports.pl LowDataQualityReleases`
```
1. After deploying `beta`, run the following shell command in order to create the table `low_data_quality_releases`.
```sh
./admin/run ./admin/RunReports.pl LowDataQualityReleases`
```
2. After deploying `production`, drop the previous table with the following SQL commands:
```sql
DROP TABLE report.low_quality_releases;
DELETE FROM report.index WHERE report_name = 'low_quality_releases';
```
> MBS-13357: Clarify the report for low data quality

- .perlcriticrc
- lib/MusicBrainz/Server/Replication.pm
- lib/MusicBrainz/Server/Validation.pm
- t/lib/t/MusicBrainz/Server/Controller/RelationshipEditor.pm
On top of https://github.com/metabrainz/musicbrainz-server/pull/2715
> Follow Perl::Critic::Policy::ClassHierarchies rules

- lib/MusicBrainz/Server/Entity/Alias.pm
- lib/MusicBrainz/Server/Entity/Area.pm
- lib/MusicBrainz/Server/Entity/Artist.pm
- lib/MusicBrainz/Server/Entity/ArtistCredit.pm
- lib/MusicBrainz/Server/Entity/Collection.pm
- lib/MusicBrainz/Server/Entity/Event.pm
- lib/MusicBrainz/Server/Entity/Genre.pm
- lib/MusicBrainz/Server/Entity/Instrument.pm
- lib/MusicBrainz/Server/Entity/Label.pm
- lib/MusicBrainz/Server/Entity/Link.pm
- lib/MusicBrainz/Server/Entity/LinkAttribute.pm
- lib/MusicBrainz/Server/Entity/LinkTypeAttribute.pm
- lib/MusicBrainz/Server/Entity/Medium.pm
- lib/MusicBrainz/Server/Entity/Place.pm
- lib/MusicBrainz/Server/Entity/Recording.pm
- lib/MusicBrainz/Server/Entity/Relationship.pm
- lib/MusicBrainz/Server/Entity/Release.pm
- lib/MusicBrainz/Server/Entity/ReleaseGroup.pm
- lib/MusicBrainz/Server/Entity/Series.pm
- lib/MusicBrainz/Server/Entity/Track.pm
- lib/MusicBrainz/Server/Entity/URL/IMSLP.pm
- lib/MusicBrainz/Server/Entity/URL/Wikidata.pm
- lib/MusicBrainz/Server/Entity/URL/Wikipedia.pm
- lib/MusicBrainz/Server/Entity/Work.pm
- lib/MusicBrainz/Server/Entity/WorkAttribute.pm
- lib/MusicBrainz/Server/Entity/WorkAttributeType.pm
https://metacpan.org/pod/Perl::Critic::Policy::Moose::ProhibitMultipleWiths
Since this involves a lot of files, doing it in parts to ensure it's easier to find what broke if something does - this just for Entity::
> Avoid using multiple with in Entity:: files

- lib/MusicBrainz/Server/Controller/User/Edits.pm
This is not an exact match, since the edit search cannot currently match the "time of last vote by the selected user" edit sort `/votes` uses, but the content itself should be the same and allowing to refine it further seems sensible.
> MBS-12725: Add "Refine this search" link on Votes by [user] page

- root/artist_credit/ArtistCreditLayout.js
- root/entity/NotFound.js
- root/static/scripts/account/components/ApplicationForm.js
- root/tag/TagLayout.js
- root/utility/tableColumns.js
These were left behind because I guess my original regex didn't play well with `N_l` calls.
> Lowercase some more forgotten strings

- root/account/Register.js
- root/cdtoc/lookup.tt
- root/report/DuplicateEvents.js
- root/search/error/RateLimited.js
- root/static/scripts/account/components/ApplicationForm.js
- root/static/scripts/account/components/PreferencesForm.js
- root/static/scripts/common/components/Annotation.js
- root/statistics/Index.js
When reviewing checks in Weblate, I found those (mostly recent) messages with issues.
Only address messages that have been updated recently (or that already exist).
Additionally fixes three strings reported by Salo.Rock through Weblate.
Expected to be merged in `master`, then `beta` today.
> Fix some recently updated messages

- lib/MusicBrainz/Script/FixLinkDuplicates.pm
- lib/MusicBrainz/Script/JSONDump.pm
- lib/MusicBrainz/Script/JSONDump/Incremental.pm
- lib/MusicBrainz/Script/PruneCache.pm
- lib/MusicBrainz/Script/RemoveEmpty.pm
- lib/MusicBrainz/Script/RemoveExpiredSessions.pm
- lib/MusicBrainz/Script/RemoveUnreferencedRows.pm
- lib/MusicBrainz/Script/SampleDataDump.pm
- lib/MusicBrainz/Script/SubscriptionEmails.pm
- lib/MusicBrainz/Server/ControllerBase/WS/2.pm
- lib/MusicBrainz/Server/EditSearch/Predicate/EditNoteAuthor.pm
- lib/MusicBrainz/Server/EditSearch/Predicate/Editor.pm
- lib/MusicBrainz/Server/EditSearch/Predicate/Role/User.pm
- lib/MusicBrainz/Server/Form/User/Login.pm
- lib/MusicBrainz/Server/Report.pm
- lib/MusicBrainz/Server/Report/ReleasesWithEmptyMediums.pm
- lib/MusicBrainz/Server/Report/ReleasesWithNoMediums.pm
- lib/MusicBrainz/Server/Sitemap/Incremental.pm
- lib/MusicBrainz/Server/Sitemap/Overall.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Area.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Artist.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Label.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Place.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Recording.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Release.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/ReleaseGroup.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Work.pm
https://metacpan.org/pod/Perl::Critic::Policy::Moose::ProhibitMultipleWiths
Since this involves a lot of files, doing it in parts to ensure it's easier to find what broke if something does - this is for the rest of non-Controller:: files.
On top of https://github.com/metabrainz/musicbrainz-server/pull/2752
> Avoid using multiple with in misc files

- root/static/scripts/edit/URLCleanup.js
This fixes three flow errors in the recently merged otototy URL handling - not sure why they did not trigger CI failures.
> Fix Flow failures for ototoy links

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
This autoselects buymeacoffee.com URLs as patronage and does some basic cleanup. We have only 30 or so of these so not adding them to the sidebar yet.
Added a basic handling test.
> MBS-13452: Add patronage autoselect for Buy Me a Coffee URLs

- .circleci/config.yml
- docker/musicbrainz-tests/run_circleci_tests.sh
The way `git grep` has been run since https://github.com/metabrainz/musicbrainz-server/pull/3178 caused it to hang on until being [failed by CircleCI after 10 minutes without any output](https://circleci.com/docs/configuration-reference/#run).
Besides, I found two minor issues:
* Some of our tests were unannounced and remained silent when successful, making these tests invisible when reading CircleCI tests output.
* Weblate’s automatically pushed commits to the branch [`translations` were needlessly triggering CircleCI tests](https://app.circleci.com/pipelines/github/metabrainz/musicbrainz-server?branch=translations).
> Fix and improve CircleCI tests

- script/update_containers.sh
Gee, Brainz. What do ya wanna do tonight?
> Allow updating (prod) containers with hyphenated prefix

- root/area/AreaMerge.js
- root/instrument/InstrumentMerge.js
Yet two more pages which only admins should ever see.
None.
> Don't translate admin-only merge pages

- root/area/DeleteArea.js
- root/instrument/DeleteInstrument.js
> Do not translate DeleteArea/Instrument

- flow-typed/npm/redux_v4.x.x.js
- package.json
- root/admin/DeleteUser.js
- root/components/Artwork.js
- root/layout/components/sidebar/SidebarIpis.js
- root/layout/components/sidebar/SidebarIsnis.js
- root/report/LowDataQualityReleases.js
- root/user/ContactUser.js
- yarn.lock
See [the release notes](https://github.com/facebook/flow/releases/tag/v0.232.0) and commit messages.
> Upgrade Flow to 0.232.0 

- package.json
- root/types/entity.js
- yarn.lock
https://github.com/facebook/flow/releases/tag/v0.236.0 
Looked big enough to have some juicy new errors... but no.
> Update Flow to 0.236.0

- admin/ExportAllTables
Just noticed two small oversights, confirmed in the chat, while updating https://wiki.musicbrainz.org/MusicBrainz_Database/Download about the new EAA.
See commit messages
> Fix oversights when exporting all tables

- flow-typed/npm/knockout_v3.1.0.js
- package.json
- root/static/scripts/common/hooks/useEventTrap.js
- yarn.lock
https://github.com/facebook/flow/releases/tag/v0.237.0
> Upgrade Flow to 0.237.0

- package.json
- yarn.lock
> Update Flow to 0.242.1

- lib/MusicBrainz/Server.pm
- lib/MusicBrainz/Server/Controller/Dialog.pm
- lib/MusicBrainz/Server/Controller/Role/Create.pm
- lib/MusicBrainz/Server/Validation.pm
- root/admin/EditBanner.js
- root/admin/EditUser.js
- root/admin/attributes/AttributeEditFormGenericSection.js
- root/annotation/EditAnnotation.js
- root/edit/ModifyNote.js
- root/forms/DialogResult.js
- root/forms/dialog.tt
- root/layout/index.js
- root/server/components.mjs
- root/static/scripts/account/components/EditProfileForm.js
- root/static/scripts/collection/components/CollectionEditForm.js
- root/static/scripts/edit/components/FormRowTextArea.js
- root/static/scripts/edit/utility/isValidSetlist.js
- root/static/scripts/event/components/EventEditForm.js
- root/types/catalyst.js
- root/user/ContactUser.js
- root/user/ReportUser.js
- t/selenium/Event_Edit_Form.json5
MBS-13727: Unable to submit corrected event setlist
MBS-13731: Cannot add new events from "Add event" popup
See commits for details.
The diff is best viewed without whitespace changes.
Manual testing + added Selenium test cases.
I suggest that we hotfix this to production.
> MBS-13727, MBS-13731: Event edit form fixes

- flow-typed/npm/he_v1.x.x.js
- flow-typed/npm/redux_v4.x.x.js
- package.json
- root/artist_credit/ArtistCreditIndex.js
- root/components/TagEntitiesList.js
- root/layout/components/sidebar/EventSidebar.js
- root/static/scripts/common/components/Autocomplete2/formatters.js
- root/static/scripts/common/components/ReleaseEvents.js
- root/static/scripts/common/i18n/expand2.js
- root/static/scripts/common/utility/areDatePeriodsEqual.js
- root/static/scripts/common/utility/areDatesEqual.js
- root/static/scripts/common/utility/createFastObjectCloneFunction.js
- root/static/scripts/common/utility/isDatabaseRowId.js
- root/static/scripts/common/utility/isDateEmpty.js
- root/static/scripts/common/utility/relationshipDateText.js
- root/static/scripts/edit/components/DateRangeFieldset.js
- root/static/scripts/edit/externalLinks.js
- root/static/scripts/relationship-editor/components/DialogDatePeriod.js
- root/static/scripts/relationship-editor/components/DialogTargetEntity.js
- root/static/scripts/tests/utility/isDateEmpty.js
- yarn.lock
> Update Flow to v0.244.0

- package.json
- root/static/scripts/common/MB.js
- root/static/scripts/edit/components/withLoadedTypeInfo.js
- yarn.lock
> Update Flow to 0.248.1

- root/taglookup/Nag.js
As part of the changes in the donation system it has been decided to up the no-nag donation requirement to $5 a month (which would also give access to user flairs in LB and I guess eventually maybe in MB and elsewhere as well?).
This is calculated on the MetaBrainz site, but we do need to update the string about it.
> MBS-13816: Update no-nag requirement to $5/mo

- lib/MusicBrainz/Server/Controller/Artist.pm
- lib/MusicBrainz/Server/Data/ReleaseGroup.pm
- lib/MusicBrainz/Server/FilterUtils.pm
- root/artist/ArtistIndex.js
- root/context.mjs
- root/static/scripts/common/components/Filter.js
- root/static/scripts/common/components/FilterForm.js
- root/types/catalyst.js
- root/utility/sanitizedContext.mjs
- t/lib/t/MusicBrainz/Server/Controller/Artist/Filtering.pm
See comment messages for details. Tested with Nine Inch Nails on prod data, including testing `_find_artist_credits_by_artist_slow` by temporarily making `find_artist_credits_by_artist` always use that function.
> MBS-8186 / MBS-11950: Allow filtering unofficial and VA RG lists

- root/static/scripts/edit/utility/diffArtistCredits.js
The original change doesn't work properly when the separator is not Hebrew, as in https://beta.musicbrainz.org/edit/120833993
See https://tickets.metabrainz.org/browse/MBS-13908?focusedId=74897&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-74897
don't isolate parts, similarly to `ArtistCreditLink`
Tested with local server
> MBS-13908: don't isolate parts

- lib/MusicBrainz/Server/Entity/Work.pm
No server now expects writers anymore, so we should be able to get rid.
> Remove no longer needed writers property

- entities.json
- entities.mjs
- lib/MusicBrainz/Script/EntityDump.pm
- lib/MusicBrainz/Server/Data/ArtistCredit.pm
- lib/MusicBrainz/Server/Data/Role/GIDRedirect.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Medium.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Recording.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Release.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/2/ReleaseGroup.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Utils.pm
This is just a bit of refactoring for stuff I noticed while working on MBS-13768 - technically I guess `artist_credit_gid_redirect` being missing from sample data is a bug, but it's as minor as they get.
> Small gid_redirect improvements

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
MBS-13884
modify regex to suport A- type creatorid URL
JS tests
> MBS-13884: support more creatorid ACUM URLs

- flow-typed/npm/react-table_v7.x.x.js
- package.json
- root/static/scripts/edit/components/ArtistCreditBubble.js
- root/static/scripts/relationship-editor/components/RelationshipEditor.js
- root/static/scripts/relationship-editor/components/RelationshipEditorWrapper.js
- root/static/scripts/release/components/ReleaseRelationshipEditor.js
- root/static/scripts/series/components/SeriesRelationshipEditor.js
- root/static/scripts/tests/examples/todo-list/Todo.js
- root/static/scripts/url/components/UrlRelationshipEditor.js
- root/utility/hydrate.js
- yarn.lock
https://github.com/facebook/flow/releases/tag/v0.266.0
Many new errors due to the component typing changes.
> Upgrade Flow to 0.266.0

- lib/MusicBrainz/Server/Controller/User.pm
Somebody reported on MBS-13949 that they couldn't send a message to another editor, but there's no trace of the message in the mb-mail-service logs, and the musicbrainz-website logs for that date are no longer available.
This commit logs such errors to Sentry.
I don't have a local Sentry setup, so this hasn't been tested at all; but it follows the same template as other `send_message_to_sentry` calls, which all work fine.
> Log errors sending messages between editors to Sentry

- root/static/scripts/admin/components/PossibleSpammersList.js
- root/static/scripts/admin/components/SpammerButton.js
This was written before we moved from switch to match and merged without updating.
> Migrate spammers list to flow match

- package.json
- root/static/scripts/common/utility/isSpecialPurpose.js
- root/static/scripts/edit/components/FormRowTextList.js
- root/static/scripts/relationship-editor/utility/compareRelationships.js
- yarn.lock
Flow keeps giving versions out like candy, this PR brings us to the latest one again. See the associated commits for version links and upgrade notes.
> Upgrade Flow to v0.285.0 
