lib/MusicBrainz/Server/EditSearch/Predicate/AppliedEdits.pm
lib/MusicBrainz/Server/EditSearch/Query.pm
root/edit/search_macros.tt

This adds a new condition into [edit search](https://beta.musicbrainz.org/search/edits): "Applied Edit Count of Editor". It allows to filter search by number of applied edits associated with the user (editor). :mag_right:

MBS-2677: Add a way to filter search by edit count of the editor

---

lib/MusicBrainz/Server/Edit/Relationship/Create.pm
lib/MusicBrainz/Server/Edit/Release/AddReleaseLabel.pm
lib/MusicBrainz/Server/Edit/Release/Create.pm
lib/MusicBrainz/Server/Edit/Release/DeleteReleaseLabel.pm
t/lib/t/MusicBrainz/Server/Edit/Relationship/Create.pm
t/lib/t/MusicBrainz/Server/Edit/Release/AddReleaseLabel.pm
t/lib/t/MusicBrainz/Server/Edit/Release/Create.pm
t/lib/t/MusicBrainz/Server/Edit/Release/DeleteReleaseLabel.pm

Makes "add release," "add release label," "delete release label," and "add relationship" edits auto-edits, as decided during the summit.

More autoedits

---

lib/MusicBrainz/Server/Entity/Relationship.pm

I'm not really sure where the strings are coming from, since I can't reproduce this locally (I guess some are coming from the cache), but this is the most sure-fire way to ensure the JSON outputs numbers instead of strings.

MBS-8620: Force numeric context on relationship JSON linkTypeID

---

lib/MusicBrainz/Server/Constants.pm
lib/MusicBrainz/Server/Controller/Admin.pm
lib/MusicBrainz/Server/Controller/Edit.pm
lib/MusicBrainz/Server/Controller/Root.pm
lib/MusicBrainz/Server/Controller/User.pm
lib/MusicBrainz/Server/Data/Editor.pm
lib/MusicBrainz/Server/Edit.pm
lib/MusicBrainz/Server/Edit/Area.pm
lib/MusicBrainz/Server/Edit/Instrument.pm
lib/MusicBrainz/Server/Edit/Relationship/Create.pm
lib/MusicBrainz/Server/Edit/Relationship/Delete.pm
lib/MusicBrainz/Server/Edit/Relationship/Edit.pm
lib/MusicBrainz/Server/Email.pm
lib/MusicBrainz/Server/Entity/Editor.pm
lib/MusicBrainz/Server/Form/User/AdjustFlags.pm
lib/MusicBrainz/Server/Form/User/Report.pm
root/admin/edit_user.tt
root/layout.tt
root/static/styles/extra/banner.less
root/user/profile.tt
root/user/report.tt

cc @Freso @reosarevok
Adds an `$EDITING_DISABLED_FLAG` which when set disables editing/voting on an account, and displays a large banner message on every page (with the assumption that we won't ever set this flag without also contacting the user to explain why).
Also adds a UI for reporting editors for bad behavior, mostly copied from the UI for sending messages to editors. Except this sends a message to all the "account administrators" (since they're the ones who can toggle account flags).
Please review/comment on the list of options!

MBS-8208 and MBS-8271

---

lib/MusicBrainz/Server/Data/LinkAttributeType.pm
t/lib/t/MusicBrainz/Server/Edit/Instrument/Merge.pm
t/sql/initial.sql
t/sql/mbs-8639.sql

This was really annoying to fix. http://musicbrainz.org/edit/35820353 is stuck because http://musicbrainz.org/release/d769b4ac-cd35-39ab-833c-8933f2f128e5 contains this relationship: "drums, musical saw, other drums [stringdrum], percussion and tambourine: Björn Tollin (1994)."
So, that relationship contains a link attribute to "drums" (the merge target) and "other drums" (the merge source) with a `credited_as` value of "stringdrum." Since the credit makes the attributes differentiable, it tries to keep both post-merge, but you can only have one (link, attribute_type) pair in the `link_attribute` table, so it fails.
The solution here is, if there's only one conflicting attribute (like in this case), to just move the credit into the target's link attribute if it's empty. Otherwise, it …

MBS-8639: Instrument merge gives ERROR: duplicate key value violates unique constraint "link_attribute_pkey"

---

root/edit/details/historic/add_relationship.tt

Historic _Add relationship_ edits no longer displayed the source entity for the relationship. Re-add the corresponding `link_entity` macro call that was removed in commit 8639da7917a3ba1fcbf4d15bd9de6de9e70c8c86, apparently because it was no longer needed in the template for current _Add relationship_ edits (which have access to the verbose link phrase).

MBS-8648: Show source entity for old relationship edits

---

lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
root/static/scripts/release-editor/edits.js

If an edit throws `MusicBrainz::Server::Edit::Exceptions::NoChanges`, return a special `errorCode` in the /ws/js/edit response to indicate this, so we can just ignore it.
This is easy to reproduce if you open two instances of the release editor and try to make the same change in both, but it also happens in weird cases which are hard to reproduce, as described by Zas in the chatlog link in the ticket.

MBS-8641: Release editor breaks with "error: 0" if a submitted edit throws a NoChanges exception

---

lib/MusicBrainz/Server/Data/Series.pm
t/lib/t/MusicBrainz/Server/Controller/Work/Edit.pm
t/sql/initial.sql
t/sql/mbs-8636.sql

Ensure that `%relationships_by_link_order` is kept up-to-date based on where we plan to move things, not just based on what's currently in the database, to avoid all conflicts.

MBS-8636: Adding duplicate entities to a series causes an internal server error

---

lib/MusicBrainz/Server/Data/Edit.pm
lib/MusicBrainz/Server/Edit/Medium/Create.pm
lib/MusicBrainz/Server/Edit/Medium/Edit.pm
lib/MusicBrainz/Server/Edit/Release/Edit.pm
lib/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm
lib/MusicBrainz/Server/Edit/Role/AllowAmendingRelease.pm
t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
t/lib/t/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm

Makes the following edits auto-edits if entered within 1 hour of the original release add, by the same editor:
Add medium
Edit medium
Edit release
"Add release label" and "Remove release label" were already made auto-edits, but "Edit release label" was not, which doesn't make sense. So I just added the `AlwaysAutoEdit` role to `EditReleaseLabel` too, instead of the new `AllowAmendingRelease` role.

MBS-1880: Allow an editor to apply edits without voting within a short timeframe after his/her 'add release'

---

lib/MusicBrainz/Server/EditSearch/Query.pm
lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Relationship.pm
root/edit/search_macros.tt

Events were missing from edit search due to hard-coded entity lists. Add them to the templates and make the query parser use `entities_with`.

 MBS-8645: Enable searching for edits by an event

---

lib/MusicBrainz/Server/Form/User/EditProfile.pm
root/account/edit.tt

It was impossible to remove a location from an editor’s profile. The problem and fix was exactly the same as MBS-7437 (removing the area from places); see commit bc8d2635731f2541d9523dc4cf8c480f643c7876 for a detailed explanation.

MBS-8660: Fix removing an editor’s location

---

lib/MusicBrainz/Server/Edit/Area/Create.pm
lib/MusicBrainz/Server/Edit/Area/Edit.pm

The edit types for adding and editing areas did not have the new `DatePeriod` role added when the default value for the `ended` field was removed in commit 1616482a0e6681a810dcb7994601d81230dc87bd. With the code to set the `ended` value correctly missing, edits affecting non-ended areas tried to set the `ended` flag in the database to `NULL`, causing a constraint violation and an ISE. Fix this by adding the missing role.

MBS-8661: Fix adding and editing non-ended areas

---

root/user/profile.tt

On the user profile page, show the `last_login_date` (time when a user last entered their name and password) to account administrators and when someone is viewing their own profile.

MBS-8664: Show last login time in user profile

---

lib/MusicBrainz/Server/Controller/User.pm
root/user/profile.tt

1. Only show user-reporting link when logged in
The link to the form for reporting misbehaving users was shown even to anonymous users. This was inconsistent with related functionality such as contacting users. Only show the link when a user is logged in.
2. Redirect to profile instead of forwarding silently
When a user tried to report themselves, this was ignored, and the profile page shown under the `/report` URL. Instead, explicitly redirect to the profile page.

Small fixes to the “report user” feature

---

entities.json
lib/MusicBrainz/Server/Controller/Edit.pm
lib/MusicBrainz/Server/Data/Edit.pm
lib/MusicBrainz/Server/Data/Role/QueryToList.pm
npm-shrinkwrap.json
package.json
root/edit/list.tt
root/edit/subscribed-editors.tt
root/edit/subscribed.tt
root/static/gulpfile.js
root/static/scripts/common.js
root/static/scripts/voting.js

cc @reosarevok
This'll show all edits by default, and it reverses the sorting so that newer edits are shown first.
But if you check "Only show open edits (oldest first)." it'll sort them oldest-first, like before.
We'll see what people think about that. See comments on http://tickets.musicbrainz.org/browse/MBS-8647

MBS-8647: "Edits for subscribed entites" doesn't show auto-edits

---

lib/MusicBrainz/ErrorCatcherEmailWrapper.pm
lib/MusicBrainz/Server.pm
lib/MusicBrainz/Server/Connector.pm
lib/MusicBrainz/Server/Controller/Edit.pm
lib/MusicBrainz/Server/Exceptions.pm
lib/MusicBrainz/Server/Exceptions/Role/Timeout.pm
lib/Sql.pm
root/main/400.tt
root/main/500.tt
root/main/info/environment.tt
root/main/info/error.tt
root/main/timeout.tt

Database timeouts used to be treated as an internal server error, i.e. an email was sent to MetaBrainz employees about each timeout, and a rather technical error page with a stack trace shown to
the user. When, on the other hand, a request exceeded the allowable time, the server process was
immediately killed with a notice in the logs. The user was shown a plain nginx error page.
This, instead, suppresses error emails for both kinds of timeouts (but logs them) and shows a dedicated error page suggesting to reload the page, with a 503 status code (service unavailable). Instead of killing the process, an exception is thrown, allowing the normal error processing and cleanup to happen. This also makes the return-to-search-form feature of the edit search less fragile (it only worked when the …

MBS-8145: Treat timeouts differently from ISEs

---

root/components/common-macros.tt

Make the `bracketed` macro return an empty string instead of empty parentheses when it is given an empty string as input. This renders some guards in other macros unnecessary and fixes an issue in the
template for "Edit alias" edits [where such a guard was missing](https://github.com/metabrainz/musicbrainz-server/blob/4020e6faad0f639286aa49238a20bed3e5f7d99c/root/edit/details/edit_alias.tt#L24-L26).

MBS-7882: Make bracketed('') a no-op

---

lib/MusicBrainz/Server/Edit.pm

The changes in commit 909831ea267c19d7355db8a36a0d6f7ceba81e89 changed the default number of days an edit was to stay open to zero, because the `days` method on a `Duration` doesn't count days that are already included for `weeks`. Use `in_units` instead, which allows control over which units are to be considered.

MBS-8681: Let edits again expire after 7, not 0 days

---

lib/MusicBrainz/Server/Controller/Edit.pm

Use `does_role` in the edit search, too, because `->does` isn’t working there either. Currently, edit searches that time out show the generic timeout page instead of returning to the search form.

Use Moose::Util::does_role in another place

---

root/doc/bare_error.tt
root/doc/error.tt

Removes redundant code from the `doc/error` template (`doc/bare_error` is identical to the removed code, except for indentation) and fixes an encoding issue in the common code. The pull request is against beta (with the intention of continuing to production immediately at today’s release); [see here for justification](https://beta.musicbrainz.org/doc/%3Cscript%20type=%22text/javascript%22%3Ealert%28%22It%20is%20a%20XSS%20vulnerability.%20All%20your%20MB%20cookies%20are%20belong%20to%20us!%22%29;%3C/script%3E).

Fixes for /doc error pages

---

lib/MusicBrainz/Server/Edit/Alias.pm
lib/MusicBrainz/Server/Edit/Alias/Add.pm
lib/MusicBrainz/Server/Edit/Alias/Delete.pm
lib/MusicBrainz/Server/Edit/Alias/Edit.pm
lib/MusicBrainz/Server/Edit/Artist/Create.pm
lib/MusicBrainz/Server/Edit/Artist/Edit.pm
root/entity/alias/edit_form.tt
t/lib/t/MusicBrainz/Server/Edit/Artist/EditAlias.pm

Two variations of the same problem: We have database triggers that will enforce certain restrictions on the data; in particular, an artist with an end area must have `ended` set to true (MBS-8414) and a search hint alias can’t have locale, dates etc. (MBS-7572). However, the edit types didn’t know about this, and so it was possible that an edit stored an invalid combination (e.g. `end_area_id => 1234, ended => 0`). The edit would be displayed with the information “Ended: No”, but when it was applied, _ended_ would be set to true. I fix this by making sure that the edit data is consistent when an edit is created.
There is a minor UI thing here, too, that is somewhat related; interestingly, nobody has ever complained about it, so no ticket. In the edit form for an alias, when “search hint” …

MBS-8414/MBS-7572: Discrepancies between edit data and database

---

lib/MusicBrainz/Server/Data/Artist.pm
lib/MusicBrainz/Server/Data/Label.pm
lib/MusicBrainz/Server/Data/Series.pm
t/lib/t/MusicBrainz/Server/Edit/Artist/Create.pm
t/lib/t/MusicBrainz/Server/Edit/Label/Create.pm
t/lib/t/MusicBrainz/Server/Edit/Series/Create.pm

The ticket was about artists, but the same issue exists for labels and series, so I fixed those too.

MBS-8690: Rejecting add-entity edits with subscriptions

---

admin/CompileSchemaScripts.pl
admin/EditEdit.pl
app.psgi
lib/MusicBrainz/Server/Controller/Release.pm
lib/MusicBrainz/Server/Controller/ReleaseEditor.pm
lib/MusicBrainz/Server/Controller/Role/Create.pm
lib/MusicBrainz/Server/Controller/Work.pm
lib/MusicBrainz/Server/Data/Edit.pm
lib/MusicBrainz/Server/Edit/Area/Edit.pm
lib/MusicBrainz/Server/Edit/Artist/Edit.pm
lib/MusicBrainz/Server/Edit/CheckForConflicts.pm
lib/MusicBrainz/Server/Edit/Event/Edit.pm
lib/MusicBrainz/Server/Edit/Historic/Fast.pm
lib/MusicBrainz/Server/Edit/Instrument/Edit.pm
lib/MusicBrainz/Server/Edit/Place/Edit.pm
lib/MusicBrainz/Server/Edit/Utils.pm
lib/MusicBrainz/Server/Edit/Work/Edit.pm
lib/MusicBrainz/Server/Test.pm
script/qunit_test_data.pl
t/lib/t/MusicBrainz/Server/Controller/WS/js/Work.pm

This simplifies our JSON story somewhat, and avoids cases like the one described in the comment in app.psgi. (See: http://chatlogs.metabrainz.org/brainzbot/metabrainz/2015-12-03/?msg=3422352&page=5)
The reason I set an environment variable instead of just importing `JSON::XS` everywhere is, `JSON::XS` doesn't export things like `null`, `true`, `false`, etc., and it's also a huge amount of work to update everything, for questionable gain.
I did however use `JSON::XS` directly in various admin scripts, rather than making sure the environment variable is set everywhere.
In the process of fixing things, I converted the deprecated `jsonToObj` and `objToJson` methods to `decode` and `encode`, respectively.
Bizarrely, the `JSON::Any` `utf8` flag has the exact opposite meaning that `JSON` uses. …

Mandate JSON::XS and kill JSON::Any

---

root/release/edit/layout.tt
root/release/edit/tracklist.tt
root/static/scripts/release-editor/dialogs.js

MB's button to add another medium to a release is labeled "Add disc", but a lot of our releases don't have discs (they have cassettes, or USBs, or just folders in a download). So i renamed that to "Add medium", which is the more MusicBrainz-y term.
While i was at it  i changed the mentions of "tracklist" to say "medium" too, where it says "search for an existing tracklist", "Existing tracklist" and "To create a new tracklist, use an existing tracklist or".
[Link to the ticket](http://tickets.musicbrainz.org/browse/MBS-8482)
[Link to the GCI task](https://codein.withgoogle.com/dashboard/task-instances/6181327283945472/)
Sorry for this previous request, i didn't understand what is the role of "po" directory.
I think it should be ok now. :+1:

#MBS-8482 Renamed "Add Disc" button in release editor to "Add Medium"

---

lib/MusicBrainz/Server/Plugin/Translation.pm
npm-shrinkwrap.json
package.json
root/static/gulpfile.js

There were three quite unrelated issues here. The commits have additional info, but the summaries are:
* Locale::Messages strictly looks up msgids via bytewise comparison
* A msggrep wildcard of ours wasn't doing what was intended
* We were using the wrong po2json `format` option
I *think* my solution to the first bullet point shouldn't cause any unintended effects (those subroutines should only be called from the templates and with raw strings), but it could certainly use some sanity checking.

MBS-8635: Untranslatable strings

---

lib/MusicBrainz/DataStore/Redis.pm
lib/MusicBrainz/Server/Controller/Edit.pm
lib/MusicBrainz/Server/Controller/Root.pm
lib/MusicBrainz/Server/Data/Edit.pm
lib/MusicBrainz/Server/Data/EditNote.pm
root/components/common-macros.tt
root/edit/edit_header.tt
root/edit/list.tt
root/edit/notes-received.tt
root/edit/notes.tt
root/layout.tt
root/layout/components/Menu.js
root/layout/index.js
root/layout/menu.tt
root/server.js
root/static/gulpfile.js
root/static/scripts/common/utility/getCookie.js
root/static/scripts/edit/notes-received.js
root/static/styles/extra/banner.less

I hacked in a basic notification banner for when this page changes, using redis. It stores two keys per user; when they last viewed the page, and when it was last updated. (These expire in a month, so we don't store unused data indefinitely.) The latter is bumped in `Data::EditNote::add_note` (so now we have two problems, besides emails :)).
There's also a new option cookie on the page to disable the banner permanently. It can't be toggled by limited users.
One problem is that if someone were to load all the individual edits they received notes on, the banner still wouldn't go away until they loaded `/edit/notes-received`, which is strange, and I'm unsure of a good solution. (Perhaps there isn't one, except to wait for a proper notification system.)

MBS-8676: Add a page to see all notes left on your own edits

---

root/static/styles/layout.less

The medium header still had the `class="mp"`, but the CSS to turn it orange was missing.
This doesn’t completely match the style of the regular header, which has a bit of 3D. I leave fixing that to someone who cares. ;-) At least this fixes the functionality.

MBS-8241: Highlight mediums with pending edits

---

admin/RemoveExpiredSessions.pl
lib/Catalyst/Plugin/Session/Store/MusicBrainz.pm
lib/MusicBrainz/DataStore.pm
lib/MusicBrainz/DataStore/Redis.pm
lib/MusicBrainz/Script/RemoveExpiredSessions.pm
lib/MusicBrainz/Server/Data/Editor.pm
t/lib/t/MusicBrainz/DataStore/Redis.pm
t/lib/t/MusicBrainz/Server/Data/Editor.pm

Of the three types of session sub-keys used by Catalyst, only two had an expire time set in order to get them auto-removed from Redis when the session was no longer valid, but `expires` had not. This was introduced in commit e7e15ef, most likely unintentionally and a side effect of `expires` being treated specially for encoding purposes. It has led to the production Redis instance accumulating over 4.8 million keys since early 2013, most of which presumably are `expires` subkeys of long-gone Catalyst sessions.
Ensure that a Redis expire time is set for all session keys equally. This also adds a script that will clean out existing expired session keys, and does some cleanup for `MB::DataStore:Redis`.

MBS-8692: Set an expire time for all Catalyst session keys

---

root/edit/details/macros.tt

Relationship attributes can now contain HTML (instrument links); diffing them as regular text for edit display may lead to broken tags. Use HTML diffs instead.

MBS-8167: Use HTML diffs for relationship attributes

---

root/static/scripts/common/MB/Control/Autocomplete.js

Area names in containments were doubly encoded in the inline search; see the screenshot in the ticket.

MBS-8381: Don’t double-encode area names in inline search

---

lib/MusicBrainz/Server/Controller/Role/JSONLD.pm

A request for the JSON-LD of an entity was only honoured if its HTTP `Accept` header consisted of the exact string `application/ld+json`. Even adding a `q` value or a second acceptable MIME type caused the server to fall back to the standard HTML page.
This commit makes the server look for any occurrence of the JSON-LD type in the `Accept` header, which will fix the common scenarios mentioned above. However, it might cause new problems if clients use valid but unusual `Accept` headers (e.g. containing both `text/html` and `application/ld+json`, with the former being preferred).

MBS-8698: Be more flexible in identifying JSON-LD requests

---

lib/MusicBrainz/Server/Controller/Account.pm
lib/MusicBrainz/Server/Plugin/Diff.pm
lib/MusicBrainz/Server/View/Node.pm
root/components/common-macros.tt
root/doc/page.tt
root/edit/data.tt
root/layout/head.tt
root/layout/sidebar/shared-entity-sidebar.tt

This fixes more encoding issues that allow to inject HTML into pages; not via query parameters this time, but via entity names etc. from the database, so the Chrome XSS Auditor wouldn’t notice, I believe. On the other hand, an editor account is required to make an exploit.
- Various places in the templates where strings controlled by other editors weren’t encoded (collection names, Wiki pages, ).
- Our `Diff` plugin for TT deals with both encoded and unencoded strings in a complicated way and got it wrong in some places. This affected "Edit medium" edits in particular, for their two types of artist credit diffs. An example that broke horribly before is at http://chirlu.mbsandbox.org/edit/33191778
- One interesting case was the raw edit data page (e.g. …

More XSS fixes

---

lib/MusicBrainz/Server/Plugin/Diff.pm
root/components/common-macros.tt

We wrap entites in `<span class="name-variation">` if the displayed name is not identical to the true entity name so that client-side CSS can highlight them. However, there were some cases where this was done or omitted erroneously:
- If the display name is from a diff and already in HTML form, it is necessary not only to remove any `<span>` tags (for diff highlighting) before the comparison – we already did that – but also to undo the conversion of HTML reserved characters into entities. Otherwise, names containing one of the reserved characters were treated as a variation even when they were, in fact, identical to the entity name. (MBS-8330)
- Artist names in artist credit diffs from the `Diff` plugin were linked inside the plugin, using what was essentially a Perl reimplementation of …

Name-variation fixes (includes MBS-7844, MBS-8330)

---

lib/MusicBrainz/Server/EditSearch/Predicate/ID.pm

Because the “ID” edit search predicate class is used not only for IDs, but also other numbers such as the Yes/No vote counts, the recently improved validation for database row IDs broke those other criteria.
Re-allow 0 (which does not cause problems when used in a database query; it will simply never find anything) as a temporary solution until the predicate class hierarchy is improved.

MBS-8694 (beta): Re-allow 0 for edit search “ID” fields, for now

---

lib/MusicBrainz/Server/Filters.pm
root/components/common-macros.tt
root/entity/details.tt
root/entity/edits.tt
root/relationship/header.tt
root/url/index.tt
root/user/profile/layout.tt

This is the first part of a number of loosely URL-related improvements. Having only one pull request would make it difficult to review.
The main change here is to give all the link macros the responsability to entity-encode their parameters, instead of the callers having to do that (who will forget it). This affects the hover text (`title` attribute) and the `href` attribute itself.
Other changes are the removal of the `display_url` macro, because it didn’t serve any useful purpose, and of the `generic_link` macro, which two templates had locally to do the same as `simple_link`.
Finally, this has a fix for MBS-8413, where deleted URL entities (in the edit history) were doubly percent-encoded, breaking the link.

URL fixes, part 1 (includes MBS-8413)

---

lib/MusicBrainz/Server/Entity/URL.pm
lib/MusicBrainz/Server/Entity/URL/ASIN.pm
lib/MusicBrainz/Server/Entity/URL/Ozon.pm
root/components/common-macros.tt
root/doc/bare_error.tt
root/entity/details.tt
root/main/400.tt
root/main/403.tt
root/main/404.js
root/main/500.tt
root/server.js
root/user/profile.tt

More about URLs:
- Remove the `url_escape` macro and all uses of the `url` filter (all bugs, the `html` filter was intended).
- Fix report-a-bug links on error pages: They used the wrong JIRA base URL that doesn’t fully accept seeding, had double-encoding issues, and (due to a mistake I made when preparing this patch series) still used the `display_url` macro that was already removed in part 1.
- In some cases, URIs inside an URL entity were changed unintentionally. Use `clone` to operate on copies instead.

URL fixes, part 2

---

lib/MusicBrainz/Server/Plugin/Diff.pm

Please look at the two commits for explanation.
Result: http://chirlu.mbsandbox.org/edit/18645604 vs. https://beta.musicbrainz.org/edit/18645604

Split both before and after separator for diffs (fixes MBS-5205)

---

root/static/scripts/edit/URLCleanup.js

I regex'ed a negative lookahead for "search" and "tags" after soundcloud.com to block all URLs calling those endpoints by using (?! ___ ).
Additionally, I added a missing validator script for LINK_TYPES.soundcloud.series
[MBS-8713](http://tickets.musicbrainz.org/browse/MBS-8713)

MBS-8713 (Block /search and /tags SoundCloud URLs)

---

lib/MusicBrainz/Server.pm
lib/MusicBrainz/Server/Entity/URL.pm
lib/MusicBrainz/Server/Entity/URL/Commons.pm
lib/MusicBrainz/Server/Entity/URL/Facebook.pm
lib/MusicBrainz/Server/Entity/URL/IMSLP.pm
lib/MusicBrainz/Server/Entity/URL/LastFM.pm
lib/MusicBrainz/Server/Entity/URL/MediaWiki.pm
lib/MusicBrainz/Server/Entity/URL/SoundCloud.pm
lib/MusicBrainz/Server/Entity/URL/VIAF.pm
lib/MusicBrainz/Server/Entity/URL/VK.pm
lib/MusicBrainz/Server/Entity/URL/Wikidata.pm
lib/MusicBrainz/Server/Entity/URL/Wikipedia.pm
lib/MusicBrainz/Server/Filters.pm
root/entity/edits.tt
root/url/header.tt
root/url/index.tt
t/lib/t/MusicBrainz/Server/Controller/URL/Show.pm

Percent-encoded UTF-8 in the local part of URLs has long been decoded for display, but punycoded internationalized domain names were shown as raw ASCII.
This uses the existing IRI support of the `URI` module to decode all parts of URLs at the same time. Some new attributes (so that the decoding only has to be done once) are added to the URL base class for access to the decoded URL or just the decoded local part and for checking whether the local part was in some non-UTF-8 legacy encoding.
Finally, the `pretty_name` method of the base class and overridden display names in the subclasses make use ofthe decoded form, as do two templates that don’t use `pretty_name` but always show the actual URL.
Additional changes:
- One of my previous related pull requests left a spurious `</a>` that is …

URL fixes, part 3 (mostly internationalized domain names/MBS-8683)

---

lib/MusicBrainz/Server/Authentication/Store.pm
lib/MusicBrainz/Server/Controller/Root.pm
t/lib/t/Mechanize.pm
t/lib/t/MusicBrainz/Server/Controller/Admin/DeleteEditor.pm

Deleted users that still had a Catalyst session, possibly on another computer or in a different browser, could be active on the site until that session expired. (They could not log in again, even if they had set a new password during that time.) When trying to restore a user from a session, check for the deleted flag and deny restoration when indicated.

MBS-6166 once more: Don’t restore deleted users that still have a Catalyst session

---

lib/MusicBrainz/Server/Controller/User.pm

For user tag pages, the entity types were sorted using the `<=>` operator. Since this operator treats its operands as numbers, the strings `"release"`, `"recording"` etc. were all the same to it, having the numerical value 0. As Perl’s sort is not guaranteed to be stable, the resulting order was unpredictable.
Use `cmp` instead, the operator for lexicographic comparison of strings.

MBS-8688: Use consistent order for entity types on tag pages

---

lib/MusicBrainz/Server/Form/Field/DatePeriod.pm
root/static/scripts/relationship-editor/common/dialog.js

I fixed a spelling mistake in one string (it’s _proceed_, but _precede_), then used the corrected string in another place where the same thing was explained in less clear words.

Two string improvements

---

lib/MusicBrainz/Server/Data/Application.pm
lib/MusicBrainz/Server/Data/CDStubTOC.pm
lib/MusicBrainz/Server/Data/CDTOC.pm
lib/MusicBrainz/Server/Data/Editor.pm
lib/MusicBrainz/Server/Data/EditorOAuthToken.pm
lib/MusicBrainz/Server/Data/Entity.pm
lib/MusicBrainz/Server/Data/LinkAttributeType.pm
lib/MusicBrainz/Server/Data/Role/GetByGID.pm
lib/MusicBrainz/Server/Data/Tag.pm

The majority of places that use `_get_by_keys` wrap the result in `values %{}`, so it makes more sense to just return a list.
This was part of my MBS-7241 branch, but since it's taking me a while to finish that, I'm submitting this for review now.

Make _get_by_keys return a list instead of a hash reference

---

admin/CalculateRelatedTags.sh
admin/cron/daily.sh

Judging by the last_updated timestamps, this script has been broken since 2014-11-17. We can enable it again once it works, and once we have an actual use for it, perhaps when we do something with genres.
I think this is partially responsible for the daily script always emailing us, since it always results in a division by zero error.

Remove CalculateRelatedTags.sh from daily.sh

---

Makefile.PL
lib/MusicBrainz/Server/Edit/CheckForConflicts.pm
lib/MusicBrainz/Server/Edit/Medium/Edit.pm
lib/MusicBrainz/Server/Edit/Role/EditArtistCredit.pm
lib/MusicBrainz/Server/Edit/Utils.pm
t/lib/t/MusicBrainz/Server/Edit/Medium/Edit.pm
t/sql/mbs-8752.sql

Looks like we finally found a reproducible case where Algorithm::Merge is the culprit for buggy behavior (see rationale in MBS-7475). Using Text::Diff3 instead causes it to not drop tracks in the test I added, and the rest of our Edit:: tests still pass. I haven't done extensive testing outside of that—I'm not sure how many of our Edit:: tests go through CheckForConflicts, actually.

Replace Algorithm::Merge with Text::Diff3 (MBS-7475, MBS-8752, ...)

---

lib/MusicBrainz/Server/View/Node.pm
root/layout/components/Footer.js
root/layout/components/Menu.js
root/layout/components/Search.js
root/main/404.js
root/server.js

I had an idea that we could eventually use `x-accel-redirect` in production for our JS template renderer. Which has the potential to dramatically improve performance. But that can't work if we have these special markers in the response that need to be processed by the perl. This PR removes those.
The benefits of `uri_for` and `uri_for_action` are mainly that (1) the URLs are path-checked and type-checked, in a way, at run-time (but, that also causes problems during deployment), (2) you can change an action's URL without changing the internal path (not that we've done that often), and (3) they can give a decent hint as to what controller the action is in.
The downsides are that the replacement magic prevents us from using `x-accel-redirect`, and that they can't be used on the client …

Remove uri_for* from JS templates

---

lib/MusicBrainz/Server/Controller/Root.pm

The banner message (if any) was assigned to a local variable that was shadowing the variable that it should have been assigned to. Consequently, when the inner variable went out of scope, the banner message text was gone and could no longer be shown.

MBS-8770: Load banner message correctly

---

admin/nginx/mbserver-rewrites.conf
root/layout/components/Menu.js
root/layout/menu.tt

Much less uses than the contact us page so probably not worthy of a constant? 
As before, there's an entry in admin/nginx/mbserver-rewrites.conf that I decided not to touch. Let me know if I should.

Update team link to the MeB Team page

---

root/components/common-macros.tt
root/components/relationship-editor.tt
root/edit/details/macros.tt

This should mean both add and edit rel edits show "(ended)" instead of the former showing "ended". This is also apparently used somewhere in series but I can't see any reason why we'd want a bare "ended" when linking to a rel anyway.

MBS-8790: put parens around ended

---

root/static/styles/entity.less

This changes the old tabs to fit a bit more - orange + white text on selected to match the header, white background elsewhere, rounded corners, lighter borders, a purple border on hover because purple and all. It makes the font a bit bigger (or well, no longer @small-text) because it felt a bit too small to me but happy to change that if needed.
Available to check at my sandbox, e.g. http://reosarevok.mbsandbox.org/artist/ebe3e32c-99f5-46a3-8c15-bac2ab5b8e4d

MBS-8797: make tabs fit the current style a bit more

---

root/static/styles/layout.less

I feel this is more consistent. Also, white on hover makes the number more visible.

MBS-8798: invert paginator colours, make hover text white

---

lib/MusicBrainz/Server/Edit/Artist/Edit.pm
t/lib/t/MusicBrainz/Server/Edit/Artist/Edit.pm

An artist edit can remove the artist’s type or gender by setting it to `NULL` (represented by `undef` in Perl). On the other hand, it can leave fields unchanged (represented in Perl by the absence of a hash entry). Because of a test for definedness instead of existence of a key before falling back to the current state of the artist, it could happen that an edit was rejected for resulting in a group artist with a gender when that was not actually the case.
Includes a test.

MBS-8801: Fix spurious group-with-gender error

---

root/user/edits.tt

cc @reosarevok 
9e2e988 made it so that "open edits"/"all edits" are no longer tabs on the user's profile, and I think it's kind of strange/confusing to show the tabs if the current page isn't part of the tab group. So this removes them and links to the user in the heading instead.

Remove user tabs from edit listings

---

root/static/styles/layout.less

Vertically center the search box between the top of the page and the horizontal line, as suggested by @MonkeyDo.

Vertically center the search box

---

lib/MusicBrainz/Server/Edit/CheckForConflicts.pm
lib/MusicBrainz/Server/Edit/Utils.pm
t/lib/t/MusicBrainz/Server/Edit/Event/Edit.pm

Broken in 6a8e2e6127cbdec3e23590368e78c2490c200768
This ISE can occur if the time being set is already the current value.
The source of the bug is due to the change in parameter order associated with Text::Diff3's merge subroutine.
Before the referenced commit, CheckForConflicts hashed the results of merge_time in the order (ancestor, current, new), which would be something like [['19:30', '19:30'], ['19:00', (DateTime object)], ['19:00', '19:00]], where the first value in each array ref is the key. Since the last two array refs have the same key, the second would override the first.
After 6a8e2e6, those array refs are hashed in the order new, ancestor, current, which means the DateTime object is the result.
The fix here is to revert the change in the order they're hashed (new should be …

MBS-8837: rare ISE editing event time

---

lib/MusicBrainz/Server/Controller/WS/2/Release.pm
lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Release.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelease.pm

`inc=user-collections` will return private (and public) collections for the authenticated user. It does not imply `inc=collections` (which returns all public collections).
Was probably wrong to not do this in the previous PR. Should help fix one or two Picard tickets.

Add inc=user-collections to /ws/2/release (MBS-6152)

---

lib/MusicBrainz/Server/Controller/WS/2/Release.pm
lib/MusicBrainz/Server/WebService/XMLSerializer.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelease.pm
t/sql/mbs-7914.sql

Doesn't make sense to output aliases for recording artists but not track artists. Note that we already don't output the track AC at all if it's the same as the recording AC.
This will output duplicate data if the track and recording ACs share any artists. But I'd rather do that than have some weird rule that makes parsing the data like a puzzle (e.g., outputting track artist aliases where the artist doesn't appear in the recording AC, or something).

Output track artist aliases in /ws/2/release (MBS-7914)

---

lib/MusicBrainz/Server/Controller/Area.pm
lib/MusicBrainz/Server/Controller/Event.pm
lib/MusicBrainz/Server/Controller/Label.pm
lib/MusicBrainz/Server/Controller/Role/CommonsImage.pm
lib/MusicBrainz/Server/Controller/Series.pm
lib/MusicBrainz/Server/Controller/Work.pm
lib/MusicBrainz/Server/Data/Role/MediaWikiAPI.pm
lib/MusicBrainz/Server/Data/WikidataProperties.pm
root/area/layout.tt
root/event/layout.tt
root/label/layout.tt
root/series/layout.tt
root/work/layout.tt

For example, to get image for label [bf519cd2-4e1e-46bf-948b-615f75424606](https://beta.musicbrainz.org/label/bf519cd2-4e1e-46bf-948b-615f75424606) we can use https://www.wikidata.org/w/api.php?action=wbgetclaims&format=json&entity=Q330629&property=P154.
*http://tickets.musicbrainz.org/browse/MBS-6381*

MBS-6381: Fetch images for entities from Wikidata

---

lib/MusicBrainz/Server/Controller/Role/Collection.pm
t/lib/t/MusicBrainz/Server/Controller/Collection/New.pm

Missed an arg to load private collections for the current user, when I refactored the `find_by` stuff.

MBS-8848: Own private collections ignored on entity pages

---

lib/MusicBrainz/Server/Controller.pm
lib/MusicBrainz/Server/Sitemap/Overall.pm

Double the number of items per page as per	MBS-8591 - the idea would be to put it on beta and see if it makes it noticeably slower (it doesn't seem to affect my sandbox much, but that's so horribly slow the difference is likely to be hard to notice there in the first place).

MBS-8591: up items per page to 100

---

root/user/profile.tt

I *think* this should work just fine, although I couldn't test it because every user seems to have a last login date in my sandbox.

MBS-8861: adding text if last login is empty

---

INSTALL.md

bzip2 is not default installed on CentOS systems, so provide general instructions to do this always, even for other systems.

Instructions to install bzip2

---

root/static/scripts/edit/check-duplicates.js

Gets `sourceEntityGID` from the window location instead of `MB.sourceEntityGID`, in case the relationship editor code isn't running first for some reason (even though the script is outputted first on the page).

MBS-8874: Editing an entity sometimes shows it as a possible duplicate of itself

---

INSTALL.md
README.md

We currently use #metabrainz for MusicBrainz server development discussion and https://community.metabrainz.org/ has replaced the mailing lists.

Update IRC and mailing list references.

---

INSTALL.md
admin/sql/CreateIndexes.sql
admin/sql/DropIndexes.sql
admin/sql/Extensions.sql
admin/sql/sitemaps/CreateFKConstraints.sql
admin/sql/updates/20141226-geodesic-index.sql
upgrade.json

Create the `earthdistance` extension and use it for a geodetic index on the `place` table, enabling fast queries for places near a given point or within a given region.

MBS-8800: Add a geodetic index on place

---

lib/MusicBrainz/Server/Controller/OAuth2.pm
t/lib/t/MusicBrainz/Server/Controller/OAuth2.pm

The /userinfo endpoint currently provides no invariant data about the user - the name and email can change. 3rd party applications that store additional information about users need invariant data to reliably match their own information to the user information from MusicBrainz.
This PR introduces an ID field into the /userinfo response, which contains the internal database ID of the user. As this is the user's PK, this is unlikely to change.

Added metabrainz_user_id field containing $c->user->id to /userinfo endpoint response

---

root/release/edit/editnote.tt
root/static/scripts/release-editor/edits.js

If the response contains an object with a "message" property, that should be what's displayed, not the object itself.

MBS-8928: Properly display not-logged-in error

---

admin/sql/updates/20151223-edit-note-index.sql
admin/sql/updates/20160429-mbs-8656.sql
upgrade.json

I included `edit_note_idx_post_time_edit` in here too, as mentioned in https://github.com/metabrainz/musicbrainz-server/pull/271#issuecomment-208104239

MBS-8656: Bring edit table indexes back into sync

---

admin/sql/updates/20160507-mbs-8669.sql
upgrade.json

According to the ticket this can go in slave_only, but it should be harmless to run it everywhere just in case.

MBS-8669: Primary keys for place tables missing on old slaves

---

lib/MusicBrainz/Server/Data/Edit.pm

After inserting a new edit, the `post_insert` hook is called, then the edit updated in case the hook changed the status, type, or data of the edit. However, no `post_insert` method actually does this, so remove the unnecessary update.

Skip unnecessary update of a recently created edit

---

t/lib/t/MusicBrainz/Server/EditQueue.pm

We need two different mock edit types for the `EditQueue` tests: one that provides access to real votes from the database, and one that also mocks the vote counts. Split `MockEdit` accordingly.

Split MockEdit class from EditQueue tests into two

---

lib/MusicBrainz/Server/Controller/Root.pm

Since banner message editors tend to forget about messages that they have dismissed previously and do not remove them, limit the effect of dismissing a banner to 20 hours for them. After that time, the banner will be reshown, but can be dismissed again (for another 20 hours). For regular users, the dismissal remains permanent as before, i.e. the banner will be hidden until a new banner message is set.

MBS-8940: Make banner dismissal temporary for banner editors

---

admin/replication/ProcessReplicationChanges

There was another instance of a `musicbrainz`-only `search_path`. This caused applying replication packets to fail.

Fix the search_path for replication

---

lib/MusicBrainz/Server/Controller/Release.pm
lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Release.pm

This may fix the image previews Facebook generates when you link to a release page there. Thanks to @zas for reporting and helping test this.

Serialize front cover in release index JSON-LD

---

root/static/scripts/edit/components/ArtistCreditEditor.js

When all of the ArtistCreditEditor components mount, they each try to take over the (one) AC bubble on the screen. This can become a problem if you open the release AC bubble before mediums have loaded. If that happens, you'll likely end up editing the last track AC instead.

MBS-8941: ACs don't change with release artist

---

root/static/scripts/common/components/Autocomplete.js

Setting the value also resets the cursor position, so don't set it unless the value actually changed.

MBS-8942: Keep cursor position in artist field

---

lib/MusicBrainz/Server/Sitemap/Overall.pm

I hope this silences the cron emails we get every day where the entire message is just:
```
NOTICE:  table "tmp_sitemaps_artist_direct_rgs" does not exist, skipping
NOTICE:  table "tmp_sitemaps_artist_va_rgs" does not exist, skipping
NOTICE:  table "tmp_sitemaps_artist_direct_releases" does not exist, skipping
NOTICE:  table "tmp_sitemaps_artist_va_releases" does not exist, skipping
NOTICE:  table "tmp_sitemaps_artist_recordings" does not exist, skipping
NOTICE:  table "tmp_sitemaps_artist_works" does not exist, skipping
NOTICE:  table "tmp_sitemaps_instrument_recordings" does not exist, skipping
NOTICE:  table "tmp_sitemaps_instrument_releases" does not exist, skipping
```
Attempted this earlier in 6df8378, which is now reverted here because I apparently thought these messages were from …

Silence overall sitemaps cron

---

admin/sql/CreateFunctions.sql
admin/sql/updates/20160602-mbs-8963.sql
lib/MusicBrainz/Server/Data/EditNote.pm

Stop storing rows in `edit_note_recipient` for edit notes left by the author of the edit. Makes the table a lot smaller and removes the need for a filter in `Data::EditNote::find_by_recipient`.
This means the table no longer maps any arbitrary edit note to the edit author. But we don't need to use it like that.

Don't populate edit_note_recipient for own notes (related: MBS-8963)

---

lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
root/release/edit/information.tt

Add a maxlength attribute to the `<input />`, and if something somehow gets through, silently truncate it.

MBS-7963: Prevent >255-char release comments

---

admin/sql/CreateIndexes.sql
admin/sql/updates/20160604-mbs-8951.sql
lib/MusicBrainz/Server/Data/EditNote.pm

I guess old edit notes don't have a post time. Sort these last so that /edit/notes-received behaves correctly.

MBS-8951: Make recent notes handle NULL post_time

---

lib/MusicBrainz/Server/EditSearch/Predicate/RelationshipType.pm

Tested this locally and the search doesn't ISE anymore.

MBS-8977: Edit searches with relationship type conditions cause an internal server error

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

(Most of ASINs nowadays start with a `B01` sequence.)
Extend the strict regex to ASINs starting with a `B`.
Add the corresponding test.

MBS-8809: ASIN cleanup can be defective

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

- Normalize to `https://www.musik-sammler.de/(album|artist|media)/(id|clean-name)/`
- Add corresponding tests

MBS-7111: Improve URL matching of Musik-Sammler.de

---

lib/MusicBrainz/Server/Report.pm

Adds back the `$join_sql` bit which was accidentally removed in 2d64080751192bb234ee1327ebc41df6db3530d2

MBS-8983: Fix report subscription filtering

---

root/components/aliases.tt

An alias was put verbatim into the aliases page, even when it contained special characters. It was a bit better for the sort name, which was escaped, but `<bdi>` tags were missing on both.

MBS-9000: Escape and bidi-isolate entity aliases

---

root/static/scripts/edit/externalLinks.js

This makes it so that the URL cleanup is only run on seeded URLs, not ones that already exist. If you actually modify an existing URL, it'll trigger a cleanup, but as long as you don't touch it, no mysterious edits will be submitted anymore.

MBS-8987: Don't run URL cleanup on existing URLs

---

root/release/merge.tt

`[% form.errors %]` can be an array if there are multiple errors. The only errors that should be possible to trigger by direct user input are for the medium positions, so just display the errors for those fields inline.

MBS-8996: Display merge append errors correctly

---

root/release/edit/tracklist.tt

This broke when we released the new AC editor stuff, because now that's all in its own table (and the table is embedded in a single cell). Previously, the release editor had the open-ac button in a separate column.

MBS-8999: Track lengths are in the wrong table column in the release editor

---

lib/MusicBrainz/Server/Data/ArtistCredit.pm
t/sql/series.sql

When `Data::ArtistCredit::get_by_ids` was called with IDs that didn’t actually exist, it returned empty `ArtistCredit` entities for them. Those were then automatically put into the cache and persisted there. When an artist credit with the relevant ID later actually was created, the empty artist credit was displayed in its place until the old cache entry expired (MBS-8806). It is unclear how `get_by_ids` could be called with a not-yet-existing ID.
Only create and return an `ArtistCredit` entity for IDs actually found in the database. Also emit a stack trace when a non-existent ID is encountered in order to aid further debugging.

MBS-8806: Don’t cache non-existent ACs as empty

---

root/edit/search_macros.tt

Unfortunately, the string extractor for templates is not sophisticated enough to detect strings that are split into multiple parts and combined with the concatenation operator (`_`). It only finds the first part, which is then used as the ID in the translation files, breaking gettext.
Undo a split made in commit c4c1d1ae74b05528de6b73a1294524dc5402bd01.

Correct a translated string

---

lib/MusicBrainz/Server/Constants.pm
lib/MusicBrainz/Server/Data/Artwork.pm
lib/MusicBrainz/Server/Data/Entity.pm
lib/MusicBrainz/Server/Validation.pm
t/lib/t/MusicBrainz/Server/Data/Artwork.pm
t/lib/t/MusicBrainz/Server/Validation.pm

IDs in the Cover Art Archive are `BIGINT`s, but they were only accepted as valid if they were in the range of an `INT`. This caused cover art not to be loaded in the normal way for edits, and also caused spurious warnings by `get_by_any_id(s)`.
Add a new `is_valid_id` method to `Data::Entity` and override it for `Data::Artwork` to allow `BIGINT` values.

Correctly validate Cover Art Archive IDs

---

lib/MusicBrainz/Server/Entity/CommonsImage.pm
root/static/images/attribution.txt
root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js
root/static/scripts/tests/externalLinks.js

All Wikimedia projects are https-only now; http requests will be redirected. In light of this and the fact that the external links editor will no longer run cleanup on unchanged pre-existing URLs (MBS-8987), make the URL cleanup code change Wikipedia and Wikidata URLs to https. Also link to Wikimedia Commons using https.
Includes some related updates in tests and documentation.

MBS-8451: Turn WP/WD URLs into https on cleanup

---

admin/InitDb.pl
admin/functions.sh

As it happens, I had recently also stumbled over the outdated Postgres version check now fixed in #334. Here are some related improvements: A typo in the error message, using the machine-readable Pg version instead of parsing the human-readable version (which is guaranteed to keep its format, see https://www.postgresql.org/message-id/4422.1465937807%40sss.pgh.pa.us), and removing an unused version comparison function.

Postgres version fixes

---

lib/MusicBrainz/Server/WebService/JSONSerializer.pm
root/static/scripts/common/MB/Control/Autocomplete.js

When considering primary aliases for display in the inline search, aliases in the interface language or in English are preferred. However, if none of these exist, any random language was chosen. (E.g., a German user might have been presented with the Japanese or Arabic alias, which they are unlikely to be able to read.) Stop using such random fallback aliases.
In cases where a (matching) alias exists, it is no longer necessary to display the sort name, whose only purpose is to provide a rudimental Latin-script version (cf. MBS-7404).

MBS-7903: Only show a matching, not any primary alias

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Guess type of RA links, either `otherdatabases` or `review`, rather than `otherdatabases` only.

MBS-8148: Identify ResidentAdvisor reviews as such

---

root/static/scripts/edit/utility/linkPhrase.js

Remove spurious spaces left from relationships attributes, especially disturbing for tree indentation.

MBS-8301: Fix the cleaning of relationships link phrases in the editor interface

---

lib/MusicBrainz/Server/Controller/Edit.pm
lib/MusicBrainz/Server/EditSearch/Predicate.pm
lib/MusicBrainz/Server/EditSearch/Predicate/EditorFlag.pm
lib/MusicBrainz/Server/EditSearch/Query.pm
lib/MusicBrainz/Server/Entity/Editor.pm
root/edit/search_macros.tt

This flag is only supposed to be set by and visible to account admins, so this can be considered a privacy breach. cc @Freso who alerted this to me.

Only allow admins to search for untrusted users

---

root/static/styles/extra/user.less
root/user/profile.tt

Each row of the _General Information_ block is now grouped into a `dl`
element, so to avoid misalignment when the translated header is large.
(It uses almost the same approach than `/relationships` pages.)
Update the stylesheet accordingly.

MBS-9042: Fix misaligned rows in user profile for translated UI

---

root/static/scripts/edit/externalLinks.js

Previously, validation rules were applied to all URL relationships. Errors were triggered for existing URLs that do not validate newly created validation rules.
This branch skips applying validation rules for untouched existing URLs.  Modifying an existing URL or seeding/adding a new one would trigger the rules. Editors won’t be blocked anymore by unexpected errors on existing URLs.

MBS-9048: Don’t validate untouched existing URLs

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Removes query strings (such as `?lang=en-gb` or `?ref_src=example.com`), possible anchors (`#content-main-heading`), and sub-paths (such as `/media` or `/status/47830`) from Twitter URLs.

MBS-8793: Improve Twitter URLs’ clean-up

---

root/static/scripts/tests/Control/URLCleanup.js

Previously, only `guessType` and `cleanURL` functions of URLCleanup component were tested, separately.
This patch merges both tests and adds support to  test `validationRules` functions. It also tests that clean URL still matches the same relationship type as input URL.
- First commit message gives extensive implementation details.
- Second commit one-to-one converts all existing tests.
- Further commits merge redundant tests and fix some erroneous ones disclosed by the conversion.
- Last commit finally adds some validation tests.

MBS-6378 & MBS-5736: Rework URLCleanup tests to support validation

---

lib/MusicBrainz/Server/Controller/Root.pm

The contents of the tagger port URL parameter are stored in the user session and later included in various generated pages. Since there used to be no validation, arbitrary text could be injected (a XSS
vulnerability).
Make sure that the tport value is a number (of at most five digits); report an invalid request otherwise.

MBS-9072: Validate the tagger port URL parameter

---

lib/MusicBrainz/Server/Form/CoverArt.pm
t/lib/t/MusicBrainz/Server/Controller/Release/AddCoverArt.pm

The `comment` field for cover art edits used `Field::Comment`, which otherwise is used for entity disambiguation comments and therefore imposes a maximum length on the field contents. Use an unrestricted `Field::Text` instead.

MBS-9069: Allow cover art comments to have arbitrary length

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Previously, it was not handy to define validation rules for `otherdatabases` URLs, because validation rules had to be defined separately for each entity type whereas there were much more other databases.
Changes caused by this improvement:
- `LINK_TYPES` no longer contain fictive duplicate IDs
- `CLEANUPS` are website `match`-related before relationship `type`-related
- New validation rules can be defined in `CLEANUPS.*.validate` and are stricter than old ones:
- Matched URLs could be blocked for other relationship types if `type` does not match
- Matched URLs could be blocked for other entity types if `type` does not match
- Matched URLs could be blocked if unclean
Old validation rules are still supported. Ultimately, all of them should be converted.
Additionally, other restricted URL …

MBS-5733: Allow to validate `otherdatabases` URL relationships

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js
root/static/scripts/tests/release-editor/edits.js

Some improvements for Discogs URLs:
- Better validation – disallow anything that doesn’t have the proper format.
- Drop everything after the ID (fixes MBS-9012 in particular).
- Harmonize to HTTPS URLs.
This also removes the remaining support for old URLs that didn’t contain a numerical ID.

Discogs URL cleanup/validation improvements (includes MBS-9012)

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Some improvements related to Wikimedia Commons:
- Recognize `commons.m.wikimedia.org` URLs and remove the `m.` on cleanup. (MBS-9053)
- Remove `#fragment` from Wikimedia Commons URLs.
- Add a test for both.
- Fix a comment. (Wikimedia is the organization that, among other projects like Wiktionary and Wikipedia, runs Wikimedia Commons.)
This builds on pull request #354, which should be merged first.

Wikimedia Commons URL cleanup improvements (includes MBS-9053)

---

lib/MusicBrainz/Server/Controller/Root.pm

By default, when following a link from a web page delivered via HTTP, a browser will send the URL of the linking page (the referrer) to the new server. On the other hand, when coming from an HTTPS page, the referrer is by default only sent if the target page is delivered via HTTPS, too. This behaviour is a relic from a time when HTTPS was only used for, e.g., webmail or banking, and was intended to reduce the risk of session-key URLs leaking via the referrer. It may also be useful in some other cases, for privacy reasons; e.g., for a social media page that is only visible to a specific group of people and contains a link to an external site, it may be unwelcome that the external site could find out who referred to it.
For a site like MusicBrainz, however, that is almost completely(*) …

MBS-8796: Set a referrer policy of “unsafe-url”

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Like most of other databases, Generasia URLs were allowed for all entity types.
This makes use of PR #354 to allow it for Artists, Release Groups, and Works only.
It prevents linking to Generasia from Releases (MBS-8744).

Validate Generasia URLs (solves MBS-8744)

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Fix auto-generated URL validation rules added by commit 8514695c21c1c8acdd0d42ccb5a20ece44b3ae65. The bug was to block URLs for some link types when there is no auto-selected link type for this entity type in the corresponding `CLEANUPS` entry.

Fix auto-generated URL validation rules, part of PR#354

---

root/static/scripts/edit/URLCleanup.js

The media viewer on Wikimedia Commons now uses for its URL fragments the format `#/media/Foo` instead of earlier `#mediaviewer/Foo`.

MBS-9078: Take new Commons media viewer URL into account

---

lib/MusicBrainz/Server/Entity/URL/iTunes.pm
root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

For iTunes *purchase for download* URL relationship
* `geo.itunes.apple.com` URLs (that already matched) are now cleaned up (like other matched URLs). **Standardisation is forced to remove the `geo` prefix from iTunes URLs.** ([MBS-9044](http://tickets.musicbrainz.org/browse/MBS-9044))
* `/audiobook/` and `/podcast/` URLs (that already matched) are now cleaned up (like other matched URLs) ([MBS-8802](http://tickets.musicbrainz.org/browse/MBS-8802)).
* Validation rules are now added so that:
* iTunes URLs are allowed for the correct entities only ([MBS-7164](http://tickets.musicbrainz.org/browse/MBS-7164)),
* `linkmaker.itunes.apple.com` URLs are no more accepted ([MBS-9044](http://tickets.musicbrainz.org/browse/MBS-9044)).
* iTunes sidebar links’ titles now feature country code …

MBS-6314, MBS-7164, MBS-8802 & MBS-9044: Update iTunes URLs’ display, clean-up and validation

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

See the individual commits. The tests are taken from original URLs found in the database (except for the artificial “special characters” test, for which I copied the corresponding Wikipedia test).

MBS-9078: Cleanup and validation improvements for Wikimedia Commons URLs

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

For Wikidata URLs, clean up those that have `/entity` instead of `/wiki`, and use stricter validation.

MBS-9079: Wikidata URL cleanup improvements

---

root/static/scripts/edit/URLCleanup.js

This follows PR #354 on deprecation and conversion of URL validation rules
- Comment on legacy definitions of URL validation rules
- Drop legacy definitions based on `CLEANUPS.*.match`
- Drop legacy definitions that do no better than `CLEANUPS.*.match`
These validation rules are now auto-generated without weakening them.
The rest of legacy definitions require additional `CLEANUPS.*.validate` functions to replace them.

Comment and drop some legacy definitions of URL validation rules in URLCleanup

---

INSTALL.md

`INSTALL.md` currently says to "grab whichever dumps suit your needs", but doesn't at all explain what the various dumps do, making that statement lead to confusion rather than clarification. It might also be good stating whether more dumps can be imported in later or if whomever is setting is up need to decide what they will need right then and there… but that's for another commit/PR.
See https://chatlogs.metabrainz.org/brainzbot/metabrainz/msg/3703747/ for my motivation for doing the PR.

Add link to explanation of the various db dump files.

---

lib/MusicBrainz/Server/Data/WikipediaExtract.pm

The `get_available_languages` method in `MB::S::Data::WikipediaExtract` loops over a list of (Wikipedia and/or Wikidata) URLs. On each iteration, `$key` is set to the page name (e.g. `"Queen (band)"` or `"Q15862"`); only for Wikipedia URLs, `$language` is set to the language code for the Wikipedia edition (e.g. `"en"`). If a Wikidata URLs follows after a Wikipedia one, the value of `$language` was not reset, leading to the construction of a broken API URL.
Move the variable declarations into the loop so that `$language` goes out of scope after each iteration and is recreated with an undefined value.
(It doesn’t appear as if that bug could currently actually be triggered in the current server, though, because the URLs are sorted in a particular order before being passed in. Still, it is …

Fix a latent bug in MB::S::Data::WikipediaExtract

---

lib/MusicBrainz/Server/Entity/URL/VIAF.pm

For linking to VIAF URLs, convert the permalinks stored in the database (e.g. `http://viaf.org/viaf/27092134`) to the form currently used by VIAF (e.g. `https://viaf.org/viaf/27092134/`, HTTPS with trailing slash).

MBS-9087: Convert VIAF URLs for linking

---

lib/MusicBrainz/Server/CoverArt/Provider/WebService/Amazon.pm
lib/MusicBrainz/Server/Report/DiscogsLinksWithMultipleArtists.pm
lib/MusicBrainz/Server/Report/DiscogsLinksWithMultipleLabels.pm
lib/MusicBrainz/Server/Report/DiscogsLinksWithMultipleReleaseGroups.pm
lib/MusicBrainz/Server/Report/DiscogsLinksWithMultipleReleases.pm
lib/MusicBrainz/Server/WebService/Serializer/XML/1/Release.pm
root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

- Fix some regexes parsing Amazon URLs to also understand HTTPS.
- Fix some Discogs reports to also consider HTTPS URLs.
- Clean up Wikisource URLs to HTTPS, and make some general improvements to cleanup (reencode the local part, using the function that does that for Wikipedia and Wikimedia Commons already) and validation.

More HTTPS fixes

---

Makefile.PL
lib/DBDefs.pm.sample
lib/DBDefs/Default.pm
t/lib/t/Context.pm
t/lib/t/MusicBrainz/Server/Data/Artist.pm
t/lib/t/MusicBrainz/Server/Data/ArtistCredit.pm

This probably isn't critical for performance, and it only causes an issue for us: the cache is per-server (not shared), so we must wait for every cache to expire (within 1 hour) after new entities are added.

Remove the in-memory cache

---

INSTALL.md
admin/InitDb.pl

It's already installed by default in PostgreSQL 9.0 and later.

No need to create PL/pgSQL

---

Makefile.PL
lib/DBDefs.pm.sample
lib/DBDefs/Default.pm
lib/MusicBrainz/Server.pm

Remove this module for a few reasons:
1. Starlet already kills workers for us between a configured min and max number of requests.
2. Proc::ProcessTable can't compile against musl libc, which is used in Alpine Linux (though this isn't really an issue anymore, because we switched our docker images to use phusion/baseimage).
3. We can finally close MBS-4071 (Proc::ProcessTable does not scale).
With the settings currently used in production, our logs confirm that workers always get killed after 60 requests (the minimum they're required to handle), because they always exceed a memory size of 350000000 at that point. We can change the Starlet settings min- and max-reqs-per-child to approximate that behavior.

Remove Catalyst::Plugin::AutoRestart

---

.gitignore
npm-shrinkwrap.json
package.json
root/server.js
root/static/gulpfile.js
script/compile_resources.sh
script/dbdefs_to_js.pl
script/start_renderer.pl

The gist is that we're now relying on a DBDefs.js file for our JavaScript instead of environment variables. This can be generated by ./script/dbdefs_to_js.pl in the case of client or server-side JS, or it can be generated by consul-template in the case of server-side JS, and reloaded by root/server.js on HUP.

Improve root/server.js for running inside docker

---

lib/DBDefs/Default.pm
lib/MusicBrainz/Server/Data/FileCache.pm
root/account/edit.tt
root/artist/edit_form.tt
root/components/common-macros.tt
root/components/forms.tt
root/components/relationship-editor.tt
root/edit/details/edit_medium.tt
root/edit/search_macros.tt
root/label/edit_form.tt
root/layout.tt
root/layout/components/Header.js
root/layout/components/Search.js
root/layout/header/top.tt
root/layout/sidebar/sidebar-licenses.tt
root/place/edit_form.tt
root/relationship/linktype/form.tt
root/release/edit/information.tt
root/release/edit/recordings.tt
root/release/edit_relationships.tt
root/static/gulpfile.js
root/static/manifest.js
root/static/scripts/common.js
root/static/scripts/common/components/Autocomplete.js
root/static/scripts/common/errors.js
root/static/styles/extra/homepage.less
script/dbdefs_to_js.pl

The majority of the changes are to do with images. Images are now copied to root/static/build along with JS and CSS, their filenames appended with a hash, and all references to them looked up in rev-manifest.json.
This makes it trivial to copy all assets to another server and run zopfli on them, for example.

Support static resource domains (staticbrainz)

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Newly generated validation rules failed to validate IMSLP artist pages using `CLEANUPS.score` which preceded `CLEANUPS.imslp`. This gets fixed by matching both relationships into `CLEANUPS.imslp`.

Restore IMSLP URLs validation for Artist entities

---

root/static/styles/extra/banner.less

Server banners overlap and hide the top menu’s second row.
Especially when the window is narrow enough to reproduce this.
Confirmed in old browsers: **Internet Explorer 8** and **Opera 12.18**.
“Unwelcome” with un‐dismiss‐able banners.
Top (horizontal) menu is `float: right;` so I have added `clear: both;` to the banner so it goes below the horizontal menu bar.
`clear: right;` would have been enough, but…

Fix banner overlap with right floating top menu.

---

lib/MusicBrainz/Server/Edit.pm
root/components/relationship-editor.tt
root/components/relationships.tt
root/edit/data.tt
root/edit/details/add_relationship_type.tt
root/edit/details/diff_table.tt
root/edit/details/edit_relationship_type.tt
root/edit/info.tt
root/medium/tracklist.tt

Fix localization by adding some missing calls to:
- `add_colon` wrapper, in relationship lists for instance
- (new) `l_status_name` wrapper, in summary of failed, rejected, or cancelled edits, and in raw edit data page of all edits.

Add some missing calls to localization wrappers

---

cpanfile
lib/MusicBrainz/Server/Controller/Account.pm
root/static/styles/widgets.less

The first version of ReCAPTCHA, as used to protect account creation, is no longer considered sufficient to protect from modern spam bots. Hence, use version 2 (“NoCAPTCHA”, because in many cases users aren’t shown a traditional CAPTCHA anymore).

MBS-9130: Update ReCAPTCHA to version 2

---

lib/MusicBrainz/Server/Entity/Role/Age.pm
t/lib/t/MusicBrainz/Server/Entity/Artist.pm

The `Age` role didn’t correctly recognize an ended entity without an end date (just the `ended` flag) nor the case where partial begin and end dates were present, but one of them didn’t include the year. This led to it thinking the entity was still active (age calculation up to the current date) or trying to calculate with `undef` (leading to an ISE, https://beta.musicbrainz.org/artist/5cc78d71-a007-4f2d-a703-cd479fad89ac vs. http://mb.chirlu.de/artist/5cc78d71-a007-4f2d-a703-cd479fad89ac).

MBS-9102: Don’t try to calculate an age when there is not enough data

---

lib/MusicBrainz/Server/Controller/Role/CommonsImage.pm

For entities supporting images, when there is no image to display (based on any Wikimedia Commons or Wikidata URLs), JavaScript code was still generated for the client to retrieve an image from the `.../commons-image` endpoint. That endpoint then had to load and check the same URLs, only to find again that no image exists; it even did an unnecessary call to the Wikimedia API for an image with an empty title. This may have caused considerable additional and useless load.
When no image is to be found, return early without querying Wikimedia and without prompting the client to access the `commons-image` endpoint.

MBS-9138: Avoid redundant requests for image-less entities

---

cpanfile
cpanfile.snapshot
lib/MusicBrainz/Server/Translation.pm

Version 1.00 of DateTime::Locale had some breaking changes. One of them was that "The canonical form of the locale codes now uses dashes (-) instead of underscores (_)." See: http://cpansearch.perl.org/src/DROLSKY/DateTime-Locale-1.11/Changes
Version 1.10 is already in the cpanfile.snapshot, but I ran ./docker/generate_cpanfile_snapshot.sh again anyway.

MBS-9140: Language menu has ids instead of names

---

root/release/edit/recordings.tt
root/static/scripts/release-editor/actions.js
root/static/scripts/release-editor/edits.js

The release editor used to have an option to infer missing track lengths from the length of the associated recording. Now, however, this means a circular reasoning because recording lengths are in turn computed from the lengths of the tracks they appear on. This option is therefore removed.

MBS-7654: Remove “Infer track length from recording” option

---

root/static/scripts/edit/utility/linkPhrase.js

Previously, translated (or not) link phrase that contains a variable
which is not an attribute of its relationship/link type would break
the relationship editing dialog in entity editor.
This patch returns the link phrase with the variable name untouched,
rather than crashing the JavaScript interpreter on the next condition.

MBS-9142: Return unmatched variable in link phrase

---

admin/InitDb.pl

The `NOCREATEUSER` option to the `CREATE USER` command was renamed to `NOSUPERUSER` in Postgres 8.1, and support for the old keyword has been removed in 9.6. It therefore needs to be replaced in `InitDb.pl`.

Replace deprecated Postgres keyword

---

lib/MusicBrainz/Server/Controller/Root.pm

When a server is of type `RT_SLAVE`, but there is no information in the `replication_control` table, it used to crash deep inside Catalyst with a difficult-to-understand error message (because `$c->stash` was called with only one parameter). Catch this situation and die explicitly with a clearer explanation.

MBS-7009: Improve error message for missing replication info

---

root/artist/header.tt
root/static/styles/entity-icons.less

Display different icons for different artist types on the top of the artist page. Earlier on all artist pages only artist icon was displayed.
Issue Link : https://tickets.metabrainz.org/browse/MBS-1352

MBS-1352: Different icon for different artist types on Artist pages

---

lib/MusicBrainz/Server/Controller/WS/2/Release.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/SubmitRelease.pm

Barcode submissions from Jaikoz users are notoriously bad, probably due to interface issues in the client. Block submissions from it, at least until these issues are fixed.

MBS-8542: Block Jaikoz from submitting barcodes

---

root/event/edit_form.tt
root/static/scripts/guess-case/MB/GuessCase/Main.js

Adding the "Guess case" feature to event names while editing .
Issue Link : https://tickets.metabrainz.org/browse/MBS-8359

MBS-8359: Add 'Guess Case' function for Event names

---

lib/MusicBrainz/Server/Controller/Role/CommonsImage.pm

Up to now, only label logos available via Wikidata were shown in the sidebar, but not any that are possibly directly linked on Wikimedia Commons. Make it as it is for artist images and fall back to Commons directly if there wouldn’t otherwise be an image to display.

MBS-8868: Show label logo from Commons in the sidebar

---

lib/MusicBrainz/Server.pm
lib/MusicBrainz/Server/Controller/Admin/WikiDoc.pm
lib/MusicBrainz/Server/Controller/Doc.pm
lib/MusicBrainz/Server/Controller/Edit.pm
lib/MusicBrainz/Server/Controller/ReleaseEditor.pm
lib/MusicBrainz/Server/Controller/Statistics.pm
lib/MusicBrainz/Server/Controller/WS/2/Collection.pm
lib/MusicBrainz/Server/ControllerUtils/CDTOC.pm
lib/MusicBrainz/Server/Data/CommonsImage.pm
lib/MusicBrainz/Server/Data/DurationLookup.pm
lib/MusicBrainz/Server/Data/Search.pm
lib/MusicBrainz/Server/Data/Utils.pm
lib/MusicBrainz/Server/Data/WebService.pm
lib/MusicBrainz/Server/Data/WikiDoc.pm
lib/MusicBrainz/Server/Data/WikipediaExtract.pm
lib/MusicBrainz/Server/Edit.pm
lib/MusicBrainz/Server/Entity/URL/LastFM.pm
lib/MusicBrainz/Server/Filters.pm
lib/MusicBrainz/Server/Form.pm
lib/MusicBrainz/Server/Sitemap/Builder.pm
lib/MusicBrainz/Server/Sitemap/Incremental.pm
lib/MusicBrainz/Server/Translation.pm
lib/MusicBrainz/Server/Validation.pm
lib/MusicBrainz/Server/WebService/JSONSerializer.pm
lib/MusicBrainz/Server/WebService/WebServiceInc.pm
lib/MusicBrainz/Server/WebService/XMLSerializer.pm
lib/MusicBrainz/XML.pm
lib/Sql.pm

Simplify some parts by using the `/r` non-destructive flag to the substitution operator (new since Perl 5.14): `$foo =~ s/bar/baz/r` doesn’t modify `$foo` as it would do without the `/r`, but simply returns a value with the substitution applied. Furthermore, replace simple character substitutions with transliterations (`tr///`).

Make use of non-destructive substitution and transliteration

---

lib/MusicBrainz/Server/Data/Release.pm
root/cdtoc/attach_filter_release.tt

When searching for a medium to attach a TOC to, only mediums of a type that supports TOCs (such as CD) are candidates. However, it is desirable to show even other mediums with the right number of tracks: Not doing so confuses users (“I’m dead sure this artist has a release with 5 tracks!”), and mediums of the wrong type may serve as model for a release duplicate in the right type. For these reasons, a search by release title has always returned all mediums with matching track count (selecting one of a non-TOC type was disabled in the UI); a search by artist, however, did not include mediums of types that don’t support TOCs.
Make this consistent by returning non-TOC mediums when searching by artist, too. They will be disabled UI-wise in the same way as they already were for a search by …

MBS-9175: Include non-TOC mediums in “Attach TOC” search

---

t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm

Test fix, forgotten in commit ef1ea4a18901d69c2d47f040ee2d836982343cb0.

Remove removed endpoint from UnconfirmedEmailAddresses test

---

script/compile_resources.sh
script/dbdefs_to_js.pl

Two changes here. The first is to add `->canonical` to the JSON object, so that the keys aren't outputted in random order. The second is to remove unused settings from the client JS altogether. I think the first fix is still good to have independent of the second fix, because we may have object-like DBDefs settings in the client JS in the future.

MBS-9180: Near-identical duplicates of common-xxx.js

---

root/static/gulpfile.js
root/static/manifest.js
root/static/scripts/rev-manifest.js

The Vinyl object mentioned in the comment in the gulpfile wasn't actually being used anywhere. So now it is. And instead of having it being required based on the build path (which can be variable), it now uses an ID, "rev-manifest.json". (Note, if a string passed to `require` doesn't look like a path, yarb will treat it as a module name relative to node_modules/, or as a global ID assigned via a call to `expose`.)

MBS-9186: Gulpfile fails to build scripts in website containers

---

docker/templates/Dockerfile.test-database.m4

Specifically bumps the unaccent extension to fix C locale issues.

Use the latest extensions in the test database

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Previously, old-fashion hand-coded `validationRules` coexisted with generated ones.
This pull request replaces all hand-coded `validationRules` by `CLEANUPS.*.validate` functions which are used to generate new `validationRules` instead.
Incidentally, validation rules have been tightened for Bandcamp, IMDb, Amazon, YouTube, VGMdb, AllMusic, Discogs, SoundCloud, VIAF, Myspace, Wikipedia, and BBC Music URLs.
Additionally, clean-up has been added for BBC Music URLs and VGMdb event URLs.
It is a revision of PR #366 by @uklauer, see [changes made](https://github.com/y-van-z/musicbrainz-server/commits/validation_rules_wiping) since then.

Generate all URL validation rules

---

root/static/images/icons/dropdown-arrow.svg
root/static/styles/layout.less

The entity type dropdown in the search form in the page header is supposed to show a down arrow. This worked in Chromium, but not in Firefox.
There were three separate issues:
- Firefox doesn’t support the individual CSS properties `background-position-{x,y}` before version 49. Use the combined `background-position` instead.
- When embedding an image as a data URI, it needs to be properly percent-encoded. Move the image to a separate file and let `data-uri()` handle the encoding. (Chromium seems to be less strict here.)
- The SVG file used an invalid SVG version. Set it to version 1.1.

MBS-9198: Show down arrow in a dropdown even in Firefox

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Previous refactoring of Facebook URLs validation was bogus, refusing any URL i but clean `/pages/` ones for Artists and Labels.
This gets fixed that by checking only `/pages/` URLs for cleanness, while accepting all non-`/pages/` URLs, just as before ddb1eba21e31d41828d7fa9551a4db12ad0437eb.
Additionally, it extends this check to all other entity types, that is, Events, Places, and Series.
Tests are added for Facebook URLs validation.

MBS-9205: Fix validation of Facebook URLs on beta

---

lib/MusicBrainz/Server/Data/Role/Collection.pm
lib/MusicBrainz/Server/WebService/JSONSerializer.pm

The JSON serializer does not currently support serializing lists of series or instruments, breaking browse requests for those entities.
This small patch resolves that, and also fixes a perl warning seen for browse requests (both XML and JSON).

MBS-9173: Support serializing of instrument and series lists.

---

root/area/edit_form.tt
root/components/forms.tt
root/components/relationship-editor.tt
root/entity/alias/edit_form.tt
root/label/edit_form.tt
root/place/edit_form.tt
root/static/scripts/edit.js
root/static/scripts/edit/utility/toggleEnded.js
root/static/scripts/relationship-editor/common/fields.js

Automatically tick and disable the “ended” date checkbox when the `end_date.year` field is filled in alias, (Area, Artist, Label, and Place) entity and relationship editors.
When the `end_date.year` field is emptied, it restores the state of the “ended” date checkbox.
Additionally factorize date range field set templates, and align the “ended” checkbox with the “end date” text input in the relationship editor, that is, in the same way as in the other editors.

MBS-9002: Automatically disable and tick ended date checkbox in editors

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Fix `otherdatabases` entry for Classical Archives URLs with both `/artist/` and `/ensemble/` paths.

MBS-8236: Recognise artist and ensemble for Classical Archives URLs

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

- Match Spotify `user` account URLs with _social network_ relationship
- (Keep matching Spotify `album`, `artist`, and `track` URLs with _streaming music_ relationship)
- Standardise to `https` scheme and `open.spotify.com` host ([MBS-9062](https://tickets.metabrainz.org/browse/MBS-9062))
- (Keep converting `embed.spotify.com` URLs)
- Remove trailing subpaths (but for `user`), slash, query (`?…`) and fragment (`#…`)
- Do not convert playlist URLs into user account URLs
- Validate clean user account URLs with any _social network_ relationship
- Specifically reject playlist URLs
- Validate clean URLs with _streaming music_ relationships with:
- `album` path only for Release-URL
- `artist` path only for Artist-URL
- `track` path only for Recording-URL
Update tests accordingly

MBS-8249: Standardise and validate Spotify URLs

---

lib/MusicBrainz/Server/Report/InstrumentReport.pm
lib/MusicBrainz/Server/Report/InstrumentsWithoutAnImage.pm
lib/MusicBrainz/Server/ReportFactory.pm
root/report/index.tt
root/report/instruments_without_an_image.tt

- Actually report instruments with neither `image` URL relationship nor `wikidata` URL relationship.
- Columns are (linked) instrument name, type, and last updated.
- Rows are sorted by type id, then by instrument name, that is, in the same way as `/instruments` list.

MBS-9193: Report instruments without image

---

docker/templates/DBDefs.pm.ctmpl

In production, a new relay service "musicbrainz-org.exim-relay" has been set up to fix mail issues.

Use new exim-relay service

---

lib/MusicBrainz/Server/Edit/Utils.pm

Due to a bug (see MBS-8750), there are edits trying to set an empty artist credit name (Artist Foo as `""`). Those edits would never close.
Test for this case when applying an edit and explicitly fail if necessary.

Fail edits trying to set empty credited-as AC names

---

lib/MusicBrainz/Server/Form/Alias.pm

Since the update to DateTime::Locale 1.10, parts in locale strings are delimited by hyphens instead of underscores. Change the code that detects sub-locales accordingly, so that they can be indented again
for visual grouping.
See #416, too.

MBS-9168: Re-enable indentation of certain locales

---

docker/musicbrainz-tests/run_tests.sh
npm-shrinkwrap.json
package.json
root/edit/notes-received.tt
root/static/gulpfile.js
root/static/scripts/tests/all.html
script/compile_resources.sh

This was almost certainly due to concurrent asynchronous writes to rev-manifest.json, through `writeResource`. The code has been modified to only write rev-manifest.json once at the end of the build, rather than for each bundle, so that there are no longer any concurrent writes. After these changes, I can no longer reproduce the issue after many attempts.
I tested that the new bundles didn't throw any errors on several edit pages, including under different languages. I also checked that the file hashes didn't change between builds.
I adapted the "watch" mode for these changes too, but it seems to have already been broken before this patch (and I didn't fix it).

MBS-9224: The gulpfile sometimes produces a corrupt rev-manifest bundle

---

root/static/scripts/area/places-map.js

'… and {place_count} other' should be displayed when markers.length == CLUSTER_POPUP_LIMIT + 1
The bug can be seen e.g. on https://beta.musicbrainz.org/area/74e50e58-5deb-4b99-93a2-decbb365c07f/places when unzooming one step on the map (there's a cluster with 11 entities)

Fix i18n text selection (related to MBS-7795)

---

cpanfile

Replicating MBS using `INSTALL.md` fails as `cpanfile` misses dependency entry `Plack::Middleware::Debug`.

MBS-9252: cpanfile missing entry Plack::Middleware::Debug

---

root/release_group/create.tt

As I mentioned on [MBS-9176](https://tickets.metabrainz.org/browse/MBS-9176), this gets rid of the artist info on top of the create RG form, which isn't there when you click Add recording, Add work, nor Add release (and looks very out of place, too).
Wrapping it into a content div like the other forms for consistency too.

MBS-9176: make Create RG form consistent with others (and less ugly)

---

root/static/styles/layout.less

The menu z-index must be above the one of leaflet map (z-index 400)

MBS-9250: Places map displays over header menus

---

lib/MusicBrainz/Server/Form/Field/ArtistCredit.pm

Fix [MBS-9246 Tool-tips displaying "undefined" text](https://tickets.metabrainz.org/browse/MBS-9246).
Previously, only artist name, id, gid, and type were loaded for preview in the Artist Credit editor.  Consequently, tool-tips did not contain sort name or disambiguation comment (but _undefined_ instead), and artists with pending edits were not highlighted. It affects Artist Credit field editor of editing forms for recording, release-group, artist credit, and artist split. Only Artist Credit field of release editor is unaffected, because it is initialized in a different way using React.
This patch loads all JSON-serialized artist fields including sort name, disambiguation comment, and status regarding pending edits to the Artist Credit form field. All of the above mentioned bugs are …

MBS-9246: Load extra data for Artist Credit field

---

root/static/scripts/common/immutable-entities.js
root/static/scripts/tests/common/immutable-entities.js

Fix [MBS-9237: Don't immediately fill back the default AC while editor is typing](https://tickets.metabrainz.org/browse/MBS-9237).
Previously, empty Artist Credits were mistakenly considered as simple, so triggering the Artist field Autocomplete to fill back user emptied Artist Credit in the Artist Credit editor bubble. This is because empty artist credit is reduced to artist name.
This patch fixes the `isComplexArtistCredit` to consider empty Artist Credit as complex.  This prevents the automatic fill-back of Artist Credit field in the Artist Credit editor to mistakenly happen before the field looses focus. See `onNameBlur` for proper fill-back.

MBS-9237: Fix complex artist credit detection

---

lib/MusicBrainz/Server/Form.pm

The `TO_JSON` method on `Server::Form` is used to encode values and errors from FormHandler for display by the JavaScript. Specifically, just the artist credit editor right now. Unfortunately, the `error_fields` property would sometimes contain blessed objects, as was the case with ISRCs. To fix this, only output the parts of `error_fields` which we actually need, and know not to include any blessed objects.
This wasn't a problem for ISWCs because we don't use `to_encoded_json` on the work edit page (as stated, it's only needed for artist credits right now).

MBS-8931: Invalid ISRC causes an ISE

---

root/release/add_cover_art.tt

Tiny bug fix for [MBS-9214: Cover art types tick boxes are listed with scrollbars in Opera 42 Stable](https://tickets.metabrainz.org/browse/MBS-9214).
Insert a `<span>` element to work around still modern Opera’s lack of support for `white-space` CSS property on `<li>` and `<label>` elements.
This affects tick boxes and their labels for cover art type field in release cover art adding form.

MBS-9214: Fix cover art tick boxes for Opera

---

root/account/edit.tt

Fix bug [MBS-9219:[Multiple languages] (Basic) is automatically added when editing/saving an editor profile](https://tickets.metabrainz.org/browse/MBS-9219) and clean template code up a bit.

MBS-9219: Fix editing known languages field in user profile form

---

lib/MusicBrainz/Server/Data/WikiDocIndex.pm

The wiki is now HTTPS-only, so don't use HTTP.

MBS-9263: Use HTTPS for WikiDoc transclusion table

---

lib/MusicBrainz/Server/Form/Admin/Attributes.pm
root/admin/attributes/form.tt

Collection and series types admin editing form missed entity type.
This adds support for entering entity type without specific check.

MBS-9215: Add entity type to attribute editing form

---

lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Release.pm
lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Role/Rating.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm

The first commit is straightforward - a release has no ratings so should not try to serialize them.
The second part aims to replicate the XML serializer's behaviour - a request for ratings on a release is "forwarded" to the release's RG (if it's also requested).
However, the JSON serializer is made up of a bunch of disjoint sources, and the bit that handles ratings has no way of knowing it's handling a release group that is being serialized as part of a release request.
If I change MusicBrainz::Server::WebService::Serializer::JSON::2::Role::Rating to ignore the toplevel flag, all release groups (including those in (requested) relationships) in all requests will serialize their ratings; instead I (ab)use $inc to pass a special flag for it to pick up.
I'm not very happy with that, but the …

MBS-9129: Adjust JSON serialization for RG ratings on release request.

---

root/static/scripts/tests/Control/URLCleanup.js
root/static/scripts/tests/GuessCase.js

Fix two small bugs while running tests in browser, as reported in https://github.com/metabrainz/musicbrainz-server/pull/449#issuecomment-277520087:
1. `too much recursion` error caused by tests nesting, resolved by splitting URL Cleanup test (currently composed of subtests) into a myriad of tests
2. Label guess case test failure using Turkish mode, resolved by initializing user settings as necessary

Fix running tests in browser

---

root/area/header.tt

Fix [MBS-9266](https://tickets.metabrainz.org/browse/MBS-9266):
- Make sub-header more easy to translate as a single string
- Remove incidental comma and properly chomp white-spaces

MBS-9266: Fix subheader of area pages

---

root/components/common-macros.tt
root/static/styles/layout.less

[MBS-8748](https://tickets.metabrainz.org/browse/MBS-8748): Long medium names caused horizontal scrolling on release pages.
This patch wraps medium name and visually split the header line into (borderless) cells so that medium format and medium number are clearly distinguished from wrapped medium name.

MBS-8748: Wrap medium name in release tracklist

---

lib/MusicBrainz/Server/Edit/Event/Edit.pm
lib/MusicBrainz/Server/Edit/Medium/Create.pm
lib/MusicBrainz/Server/Edit/Medium/Edit.pm
lib/MusicBrainz/Server/Edit/Release/ChangeQuality.pm
lib/MusicBrainz/Server/Edit/Release/Edit.pm
lib/MusicBrainz/Server/Edit/Role/AllowAmendingRelease.pm

Allow for auto-edits in the three following cases:
- Editing release in a 1 hour delay, see [MBS-8905](https://tickets.metabrainz.org/browse/MBS-8905)
- Lowering release data quality in a 1 hour delay, see [MBS-8927](https://tickets.metabrainz.org/browse/MBS-8927)
- Adding time and setlist to an event that doesn’t have one, see [MBS-9120](https://tickets.metabrainz.org/browse/MBS-9120)
Although there is no test for amending release for now, this change doesn’t conceal other tests.

MBS-8905, MBS-8927, MBS-9120: Allow for more auto-edits

---

lib/MusicBrainz/Server/Validation.pm
t/lib/t/MusicBrainz/Server/Validation.pm

[MBS-9260](https://tickets.metabrainz.org/browse/MBS-9260): Make changing between version (visually similar to three dots) of an ellipsis an auto-edit.

MBS-9260: Make changing ellipsis version an auto-edit

---

script/compile_resources.sh

The '*.png' glob will fail if compile_resources.sh is run before `npm install`, creating a broken symlink.
Setting failglob was suggested by Mineo.

MBS-9264: Don't leave broken Leaflet symlinks

---

lib/MusicBrainz/Server/Validation.pm
t/lib/t/MusicBrainz/Server/Validation.pm

Fix [MBS-8354](https://tickets.metabrainz.org/browse/MBS-8354).
Add em-dash and horizontal bar to the class of dash characters for auto-edits.

MBS-8354: Make replacing em-dash and horizontal bar auto-edits

---

lib/MusicBrainz/Server/WebService/Format.pm
lib/MusicBrainz/Server/WebService/Validator.pm
t/lib/t/MusicBrainz/Server/WebService/Format.pm

Only question is whether or not it's safe to modify the args entry in the stash, or whether I should make a copy before adding the fmt value.
Alternatively, maybe it's Format.pm that should handle this by guaranteeing that fmt will be set appropriately (it already looks at the Accept header).

MBS-9258: Map "Accept: application/json" to "fmt=json" for search server WS requests.

---

root/components/relationship-editor.tt
root/static/scripts/relationship-editor/common/dialog.js

Previously, relationship editor had an option to change artist credits for all relationships on the page at the same time. 
Improvement [MBS-8465](https://tickets.metabrainz.org/browse/MBS-8465) involves allowing editor to change a subset only of these relationships, filtered either by type or by entity types.
To that end, this patch adds three radio buttons to the current checkbox input which is now labelled “Change other” rather than “Change all”.  Radio buttons are visible if and only if input is checked.  Label lines are wrapped if translation is too long.
Additionally, it fixes bug [MBS-9288](https://tickets.metabrainz.org/browse/MBS-9288) which prevented to change other relationship credits for source Artist from an Artist-Artist relationship.

MBS-8465, MBS-9288: Improve changing other relationship credits

---

lib/MusicBrainz/Server/Controller/WS/js.pm

Stops it from throwing another error while it's trying to return the original error.
https://sentry.metabrainz.org/metabrainz/musicbrainz-server/issues/441/

Stringify blessed /ws/js errors for encode_json

---

lib/MusicBrainz/Server/Constants.pm
lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
root/static/scripts/release-editor/edits.js
t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm

Prior to this patch, if an edit threw a NoChanges exception it'd cause the request to 400, and cause it to stop processing edits (a submission could contain multiple edits). This was a problem, because the release editor batches recording and medium edits together in one request; at the same time, the JavaScript ignored 400 errors caused by NoChanges exceptions (which were indicated by a specific code in the response), and continued submitting other edits. The result was usually a stub release with no mediums.
The fix is simply that NoChanges exceptions will no longer cause a request to /ws/js/edit to fail (though they are still indicated in the response).

MBS-8578: Handle NoChanges edits better in the release editor

---

admin/BuildIncrementalSitemaps.pl
lib/Catalyst/Plugin/Sentry.pm
lib/MusicBrainz/Sentry.pm
lib/MusicBrainz/Server.pm
lib/MusicBrainz/Server/EditQueue.pm
npm-shrinkwrap.json
package.json
root/server.js

Fixes a couple issues I found, and notably, also enables Sentry in our Node.js template renderer, and our sitemaps/ModBot scripts. A general approach for enabling Sentry in every ./admin/ script is pretty difficult, but we can add calls to `capture_exceptions` wherever they're useful, or we can report all cron errors with a bit of engineering too. But those are later issues.

Sentry fixes

---

root/static/scripts/common/utility/getScriptArgs.js

`getScriptArgs` can be executed multiple times from different scripts, but `currentScript` is only calculated once. Calculate it every time `getScriptArgs` is called, because it's obviously dynamic.

MBS-9289: Area places map doesn't display

---

admin/ExportAllTables
admin/sql/CreateFunctions.sql
admin/sql/CreateIndexes.sql
admin/sql/CreateTables.sql
admin/sql/CreateTriggers.sql
admin/sql/DropFunctions.sql
admin/sql/DropIndexes.sql
admin/sql/DropTables.sql
admin/sql/DropTriggers.sql
admin/sql/updates/20170327-mbs-9271-standalone.sql
admin/sql/updates/20170327-mbs-9271.sql
lib/MusicBrainz/Server/Constants.pm
lib/MusicBrainz/Server/Controller/Admin.pm
lib/MusicBrainz/Server/Data/Editor.pm
lib/MusicBrainz/Server/Form/Utils.pm
root/admin/delete_user.tt
t/lib/t/MusicBrainz/Server/Controller/User/Register.pm
t/lib/t/MusicBrainz/Server/Data/Editor.pm
t/sql/editor.sql
upgrade.json

On the account deletion page, admins will have a choice of whether to allow the name to be reused. It's checked by default, since I assume they'll mostly be deleting spam accounts. People deleting their own accounts can't toggle this.
I didn't add a way to allow admins to force-rename a user even if the name was previously used, but I assume it won't happen often and it's easy enough to get someone to delete the entry from the `old_editor_name` table.

MBS-9271: Prevent usernames from being reused

---

lib/MusicBrainz/Server/Edit/Work/Edit.pm
t/lib/t/MusicBrainz/Server/Edit/Work/Edit.pm
t/sql/edit_work_attributes.sql

[MBS-8640](https://tickets.metabrainz.org/browse/MBS-8640): Make adding work attribute auto-edit
Previously, adding work attribute was not an auto-edit, both because of a potential deliberate choice and a bug in implementation (`old` `attributes` array is always defined when adding work attributes).
This patch allows adding work attributes to be an auto-edit, only if there is no existing attribute of the same type for this work.
It doesn't allow modifying/deleting work attributes to be auto-edit.

MBS-8640: Make adding work attribute auto-edit

---

npm-shrinkwrap.json
package.json
root/server.js
root/server/buffer.js
root/server/createServer.js
root/server/response.js
root/static/gulpfile.js

It wasn't much effort to fix, so here it is. Tested with the help of adhawkins.
I updated node-raven to v2 because it was impossible to even see what the errors were without it (v1 hid uncaught exceptions).

Node renderer fixes

---

root/layout/components/Head.js

Fix [MBS-9347](https://tickets.metabrainz.org/browse/MBS-9347): append “- MusicBrainz” to the title of all pages but the homepage.

MBS-9347: Fix regression regarding page titles

---

lib/MusicBrainz/Server/Edit/Work/Edit.pm

Fix [MBS-9362](https://tickets.metabrainz.org/browse/MBS-9362)
Prior to schema change 2017 Q2 update, work lyrics language was represented by a single value in `language_id` field.  It is now represented as a set of values in `languages` array field.
This patch allows to apply work edits made before the schema change.
This pull request is made against `beta` branch in order to hot fix 125 pending edits.
There is no conflict with `master`.

MBS-9362: Restore work language edit data

---

admin/MBImport.pl
admin/replication/ImportReplicationChanges
lib/MusicBrainz/Server/Connector.pm
t/script/ExportAllTables.t

DBD::Pg 3.6.0 fixed their UTF8 flag handling with respect to the pg_(get|put)copydata methods, and the effect is that we now have to decode our strings before passing them into those functions.
This change also works with DBD::Pg 3.5.3. The way they changed the UTF8 handling is a bit hard to follow since it deals with Perl internals, but it must have only worked accidentally before, if the behavior we were relying on wasn't intended.

MBS-9342: Fix imports with DBD::Pg 3.6.0

---

root/static/styles/layout.less

Long URLs do not wrap and cause page distortion e.g. in https://musicbrainz.org/artist/f2b1690b-7b7a-4364-9764-098ecf87f794 a Wikipedia url with a very long #id caused the sidebar to take c. 80% of page width.
This proposed fix is applied to all `<a>` tags on every page. Further selectors can be added to e.g. restrict this to the sidebar if that is prefered. e.g. 
```
&#sidebar {
word-break: break-all;
}
```
Resolves https://tickets.metabrainz.org/browse/MBS-9323

MBS-9323: Fix long URLs distorting page layout.

---

lib/MusicBrainz/Server/Controller/Edit.pm
root/edit/cannot_vote.tt

Fix bug [MBS-9372](https://tickets.metabrainz.org/browse/MBS-9372): Revoking editing/voting editor rights also renders them unable to write edit notes.
Prior to this patch, if admin revoked editing/voting privileges of any editor, this editor would not be able to submit edit notes, since it would be incidentally disallowed at the same time as votes.
This patch refines permissions to submit edit notes and votes so to allow submitting edit notes when editor is editing/voting-disabled and no vote is submitted.  If any vote is submitted at the same time, edit notes are rejected as well and an error page is returned.

MBS-9372: Allow notes from voting-disabled editor

---

admin/sql/updates/20170604-mbs-9365.sql
upgrade.json

It wasn't included in the upgrade script when events were originally added.

MBS-9365: Create event_meta_fk_id for old standalone DBs

---

docker/scripts/import_db.sh

Added option `--retry 15` in the `curl` command for making it retry downloading the dumps. Now, the import fails if the downloading fails (without retrying).

MBS-9391: Update import_db.sh to retry downloading dumps.

---

script/dump-entities-sql.pl

The sql generation fails presently for release group (in function `dump_release_groups`) with this [error]( https://gist.github.com/ferbncode/0f289e7368d58f3b4eae522d965d844f#file-error-L147-L150). Updated the query according to the present schema.

MBS-9401: Fix sql query to fetch releases in dump-entities-sql.pl

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Clean the new format of Wikidata URLs found in Wikipedia pages, for example,
from https://www.wikidata.org/wiki/Special:EntityPage/Q339359
to https://www.wikidata.org/wiki/Q339359

MBS-9416: Handle new Wikidata URL format redirect

---

lib/MusicBrainz/Server/Controller/Collection.pm
lib/MusicBrainz/Server/Controller/User.pm
t/lib/t/MusicBrainz/Server/Controller/User/Login.pm
t/lib/t/MusicBrainz/Server/Controller/User/Ratings.pm
t/lib/t/MusicBrainz/Server/Controller/User/Show.pm
t/lib/t/MusicBrainz/Server/Controller/User/Tags.pm

[MBS-9353](https://tickets.metabrainz.org/browse/MBS-9353): Do not show collections or user profiles to people not logged in
Set `RequireAuth` attribute to every subroutine of Collection & User rather than `base` subroutine.

MBS-9353: Fix RequireAuth attributes for user profile and collection

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Rock.com.ar’s URL format has been revamped for its relaunch in 2017.
- Domain name now defaults to `rock.com.ar` (`www` subdomain is a redirect).
- Validate paths starting with `/artistas/<ID>` as well as sub-paths `/discos/<ID>` and `/letras/<ID>`
- Worthless sub-paths `/`, `/biografia`, `/discos`, `/fotos`, `/fotos/*`, `/letras are removed
Old format URLs, properly redirected, are still recognized, cleaned and validated.

MBS-9435: Update URL Cleanup for Rock.com.ar 2017 Relaunch

---

lib/MusicBrainz/Server/Entity/PartialDate.pm

Fix commit 23e11bdd65d9d5c92328af47496bb256daaa8255 and bug reported as [MBS-9446](https://tickets.metabrainz.org/browse/MBS-9446).
Thanks to @mkubenka for having reported it and proposed a patch in PR #532.

Add a custom TO_JSON method for PartialDate

---

admin/RemoveSpamAccounts.pl

First part of [MBS-9357](https://tickets.metabrainz.org/browse/MBS-9357):
- Allow filtering on **email**, **website**, and **bio** (additionally to name)
- Support POSIX regular expression (in place of prefix)
- Use case-sensitive operator by default (instead of insensitive)
- Preserve accounts with edits/votes/OAuth tokens by default
- Add options for operator case-sensitivity and verbosity level
- Show help message (documentation) in case of incorrect usage

Update RemoveSpamAccount admin script for MBS-9357 (part 1)

---

package-lock.json
package.json
root/static/scripts/edit/components/Tooltip.js
root/static/styles/common.less
root/static/styles/tooltip.less

RCSS is deprecated and isn't a very good idea for us, since for server rendering it'd mean sending CSS twice (in the JavaScript, and in the compiled CSS it injects).
This changes the style of the tooltip very slightly to use existing colors defined in colors.less.

Remove RCSS

---

admin/sql/updates/20170909-mbs-9462-missing-event-triggers.sql
upgrade.json

...for standalone databases created before schema 21.
Ran manually on the prod DB already.

MBS-9462: Create missing l_event_url triggers

---

lib/MusicBrainz/Server/Entity/Relationship.pm
lib/MusicBrainz/Server/Entity/Role/Linkable.pm
root/components/common-macros.tt
root/components/medium.tt
root/components/relationship-editor.tt
root/components/relationships.tt
root/forms/relationship-editor.tt
root/release/edit_relationships.tt
root/static/scripts/edit/utility/linkPhrase.js
root/static/scripts/relationship-editor/common/entity.js
root/static/scripts/relationship-editor/common/fields.js

For orderable link types, we "cleaned" non-required attributes from the link phrases in `interpolate` so that they are grouped together in the relationships display and editor UIs. However, the release relationship editor as well as recording-work relationships on the release page don't require any grouping, so this had the effect of hiding those attributes there. This patch makes that behavior optional, so that the cleaned phrases are only used where grouping is intended.

MBS-9455: Show orderable relationship attributes absent grouping

---

lib/MusicBrainz/Server/Form/Utils.pm
root/static/scripts/relationship-editor/common/viewModel.js

It appears that `build_attr_info` is only used to pass data to `exportTypeInfo` in the JS.
It also appears that in `exportTypeInfo`, we completely disregard the key. This patch just makes sure the keys are unique, so that one attribute type doesn't clobber another with the same name.

MBS-9471: Relationship editor breaks if two link attribute types have the same name

---

.babelrc
INSTALL.md
package-lock.json
package.json
root/components/Frag.js
root/layout/components/ExternalLinks.js
root/layout/components/Footer.js
root/static/scripts/area/places-map.js
root/static/scripts/common/components/ArtistCreditLink.js
root/static/scripts/common/components/Autocomplete.js
root/static/scripts/common/components/DescriptiveLink.js
root/static/scripts/common/components/EntityLink.js
root/static/scripts/common/components/TagEditor.js
root/static/scripts/common/entity.js
root/static/scripts/common/i18n.js
root/static/scripts/common/i18n/commaList.js
root/static/scripts/common/i18n/commaOnlyList.js
root/static/scripts/edit/components/ArtistCreditEditor.js
root/static/scripts/edit/components/HelpIcon.js
root/static/scripts/release-editor/bindingHandlers.js
root/static/scripts/release-editor/fields.js
root/static/scripts/tests/external-links-editor/utils.js
root/static/scripts/tests/release-editor/edits.js

Note: This is based on https://github.com/metabrainz/musicbrainz-server/pull/550 to avoid conflicts with the PropType removals. Just see the last commit here.
We haven't been able to update to any of the intermediate v15 releases, because we're relying on my fork which adds a `<frag>` builtin. Subsequent v15 releases made it very difficult for me to rebase that work.
React v16 supports fragments (returning an array of elements from `render()`) natively, so we no longer need to rely on my fork. We'll keep the `<Frag>` idea by defining a wrapper component, because returning an array is awkward in some instances (unnecessary key props, literals requiring commas).
The `transform-react-inline-elements` babel plugin has been removed because it causes spurious unique key prop warnings. This …

Upgrade React to v16

---

admin/GenerateSQLScripts.pl

Allow the regex to parse the schema when specified.
See https://github.com/metabrainz/sir/blob/master/sir/trigger_generation/sql_generator.py#L47
Fixes https://tickets.metabrainz.org/browse/SOLR-47

SOLR-47 Fix DropTriggers creation function

---

lib/MusicBrainz/Server/Edit/Release/Edit.pm
lib/MusicBrainz/Server/Edit/Role/AllowAmending.pm
t/lib/t/MusicBrainz/Server/Edit/Role/AllowAmending.pm

- Fix bug [MBS-9313](https://tickets.metabrainz.org/browse/MBS-9313): Adding first release event should be an auto-edit.
- Implement [MBS-9505](https://tickets.metabrainz.org/browse/MBS-9505): Extend amending delay from one hour to one day.

MBS-9313, MBS-9505: Auto-editing release event, amending within one day

---

root/static/scripts/common.js
t/selenium.js
t/selenium/Artist_Credit_Editor.html
t/selenium/MBS-7456.html

The `confirm()` dialog in the release editor that tells you you're going to lose all your changes is now breaking the tests, because it prevents subsequent commands from running.
It's unclear why it worked previously, but an update to chrome broke it.
Also included are two unrelated improvements to selenium.js: checking if errors occurred on the page after every command, and logging every command (so when it fails we can see where it was at).

 Handle now-unexpected alerts in selenium tests

---

lib/MusicBrainz/Server/Controller/Collection.pm
lib/MusicBrainz/Server/Controller/User.pm
lib/MusicBrainz/Server/Form/User/EditProfile.pm
root/account/edit.tt
root/collection/index.tt
root/user/profile.tt
t/lib/t/MusicBrainz/Server/Controller/Collection/Show.pm
t/lib/t/MusicBrainz/Server/Controller/User/Edit.pm
t/lib/t/MusicBrainz/Server/Controller/User/Login.pm
t/lib/t/MusicBrainz/Server/Controller/User/Ratings.pm
t/lib/t/MusicBrainz/Server/Controller/User/Show.pm
t/lib/t/MusicBrainz/Server/Controller/User/Tags.pm

This supersedes [MBS-9353](https://tickets.metabrainz.org/browse/MBS-9353) (completly hide user profiles and collection pages) and [MBS-9355](https://tickets.metabrainz.org/browse/MBS-9355) (disable editing biography and homepage/website for limited users).

MBS-9519: Hide biography, website/homepage, and collections description of limiter users from not-logged-in users

---

admin/functions.sh
bin/rsync-fullexport-files

This has failed twice recently: https://community.metabrainz.org/t/mbdump-tar-bz2-missing-from-latest-full-export/333175/5
This just retries it forever, sleeping for 30 seconds between each attempt.

MBS-9525: retry fullexport rsync if it fails

---

lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Release.pm
lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Utils.pm

This is used in picard to get track ratings.

MBS-9540: Add ratings for non top level entities

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Update iTunes URL cleanup to add `id` characters which are now missing from new default iTunes link format. Validation is unchanged.

MBS-9542: Update iTunes URL cleanup

---

lib/MusicBrainz/Server/Email.pm

Encode email header fields `From` and `Subject` in quoted-printable if a non-ASCII character is detected.

MBS-9570: Fix encoding of email header fields

---

root/user/profile/layout.tt

Subscriptions, tags, and ratings are tabs in editor profile. Accessing their content may be forbidden by privacy preferences.
This patch hides private tabs from editor profile, rather than linking to a page that returns a 403 Forbidden Request error.

MBS-9578: Hide private tabs from editor profile

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

For [Anison Generation](http://anison.info/):
1. Allow to enter as `otherdatabases` relationship (with auto-selection, cleaning-up, and validation)
Link to issue: [MBS-9561](https://tickets.metabrainz.org/browse/MBS-9561)

MBS-9561: Add Anison.info to otherdbs whitelist

---

lib/MusicBrainz/Server/Controller/Work.pm
lib/MusicBrainz/Server/Data/WorkType.pm
lib/MusicBrainz/Server/Entity/WorkType.pm
root/static/scripts/work.js
root/work/edit_form.tt

Show the description of the selected type next to the type dropdown. Somewhat inelegant solution with a bunch of preloaded `<span>`s, but works well.

MBS-8576: Show work type descriptions in work creation form

---

lib/MusicBrainz/Server/Report/ReleasesMissingDiscIds.pm
lib/MusicBrainz/Server/ReportFactory.pm
root/report/index.tt
root/report/releases_missing_disc_ids.tt

This report shows all the releases that have at least one medium that has a format with the `has_discids` property, but that don't actually have a Disc ID attached to it.

MBS-8206: Add Disc ID report

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

For [brahms.ircam.fr](http://brahms.ircam.fr):
1. Allow to enter as `otherdatabases` relationship (with auto-selection, cleaning-up, and validation)
Link to issue: [MBS-9566](https://tickets.metabrainz.org/browse/MBS-9566)

MBS-9566: Add http://brahms.ircam.fr to the otherdbs whitelist

---

app.psgi
root/server.js

This seems to fix cases where the renderer socket file doesn't get removed after server.js exits. I then removed the explicit `unlink` calls I added in places, which were causing their own problems (sometimes the socket file would get removed, so the unlink would fail).
No idea if it fixes issues like [MBS-9370](https://tickets.metabrainz.org/browse/MBS-9370).

Renderer socket fixes

---

package-lock.json
package.json

The only purpose of updating `moment` is to get rid of the awful vulnerability alert that shows up on GitHub. Indeed, the spotted ReDoS vulnerability cannot be exploited on MusicBrainz server, since `moment` is running client-side and its only input is controlled (entity’s last modification time).
Updating `moment-strftime` too is needed to fix dependency issues.

Update moment and moment-strftime

---

root/layout/components/Head.js

Pages header did not pass HTML validation because of the presence of ampersand `&` character in `<style>` tag which is supposed to contain character data.
This patch prevents encoding `>` as HTML entity `&gt;` here.

Fix encoding of CSS `>` immediate children selector in HTML `<style>` tag

---

lib/MusicBrainz/Server/Data/WebService.pm

A fix by changing the redirect URL so that regex parsing is valid
at
https://github.com/metabrainz/openresty-gateways/blob/master/files/nginx/includes/musicbrainz-website_common.conf#L1

Fix SEARCH_X_ACCEL_REDIRECT to work with solr

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

As part of Google Code-in, here's code that adds UtaTen to the lyrics whitelist. It also performs cleaning of the input URL and validates to make sure that the URL conforms to the entity type being entered.

MBS-9582: Add UtaTen to the lyrics whitelist

---

lib/MusicBrainz/Server/Data/WebService.pm

Reverts metabrainz/musicbrainz-server#600
So @zas finally figured out why the redirect was working with the current search and not solr.
It is because of the way nginx is configured. We do not set the host header while doing a redirect. 
https://github.com/metabrainz/openresty-gateways/blob/master/files/nginx/includes/musicbrainz-website_common.conf#L1
But it still works since instead of using a host, we use the consul service name in our docker configs like so - https://github.com/metabrainz/docker-server-configs/blob/master/consul/services/prod.musicbrainz-server.json#L26
This makes the redirect work and also allows us to redirect from http -> https solr.
So we should change the current config on https://github.com/metabrainz/docker-server-configs/blob/master/consul/services/test.musicbr …

Revert "Fix SEARCH_X_ACCEL_REDIRECT to work with solr"

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Bandsintown recently changed its default URL pattern:  It uses one-letter prefix (instead of no prefix for artist and type name for `event` and `venue`) and numeric ID everywhere (instead of artist name).
While Bandinstown correctly redirect URLs using the old format, MusicBrainz doesn’t accept entering URLs in the new format yet.
This patch updates Bandsintown URL cleanup to handle both URL formats from user input, to convert input URLs in old format to the new format, and to validate URLs in the new format only.
Additionally, it normalizes Bandsintown URLs to use the new default subdomain `ẁww` of `bandsintown.com`. It should prevent potential further reopening of [MBS-9559](https://tickets.metabrainz.org/browse/MBS-9559).

MBS-9608: Update URL cleanup to handle new Bandsintown’s URL format

---

lib/MusicBrainz/Server/Data/Search.pm

The search query was missing the version parameter, as a result
WS/1 searches were returning errors. Fixed this for now, but this opens
up a whole new problem. Solr output isn't compatible with WS/1. so will
we finally deprecate WS/1 or keep on running search.mb.org

Fix WS/1 search

---

root/release/edit/tracklist.tt
root/static/scripts/release-editor/fields.js

After some discussion with @chhavijustme and @reosarevok:
https://chatlogs.metabrainz.org/brainzbot/metabrainz/2018-01-12/?msg=4096763&page=1
https://chatlogs.metabrainz.org/brainzbot/metabrainz/2018-01-12/?msg=4096935&page=2
We decided that a checkbox affirming that the user doesn't know what the format would result in a better UX.
https://tickets.metabrainz.org/browse/MBS-9368

MBS-9368: Ask for confirmation when leaving format empty

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Additionally, validate Deezer URLs for streaming relationships.
Actually, Hoick, JOYSOUND, and Petit Lyrics, with auto-select, cleanup and validation.
Still it doesn’t change existing URLs as requested. This should be done later on with ModBot.
It used to be rely on TLD name, but it is actually also set through path prefix and/or query parameter. This patch removes both.

MBS-9562, MBS-9587, MBS-9597, MBS-9612: Update URL cleanup

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Add auto-select, cleanup and validation for Musixmatch _artist_ and _lyrics_ URLs to be linked to MusicBrainz _artist_ and _work_, respectively.
It doesn’t allow linking Musixmatch _album_ which matches neither MusicBrainz _release group_ nor _release_.

MBS-3643: Add Musixmatch to the lyrics whitelist

---

package.json
root/static/scripts/common.js
yarn.lock

Fixes [MBS-9628](https://tickets.metabrainz.org/browse/MBS-9628) and probably many other issues in IE11.
Note: core-js is what babel-polyfill uses, but by using it directly we can include just the parts we need.

Add an Object.assign polyfill for IE11

---

package.json
root/components/Aliases/AliasTable.js
root/components/EntityHeader.js
root/components/EntityTabLink.js
root/components/EntityTabs.js
root/static/scripts/common/components/CodeLink.js
root/static/scripts/common/components/TagEditor.js
root/static/scripts/common/utility/entityHref.js
root/types.js
yarn.lock

The previous code is wrong because an object can't simultaneously satisfy two distinct, *exact* object types.
The correct way is using object type spreads as described here: facebook/flow#2626
I'm not sure why things currently type-check.

Object type spreads

---

admin/nginx/mbserver-rewrites.conf
lib/MusicBrainz/Server/Controller/Doc.pm
root/account/register.tt
root/layout/components/BottomMenu.js
root/layout/header/bottom.tt

Following https://github.com/metabrainz/metabrainz.org/pull/299, this patch updates **links** and **redirects** to replace:
* https://musicbrainz.org/doc/Social_Contract with https://metabrainz.org/social-contract
* https://musicbrainz.org/doc/About/Privacy_Policy with https://metabrainz.org/privacy
Third commit is a small code style fix only.

Move Privacy Policy and Social Contract to MetaBrainz website

---

root/instrument/List.js
root/types.js

Handles cases where `instrumentsByType` returns undefined for unused types.
I changed the Flow type to indicate the key can be unset. You can't do `[number]?` as I thought for indexer props, but `?Array<InstrumentT>` should be equivalent for our needs.

MBS-9658: /instruments page breaks if a new instrument type is added but not used

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Address 2 issues (actually related to 8 STYLE issues) about handling external URLs:
* [MBS-9645](https://tickets.metabrainz.org/browse/MBS-9645): Extend Geonames autoselect to places
* [MBS-9648](https://tickets.metabrainz.org/browse/MBS-9648): Add a bunch of lyrics sites to the whitelist

MBS-9645, MBS-9648: Update URL cleanup with Geonames and lyrics websites

---

lib/MusicBrainz/Server/Data/Search.pm
root/search/results-work.tt

Since MBS-5452 has been implemented, lyrics language was not displayed anymore in work search result.

MBS-9374: Display multiple lyrics languages in work search result

---

root/static/scripts/common/i18n/wrapGettext.js

The `domainLoaded` flag in `wrapGettext` wasn't working as intended.
(Note: this flag was only initialized to `false` in Node.js, because on
the client, all required domains are loaded via JS bundles.)
* It didn't make sense to have a single `domainLoaded` flag, because
`gettext.loadDomain` only loads a given domain for the *current
locale*. If the locale changes, the domain will no longer be loaded,
yet `domainLoaded` will be set to true. This caused MBS-9668.
* It also didn't make sense for `domainLoaded` to be local to the
`wrapGettext` closure. This meant, for whatever locale was loaded
at the time, the domain would have been reloaded (unnecessarily) up
to three times if all of `l`, `ln`, and `lp` were called. This didn't
cause any issue in practice. However, it did make the behavior …

Reload domain when locale changes (MBS-9668)

---

root/layout/components/ExternalLinks.js
t/selenium.js
t/selenium/MBS-9548.html
t/sql/selenium.sql

Restore `unique` filtering on external links from late [root/layout/sidebar/sidebar-favicons.tt#L31](https://github.com/mwiencek/musicbrainz-server/blob/3205207c3c4f524e62119489957dc05531db162f/root/layout/sidebar/sidebar-favicons.tt#L31).

MBS-9548: Filter external links by unique target

---

.eslintrc.yaml
root/layout/components/Search.js
root/server/response.js

[MBS-9672](https://tickets.metabrainz.org/browse/MBS-9672) is already fixed in `beta` with https://github.com/metabrainz/musicbrainz-server/commit/caec7c46a6a3fdadd2ab00e4b2d4250c17920b41 (cherry-picked to `master` as https://github.com/metabrainz/musicbrainz-server/commit/54579586754c51c92614c86488a8c87739a50c37).
This display bug has been inadvertently introduced by running `eslint`. This patch:
1. disables ESLint `sort-keys` rule for search type options,
2. sets ESLint `key-spacing` rule to vertically align values in object literal props.

MBS-9672: Prevent alphabetical sorting of search options with ESLint & Vertically align values

---

root/layout/components/Search.js

Define a component rather than a constant for search options.

MBS-9673: Delay localization of search options (2)

---

root/static/scripts/release-editor/init.js

This hopefully works around the issue described in https://community.metabrainz.org/t/a-problem-with-dictation-software-and-musicbrainz/376046
My guess is that the Chrome extension is modifying input values, but not triggering any `input` or `change` event to signal a change. Clearly, the Knockout model would update if an event was triggered.
You can simulate this by adding a single track with a title and artist set, opening the console, and running this:
```JavaScript
document.querySelector('.track-length').value = '3:33';
```
Moving to the recordings tab will show the track as having no time set.
The workaround is to trigger change events on all inputs on the active tab before it's changed.

Trigger inputs in release editor on tab change

---

root/static/scripts/edit/URLCleanup.js

I just added https://musicbrainz.org/relationship/770ea9f4-cba0-4194-b77f-fe2740055e34 and we should be able to autoselect stuff for it (https://tickets.metabrainz.org/browse/MBS-9688)

MBS-9688: Add autoselect and cleanup for work license rel

---

root/components/Aliases/index.js

The issue was about computing permissions to display edit links:
1. Default editing permission has been given to location editor only
2. There were no input Prop to override the default permission
This patch fixes both by adding `allowEditing` as a Prop and setting
default value to whether user is a logged-in not-disabled editor.
`allowEditing` values for area and instrument were correctly set.

MBS-9691: Fix aliases editing links

---

root/static/scripts/common/components/TagEditor.js

Aggregate tags come without vote property.
This property was set for user (up/down) voted tags.
It has not been set for tags not voted by the current user.
This patch sets default vote to 0 (withdrawn) rather than undefined.
It fixes every vote comparison in tag editor.

MBS-9693: Fix display of tags without current user’s vote

---

lib/MusicBrainz/Server/Data/CoverArtArchive.pm
t/lib/t/MusicBrainz/Server/Data/CoverArtArchive.pm

The IA has requested we set this flag on new uploads to prevent them from getting added to their public search index. They've already purged previous uploads from the index.
Their reasoning was,
"We've been digitizing CDs lately and we're finding people somewhat
confused by whether they're going to get an image or an actual CD
when looking at search results."
This doesn't affect anything on our side and we'll still be able to search the entire CAA collection on their side through https://archive.org/metamgr.php (though it's an admin tool so it requires the coverartarchive login in syswiki).
As far as the code changes here, they stated we should only need the noindex tag "once on [our] initial `PUT`" (so I believe this is the right spot), and that they'd prefer we "use the value `true` …

Set x-archive-meta-noindex on CAA uploads

---

lib/MusicBrainz/Server/Constants.pm
lib/MusicBrainz/Server/Email.pm
t/lib/t/MusicBrainz/Server/Email.pm

The purpose of this change is to provide DKIM signature.
See https://tickets.metabrainz.org/browse/MBS-9696

MBS-9696: Replace @users.musicbrainz.org with noreply@musicbrainz.org in hidden email From field

---

admin/config.sh

not to fail when MBS_ADMIN_CONFIG is not defined and shell flag `errexit` is set in caller.

Fix checking MBS_ADMIN_CONFIG env var

---

root/components/Aliases/AliasTableBody.js
root/components/Aliases/AliasTableRow.js
root/components/Aliases/index.js
root/elections/Nominate.js
root/layout/components/Footer.js
root/static/scripts/common/components/DescriptiveLink.js
root/static/scripts/edit/externalLinks.js

Two small fixes about `key` attributes of some React components:
1. Take misplaced `key` from `tr` to parent component `AliasTableRow`.
2. Add missing `key` attributes for React components given as parameters of calls to the localization function `l`.
Enforce as code style to use the placeholder name as key value in such case.

Fix key attributes for some React components

---

root/static/gulpfile.js

Resources compilation logs were full of useless warnings, this patch removes two of those:
* _MaxListenersExceededWarning_ which was due to `MaxListeners` not being proportionate to the number of MB languages. (This patch does not set it to `Infinity` either.)
* _Output exceed 256 characters_ (x432) which cluttered the output and is just dropped here.

Silence some gulp/uglifyify warnings

---

root/components/EntityTabs.js

Both URLs are correct, but `/show` subpath is unneeded and was not returned by `uri_for`.

MBS-9705: Hide /show subpath from Overview tab

---

root/components/Aliases/AliasTableRow.js

Complete f809ef73e8e68c0e99db8de2c471c26941ff9e96 which removed space from the function `bracketed`.

MBS-9707: Add space before locale attribute primary

---

root/static/scripts/release-editor/init.js

Complete bfc4aa4cbcf834ee2b9de04329f747f0cfc05c13
Fix issue MBS-9709 where clicking on button ‘Done’ rather than the button ‘Next’ in the recording association bubble would set the recording in the tab ‘Recordings’ only, not in the tab ‘Edit Note’.

MBS-9709: Only trigger change on visible inputs

---

lib/MusicBrainz/Server/ControllerBase/WS/2.pm

`WS::2 'authenticate'` is used to authenticate user from credentials and to check authorization scope.
Calling it twice was calling `Catalyst 'authenticate'` twice in a row which is not supposed to happen, thus returning 400 Bad Request error.
This patch skips authenticating from credentials again if user already exists, that is, it has already been successfully authenticated from credentials.
`WS::2 'authenticate'` still checks authorization scope.

MBS-9704: Skip checking credentials twice for WS

---

root/static/scripts/release-editor/init.js

Steps to reproduce the issue were:
- open the tab “Recordings” of the release editor;
- select a different recording for a track, without hitting the button “Done”;
- switch to any other tab and the above change is lost!

MBS-9710: Only trigger tracklist inputs

---

root/components/medium.tt

Hide work parts from the release page, still keep works related works are part of.

MBS-8629: Hide work parts from the release page

---

root/release/edit_relationships.tt

Cause was translation domain `attributes` was not loaded from the relationship editor, whereas it is required for adding new works when no existing work is found.

MBS-9675, MBS-9676: Fix work attributes localization issues in the release relationship editor

---

root/forms/dialog.tt
root/release/edit_relationships.tt

Cause was translation domain `attributes` was not loaded from the work creation dialog (opened from the release relationship editor), whereas it is required for adding new works when no existing work is found.
It reverts change from PR #673, and load gettext domain “attributes” for work creation dialog specifically.

MBS-9675, MBS-9676: Fix work attributes localization issues in the work creation dialog

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Only accept `https://daily.bandcamp.com/YYYY/MM/DD/*-review/` URLs.

MBS-9730: Auto-select, clean and validate Bandcamp Daily review page URL in release group relationships

---

admin/NormalizeToHTTPS
fabfile.py

* Add an admin script to normalize external links to `https`
This script is not for use in `hourly.sh` since it may last for more than 1h if called with a large number of rows during busy hours. It is currently running in a shell of `cron` container for [MBS-9646](https://tickets.metabrainz.org/browse/MBS-9646).
* Set default blog link in `fab tag`

Tooling: Normalize external links to https & Set default blog link

---

lib/MusicBrainz/Server/Edit/URL/Edit.pm
t/lib/t/MusicBrainz/Server/Edit/URL/Edit.pm

MBS-9439: Allow auto-editing URL to shift protocol from HTTP to HTTPS

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

MBS-9743: Fix Beatport URL cleanup for artist names starting with digit

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

to drop the new referral tag `ref_page_id`.

MBS-9740: Update Facebook URL cleanup

---

lib/MusicBrainz/Server/Controller/TagLookup.pm
lib/MusicBrainz/Server/Controller/WS/js.pm
lib/MusicBrainz/Server/Data/Search.pm

Tag lookups for artist was using a search modifier to search for sortnames and aliases with a particular boost. This is not needed or supported anymore (since it uses a weird syntax) with Solr since these fields are searched by default with a particular set of boosts

SOLR-90: Fix tag lookups for artist

---

lib/MusicBrainz/Server/Controller/Account.pm
lib/MusicBrainz/Server/Controller/Release.pm
lib/MusicBrainz/Server/Form/Admin/LinkAttributeType.pm
lib/MusicBrainz/Server/Form/Alias.pm
lib/MusicBrainz/Server/Form/Application.pm
lib/MusicBrainz/Server/Form/Artist.pm
lib/MusicBrainz/Server/Form/CDStub.pm
lib/MusicBrainz/Server/Form/Field/ArtistCredit.pm
lib/MusicBrainz/Server/Form/Field/Barcode.pm
lib/MusicBrainz/Server/Form/Field/DatePeriod.pm
lib/MusicBrainz/Server/Form/Field/DiscID.pm
lib/MusicBrainz/Server/Form/Field/FreeDBID.pm
lib/MusicBrainz/Server/Form/Field/GID.pm
lib/MusicBrainz/Server/Form/Field/IPI.pm
lib/MusicBrainz/Server/Form/Field/ISNI.pm
lib/MusicBrainz/Server/Form/Field/ISO_3166_1.pm
lib/MusicBrainz/Server/Form/Field/ISO_3166_2.pm
lib/MusicBrainz/Server/Form/Field/ISO_3166_3.pm
lib/MusicBrainz/Server/Form/Field/ISRC.pm
lib/MusicBrainz/Server/Form/Field/ISWC.pm
lib/MusicBrainz/Server/Form/Field/Length.pm
lib/MusicBrainz/Server/Form/Field/Relationship.pm
lib/MusicBrainz/Server/Form/Field/Setlist.pm
lib/MusicBrainz/Server/Form/Field/Time.pm
lib/MusicBrainz/Server/Form/Field/URL.pm
lib/MusicBrainz/Server/Form/Recording.pm
lib/MusicBrainz/Server/Form/Role/EditNote.pm
lib/MusicBrainz/Server/Form/User/EditProfile.pm
lib/MusicBrainz/Server/Form/User/Login.pm
lib/MusicBrainz/Server/Form/User/Register.pm

Move localization of these error messages from Moose code to templates.

MBS-9687: Fix editing forms field error message localization

---

root/components/FormRowRadio.js
root/components/SelectField.js
root/layout/components/Search.js
root/search/components/SearchForm.js
root/static/scripts/common/i18n.js
root/static/scripts/common/i18n/NopArgs.js
root/types.js

Fixes the same bug as MBS-9673 (see ccdb147). The idea is to delay the localization of the strings from when the module is loaded until the request lifecycle.

MBS-9757: Search page form is sometimes in the wrong language

---

root/search/components/AreaResults.js
root/search/components/ArtistResults.js
root/search/components/EventResults.js
root/search/components/SeriesResults.js
root/search/lib/inline-results-artist.tt
root/search/lib/inline-results-recording.tt
root/search/lib/inline-results-release.tt
root/search/results-annotation.tt
root/search/results-cdstub.tt
root/search/results-editor.tt
root/search/results-instrument.tt
root/search/results-label.tt
root/search/results-place.tt
root/search/results-release_group.tt
root/search/results-tag.tt
root/search/results-work.tt

Hide search scores from the UI by moving it to the added attribute `data-score` for each result.

MBS-9767: Hide search scores from the UI

---

root/components/forms.tt
root/components/relationship-editor.tt
root/forms/relationship-editor.tt
root/release/edit/information.tt
root/release/edit/layout.tt
root/release/edit/tracklist.tt
root/static/scripts/common/MB.js
root/static/scripts/common/entity.js
root/static/scripts/relationship-editor/common/dialog.js
root/static/scripts/relationship-editor/common/entity.js
root/static/scripts/relationship-editor/common/fields.js
root/static/scripts/relationship-editor/common/viewModel.js
root/static/scripts/release-editor/dialogs.js
root/static/scripts/release-editor/fields.js
root/static/scripts/release-editor/init.js

This is a cleanup which improves a few things:
1. Removes the `i18n` reference from the global `MB` object.
2. Removes some ugly hacks where we had to pass strings translated by TT to a JavaScript function (`expand`). Now we can just use `l` directly in the JS.
3. Interpolating raw HTML into a translated string will no longer be possible soon: all raw strings will be HTML-escaped, so you'll have to use JSX to interpolate markup. Moving these instances out of the knockout templates will allow us to easily fix them later.

Remove MB.i18n references from knockout bindings

---

lib/MusicBrainz/Server/Controller/Artist.pm
lib/MusicBrainz/Server/Data/Search.pm
lib/MusicBrainz/Server/Entity/Medium.pm
root/components/common-macros.tt
root/components/medium.tt
root/components/recordings-list.tt
root/edit/details/merge_recordings.tt
root/medium/tracklist.tt
root/recording/merge.tt
root/release/index.tt
root/search/lib/inline-results-recording.tt
root/static/scripts/common/MB/Control/Autocomplete.js
root/static/scripts/common/components/EditorLink.js
root/static/scripts/common/components/EntityLink.js
root/static/scripts/common/entity.js
root/static/scripts/tests/entity.js
root/static/styles/layout.less
t/lib/t/TemplateMacros.pm

Removes the lodash `_.template` code which was used to render links, and plugs in the React components which we've had for a while. It's a bit ugly, but not as bad as before.

Render entity links in release/relationship editors with React

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

The ticket mentioned that http and https were not detected as dupes. There seems to be no reason *not* to default to https though, so we might as well. Split the cleanup in two since the "fix cruft" bit only affects some, but not all, of the URLs. While at it, I added a couple tests for this, one per type.

MBS-9766: change worldcat cleanup to https + add tests

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

This was requested to ensure duplicate http and https can't be added. They seem to redirect to https anyway nowadays, so we might as well.

MBS-9763: clean up setlist.fm to https

---

root/series/SeriesHeader.js

This fixes an issue where, say, a release series just says "Release" in edit lists, making it look like the edit list for a release.
Alternatively, we could keep the code as it is, but rename all the existing types to include "series" when appropriate, as with instruments (e.g. "string instrument"). I'm fine with this if it is the preferred solution.

MBS-9788: Indicate "series" in series edit lists

---

lib/MusicBrainz/Server/Data/Event.pm
lib/MusicBrainz/Server/Data/Search.pm

Event search was not loading additional (relationship-based) info for external search, only for direct search. Changing it to do so, following the example of works.
load_ids is basically the same method as for works - not sure if we have some way of generalising this that might be good here.

MBS-8062: query for performers and locations when rendering external event search

---

lib/MusicBrainz/Server/Constants.pm
lib/MusicBrainz/Server/Controller/User.pm
lib/MusicBrainz/Server/Data/Editor.pm
lib/MusicBrainz/Server/Entity/Editor.pm

Address two related issues:
- [MBS-9210](https://tickets.metabrainz.org/browse/MBS-9210): Update password hash on login if bcrypt cost parameter increased, so as to gradually rehash password for all active accounts.
- [MBS-9208](https://tickets.metabrainz.org/browse/MBS-9208): Increase bcrypt cost parameter to 12.

MBS-9208, MBS-9210: Increase bcrypt cost parameter to 12, for all active accounts

---

root/annotation/revision.tt
root/annotation/summary.tt
root/components/common-macros.tt
root/release_group/index.tt
root/static/scripts/area/index.js
root/static/scripts/artist/index.js
root/static/scripts/common.js
root/static/scripts/common/components/Annotation.js
root/static/scripts/common/components/Collapsible.js
root/static/scripts/common/components/CommonsImage.js
root/static/scripts/common/components/CritiqueBrainzReview.js
root/static/scripts/common/components/WikipediaExtract.js
root/static/scripts/event/index.js
root/static/scripts/instrument/index.js
root/static/scripts/label/index.js
root/static/scripts/place/index.js
root/static/scripts/release-group/index.js
root/static/scripts/series/index.js
root/static/scripts/work/index.js

The Jed language bundles only contain strings that appear in files under root/static/scripts/. This is to reduce bundle sizes by removing strings only needed on the server. See [root/static/gulpfile.js lines 215 - 223](https://github.com/metabrainz/musicbrainz-server/blob/f94973b0052418679429994a4a62d1f99af136bc/root/static/gulpfile.js#L215-L223).
Thus, components with translated strings used on the client must be placed under root/static/scripts/.
Note that this commit by itself doesn't immediately fix things, because new .pot files have to be generated, and new .po files have to be downloaded based on those; msggrep looks at the .po files in order to filter strings by source path.

MBS-9817: Missing i18n in hydrated components

---

lib/MusicBrainz/Server/Controller/Series.pm

By the way: is there a reason we specifically limit what we show here?

MBS-9641: Show label-series rels on series page

---

lib/MusicBrainz/Server/Controller/CDTOC.pm

For some reason, this wasn't loading the recordings, meaning all recordings showed as removed.
Also changed the way it works a bit to mirror the one for multi-artist release lists (slightly below). 
In fact, I'd suggest just having the two options be the same thing with different filters when we look into this again for changing the templates into React - I see no reason for the current choice of the one-artist result not showing ACs, which might very well be relevant whether for collaborations or alternate names.

MBS-9422: Load recordings for CDToc attach

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Additionally improve cleanup code to better handle legacy format (documented in [MBS-6130](https://tickets.metabrainz.org/browse/MBS-6130)) and stop handling URL without slug (which may come from Beatport redirect).

MBS-9846: Fix Beatport URL cleanup

---

lib/MusicBrainz/Server/Data/URL.pm

**Problem**  
Creative  commons licenses only match if links are HTTP, while most will probably be HTTPS.  
**Solution**  
Replace "http" regex with "https?", as "?" matches 0 or 1 for the previous character.  
Made for [GCI](https://codein.withgoogle.com/tasks/5620778444783616/?sp-organization=5353072260808704).

MBS-9863: License links are ignored if https

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Discogs now has support for works (or as they're called on Discogs, 'compositions'). This PR allows these to be recognized.
Unlike all other Discogs entities (apart from users), the IDs aren't numerical, i.e:
* https://www.discogs.com/composition/1b383ed3-7b58-45ff-8f1b-1135c41988d4-In-Verbundenheit
* https://www.discogs.com/composition/d6652f48-35ad-4900-9c42-d0b0f2f84674-Mr-Henri-Rousseaus-Dream
* https://www.discogs.com/composition/27b17569-3e40-40b5-9819-409794c2d5d9-In-The-Hospital
Because of this, I also implemented a new replace statement just for compositions.

MBS-9873: Add autoselect for Discogs compositions

---

root/genre/List.js
root/instrument/List.js

Documentation on how to request a new instrument or a new genre is missing from https://musicbrainz.org/instruments and https://musicbrainz.org/genres. 
This PR has the addition of such documentation. 
https://tickets.metabrainz.org/browse/MBS-9900

    MBS-9900:  Add information on requesting instruments/genres to their lists

---

root/account/PreferencesSaved.js

"profile/" here led to a non-working link, that also caused a situation where someone registering the "profile" username would get seen every time someone changed their prefs. I've also removed the malicious "profile" user, but this fixes it so that the link will actually go to the appropriate user profile.

Fix link to profile from preferences saved dialog

---

lib/MusicBrainz/Server/Data/Event.pm

When viewing a user's event collection, the events were displayed in chronological order. The most relevant results would usually be the most recent ones, so this will reverse the the default $order variable.  
This is cleaner than changing the actual columns passed into **order_by**, since it keeps all of the "DESC" handling within the order_by function itself (found in [Utils.pm](https://github.com/metabrainz/musicbrainz-server/blob/master/lib/MusicBrainz/Server/Data/Utils.pm#L372)).

MBS-9847: Show event collections in reverse by default

---

root/search/components/EventResults.js
root/static/scripts/common/components/EntityLink.js

> Event dates are displayed:
>1. in parenthesis right after the name in the column “Name”,
>2. in the column “Date”.
>
> Example: https://musicbrainz.org/search?query=test&type=event
> It is redundant and unnecessarily widens the event results page.
I also merged the date & time columns, since otherwise they were on the other side of the screen (or taking too much space next to eachother as seperate columns).
<br/>
Before:
After:

MBS-9765: Do not display event dates twice in search results

---

root/release/edit/information.tt

This PR improves of the description of MusicBrainz annotation field in release editor to mention licenses.
https://tickets.metabrainz.org/browse/MBS-8311

    MBS-8311: Annotation field in the release editor does not mention liscenses

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

When inputting a Tipeee URL that begins with a language-related subdomain, i.e...
https://en.tipeee.com/borisdalstein
...the URL is not recognised as tipeee. This is the case with all 5 languages that the Tipeee website supports: **en**, **it**, **fr**, **de** & **es**.
An example of a _working_ URL would be:
https://www.tipeee.com/borisdalstein
----

MBS-9905: Tipeee Broken URL validation

---

lib/MusicBrainz/Server/Report/ReleaseLabelSameArtist.pm
lib/MusicBrainz/Server/ReportFactory.pm
root/report/index.tt
root/report/release_label_same_artist.tt

This commit adds support for a new daily report, which shows all releases which have label names that are identical to their artist names.
If "ReleaseLabelSameArtist" is too ambiguous, please don't hesitate to suggest an alternative name.
https://tickets.metabrainz.org/browse/MBS-3685

MBS-3685: Report for releases where label name = artist name

---

lib/MusicBrainz/Server/Controller/Root.pm
root/main/index.js

Replace each cover art with a message explaining that issue [CAA-116](https://tickets.metabrainz.org/browse/CAA-116) is pending, for every browser with "Chrome" in the user agent string.
See the ticket for motivations.

MBS-9930: Disable CAA images on the homepage for Chrome-based browsers

---

lib/MusicBrainz/Server/Report/PlaceReport.pm
lib/MusicBrainz/Server/Report/PlacesWithoutCoordinates.pm
lib/MusicBrainz/Server/ReportFactory.pm
root/report/index.tt
root/report/places_without_coordinates.tt

This commit adds support for a new daily report, which shows all the places which haven't been assigned coordinates.
https://tickets.metabrainz.org/browse/MBS-9907
I originally did this with an "annotation" column, but seeing as the number of entries with annotations is relatively low, it seemed more of an inconvenience.
The final result looks as follows:

MBS-9907: Report for places without coordinates

---

lib/MusicBrainz/Server/Report/ReleaseLabelSameArtist.pm
root/report/release_label_same_artist.tt

This continues on the work from #760.
In [MBS-3685](https://tickets.metabrainz.org/browse/MBS-3685), a new report page was created for artists which have the same label name as artist name. However, this did not include featured artists. This PR compares the artist names from **artist_credit_name** instead of just **artist_credit**,  which means that all featured artists will also be checked.
For example, a release like...
https://musicbrainz.org/release/14bfe5a4-ae36-4642-9ed3-fdadfe83f2e5 
... is now identified.
Before, there were 2964 entities found in the report, but now there are 7026.

Improve Label Report from #760

---

lib/MusicBrainz/Server/Controller/WS/js/Work.pm
root/static/scripts/common/MB/Control/Autocomplete.js

Chose to use the same way as we do with artists and writers because the more consistent / usual way (parentheses after the name) was blocked by the way we do work languages. Alternatively, we could do the usual with types *and* move languages to a "Languages: X, Y" line like writers / artists.

MBS-7192: Show work types in inline search

---

root/edit/details/add_remove_alias.tt
root/edit/details/edit_alias.tt
root/edit/details/macros.tt

https://tickets.metabrainz.org/browse/MBS-9872
The rename in https://github.com/metabrainz/musicbrainz-server/commit/5cb19e7248bc838d5124559fa36d1d39b67413ef left three files using "bracketed" behind, which broke the ended flag (as reported) plus some alias edit displays.

MBS-9872: change leftover bracketed macro calls to bracketedWithSpace

---

lib/MusicBrainz/Server/Report/ReleasesWithCAANoTypes.pm
lib/MusicBrainz/Server/ReportFactory.pm
root/report/index.tt
root/report/releases_with_caa_no_types.tt

https://tickets.metabrainz.org/browse/MBS-6232
The query itself seems fine - I ran it on queen and got the expected results (well, unexpectedly many but they seem correct). I don't have the cover art tables filled locally so I couldn't fully test the report itself but I expect it should be fine.

MBS-6232: Add report for releases which only have cover art (in CAA) with no types

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Add auto-select, clean-up, and validation for linking lyrics from Bandcamp track to work.
Add test.

MBS-9831: Add Bandcamp to the Lyrics Whitelist

---

lib/MusicBrainz/Server/Controller/Role/Load.pm
t/selenium.js
t/selenium/Redirect_Merged_Entities.html
t/sql/selenium.sql

As discussed in tickets [MBS-9827](https://tickets.metabrainz.org/browse/MBS-9827) and [MBS-4937](https://tickets.metabrainz.org/browse/MBS-4937), it was difficult to tell whether you were on the page of a merged ~~artist~~ entity. This PR will cause a 301 redirect to the "correct" page if this is not the case.  
Currently, the only way to tell is through the **link rel="canonical"** tag.
i.e:
[f21a407e-3af9-4539-ab3d-c92a5230dff6](https://musicbrainz.org/artist/f21a407e-3af9-4539-ab3d-c92a5230dff6) will redirect you to [1155431a-d35e-4863-9ae0-e3c24eb61aa9](https://musicbrainz.org/artist/1155431a-d35e-4863-9ae0-e3c24eb61aa9).
Selenium test cases for #736.
This tests:
1. Redirection of `/artist/gid`.
2. Redirection of `/artist/gid/releases` (actions).
3. Redirection of …

MBS-9827: Redirect Merged Entities

---

root/report/places_without_coordinates.tt
root/static/styles/layout.less

As requested in comment to this ticket, link to Google Maps to search for place's coordinates.
Plus, link to MapQuest and Qwant Maps ([open source](https://github.com/QwantResearch/qwantmaps)) which both use OpenStreetMap data.
Finally, make small UI changes, displaying _external link_ favicon ahead of this set of links.

Improvements to PR #762 (MBS-9907)

---

script/xgettext.js

Detecting whether the literal contains `${}` turned out to be simple. There's no issue if a translation contains `${}`.

Add support for template literals to xgettext.js

---

root/static/scripts/release-editor/fields.js
root/static/scripts/tests/release-editor/fields.js

Convert both `7400` and `11400` to `1:14:00`. See added tests for more examples.

MBS-9605: Fix converting track length over 1 h

---

root/static/scripts/tests/relationship-editor.js

`relationships` should be an array, not an object.
Cherry-picked from the Webpack PR.

Fix relationships type in test data

---

lib/DBDefs/Default.pm
lib/MusicBrainz/Server.pm
lib/MusicBrainz/Server/Context.pm
lib/MusicBrainz/Server/Controller/Root.pm

Running Selenium tests against a development server (with `USE_SELENIUM_HEADER` enabled) required a restart of plackup after they were done, due to the database handle still pointing to the `SELENIUM` DB. This sets/resets the handle properly during the request lifecycle (there's now no issue performing `READWRITE` requests concurrently, even).
There were related issues with the DBDefs settings not being reset, and the Redis cache being shared (which could clobber login sessions on the development server). To resolve the DBDefs issue, we save CODE references to the original DBDefs methods and reset them after dispatch. To resolve the cache issue, we introduce a `CACHE_NAMESPACE` setting and modify it to add a 'Selenium:' prefix during Selenium test requests.

Unbreak plackup after running Selenium tests

---

admin/sql/caa/CreateMQTriggers.sql
admin/sql/caa/DropPGQ.sql

by triggering a reindex from `cover_art_archive.cover_art_type` table change.

MBS-9957: Reindex release cover art on cover art type change

---

root/components/UserAccountTabs.js

Regression introduced with https://github.com/metabrainz/musicbrainz-server/commit/32cdf4950da69520edb47ffaa776e2383b35c7cb

MBS-9967: Fix typo borking Subscribers tab

---

root/layout/components/sidebar/PlaceSidebar.js

by replacing "?" with "&" for the second query parameter.

MBS-9966: Fix seeding place to add event

---

root/static/scripts/edit/components/ArtistCreditBubble.js
root/static/scripts/edit/components/ArtistCreditEditor.js
root/static/scripts/release-editor/bindingHandlers.js

I suggest trying to test/break this locally to see if it works and ignoring my useless commit message, since I got frustrated trying to fix this and could barely remember why things worked afterward. 😆
---
This works around the issue while we wait for the release editor to be converted to React, and for the artist credit editor/bubble code to be implemented properly.
The main fix is in setting the `target` and `componentInst` data values on the bubble div before rendering it, *not* after. I don't remember why that works, exactly, after half an hour in the Chrome debugger, but it's not important or interesting since this code is going in the scrap heap.
Fixing this then revealed that the "change matching artists" option was broken, because someone (me) thought mixing knockout and React was …

Workaround for MBS-9865

---

lib/MusicBrainz/Server.pm
lib/MusicBrainz/Server/Filters.pm

Removing the `language` filter and its dependency on `Locale::Language` resolves a warning on plackup startup (in Perl 5.28) that this module is being removed.

Remove some apparently unused TT filters

---

lib/MusicBrainz/Server/Data/EntityAnnotation.pm
root/annotation/edit.tt

1. Fix long-standing regression [MBS-4709](https://tickets.metabrainz.org/browse/MBS-4709): Can't use square brackets in annotations.
Note: The future Markdown syntax will allow for HTML entities again.
2. Improve embedded documentation about annotation syntax:
* [MBS-4469](https://tickets.metabrainz.org/browse/MBS-4469): lists syntax only partly working
* [MBS-8803](https://tickets.metabrainz.org/browse/MBS-8803): `[<entity_type>:<mbid>|<name>]` links

MBS-4469, MBS-4709, MBS-8803: Address some annotation issues

---

lib/MusicBrainz/Server/Entity/ISNI.pm
root/layout/components/sidebar/SidebarIsnis.js

- Fix a regression introduced during sidebar rewrite to React
- Move from `isni-url.oclc.nl` to `isni.org`

MBS-9971: Link ISNI code to isni.org

---

docker/musicbrainz-tests/DBDefs.pm
docker/musicbrainz-tests/run_tests.sh
docker/templates/Dockerfile.tests.m4
root/account/edit.tt
root/area/create.tt
root/artist/create.tt
root/components/relationship-editor.tt
root/entity/edit.tt
root/event/create.tt
root/forms/dialog.tt
root/instrument/create.tt
root/label/create.tt
root/place/create.tt
root/recording/create.tt
root/release/edit_relationships.tt
root/release_group/create.tt
root/series/create.tt
root/work/create.tt
t/selenium.js
t/selenium/MBS-9941.html
t/sql/selenium.sql

This fixes the inline search for works in the relationship editor, and the area selection bubbles, when using a non-English translation.
The attributes domain isn't currently needed, AFAICT, but it will be once we fix all the untranslated strings in Autocomplete.js.

MBS-9941: Load more gettext domains on edit pages

---

root/static/scripts/guess-case/MB/GuessCase/Handler/Release.js
root/static/scripts/guess-case/MB/GuessCase/Handler/Track.js
root/static/scripts/guess-case/MB/GuessCase/Main.js

https://tickets.metabrainz.org/browse/MBS-9975
Release (and RG) and Track (so, Recording) have no sort name methods, because they don't have sort names. Which is great... but their aliases have, so those break. This just adds the simplest possible sort name method (copied from Work) which is, IMO, all they need.

MBS-9975: Add release/track sortname guess-case (for aliases)

---

root/area/AreaHeader.js
root/artist/ArtistHeader.js
root/event/EventHeader.js
root/instrument/InstrumentHeader.js
root/instrument/List.js
root/isrc/Index.js
root/label/LabelHeader.js
root/place/PlaceHeader.js
root/recording/RecordingHeader.js
root/release_group/ReleaseGroupHeader.js
root/series/SeriesHeader.js
root/url/URLHeader.js
root/work/WorkHeader.js

Entity headers + instrument list

MBS-9936: Move from CJS style to ES6 (imports, exports) (I)

---

lib/MusicBrainz/Server/Controller/Role/Details.pm
lib/MusicBrainz/Server/Plugin/Canonicalize.pm
root/area/layout.tt
root/artist/layout.tt
root/components/common-macros.tt
root/entity/Details.js
root/event/layout.tt
root/forms/dialog.tt
root/instrument/layout.tt
root/label/layout.tt
root/layout.tt
root/layout/components/Head.js
root/place/layout.tt
root/recording/layout.tt
root/release/layout.tt
root/release_group/ReleaseGroupLayout.js
root/release_group/layout.tt
root/series/layout.tt
root/url/layout.tt
root/work/layout.tt

This doesn't seem to be needed anymore now that we perform a 301 redirect for merged MBIDs. The MBID in the URL should always be the same as the main entity gid in that case.

Remove replace_gid

---

root/static/scripts/common/i18n/expand2.js
root/static/scripts/tests/i18n/expand2.js

I don't have a specific line of code where this is needed, but in addition to being a small ergonomic benefit, it provides some additional safety where we call this function via untyped files and don't know where null/undefined values are lurking.
Cherry-picked from #801

Gracefully handle null, undefined in expand2

---

root/components/FormRowSelectList.js
root/static/scripts/work.js
t/selenium/Work_Editor.html

At the moment, the user can select both "No lyrics", and other languages when editing works' lyrics. This PR aims to prevent this.

MBS-9340: Improve lyrics language selector

---

docker/musicbrainz-tests/DBDefs.pm

Given that our tests run concurrently now, they should be using separate caches for obvious reasons. (So far we've luckily not seen too many issues caused by this.) This doesn't achieve that, but allows us to actually have it use `CACHE_NAMEPSACE` if we set it to something.

Fix tests DBDefs to use CACHE_NAMESPACE

---

lib/MusicBrainz/Server/Controller/CDTOC.pm
lib/MusicBrainz/Server/Data/Medium.pm
lib/MusicBrainz/Server/Edit/Medium/SetTrackLengths.pm
lib/MusicBrainz/Server/Entity/MediumCDTOC.pm
root/cdtoc/list.tt
t/lib/t/MusicBrainz/Server/Edit/Medium/SetTrackLengths.pm
t/sql/tracklist.sql

[MBS-9297](https://tickets.metabrainz.org/browse/MBS-9297): Set track lengths from CD TOC only if different
Until then, it was possible to set track durations from CD TOC for any attached medium even if it does not change a millisecond of it.
This patch hides unnecessary links to `/set-durations` and disallows `SetTrackLengths` medium edits with no change.
Note about hidden pre-gap tracks: these are ignored at purpose, because CD TOC is not considered reliable regarding their lengths.

MBS-9297: Set track lengths from CD TOC only if different

---

t/tests.t

The tests container already has one running in the background. Someone running the tests on their own will almost definitely already have one running, too.

Do not start a template renderer in t/tests.t

---

docker/musicbrainz-tests/run_tests.sh

We don't add a ton of new Perl code these days, so I think this is of limited utility to have run on *every* build (even ones where no Perl is touched). I don't remember the last time it reported an issue, either. It takes around a minute to run this locally, so I think it could save a good chunk of time if we disable it. If someone does add a lot of Perl code in some PR, it can still easily be run locally.

Disable t/critic.t

---

bin/rsync-staticbrainz-files
docker/musicbrainz-sitemaps/crontab
docker/templates/Dockerfile.sitemaps.m4

This failed because `$STATICBRAINZ_SERVERS` (set on the container via `--env`) is unset when bin/rsync-staticbrainz-files runs.
I've made three changes to address this:
1. Run rsync-staticbrainz-files with `bash -u` so that it errors on unset variables.
2. Source /etc/container_environment.sh in the crontab so that rsync-staticbrainz-files has access to `$STATICBRAINZ_SERVERS`.
3. Give the musicbrainz user access to /etc/container_environment.sh by changing permissions in the Dockerfile. This is described in https://github.com/phusion/baseimage-docker#security

MBS-9994: Sitemaps are not rsynced to gateways

---

lib/MusicBrainz/Script/JSONDump/Incremental.pm
t/script/ExportAllTables.t

This is needed because both DumpJSON.t and ExportAllTables.t use LoadReplicationChanges, and they may run concurrently during tests.

Per-database lock file in LoadReplicationChanges

---

root/annotation/edit.tt

Issue was angle quotes were not escaped.
- Remove angle quotes to follow other link syntax
- Switch entity-type to kebab-case like release-group
- Write MBID all caps since it is an acronym like URL
- Replace name with label not to confuse wwith entity name
Fix commit 44128de8a3ae822cac6f25cd17e3149371bfae0e
Change-Id: I6a4984c73d97ca5588d9681f2575d7a1270fd7e3

MBS-8803: Fix entity link syntax doc for annotation

---

root/static/scripts/common/components/TagEditor.js

Uses the correct translation on the server now, thus fixing a warning that the client/server markup differs on the release group tags page.
This is cherry-picked from #801.

Fix vote button titles to use N_l

---

HACKING.md
docker/musicbrainz-tests/DBDefs.pm
docker/musicbrainz-tests/run_tests.sh
lib/DBDefs.pm.sample
lib/DBDefs/Default.pm
lib/MusicBrainz/Server.pm
lib/MusicBrainz/Server/Sitemap/Incremental.pm
t/script/BuildSitemaps.t
t/selenium.js

Similar to what was done for the DumpJSON and ExportAllTables tests, create a separate musicbrainz_test_sitemaps DB to allow running it concurrently in a safe manner.
In order to use this DB for requests made during the incremental sitemaps tests, I've adapted the `selenium` header into a more generic `mb-set-database` header to allow selecting any database for the duration of the request.

Use separate DB for sitemaps tests

---

lib/MusicBrainz/Server/Controller/OAuth2.pm
t/lib/t/MusicBrainz/Server/Controller/OAuth2.pm

Allow * origins and add support for preflight requests to the following
endpoints:
/oauth2/token
/oauth2/tokeninfo
/oauth2/userinfo
The browser should normally only send OPTIONS to /oauth2/userinfo since
it makes use of a non-safelisted header (Authorization).

MBS-9993: /oauth2/ CORS

---

root/static/scripts/common/i18n.js
root/static/scripts/common/i18n/attributes.js
root/static/scripts/common/i18n/countries.js
root/static/scripts/common/i18n/instrument_descriptions.js
root/static/scripts/common/i18n/instruments.js
root/static/scripts/common/i18n/languages.js
root/static/scripts/common/i18n/relationships.js
root/static/scripts/common/i18n/scripts.js
root/static/scripts/common/i18n/statistics.js
root/static/scripts/common/i18n/wrapGettext.js

Before this commit, wrapGettext was a single function that handled all three of dgettext, dngettext, and dpgettext. This required some hacks due to the different argument orders these functions have; the code is much clearer by just having separate exports. Additionally, we can more easily define sound Flow types this way.
This is cherry-picked from #801.

Un-genericize wrapGettext

---

root/static/scripts/edit/URLCleanup.js

LINK_TYPES should definitely have keys sorted. If we don't want CLEANUP keys sorted because of them matching the way the code works or whatever I can undo that part, let me know

URLCleanup eslint fixes: fix key sort for second level keys

---

root/static/scripts/common/i18n/attributes.js
root/static/scripts/common/i18n/countries.js
root/static/scripts/common/i18n/instrument_descriptions.js
root/static/scripts/common/i18n/instruments.js
root/static/scripts/common/i18n/languages.js
root/static/scripts/common/i18n/relationships.js
root/static/scripts/common/i18n/scripts.js
root/static/scripts/common/i18n/statistics.js

These all used different export styles for some reason. Some were missing `@flow` too.

Standardize i18n domain file formatting

---

root/static/scripts/common/i18n/expand2.js
root/static/scripts/tests/i18n/expand2.js

This is needed for instrument links in relationship link phrases. For example, in 'performed {instrument:%|instruments} on', we will want to substitute the '%' with a link to the actual instrument page, as our Perl-based expand code currently does.

Allow % replacements to be React nodes

---

docker/templates/Dockerfile.tests.m4
docker/templates/macros.m4

instead of git commit ac9a0bdd209091a61c97915d8419180002e87931
The content is the same, the reference only changes.
Note: Tag [v-2019-01-07](https://github.com/metabrainz/mmd-schema/releases/tag/v-2019-01-07) is on `production` branch, whereas commit was from `master` branch.

Refer to mmd-schema git tag v-2019-01-07

---

lib/MusicBrainz/Server/Entity/URL/CPDL.pm

https://tickets.metabrainz.org/browse/MBS-10008
Since the URLs can't be differentiated, the best we can do is generalize this to "Score(s)" or "Scores", sadly.

MBS-10008: Generalize CPDL sidebar name

---

root/url/UrlHeader.js
root/url/UrlLayout.js
root/url/layout.tt

https://tickets.metabrainz.org/browse/MBS-9923
Index probably can't be converted until the relationship components are merged, meaning this Layout file is currently unused, but it shouldn't hurt to have it already. Once the relationships component is merged it should be very easy to finish MBS-9923
UrlHeader renamed for consistency on @mwiencek's suggestion.

MBS-9923 (I): Convert URL Layout to React

---

lib/MusicBrainz/Server/Controller/Artist.pm
root/artist/SpecialPurpose.js
root/artist/special_purpose.tt

https://tickets.metabrainz.org/browse/MBS-10018
The current implementation does not display any info about the artist being (not) edited. I think that's confusing and it's much better to have the header present (both to show the user *which* artist they're trying to edit, and to allow them more navigation options away from the error) so changed this from the original layout.tt to use ArtistLayout.

MBS-10018: Convert artist/special_purpose.tt to React

---

lib/MusicBrainz/Server/Controller/WS/js/Edit.pm

https://tickets.metabrainz.org/browse/MBS-8782
This was already supposed to happen, it's just comma_only_list wasn't actually being passed correctly to the ws/js TT renderer. @mwiencek figured how to pass it properly and now it seems to work right :)

MBS-8782: Correctly pass comma_only_list in WS::js::Edit

---

root/static/scripts/edit/URLCleanup.js

This just separates things that have their own match + cleanup but were before grouped into a huge ball of per-relationship-type cleanup. I feel it's much easier now to follow stuff. I left together under otherdatabases the ones that are only matched, but not cleaned up in any other way - I'd suggest to split those only if we start also cleaning them up.

URLCleanup fixes: split grouped cleanups for clarity

---

lib/MusicBrainz/Server/Data/Medium.pm
t/lib/t/MusicBrainz/Server/Data/Medium.pm
t/sql/mbs-9309.sql

If two mediums are being merged, where recording 1 on medium 1 is being merged into recording 2 on medium 2, and recording 2 on medium 2 is being merged into recording 1 on medium 1 (because the positions are swapped), then the current merge logic will fail, because after performing the first merge, it proceeds to try and merge the same recording into itself.
This situation is now ignored, so no merge is performed, which I think is safer (it certainly wouldn't have been intended in edit #40241956). I'm not even sure it makes sense to support the scenario in MBS-8614 anymore; that should probably fail the edit and at the very least display a warning.
I think we should show a warning in this case, too, but we have separate pieces of logic which should probably be unified first …

MBS-9309: Ignore swapped recordings in medium merges

---

lib/MusicBrainz/Server/Data/LinkAttributeType.pm

The ORDER BY should make the new link creation order deterministic. Note that if you change ASC to DESC, it'll consistently reproduce the failure given in the description to MBS-9276.

MBS-9276: Fix flaky Edit::Instrument::Merge test

---

docker/Dockerfile.tests
docker/templates/macros.m4

**Problem:** Yarn Packaging subkey often changed during the latest months, breaking our build process.
**Solution:** Refresh APT keys when installing yarn package or on package installation failure.

Fix APT package installation failure by refreshing keys

---

root/static/scripts/common/components/WikipediaExtract.js

https://tickets.metabrainz.org/browse/MBS-10033

MBS-10033: Missing space after Wikipedia blurb

---

root/user/edits.tt

https://tickets.metabrainz.org/browse/MBS-10029
I'm not happy with the capitalization (we use "Release group X by Y" for example, so I'd want "Open edits" rather than "Open Edits") so changing that on a second commit but I can drop that one if it's a problem.

MBS-10029: Include editor on page title of Edits by Editor

---

lib/MusicBrainz/Server/Data/Search.pm

https://tickets.metabrainz.org/browse/MBS-10031
Reason seemed to be the sort-name served by the search result wasn't being turned into sort_name since the fixup didn't run on the relationship entity. This does now load it properly, but I'm not 100% sure this is the best possible way of doing it and won't have any unintended consequences.

MBS-10031: Fix schema mapping of entities in relationships

---

.eslintrc.yaml

I keep finding imports we've forgotten, and while there's at least a case I remember seeing when a seemingly unused var was actually needed, I think this makes sense in general.

Add no-unused-vars rule to eslint

---

INSTALL.md
script/compile_resources.sh

This seems like a good idea, in case people forget to do it when updating their git checkout or switching branches. I thought about this after merging the Webpack PR.
If node_modules/ is up-to-date and this command is a no-op, it only takes about ~0.5s to run on my machine.

Run yarn in compile_resources.sh

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

https://tickets.metabrainz.org/browse/MBS-10032
Since every artist seems to have an author page automatically (https://itunes.apple.com/us/author/yung-beef/id1090884617 is a rapper with zero books, so it's not even connected to having multiple types of media), and the IDs are the same, I feel it makes sense to just store the links as "artist" (which is specifically about music AFAICT).

MBS-10032: detect and cleanup iTunes "author" URLs for artists

---

entities.json
lib/MusicBrainz/Server/Controller/Area.pm
lib/MusicBrainz/Server/Data/Event.pm
root/area/AreaEvents.js
root/server/components.js

https://tickets.metabrainz.org/browse/MBS-10022
I don't see any real reason not to add this, and in fact it should at least help lower the amount of stuff cluttering the Overview page of areas. Given some take a minute to load, this should be a slight improvement. Plus, places have this tab and we use place and area as effectively equivalent everywhere else for events.

MBS-10022: Event tab for areas

---

root/static/scripts/common/i18n/wrapGettext.js

If the same renderer process handles two requests in two different languages, the `wrapGettext` instance won't call `tryLoadDomain` for one of the languages. The call must be moved so that it's invoked for every string, as it was before 77a1286.

Call tryLoadDomain on every string

---

root/elections/ElectionDetails.js
root/report/components/InstrumentList.js
root/utility/formatUserDate.js

https://tickets.metabrainz.org/browse/MBS-9990
https://momentjs.com/guides/#/parsing/strict-mode/ (moment.defaultFormat is YYYY-MM-DDTHH:mm:ssZ, https://momentjs.com/docs/#/displaying/format/)
If not being passed a valid date, it will just say Invalid date. Is there anywhere where we're passing this function anything else than a YYYY-MM-DDTHH:mm:ssZ format? (multiple formats can be allowed, if needed)

MBS-9990: Make formatUserDate check it's being passed a valid date

---

package.json
yarn.lock

Fixes some security vulnerabilities GH keeps mailing us about (also visible in `yarn audit` BTW).
It doesn't fix any associated with `less-plugin-clean-css`, because there's no newer version of that package (it seems pretty dead). Nor jQuery, since it might be a PITA to upgrade and we should be removing uses of it anyway.

Some yarn audit fixes

---

root/account/Donation.js
root/account/EmailVerificationStatus.js
root/account/LostPassword.js
root/account/LostPasswordSent.js
root/account/LostUsername.js
root/account/LostUsernameSent.js
root/account/Preferences.js
root/account/PreferencesSaved.js
root/components/UserAccountLayout.js
root/utility/chooseLayoutComponent.js

CatCat caught this one on test - we weren't actually using UserAccountLayout in chooseLayoutComponent, but we were using it for entity/Subscribers, so the user subscriber page broke. In order to use it on cLC, it needs to take "entity" rather than "user", like all other entity layouts, so changed that.

Change user to entity on UserAccountLayout for use with chooseLayoutComponent

---

lib/MusicBrainz/Server/Constants.pm
lib/MusicBrainz/Server/Controller/OAuth2.pm
lib/MusicBrainz/Server/Entity/Application.pm
lib/MusicBrainz/Server/Form/Application.pm
lib/MusicBrainz/Server/Form/Field/OAuthRedirectURI.pm
root/account/applications/Index.js
root/static/scripts/account/components/ApplicationForm.js

Scheme of such URI must be a reverse-DNS string, e.g. `org.example.app`.

MBS-9999: Allow custom scheme for redirect URI

---

root/static/scripts/common/utility/debounce.js
t/selenium.js

I think this will help solve sporadic issues waiting for edit previews in the release editor.
The debounce change is to make sure edit previews start generating immediately (meaning a request will initiate before the next command starts, and we'll wait for it). The EnvironmentPlugin for webpack should replace `MUSICBRAINZ_RUNNING_TESTS` with `false` for production builds and eliminate that block as dead code.

Wait for net requests between Selenium commands

---

root/components/relationship-editor.tt
root/static/scripts/common/components/TagEditor.js
root/static/scripts/common/entity.js
root/static/scripts/common/utility/lens.js
root/static/scripts/common/utility/request.js
root/static/scripts/edit/MB/edit.js
root/static/scripts/edit/components/ArtistCreditEditor.js
root/static/scripts/edit/utility/guessFeat.js
root/static/scripts/guess-case/MB/Control/GuessCase.js
root/static/scripts/relationship-editor/common/dialog.js
root/static/scripts/relationship-editor/common/entity.js
root/static/scripts/relationship-editor/common/viewModel.js
root/static/scripts/release-editor/actions.js
root/static/scripts/release-editor/bubbles.js
root/static/scripts/release-editor/dialogs.js
root/static/scripts/release-editor/edits.js
root/static/scripts/release-editor/fields.js
root/static/scripts/release-editor/init.js
root/static/scripts/tests/relationship-editor.js
root/static/scripts/tests/release-editor/dialogs.js
root/static/scripts/tests/release-editor/trackParser.js

Removing unnecessary uses of lodash. This doesn't help with our bundle sizes yet (we'll have to kill lodash chaining first).
`_.extend` differs in that it enumerates over inherited properties, but there was no case where we needed or wanted that.
Note: We already have an `Object.assign` polyfill for IE.

Replace _.assign with Object.assign/spreads

---

root/static/scripts/edit/ExampleRelationships.js
root/static/scripts/timeline.js

Method chaining is bad because it prevents use from being able to remove unused lodash code.
This commit doesn't remove implicit chaining using `_()`, which is much more common.

Remove explicit calls to _.chain

---

.eslintrc.yaml

https://eslint.org/docs/rules/no-unneeded-ternary
There's no good reason to have (x ? x : 1) when we can have (x || 1). This will just ensure we are reminded of it.

Add no-unneeded-ternary eslint rule

---

lib/MusicBrainz/Server/Data/Release.pm

https://tickets.metabrainz.org/browse/MBS-10075

MBS-10075: Fix to still display releases with no medium when sorting collection by format/no. of tracks

---

root/server/createServer.js

Currently, we only use the `linked_entities` sent when the request begins. If there's a call to `React.embed` later which produces new ones, we had completely ignored them. The change here is to merge them into the existing ones.

Merge new linked_entities during the request

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Allow % for CD Baby both artist and release. Update related tests.
Real example: https://store.cdbaby.com/artist/ka%c3%afssa

MBS-10084: Allow percent encoding in CD Baby URLs

---

root/layout/components/BottomMenu.js
t/selenium.js
t/selenium/MBS-9669.html

Locale code is displayed in BCP 47 format in URL, cookie, and UI language selector menu, but it is used in POSIX format internally for Jed and PO files. The bug was to compare current language code in internal POSIX format with available UI languages code in BCP 47 format.
This patch calls component `LanguageMenu` with current language in BCP 47 format.

MBS-9669: Fix UI language selector menu header for locale with country code

---

lib/MusicBrainz/Server/Controller/WS/2/Release.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/BrowseRelease.pm

https://tickets.metabrainz.org/browse/MBS-6895
There seems to be no good reason why these are not allowed for browse while they're allowed for lookup.

MBS-6895: Enable tags and genres for release browse

---

INSTALL.md

It is mostly about not worrying about `MB_SERVER_ROOT` anymore since the default value should do.

Update install documentation

---

lib/MusicBrainz/Server/Data/WikiDoc.pm

https://tickets.metabrainz.org/browse/MBS-10090
This avoids a situation where a '%3F' in the docpage URL is taken by MediaWiki to be an actual ? and breaks the "?action=render&redirect=no" part of the page, causing it to return the entire html content of the wiki page inc. headers and UI sections.
(in case you're wondering, yes, this is what came out of me being like "oh I wonder what will happen if I add a question mark to the URL")

MBS-10090: Escape id before passing to MediaWiki

---

lib/MusicBrainz/Server/Data/Relationship.pm

https://tickets.metabrainz.org/browse/MBS-10088
The current query used "${source_id}_cardinality = 0" if $use_cardinality; to exclude relationships affected by cardinality.
That works great, except on l_x_x relationships where *both* sides of the relationship need to be checked for cardinality. In that case, only entity1 (the final value of $source_id) was being checked, meaning if entity_1 had cardinality=1 it would always return no results, even if the entity we were looking for was entity0 with cardinality=0.
This changes it so that the condition strings are actually fully built inside the $type checks, which ensures we'll get "WHERE (entity0 IN (?) AND entity0_cardinality = 0) OR (entity1 IN (?) AND entity1_cardinality = 0)" rather than "WHERE (entity0 IN (?) OR entity1 IN (?)) AND …

MBS-10088: Correctly check for cardinality on l_x_x rels

---

root/cdtoc/attach_list.tt
root/cdtoc/list.tt
root/components/releases-list.tt
root/edit/details/merge_releases.tt
root/edit/list.tt
root/otherlookup/results-release.tt
root/release/edit/tracklist.tt
root/release/merge.tt
root/release_group/index.tt
root/search/components/ReleaseResults.js
root/static/scripts/edit/components/ArtistCreditBubble.js
root/static/scripts/edit/components/ArtistCreditNameEditor.js
root/static/styles/layout.less

https://tickets.metabrainz.org/browse/MBS-10094
IMO it makes no sense to do it like that only on one kind of release list - since I feel it makes sense, I'm making the change in all lists of releases (of which we clearly have way too many).
If you'd rather have a class "barcode-row" or something and then the text-align on CSS, that works for me too.

MBS-10094: Right-align barcodes in lists

---

lib/MusicBrainz/Server/Edit/Relationship/Delete.pm

Older 'Remove Relationship' edits seem to only have root_id/root_name for attributes, which we can use for the id/name and assume the type is its own root.
Another issue is that attribute gids aren't present in these edits. The LinkAttributesArray type allows these to be optional, but not undef.

MBS-9413: Fix for old 'remove relationship' edits

---

root/static/scripts/edit/externalLinks.js

https://tickets.metabrainz.org/browse/MBS-10099
It also includes a ton of eslint fixes on the file, moving the amount of failures from like a hundred to 11 warnings. The rest would require a more significant rewrite and/or me understanding refs and callbacks and state stuff which I'm still working on. But it should already be quite an improvement.
Edit: around half the remaining warnings are for react/jsx-no-bind which @mwiencek suggested we might want to stop applying.

MBS-10099: Use backwards link phrase when needed on ExternalLinks (+ eslint fixes)

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Bandsintown URLs can now have a language code for website UI.
(Note: Tested, this was likely not the case with old URL format.)
This patch recognizes such language code and strips it of URLs.

MBS-10103: Strip language code from Bandsintown

---

root/static/scripts/common/components/CritiqueBrainzReview.js

'DBDefs' can't be imported in scripts that run in the browser. It can contain sensitive configuration values, so is specifically excluded from the build by Webpack.
'DBDefs-client' must be used instead, as it's available in the browser and specifically includes only the %CLIENT_DEFS listed in script/dbdefs_to_js.pl.
Resolves https://sentry.metabrainz.org/metabrainz/musicbrainz-server/issues/52114/

Fix DBDefs import in CritiqueBrainzReview

---

root/static/scripts/release-editor/validation.js

There's no reason to use `N_l` here, and it's causing an issue because we pass `checkDigitText` to `expand2text` below (which expects a string as the first argument, not a function).
Resolves https://sentry.metabrainz.org/metabrainz/musicbrainz-server/issues/57619/

Fix broken check digit i18n

---

root/instrument/List.js
root/search/components/InstrumentResults.js
root/static/scripts/common/MB/Control/Autocomplete.js

In most cases we want to read and use this html.
For Autocomplete, the description should just be text, so we just drop the html tags. I've done that with jquery since that file is already using jquery anyway and it seems to be the simplest way, but eventually we might want a better way or our own function.
The autocomplete error is already there in prod. The other two are beta only.

MBS-10112: Support instrument descriptions that contain HTML

---

root/static/scripts/release-editor/init.js

This is a hack, but fixes an issue where the track artist credits would not appear to be updated when the matching release artist credit was changed. It achieves this by setting the component state directly, similar to how we do inside `doneCallback` in bindingHandlers.js.
I don't know if it's related to [MBS-10115](https://tickets.metabrainz.org/browse/MBS-10115) without specific steps to reproduce that.
Also, I saw some talk on IRC about the "Change all artists on this release that match ..." feature not working, but I can't reproduce any issue with that (and don't see any tickets related to it). It was recently fixed with https://github.com/metabrainz/musicbrainz-server/pull/795 so if anyone has more details about how to break it (again), please open a ticket with steps! :)

Fix for updating track ACs with the release AC

---

admin/sql/CreateTables.sql
admin/sql/updates/20190422-mbs-5818-collection-position.sql
admin/sql/updates/schema-change/25.slave.sql
upgrade.json

Add `position` column of `INTEGER` type to every `editor_collection_<entity_type>` table.
It will allow collection owner to manually order collection entries.
Default is still unordered collection, with positions set to `NULL`.

MBS-5818 (SQL): Add integer position column to collection entries

---

script/dbdefs_to_js.pl

https://tickets.metabrainz.org/browse/MBS-10150
https://github.com/metabrainz/musicbrainz-server/pull/1008 made it so the CB component uses DBDefs-client... but we didn't include the CB constant in that file.

MBS-10150: Include CRITIQUEBRAINZ_SERVER in DBDefs-client

---

.circleci/config.yml
bin/rsync-staticbrainz-files
docker/Dockerfile.tests
docker/musicbrainz-website/deploy_static_resources.sh
docker/musicbrainz-website/start_musicbrainz_website.sh
docker/scripts/mbs_constants.sh
docker/scripts/start_template_renderer.sh
docker/templates/macros.m4

It completes the previous pull request https://github.com/metabrainz/musicbrainz-server/pull/915, more particularly the commit https://github.com/metabrainz/musicbrainz-server/pull/915/commits/43ee7e757bcb8246108606c7e73609bfbd54be73, that fixed building docker images but musicbrainz-tests docker image which is used by CircleCI.

Fix CircleCI build

---

entities.json
lib/MusicBrainz/Server/Controller/Genre.pm
lib/MusicBrainz/Server/Data/Genre.pm
lib/MusicBrainz/Server/Data/Statistics.pm
lib/MusicBrainz/Server/Entity/Genre.pm
root/genre/GenreListPage.js
root/genre/List.js
root/server/components.js
root/statistics/Index.js
root/types.js

First step of genres-in-DB, creates Data::Genre and Entity::Genre.
Also: I haven't added a new entity nor data page since I think 2013, so comments on those would be very appreciated.

MBS-9491: Update genre list to use database genres

---

root/components/relationships-table.tt

`rel.target.artist_credit` is empty, for example, if `rel.target` is a work or any other type of entity without an artist credit.
This didn't cause any issue until we changed the artist_credit macro to embed the `ArtistCreditLink` React component, which can't handle its `artistCredit` prop being an empty string.

Only call AC macro if an AC exists (MBS-10182)

---

docker/templates/Dockerfile.test-database.m4

Previous docker image for test-image was based on `postgres:9.5.6` which, in turn, was based on `debian:jessie`.
The recent removal of jessie-updates from mirrors broke sources.list
https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html
Rather than working around by hot-fixing `/etc/apt/sources.list`; this patch updates to `postgres:9.5.16` which is based on `debian:stretch`.
----
P.S. That should fix error at the bottom of https://ci.metabrainz.org/job/MusicBrainz%20Server%20Docker%20Images/274/console

Update postgres base to 9.5.16 (and thus debian to stretch) in test-database docker image

---

root/components/common-macros.tt
root/recording/layout.tt
root/release/layout.tt
root/release_group/layout.tt
root/static/scripts/common/components/ArtistCreditLink.js

Original macro `artist_credit` was producing nothing if `ac.names` was undefined or empty, whereas its React replacement `ArtistCreditLink` expects a property of type `ArtistCreditT` and errors otherwise.
This patch checks artist credit `ac` matches `ArtistCreditT` type before calling `React.embed`.
It depends on PR #1073 (solely to avoid conflict, not a functional dependency).
It partly completes commit 9493fe2f3ab73ae762052990d9672d28656018a4. It is a more general fix for the same issue addressed in PR #1071.

MBS-10184: Only call React component if artist credit has names

---

root/components/common-macros.tt
root/recording/layout.tt
root/release/layout.tt
root/release_group/layout.tt
root/static/scripts/common/components/ArtistCreditLink.js

Template Toolkit macro `artist_credit` has been correctly converted to React with `ArtistCreditLink` component, `plain` option included. But React.embed` call encodes HTML entities, TT macro `artist_credit` has a `plain` text mode option, which results in overencoding.
This patch creates a new TT macro `artist_credit_plain` to replace the 3 lasting template calls to `artist_credit` with `plain` option, and removes `plain` from `ArtistCreditLink` component properties.
Such calls can be replaced with `reduceArtistCredit` JS function calls (which is not a component though) when converting template to React.
It partly reverts commit 9493fe2f3ab73ae762052990d9672d28656018a4.

MBS-10183: Fix double-encoding of artist credit in page title

---

lib/MusicBrainz/Server/Controller/Admin.pm
lib/MusicBrainz/Server/Controller/Root.pm

https://tickets.metabrainz.org/browse/MBS-10095
400 seemed appropriate, since the username being requested is incorrect. 404 would work too but it doesn't seem to accept any sort of extra explanatory message, so it seems less ideal. Of course, we could always add an optional extra message to our 404 pages :)

MBS-10095: Meaningful error for editing nonexisting user

---

flow-typed/npm/redux_v3.x.x.js
package.json
root/static/scripts/edit/utility/linkPhrase.js
yarn.lock

Updates flow-typed/npm/redux_v3.x.x.js to remove the deprecated `$Subtype` utility (though they replaced it with `*` which is also deprecated, though Flow doesn't complain about it, so...).
Fixes an issue where Flow now expects a `$ReadOnlyArray` from `PhraseVarArgs.get`. Not sure which bit in the changelog correlates to that, but perhaps "mixed refined to an array produces a read-only array" now.

Bump Flow to 0.98.1

---

package.json
yarn.lock

This resolves an issue with parsing Flow's inexact object type syntax (`{...}`).

Update babel-eslint to 11.0.0-beta.0

---

lib/MusicBrainz/Server/Data/Artist.pm
lib/MusicBrainz/Server/Data/Editor.pm
lib/MusicBrainz/Server/Data/Label.pm
lib/MusicBrainz/Server/Data/Place.pm
lib/MusicBrainz/Server/Data/Utils.pm

https://tickets.metabrainz.org/browse/MBS-10141
get_area_containment_query only looks at area types:
1 (Country)
2 (Subdivision)
3 (City)
While this might make sense for listing containment while linking to the entity, it's quite confusing to skip levels when loading the contained entities in the different tabs of the Area page.

MBS-10141: Look at all area levels for Area tabs

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

1. Replace songkick.com with www.songkick.com and deny other domains
2. Remove slug, subpath, query, fragment, and deny unclean URLs
* It helps with preventing duplicates (with/without slug)
* Only festivals have mandatory `/id/<edition id>` subpath
* Songkick accepts URLs without slug and auto-add slug to it
Update tests accordingly, and add artist test with unneeded subpath.
Edit: Additionally disallow linking Songkick festivals to places (which was an unexploited bug).

MBS-9762: Standardize Songkick URLs

---

package.json
yarn.lock

Per WhiteSource, "Knockout, before 3.5.0-beta, has an XSS injection point in attr name binding for browser IE7 and older."
I've backported https://github.com/knockout/knockout/commit/86b06aa to our fork via https://github.com/mwiencek/knockout/commit/a09f077.

MBS-10196: backport IE7 XSS fix to knockout

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

[MBS-10108](https://tickets.metabrainz.org/browse/MBS-10108): Allow linking tweets to recordings only
----
Handle Twitter update permalinks such as `https://twitter.com/user/status/123`:
* auto-select “stream music for free” relationship type,
* same cleanup as for linking to Twitter accounts,
* validate linking Twitter updates to recordings only.
See https://blog.twitter.com/en_us/a/2006/twitter-has-permalinks-and-rss-feeds.html

MBS-10108: Allow linking tweets to recordings only

---

root/instrument/InstrumentLayout.js
root/instrument/layout.tt

Restore instrument type name in instrument page title
----
Fix a small regression from https://github.com/metabrainz/musicbrainz-server/pull/869 noticed in https://github.com/metabrainz/musicbrainz-server/pull/1006#pullrequestreview-241396314: During React conversion (commit https://github.com/metabrainz/musicbrainz-server/commit/d2507d6d4ad41106833d8122ceac34e0c9c3587d for [MBS-10005](https://tickets.metabrainz.org/browse/MBS-10005)), instrument type name has been lost from instrument page title, this patch restores it.

Restore instrument type name in instrument page title

---

lib/MusicBrainz/Server/Controller/Role/CORS.pm
lib/MusicBrainz/Server/WebService/Validator.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/SubmitRecording.pm

Resolves MBS-6033, MBS-6072
Thanks to Johannes Dewender for his initial work in https://bitbucket.org/metabrainz/musicbrainz-server/pull-requests/45/mbs-6033-allow-cors-preflights/diff

Answer OPTIONS / CORS preflights in the WS

---

package.json
root/components/FormRowRadio.js
root/static/scripts/common/components/WorkListEntry.js
root/static/scripts/work.js
root/types.js
yarn.lock

The main items from the changelog (https://github.com/facebook/flow/releases) that required fixing were:
* "The statics of function types used to be any but are now typed as an empty object."
* "Fix an issue where Flow would not catch certain errors involving React function components with unannotated props."
* "Destructuring patterns could previously include missing properties if the resulting binding was unused. This is now an error even when unused."

Bump Flow to 0.100.0

---

lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
root/static/scripts/release-editor/edits.js
root/static/scripts/release-editor/fields.js
t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm

Mitigate bug [MBS-9512](https://tickets.metabrainz.org/browse/MBS-9512) _(Changing recording name to empty string should not be allowed)_ by rejecting edits which violate `only_non_empty` and `only_non_empty_sort_name` constraints.

Reject edits with empty name to mitigate MBS-9512

---

lib/MusicBrainz/Server/Entity/URL/SoundCloud.pm

Fix [MBS-10212](https://tickets.metabrainz.org/browse/MBS-10212): SoundCloud URL with trailing slash is not displayed with user name in artist sidebar
----
SoundCloud artist URL ending with a slash `/` was wrongly treated as SoundCloud song URL and displayed with generic 'SoundCloud' instead of artist name.

MBS-10212: Display artist name for SoundCloud URL with trailing slash

---

lib/MusicBrainz/Server/Data/WebService.pm
lib/MusicBrainz/Server/Test/WS.pm
lib/MusicBrainz/Server/WebService/JSONSerializer.pm
lib/MusicBrainz/Server/WebService/XMLSerializer.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/Collection.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseReleases.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupArtist.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupArtist.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupDiscID.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupEvent.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupInstrument.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupSeries.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/SubmitCollection.pm
t/lib/t/MusicBrainz/Server/WebService/Format.pm

Fix [MBS-10133](https://tickets.metabrainz.org/browse/MBS-10133)
----
Collections aren't searched through the search server at all, if https://musicbrainz.org/doc/Development/XML_Web_Service/Version_2/Search is correct. As such, this should just say that the blank query was blank.
Also generalize what is seen as a blank query: given we can't have empty string or whitespaces as names, `""`, `''` or `"    "` should also be rejected as blank queries. *Escaped* quote marks, such as `query=\"`, should be allowed in order to allow searching for fields containing quote marks.

MBS-10133: Clarify "empty query" bad request error

---

root/release/edit/tracklist.tt
root/static/scripts/release-editor/trackParser.js
root/static/styles/release-editor.less

https://tickets.metabrainz.org/browse/MBS-8915
Had to resubmit this since I couldn't push to https://github.com/metabrainz/musicbrainz-server/pull/774 - so it's still mostly @Ge0rg3's work.
Made a few changes as requested on the comments on the previous PR, and a change to move both components of the delimiter to the left column in a way that seems to make more sense to me.
Commit text: 
"This commit allows users to choose a custom delimiter, which can be any regular expression. This also required a change to the CSS to fit on, and a change to the optionCookie function to allow for strings as well as just boolean values."

MBS-8915: Allow editors to choose delimiter in track parser

---

root/static/scripts/release-editor/edits.js

https://tickets.metabrainz.org/browse/MBS-10260
The code already tried to check whether the video attribute had been removed, but for some reason it checked for .video, while externalLinkRelationship stores the info as an attribute instead.

MBS-10260: Fix RE check for video attributes

---

root/recording/edit_form.tt

Amendment to https://github.com/metabrainz/musicbrainz-server/pull/1037 - because this is in an editor page, and we don't want opening the link to mess up a user's changes.

MBS-10139 (fixup): Make the doc link open in a new tab

---

root/components/VotingPeriod.js

https://tickets.metabrainz.org/browse/MBS-2614
While the closing period for voting is exactly 7 days after the edit is entered (or more if extended), ModBot only applies them on the full hour mark (more or less). That means there's a fair amount of edits already past their "closing time", but still open and votable.
The current message "Already closed" suggests that no more votes will be accepted, but that is not the case: any votes entered before ModBot looks at the edit will still be as valid as the older ones. As such, changing it to "About to close" (without a specific time) seems like the easiest way to not have a misleading message anymore.

MBS-2614: Clearer message for edits waiting for ModBot

---

lib/MusicBrainz/Server/Entity/URL/Spotify.pm

See commit message for details.
Additionally localize Spotify URLs sidebar name.

MBS-10250: Distinguish Spotify links sidebar name

---

root/static/scripts/relationship-editor/common/dialog.js

https://tickets.metabrainz.org/browse/MBS-10256
React's renderToStaticMarkup seems to be sanitizing the HTML in a way that means what Knockout actually gets is not directly usable in a HTML binding. So I'm parsing it back into HTML before displaying it.

MBS-10256: Unescape description HTML in rels editor

---

docker/musicbrainz-test-database/create_test_db.sh

Run `postgres` and listen on localhost before trying to create database and setup schema. I think after changes due to https://github.com/docker-library/postgres/pull/440, during internal initialization, postgres only accepts connections over a unix domain socket. Please steer in the right direction if this issue should be handled differently :) (Ticket link: https://tickets.metabrainz.org/browse/MBS-10274)

MBS-10274: Make sure to run postgres to listen on localhost

---

lib/MusicBrainz/Server/Form/CDStub.pm
root/cdstub/edit_form.tt
root/static/styles/forms.less

https://tickets.metabrainz.org/browse/MBS-2905
For some weird reason, we have historically added a null release artist for various artists CD stubs. This changes it so that various artists CD stubs instead get a hardcoded "Various Artists" release artist.

MBS-2905: Make CD Stub submission always include release artist

---

root/edit/details/AddArtist.js
root/static/scripts/common/components/DescriptiveLink.js
root/static/scripts/common/entity.js

https://tickets.metabrainz.org/browse/MBS-10268
Knowing the release group artist(s) is quite useful, so this changes the release group bubble in the release editor to use DescriptiveLink, which shows both title and AC rather than just title as before.

MBS-10268: Use DescriptiveLink for the RG bubble

---

lib/MusicBrainz/Server/Data/Language.pm
lib/MusicBrainz/Server/Data/Work.pm

https://tickets.metabrainz.org/browse/MBS-9976
In the ISWC report (at least) we sometimes get works that have been merged away since, and the work not being defined causes an ISE. This patch fixes that by ensuring writers, artists and language are only loaded for works that are defined.

MBS-9976: Check work is defined before loading stuff

---

lib/MusicBrainz/Server/Data/Work.pm

https://tickets.metabrainz.org/browse/MBS-10287
I originally considered [MBS-4051](https://tickets.metabrainz.org/browse/MBS-4051) already fixed, but @jesus2099 rightly complained that sorting by most recordings means if two artists have a similar number of real recordings of one work, but one has been cleaned up so that the recordings are properly merged while the other has all recordings yet unmerged, the latter will be unfairly listed on top. By LEFT JOINing tracks, we ensure that we are actually comparing at least popularity in the database, rather than just how badly an artist has been cleaned up.

MBS-4051: Sort work artists by tracks, not recordings

---

lib/MusicBrainz/Server/Report/ReleasesWithUnlikelyLanguageScript.pm

https://tickets.metabrainz.org/browse/MBS-5755
All Western languages can also be transliterated into Katakana, and since a combination of Latin and Katakana is possible, [multiple scripts] should be accepted.
Additionally, Japanese is usually written in a specific number of scripts as well, so limiting it to Japanese scripts, Latin (for transliterations) and [multiple scripts].

MBS-5755: Improved unlikely language/script pairs

---

lib/MusicBrainz/Server/EditSearch/Predicate/Voter.pm
root/edit/search_macros.tt
root/static/scripts/common/MB/edit_search.js

https://tickets.metabrainz.org/browse/MBS-2663
As a follow-up to https://github.com/metabrainz/musicbrainz-server/pull/1119 - I just realized that I didn't implement it for editors. Same general idea.

MBS-2663 (II): Search edits by non-subscribed editor

---

root/release/edit/tracklist.tt
root/static/scripts/release-editor/utils.js

https://tickets.metabrainz.org/browse/MBS-10235
The medium format being kept when reusing a medium causes a lot of problems (when editors forget to unset it) yet it rarely is of any use: a tracklist being the same doesn't imply the format will be and in fact it's often the opposite, with the same release having CD, vinyl and digital versions, for example. This drops the format when reusing a medium, so that the user will have to either select a format or select the "I don't know" checkbox for it.

MBS-10235: Drop format when reusing mediums

---

lib/MusicBrainz/Server/Edit/Relationship/RelatedEntities.pm

https://tickets.metabrainz.org/browse/MBS-6087

MBS-6087: Show relationship edits for recordings on release edit list

---

root/release/edit/information.tt
root/release/edit/macros.tt
root/static/scripts/release-editor/fields.js
root/static/scripts/release-editor/validation.js

https://tickets.metabrainz.org/browse/MBS-10262
Users sometimes don't realize that a new release group will be created if they don't select an existing release group when adding a release. This adds a message to let them know, that gets hidden if they select an existing RG.

MBS-10262: Let user know if new RG will be created

---

root/static/scripts/edit/components/ArtistCreditEditor.js
root/static/scripts/edit/components/forms.js

Fix [MBS-10137](https://tickets.metabrainz.org/browse/MBS-10137): Guess feat button doesn't change AC on recording pages
----
The `guessFeat` function expects an entity's `artistCredit` to be an observable, which was previously only true on release pages. This is now made true on the other entity forms.
We also need a way to update the `ArtistCreditEditor` component when the observable changes. This is done by storing the component instance on the table node, and later calling `setState` on it. (Unfortunately, we can't just render `FormRowArtistCredit` again using a different key, because `ArtistCreditEditor` does some extremely bad things with `ArtistCreditBubble` that leave behind stale state. These components should hopefully be rewritten and changed to be fully controlled in the …

MBS-10137: Fix guess feat. on recording pages

---

lib/MusicBrainz/Server/Report/FeaturingRecordings.pm
lib/MusicBrainz/Server/Report/FeaturingReleaseGroups.pm
lib/MusicBrainz/Server/Report/FeaturingReleases.pm
root/report/FeaturingRecordings.js
root/report/FeaturingReleaseGroups.js
root/report/FeaturingReleases.js

https://tickets.metabrainz.org/browse/MBS-3920
This extends the Featuring reports with more options that also mostly mean the artist needs to be fixed: "f/", "featuring", "ft.", "w/" and "duet with". It does not add other similar options (such as "con", "avec", "with") because they seem to cause too many false positives (mostly but not only related to classical music).

MBS-3920: Add more matching to Featuring reports

---

lib/MusicBrainz/Server/Controller/Role/Merge.pm

https://tickets.metabrainz.org/browse/MBS-2250
The code already attempted to do this, but because the merge goes through a redirect (merge_queue -> merge) the referer was /merge itself, and it always redirected the user to the main page.
I don't see a less ugly way to do this than a returnto parameter, but we already use these elsewhere so it should be ok.

MBS-2250: Go back when cancelling merge

---

lib/MusicBrainz/Server/Form/Field/PartialDate.pm
root/artist/edit_form.tt
root/components/forms.tt
root/components/relationship-editor.tt
root/event/edit_form.tt
root/release/edit/information.tt
root/static/scripts/edit/utility/dates.js
root/static/scripts/relationship-editor/common/dialog.js
root/static/scripts/relationship-editor/common/fields.js
root/static/scripts/release-editor/fields.js

https://tickets.metabrainz.org/browse/MBS-4538
Cases where years before 1000 are correct are rare. This requires the user to enter padding zeroes for those cases, which is not too problematic yet avoids all the cases where a too short year is added accidentally (for example because the user thought this was the day field).
After a chat with @mwiencek we decided not to try to implement this also on the Perl side.

MBS-4538: Prevent years with less than 4 digits

---

lib/MusicBrainz/Server/Controller/WS/2/Area.pm
lib/MusicBrainz/Server/Controller/WS/2/Artist.pm
lib/MusicBrainz/Server/Controller/WS/2/Event.pm
lib/MusicBrainz/Server/Controller/WS/2/Label.pm
lib/MusicBrainz/Server/Controller/WS/2/Place.pm
lib/MusicBrainz/Server/Controller/WS/2/Recording.pm
lib/MusicBrainz/Server/Controller/WS/2/Release.pm
lib/MusicBrainz/Server/Controller/WS/2/ReleaseGroup.pm
lib/MusicBrainz/Server/Controller/WS/2/Series.pm
lib/MusicBrainz/Server/Controller/WS/2/URL.pm
lib/MusicBrainz/Server/Controller/WS/2/Work.pm
lib/MusicBrainz/Server/WebService/Validator.pm

https://tickets.metabrainz.org/browse/MBS-10134
Any browse request with an unsupported attribute will be understood as a search request. Since there's no good way of distinguishing those from an actual search request with "query=" (an empty query attribute), we need an error message that fits both options. 
It isn't useful to send either of these to the search service anyway, so we can just give a bad request error before we send them.

MBS-10134: Don't send bad browse queries to the search server

---

lib/MusicBrainz/Server/Controller/Root.pm
root/main/index.js

Almost revert commit ef92e13639e62b4b26c78b865f94a5b6c287f1cf
See ticket and related tickets for details.

MBS-10313: Reenable CAA image on homepage for Chrome

---

lib/MusicBrainz/Server/EditSearch/Predicate/Role/User.pm
lib/MusicBrainz/Server/Entity/Editor.pm
lib/MusicBrainz/Server/Report/LimitedEditors.pm
root/edit/search_macros.tt
root/static/scripts/common/MB/edit_search.js

https://tickets.metabrainz.org/browse/MBS-6791
The query checks for all the conditions of a beginner editor, except whether they have a confirmed email address, since you can't edit without a confirmed email address anyway.
Works great on my sample DB, hope it scales fine to a full DB :)

MBS-6791: Search for edits made by beginners

---

root/components/forms.tt

"Roman" is a demonym and should be uppercased in English.

Uppercase "Roman" in "Roman numerals"

---

root/static/scripts/guess-case/utils.js

https://tickets.metabrainz.org/browse/MBS-10324
This will cause issues with a title like "Fight (Whatever It Takes)" or something like that, but I guess that's not worse than the existing "take", which can also be used in the same way.

MBS-10324: Make "takes" ETI (since "take" is)

---

lib/MusicBrainz/Server/Controller/TagLookup.pm
t/lib/t/MusicBrainz/Server/Controller/TagLookup.pm

https://tickets.metabrainz.org/browse/MBS-10320
There's little reason to nag users in slave servers, test, and other non-core MB installs. The users are either already supporters, just testing for bugs (which is also a way of supporting us), or at the very least know enough to set up their own server, which also should mean they know we'd like them to donate without nagging them.
In many of these servers, there's no way to know if the user has donated or not, so we would risk annoying a user who has already donated by nagging them again locally.

MBS-10320: Only nag user if in prod or beta site

---

root/components/common-macros.tt
root/edit/details/edit_medium.tt
root/static/scripts/common/components/EntityLink.js
t/lib/t/TemplateMacros.pm

https://tickets.metabrainz.org/browse/MBS-4478
When editing a medium and using a new recording, the current tooltip claims that the entity will be created once the edit is entered (both in the preview and... once the edit is entered). This is not really true: it is created once the edit is *applied*. Tooltip changed accordingly.
Additionally, it doesn't really make a difference when a recording in the new column has been removed or is being created, but we do have that information (the former has a recording_id but the latter does not), so I'm changing the code to actually check what is the case.
There's a third issue where the "will be created" message is never replaced by a link to the actual recording (MBS-7814), but that's a much less straightforward fix, so let's start with this.

MBS-4478: Improve messages for edits that create entities

---

lib/MusicBrainz/Server/Controller/Track.pm

https://tickets.metabrainz.org/browse/MBS-975
When we redirect an (old, pre-NGS) track link to a recording link, we should 301, not 303, since this is not a "see other" situation (such as with tracks in release tracklists) but a "this track permanently turned into this recording" situation. 
This was decided in a dev meeting in 2014, but never implemented (see jira comments)

MBS-975: 301 redirect from track/ to recording/

---

admin/nginx/mbserver-rewrites.conf

While the namespace URI doesn't have to point to anything to be valid, it seems sensible to point it to the documentation to give users a quick link to the docs rather than a kinda frustrating 404.
This was apparently also the pre-NGS behaviour.

MBS-4787: Redirect WS namespace to WS docs

---

root/edit/notes.tt

https://tickets.metabrainz.org/browse/MBS-5049
We currently only show some info about edit note syntax when entering an edit, but not when voting on it. The info is equally useful there.
While at it, added a reminder to follow the CoC while voting: if we're going to have text, we might as well remind people to be nice!

MBS-5049: Link to edit note syntax from edit pages

---

root/static/scripts/edit/utility/guessFeat.js
root/static/scripts/tests/guessFeat.js

https://tickets.metabrainz.org/browse/MBS-10291
In Japanese "、" is sometimes used to separate multiple artists in a feat. credit. As such, we should allow splitting collab artists by "、".

MBS-10291: Add "、" as a separator in guessFeat

---

flow-typed/npm/lodash_v4.x.x.js
root/components/FormRowRadio.js
root/components/SelectField.js
root/static/scripts/common/components/Autocomplete2.js
root/static/scripts/common/components/Autocomplete2/actions.js
root/static/scripts/common/components/Autocomplete2/constants.js
root/static/scripts/common/components/Autocomplete2/reducer.js
root/static/scripts/common/components/Autocomplete2/types.js
root/static/scripts/common/hooks/useOutsideClickEffect.js
root/static/scripts/common/i18n.js
root/static/scripts/tests/autocomplete2.html
root/static/scripts/tests/autocomplete2.js
root/static/styles/autocomplete2.less
root/static/styles/widgets.less
root/statistics/StatisticsLayout.js
webpack.tests.config.js

This is a basic implementation that just shows a list of names; the entity-specific formatters which display more details will be converted later.
To test this, run `./script/compile_resources.sh tests` and navigate to http://localhost:5000/static/scripts/tests/autocomplete2.html.
I'd like if we could check that the basic functionality and controls work as we'd like here (I tried to keep them almost identical to the existing autocomplete), and if they do, merge this mostly as-is plus any requested changes. We could then convert the entity formatters in a followup-PR, and soon after open a PR to replace the jQuery UI one with this.

React autocomplete component

---

root/edit/notes.tt

It amends https://github.com/metabrainz/musicbrainz-server/pull/1184 which is currently in beta.

Beta: MBS-10348: Open edit note help links in a new tab

---

lib/MusicBrainz/Server/Edit/Relationship/Edit.pm
lib/MusicBrainz/Server/Edit/Release/Edit.pm
lib/MusicBrainz/Server/Entity/Relationship.pm
lib/MusicBrainz/Server/Plugin/Diff.pm
package.json
root/edit/details/edit_relationship.tt
root/edit/details/edit_relationship_type.tt
root/edit/details/edit_release.tt
root/edit/details/macros.tt
root/server/components.js
root/static/scripts/common/components/EntityLink.js
root/static/scripts/common/i18n/expand2react.js
root/static/scripts/common/utility/clean.js
root/static/scripts/common/utility/displayLinkAttribute.js
root/static/scripts/common/utility/reactTextContent.js
root/static/scripts/edit/components/edit/Diff.js
root/static/scripts/edit/components/edit/DiffSide.js
root/static/scripts/edit/components/edit/FullChangeDiff.js
root/static/scripts/edit/components/edit/RelationshipDiff.js
root/static/scripts/edit/components/edit/ReleaseEventsDiff.js
root/static/scripts/edit/components/edit/WordDiff.js
root/static/scripts/edit/utility/diffArtistCredits.js
root/static/scripts/edit/utility/editDiff.js
root/static/scripts/edit/utility/linkPhrase.js
root/static/scripts/tests/react-macros.js
root/types.js
root/utility/relationshipDateText.js
t/lib/t/MusicBrainz/Server/Controller/WS/js/Release.pm
t/lib/t/TemplateMacros.pm
yarn.lock

https://tickets.metabrainz.org/browse/MBS-10357

MBS-10357: React edit diffs

---

lib/MusicBrainz/Server/Entity/ArtistCredit.pm

Because some edits may create new entity only when applied, rendering open edits page may cause the following warning:
> Use of uninitialized value in numeric eq (==) at lib/MusicBrainz/Server/Entity/ArtistCredit.pm line 45.
This patch should mute this warning when comparing artist credits missing artist id.

Fix: Properly compare Entity::ArtistCredit missing artist_id

---

root/user/collections.tt

https://tickets.metabrainz.org/browse/MBS-10346
For some reason I added a `<p>` around collaborator_number(). It seems wholly unnecessary and makes the table too high, so removing.

MBS-10346: Remove unneeded <p> inside <td>

---

root/components/Aliases/AliasTable.js
root/components/Aliases/AliasTableRow.js
root/components/Aliases/ArtistCreditList.js
root/static/styles/layout.less
root/user/collections.tt

https://tickets.metabrainz.org/browse/MBS-10347
Actions columns are never the main focus of a table, so they should take as little space as they need for "Remove", "Edit", or whatever else goes in them. There's already a min-width of 10em, so they won't look too tiny anyway.

MBS-10347: Make action columns take only needed space

---

lib/MusicBrainz/Server/Controller/Role/Merge.pm

https://tickets.metabrainz.org/browse/MBS-10345
Currently going to /merge with just one entity in the queue loads a useless, semi-broken page. This changes it so that it just doesn't work, either sending the user back (if gone through a button, which can happen if the merge queue changed in another tab in the meantime), or just sending them to the front page if they typed /merge manually.
This also fixes https://tickets.metabrainz.org/browse/MBS-10344 by virtue of just not letting the user navigate there in the first place.

MBS-10345: Redirect away from /merge if not ready to merge

---

root/statistics/Relationships.js

https://tickets.metabrainz.org/browse/MBS-10349
It's not particularly obvious what "Exclusive" vs "Inclusive" mean on the relationship stats. This changes the headers to actually specify what the numbers mean.

MBS-10349: New, more clear headers for rel stats

---

root/static/scripts/release-editor/seeding.js
t/selenium/release-editor/Seeding.html
t/selenium/release-editor/seeds/no_barcode.html

https://tickets.metabrainz.org/browse/MBS-10240
Needs updating the barcode section of https://musicbrainz.org/doc/Development/Release_Editor_Seeding to "The barcode of the release. May be any valid barcode without whitespace. To indicate there is no barcode, seed "none"" if it gets merged.

MBS-10240: Allow seeding "release has no barcode"

---

root/static/scripts/edit/externalLinks.js
t/selenium/External_Links_Editor.html

Do [MBS-10229](https://tickets.metabrainz.org/browse/MBS-10229) block 12 more URL shorteners
----
Throw error message “Please don't use shortened URLs.”

MBS-10229: Block more shortened/“smart” URLs

---

lib/MusicBrainz/Server/Test.pm
lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Place.pm
lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Place.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupPlace.pm

https://tickets.metabrainz.org/browse/MBS-10411
When serializing the JSON for places, we want latitude and longitude to always be outputted as floats. Perl doesn't have explicit "string" or "number" types; the conversion between them is done automatically depending on context in which they're used. Thus adding 0 to these values changes the context, and forces Perl to change its internal representation of the values to numbers. The JSON serializer follows suit.

MBS-10411: Force coordinates as floats in JSON WS

---

lib/MusicBrainz/Server/Data/Statistics.pm

Adjusts the `count.artist.country` and `count.label.country` stat queries to count those entities as part of a descendant area if the descendant is itself a country.
Here's the artist stats before/after:
Before: https://gist.github.com/mwiencek/00b0657ce8d9c377a22a85b1f6e9ea23
After: https://gist.github.com/mwiencek/0cf9efe9d523677110d7c327913dce20

MBS-10369: Count descendant countries in stats

---

lib/MusicBrainz/Server/Report/DuplicateEvents.pm

https://tickets.metabrainz.org/browse/MBS-8967
Same as we do with artists, we should assume that if all the events in a possible duplicate set have disambiguation comments, they are not actually duplicates.

MBS-8967: Events aren't dupes if all have comment

---

lib/MusicBrainz/Server/Controller/Role/Merge.pm

https://tickets.metabrainz.org/browse/MBS-10363
My commit 7ea117feea2df13f0a4478c39fa5f5e55ad6b5db made things better on the /merge page but inadvertently made them worse on the merge helper. This changes it so that it does still try to go to referer if there's no returnto set, so that it will stay in the same page when canceling a merge from the merge helper.

MBS-10363: Go back to referer on merge cancel

---

lib/MusicBrainz/Server/Form/Role/EditNote.pm
lib/MusicBrainz/Server/Validation.pm
root/components/EnterEditNote.js
root/components/forms.tt

https://tickets.metabrainz.org/browse/MBS-9111
Also https://tickets.metabrainz.org/browse/MBS-10373 as an addendum
We keep having issues with people adding edit notes with no content.
This blocks edit notes with only whitespace and (common) punctuation combinations, and asks the user to provide an edit note that will be useful to fellow editors.
It also blocks one-character ASCII notes, but not one-character notes in wider Unicode, since glyph languages (such as Japanese) might have a full meaningful word that is one character long.
People can obviously still enter just "á" or something, but at least it might block some of the bad edit notes while reminding users why a note is important.

MBS-9111: Stricter validation for empty edit notes

---

root/static/scripts/edit/components/edit/RelationshipDiff.js

`DescriptiveLink` accepts a `content` prop to change the link content, not `credit`.
I noticed this by accident in #1224. Since `DescriptiveLinkProps` is an inexact object, Flow didn't care about the extra `credit` prop (`content` is optional).
Random edit ID you can test against: 33386803

Fix relationship edit credit display

---

root/static/scripts/release-editor/dialogs.js

https://tickets.metabrainz.org/browse/MBS-8566
If a CD stub is being imported that has track artists matching the release artist already selected, it's very unlikely that the user actually wants a different artist for the tracks. This assigns the release AC to the tracks if the track artist name matches the reduced artist credit for the release.

MBS-8566: Reuse release AC when importing CD stubs

---

lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
lib/MusicBrainz/Server/Data/Utils.pm
lib/MusicBrainz/Server/Form/Field/Comment.pm
root/release/edit/information.tt

https://tickets.metabrainz.org/browse/MBS-4486
Disambiguation is already presented in parentheses everywhere, but people sometimes add it *in* parentheses,leading to stuff being shown as ((disambiguation)). This drops parentheses if the disambiguation comment both starts and ends with them.

MBS-4486: Remove parentheses around disambiguation

---

root/components/EntityTabs.js
root/release/edit_relationships.tt

https://tickets.metabrainz.org/browse/MBS-5479
This adds an "Edit Relationships" tab to releases by the "Edit" tab, in order to make the relationship editor easier to find for everyone.
Since most users are currently used to click the link on the sidebar and it also makes sense in that context, this leaves it in there as well - we certainly can use as big a chance as possible for people
to add relationships anyway.

MBS-5479: Add an "Edit Relationships" tab

---

root/components/ConfirmLayout.js
root/release/edit/layout.tt

https://tickets.metabrainz.org/browse/MBS-3112
Other menus (e.g. merge menus) have Enter first, Cancel second. This doesn't matter too much for normal clicking but it makes a lot of difference in the tab order (when navigating with the keyboard).
In the release editor, we generally want to submit the edits if we're in the edit note page, and otherwise navigate either forwards or backwards, much more often than we want to cancel the whole thing (which in my experience is easier done by closing the window anyway).

MBS-3112: Switch order of release editor buttons

---

lib/MusicBrainz/Server/Data/Release.pm

https://tickets.metabrainz.org/browse/MBS-4980
https://github.com/metabrainz/musicbrainz-server/pull/29 was originally rejected because it didn't work in PG 8.4. We don't have that problem anymore, and the general idea makes sense, so I just changed it a bit to fit in our current query.

MBS-4980: Use catnos to sort releases in RG page

---

root/recording/RecordingIndex.js

https://tickets.metabrainz.org/browse/MBS-10355
This patch adds a "Track artist" column to recording pages. While in some cases that will be the same as the release and recording artist, IMO it makes sense to always show it for consistency rather than hiding it only when every single track in the page happens to have the same artist as its release or as the recording.

MBS-10355: Display track artist on recording pages

---

lib/MusicBrainz/Server/WebService/XMLSerializer.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupArtist.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRecording.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelationship.pm
t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelease.pm

https://tickets.metabrainz.org/browse/MBS-10370
The JSON WS already outputs direction either way, but the XML one only outputs direction if it's backward. mmd specifies forward is allowed, so this should cause no issues.

MBS-10370: Add "direction: forward" to XML WS rels

---

root/release/edit/layout.tt
root/static/scripts/release-editor/actions.js

https://tickets.metabrainz.org/browse/MBS-2176
This adds a "Finish" button that goes straight to the Edit Note tab, to make it more clear that a user can go to the Edit Note tab and enter the edit from any tab, without having to go through every single one.

MBS-2176: Add "Finish" button to go to last tab

---

lib/MusicBrainz/Server/Data/Medium.pm
root/components/medium.tt
t/selenium/release-editor/The_Downward_Spiral.html

https://tickets.metabrainz.org/browse/MBS-5083
There's currently no good way of telling if the  recording artist is different from the track artist from a release page without actually opening the recording page for each recording.
This patch makes it so that if the track and recording ACs differ, the recording AC is displayed under the track name (since the track artist column, which might seem like a more obvious choice, doesn't appear at all if all track artists match the release artist).
This is particularly useful in two cases:
a) when a user has fixed a track artist but forgotten to fix the recording artist, or vice versa.
b) for classical music, where the recording artist should usually be different from the track artist.

MBS-5083: Display recording artist on release view

---

lib/MusicBrainz/Server/Data/Relationship.pm

With 42ad9a5, we have to set the source attribute explicitly now. `load_entities` was modified to set the target, but not the source.
Fixes [MBS-10418](https://tickets.metabrainz.org/browse/MBS-10418) and possibly other cases where we have a relationship fetched via `get_by_id` which then has `load_entities` invoked on it. (This is likely not many other places, if any. The vast majority of places we load relationships use the form `$c->model('Relationship')->load($source)` for obvious reasons, which does set the source attribute on the loaded relationships correctly.)

Set source attribute in load_entities, if unset

---

lib/MusicBrainz/Server/Data/Search.pm

After having added release packaging id to MMD schema for MBS-8978, and having updated search indexer/server to follow this new schema, this patch updates MusicBrainz Server to handle the new JSON format returned by MB Solr search server to instantiate ReleasePackaging.
It keeps compatibility with former Lucene-based search server.
Since JSON WS 2 lookup/browse requests use 'packaging-id' instead of 'id' subkey to 'packaging' to preserve backward-compatibility, this patch also anticipates further fix to SOLR-121 search server issue.

MBS-10421: Update schema_fixup of ReleasePackaging

---

root/layout/components/TopMenu.js

https://tickets.metabrainz.org/browse/MBS-10420
We have nothing that deals with /edits/all - this only works because the default for /edits/whatever is to ignore the whatever and load /edits (except for /edits/open)

MBS-10420: Remove /all from /edits/all links

---

lib/MusicBrainz/Server/Data/Search.pm

Search server may sometimes return release packaging without any ID associated with.
This patch enables MusicBrainz Server to handle this corner case.

MBS-10423: Handle missing ID of release packaging

---

root/static/scripts/common/components/FingerprintTable.js

https://tickets.metabrainz.org/browse/MBS-10430
This column is wrapping when translations are too long because I forgot to add the "actions" class to it.

MBS-10430: Add "actions" class to fingerprints

---

lib/MusicBrainz/Server/Filters.pm
root/instrument/edit_form.tt
root/release/edit/information.tt
root/static/scripts/area/places-map.js
root/static/scripts/common/i18n/expand2.js
root/static/scripts/common/i18n/expand2html.js
root/static/scripts/common/i18n/expand2react.js
root/static/scripts/tests/i18n/expand2.js
root/taglookup/Nag.js

https://tickets.metabrainz.org/browse/MBS-10356
This replaces all of our `<b>` messages, including the ones not yet ported to JS, since we will eventually need them to be `<strong>` anyway. Ideally we should also fix the translations (which this will break, but can be reused by simply changing `<b>` to `<strong>` there as well). @yvanzo: any suggestions on how to do that? :) 
I added some eslint fixes to files I was touching anyway. I fixed all except no-weak-types, since I'm not sure what's the right fix for that one. We can either merge it as-is, or I can fix those too if you let me know how :)

MBS-10356: Replace <b> with <strong>

---

lib/MusicBrainz/Server/EditSearch/Predicate/RelationshipType.pm

https://tickets.metabrainz.org/browse/MBS-9468
The query currently checks for `(data#>>'{relationship,link_type,id}')::int`.
In the removal examples I checked, the type is loaded and we need `(data#>>'{relationship,link,type,id}')::int` (comma instead of underscore) instead.
Since I'm not 100% sure whether the previous check actually matches something too, not removing it at the moment (if you're confident it should be removed, let me know).

MBS-9468: Missing check for remove rel edits in search

---

lib/MusicBrainz/Server/Data/ArtistCredit.pm

By having both  artist.edits_pending and ac.edits_pending, and processing them not very carefully later, this query was causing ac.edits_pending to be used for both the AC and the artist itself, giving the wrong result everywhere ArtistCredit::get_by_ids is used.

MBS-10408: Stop AC edits_pending overwriting artist one

---

lib/MusicBrainz/Server/Controller/Role/Delete.pm
lib/MusicBrainz/Server/Data/Area.pm
root/area/delete.tt

https://tickets.metabrainz.org/browse/MBS-10432
https://tickets.metabrainz.org/browse/MBS-10433
https://tickets.metabrainz.org/browse/MBS-10437
I chose to add a new check for MBS-10433 because I wanted a different error text for that case.

MBS-10432 / MBS-10433 / MBS-10437: Block adding removal edits for areas that shouldn't be removed

---

root/edit/notes.tt
root/static/styles/common.less
root/static/styles/edit.less
root/static/styles/forms.less
root/static/styles/help.less
root/static/styles/layout.less

https://tickets.metabrainz.org/browse/MBS-10361
Users will want to tab directly to the submit button on edit pages, which the current position of the edit note help prevents (at least in Chrome). This moves it above the note field, but makes it .small to ensure the user doesn't confuse it with an existing edit note.

MBS-10361: Move edit note help for better tabbing

---

lib/MusicBrainz/Server/Controller/Vote.pm
root/layout/components/BottomMenu.js
root/server/components.js
root/vote/VotingIndex.js
t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm

https://tickets.metabrainz.org/browse/MBS-10299
This currently includes three sets of links: one for destructive edits, one for unreviewed / controversial edits, and one for edits by beginners.
Once [MBS-7912](https://tickets.metabrainz.org/browse/MBS-7912) is available, it should be possible to also add a filter for these (when relevant, at least) to let the user see edits related to their suscriptions only.

MBS-10299: Add page with suggested edit searches

---

lib/MusicBrainz/Server.pm

https://tickets.metabrainz.org/browse/MBS-10467
How did this work before????

MBS-10467: whitelist new_edit_notes_mtime stash key

---

.eslintignore

root/static/scripts/tests/typeInfo.js is usually an empty file, unless tests have been generated. This makes eslint error on it all the time.

Add typeInfo.js to eslintignore

---

root/components/common-macros.tt
root/release/merge.tt

https://tickets.metabrainz.org/browse/MBS-4299
When merging releases and recordings, if the recording artists differ, the user is shown the recordings with different artists, so that they can make sure the merge seems correct. This does not show disambiguations, which can lead to a confusing situation where a user is told "these recordings have different artists" but the only info shown is "Foo by Bar" for both recordings.
This changes the display to use the list we already use for edit medium edits, where every artist in an AC is shown separately under the line if they have a disambiguation.

MBS-4299: Show expanded AC in merge release warning

---

.eslintrc.yaml

These are a bunch of rules that got added to eslint:recommended with eslint 6, plus enforceForClassMembers which is newly added.

New eslint rules (eslint 6 recommended)

---

lib/MusicBrainz/Server/Report/ReleasesWithDownloadRelationships.pm

https://tickets.metabrainz.org/browse/MBS-7097
The old query had one line for each non-digital medium, and one line for each download relationship. We only need one line per release, so the two conditions are moved to subqueries. We check that at least one medium is non-digital, since if the whole thing isn't digital then it follows you can't just download the whole thing.

MBS-7097: Avoid listing releases multiple times

---

lib/MusicBrainz/Server/EditSearch/Query.pm
root/edit/search_macros.tt
root/static/styles/layout.less

https://tickets.metabrainz.org/browse/MBS-10471
Also adding an option for date applying.
For the closing date filter, filtering specifically for edits with a close_time set.  For the applying date filter, filtering specifically for open edits.

MBS-10471: Add option to view edits by date closed

---

lib/MusicBrainz/Server/Form/Annotation.pm

https://tickets.metabrainz.org/browse/MBS-4091
From annotation formatting:
Lists: tab or 4 spaces and:
* bullets or 1., a., A., i., I. numbered items (rendered with 1.)
We are trimming all whitespace at the start and end of the annotation though (FormHandler's default), meaning if the annotation starts with a list the formatting for the first element will be broken. This overrides the default trim method with one that will leave one tab or four spaces if there's that or more than that at the start of the annotation.

MBS-4091: Avoid breaking lists while trimming annotations

---

root/release/edit/tracklist.tt
root/static/scripts/release-editor/fields.js
root/static/styles/layout.less

https://tickets.metabrainz.org/browse/MBS-4776
We have a warning for Various Artists used as a track artist, but people keep wrongly selecting it. This adds a checkbox so that they have to explicitly confirm they want to use VA, which hopefully will make them think twice about it (we can't disallow it completely since it *is* correct in some rare cases).

MBS-4776: Require confirmation for VA track artist

---

root/user/UserProfile.js

https://tickets.metabrainz.org/browse/MBS-10488
When converting to React, I apparently changed these to use user name instead of ID by mistake, and we missed it on review.
https://tickets.metabrainz.org/browse/MBS-10485
Also removing the useless /all in /edits/all link.

MBS-10488: Fix profile subscription links

---

lib/MusicBrainz/Server/Controller/Discourse.pm

https://tickets.metabrainz.org/browse/MBS-10495
Discourse’s SSO API has changed to use HTTP headers for authentication instead of URL parameters.
**Note:** This has not been tested in any way, shape, or form.
See:
* https://meta.discourse.org/t/discourse-api-documentation/22706
* https://docs.discourse.org/

MBS-10495: Update Discourse API authentication method

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

https://tickets.metabrainz.org/browse/MBS-10468
Merch links are sometimes used to sell music releases, with or without other merch, such as https://non-serviam-records.bandcamp.com/merch/the-howling-void-megaliths-of-the-abyss-digipak
As such, we should avoid breaking those links by cleaning them up into the main Bandcamp page URL.

MBS-10468: Stop breaking Bandcamp merch links

---

.eslintrc.yaml

The flow/require-indexer-name rule seems like it would be really nice
to help document what our flow object indexers actually stand for.
See "An indexer can be optionally named, for documentation purposes"
in https://flow.org/en/docs/types/objects/ 
https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-require-indexer-name

Adding flow/require-indexer-name to eslintrc

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Prior to this patch, 45cat and 45worlds record URLs were wrongly mapped to MusicBrainz releases. But 45xxx records are identified with catalog number, thus grouping some releases together. This patch maps 45xxx records to MusicBrainz release groups instead.

MBS-10502: Map 45cat/45worlds records with MB RGs

---

root/static/scripts/release-editor/utils.js

https://tickets.metabrainz.org/browse/MBS-10422
The recording search in the release editor takes ws/2 data and turns it into ws/js. This makes it so that the ws/2 formatted ISRCs also get converted to the ws/js format, so that we can actually display them in autocomplete.

MBS-10422: Add ISRCs to release editor recording search

---

root/static/scripts/common/components/TagEditor.js
root/static/scripts/edit/check-duplicates.js
root/static/scripts/edit/components/ArtistCreditEditor.js
root/static/scripts/edit/components/ArtistCreditNameEditor.js
root/static/scripts/edit/components/PossibleDuplicates.js
root/static/scripts/edit/components/RemoveButton.js
root/static/scripts/edit/externalLinks.js
root/static/scripts/tests/autocomplete2.js

*Submitted as part of the Google Code-in (GCI) competition*
The eslint rule **react/jsx-handler-names** requires that prop methods which handle events are prefixed so that their purpose is clear (that is, it imposes a simple naming convention on event handlers appearing in JSX). [Specifically](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-handler-names.md), their names must start with "handle" (or in some cases, "on").
This pull request does this in a few different ways:
- In some cases, such as where the event handler is `console.log`, eslint is simply disabled for that line because the code is in its most readable and understandable form
- Often, a callback is simply renamed from `x` to `handlerX`
- In some cases, the callback is renamed to something vastly …

Eliminate warnings caused by eslint rule react/jsx-handler-names

---

root/static/scripts/edit/forms.js
root/static/scripts/relationship-editor/common/dialog.js
root/static/scripts/relationship-editor/common/fields.js
root/static/scripts/relationship-editor/common/multiselect.js
root/static/scripts/relationship-editor/common/viewModel.js
root/static/scripts/relationship-editor/generic.js
root/static/scripts/release-editor/actions.js
root/static/scripts/release-editor/edits.js
root/static/scripts/timeline.js

*Submitted as part of the Google Code-in (GCI) competition*
This pull request aims to make JS files in `/root` directory follows [ESLint](https://eslint.org/) rule [no-cond-assign](https://eslint.org/docs/rules/no-cond-assign). 
**Description:** 
If the assignment is intentional then wrap it with parentheses to signals readers that assigning a new value to the variable (using =) was intended, rather than it being an equality comparison (which should use == or ===) that was wrongly written.
For example: 
`while(foo = bar) // Intentional assignment` 
becomes 
`while((foo = bar)) // Wrap it with parentheses`.

Fix JS to follow the no-cond-assign eslint rule

---

lib/MusicBrainz/Server/Controller/Instrument.pm
lib/MusicBrainz/Server/Data/Recording.pm
lib/MusicBrainz/Server/Data/Release.pm
root/components/InstrumentRelTypes.js
root/components/list/RecordingList.js
root/components/list/ReleaseList.js
root/instrument/recordings.tt
root/instrument/releases.tt
root/types.js

https://tickets.metabrainz.org/browse/MBS-10248
Sometimes it can be useful to distinguish whether an artist played an instrument in a recording, or programmed it, or arranged it.
This changes the credit column to a roles column, with the credit also shown when it exists.

MBS-10248: Show relationship types in instrument lists

---

root/layout/components/Head.js
root/layout/components/sidebar/ReleaseSidebar.js
root/static/scripts/edit/ExampleRelationships.js
root/static/scripts/edit/MB/CoverArt.js
root/static/scripts/guess-case/MB/GuessCase/Handler/Base.js
root/static/scripts/guess-case/MB/GuessCase/Output.js

*Submitted as part of the Google Code In competition*
This pull request makes stylistic changes only. Where there is a negated condition, like the one below:
```javascript
!boolExpr ? "a" : "b"
```
it is rewritten to not be negated:
```javascript
boolExpr ? "b" : "a"
```
This is to comply with the eslint rule *no-negated-condition*, to make it easier to reason about branching.
<hr>
This pull request is not intended to change any program behaviour, so all I did was negate any conditionals.

Fix issues relating to eslint rule no-negated-condition

---

root/edit/search_macros.tt
root/static/styles/forms.less

https://tickets.metabrainz.org/browse/MBS-10493
Some edit search multiple selects have *lots* of options, yet their default size is very, very small and they can't be resized.
This makes it so the largest selects (edit type, relationship type, release language and release country) start at size 15 and can be vertically resized, while two smaller selects that still were too big for the default size (edit status and vote type) get a size matching their number of entries to avoid pointless scrolling.

MBS-10493: Better sizing for edit search selects

---

root/components/PaginatedResults.js
root/static/scripts/common/MB/Control/Autocomplete.js
root/static/scripts/edit/ExampleRelationships.js
root/static/scripts/edit/MB/CoverArt.js
root/static/scripts/edit/components/PossibleDuplicates.js
root/static/scripts/edit/forms.js
root/static/scripts/release-editor/recordingAssociation.js
root/static/scripts/release-editor/trackParser.js
root/static/scripts/timeline.js

*Submitted as part of the Google Code-in (GCI) competition*
This pull request aims to make js files in `/root` directory follows [ESLint](https://eslint.org/) rule [function-paren-newline](https://eslint.org/docs/rules/function-paren-newline) (with 'consistent' option).  
**Description** 
This rule enforces consistent line breaks inside parentheses of function parameters or arguments.
For example: 
```
foo(
bar,
baz);
```
becomes 
```
foo(
bar,
baz
);
```

REFACTOR: Make line breaks inside parentheses more consistent

---

lib/MusicBrainz/Server/Entity/EditNote.pm

This was broken in d2f9ced19a20a45e25b5a7e5beb0b7fdb4b726a4 due to all ModBot notes no longer being passed to `format_editnote`. (We don't need to do that if the note is actually localized, because it should be using our translated string syntax to link/format things in that case.)

MBS-10511: Regression: Modbot edit references are no longer linkified

---

root/static/scripts/common/MB/Control/Autocomplete.js
root/static/scripts/common/MB/release.js
root/static/scripts/edit/MB/Control/Bubble.js
root/static/scripts/edit/MB/edit.js
root/static/scripts/edit/URLCleanup.js
root/static/scripts/edit/confirmNavigationFallback.js
root/static/scripts/edit/utility/guessFeat.js
root/static/scripts/guess-case/MB/GuessCase/Handler/Artist.js
root/static/scripts/relationship-editor/common/dialog.js
root/static/scripts/relationship-editor/common/entity.js
root/static/scripts/relationship-editor/common/fields.js
root/static/scripts/relationship-editor/common/viewModel.js
root/static/scripts/relationship-editor/release.js
root/static/scripts/release-editor/bubbles.js
root/static/scripts/release-editor/dialogs.js
root/static/scripts/release-editor/fields.js
root/static/scripts/release-editor/init.js
root/static/scripts/release-editor/recordingAssociation.js
root/static/scripts/release-editor/trackParser.js

The eslint rule [consistent-return](https://eslint.org/docs/rules/consistent-return) asks that all functions should either:
- Always return a value explicitly (using `return value;` and even `return undefined;`) or
- Never return a value explicitly (using only `return;` or simply by omission)
This means that a function which sometimes returns a value and sometimes doesn't (e.g. it depends on an `if` statement) will be in violation of this rule.
<hr>
I would say that it is possible to categorise when a rewrite in a function occurred as follows:
- *Event listener*: Boolean return value decides whether the default action should be taken by the browser. **Solution: explicitly return the 'default' Boolean)**
- *Undefined indicates that the result should be discarded*. This would often occur in …

Code style: eslint consistent-return (2)

---

lib/MusicBrainz/Server/Controller/WS/js.pm

c4f6823e4465fb7dff9a631250d19079a4b32238 changed the release editor to no longer treat format as a string, but the `tracklist_results` subroutine in WS::js wasn't changed to match the corresponding TO_JSON changes.

MBS-10521: Fix format in /ws/js/medium search

---

root/account/change_password.tt

https://tickets.metabrainz.org/browse/MBS-10524
The issue is ultimately that `UserAccountTabs` requires a user to function. It doesn't make sense to use user/profile/layout.tt at all without a user, but it "worked" until the React conversion because TT allows magic behavior.
This patch uses the normal layout if the user isn't logged in.

MBS-10524: /account/change-password is broken unless logged in

---

cpanfile
lib/MusicBrainz/Server/Data/Role/EntityCache.pm
t/lib/t/MusicBrainz/Server/Data/CoreEntityCache.pm

This limits the number of cache locks we have open per entity type per transaction by mapping entity IDs to locks IDs with `% 50`.
This may increase contention, but cache deletions are relatively infrequent compared to reads. If desired we could add some logging in cases where it waits longer than 10ms or so for a lock.

MBS-10497: Limit the number of cache locks

---

lib/MusicBrainz/Script/SubscriptionEmails.pm
lib/MusicBrainz/Server/Controller/Account.pm
lib/MusicBrainz/Server/Controller/User.pm
lib/MusicBrainz/Server/Controller/WS/2/Recording.pm
lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
root/account/sso/DiscourseUnconfirmedEmailAddress.js
root/user/UserProfile.js
t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm

Jira Ticket: MBS-8699
Changed all instances of the usage of confirm in the context of emails to verify/verified/verification

Fixed: E-mail verification is sometimes called confirmation

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

`quebecinfomusique.com` (additionally to `qim.com`)
- protocol to `http` (as `https` is not available)
- domain name to `www.qim.com` (which has the best SEO)
- `artistes/` subpage to `biography` (which exists for every entry)
- QIM "artistes" with MB artist
- QIM "albums" with MB release group
- QIM "oeuvres" with MB work

MBS-10292: Normalize and validate QIM URLs

---

docker/musicbrainz-tests/chrome.service
t/selenium.js
t/selenium/release-editor/Duplicate_Selection.html

We're starting to get page crashes in our Selenium tests since the Solr/sir integration was merged. This might have to do with /dev/shm being too small in the CircleCI container.

Run chrome with disable-dev-shm-usage in tests

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Since musik-sammler changed the URL format for releases a tiny bit, I have updated the cleanup URL along with the suggested changes by chaban. See https://tickets.metabrainz.org/browse/MBS-10309

MBS-10309: Updated URL cleanup for musik-sammler

---

root/utility/formatUserDate.js

https://tickets.metabrainz.org/browse/MBS-10492
Intl.DateTimeFormat resolves "2-digit" to "numeric" if minute or second are alone in the options object.
This works around it by adding hour/minute.
https://bugzilla.mozilla.org/show_bug.cgi?id=1284868

MBS-10492: Display leading 0 in minute and second

---

lib/MusicBrainz/Server/Controller/Search.pm
lib/MusicBrainz/Server/Data/Search.pm
root/search/components/TagResults.js

Goes after https://github.com/metabrainz/musicbrainz-server/pull/1062
It makes sense to show genres for tags - it will make even more sense once we have aliases and the genre associated to a tag can have a different name than the tag itself.

MBS-9491: List genre on tag search results

---

lib/MusicBrainz/Server/Data/Artist.pm
lib/MusicBrainz/Server/Data/Label.pm
lib/MusicBrainz/Server/Data/Series.pm
lib/MusicBrainz/Server/Data/Subscription.pm
lib/MusicBrainz/Server/Edit/Role/MergeSubscription.pm

MBS-10522
This was supposed to happen already, but merge_entities was running after the around do_merge code deleted the subscriptions, so there was nothing left for merge_entities to move. This moves it to run as part of the around do_merge section of MergeSubscription, which seems sensible given it's as much part of the subscription merge as the deletion is.

Fix MBS-10522: Save subscriptions to merge destination

---

lib/MusicBrainz/Server/Form/User/Report.pm

MBS-10553
We currently always translate the report reasons whenever we use them.
This makes a lot of sense when we're doing it to show them to the user (who will want them on their language), but not so much when sending them with the report email (which goes to the MeB team who might not speak said language). As such, this moves the moment the reasons are translated from the %REASONS hash (which is used in both cases) to the specific options_reason map for the form creation.

Fix MBS-10553: Translate report reason only if needed

---

INSTALL.md

PostgreSQL changes:
- added a missing ';' to the ALTER USER
- note that for PostgreSQL 10 and later, UNENCRYPTED must be left
off the ALTER USER
- explicitly note that the database must be dropped to restart an
interrupted or failed run of InitDb --createdb
Translations:
- adjusted setup instructions, linking to .transifexrc docs
- noted that simply creating an account is not enough to be able
to download the translations

Updated the installation guide.

---

lib/MusicBrainz/Server/Form/Admin/Attributes.pm
root/admin/attributes/form.tt

MBS-10565
The entity type for the items in a series (or collection) is expected to be item_entity_type. This renames the field in the form so that it actually sees and submits the item entity type correctly.

MBS-10565: Fix item_entity_type field name

---

lib/DBDefs.pm.sample
lib/DBDefs/Default.pm
root/area/AreaPlaces.js
root/place/PlaceMap.js

- Document `MAPBOX_ACCESS_TOKEN` in sample config
- Prevent sending unauthorized requests to the maps service
- Display explanatory message instead of incomplete map

MBS-10531: Document and fix handling of maps service access token

---

root/release/ReleaseHeader.js

This should only be used if a different entity name (credited name) is being used.

MBS-10536: Remove span.name-variation around "see all" releases link

---

entities.json
lib/MusicBrainz/Server/Form/Admin/Attributes.pm

MBS-10567
When creating a new series type, you can currently select any entity type for the items that is allowed for collections. The list of types allowed for series is different though, meaning that the system will allow you to try to create an artist series type, then fail at the database level when it hits a constraint. This makes it so that only entity types allowed by the allowed_series_entity_type constraint are shown as options for new series types, mirroring the way it's done for collections.
On top of https://github.com/metabrainz/musicbrainz-server/pull/1350

Fix MBS-10567: Limit series types as per DB constraint

---

root/static/scripts/common/MB/Control/Autocomplete.js
root/static/scripts/common/components/Autocomplete.js
root/static/scripts/common/components/TagEditor.js
root/static/scripts/common/utility/getCookie.js

In accordance with ESLint, the files in musicbrainz-server have been edited to have no objects use non-prototype-builtins.
**Disambiguation:**
Instead of objects using the `.hasOwnProperty` method in the following way:
`object.hasOwnProperty('name')`
they would do it in the following way instead:
`Object.prototype.hasOwnProperty.call(object, 'name')`
where `object` is the object that the method is being called on.
**Command:** `./script/check_eslint_rule 'no-prototype-builtins: warn' root/`

Fixed files so that objects do not use non-prototype-builtins, going along with the ESLint guidelines.

---

lib/MusicBrainz/Server/Email.pm
lib/MusicBrainz/Server/Translation.pm
t/lib/t/MusicBrainz/Server/Email.pm

ModBot's notes can be localized since d2f9ced using a special syntax. Where it was used, the notes weren't being mailed correctly, instead exposing the internal syntax to the recipient.
This passes the ModBot note text through `Entity::EditNote::localize` before sending out the email. `editor_id` and `text` are the only attributes needed to run that method.
The message is sent in English (via a new `run_without_translations` method in `Server::Translation`) because we don't know the language of the recipient. This is the behavior it's always had, of course.

MBS-10571: Fix "localized" ModBot email display

---

babel.config.js
root/account/EditProfile.js
root/area/create.tt
root/artist/create.tt
root/components/UserAccountLayout.js
root/entity/edit.tt
root/event/create.tt
root/forms/dialog.tt
root/instrument/create.tt
root/label/create.tt
root/layout.tt
root/layout/components/Head.js
root/place/create.tt
root/recording/create.tt
root/release/edit/layout.tt
root/release/edit_relationships.tt
root/release/index.tt
root/release_group/ReleaseGroupIndex.js
root/release_group/ReleaseGroupLayout.js
root/release_group/create.tt
root/series/create.tt
root/server/gettext.js
root/static/scripts/common/i18n/wrapGettext.js
root/static/scripts/jed-data.js
root/statistics/StatisticsLayout.js
root/statistics/timeline.tt
root/work/create.tt
webpack.client.config.js

Prior to this patch, we had separate Jed data bundles per language per domain, and any page that used a domain other than mb_server had to specify that so it could be loaded. This was horrible, because we'd have to remember to update these domain lists on every change, and before we did, had to figure out what pages the change affected.
For example, re MBS-10572 an l_countries call was introduced into the ReleaseEvents component, which it turns out is used on a lot of pages that don't have the countries domain loaded.
This patch combines all domain-specific Jed data bundles into a single bundle per language. These new bundles are around 500KB before gzip and loaded on every page if a language is selected. Some unnecessary data will be loaded on some pages now, but on a lot of edit pages …

Fix MBS-10572: Have one Jed bundle per language

---

INSTALL.md
docker/Dockerfile.tests
docker/templates/macros.m4

Anticipate postgresql-musicbrainz-collate's switch to pkg-config at https://github.com/metabrainz/postgresql-musicbrainz-collate/pull/5.
Unicode::ICU::Collator 0.004 already uses pkg-config if available, see https://rt.cpan.org/Public/Bug/Display.html?id=86373

Install pkg-config to probe ICU headers/libraries

---

webpack.client.config.js

This generates source maps (mapped to the original source) in production, to be hosted on StaticBrainz. Sentry can use these to display better stack traces.
For development, I checked the difference in build time between source-map and cheap-source-map, and it was negligible (less than a second or two for me). Didn't check for rebuilds, though.
I don't see any issue with exposing these publicly since it doesn't contain any private data and the code is open source.

Generate source maps in production

---

root/artist/edit_form.tt
root/release/edit/recordings.tt
root/static/scripts/common.js
root/static/scripts/common/MB/Control/SelectAll.js
root/static/scripts/edit/MB/Control/ArtistEdit.js
root/static/scripts/release-editor/init.js

https://tickets.metabrainz.org/browse/MBS-5460
https://tickets.metabrainz.org/browse/MBS-5572
The patch extends the support for shift-click (de)selecting of checkboxes to the release editor recording tab and to the artist credit list on artist/edit.
This has a bunch of eslint fixes included. I didn't fix all of the issues, just some that were annoying me, but I feel that's still better than before. If preferred, I can drop the eslint commits or split them into a separate PR.

MBS-5460/MBS-5572: Add shift-click selecting to more places

---

entities.json
lib/MusicBrainz/Server.pm
lib/MusicBrainz/Server/Controller/Release.pm
lib/MusicBrainz/Server/Data/MediumCDTOC.pm
lib/MusicBrainz/Server/Entity/Release.pm
root/components/EntityTabLink.js
root/components/EntityTabs.js
root/release/discids.tt
root/static/styles/entity.less
root/types.js
t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm

MBS-9477, MBS-10568, MBS-10569
See commit messages for details. Screenshots:

Implement MBS-9477, MBS-10568, MBS-10569: DiscID tab improvements

---

lib/MusicBrainz/Server/Controller/MBID.pm
lib/MusicBrainz/Server/Controller/OtherLookup.pm
root/mbid/NotFound.js
root/server/components.js
t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm

https://tickets.metabrainz.org/browse/MBS-6539
This takes the quite hidden MBID "search" in the /search page and makes it possible to do /mbid/$mbid to redirect to the entity that MBID represents, whatever its type. The /search page option now just forwards to this.

MBS-6539: Allow resolving MBIDs of unknown type

---

root/release/edit/tracklist.tt
root/static/scripts/release-editor/fields.js

MBS-10366
If a medium has a discID attached, the user shouldn't be able to move the pregap track to track 1 by unchecking the "has pregap" checkbox, since the number of "normal" tracks is frozen by the discID. This makes it so the pregap track is removed if there is a discID, but still renumbered otherwise, which is consistent with the way data tracks work.
I also added a toggleable help section with a second commit, that looks like this:

Fix MBS-10366: Remove rather than renumber pregap track if DiscID is present

---

webpack.client.config.js

https://tickets.metabrainz.org/browse/MBS-10579
The code and associated comment here don't make sense to me. The language used in the Jed files should match what's in DBDefs, since that's what gets set in the lang cookie and is what's used to fetch the file.
I'd also be in favor of changing these to es/el (without country codes) in `MB_LANGUAGES` in production and removing the symlinks - they were to work around a bug in `Locale::Util` that's been fixed for years. But in that case we'd still remove this code as unused.

MBS-10579: Unbreak es-es/el-gr translations

---

root/edit/details/AddPlace.js

MBS-10604
An Add Place edit always creates the place immediately, so there is no case where the "This entity will be created by this edit" message applies. As such, we don't even need to check whether it applies on a specific edit, we can just never allow it.

MBS-10604: Remove allowNew from Add Place edit

---

lib/MusicBrainz/Server/Controller/Release.pm
lib/MusicBrainz/Server/Controller/ReleaseEditor.pm
root/release/edit/layout.tt
root/static/scripts/release-editor/init.js
t/lib/t/MusicBrainz/Server/Controller/Release/Aliases.pm
t/lib/t/MusicBrainz/Server/Controller/Release/CoverArt.pm
t/lib/t/MusicBrainz/Server/Controller/Release/Show.pm

The EntityTabs component accesses `entity.may_have_discids` to toggle the Disc IDs tab, but this property requires mediums loaded to be computed on the server. Since loading mediums twice isn't a good use of resources, I've change the release editor controller to directly seed release and medium data to the page (still without tracks) rather than requesting it asynchronously.

MBS-10591: Enable Disc IDs tab in release editor

---

.eslintrc.yaml
root/types.js
root/vars.js
script/check_eslint_rule

This wasn't enabled before because all of these real/fake globals would trigger the error, rendering it useless.
I've also set `no-global-assign: error`, which is good to have. (Our code doesn't have any such issues.)
https://eslint.org/docs/rules/no-undef
https://eslint.org/docs/rules/no-global-assign

Define eslint globals and set no-undef: error

---

lib/MusicBrainz/Server/Controller/Edit.pm
lib/MusicBrainz/Server/Controller/Role/EditListing.pm
root/edit/components/EditSidebar.js
root/edit/components/EditSummary.js
root/edit/edit_header.tt
root/edit/index.tt
root/edit/list.tt
root/edit/search_macros.tt
root/layout/components/BottomMenu.js
root/layout/components/sidebar/CollectionSidebar.js
root/layout/components/sidebar/EditLinks.js
root/robots.txt.production

Submitting a WIP PR for [MBS-9164](https://tickets.metabrainz.org/browse/MBS-9164) per bitmap's request. 
Displaying edits seems to work pretty much fine, although I don't discount the possibility of there being some issue I haven't noticed yet. 
Edit search needs to be restricted properly so that it won't actually submit when the non-logged-in options are selected, and it also needs to be restricted so that if someone constructs a URL (or clicks a link) involving the logged-in-only options when not logged in, it will actually reject it and ask for login. 
I haven't looked at tests yet, so I expect this to break a ton of them.

MBS-9164: Show edit history (but not notes) when not logged in

---

root/components/forms.tt
root/static/styles/release-editor.less

Thanks to @reosarevok, https://musicbrainz.org/doc/Guess_Case is currently up-to-date.
This patch links to this page from guess case options dialog and tracklist guess case form.
It additionally slightly improves display of guess case options and removes unused style.

Link from guess case options to guess case documentation page

---

lib/MusicBrainz/Server/Entity/URL/Maniadb.pm
root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

Convert old format `/artist.asp?p=ID` to `/artist/ID`
Normalize
- protocol to `http` (as `https` is not available)
- domain name to `www.maniadb.com` (which is redirected to)
Drop
- `/index.php` legacy path prefix (rarely used nowadays)
- subpath `/` (rarely used nowadays)
- unneeded query and fragment
Only validate linking
- clean maniadb /artist/ URL with MB artist
- clean maniadb /albums/ URL with MB release group

MBS-10308: Clean up and validate maniadb URLs

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

https://tickets.metabrainz.org/browse/MBS-10209
The current instagram regex means that if a user starts typing the URL by hand, it will add the slash at the end and let the user keep typing, eventually leading to something like instagram.com/s/o/m/e/t/h/i/n/g/
This changes the regex so that it doesn't allow typing anything after the first slash in the user name section. While this means the user can't just type the whole URL in one go, it does avoid it turning into a mess, and the user can just move back to before the slash and finish typing.
It also redirects stories links to the main user page (those can easily be accessed from the user page anyway), and blocks posts (/p/) and post location (/explore/) pages, since those aren't correctly selected as "social network" and there's no …

MBS-10209: Finetune instagram regex

---

lib/MusicBrainz/Server/Edit/Medium/Edit.pm
t/lib/t/MusicBrainz/Server/Edit/Medium/Edit.pm

https://tickets.metabrainz.org/browse/MBS-2436
Once an Edit Medium edit applies, creating new recordings, we should update the edit data so that the new recordings get displayed in the history. This updates the edit data to use the final tracklist while applying the edit.
Same general idea as https://github.com/metabrainz/musicbrainz-server/pull/1124

MBS-2436: Link to created recordings on EditMedium

---

root/server/components.js
root/static/scripts/common.js
root/static/scripts/common/components/WorkArtists.js
root/static/scripts/common/components/WorkListEntry.js
root/static/styles/entity.less
root/utility/tableColumns.js

MBS-10584
For some works (mostly classical) there can be dozens or hundreds of artists listed, making proper navigation of any work list including them pretty much impossible. This makes it so that only the top four artists are shown, with an option to see all, using the same general idea as MBS-10424 (https://github.com/metabrainz/musicbrainz-server/pull/1242).
For an example where this makes a huge difference:

MBS-10584: Collapse work artists if too many

---

lib/MusicBrainz/Server/Edit/Medium/AddDiscID.pm
lib/MusicBrainz/Server/Edit/Medium/MoveDiscID.pm
t/lib/t/MusicBrainz/Server/Edit/Medium/MoveDiscID.pm

https://tickets.metabrainz.org/browse/MBS-4326
DiscID edits seem relevant enough to both the release group the release is in and the artists in release and release group to be displayed in those's edit histories as well.
Remove Disc ID was already being shown in the relevant places: this changes Add and Move to do the same.

MBS-4326: Show DiscID edits in RG and artist history

---

lib/MusicBrainz/Server/Data/Event.pm
lib/MusicBrainz/Server/Data/Search.pm
lib/MusicBrainz/Server/Data/Work.pm
lib/MusicBrainz/Server/Entity/Event.pm
lib/MusicBrainz/Server/Entity/Work.pm
root/static/scripts/common/components/ArtistRoles.js
root/types.js
root/utility/tableColumns.js

https://tickets.metabrainz.org/browse/MBS-10223
This makes it so that if a relationship used in ArtistRoles (work writers or event performers) has a relationship credit for the artist, the credit is also displayed in the ArtistRoles display.
The search results for works don't include credits for work relationships, so in search results the credits will be missing until SOLR-110 is fixed.

MBS-10223: Use relationship credits in ArtistRoles

---

lib/MusicBrainz/Server/Data/Release.pm
root/components/FieldErrors.js
root/components/FormRowSelect.js
root/components/forms.tt
root/release/merge.tt

MBS-10576
This allows passing forms errors containing HTML. We interpret the errors as HTML only when specifically requested to ensure we still escape the appropriate characters otherwise.
For now, this changes only form_row_select since that's the one that already has one error using HTML, but we might want to expand it in the future (if we add links to documentation in error texts, for example).
Even though this isn't yet needed anywhere that uses the React components, I'm adding it there already for parity - we'll need it once we convert release/merge anyway.

Fix MBS-10576: Support errors with HTML

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

iTunes stores are country-specific. When unspecified, the default store is the US one.
Adding country-code `/us` when missing makes it more clear it isn’t global.

MBS-10623: Auto-add US iTunes store country-code

---

root/edit/search_macros.tt

MBS-10608
Fixes regression introduced by my code at https://github.com/metabrainz/musicbrainz-server/commit/e690b6bb1df9b0563ff2202be33b456dbb8494ea#diff-b398f96e41b6461cfb244c7b7679e17bR433

MBS-10608: Restore parameter options for edit note search

---

t/selenium.js

c7d7038e527ba6bdd0699e0ba3a1e878e997b285 broke some of our Selenium tests which expect numeric IDs to not be encoded as strings.

Allow number-string equality in assertEditData

---

root/components/RelationshipTargetLinks.js
root/utility/relationshipDateText.js

The brackets are used when displaying the relationship date text alongside long link phrases, as we do on relationship edit pages, but they don't make sense for the static relationships display, where brackets are always present.

MBS-10611: Remove double brackets from (ended) relationships

---

.dockerignore
.eslintignore
.flowconfig

This patch completes pull request https://github.com/metabrainz/musicbrainz-server/pull/1319 that added `local::lib` files to the ignore list of Git only.

Ignore local::lib files for docker/js tools too

---

root/components/common-macros.tt
root/components/list/RecordingList.js
root/edit/details/merge_recordings.tt
root/recording/RecordingMerge.js
root/static/scripts/common/components/ExpandedArtistCredit.js

https://tickets.metabrainz.org/browse/MBS-9654
When merging recordings, it's pretty useful to be able to see whether, say, the same artist credit name hides a different artist (and the disambiguation comment for the artist).
This makes the merge page and the edit display show expanded artist credits in the artist cell to make these things more visible than just on hover.
This is on top of https://github.com/metabrainz/musicbrainz-server/pull/1162 and should probably be reviewed after it.
Examples:
_**Edit page**_
**_Merge page_**

MBS-9654: Show expanded ACs on recording merges 

---

INSTALL.md
README.md

Since the commit 83ecd3bf42d (in the pull request #1370), the `script/compile_resources.sh` returned:
error selenium-webdriver@4.0.0-alpha.5:
The engine "node" is incompatible with this module.
Expected version ">= 10.15.0".
This requirement seems reasonable enough since Node.js v10 is the oldest still active (soon in maintenance only) LTS: <https://nodejs.org/about/releases>.
----
Notes:
* our [`docker`](https://github.com/metabrainz/musicbrainz-server/tree/v-2020-02-18/docker) containers already has been using Node.js 10.17 for months;
* `musicbrainz-docker` is going to use Node.js 10.19 with merging the pull request <https://github.com/metabrainz/musicbrainz-docker/pull/123> that includes the commit <https://github.com/metabrainz/musicbrainz-docker/pull/123/commits/bbff5cbd9319a71148c17 …

Document newly required version 10.15 of Node.js

---

script/tag.sh

It fixes a regression from <https://github.com/metabrainz/musicbrainz-server/pull/1337>.
----
I also fixed blog post links that were broken for all of 2020 [tags](https://github.com/metabrainz/musicbrainz-server/tags).

Fix blog post link in generated git tag message

---

lib/MusicBrainz/Server/ControllerBase/WS/2.pm
lib/MusicBrainz/Server/WebService/XMLSerializer.pm

Fix 3 noisy warnings that represent over 98% of webservice servers logs for the three last days at least.

Reduce noise in webservice server logs

---

lib/MusicBrainz/Server/Edit/Annotation/Edit.pm

MBS-10594: Fail add annotation edit if entity is gone

---

lib/MusicBrainz/Server/WebService/JSONSerializer.pm

Fix a not serious but noisy warning (in website server logs) that is triggered by ws/js entity autocomplete.
Note: Since `alias_preference` is an ordered list of user preferred languages, it is expected to not necessarily intersects the set of available languages with primary alias for a result/entity.
It is picked from https://github.com/metabrainz/musicbrainz-server/pull/1377

Fix noisy warning about autocomplete: uninitialized value in numeric gt (>)

---

lib/MusicBrainz/Server/Edit/Medium/Edit.pm
lib/MusicBrainz/Server/Entity/MediumCDTOC.pm

Fix two not serious but very noisy warnings (in website server logs) that are often triggered when attaching a CDTOC or editing a tracklist. See commits’ message for details.
These replace the just wrong commits https://github.com/metabrainz/musicbrainz-server/pull/1377/commits/88a904cfbb39eb0f3dee344abf66893f313e9a10 and https://github.com/metabrainz/musicbrainz-server/pull/1377/commits/54139c65fd862fb23dd93427946a0c6f3c93d635 picked from #1377

Fix noisy warnings about medium: uninitialized value in numeric eq/ne

---

lib/MusicBrainz/Server/Edit/Relationship/Edit.pm
t/lib/t/MusicBrainz/Server/Controller/Artist/EditExternalLinks.pm
t/lib/t/MusicBrainz/Server/Controller/Artist/EditRelationships.pm
t/lib/t/MusicBrainz/Server/Controller/RelationshipEditor.pm
t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
t/lib/t/MusicBrainz/Server/Edit/Relationship/Edit.pm

MBS-10659
If one or both entities on the relationship have a credit, we want to still display that credit in the edit relationship edit, even if the edit itself doesn't change the credit (because it is still relevant to know the relationship is under a specific credit). Currently, the edit will display the main artist name at all times except if the credits are changing.

MBS-10659: Always show entity credits in rel edits

---

lib/MusicBrainz/Server/Data/Release.pm

Suffix used to not be loaded on homepage, spamming website logs with this warning:
Use of uninitialized value in concatenation (.) or string at lib/MusicBrainz/Server/Entity/Artwork.pm line 88
This patch mutes this warning for the homepage only by setting an arbitrary value as suffix.
It’s the 3rd commit picked from https://github.com/metabrainz/musicbrainz-server/pull/1377
----
It doesn’t solve similar warnings triggered on cover art edits’ display which are less frequent.

Fix ubernoisy warning about artwork image suffix on homepage

---

lib/MusicBrainz/Server/Data/Release.pm

MBS-10515
This was attempting to nsort_by by two columns, but that doesn't seem to work, and it was sorting only by track position. Changed it to use a usual sort with a manually defined sort function, to ensure it sorts by medium first then track.

MBS-10515: Fix sort of release recordings in merge

---

lib/MusicBrainz/Server/Entity/Editor.pm

Fix a not serious but noisy warning (in website server logs) that is triggered when trying to display gravatar of an editor without email.
Note: Since users are allowed to delete their email (automatically marking them as beginners), it is normal that their email might be missing while their preferences are still here.
Nevertheless, most of these are either inactive or spam (or both).
It is the 2nd commit picked from #1377.

Fix noisy warning about editor’s gravatar: uninitialized value in lc

---

root/components/GroupedTrackRelationships.js

MBS-10661
Recording-work rels are the only ones not currently highlighted if they have pending edits on release pages. This adds the same "mp" class as the other relationships get.

MBS-10661: Highlight recording-work pending edits in release

---

lib/MusicBrainz/Server/Controller/Rating.pm
root/components/RatingStars.js
t/lib/t/MusicBrainz/Server/Controller/Rating.pm

MBS-10671
People are creating email-less accounts to mass-rate their favourite boy band. While that's mostly harmless, it's still stupid, and I can't see any reason why we should allow unverified users to submit ratings.
I haven't even tried to block submissions via the WS, since that doesn't seem very relevant for the kind of stuff we're trying to stop right now, but I guess we should do that too? Putting this up for now to make sure the general idea seems sound.

MBS-10671: Block ratings for unverified users

---

lib/MusicBrainz/Server/ControllerBase/WS/2.pm

Without uniq here, this is loading the language once per each time the work is used in a relationship, leading to languages arrays like ["eng",  "eng", "eng"] and a calculated fallback language "mul".

MBS-9359: Only load language for each work once

---

lib/MusicBrainz/Server/Data/Vote.pm

MBS-9651
When searching for votes or compiling general voting statistics we ignore votes that have been superseded (i.e. we only count the last vote by an editor for each particular edit). This changes the editor profile vote count to also ignore superseded votes.

MBS-9651: Ignore superseded votes for editor stats

---

root/place/edit_form.tt
root/static/scripts/place.js

MBS-10683 / MBS-10684 / MBS-10685
An issue occurs sometimes with Leaflet that moves the marker to the entered coordinates, but then zooms the map on (0, 0). It seems to be a race condition of some kind between panTo and setZoom.
This moves from panTo + setZoom to setView (which allows passing a zoom parameter, obviating the need for a second call to setZoom). panTo actually uses setView internally anyway.
This seems to lead to consistent correct results locally, so hopefully it'll also do the trick in the main servers.

MBS-10683 / MBS-10684 / MBS-10685: Place map fixes

---

lib/MusicBrainz/Server/Data/Editor.pm
lib/MusicBrainz/Server/Form/Utils.pm

MBS-10633
It should be possible to change someone's username to the same username, but with different capitalization. This changes the comparison that checks if the username has changed to allow those
capitalization--only changes, by comparing normalized usernames instead. The registration system doesn't allow two usernames to only differ in capitalization in any case, so this should be perfectly safe.

MBS-10633: Allow changing username capitalization

---

lib/DBDefs.pm.sample
lib/DBDefs/Default.pm
root/static/scripts/common/leaflet.js

The old Studio Classic style for MapBox we use is being discontinued in June 2020. This follows the instructions on their guide (https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/) in order to move to the latest version of the maps.

MBS-10689: Update MapBox API calls

---

root/artist/ArtistMerge.js

This got accidentally removed with 379959b

MBS-10693: Restore FieldErrors for target on artist merges

---

lib/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm
lib/MusicBrainz/Server/Entity/Release.pm
root/edit/details/add_isrcs.tt
root/edit/details/historic/convert_release_to_multiple_artists.tt
root/edit/details/historic/mac_to_sac.tt
root/entity/Details.js
root/recording/RecordingIndex.js
root/release_group/ReleaseGroupIndex.js
root/static/scripts/release-editor/duplicates.js

MBS-10607
We have plenty of "(unknown)" strings, and the thing that is unknown can be one of many. Depending on the thing, though, the translation should vary (for example, a release format is "desconocido" in Spanish but a release itself is "desconocida" - gender variation). This adds context to the different strings to make it possible to translate them separately.

MBS-10607: Add context to (unknown) strings

---

root/static/scripts/common/components/WorkListEntry.js
root/utility/tableColumns.js

We currently show the code plus the main language on hover, but the code is unclear to most users and we do have enough space here to show the whole name.
This moves the code to a data-iso-639-3 attribute, in case people want to be able to access it still.

MBS-10695: Show language names on work lists

---

lib/MusicBrainz/Server/Edit/Work/Create.pm

MBS-10063 (https://github.com/metabrainz/musicbrainz-server/pull/966) fixed this for most edits, but old Create work edits (from the one-language-per-work time) weren't touched. This fixes that. Old Edit work edits are not affected.

MBS-7835: Old Create work edits should display [No lyrics] for zxx

---

lib/MusicBrainz/Server/Report/RecordingTrackDifferentName.pm
lib/MusicBrainz/Server/ReportFactory.pm
root/report/RecordingTrackDifferentName.js
root/report/ReportsIndex.js
root/report/types.js
root/server/components.js

https://tickets.metabrainz.org/browse/MBS-4090
To avoid false positives (which would be quite likely otherwise), only recordings linked to just one track are checked for this report.
The original request also asked for differences in artist credits, but that would make almost all classical recordings false positives, and titles-only will still probably catch most cases that need fixing.

MBS-4090: Report: non-matching recording/track titles

---

root/components/Relationships.js

MBS-10704
We're checking source.relationships here, but that includes relationships not on displayTargets (for example, for works, it includes recording relationships). Changed this to only look at the actual relationships to be displayed.

MBS-10704: Only show Rels header if something to display

---

root/static/scripts/guess-case/utils.js

Most often, "Medley" is the last word of the title. Guess case used to put that word in parenthesis as extra title information. Even though it sometimes is correct, it is more often wrong, e.g. "Detroit Medley".

MBS-10699: Remove "medley" from guess case

---

lib/MusicBrainz/Server/Edit/Historic/MergeRelease.pm

This was doing `name => $_->{name}`, but by that time `$_` is the release ID (a number) rather than the old release itself. Fixed by storing the old release before the second map and just getting the name from there.

MBS-10712: Fix loading old release name if ID is missing

---

flow-typed/npm/react-table_v7.x.x.js
root/components/RemoveFromMergeTableCell.js
root/components/RemoveFromMergeTableHeader.js
root/components/Table.js
root/components/list/RecordingList.js
root/utility/tableColumns.js

On top of https://github.com/metabrainz/musicbrainz-server/pull/1413
MBS-10365
Artist (the only one left) is a bit more annoying since the component is currently being shared between search results and normal lists. We might want to split that one for now, until we can figure out how to easily do search results with react-table.

MBS-10365 (V): Convert entity lists to react-table

---

lib/MusicBrainz/Server/Edit/Medium/AddDiscID.pm

Seems like if an open AddDiscID edit was voted down or cancelled, we had no way to actually remove the discID that was inserted when the edit was opened. This changes it so that rejecting the edit will actually remove the added discID.

MBS-10707: Actually remove discID if add edit is rejected

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

The motivation behind this change is to map MA /albums/ to MB /release/.
Auto-select is extended to invalid Metal Archives URLs (/user/, ...).
Normalize
- protocol to `https` (as `http` is redirected to)
- domain name to `www.metal-archives.com` (which is redirected to)
Drop
- trailing `/` (rarely used nowadays)
- unneeded query `?` and fragment `#`
Only validate linking
- clean MA /bands/ and /band/ URL with MB artist
- clean MA /labels/ URL with MB label
- clean MA /albums/ URL with MB release (and no longer release group)
- clean MA /reviews/ URL with MB release group (as reviews)
Notes:
- MA /band/ URL is allowed, as it is already present in MB DB, and there is no redirect from /bands/ to /band/ on MA website, that is it is already in use and there is no easy conversion path. Dealing …

MBS-10669: Clean and validate Metal Archives URLs

---

lib/MusicBrainz/Server/Data/Artist.pm
lib/MusicBrainz/Server/Data/Place.pm
lib/MusicBrainz/Server/Data/ReleaseGroup.pm
root/collection/CollectionIndex.js
root/components/list/ArtistList.js

We're super inconsistent on what columns we can sort by or not. This makes it so that if an entity can be sorted by a column, others can too.

MBS-10724: Make list sorting options consistent

---

flow-typed/npm/react-table_v7.x.x.js
root/components/Table.js
root/components/list/RecordingList.js
root/components/list/ReleaseGroupList.js
root/components/list/ReleaseList.js
root/utility/tableColumns.js

On top of https://github.com/metabrainz/musicbrainz-server/pull/1435
The lenghtClass for recording merges should only apply to cells, but currently className applies to both cells and headers. This uses the existing headerProps and creates an equivalent cellProps for cell attributes.

MBS-10723: Separate className for cell and header

---

lib/MusicBrainz/Server/Data/Recording.pm

Standalone and video recordings with multiple artist credits to the same artist were shown
multiple times on the artist's page

MBS-10730: Select DISTINCT video/standalone recordings

---

lib/MusicBrainz/Server/Report/NoLanguage.pm
lib/MusicBrainz/Server/Report/NoScript.pm
lib/MusicBrainz/Server/Report/ReleasesWithUnlikelyLanguageScript.pm
root/report/NoLanguage.js
root/report/NoScript.js
root/report/ReleasesWithUnlikelyLanguageScript.js
root/report/components/ReleaseList.js

https://tickets.metabrainz.org/browse/MBS-5641
Mostly follows how it's done on release search results, but I chose to show "-" rather than nothing when language or script are missing, since I feel it makes *what* is missing more understandable.
Arguably could have been done so that the NoScript report only shows language and NoLanguage only script, but by showing both it also serves to show the editor whether some have already been fixed (since the language and script are loaded from the release entry and not from the saved report data).

MBS-5641: Show language/script in relevant reports

---

lib/MusicBrainz/Server/Controller/Tag.pm
lib/MusicBrainz/Server/Data/Tag.pm

This uses a query suggested by Ian McEwen in the comments to [MBS-7465](https://tickets.metabrainz.org/browse/MBS-7465), with some modifications. I've modified his "UNION ALL" suggestion to also limit each individual entity subquery to the top 200 tags for each entity; this reduces the execution time by an additional 1s while still giving reasonably accurate results. (We don't show the exact counts in any case, just use them to size the tag names.)
We also now store the results of the query in Redis for 24 hours, so the tag cloud is effectively updated once per day.

MBS-7465: Update the tag cloud

---

lib/MusicBrainz/Server.pm
lib/MusicBrainz/Server/Entity/Event.pm
root/event/EventIndex.js
root/types.js

* Fix noisy warnings on `/search` and `/ws/js/event` endpoints, see commit message for details.
* Stop exporting `format_setlist` filter to templates, as events are now rendered using React.
It replaces commit https://github.com/metabrainz/musicbrainz-server/pull/1377/commits/4e5b3917c2550159898280cab6bff2a54bbe3864 submitted in #1377

Fix noisy warnings about event’s search: uninitialized value $text in substitution (s///)

---

lib/MusicBrainz/Server/Data/Utils.pm
t/lib/t/MusicBrainz/Server/Data/Utils.pm

https://tickets.metabrainz.org/browse/MBS-9728
The `:print:` char class doesn't include code points reserved for future use, since characters that don't exist aren't printable. But clearly, new emojis are added quite often and they'll always outpace the particular version of Unicode supported by our Perl interpreter.
Instead of stripping non-`:print:` characters, I've tried to construct the desired class of characters to remove explicitly. I didn't strip `\p{Cf}` (format characters) since it does appear we allow LRM/RLM under some circumstances in `remove_direction_marks`, though we may still want to remove zero-width joiners and language tag chars.
Obviously this may allow the entry of some unassigned code points if someone manages to enter them, but I'm not sure we need to worry about …

MBS-9728: Allow new emojis in titles

---

root/static/scripts/timeline.js

Months start at 0 in Javascript Date

MBS-9894: Fix timeline month off by 1

---

root/components/StaticRelationshipsDisplay.js
root/utility/groupRelationships.js

https://tickets.metabrainz.org/browse/MBS-10718
Previously, we only avoided grouping relationships with different link orders if we were viewing it from the "orderable" side. This modifies the code to use the link orders no matter which side we're viewing them from.
However, displaying the link orders as "1. Foo", "2. Bar", etc. doesn't make any sense from the non-orderable side, because the target entities there aren't what's being ordered (the source entity is). So I've changed it to display as "Foo (order 1)", "Bar (order 2)" from that side instead. (Let me know if you have a better idea here.)
A before screenshot can be found in the linked ticket. After:

MBS-10718: Always use link orders for grouping

---

lib/MusicBrainz/Server/Controller/CDTOC.pm
root/cdtoc/attach_list.tt

https://tickets.metabrainz.org/browse/MBS-10688
If the selected medium already has the CDTOC being attached, go back to the filter/listing page and show a readable error message informing the user rather than a cryptic "Bad Request" page.

MBS-10688: Show a human readable error when attaching a dupe CDTOC

---

root/utility/edit.js

"This edit is open and awaiting votes before it can be applied." suggests the edit can't be applied without votes, which is not true. Just "This edit is open for voting" actually describes the situation well enough without making any additional claims.

MBS-10747: Fix misleading open edit message

---

lib/MusicBrainz/Server/Data/Artist.pm

The reason we have a sort name is to sort by it, so when sorting collections by artist we should use the artist's sort names, not their names.

MBS-10753: Use artist sort names for artist collection ordering

---

lib/MusicBrainz/Server/Controller/Account.pm
lib/MusicBrainz/Server/Data/Editor.pm

This was only saying you needed to donate if the MeB site returned a nag status of 1: "known editor, donation time has passed". It was not saying it when it returned -1 ("we don't know of this editor, has never donated before").
This change makes it so that only 0 ("no-nag period applies currently") is shown as "you don't need
to donate".

MBS-10640: Fix donation check

---

lib/MusicBrainz/Server/Data/Relationship.pm

Commit 2e2e5c670816e2892374e977874f21b2d8cb2419 added a sort by link_order here, but this causes issues (in RelationshipsTable we'd expect rels to sort by date but the ones with a higher link_order are getting pushed to the bottom) and doesn't actually do any good (the places where we care about link order, we already sort the rels properly on the JS side).

MBS-10756: Remove link_order from rels sort

---

root/static/scripts/common/components/ReleaseEvents.js
root/static/scripts/common/components/WorkArtists.js

The number being printed in "show {n} more" was events.length - COLLAPSE_THRESHOLD, but in fact the code prints two events before the collapse and one after - 3, not the 4 for COLLAPSE_THRESHOLD.
This moves the numbers to (easier to understand) constants, and then ensures we show the right number of events.

MBS-10742: Show right number of hidden events

---

admin/BundleSearchIndexesDump
admin/RequestSolrCloudBackups
admin/RunSearchIndexesDump
admin/config.default.sh
admin/config.search-indexes-dump.sh
admin/cron/daily-json-dump.sh
admin/cron/daily-search-indexes-dump.sh
admin/cron/daily.sh
bin/rsync-solrcloud-backups
docker/musicbrainz-search-indexes-dump/consul-template-search-indexes-dump.conf
docker/musicbrainz-search-indexes-dump/consul-template.service
docker/musicbrainz-search-indexes-dump/crontab
docker/templates/DBDefs.pm.ctmpl
docker/templates/Dockerfile.search-indexes-dump.m4
lib/DBDefs/Default.pm
lib/MusicBrainz/Script/MBDump.pm

Bootstrapping a mirror with indexed search requires huge resources.
Solution here is to provide search indexes dump on FTP to start with.
Since search indexes dump must have all entities from latest mbdumps, and is allowed to have more recent entities (that will be replicated), it starts at 4:10 which is expected to be after the end of full export.
SolrCloud collections backup is pretty fast (few minutes).
However compressing 50GB takes some time, thus the dedicated service.
It adds the following five entries to DBDefs:
* SOLRCLOUD_COLLECTIONS_API that is SolrCloud Collections API endpoint.
* SOLRCLOUD_BACKUP_LOCATION that is the absolute path on SolrCloud leader filesystem to save backups to and retrieve these from.
* SOLRCLOUD_RSYNC_BANDWIDTH that is passed to `rsync --bwlimit` to …

MBS-10546: Export search indexes dump to FTP

---

package.json
yarn.lock

The commit it was pinned to has been merged a while ago.

Bump tablesorter to 2.31.3

---

root/static/scripts/common/components/Annotation.js

https://tickets.metabrainz.org/browse/MBS-1921
This adds an extra "Edit annotation" link under annotations.
This link will make it clearer to users that they can edit the current annotation, which isn't always that clear at the moment since the only edit link is on the sidebar, very far away from the text.
Because the "View annotation history" link is already there sometimes, I'm separating them with a slash when that's the case. Seems cleaner than using brackets or periods.

MBS-1921: Display edit link under annotations

---

root/release_group/ReleaseGroupIndex.js

Add missing key prop to Fragment siblings, see https://reactjs.org/docs/lists-and-keys.html#keys.

Fix a warning from /release-group/ overview page in server logs

---

root/static/scripts/edit/utility/guessFeat.js
t/selenium.js
t/selenium/External_Links_Editor.html
t/selenium/release-editor/MBS-10359.html
t/selenium/release-editor/seeds/mbs-10359.html

I was able to reproduce this by re-importing the release in https://musicbrainz.org/edit/64567170, selecting the release artist first, then using the release-level guess-feat. button.
The problem appears to be that the artist credit name objects are getting shared internally, so modifying the join phrase on one AC name would potentially modify the AC name on an entirely unrelated track. (Note that this is a good example of why future React-based edit page rewrites should never use mutable state.)
The added test case consistently fails without the cloneDeep change.

MBS-10359: Guess feat. adds bogus trailing join phrases

---

cpanfile
cpanfile.snapshot

Traced this back to a change in Template::Toolkit 3.008 which inadvertently broke syntax of the form `SET a = b UNLESS c`. We use that in `_link_other_entity` and possibly elsewhere.
Downgraded to 3.007, which is what we run in production and fixes the issue.

MBS-10783: Beta: Links in edit listings go to /

---

.github/FUNDING.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/config.yml
CONTRIBUTING.md
README.md

Attempt to follow https://opensource.guide/best-practices/#be-proactive by adding a `CONTRIBUTING.md` file (essentially linking to our development docs for now), a pull request template and a funding link.
Note: Most of our development docs should ultimately be moved to `CONTRIBUTING.md` or other file in the repository itself. Additional hints are a link that has been [shared on `#metabrainz`](https://chatlogs.metabrainz.org/brainzbot/metabrainz/msg/4506987/) already, and common practices coupled with keywords that could be used to automate ticket’s transition on submission/merge/beta/release.

Complete GitHub docs to welcome contributors

---

lib/MusicBrainz/Server/Email/Subscriptions.pm

MBS-10641: Email says “see all **open** edits for your subscribed entities” but actually links to all edits for subscribed entities, not just the open ones.
Append supported query parameter `open=1` to the link.

MBS-10641: Fix link to open edits for subcriptions

---

lib/MusicBrainz/Server/Edit/Historic/RemoveLabelAlias.pm
root/edit/details/historic/RemoveLabelAlias.js
root/edit/details/historic/remove_label_alias.tt
root/server/components.js

The only change from the TT is to add the "remove-label-alias" class, for consistency.
Amazingly enough, it seems no info about the label itself is stored with these old edits, so all we do is literally print the alias being removed as a string.
On top of https://github.com/metabrainz/musicbrainz-server/pull/1462

MBS-10764: Convert historic Remove Label Alias edit to React 

---

root/edit/notes.tt

Because this header is styled the same way as the edit note headers
(the ones with an actual edit note), having this header makes it look
like there is a comment missing.
**Before:**
**After:**
Redundant header has been removed.

MBS-10804: Remove redundant header with editor name

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

MBS-10737: `thesession.org/sessions/` URLs cannot be entered
Whitelist `/sessions/` pages and map it to MB events.

MBS-10737: Allow The Session place URLs

---

root/static/scripts/edit/URLCleanup.js
root/static/scripts/tests/Control/URLCleanup.js

MBS-10803: Cannot link to `https://www.metal-archives.com/artists/<artist>/<number>`
Actually a bug in implementation https://github.com/metabrainz/musicbrainz-server/pull/1432.
Allow both `/artists/<artist>/<number>` and `/artist/view/id/<number>`.

MBS-10803: Fix allowing Metal Archives artist URLs

---

lib/MusicBrainz/Server/Data/Editor.pm

Changes to use the newer format for the nag check URL, which does support usernames with slashes (MEB-115). This avoids an ISE on the Donation Check page for these users.
This is fairly minor, since we only have 140 or so of these usernames, but still, we do have them :)

MBS-10768: Fix crash in donation check for names with slashes

---

lib/MusicBrainz/Server/Entity/URL/YouTube.pm

The sidebar limited the YouTube channel names to ASCII, but that is not how this actually works (the example channel URL from the ticket is "三浦コウkomiura"). This uses the decoded version of the URL for printing, and prints (almost) anything that could be a channel name.

MBS-10564: Display non-ASCII YouTube channel names too

---

root/static/scripts/guess-case/MB/GuessCase/Handler/Base.js
root/static/scripts/tests/GuessCase.js

Guess case tries to find whether a title includes "f/" or "f." (for featuring artists) by finding a solitary F, and then checking if the next "word" is "/" or ".". This usually works, but since it does it by trying to match the next word, we need to check whether said word actually exists at all before attempting to match. Otherwise, an F at the end of a title will lead to an attempted match on null (since there's no next word) and Guess Case crashing.

MBS-10138: Fix guess case for titles finishing in "f"
