metabrainz/musicbrainz-server

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/edit/externalLinks.js
- root/static/scripts/relationship-editor/common/dialog.js
- root/static/scripts/tests/Control/URLCleanup.js
This patch allows giving custom error messages for URLs that fail validation. Hopefully this will help avoid confusion when, for example, a user tries and fails to paste an Allmusic link on a release.
The patch already adds a fair amount of errors for cases that I have often seen can be confusing, but most validation failures will still return the default message. We should eventually decide just how often we want to give custom messages, but I would expect for a lot of the most obvious ones the default error message is enough.
This also changes the Wikipedia exception introduced in MBS-9515 to work as all the other newly-added error messages.
It also implements MBS-10831 and MBS-10412 for niconico improvements.
> MBS-9516: Support custom validation errors in URLCleanup

- docker/templates/DBDefs.pm.ctmpl
- lib/MusicBrainz/Server/Context.pm
- lib/MusicBrainz/Server/Data/Role/EntityCache.pm
This will allow us to bring the master database down while still allowing read-only access to MusicBrainz.
There are some minor changes and cleanups to the DBDefs.pm.ctmpl file here. I check its validity by copying the updated file into an MBS container on pink and running `consul-template -consul-addr=10.2.2.41:8500 -template /home/musicbrainz/musicbrainz-server/lib/DBDefs2.pm.ctmpl -once -dry`, which produced the output I expected.
> Default to READONLY database for DB_READ_ONLY

- package.json
- root/components/list/AreaList.js
- root/components/list/ArtistList.js
- root/components/list/EventList.js
- root/components/list/InstrumentList.js
- root/components/list/LabelList.js
- root/components/list/PlaceList.js
- root/components/list/RecordingList.js
- root/components/list/ReleaseGroupList.js
- root/components/list/SeriesList.js
- root/components/list/WorkList.js
- root/utility/tableColumns.js
- yarn.lock
The low usage we have of the API is affected by neither deprecation nor breaking change.
References:
* https://github.com/tannerlinsley/react-table/blob/master/CHANGELOG.md
* https://github.com/tannerlinsley/react-table/releases
> Bump react-table version to 7.1.0

- root/static/scripts/guess-case/modes.js
- root/static/scripts/tests/GuessCase.js
Guess Case currently does a pretty bad job with classical key names: they should be "in B-flat major" or whatnot as per the guidelines, but the guess case code just capitalizes them as any other words.
This is normally annoying, and sometimes kinda ridiculous ("Sonata in a Minor" is a quite  different from "Sonata in A minor"!).
The code only runs for key names preceded by "in", to avoid false positives ("Signed to a Major" or whatnot). I'm sure there are still some cases where this will give a false positive, but I'm pretty sure they will be much less common than the classical releases it currently mangles.
> MBS-10840: Fix key names in English guess case

- root/release/edit/tracklist.tt
- root/static/scripts/release-editor/actions.js
Sometimes, for example, one medium will have English titles and another titles in a language that requires sentence guess case, or most discs in a boxset are correct (and might become worse with automatic guesses) but one or two need guess case.
This add an extra Guess case button under each medium (there's already plenty of buttons there so it fits well) that affects only the tracks for that medium plus the medium title.
> MBS-10841: Add "Guess case" per medium

- root/user/ReportUser.js
- root/user/UserProfile.js
There seems to be no reason to allow reporting deleted editors, since they already deleted their account. I talked to Freso and he agreed. If there's a particular problem they still want us to look at they can contact us at support.
This changes the /report page to say that - I could have blocked it if the user has been deleted, but it feels that if somebody makes the effort of trying to get to /report without the link, we might as well explain the issue.
> MBS-10842: Remove report link from deleted editors

- lib/MusicBrainz/Server/Report/MediumsWithSequenceIssues.pm
Fixes `ERROR:  column "name" specified more than once`
> Fix MediumsWithSequenceIssues

- root/artist/ArtistIndex.js
For some reason, we didn't have a merge option if an artist only has standalone recordings and those are shown on the artist overview.
> MBS-10839: Add merge button to recording list in artist overview

- lib/MusicBrainz/Server/Report/QueryReport.pm
- lib/MusicBrainz/Server/Report/RecordingTrackDifferentName.pm
- lib/MusicBrainz/Server/Report/RecordingsSameNameDifferentArtistsSameName.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/ReportsIndex.js
This should unbreak daily.sh for now and allow subscription emails to get out without us having to manually kill RunReports.pl.
> Prevent two statement timeouts in reports

- lib/MusicBrainz/Redis.pm
- lib/MusicBrainz/Server/Controller/Admin.pm
- lib/MusicBrainz/Server/Controller/Root.pm
- lib/MusicBrainz/Server/Controller/User.pm
- lib/MusicBrainz/Server/Data/Editor.pm
- lib/MusicBrainz/Server/Form/Admin/EmailSearch.pm
- root/admin/EmailSearch.js
- root/admin/IpLookup.js
- root/admin/components/UserList.js
- root/layout/components/TopMenu.js
- root/server/components.js
- root/user/UserProfile.js
- t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
/admin/email-search:
Allows account admins to search users by email using a POSIX regular expression. Since I didn't bother paging the results, it's limited to returning 100 users (in case someone were to accidentally enter a pattern matching half the database) ordered by signup date.
/admin/ip-lookup/$hash:
Allows account admins to see a list of users accessing MusicBrainz from a specific IP hash (an MD5 of their IP address). This is linked from users' profile pages, which now display a list of hashed IPs "belonging" to a user to account admins. (The point of the hash isn't to be cryptographically secure, since admins can find this data in the server logs anyway; it's just to obscure the possible geographic location of the user, since it doesn't seem relevant in most cases.)
Redis keys …
> MBS-10845: User lookup tools for account admins

- INSTALL.md
- lib/DBDefs.pm.sample
- lib/DBDefs/Default.pm
- lib/MusicBrainz/Server/Data/Search.pm
- lib/MusicBrainz/Server/Data/WebService.pm
NOTE: This is not mergeable until search.mb.org/wstest/2 becomes live at search.mb.org/ws/2, but it needs some more work from Zas first.
The relevant openresty config is at https://github.com/metabrainz/openresty-gateways/blob/master/files/nginx/includes/search-server_server_http_05.conf
Edit: this change is now in production, as 2020-05-26
---
* WS1 is removed.
* The default `SEARCH_ENGINE` setting is changed to 'SOLR'. If 'SOLR' is in use and `SEARCH_SERVER` is set to the default public search server (search.musicbrainz.org), it uses the compatibility API described in MBH-502. This is the very same code used if `SEARCH_ENGINE` is set to 'LUCENE' (which I assume the VM still needs?). Otherwise it assumes direct SOLR access (so, production or someone setting up their own instance).
* The …
> Prepare for SOLR access via search.mb.org (MBH-502)

- lib/MusicBrainz/Server/Form/Collection.pm
- root/static/scripts/collection/components/CollectionEditForm.js
- root/static/styles/forms.less
Up until now a user could type in an editor name in the collaborators field for a collection and try to submit without selecting a result, leading to an ISE.
The error field is special-cased to remove the margin because otherwise a margin of over 160px makes it look absurd.
Also, inputName for the autocomplete was incorrect, so this fixes that.
> MBS-10732: Add collaborator validation to collection form

- script/update_containers.sh
Because deploying a new beta version is more work, we need more restful sleeps! Joking aside, this is because there are only 2 servers in beta, and starting a container currently takes more than 30 seconds. This is due to `compile_resources.sh` being run by the container rather than at build time.
> Sleep when deploying

- lib/MusicBrainz/Server/Email/Subscriptions.pm
We already have the link for the entities, so there's no reason not to also give the equivalent link for subscribed editors.
> MBS-10853: Include link to subbed users' open edits in sub email

- root/layout/components/Footer.js
For some reason we were showing git branch info on production. This information was meant for staging servers, so this adds a check to ensure we only display it in those.
> MBS-10613: Only show git info on staging servers

- lib/MusicBrainz/Server/Edit/Historic/ChangeTrackArtist.pm
We were showing nothing at all for the recording in historic Edit Track (ChangeTrackArtist) edits if the recording ID didn't resolve to an existing recording. That's kinda confusing, so this ensures we at least show Recording: [removed] there to clarify the situation.
> MBS-10855: Show [removed] recording in historic EditTrack

- lib/MusicBrainz/Server/Controller/Edit.pm
- lib/MusicBrainz/Server/Controller/User.pm
- lib/MusicBrainz/Server/Controller/User/Edits.pm
We have different pagination limits for different edit pages, which leads to situations like artist/mbid/edits showing 100 edits but the edit search reached when clicking "Refine this search"
(which a user would no doubt expect to be equivalent, until they refine it) only showing the first 25 of them.
This standardises all of those 25-edit lists to 100, our default pagination limit.
If this seems like too much for some reason then we could change all edit listings to show 50, but I think 100 should be doable since it was already used in most places anyway.
> MBS-8412: Standardize pagination limits

- root/edit/details/edit_barcodes.tt
While in the edit data the field that is used here is "barcode", the display data maps it to "new_barcode", so no barcode was shown when the edit just added a new barcode to releases that had none.
By the way, any reason we shouldn't just use a diff anyway and just pass an empty string if no old barcode exists?
> MBS-10863: Fix Edit barcodes edit display for no barcode -> barcode

- lib/MusicBrainz/Server/Report/BadAmazonURLs.pm
- root/static/scripts/edit/URLCleanup.js
Two big issues here: first, we currently support quite a few more subdomains than this accepted even for proper Amazon store products, and second, this was catching every Amazon Music link as a false positive.
Added comments to URLCleanup to help us avoid this in the future.
> MBS-10850: Update BadAmazonURLs report to avoid false positives

- root/edit/details/AddReleaseGroup.js
On the release editor preview, new RGs were being shown as removed.
WS::js::preview is already passing allowNew here for previews, we just weren't using it.
> MBS-10849: Check for allowNew on AddReleaseGroup

- root/static/scripts/edit/URLCleanup.js
- root/user/UserProfile.js
Many new error messages have been added with #1515 and #1529. A word is likely missing according to https://community.metabrainz.org/t/incomplete-string-is-not-translatable/478813 and I found some other phrasing issues while translating.
1. Get latest translations before re-uploading `server` resource to Transifex
> Fix new localizable messages

- lib/MusicBrainz/Server/Data/Release.pm
Currently a lot of cover art on the front page is not shown since it hasn’t been processed by the IA yet, so visitors see "Image not available yet" messages instead.
MBS-10469: The proper solution to fix this would be to not show images on the front page until they’re actually processed, but I am not currently aware of a way to do this easily and reliably (there are database columns for storing sizes of the thumbnails, but they don’t seem to be populated, otherwise they would possibly be a good fit).
This is mostly meant as a temporary workaround to lessen the problem. It won’t remove the problem entirely, since sometimes cover arts take more than 10 minutes to generate, but having a 3+ hour long wait also seems excessive.
I don’t have access to a live test server, so I’ve only played …
> MBS-10469: Add 10 minute delay to shown CAA on front page

- lib/MusicBrainz/Server/Controller/Role/Tag.pm
- root/layout/components/sidebar/SidebarTags.js
- root/static/scripts/common/components/TagEditor.js
- root/types.js
- root/utility/sanitizedEditor.js
- t/lib/t/MusicBrainz/Server/Controller/Work/Tags.pm
People are creating email-less accounts to mass-tag their favourite boy band. While that's mostly harmless, it's still stupid, and I can't see any reason why we should allow unverified users to submit tags.
Ratings were already blocked recently by MBS-10671 / https://github.com/metabrainz/musicbrainz-server/pull/1404.
Most "changes" are just extra indentation required from splitting lines because `has_confirmed_email_address` is a pretty long name.
> MBS-10771: Block tagging for unverified users

- lib/MusicBrainz/Server/Data/ReleaseGroup.pm
This was causing a SQL error and thus an ISE when filtering by name.
> MBS-10882: Remove accidental duplicate push

- lib/DBDefs.pm.sample
- lib/DBDefs/Default.pm
- lib/MusicBrainz/Server/Controller/Root.pm
- lib/MusicBrainz/Server/Controller/User.pm
IP hashes were stored and displayed to everyone on `test.musicbrainz.org` since everyone has account admin permissions.
Do not store IP hashes on staging servers running a sanitized database.
This is the same condition that is already used to inform that all passwords have been reset.
1. Set `DB_STAGING_SERVER_SANITIZED` to `1` for `test.musicbrainz.org`
> Sanitize IP hashes on staging servers

- lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
We have a control_for_whitespace_entity0_credit constraint, so trying to add a relationship credit ending in whitespace was causing an error. This actually trims the credits before submitting, as we do with other strings.
> MBS-10856: Trim whitespace on relationship credits

- lib/MusicBrainz/Server/Controller/User.pm
Checking stash keys is less reliable than DBDefs when available, see https://github.com/metabrainz/musicbrainz-server/pull/1552#issuecomment-639541115 for details.
Check DBDefs directly.
> Refactor 435310dd54: Check DBDefs instead of stash

- root/report/BadAmazonUrls.js
MBS-10885: <https://musicbrainz.org/report/BadAmazonURLs> is crashing after a reported URL has been removed.
Inform the URL no longer exists instead.
> MBS-10885: Fix error when URL has been removed

- docker/Makefile
- docker/templates/macros.m4
There were three issues here:
1. Docker requires ' and " to be escaped in the ENV command.
2. m4 could break spectacularly if you used its quote delimiters in the commit message. There's no way to escape these, so we have to temporarily change the quotes to something that'll never appear.
3. The GIT_MSG wasn't quoted in m4, so underwent macro expansion.
If the commit title I've used here doesn't (1) immediately crash the Docker build or (2) cause it to hang forever due to recursive macro expansion in `GIT_MSG`, this should be a success. :)
> Escape ', ", `, and GIT_MSG in GIT_MSG

- root/layout/components/BottomMenu.js
- root/main/index.js
Magic MP3 Tagger has been replaced by the creator's new tool, AudioRanger. This updates the links so we don't point to deprecated software.
> MBS-10891: Replace Magic MP3 Tagger link with AudioRanger

- lib/MusicBrainz/Server/Edit/Medium/SetTrackLengths.pm
- t/lib/t/MusicBrainz/Server/Edit/Medium/SetTrackLengths.pm
If a CD TOC is removed before an edit setting track times from it applies, the edit currently fails to close. This fails it with an appropriate failed dependency message.
> MBS-10186: Check for missing CD TOC on SetTrackLengths

- lib/MusicBrainz/Server/Form/Work.pm
- root/static/scripts/work.js
There's no case where it makes sense to have [Multiple languages] or [No lyrics] and a second, different language as a work language at the same time.
There's already a limitation on the JS layer that makes it so no more languages can be added if one of the two is selected, but that doesn't affect any languages already selected before them.
I chose not to further enforce this on the JS level because the form verification does all that is needed while making sure the selected languages do not get lost/deselected, which would seem annoying if the user selected one of these two by mistake.
> MBS-9340: Only allow mul and zxx as the only work language 

- lib/MusicBrainz/Server/Edit/Relationship/Delete.pm
- lib/MusicBrainz/Server/Entity/EditNote.pm
- t/lib/t/MusicBrainz/Server/Edit/Relationship/Delete.pm
- t/sql/edit_relationship_delete.sql
If someone tries to remove an example relationship, the edit gets stuck. We don't want people to actually remove these themselves, so this fails the edit and asks them to contact us.
Eventually, we might want to block entering these removals completely, but that's much harder and given the situation is pretty rare, this seems like a good first step.
> MBS-9931: Fail gracefully when trying to remove example rel

- lib/MusicBrainz/Server/Report/CatNoLooksLikeLabelCode.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/CatNoLooksLikeLabelCode.js
- root/report/ReportsIndex.js
- root/server/components.js
This finds catalog numbers that look like label codes, which seems to be a surprisingly common error.
> MBS-10862: Report "CatNoLooksLikeLabelCode"

- admin/sql/CreateFunctions.sql
- admin/sql/updates/20200512-mbs-10821-orphaned-recording-collection.sql
- t/pgtap/delete_orphaned_recordings.sql
An edit medium edit is stuck because one of the recordings that would be orphaned and removed with the edit is in an editor collection.
While silently removing the recording from a collection might not seem ideal, this is already what we do with other entity removals. The alternative would be to fail edits that would cause that, but that would block removal of any recordings that should be removed but are still present on an editor's collection for whatever reason, since the collection owner would need to actively remove them from the collection to allow the medium edit to ever apply.
> MBS-10821: Remove orphaned recordings from collections for deletion

- root/static/styles/layout.less
MBS-10907
Previously, background color was set for the main content only.  Header and footer were lesser readable when the browser’s background color was not white as well.
This patch defines the background for HTML body instead of main content.
> MBS-10907: Set white background color to HTML body

- lib/MusicBrainz/Server/Report/RecordingsWithFutureDates.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/DeprecatedRelationshipRecordings.js
- root/report/RecordingsWithFutureDates.js
- root/report/ReportsIndex.js
- root/report/components/RecordingRelationshipList.js
- root/report/types.js
- root/server/components.js
MBS-10770 new report about recordings with relationships having dates in the future
New report (.pm + .js) to display dates / relation type / link to recording
The SQL query looks for begin dates > current year OR end date > (current year + 5y)
I tried to keep the SQL query straightforward. On the JS side I added the support of date columns on RecordingRelationshipList instead of creating a new one (even if for this report the Artist column is not needed).
Works on my local instance with the sample data so I don't expect more work to be needed (except i18n) before merging.
> MBS-10770: add report about relationships with future dates

- lib/MusicBrainz/Server/Report/ReleasesConflictingDiscIDs.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/ReleasesConflictingDiscIds.js
- root/report/ReportsIndex.js
- root/report/components/ReleaseList.js
- root/server/components.js
MBS-10895
New report (.pm and .js)
Add subPath to report/<ReleaseList> react class in order to have links directly to release/uuid/discids page
Ready for review.
Works on my local instance with sample data
Possibly change what the cutoff should be, I started with a 5 minutes minimal difference between discids on the same medium
> MBS-10895: conflicting discids report

- root/static/scripts/common/entity.js
MBS-10894 Display label code in the release editor
Add label code in the info bubble after selection of the label
Tested on local instance with sample database, looks ready to me
> MBS-10894: Add LC code in help bubble after adding label in release editor

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
While old Operabase cleaned links still redirect correctly, they have changed their URL format. The new format is simpler and no longer requires the artist name.
> MBS-10903: Update Operabase cleanup / validation

- lib/MusicBrainz/Server/Edit/Relationship/Create.pm
- lib/MusicBrainz/Server/Edit/Relationship/Delete.pm
- lib/MusicBrainz/Server/Edit/Relationship/Edit.pm
- lib/MusicBrainz/Server/Edit/Relationship/RelatedEntities.pm
- lib/MusicBrainz/Server/Edit/Relationship/Reorder.pm
While it's generally useful to show relationship changes for a work on recordings and releases connected to the work (MBS-6532), for example if writers are being added or changed, there's one very common use case (recording-work "recording of" rels) where the edits are just noise on other recording entries. The fact that other, unrelated recording is or isn't a recording of this work should never affect the other recordings of the work in any way.
This makes it so the edit is only added to the edit histories of recordings and releases connected to the work if the relationship type is *not* "recording of". The recording and release(s) that are directly connected to the edit will still be linked through the recording side of the edit data.
Also, the previous implementation of MBS-6532 had …
> MBS-10908: Stop recording-of rel edits showing for all recordings of a work

- package.json
- yarn.lock
> The low usage we have of the API is affected by neither deprecation nor breaking change.
> 
> Reference:
> * https://github.com/tannerlinsley/react-table/releases
> Bump react-table version to 7.2.1

- root/static/scripts/common/components/Autocomplete2.js
- root/static/scripts/common/components/FingerprintTable.js
- root/static/scripts/common/components/ReleaseEvents.js
- root/static/scripts/common/components/WorkArtists.js
We seem to have missed these when we did the conversion to the "import * as React" format.
> Fix some left-behind "import React" imports

- root/edit/details/AddRelationship.js
- root/static/scripts/common/components/Relationship.js
Add Relationship edits were always assuming allowNew should be set, but in reality this should only be set where the entity didn't ever exist (usually in previews) rather than every time the entity was missing.
While in most cases I could think of either both entities should have allowNew or neither should, I made a separate allowNew for entity0 and entity1, just in case.
> MBS-10927: Check whether entity existed before setting allowNew

- lib/MusicBrainz/Server/Controller/Event.pm
MBS-10246 removed the special case "attendance" but Controller::Event wasn't changed to go along with it, breaking the event collections page. This fixes that oversight.
> MBS-10917: Remove no longer used "attendance"

- lib/MusicBrainz/Server/Edit/Historic/Relationship.pm
- lib/MusicBrainz/Server/Entity/Relationship.pm
Some old edits (at least edit 12587968) are missing this.
> MBS-10833: Avoid crashing if entity0_id is missing

- lib/MusicBrainz/Server/Edit/Relationship/Delete.pm
Always creating a new LinkAttributeType means we're missing data that is necessary, for example, to decide whether to also convert text_value to JSON, causing the bug here. This change ensures that we use the actual attribute as loaded from the DB if possible, in the same way we already do on Relationship::Create.
> MBS-10943: Fix loading attribute on Relationship::Delete

- lib/MusicBrainz/Server/Edit/Relationship/Create.pm
- lib/MusicBrainz/Server/Entity/Relationship.pm
- root/static/scripts/common/components/Relationship.js
- root/types.js
- t/lib/t/MusicBrainz/Server/Controller/WS/js/Release.pm
Removed reltypes (such as "microblog") no longer have info on which entity types they expected as type0 and type1. Luckily, we have source_type and target_type on relationships which serve the same purpose and can be used as a replacement.
> MBS-10930: Fix loading relationship entities for removed reltypes

- root/release/edit/information.tt
- root/static/scripts/release-editor/fields.js
- root/static/scripts/release-editor/validation.js
MBS-9502
Display warning when creating a new release if the barcode is already linked to an existing release
Add request to ws/2/release with the barcode as the same time as the UPC/EAN validation is performed
Display a sentence suggesting to check to search page results and confirm the new release is different.
Looks ready to me.
Works on my local instance with the sample database
Please confirm the call to /ws/2/ is the right way to do this.
> MBS-9502: Add search for pre-existing barcode value in release editor

- root/components/relationship-editor.tt
- root/static/scripts/relationship-editor/common/dialog.js
- root/static/styles/relationship-editor.less
MBS-10926: Add "paste date" button in relationship editor dialogs
Minimal solution to keep the UI simple:
* only the copy begin → end behavior
* only on the relationship editor
The userscript still exists for more complex behavior.
I guess this part will be converted to React later, so it might be easy to apply somewhere else.
Looks ready to me
> MBS-10926: add 'copy date' button on relationship editor dialog

- lib/MusicBrainz/Server/Data/Recording.pm
- lib/MusicBrainz/Server/Data/Release.pm
- lib/MusicBrainz/Server/Data/ReleaseGroup.pm
- lib/MusicBrainz/Server/Data/Role/Collection.pm
`DISTINCT ON (release.id)` is used here because the joins create "duplicate" rows for every release. With DISTINCT ON, only the first row from each set is kept, so the ORDER BY in the inner query is important. If `$order_by` is say `date_year, date_month, date_day, name COLLATE musicbrainz`, then after sorting by id we also want it to consistently pick the row with the earliest year, then month, etc. (There will be a different row for each release event.)
In the outer query, we also want to make sure that releases that happen to have the same release date and name (or whatever the configured sort order is) are next ordered by id, otherwise the sort is undefined.
One gotcha here is that `$order_by` references column aliases that can be used in the outer query, but not the inner one. We …
> MBS-10923: Fix inconsistent ordering in find_by_collection

- package.json
- yarn.lock
* Bump react-table version from 7.2.1 to 7.3.2 ([releases](https://github.com/tannerlinsley/react-table/releases))
* Bump lodash version from 4.17.11 to 4.17.19 ([changelog](https://github.com/lodash/lodash/wiki/Changelog))
> Update lodash and react-table to the latest version

- root/edit/edit_header.tt
Each search for edits was filling logs with one hundred of:
[warning] GET …/search/edits?… caused a warning:
Argument "" isn't numeric in numeric eq (==)
at lib/MusicBrainz/Server/Edit.pm line 144.
This patch prevents calling this subroutine for not logged in users.
> Skip looking for latest vote when not logged in

- docker/templates/Dockerfile.test-database.m4
This is needed for importing dumps. It was present in the postgres 9.5 base image but isn't present in the postgres 12 image.
> Install bzip2 in the test-database docker image

- root/artist/utils.js
- root/layout/components/sidebar/ArtistSidebar.js
- root/layout/components/sidebar/PlaceSidebar.js
- root/utility/isFutureDate.js
MBS-10562
This only adds the option for cases that seem likely to happen and where we have custom phrases already. The opening and closing of a place can be announced ahead of time, and so can the dissolution of a group (but it would be strange to announce the foundation of a group before it happens, very dodgy to announce the death of a person and pretty much impossible to specify the birth of one).
> MBS-10562: Add phrases for future (sidebar) dates

- .circleci/config.yml
- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
1. In CircleCI, failed tests for JavaScript (including URLCleanup) did not show actual results (to compare to expected results).
See [job #10360’s summary](https://app.circleci.com/pipelines/github/metabrainz/musicbrainz-server/3507/workflows/1dd22714-0b21-436c-ac93-9ccbbfb5b363/jobs/10360) and [job #10360’s steps](https://app.circleci.com/pipelines/github/metabrainz/musicbrainz-server/3507/workflows/1dd22714-0b21-436c-ac93-9ccbbfb5b363/jobs/10360/steps) for example.
2. MBS-10932:  Until then, Instagram photos were disallowed to be linked to an entity, but videos had not been even considered.
1. Fix CircleCI config in commit https://github.com/metabrainz/musicbrainz-server/pull/1590/commits/4ab7fce77bda0832f3d364bef44dcf4f858ea154
See [job #10370’s …
> MBS-10932: Allow linking Instagram videos to MusicBrainz recordings

- lib/MusicBrainz/Server/Controller/Edit.pm
- lib/MusicBrainz/Server/Controller/Role/EditListing.pm
- lib/MusicBrainz/Server/Controller/User.pm
- lib/MusicBrainz/Server/Controller/User/Edits.pm
MBS-8412 standardised all lists to 100 items, including edit lists (which used to be 25 items, except for the EditListing role, which didn't set a limit so it used the standard 100 item limit).
Some users were overwhelmed by 100 edits everywhere, so this sets all edit lists to 50 items per list, including in EditListing.
> MBS-10990: Limit edit displays to 50 edits per page 

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
Apple Music links can apparently be both purchase or streaming. As such, until MBS-9902 is implemented we should only clean the links up but not autoselect a relationship.
> Drop autoselect for Apple Music

- lib/MusicBrainz/Script/JSONDump.pm
Disables reading from the json_dump.* tables (pulling cached JSON) when making full JSON dumps. This is slower, but will help mitigate MBS-10911 (so that data remains stale until, at most, a Wednesday or Sunday), which has been reported by multiple people.
> Disable the full json dumps cache

- root/components/RelationshipTargetLinks.js
- root/components/StaticRelationshipsDisplay.js
- root/static/scripts/common/components/AreaWithContainmentLink.js
- root/static/scripts/common/components/DescriptiveLink.js
- root/static/scripts/common/components/EntityLink.js
- root/static/scripts/common/components/Relationship.js
- root/static/scripts/edit/components/edit/RelationshipDiff.js
If a URL relationship has an "ended" flag (e.g. an artist's homepage is gone), this displays it as just text (a "disabled link").
Especially significant in cases where the URL has been taken over by a cyber-squatter/scammer or some other disreputable site that we do not want to provide links (and possible page-rank) to.
> MBS-10992: Disable ended URL links

- lib/MusicBrainz/Server/Controller/Artist.pm
Just adding 'split' to the usual after sub list doesn't work, so I just added it to the actual sub split.
> MBS-9420: Load collection info for sidebar in sub split

- lib/MusicBrainz/Server/Controller/User.pm
- root/server/components.js
- root/user/UserMessage.js
- root/user/email_sent.tt
- root/user/message.tt
This reuses the existing StatusPage component, which works perfectly for the use case (but should maybe be renamed by now).
email_sent.tt was effectively the same page but with the messages defined on the TT instead of the Perl side. I moved them to the Perl side so it can also use UserMessage.
> MBS-10994: Convert user/message.tt to React

- t/selenium.js
- t/selenium/release-editor/MBS-11015.html
https://tickets.metabrainz.org/browse/MBS-11015
This test case demonstrates that changing a medium's format (and nothing else) doesn't delete the tracklist.
> Add regression test for MBS-11015

- root/static/search_plugins/firefox/musicbrainzartist-old.src
- root/static/search_plugins/firefox/musicbrainzartist.src
- root/static/search_plugins/firefox/musicbrainzlabel-old.src
- root/static/search_plugins/firefox/musicbrainzlabel.src
- root/static/search_plugins/firefox/musicbrainzrelease-old.src
- root/static/search_plugins/firefox/musicbrainzrelease.src
- root/static/search_plugins/firefox/musicbrainztrack-old.src
- root/static/search_plugins/firefox/musicbrainztrack.src
- root/static/search_plugins/opensearch/musicbrainz_artist.xml
- root/static/search_plugins/opensearch/musicbrainz_label.xml
- root/static/search_plugins/opensearch/musicbrainz_release.xml
- root/static/search_plugins/opensearch/musicbrainz_track.xml
Problem
-------
Mozilla/Netscape search and OpenSearch files are outdated:
- Some icon URLs are broken
- **Their update URLs are broken**
- They are pointing to HTTP URLs (now we exclusively use HTTPS)
- They are using pre-NGS pages like search.html, textsearch.html and oldsearch.html
For the most part, it just relies on some redirects and works out well.
But I think it's cleaner to use canonical URLs.
Solution
--------
I replaced broken URLs by working URLs.
I also set canonical URLs instead of HTTP and pre-NGS URLs that were indirectly working after redirecting the user.
I am not sure that Firefox or another browser actually uses those non-standard OpenSearch `<Mox:UpdateUrl>` tags at all.
See https://developer.mozilla.org/fr/docs/Web/OpenSearch#Supporting_automatic_updates_for_OpenSearc …
> Update search plugin settings

- root/static/scripts/common/components/AreaWithContainmentLink.js
- root/static/scripts/common/components/DescriptiveLink.js
- root/static/scripts/common/components/EntityLink.js
- root/static/scripts/edit/components/ArtistCreditBubble.js
This solves several issues with the track names in ArtistCreditBubble:
1) Editing a new track's AC before adding a name showed [removed] as the title. Now it will show [missing track name], with a tooltip explaining that the user still needs to enter a track name.
2) Editing an existing track's AC after blanking its name showed no title at all, making clicking through to the track impossible. Now it will show [missing track name], but still link to the track.
3) Editing a new track's AC when a name had already been added still set the "deleted" class on the track name and displayed the "has been removed" tooltip. Now it doesn't show it as removed and uses the caption "This track hasn’t been created yet."
> MBS-10721: Improve track info in ArtistCreditBubble

- root/edit/details/historic/EditRelationship.js
- root/static/scripts/common/components/Warning.js
We seem to have some cases where historic EditRelationship edits do not have "new" for some of the "old" relationships in the old-new pairs. This makes no sense, so it's probably just data corruption caused during the NGS migration - we can't do much about it, so this just displays those old rels unchanged (diff with themselves) which is the least neurotic of the possibilities.
> MBS-10901: Fix ISE when historic EditRelationship data is broken

- lib/MusicBrainz/Server/Data/URL.pm
- root/components/RelationshipTargetLinks.js
- root/static/scripts/common/components/EntityLink.js
- root/static/scripts/common/components/Relationship.js
- root/static/scripts/edit/components/edit/RelationshipDiff.js
- root/url/UrlIndex.js
- root/url/utility/isGreyedOut.js
- root/utility/isDisabledLink.js
MBS-11049: Decoda has been reported to sometimes redirect to a scam page.
To do no harm, this patch temporarily disables external links to Decoda.
It should be reverted whenever their situation gets resolved.
> MBS-11049: Temporarily disable external links to Decoda

- root/layout/components/sidebar/RecordingSidebar.js
- root/static/scripts/common.js
- root/static/scripts/common/components/sidebar/AcousticBrainz.js
MBS-10916
Display AcousticBrainz info in Recording pages sidebar
Use React hook to fetch submission count from AB API. If not zero, fetch low-level data (tonal and rhythm).
See screenshot in MBS-10916
Tested on local database with sample data, works as expected
Check that the number of requests/data transfer amount to the AcousticBrainz API is reasonable. Another solution I tested quickly would be to display the result in the figerprints tab instead: less API requests vs lower visibility of the information
> MBS-10916: showing AcousticBrainz info in the Recording sidebar

- lib/MusicBrainz/Server/Edit/Relationship/Edit.pm
While this will be fixed more properly in the React conversion (where the message will be shown by the affected relationship, so we can revert to the original string), in the meantime this string gives a bit more useful information than just "This relationship already exists" at the bottom of the relationship editor.
The original string, which should be re-added on the React conversion, is still in use in several other places so the translation will not be lost.
> MBS-11014: Add context to DuplicateViolation on rels editor

- lib/MusicBrainz/Script/RemoveEmpty.pm
These edits often confuse users, who don't understand why their added entity has been removed without a word by some weird editor. This adds an explanatory edit note which should hopefully avoid those situations and help them understand they can readd the entity if needed.
@mwiencek: please let me know if localized_note would not work here for some reason :)
> MBS-11041: Make ModBot leave a note on autoremoval edits

- lib/MusicBrainz/Server/Controller/Series.pm
- root/types.js
- root/utility/tableColumns.js
An entity can appear more than once in a series with different series numbers. While it is uncommon, it is supported and has real-life use cases. With the current code, the number is overwritten and only the latest number is displayed for all rows of the series table.
This changes seriesItemNumbers to be an array that is later accessed based on the index of the react-table row (so, the entities array map).
As far as I can tell, this should work in any event where the arrays are just taken directly from Perl and sent up to React (even if we were to introduce server-side filtering or ordering later). If I'm missing a reason why this is a bad idea, do let me know! It's the most minor change I could figure out to fix this. I expect this would cause issues if we eventually decided to drop …
> MBS-11039: Don't use entity id as key for seriesItemNumbers

- admin/DumpJSON
- admin/nginx/mbserver-rewrites.conf
- lib/MusicBrainz/Server/Release.pm
- lib/MusicBrainz/Server/WebService/Validator.pm
- root/account/applications/Index.js
- root/entity/Details.js
- root/layout/components/BottomMenu.js
We are officially unmarking the JSON API as beta, making it more visible, and moving from "web service" to "API" as a name for both XML and JSON. The documentation has already been updated, so this makes the needed changes to MBS. We won't actually rename WebService on the code, this is just an outward-facing change.
> MBS-10941: Rename XML Web Service into "MusicBrainz API" 

- root/cdtoc/attach_list.tt
- root/static/styles/layout.less
Instead of a disabled radio icon (which e.g. recent versions of Firefox display the same as a non-disabled one!), this uses a forbidden sign. That should give a much more clear sign that you're not supposed to select those entries.
Discussion on the ticket is divided between showing these entries at all or not, and another suggestion is to move them to a separate section. But for now I feel this is the easiest way to make the difference more clear, at least.
Example:
> MBS-7409: Make "cannot attach discid" more obvious

- root/edit/details/EditReleaseGroup.js
> MBS-11000: Avoid "Edit release group" edit ISE when comment is null

- babel.config.js
- package.json
- root/static/scripts/common.js
- webpack/babel-ignored.js
- webpack/moduleConfig.js
- yarn.lock
While testing the lodash removal PR in IE11, I found that it was already broken in that browser even before the PR. So I started working on fixing that, since it's one of our supported browsers. Then I discovered some more disturbing stuff unrelated to IE11 (see commit "Disable core-js on plugin-transform-runtime"). That commit shaves about 502 kB off of common-chunks, or 37 kB after minification.
> Polyfill improvements (also unbreaks IE11)

- root/components/list/ReleaseGroupList.js
With the lodash changes for groupBy, the type here is no longer null but empty string, so currently no type string is shown at all.
> Fix unspecified RG type

- lib/MusicBrainz/Server/Data/CritiqueBrainz.pm
For some reason, CB's c3d344dabecbbcb007b266861e7ddd64b83107c2 commit replaced "created" with "published_on" (without any doc update nor any backwards compatibility), breaking our review display code.
> MBS-11077: Update sort parameter for load_display_reviews

- lib/MusicBrainz/Script/RemoveEmpty.pm
Fixes my mistake where I forgot an import in recently changed code. Seems the cron containers didn't get updated this release for some reason, meaning the bug isn't out yet.
> Add missing N_l import

- root/components/common-macros.tt
- root/edit/details/AddMedium.js
- root/medium/MediumTracklist.js
- root/medium/tracklist.tt
- root/static/scripts/common/components/PregapTrackIcon.js
One of these (MBS-11078) is a newly introduced regression. The other (MBS-11081) has been there from the beginning, but hey, might as well fix it too so once the edit works again, it's also complete.
MBS-11081 also brings the icon to a couple other places related to discIDs, where it certainly won't hurt.
> MBS-11078 / MBS-11081: Fix pregap bugs in Add medium

- root/layout/components/ExternalLinks.js
- root/static/scripts/release-editor/fields.js
MBS-11085: 
This was changed with cede01b1342c553ceb91e790f61eedcff26db5a8 - I assume under the assumption that MB.formatsWithDiscIDs is an object. It is not, though, it's just an array of IDs, so this was checking whether the position in the array matching the format ID was null. 
Changed to use includes, as it did before (just the native version).
MBS-11089:
While making the file flow strict-local I forgot to change this into a ternary, so it was being passed a boolean when className exists.
> MBS-11085 / MBS-11089: Fix canHaveDiscID check / Fix missing favicons

- lib/MusicBrainz/Script/RemoveEmpty.pm
Since https://github.com/metabrainz/musicbrainz-server/pull/1654, the generated message contained line breaks and indenting spaces.
Split into strings and concatenate with `.` operator.
> Amend d5e3f84e62 to fix localizable string

- root/static/styles/layout.less
MBS-11069
Browsers omit the rendering of trailing white spaces by default when they wrap content to fit the width of the containing element. In case the white spaces are part of the highlighted differences, they should be rendered before line wraps as well.
Change the behavior of white spaces for diffs via CSS, see https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
Someone should verify this change on a test server as I haven't installed the server on my machine (Hopefully I've added this to the correct stylesheet). I only verified that this works by dynamically changing the CSS of the [example that was given for the ticket](
https://musicbrainz.org/edit/62573212) using the Firefox development tools.
> MBS-11069: Fix diff highlighting of white spaces

- root/static/scripts/edit/externalLinks.js
I checked and there were only three more-or-less legitimate cases of this (among a larger amount of stuff clearly pasted in error such as links to the same entity the URL was added to). One of those was a link to our wiki summit page as an "official website" link for the Summit 2014, where some music got recorded (and arguably that is not an official website anyway) and the other two were artists using their own MusicBrainz user profile for a bio and then linking to their user page as their biography page (which is something I think we should disencourage anyway and feels very spammy, while being no better than just adding the same text to an annotation).
> MBS-11061: Disallow MusicBrainz URLs in relationships

- root/release/edit/editnote.tt
- root/static/styles/release-editor.less
Some high contrast modes make the red background in the tabs white, making it impossible to know which tabs actually have errors. This adds a warning icon to the appropriate tabs to make it more clear. It probably also helps with color-blindness to some degree, so 2x1.
Standard:
High contrast:
> MBS-11086: Add icon for tabs with errors in release editor

- lib/MusicBrainz/Server/Constants.pm
- lib/MusicBrainz/Server/Controller/User.pm
- lib/MusicBrainz/Server/Data/Editor.pm
- root/static/scripts/common/constants/editTypes.js
- root/user/UserProfile.js
MBS-9769
Display the number of entities created (artists, releases, etc.) on the editor main page
See screenshot on MBS-9769: new colum on the editor main page with the count of added entities for the main entity types (artists, releases, works, events...)
Tested on local instance with sample data, looks ready to me
I'm actually not sure how what the performance will be for editors with e.g. > 1 million edits. Can we try this on a test server?
> MBS-9769: add entities added stats on editor profile

- lib/MusicBrainz/Server/Edit/Release/Edit.pm
Edits adding release event without country such as edit 72951011 were causing the following warnings to occur in website server logs:
Use of uninitialized value $country_id in hash element at
lib/MusicBrainz/Server/Edit/Release/Edit.pm line 178.
Use of uninitialized value within @_ in anonymous hash ({}) at
lib/perl5/x86_64-linux-gnu-thread-multi/Moose/Object.pm line 42.
These warnings are neither causing nor revealing any issue but occurred 600 times just on yesterday.
> Fix innocuous warnings caused by Edit release edit

- lib/MusicBrainz/Server/Data/Release.pm
The old first release date (or lack thereof) was being cached and making RGs order wrongly in series until the cache got reset.
This resets the RG cache during release update if the release events change.
> MBS-10880: Reset RGs in cache when first date changes

- root/main/index.js
The Quick Start section in the front page seems like a good place to direct people to the most basic editing how-tos: artists and releases. A general link to the how-to page is in the documentation menu, but having these two somewhere that might be more directly accessible to newcomers can't hurt.
While we have a lot more how tos, these two are the ones that seem the most useful for new users, and from the bottom of those two they can always find the links to the more advanced ones.
> MBS-11062: Link basic how-tos from the front page

- lib/MusicBrainz/Server/Controller/Account.pm
- lib/MusicBrainz/Server/Data/Editor.pm
- lib/MusicBrainz/Server/Email.pm
To avoid email reuse, this only sends a verification email if the address isn't being used by any other editor.
For cases where the user has a good reason to reuse the address (such as bots) they can let us know and we can manually override the whole thing by skipping verification.
I don't have email sending setup locally. If this seems generally fine, I can throw it on test and try from there, but before that let's make sure I didn't do anything too dumb.
> MBS-10835: Don't send verification mail if address in use

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
IMSLP defaults to HTTPS, so we should clean up links to follow that.
This also adds basic validation: score links shouldn't include "Category", and artist ones should, since Category:Whatever links are their entries for a person and are never (AFAICT) used for a specific work or score.
> MBS-11017: Normalize IMSLP to HTTPS and add validation

- root/static/scripts/edit/externalLinks.js
In rare cases, the actual host of smart links might be a legitimate relationship as the homepage for a distributor (e.g. distrokid.com, unitedmasters.com). We will still want to block the specific smart links but not the host without any additional path.
It's true that, say, https://distrokid.com was already allowed, but simply copy-pasting their URL does give https://distrokid.com/ (which is blocked). We might as well make it a bit less annoying.
> MBS-11065: Only block smart links if they have a path

- lib/MusicBrainz/Server/Controller/CDTOC.pm
- root/cdtoc/attach_filter_release.tt
- root/cdtoc/attach_list.tt
- root/cdtoc/lookup.tt
If the specified MBID can't have the CD TOC attached, I figured it'd be confusing to show an empty results page, so it shows the requested release with a custom error message.
> MBS-7473: Allow specifying a release MBID when attaching a CD TOC

- root/edit/details/edit_medium.tt
- root/static/styles/layout.less
Too many leading and trailing white spaces are rendered for the positive part of the diff for changed recordings, see the [comment on the ticket](https://tickets.metabrainz.org/browse/MBS-11069?focusedCommentId=55354&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-55354).
This is a regression of #1691 which changed the style of highlighted differences to always render white spaces inside their `<span>` elements.
Move the code of the template that is not generating output out of the `<span>` element to avoid code formatting within the white space sensitive area.
This change needs to be verified again on a test server as I haven't installed the server on my machine.
> Beta (MBS-11069): Avoid code formatting within white space sensitive area

- admin/sql/updates/20200921-mbs-10921-unlist-unrelated-edits.sql
MBS-10921
Drop all of these wrongly listed edits from history, at a limited hourly rate so as to not create further troubles with replication.
The whole process will take around 4 days.
1. Build a production image and deploy to run hourly cron.
2. Check progress during the week and update ticket’s status accordingly.
3. Remove the delete queries from the hourly script.
> MBS-10921: Drop wrongly listed edits from history

- root/static/scripts/account/components/EditProfileForm.js
- root/static/scripts/common/components/Autocomplete2.js
- root/static/scripts/common/components/CodeLink.js
- root/static/scripts/common/components/TagEditor.js
- root/static/scripts/common/hooks/useOutsideClickEffect.js
- root/static/scripts/common/linkedEntities.js
- root/static/scripts/common/utility/parseIntegerOrNull.js
We can make error suppressions more granular by specifying which exact error code we're ignoring. (Sort of like specifying which exceptions to catch.)
https://flow.org/en/docs/errors/
In some cases I removed the suppression altogether by addressing the underlying issue, if it seemed reasonable enough to.
> Improve Flow error suppressions

- lib/MusicBrainz/Server/Report/ReleasesSameBarcode.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/ReleasesSameBarcode.js
- root/report/ReportsIndex.js
- root/server/components.js
This should almost never happen, unless the label made a mistake. This skips bootleg releases, since those sometimes intentionally are all given the same barcode anyway by the bootleg label.
> MBS-6322: Add report for releases with same barcodes in diff RGs

- package.json
- script/start_renderer.pl
- yarn.lock
Without this, Number.toLocaleString and Date.toLocaleString always use the English locale in Node 12, at the very least.
See https://nodejs.org/docs/latest-v12.x/api/intl.html
For testing, see that (e.g.) the statistics page does have the right thousand separators (comma for English, space for Estonian, thin space for French and dots for Spanish) rather than always having comma-separators.
> MBS-4118: Add full-icu to Node for locale strings

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
They point to the same content, so just removing `beta.` from them works.
> MBS-11121: Normalize Apple Music beta links

- lib/MusicBrainz/Server/Controller/Area.pm
- lib/MusicBrainz/Server/Controller/Artist.pm
- lib/MusicBrainz/Server/Controller/Collection.pm
- lib/MusicBrainz/Server/Controller/Series.pm
This is a generalization of MBS-10937. For some reason, a fair amount of places where we load user ratings are missing a load_meta call, so the average community rating is never loaded there (and the rating stars will thus remain grayed out). This adds the load_meta calls everywhere we already load user ratings for display.
> MBS-10956: Load ratings everywhere we also load user ratings

- lib/MusicBrainz/Server/Validation.pm
- t/lib/t/MusicBrainz/Server/Validation.pm
5 digits was the shortest our users found in SACEM (see ticket). Given that it seems unlikely a user would randomly type 5 digits by mistake in the IPI field, going down to this seems safe to me.
> MBS-8650: Lower how long an IPI must be to 5

- root/static/scripts/release-editor/fields.js
- t/selenium.js
- t/selenium/release-editor/MBS-11114.html
0d45452121257d336c915f1b78f1114a21afe518 broke this by incorrectly removing the "useless" isNaN check, which it turns out was not "useless." The result of `unformatTrackLength` is null when the length is empty, so the bug is that we'd bail out too early with the new check and fail to set `this.length(newLength)`. The result is only NaN when the input can't be parsed. A test is now added.
> MBS-11114: Allow track times to be unset

- root/release/edit/tracklist.tt
- root/static/scripts/release-editor/fields.js
With other errors like this one, we allow the user to edit as long as they don't actually introduce a problem that didn't previously exist. This does the same, by not giving an error (but still displaying a warning) if the too early format was already there. It will still give an error if the user selects *another* too early format.
IT'S ALL YOUR FAULT version:
YOU'RE GOOD version:
> MBS-11094: Don't block editing on pre-existing too early format

- .circleci/config.yml
- .eslintrc.unfixed.yaml
- .eslintrc.yaml
- script/check_unfixed_eslint_rules
- script/xgettext.js
A lot of efforts have been made to make the code follow some ESLint rules already, but nothing prevents new code to break them again. But `estlint` cannot be run with all rules currently defined in `.eslintrc` and not followed by code prior to these rules.
Create a script that checks only the rules followed so far. This script is for continuous integration and to be run manually for convenience when creating new code. It follows PR #1681 which enforced `indent` rule but for `script/xgettext.js`.
1. Add other rules that have already been applied, if any.
2. Gradually add more rules when fixing code to follow them.
> Enforce ESLint rules followed so far

- root/area/AreaRecordings.js
- root/area/AreaReleases.js
- root/area/AreaWorks.js
- root/artist/ArtistRelationships.js
- root/components/RelationshipsTable.js
I can't see any reason why we would not want to show relationship credits on all relationship tables. These aren't any less relevant on say label or place relationship tables as they are in artist or area ones.
> MBS-11104: Always show credits in RelationshipsTable

- root/components/Artwork.js
- root/main/index.js
I suspect having the release title and artist on the <a> title was meant to show it when hovering over the cover art, but it doesn't - we need to pass it down to ArtworkImage.
I also made Artwork itself support it, since we might as well want it later and it feels more consistent.
> MBS-11137: Show info on hover on frontpage's new releases

- root/admin/attributes/Attribute.js
While the descriptions for things like EventType (the one I actually added an HTML description for) don't actually show anywhere except the admin/attribute page yet AFAICT, it still probably makes sense to show them as intended here.
Hopefully we will eventually also display them elsewhere when relevant, so that most users can see them.
> MBS-11136: Support HTML in admin/attribute descriptions

- lib/MusicBrainz/Server/Controller/CDTOC.pm
- root/cdtoc/attach_filter_release.tt
This button is currently broken, but after some talk we decided that it shouldn't be fixed, but dropped. There's no way to know
that moving (as opposed to additionally adding) a CD TOC to a new release is correct, except for very specific cases.
It makes more sense to only allow moving the CD TOC to another existing release. If it has been added by mistake, it can either be removed from the wrong one (and the new release can just be added based on the CD TOC) or it can be moved after adding the release.
> MBS-11036: Don't show Add release button when moving CD TOC

- lib/MusicBrainz/Server/ControllerBase/WS/2.pm
- lib/MusicBrainz/Server/Data/Relationship.pm
This avoids returning all unrelated recording-work relationships for every release with work-level-rels inc, which in some cases
was over 90% of the size of the full response for no apparent benefit.
The only other relationship currently not returned because of cardinality is work-artist "artist was named after work", which also seems irrelevant to release responses anyway.
Note: we should make sure to notify users of this change when we release it (and possibly before?) in case someone specifically expected and made use of this behaviour. If needed, we could add a second, explicitly GIVE ME ALL inc that still works like before.
> MBS-11127: Use cardinality for work-level-rels in WS/2

- root/static/scripts/common/components/EntityLink.js
We can use relationship credits with most entity types. As such, it makes sense to supply the same hover info + span class name for them as we currently do for artists and recordings.
I special-cased URLs since I expect we don't really want to have hover features for them if we print a pretty-name and not the URL.
> MBS-11107: Support nameVariation for other entity types

- root/release/ReleaseHeader.js
Amend d17a2fd: Drop name-variation from "see all"
Remove span with class name-variation around "see all" releases link.
We did this once before for MBS-10536, but we've since changed the behaviour while implementing MBS-11107 so that it is shown if nameVariation is undefined and the content is not the entity name. As such, explicitly state we do not want nameVariation here.
> Remove span.name-variation around "see all" releases link

- docker/templates/Dockerfile.website.m4
Language packs /probably/ need to be installed before compile_resources.sh is run in order for translations to work. Just a guess.
Broken in aed356a10c0551d26f585d03a30a95918231f9c9
> MBS-11140: Build Jed language bundles in prod

- lib/MusicBrainz/Server/WebService/JSONSerializer.pm
artists was changed to related_artists with commit d1d8fbaf9c97f9d8f45b4e28b70b00a12688d3da but the autocomplete_work sub was not updated for it, breaking autocomplete.
> MBS-11147: Update autocomplete serialization

- script/tag.sh
GitHub doesn’t create a hyperlink if git message is just a link.
Adding a few words make GitHub to better format releases list.
Actually, I have been adding them for six months already.
For comparison, see `v-2020-04-13` and `v-2020-03-31` from <https://github.com/metabrainz/musicbrainz-server/releases?after=v-2020-04-27>.
> Improve blog link format in releases on GitHub

- README.md
Since we announce breaking changes in our blog, it makes sense to specify this in our readme.
> ORG-44: Update readme to mention the blog

- root/cdtoc/attach_filter_artist.tt
This was sending artist.gid, but that button is meant to be used "if you don't see the artist you are looking for", so submitting any gid is contrary to the intent anyway.
Since artist got loaded in a foreach earlier, this was just submitting the MBID of the last artist in the foreach loop.
> MBS-11150: Don't send artist gid if none selected

- HACKING.md
- admin/sql/CreateFunctions.sql
- flow-typed/npm/pg-cursor_v2.x.x.js
- flow-typed/npm/pg_v8.x.x.js
- package.json
- root/edit/details/RemoveRelationship.js
- root/static/scripts/common/DBDefs.js.flow
- root/utility/generateFlowType.js
- script/dbdefs_to_js.pl
- script/generate_edit_data_flow_type.js
- script/generate_json_flow_type.js
- yarn.lock
A SQL function, `edit_data_type_info()`, is added that generates "type info" for a single column of edit data.
A script, script/generate_edit_data_flow_type.js, is added which takes an edit type, `selects edit_data_type_info()` for every row of edit data for that type, and outputs a single merged Flow type representing the edit data overall for that type.
For example:
```sh
./script/generate_edit_data_flow_type.js --edit-type 92
```
Generates a Flow type for `EDIT_RELATIONSHIP_DELETE`.
The `PROD_STANDBY` database must be configured in DBDefs.pm to use this utility.
The underlying code used to build the Flow type may also be useful to generate Flow types for other JSON data, e.g. entities.json, so I've added script/generate_json_flow_type.js for this more general purpose too. Here's an …
> Function to generate Flow types from edit data

- lib/MusicBrainz/Server/Controller/CDTOC.pm
- root/cdtoc/attach_confirm.tt
- root/components/common-macros.tt
- root/static/styles/edit.less
- root/static/styles/layout.less
To be able to make sure that you're attaching the disc ID to the right disc before entering the edit, this displays info about the medium and compares the medium lengths to the ones on the disc ID.
> MBS-11115: Show extra info when attaching/moving discIDs

- lib/MusicBrainz/Server/Entity/URL/LoC.pm
We want to keep the URI as HTTP because that seems to be their official permalink, but they redirect to HTTPS so it makes sense for us to do the same.
> MBS-11139: Use HTTPS for display on Library of Congress links

- lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
- lib/MusicBrainz/Server/Data/Track.pm
- lib/MusicBrainz/Server/Edit/Medium/Create.pm
- lib/MusicBrainz/Server/Edit/Medium/Edit.pm
- lib/MusicBrainz/Server/Entity/Medium.pm
- root/components/medium.tt
- root/edit/details/AddMedium.js
- root/release/edit/recordings.tt
- root/release/edit/tracklist.tt
- root/release/edit_relationships.tt
- root/release/index.tt
- root/static/scripts/release-editor/edits.js
- root/static/scripts/release-editor/fields.js
- root/static/scripts/tests/release-editor/edits.js
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelease.pm
- t/sql/webservice.sql
This had to be reverted because I fucked up and didn't realize that the code as it was would remove the tracklist if the edit didn't actually change the tracklist at all. Now it checks that there is tracklist info in the edit opts before removing anything. 
On top of https://github.com/metabrainz/musicbrainz-server/pull/1632 to ensure that it doesn't happen again.
> MBS-8725: Allow mediums to have an unknown tracklist

- lib/MusicBrainz/Server/Report/CDTOCDubiousLength.pm
- lib/MusicBrainz/Server/Report/CDTOCReport.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/CDTocDubiousLength.js
- root/report/ReportsIndex.js
- root/report/components/CDTocList.js
- root/report/types.js
- root/server/components.js
- root/types.js
MBS-11117: new report about discid durations above 100 minutes, that should be fixed or removed.
cf https://community.metabrainz.org/t/sacd-types-and-discid/494807/8
cf screenshot on MBS-11117
There are a few things that need a serious review and will probably need rework:
* the report could be applied on releases but it makes more sense to have it on discids directly. Since there was no report on cdtocs yet, I had to create a lib/MusicBrainz/Server/Report/CdTocReport.pm ~~that just passes the parameters of the report SQL query. Not sure it would make more sense to pass the 'id' there, since we don't have gid on the cdtoc table.~~ (Edit: I had to use "id" in the end in order to use CDTocLink)
~~* CDTOCs are not defined with React yet. I didn't want to modify EntityLink so I just defined …
> MBS-11117: Create report for too long discIDs

- lib/MusicBrainz/Server/Controller/CDTOC.pm
- root/cdtoc/attach_list.tt
- root/cdtoc/list.tt
- root/cdtoc/lookup.tt
When importing a discID normally, you get given a nice table with a lot of data, including tracklist (see cdtoc/attach_list.tt). 
When importing it from a CDStub, a list of "Possible Mediums" was given, with only release title, artist, and medium number, forcing users to choose semi-blindly.
This patch changes the table to be more similar to the one in attach_list, with both more info and collapsible tracklists. attach_list itself can't directly be reused without changing the way we look for the possible mediums, but this reuses as many components as possible.
The second commit allows seeing tracklists both on the list of "Matching CDs" shown in Lookup CD, and on the list of mediums attached to a discid on cdtoc/index.
> Allow showing tracklists everywhere when attaching/viewing discIDs

- root/components/MediumToolbox.js
- root/release/index.tt
- root/server/components.js
- root/static/scripts/common/MB/release.js
- root/static/scripts/common/utility/request.js
- root/static/styles/layout.less
MBS-7256
If a release has, say, 20 mediums, expanding them all by hand is a huge pain. This makes it so that they can all be expanded and collapsed with one click.
> MBS-7256: Add "Expand all mediums" to release page

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
AFAICT vk.com always redirects to HTTPS now.  Given there was no normalization at all before this, there's no downside I can see to standardising in the future.
MBBE-17 exists to convert preexisting VK links to HTTPS.
> MBS-11167: Normalize vk.com links to HTTPS

- lib/MusicBrainz/Server/Data/Editor.pm
- root/admin/delete_user.tt
- t/lib/t/MusicBrainz/Server/Data/Editor.pm
- t/sql/vote.sql
In some cases, a rage-quitting editor might go out with a barrage of No votes (or, more insidiously, incorrect Yes votes).
In the same way we already cancel the editor's open edits upon deletion, this also changes their votes on edits currently open from Yes or No to Abstain.
> MBS-11173: Turn pending votes by deleted editor to Abstain

- root/work/edit_form.tt
If the work already has a work type selected then its description, rather than the default "select any type to see the description" text, should be shown from the beginning.
> MBS-11162: Show correct work type description if preselected

- root/layout/components/ExternalLinks.js
I checked the rest of the nonEmpty now to make sure I didn't mess up more of these... this seems to be the last one.
> MBS-11176: Fix missing nonEmpty ternary

- lib/MusicBrainz/Server/Controller/Area.pm
- lib/MusicBrainz/Server/Controller/Artist.pm
- lib/MusicBrainz/Server/Controller/Event.pm
- lib/MusicBrainz/Server/Controller/Place.pm
- lib/MusicBrainz/Server/Entity/AreaType.pm
- lib/MusicBrainz/Server/Entity/ArtistType.pm
- lib/MusicBrainz/Server/Entity/PlaceType.pm
- root/area/edit_form.tt
- root/artist/edit_form.tt
- root/components/forms.tt
- root/event/edit_form.tt
- root/place/edit_form.tt
- root/static/scripts/area.js
- root/static/scripts/artist.js
- root/static/scripts/edit/typeBubble.js
- root/static/scripts/event.js
- root/static/scripts/place.js
- root/static/scripts/work.js
- root/work/edit_form.tt
- webpack.client.config.js
We currently show work type descriptions when adding / editing works, but we don't do the same for other entities with types that already have descriptions, such as area, artist (ok, that didn't have them, I just added it), event, place. This extends that code to these four entities. 
Series already has the same kind of popup, implemented somewhat differently. If desired, I can try to replace the implementation there with this same one.
On top of https://github.com/metabrainz/musicbrainz-server/pull/1740
> MBS-11163: Show type descriptions when editing more entities

- root/relationship/linktype/RelationshipTypeIndex.js
While this *should* be an internal ID only, sadly it's needed for release editor seeding, see the docs for that at https://musicbrainz.org/doc/Development/Release_Editor_Seeding
> MBS-11158: Make relationship type rowids visible to all

- package.json
- root/components/Table.js
- root/layout/components/Search.js
- root/static/scripts/common/components/Autocomplete2.js
- root/static/scripts/common/components/Autocomplete2/reducer.js
- root/static/scripts/common/hooks/useEventTrap.js
- root/static/scripts/common/utility/cloneDeep.js
- root/static/scripts/edit/utility/editDiff.js
- yarn.lock
It's now an error for generics to escape outside of the scope they're defined in. Which usually just means that if a variable's type contains a generic type variable, then we can't pass that variable around without also passing the associated generic.
> Upgrade to Flow 0.136.0

- root/components/forms.tt
From context and the default message it's blindingly clear what these are supposed to be, so the header just takes space.
> MBS-11177: Drop "Description" label from type_bubble

- root/edit/details/historic/EditRelationship.js
We fixed this for missing newRel with MBS-10901 (https://github.com/metabrainz/musicbrainz-server/pull/1575) but apparently it also happens the other way around in some cases.
Also reverting a couple changes from that PR that seem unneeded.
> MBS-11194: Fix ISE when historic EditRelationship data is broken 

- root/artist/edit_form.tt
- root/edit/details/EditArtistCredit.js
- root/server/components.js
- root/static/scripts/artist.js
- root/static/scripts/artist/components/ArtistCreditRenamer.js
- root/static/scripts/edit/MB/Control/ArtistEdit.js
- root/static/styles/layout.less
- webpack.server.config.js
I tested with the extreme case of 9ddd7abc-9e1b-471d-8031-583bc6bc8be9 and tried to guarantee acceptable performance by caching the rows and keeping the checkbox state local.
Previews are now displayed at the bottom instead of inline, and use the `diffArtistCredits` utility.
The list is collapsed if there are more than 10 artist credits. (I've used the hide technique that annotations use, since actually adding/removing hundreds of items to the DOM is extremely slow.)
This also fixes MBS-6666 by hiding the fieldset if the artist name hasn't changed.
> MBS-11195: Convert the artist-credit-renamer to React

- lib/MusicBrainz/Server/Edit/Historic/Relationship.pm
Equivalent of MBS-10833 (https://github.com/metabrainz/musicbrainz-server/pull/1543) for entity0_id.
Some old edits (at least edit 6774077) are missing this. Since this is later loaded via linkedEntities, we need to use the same "fake entity ID" method we use for entity0 to access it (and since _display_relationships could hit several cases where this is needed, the fake ID needs to be distinct every time).
> MBS-11204: Avoid crashing if entity1_id is missing

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
The site redirects to HTTPS. I'm also normalizing to drop www. since both options are valid and the vast majority of our links don't include it (the site just accepts either without redirecting).
Works and artists are straightforward. I chose release rather than release group for 'records' because the site gives a format and catno, from what I can see.
This drops index.hml from artist pages because it's unneeded. It does not drop #sections because it seems in some cases different album pages are actually sections of a larger discography but we might still want to link to them.
> MBS-11197: Add validation for Mainly Norfolk links and normalize

- lib/MusicBrainz/Server/Controller/Artist.pm
- lib/MusicBrainz/Server/Data/Recording.pm
- root/artist/ArtistRecordings.js
If there are no standalone recordings or no videos then there is no good reason to actually give the user links to such subset pages.
I hope making this check every time a recording page is loaded isn't too bad given that I'm specifically limiting it to 1 - I can't see a good way to do this otherwise.
> MBS-7219: Hide links to empty ArtistRecording subsets

- root/static/scripts/release-editor/recordingAssociation.js
This wasn't actually finding recordings without length at all, except when the track also had no length (which made the query different).
This makes it so that recordings without length can also be found. Because we're unlikely to want recordings without length and *also* with a different artist as the track, and that can cause a lot of false positives, this restricts the no-length results to ones with matching artists.
While this certainly improves the inline search, I feel that this causes more (less precise) suggested recordings to appear. If you find while testing that that's the case, please do feel free to suggest improvements to the query.
I tested with "A Soul to Bear" by Fall of Efrafa, FWIW, but ideally you'd test it with other recordings that have no times to make sure it works …
> MBS-10829: Fix SOLR syntax for recording with no length

- lib/MusicBrainz/Server/Edit/Role/AllowAmending.pm
MBS-9505's 618e9109d151562e7787a1f76d87b75916d8117f changed auto edit grace period from 1h to 1 day but associated comment (just for coders) is still mentioning 1h.
I just updated the comments
It should have no impact on MBS runtime.
> Align comments with new code (very minor low priority PR)

- root/static/scripts/common/i18n/expand2react.js
This adds html tags legitimately generated by our MediaWiki syntax (annotations, bios, etc) to htmlTagName. While the
MediaWiki syntax parser sometimes generates invalid tags or puts them in the wrong order, this should unbreak some bios and cause no problems.
Originally part of https://github.com/metabrainz/musicbrainz-server/pull/1653
> MBS-10664: Allow more tags in expand2react

- lib/MusicBrainz/Server/Connector.pm
This seems to fix the error, but we might prefer trying to find where this is being re-encoded and stop it from happening instead.
> MBS-11207: Avoid double-encoding DBI errors

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
This autoselects IROMBOOK images on StaticBrainz as image links for instruments (and only for instruments).
> MBS-11225: Autoselect IROMBOOK images

- lib/MusicBrainz/Server/Controller/ReleaseGroup.pm
- t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
The URL for RGs is usually release-group (see entities.json) but following the url in ENTITIES fails for merge because of it being defined in a generic role. This adds forwarding so that /release-group/merge works and just forwards to /release_group/merge.
> MBS-11227: Ensure /release-group/merge also works

- lib/MusicBrainz/Server/Report/InstrumentsWithoutWikidata.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/InstrumentsWithoutWikidata.js
- root/report/ReportsIndex.js
- root/server/components.js
Wikidata is not connected to images at all anymore, but it's still a very useful link to have. As such, it makes sense to split this report in two. Also changed the query a bit to hopefully improve it.
We could just remove InstrumentsWithoutAnImage, but hopefully we can soon use it again once we start being able to link to IROM images on StaticBrainz.
> MBS-11216: Split InstrumentsWithoutAnImage report

- lib/MusicBrainz/Server/Data/Event.pm
I'm pretty sure this was originally based on `Work::find_by_artist`. But there the `UNION` in `s` ensures uniqueness of the IDs, which I clearly didn't consider when modifying the queries for events.
> MBS-8438: Only return event once in find_by methods

- lib/MusicBrainz/Server.pm
- lib/MusicBrainz/Server/Controller/CDStub.pm
- lib/MusicBrainz/Server/Controller/Rating.pm
- lib/MusicBrainz/Server/Controller/Role/Merge.pm
- lib/MusicBrainz/Server/Controller/Root.pm
- lib/MusicBrainz/Server/Controller/User.pm
- root/layout/components/MergeHelper.js
https://tickets.metabrainz.org/browse/MBS-11238
5ab8cfba261175f4712d89a230b2c8b0c2bc716a made it so that session/login cookies are only sent in first-party contexts from the same origin. This means the user will appear as logged out if they click on any links to MB from an external origin. In order to address this, we either have to downgrade to SameSite=Lax and ensure we don't allow any data modifications via GET requests, or add a separate non-strict cookie that points to a user session for display but doesn't authenticate as that user. I'm not sure how to do the latter with Catalyst without breaking a lot of assumptions we make throughout the codebase, so I'm "downgrading" the cookies to Lax mode and tweaking a couple cases where it might be possible to submit changes via a GET …
> Use SameSite=Lax for login cookies (fixes MBS-11238)

- root/components/PostParameters.js
- root/static/styles/forms.less
This should preserve newlines in the input.
The CSS changes are required in order to make the inputs and textareas have identical widths. Setting size=50 and cols=50 wasn't sufficient because the font families and font sizes were different for some reason.
> MBS-11241: Seed annotation, edit_note with textarea

- lib/MusicBrainz/Server.pm
- lib/MusicBrainz/Server/Controller/Root.pm
If someone has the beta preference on and uses an external importer, the POST request won't include the beta cookie due to it using SameSite=Lax. This switches the beta cookie to use SameSite=None so that the 307 redirect is performed before the ConfirmSeed page is shown twice (first on the production site, then again on the beta site).
> Set SameSite=None on beta cookie

- lib/MusicBrainz/Server/Data/Recording.pm
If `@ids` is empty, this errors with `invalid input syntax for type integer: ""`.
For example, on: https://beta.musicbrainz.org/ws/2/recording?artist=93ce655f-d54f-435f-a13c-0c6fb1f10a96&inc=work-rels&limit=100&offset=0
> Beta: Fix load_first_release_date for empty recording lists

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
They redirect to HTTPS (with www.) so we should do the same. MBBE-25 will convert existing links.
Also added validation for different sorts of links I could find.
> MBS-11221 / MBS-11234: Normalize whosampled.com links to HTTPS and add validation

- lib/MusicBrainz/Server/Report/ReleasesSameBarcode.pm
We were checking the same release twice, instead of checking whether both releases were not bootlegs.
> MBS-11291: Fix wrong bootleg check in ReleasesSameBarcode

- lib/MusicBrainz/Server/Controller/CDTOC.pm
We load these when we have a medium param, but not otherwise.
> MBS-11275: Load recordings for cdtoc move

- root/entity/Ratings.js
I chose the wrong conditional when original converting this, meaning an entity having only private ratings was displayed as having no ratings at all.
> MBS-11278: Also show rating info when there's only private ratings

- package.json
- root/static/scripts/common/components/Autocomplete2/formatters.js
- root/static/scripts/common/components/Autocomplete2/types.js
- root/static/scripts/common/i18n/expand2react.js
- yarn.lock
This resolves some issues that have arisen due to the new generics implementation. See https://medium.com/flow-type/flows-improved-handling-of-generic-types-b5909cc5e3c5 for more information.
`./node_modules/.bin/flow` passes locally.
> Upgrade Flow to 0.141.0 (fixes issues with new generics)

- lib/MusicBrainz/Server/Controller/OAuth2.pm
- t/lib/t/MusicBrainz/Server/Controller/OAuth2.pm
As the ticket describes, the code verifier is not meant to be base64url-decoded during verification; the encoding when generating the verifier is only to transform the initial random octets into something URL safe. The encoded string is in fact the code verifier and not the initial random octets.
I fixed the automated tests and ran `prove -vl t/tests.t :: --tests Controller::OAuth2` to check the change.
> MBS-11313: Fix OAuth PKCE S256 verification

- root/edit/details/historic/AddTrackKV.js
This doesn't seem to make any sense, I assume it's either an error or a placeholder. At least in one case ([edit 8513870](https://musicbrainz.org/edit/8513870)) the track length originally shown here as 0 ms is shown as ?:?? when being edited in a further edit. See also [edit 8934453](https://musicbrainz.org/edit/8934453) (-1).
> MBS-11126: display track lengths of 0 ms or -1 ms as unknown

- lib/MusicBrainz/Server/Controller/Collection.pm
We were loading these for some but not others.
Also, remove duplicate load_meta calls.
> MBS-11285: Always load user ratings for collections

- lib/MusicBrainz/Server/Data/Alias.pm
The code always added the name of any entities being merged as an alias to the destination entity, with one exception: if the same name was already used as an alias for any other entity of the same type.
This probably dates back to when we only allowed each alias to be used once across the DB, but we stopped doing that ages ago. As such, the commit changes it to only skip adding the name as an alias if the destination entity *already* has that name as an alias.
> MBS-11183: Always preserve merged entity name as alias

- root/layout/components/sidebar/ReleaseSidebar.js
- root/layout/components/sidebar/SeriesSidebar.js
- root/statistics/stats.js
Unless I'm very wrong, l_attributes should basically never be called on its own, but as lp_attributes with the specific context. Some of these aren't even in the attributes context at all.
> MBS-11262: Fix l_attributes translation calls

- lib/MusicBrainz/Server/Controller/WS/2/Rating.pm
- lib/MusicBrainz/Server/Controller/WS/2/Tag.pm
- lib/MusicBrainz/Server/WebService/JSONSerializer.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/Authenticated.pm
Asking for this as JSON didn't error, but serialized the entity instead. This changes it so that you can actually query for the rating/tag as in XML.
Note this returns the rating in a 0-100 scale, while normally user-rating is returned on the 0-5 scale. This is inconsistent with the rest of MB but consistent with the XML version of this endpoint, so probably for the best.
Added tests and all since I was feeling responsible.
> MBS-11250 / MBS-11253: Properly support JSON user-rating / user-tags lookups

- lib/MusicBrainz/Server/Controller/WS/2/Release.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Recording.pm
- lib/MusicBrainz/Server/WebService/XMLSerializer.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupISRC.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelationship.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelease.pm
> MBS-11304: Add recordings’ first release date to release lookup

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
Since the pull request #1795 for MBS-11234 has been merged:
* WhoSampled `/cover` and `/remix` URLs are incorrectly accepted for artists and recordings;
* Error message is incorrectly referring to “release” instead of WhoSampled “album”.
* Deduplicate matching top level segment of path to safely handle extra `cover` and `remix` cases,
(and add corresponding tests)
* Fix error message for blocked URL,
* Refer to WhoSampled “tracks” (used in their pages) instead of “songs” (used in their sections),
* Improve formatting of error message.
> Beta: Amend #1795 (MBS-11234): Fix validating WhoSampled URL relationships

- lib/MusicBrainz/Server.pm
- lib/MusicBrainz/Server/Controller/Role/Delete.pm
- root/layout/components/sidebar/LabelSidebar.js
- root/layout/components/sidebar/RemoveLink.js
- root/types.js
Passing can_delete through $c.stash seemed like the most straightforward option, but open to other better possibilities.
> MBS-10830: Only show Remove link if entity can be removed

- lib/MusicBrainz/Server/Data/Series.pm
- root/static/scripts/series.js
While there's an obvious reason why you can't change the type of a series from, say, "Work series" to "Release series" once it has any items, there's no reason we shouldn't allow changing from "Work series" to "Catalogue", since both are series of works.
> MBS-8028: Allow editing series type to any with same entity type

- root/static/scripts/edit/MB/edit.js
- root/static/scripts/tests/release-editor/edits.js
We changed this in the main annotation form with MBS-4091 but the release editor doesn't use that code.
Tested manually, plus added test for it.
> MBS-11317: Avoid breaking annotation formatting in RE

- lib/MusicBrainz/Server/Controller/Release.pm
- root/release/discids.tt
We didn't use to show this, probably because IIRC  there was no indication at all of how a disc id's track times matched the medium's when applying the edit (so it made sense to force users to always go through the specific discID page). This has been changed though, so we can display the links here, the user can click them and then compare the durations on the next page. The user will still need to go through two pages to get all the info, but it makes the links easier to find (many people are unlikely to have realized you could do this by clicking the weird discid title).
> MBS-11268: Show "Set track durations" on release/discids

- lib/MusicBrainz/Server/Form/Field/OAuthRedirectURI.pm
- lib/MusicBrainz/Server/Form/Field/URL.pm
- package.json
- root/static/scripts/edit/externalLinks.js
- root/static/scripts/url.js
- yarn.lock
This was failing because, unsurprisingly, it couldn't find the ASCII hostname in the Unicode URL. I used punycode (which we already installed as a dependency, but I added as a requirement) to decode the punycode back into the original unicode URL for hostname comparison. 
During the last Monday meeting we also agreed to always display international URLs as Unicode (which we already did when prettifying but not in the links editor). This makes the relevant changes to externalLinks and to URL forms.
> MBS-9674: Support internationalized domains in URL forms

- lib/MusicBrainz/Server/Form/OtherLookup.pm
We remove all spaces when a barcode is pasted on the RE and store them without spaces. As such, we should do the same when a user pastes, say, " 9 78849 2540655" in the barcode search, so that the actual search submitted ("barcode:9788492540655") can find results.
Tested manually with the barcode above.
> MBS-11324: Trim input in the barcode otherlookups field

- lib/MusicBrainz/Server/Edit/Medium/Edit.pm
- t/lib/t/MusicBrainz/Server/Edit/Medium/Edit.pm
We generally make adding something where nothing existed an autoedit. I see no reason why this shouldn't also apply to adding a tracklist if it was previously unknown.
> MBS-11256: Make adding tracklist to empty medium an autoedit

- lib/MusicBrainz/Server/Edit/Release/Merge.pm
- t/lib/t/MusicBrainz/Server/Edit/Release/Merge.pm
If a release merge is going to merge recordings, we should also show those recordings as having pending edits, since otherwise it's easy to miss that they shouldn't be merged or whatnot separately.
> MBS-11111: Set edit_pendings on recordings merged with release

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
I looked at the most common misuses of these links on the release level and added errors rejecting them and telling the users to add them to the RG level (as we already did for the Wikipedia / Discography entry combo).
> MBS-11296 / MBS-11297: More blocks for Wikipedia/Wikidata at release level

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
YouTube Music links shouldn't be converted to YouTube links, since they're intended to be a different thing and, in some cases, are not available to anyone else to YouTube Music subscribers.
For now I'm not making them autoselect paid or free streaming, since most of them *can* be streamed for free with ads, but some are strictly limited to paid streaming only.
> MBS-11289: Stop autocleaning YouTube Music -> YouTube

- lib/MusicBrainz/Server.pm
This only occurred when approving from an edit page (e.g. /edit/123), not from an edit listing.
The issue is that while 69df512dc2c59af936a1291f0476e0acdf5d6aeb improved the security of `returnto` by preventing it from redirecting to external URLs, it did this by ignoring any URL with an authority set. We want to be a bit more lax and accept absolute URLs that point to musicbrainz.org or the current web server.
Tested the change manually on my mirror server.
> MBS-11328: Regression: Approving an edit redirects to home page

- lib/MusicBrainz/Server/Data/Release.pm
- lib/MusicBrainz/Server/Data/Role/IPI.pm
- lib/MusicBrainz/Server/Data/Role/ISNI.pm
- lib/MusicBrainz/Server/Data/Utils.pm
- lib/MusicBrainz/Server/Edit/Artist/Edit.pm
- lib/MusicBrainz/Server/Edit/Label/Edit.pm
- lib/MusicBrainz/Server/Edit/Relationship/Delete.pm
- lib/MusicBrainz/Server/Edit/Release/Merge.pm
- lib/MusicBrainz/Server/Edit/Role/IPI.pm
- lib/MusicBrainz/Server/Edit/Role/ISNI.pm
- lib/MusicBrainz/Server/Entity/EditNote.pm
- t/lib/t/MusicBrainz/Server/Edit/Medium/SetTrackLengths.pm
We generally allow auto-edits for everyone if data is being added where it didn't earlier exist. For some reason though we didn't make that check for IPIs and ISNIs. It makes sense to make the edit go into voting for cases where an IPI or ISNI already exists, but otherwise we should act in the same way as we do for other data.
We check whether an ISNI / IPI is already in use elsewhere, and block autoediting in that case. Whether the edit was otherwise autoeditable or not, ModBot will leave a note specifying that the IPI or ISNI is already in use in x artists / labels, and linking to a search to find out which (actually building the list for display on the edit turned out to be almost impossible with localized_note, so this is the best compromise I could find)
> MBS-10999: Make adding first IPI/ISNI an auto-edit

- lib/MusicBrainz/Server/Report/DeprecatedRelationshipReport.pm
This report is now full of BBC Music Page relationships, which are set to ended. As such, they have already been dealt with, so there's no point showing those in the report. In general, "ended" URL relationships should be considered effectively removed for most cases (since we don't show them on the sidebar and we grey them out elsewhere).
> MBS-11336: Don't show ended rels in DeprecatedRelationshipURL

- lib/MusicBrainz/Server/Edit/Release/AddCoverArt.pm
We store the original MBID, so we should use it. The TT used to use the original MBID straight from the data (not passing it to display data) for the filename display, but didn't use it for the actual cover art display, so that was broken. Passing the MBID to the Release->new call ensures both filename *and* image work.
> MBS-4782 / MBS-11333: Pass original MBID to AddCoverArt if no release

- root/cdtoc/set_durations.tt
This is currently confusing because it seems that there would be no changes at all if the edit was entered. In reality, it will cause sub-second changes, and we should specify that for clarity.
> MBS-11310: Clarify when discid would cause subsecond changes

- lib/MusicBrainz/Server/Entity/URL/Spotify.pm
- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
As per the URLs added to the tests, there's a lot more characters allowed in these URLs than just what we were limiting them to.
> MBS-11340: Allow more characters on Spotify user URLs

- lib/MusicBrainz/Server/Report/CDTOCDubiousLength.pm
- root/report/CDTocDubiousLength.js
Implement MBS-11346
The report (discIDs durations > 100 minutes) is now empty, Setting to 88 minutes to get more results and avoid too many false positive.
> MBS-11346: Lower duration threshold on dubious duration discID report

- lib/MusicBrainz/Server/Report/CDTOCNotApplied.pm
- lib/MusicBrainz/Server/Report/CDTOCReport.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/cdtoc/list.tt
- root/report/CDTocNotApplied.js
- root/report/ReportsIndex.js
- root/report/components/CDTocReleaseList.js
- root/report/types.js
- root/server/components.js
- root/static/scripts/common/components/CDTocLink.js
- root/static/scripts/common/utility/entityHref.js
Implements MBS-11348
Find un-applied discIDs on releases where applying them should be a no-brainer: some track durations are unset on the release, and only discID is attached to the relevant medium.
PR ready to be merged, I think
Please check  lib/MusicBrainz/Server/Report/CDTOCReport.pm  which is used by both  CDTOCNotApplied.pm and CDTOCDubiousLength.pm
I modified generateHref() and entityHref() to be able to build urls with anchors, I think there are no side-effects but of course I might be wrong.
A far as I know urls with anchors are used to highlight track rows in releases (and it was probably never used with react), and I wanted to be able to highlight release rows on cdtoc pages too.
This last part is not required for the report and the two commits can be removed if needed.
> MBS-11348: New report about discIDs attached to a medium but not applied

- lib/MusicBrainz/Server/Data/Artist.pm
- lib/MusicBrainz/Server/Data/Utils.pm
- lib/MusicBrainz/Server/Edit/Artist/Merge.pm
- t/lib/t/MusicBrainz/Server/Controller/Relationship/LinkAttributeType/Edit.pm
- t/lib/t/MusicBrainz/Server/Data/Editor.pm
- t/lib/t/MusicBrainz/Server/Data/ISWC.pm
- t/lib/t/MusicBrainz/Server/Data/LinkAttributeType.pm
- t/lib/t/MusicBrainz/Server/Edit/Artist/Merge.pm
- t/lib/t/MusicBrainz/Server/Edit/Medium/MoveDiscID.pm
- t/lib/t/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm
- t/sql/edit_artist_merge.sql
Artist merges can get stuck if their merged types and genders conflict: groups can't have a gender.
We now detect this case and drop any conflicting information. This is done as opposed to failing the edit because it's less annoying to the user. ModBot will leave a note explaining what information was lost.
This also handles the case where the target doesn't have a type or gender, but the resulting merged type & gender from the source artists would result in a conflict. In that case we drop both values and leave two notes.
> MBS-10187: "Merge artists" edit is stuck

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
Only “discography entry”, “license”, and “show notes” relationship types used to be blocked at release level because these were the most common. It doesn’t prevent adding Wikidata/Wikipedia using other free relationship types such as streaming and so on.
This patch prevents Wikidata/Wikipedia links from being added to release using any relationship type. Would it be allowed to in the future, a dedicated relationship type should be created in the meantime.
Edit a release, try adding links such as `https://www.wikidata.org/wiki/Special:EntityPage/Q14005` and  `https://en.wikipedia.org/wiki/MusicBrainz`. Selecting any relationship type should throw an error.
Edit an entity of any other type, adding the same links should auto-select the appropriate relationship type and be accepted.
> Prevent linking release to Wikidata/Wikipedia

- root/components/SelectField.js
Without this, cover art type can only be unset in an unintuitive way involving control-clicks. We used to have this, so we should readd it.
> MBS-11353: Allow empty row in multiple select

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
Forgot to allow for RGs in 9f56fea514cf49d2a276c5338c1961044d67d670
The difference between releases and RG links can't be determined from the URL as far as I can tell. Some include a dot (like in the test example) but some just append "_f1" or whatever to the RG URL.
> MBS-11357: Allow linking RateYourMusic to release groups

- root/static/scripts/alias/AliasEditForm.js
- root/static/scripts/edit/components/FormRowSortNameWithGuessCase.js
The backend already copies the name to the sort name if left blank, so this was never intended to be marked required here. Making required an optional boolean since we will want it to remain required for artist editing.
> MBS-11358: Allow alias sort name to be blank

- lib/MusicBrainz/Server/Controller/Role/Alias.pm
For some reason, the entity_name for release group is 'rg' in Controller::ReleaseGroup, despite its ENTITIES entry being 'release_group'. This seems very weird to me but it'd probably be a mess to change it now, so I just massage it into what the JS code expects instead so that the RG alias form will work.
> MBS-11360: Work around unconsistent name for RG type

- lib/MusicBrainz/Server/Edit/Medium/Edit.pm
Without this check Perl autovivifies the tracklists, leading to edits which show tracklist changes despite only changing the edit name.
> MBS-11362: Avoid autovivification leading to broken edit data

- root/layout/merge-helper.tt
returnto should be prefixed by ? not & since it's the start of the query parameters
> MBS-11363: Fix broken returnto in merge-helper.tt

- root/static/styles/layout.less
Detail table rows begin with colon-terminated headers which can easily wrap onto multiple lines. When this occurs, the value associated with the header (which follows in the next cell) can appear far above where the header ends when the value's cell is top-aligned, potentially making the value appear unrelated to the header and harder to parse than it needs to be.
Revert to the default theme's vertical alignment style for data cells which in most circumstances should more clearly delineate a row's values from any preceding or succeeding rows.
> MBS-11369: Revert to middle vertical alignment for table.details data

- lib/MusicBrainz/Server/Controller/Edit.pm
[MBS-9573](https://tickets.metabrainz.org/browse/MBS-9573): **_Search for Edits: Looses track of type criteria_** (2017)
In https://musicbrainz.org/search/edits **Type** criteria, edit type keys were not sorted:
**Edit release**:
- 201,32,312,33,208,273,226,244
- 244,273,32,201,312,33,226,208
- **random** at each page load
So the more legacy keys an edit type had,
The more likely query parameters found no match in the select option
values.
Now they are sorted, subsequent form submits will always work.
**Edit release**:
- 32,33,201,208,226,244,273,312
- predictive **numeric sort**
It is not necessay to numeric sort, so if `sort` is better, performance wise, than `sort { $a <=> $b }` we would be OK with:
**Edit release**:
- 201,208,226,244,273,312,32,33
- predictive **ASCII sort**
I no …
> MBS-9573: Sort edit type keys in edit search select option values

- root/forms/relationship-editor.tt
This was changed with 72ce47118a42097872d4a15bb2407e1c9d14c9b9 in a way that caused the arrows to always show for orderable relationship types. It used to only show once there were at least two relationships and the user selected that they wanted them to be ordered (hasOrdering). The old way seems more sensible to me.
> MBS-11354: Don't show arrows unless we want ordering

- root/edit/details/EditMedium.js
This used to work, but broke on React conversion because content is no longer a string, but a React element. The easiest way to do this seems to be to just compare the two names when calling EntityLink.
> MBS-11368: Set nameVariation in EditMedium if rec name != track name

- lib/MusicBrainz/Server/Edit/Historic/AddTrackKV.pm
- lib/MusicBrainz/Server/Edit/Historic/EditTrackLength.pm
- root/edit/details/historic/AddTrackKV.js
Same issue as https://github.com/metabrainz/musicbrainz-server/pull/1783 but on another edit type. I'm also moving that PR's check from JS to Perl.
> MBS-11370: display track lengths of 0 ms or -1 ms as unknown 

- root/static/scripts/edit/components/edit/ReleaseEventsDiff.js
- root/static/styles/edit.less
MBS-11369 changed the vertical align and in most places that's for the best, but release event diff tables are better with top align. Otherwise, a long list being turned into a small one (e.g. [edit #74086408](https://beta.musicbrainz.org/edit/74086408)) has the smaller value way down the page and makes understanding the change a lot harder.
> MBS-11375: Use top-align for release event tables in Edit release

- root/static/scripts/edit/externalLinks.js
Blocking all Google TLDs because the ones we currently have in the DB are from Google India and Google Italy, not .com
> MBS-10195: Block Google AMP links

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
The functionality added here will not work in IE11 due to the use of the `URL()` constructor, however it should fail gracefully and just return the original URL in such cases. I feel this is a reasonable compromise, as the functionality is not crucial and the alternative would be to implement a clunky regexp based parameter parser.
> MBS-10312: Remove tracking parameters from URLs

- root/layout/components/Footer.js
Suggestion was to make this "Chat" because it is more clear to new users. While that is probably true, other users might still search for "IRC", so I feel "Chat (IRC)" is short enough, clear enough for newbies and still useful for people who are searching for an IRC link.
I also re-ordered and slightly simplified the doc page it links to so that there's less to read before you figure out where to go to chat: https://wiki.musicbrainz.org/index.php?title=Communication%2FIRC&type=revision&diff=75211&oldid=74290
> MBS-10470: Rename "IRC" link in footer to "Chat (IRC)"

- lib/MusicBrainz/Server/Data/Editor.pm
This was just having two rows for release, so the second would end up overwriting $result{release}. Both lines should be summed up instead.
> MBS-11390: Sum, don't overwrite, added entity counts

- lib/MusicBrainz/Server/Controller/Series.pm
I just added the first place-series rel type, so we should show it.
> MBS-11397: Show place-series rels on series page

- lib/MusicBrainz/Server/Controller/Release.pm
- root/components/EntityTabs.js
- root/layout/components/sidebar/ReleaseSidebar.js
- root/release/CoverArt.js
- root/release/CoverArtDarkened.js
See commit messages for more details.
Darkened status isn't currently being updated properly (MBS-6567), but at least with this it will show up as it should once that is fixed.
> MBS-10343 / MBS-11394: Deal with darkened cover art

- lib/MusicBrainz/Server/Form/User/Register.pm
Trying to pass the default message through l() breaks it, displaying "Field should not exceed [quant,_1,character]. You entered [_2]". It also can't be translated anyway, since it's not exported to .pot files. So I'm adding a custom error message that can be used for text_maxlength for both password and username, which fixes the issue and should also allow translating it. It seems unneeded to have separate error messages just changing the field name, since these get displayed just under the relevant field anyway.
> MBS-10117: Fix broken maxlength password message on register page

- root/edit/details/EditMedium.js
- root/static/styles/edit.less
This matches the display on release tracklists. It used to be this way here too until commit 50c8156d829221d623eb1c045dcbde13f695baf4
> MBS-11389: Top-align edit medium Tracklist tables

- root/static/scripts/common/i18n/localizeLinkAttributeTypeName.js
type.root_id === INSTRUMENT_ROOT_ID on itself sends all instruments to be translated by l_instruments... but also the actual instrument parent attribute itself, since root_id = id in that case. But "instrument" needs to use l_relationships since it is not currently itself in the instrument context.
> MBS-11387: Use l_relationships for "instrument" attribute name

- lib/MusicBrainz/Server/Controller/Collection.pm
- root/layout/components/sidebar/CollectionSidebar.js
This also changes it so that entity_count is loaded by default for collections, which was already expected by CollectionT.
> MBS-10227: Display entity count on collection page

- lib/MusicBrainz/Server/Entity/CollectionType.pm
- root/admin/attributes/Attribute.js
Obviously the point of these was not to show "series_type" or "collection_type" for every row, but to show item_entity_type - what type of entities are allowed as part of the series or collection.
> MBS-11396: Show item_entity_type on Series/CollectionType admin tables

- lib/MusicBrainz/Server/Entity/URL/OCReMix.pm
- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
Validation is MBS-7674 but there's (old) discussion there about whether /remix pages should be freedownload instead. Will do that later once we have more feedback.
> MBS-9706: Normalize OCRemix URLs (including HTTPS)

- root/recording/RecordingIndex.js
This makes the table even more crowded, but only on demand, so it shouldn't be a problem - most users won't see it, unless they have done a Picard lookup, in which case it should be of use.
> MBS-10452: Implement tagger links for releases on recording pages

- lib/DBDefs/Default.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Role/GID.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Role/SameAs.pm
- t/lib/t/MusicBrainz/Server/Controller/Area/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/Area/Show.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/Recordings.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/Relationships.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/Show.pm
- t/lib/t/MusicBrainz/Server/Controller/Label/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/Label/Show.pm
- t/lib/t/MusicBrainz/Server/Controller/Place/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/Place/Show.pm
- t/lib/t/MusicBrainz/Server/Controller/Recording/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/Recording/Show.pm
- t/lib/t/MusicBrainz/Server/Controller/Release/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/Release/CoverArt.pm
- t/lib/t/MusicBrainz/Server/Controller/Release/Show.pm
- t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Show.pm
- t/lib/t/MusicBrainz/Server/Controller/Work/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/Work/Show.pm
These are documented as HTTP, formatted by Wikidata as HTTP, and as such generally expected to have this as the base.
> MBS-10004: JSON-LD MBID URIs should be HTTP

- root/edit/search_macros.tt
The options for edit_note_author shouldn't have the same name as for other user predicates, because while there can be only one edit editor, there can be multiple edit note authors. As such, "edit note author is not me" for example can be interpreted as "the edit has at least one note written by someone else than me" or (as it actually works): "the edit has no notes written by me". Same for other predicates, especially negated ones. I changed the header to plural because "Edit note author does not include X" seems kinda ungrammatical.
> MBS-11408: Clarify Edit Note Author edit search options

- lib/MusicBrainz/Server/Report/DeprecatedRelationshipReport.pm
This generalizes MBS-11336 to not only hide ended URL rels in DeprecatedRelationshipURLs, but also on all other DeprecatedRelationship reports. URL rels set as 'ended' are just kept for historical reasons, so we do not want people to remove them or change them.
Tested by running the reports again and comparing.
> MBS-11405: Don't show ended URL rels in DeprecatedRelationship reports

- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Role/SameAs.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/Show.pm
These are the IDs Wikidata itself uses for RDF / SPARQL, so it makes linked data usage a lot easier by avoiding the user
having to put the right URI together. They redirect to the standard page when loaded in the browser, so it shouldn't make things harder for data users otherwise.
> MBS-9987: JSON-LD: Use "Concept URI" for Wikidata

- root/artist/edit_form.tt
- root/components/forms.tt
- root/label/edit_form.tt
It's hard to explain these in a very clear way, but really the most important thing here is to tell users that no, they really don't need to freak out about not being able to fill these.
> MBS-9866: Add bubbles explaining what IPI and ISNI are on add forms

- root/static/scripts/alias/AliasEditForm.js
- root/static/scripts/common/components/Autocomplete2/reducer.js
- root/vars.js
Calling this imaginary function from a 'flow-include' comment will cause a switch statement to error if you haven't handled all possible cases. This is especially useful for reducer functions that have many possible actions.
See https://flow.org/en/docs/tips/switch-statement-exhaustiveness/
> Add Flow helper to check the exhaustiveness of switch statements

- root/static/scripts/guess-case/MB/GuessCase/Handler/Base.js
- root/static/scripts/guess-case/MB/GuessCase/Input.js
- root/static/scripts/tests/GuessCase.js
This adds support for most Unicode quotation marks, to avoid the word just after the quotation mark being lowercased.
> MBS-8232: Support more Unicode quotation marks in guess case

- root/artist/utils.js
The documentation says "Begin date represents the date (in real life) when the character concept was created." As such, "Created" is the best option for this, much better than "Begin date".
The docs also say "The End date should not be set", so no point setting a specific label for that.
> MBS-9884: Use "Created" for character-type artist begin dates

- lib/MusicBrainz/Server/Controller.pm
This got missed when we did the conversion, and .tt error templates no longer exist.
> MBS-11407: Make Controller->error use React errors

- root/static/scripts/guess-case/MB/GuessCase/Handler/Artist.js
- root/static/scripts/tests/GuessCase.js
There's no documentation about why this was done this way in the first place, but most likely it was because of pre-NGS artists which would have two or more different, full artist names as part of a collaboration artist name. This is fairly uncommon with NGS, while artists which just have "the" in their names (think "Tyler, the Creator") and where "the" should be lowercase are reasonably common.
I asked the community and most feedback suggested dropping this unexplained / unexpected difference between artist guess case and guess case for other entities.
> MBS-9836: Guess Case: stop uppercasing "the" in artist names

- root/static/scripts/edit/externalLinks.js
There's no reason I can see why we shouldn't block adding a http link if https exists already, and vice versa. I haven't seen any side effects of just making linkTypeAndUrlString normalize it.
Tested by both trying to add the two links from the ticket (http://www.example.com/path/object vs https://www.example.com/path/object) on artist creation and release creation, and by adding both to an artist (temporarily the code disallowing this) and then checking that they are detected as duplicates on loading the artist edit page once the code is changed back.
> MBS-10012: Treat http and https version of link as same for adding

- lib/MusicBrainz/Server/Data/Utils.pm
- lib/MusicBrainz/Server/Form/Field/Text.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/Create.pm
Allows the main PUA (U+E000..U+F8FF), but not any of the supplementary PUAs. This should at least cover the use case in the ticket (Klingon). If we want to be more restrictive, we could allow only (U+F8D0..U+F8FF) for Klingon, though there might be other use cases of the PUA that would be useful for MusicBrainz.
This commit also fixes an ISE that can be triggered by submitting a name consisting *only* of invalid characters. The message I added should very rarely be seen by any user; if they only enter whitespace, "Required field" is shown instead.
> MBS-10976: Allow some private use characters

- root/artist/ArtistIndex.js
- root/artist/ArtistRecordings.js
* Fixes a React key warning on the artist index page (in the `FooterSwitch` component) that's been spamming my logs, and probably the servers' logs.
* Moves the initialization of strings in this component to where they're used. Calling into Jed isn't free, and most of these variables end up unused on every request.
> Fix key warning in FooterSwitch, make small tweaks

- lib/MusicBrainz/Server/Controller/Release.pm
This was causing an issue where if a release doesn't have consecutive mediums, "disc/10" would load the 10th medium on the release, whatever its position, rather than the medium set to position 10.
Tested (with `pink` data) using the release given on the ticket. Alternatively, I guess you could add a release with 10+ mediums and ensure there's position gaps.
> MBS-11426: Use medium's position, not array position, to load it

- root/components/RelatedSeries.js
- root/components/Relationships.js
The only thing we want to avoid here is showing all the part-of-series rels on the page for every entity in a series. But for that there is no need to limit the rels shown to URLs - we have a perfectly effective `isNotSeriesPart` function we already use for series pages.
> MBS-9871: Display all useful series relationships in RelatedSeries

- root/static/scripts/common/components/Autocomplete.js
The basic flow leading to the issue is this:
* `this.setState` in `pasteArtistCredit` is called.
* `componentDidUpdate` is triggered on the artist Autocomplete.
* Since the artist changed, this sets the observable `autocomplete.currentSelection` to the new artist. This observable has a subscription, `this.props.onChange`, which updates the artist again on the parent (even though it already knows about this change).
The bit that screws up the credited name is the last point, because when the "duplicate" update winds up in `handleArtistChange`, it doesn't know about the credited name from the original update -- it thinks we're changing the artist only, so acts to keep the credited name in sync as it usually does.
We can avoid this by not re-attaching the observable subscription until after …
> MBS-11420: "Paste Credits" doesn't apply credited name

- root/components/PostParameters.js
We weren't accounting for arrays in PostParameters.js. Now we are.
Tested the change manually by seeding three types and observing that they were all selected. (If it helps, you can force the ConfirmSeed page locally by removing the `$c->is_cross_origin` check, then adding it back once you're ready to submit.)
> MBS-11424: Unbreak seeding multiple RG types

- lib/MusicBrainz/Server/Data/Edit.pm
- lib/MusicBrainz/Server/Data/Editor.pm
Reverts the following commits:
e3db4d5491c9a56f50193fd03dd67356a2c19db2
77f04ca1fe86dc53168139ef30c5b76f64bb3066
These changes were made to resolve the type of deadlock described in MBS-3597. However, there is no longer any `edits_accepted` column on the editor table; it's been dropped since f4fccd56ff930b0f0610c57d2b751541fe030132 and unused since before that. So there is no present situation I can see where the mere *creation* of an edit requires a lock on the editor row.
More discussion of the original changes can be found here:
https://web.archive.org/web/20140602202250/http://codereview.musicbrainz.org/r/2043/
I was able to reproduce the issue in MBS-11410 simply by setting the `statement_timeout` of my local database to something small, like '1s', and adding a `sleep(10);` to …
> MBS-11410: Remove row lock on editor table when creating edits

- lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
- lib/MusicBrainz/Server/Data/Utils.pm
- lib/MusicBrainz/Server/Form/Annotation.pm
- lib/MusicBrainz/Server/Form/Recording.pm
- lib/MusicBrainz/Server/Form/ReleaseGroup.pm
- lib/MusicBrainz/Server/Form/Work.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/Label/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/Recording/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/Release/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/Series/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
- t/lib/t/MusicBrainz/Server/Controller/Work/AddAnnotation.pm
MBS-10416: Annotation with some control characters cannot be indexed for search
Strip such characters (and other invalid characters) when entered in annotation.
1. Clean the 216 existing annotations having such invalid characters.
> MBS-10416: Remove invalid characters from edited annotations

- lib/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm
- root/edit/details/edit_release_label.tt
This is causing the new modifications not to get converted to JSON, causing an ISE. There's also no good reason to do this at all, since we can easily pass only the data we need via build_display_data and we even limit the amount of bandwidth needed while at it.
> MBS-11435: Don't modify data in build_display_data for EditReleaseLabel

- lib/MusicBrainz/Server/Controller/User/Subscriptions.pm
- lib/MusicBrainz/Server/Controller/User/SubscriptionsRole.pm
These used to be blessed collections but are now JSON, so {public} is JSON::true/false. Dereferencing it to see if true/false.
Tested by making one of my own collections private and making sure it matched prod (so you can test with `pink` data from http://localhost:5000/user/reosarevok/subscriptions/collection).
> MBS-11436: Don't try to call method public on unblessed JSON

- lib/MusicBrainz/Server/Entity/Role/Linkable.pm
68f8ae8a49aaa22e49c4982c0ecd0563f8e8dae4 broke this for obvious reasons. Since I'm not comfortable reverting that (I did run into a case where infinite recursion was triggered -- just not sure where), I increased the max allowed depth instead.
> MBS-11437: Beta: work-level rels not shown on release pages

- lib/MusicBrainz/Server/Entity/Area.pm
- root/static/scripts/common/entity.js
- root/static/scripts/common/i18n/localizeAreaName.js
The existence of iso_3166_1 (not the area having the country type) is what matters for whether we make the area name available for translation. As such, that's also what we should be checking for.
> MBS-11384 / MBS-11385: Ensure all country context names are translated

- lib/MusicBrainz/Server/Entity/EditorOAuthToken.pm
Adds the missing `to_json_object` call to `Entity::EditorOAuthToken`.
> MBS-11441: Beta: ISE on /account/applications

- lib/MusicBrainz/Server/Data/Utils.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/Label/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/Recording/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/Release/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/Series/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
- t/lib/t/MusicBrainz/Server/Controller/Work/AddAnnotation.pm
Since commit 43b9dd787947471b6dbddf15baf98947fe916d2c, blank lines were removed from edited annotations because `\s` matches `\n` too.
This pull request amends that commit by not removing consecutive `\n` but if there are more than two.
Update tests accordingly.
> MBS-11446: Keep blank lines in annotation

- lib/MusicBrainz/Server/Edit/Work/Create.pm
> MBS-11447: Use to_json_object on language in Work::Create

- lib/MusicBrainz/Server/Edit/Area/Edit.pm
This is checking $self->data->{new}{type} to see whether to run to_json_object on the type data, but the edit data does not have types, it has type_id from which the type is loaded for display.
> MBS-11470: Ensure to_json_object(type) does run in Area::Edit

- lib/MusicBrainz/Server/Edit/Release/EditCoverArt.pm
Passes the blessed `Release` object to `Artwork->new` as intended, rather than the unblessed JSON object.
> MBS-11468: ISE on "Edit cover art" edits

- root/main/index.js
Fixes MBS-11506 to point the MB 'data' link on the website home page from https://musicbrainz.org/doc/MusicBrainz_Documentation to https://musicbrainz.org/doc/MusicBrainz_Database.
> MBS-11506: Redirect 'data' link on home page

- root/static/scripts/edit/externalLinks.js
https://beny.trac.co/ seems to be a legit page, but https://beny.trac.co/benyslowmotion is effectively a smart link.
Since our implementation only blocks links with a subpath, it's fine to block this here, but adding a comment in case we eventually change the blocking method.
> MBS-11503: Block smart links: trac.co

- root/static/scripts/common/i18n/expand2react.js
A user bio repeatedly fails to parse because it has some irc:// links. Unless I'm missing some reason why these are a security risk, we should allow users to link to IRC, especially given we use IRC all the time.
User in question: https://musicbrainz.org/user/xps2
> MBS-11485: Allow irc(s):// links on expand2react

- root/static/scripts/release-editor/fields.js
If a release already had a too early format before the editor started this release editor session, `hasTooEarlyFormat` is still set. As such, these lines were blocking editing even in that case.
The whole point of having `hasUnconfirmedEarlyFormat` as well was for that to be the one that triggers an error, while just `hasTooEarlyFormat` should not. Compare `hasUnconfirmedVariousArtists` vs `hasVariousArtists`.
> MBS-11454: Don't consider hasTooEarlyFormat a blocking error

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
I'm removing the cleanup for the old artist format because it hasn't been used for years, so it seems useless by now.
Works are just like artists, and can be reduced to works/id.
Places require the country name on the URL, so they can only be reduced to venues/country/id.
> MBS-11432: Allow also linking places and works to Operabase

- root/release/edit/layout.tt
- root/release/edit/tracklist.tt
- root/static/scripts/release-editor/actions.js
- root/static/scripts/release-editor/dialogs.js
- root/static/scripts/release-editor/init.js
- root/static/scripts/tests/release-editor/dialogs.js
- root/static/styles/release-editor.less
- t/selenium/Artist_Credit_Editor.json5
- t/selenium/release-editor/Duplicate_Selection.json5
- t/selenium/release-editor/MBS-11156.json5
- t/selenium/release-editor/The_Downward_Spiral.json5
These can apply to mediums that are not discs. The pregap / data track strings only apply to actual discs, so not changing those for now.
> MBS-10726: Use "medium", not "disc", as a generic term in RE buttons

- root/static/scripts/edit/externalLinks.js
Normally it's not the editor's fault if someone before them has added a shortener link, MusicBrainz link, malware link or Google AMP link. As such, it feels unfair to force them to deal with the link before submitting their (unrelated) edits (plus the error messages all assume the link is newly added).
> MBS-11429: Don't error on existing but now blocked links

- root/static/scripts/release-editor/bindingHandlers.js
We were setting a title here, and then overwriting it with an empty string with the disableBecauseDiscIDs.update function. Obviously we want to keep the title if we don't need to overwrite it.
> MBS-11510: Stop overwriting titles in disableBecauseDiscIDs

- lib/MusicBrainz/Server/Controller/ReleaseEditor.pm
- root/static/scripts/tests/release-editor/seeds/title_is_0.html
- t/selenium/release-editor/Seeding.json5
These ifs were seeing any seeded string `'0'` as falsey and skipping seeding that field. This ensures the field is still not seeded when `_seeded_string` specifically returns `undef`, which I assume was the intended target of these checks.
> MBS-9543: Avoid false negative for string '0'

- entities.json
- lib/MusicBrainz/Server/Edit/Relationship/AddLinkType.pm
- root/edit/details/AddRelationshipType.js
- root/relationship/linktype/RelationshipTypeIndex.js
- root/relationship/linktype/RelationshipTypePairTree.js
- root/static/scripts/common/components/EntityLink.js
- root/static/scripts/common/utility/entityHref.js
For old enough edits this isn't doable since we do not store entity_id nor entity_gid. Starting 2015 we have that data, so it makes sense to link to the relationship type.
Many changes are indentation - I'd suggest hiding whitespace changes.
> MBS-9310: Link to relationship type in Add Relationship Type edits

- lib/MusicBrainz/Server/Data/CoreEntity.pm
- lib/MusicBrainz/Server/Data/EntityTag.pm
It makes sense to use sort names for sorting artists also in tag lists.
This changes get_by_ids_sorted_by_name to use sort_name for artists, but this seems to be used for tags only anyway. In any case, I don't feel the name becomes incorrect, since the sort_name column is just meant as "the way to sort artists by name" in the first place.
Tested with http://localhost:5000/tag/classical/artist / http://localhost:5000/user/reosarevok/tag/classical (`pink` data).
> MBS-11467: Use sort name to order lists of artists for tags

- root/static/scripts/common/components/TagEditor.js
Looking at the comment here, the original intention was to activate the autocomplete only if the user hadn't typed anything yet, but we never deactivated it once the typing started.
> MBS-11367: Disable browser autocomplete for tags when non-empty

- root/release/add_cover_art.tt
- root/release/reorder_cover_art.tt
- root/static/scripts/edit.js
- root/static/scripts/relationship-editor/generic.js
- root/static/scripts/release/coverart.js
- webpack.client.config.js
Surprisingly, this is due to some relationship editor code that's running. This shouldn't even be loaded on these pages, so I created a separate bundle for CoverArt.js. I also added a workaround in the relevant relationship editor code, just in case this affects other edit pages too.
> MBS-11442: Adding tags on add-cover-art page disables submit

- lib/MusicBrainz/Server/Controller/Edit.pm
- lib/MusicBrainz/Server/Data/Edit.pm
Unsurprisingly, this was giving an ISE. I think just showing all open edits in this case makes the most sense.
> MBS-11473: Don't try to filter open edits for user if logged out

- root/static/scripts/common/utility/isDateEmpty.js
- root/static/scripts/relationship-editor/common/fields.js
- root/static/scripts/tests/relationship-editor.js
I implemented MBS-11181 a bit too overzealously. If we add an ended relationship on top of one with completely empty dates, we should still overwrite it - otherwise it kinda makes the whole system useless.
> MBS-11373: Overwrite empty dates in relationship merges

- lib/MusicBrainz/Server/Data/Edit.pm
- t/lib/t/Edit.pm
- t/lib/t/MusicBrainz/Server/Controller/Edit/Open.pm
We already filter edits the editor has voted on, so obviously this is meant for voting. As such, it is useless to show open edits by that specific editor.
> MBS-11476: Don't show own open edits in /edit/open

- root/release/edit/tracklist.tt
- root/release/index.tt
- root/static/scripts/common.js
- root/static/scripts/release/index.js
- root/static/styles/release-editor.less
- webpack.client.config.js
Using `.collapse-medium` here broke because `common/MB/release` actually has code that runs on clicking a `.collapse-medium`.
For now, using `collapse-re-medium` / `expand-re-medium` to ensure a quick fix, but we shouldn't be running that code inside the release editor anyway, it's only relevant to a release's display page.
> MBS-11530: Avoid common/MB/release code running on these

- root/components/TagEntitiesList.js
If the user is in a downvotes page and clicks "See all works" or whatever, they are looking for all *downvoted* works.
> MBS-11525: Link to downvoted per-entity list when seeing downvotes

- lib/MusicBrainz/Server/EditSearch/Predicate/Role/User.pm
- root/edit/search_macros.tt
It can be very useful to find out edits where discussion of some sort is happening.
This operator will never apply to any other Role::User predicates than EditNoteAuthor, but I didn't find a way to add it only for that one - it's still only exposed for that one though.
Tested by searching and making sure all results seem legit.
Do let me know if you can think of a way to actually limit this to only EditNoteAuthor.
> MBS-9851: Allow finding edits w/ edit notes by not original editor

- lib/MusicBrainz/Server/Report/FilterForEditor.pm
_load was changed in 7984bf28dd29b2095b96d2263eacff29f5781d37 to take $c, but the load_filtered call wasn't updated and is ISEing.
> MBS-11531: Pass $c to _load in load_filtered

- lib/MusicBrainz/Server/Controller/Area.pm
- lib/MusicBrainz/Server/Controller/Artist.pm
- lib/MusicBrainz/Server/Controller/Event.pm
- lib/MusicBrainz/Server/Controller/Instrument.pm
- lib/MusicBrainz/Server/Controller/Label.pm
- lib/MusicBrainz/Server/Controller/Release.pm
- lib/MusicBrainz/Server/Controller/Series.pm
- lib/MusicBrainz/Server/Controller/Work.pm
https://tickets.metabrainz.org/browse/MBS-8807
https://tickets.metabrainz.org/browse/MBS-11538
Some tabs/sub-pages that contain sidebars and thus try to display collections have no collections data from the server, therefore display broken collection status (as if no collections, sort of).
- **Artist** missing collection data in **Subscribers** sub-page
- **Area** missing collection data in **Events** tab
- **Instrument** missing collection data in **Artists** tab
- **Label** missing collection data in **Subscribers** sub-page
- **Release** missing collection data in **Aliases** tab
- **Series** missing collection data in **Subscribers** sub-page
- **Work** missing collection data in **Aliases** tab
I found how it works, you have to list the tabs/sub-pages that contain sidebar to send …
> MBS-8807 / MBS-11538: Collections data missing in some sidebars

- root/static/scripts/release-editor/dialogs.js
- root/static/scripts/release-editor/fields.js
- root/static/scripts/release-editor/init.js
For cases where an existing empty medium is already present, present the track parser (rather than the Add disc dialog) if the user disables the "tracklist is unknown" checkbox, and don't overwrite the medium if using Add medium.
> MBS-11320 / MBS-11321: Don't add new medium if empty medium existed

- root/user/UserProfile.js
These links are already hidden for the Added entities section. Elsewhere they are shown, but they require log in on click - except for the last 24 hours link, which loads but drops the private info (user) and misleadingly shows all MB edits from the last 24 hours. I think just hiding these links unless the user is logged in is the most reasonable choice.
> MBS-11455: Hide view links on stats when logged out

- lib/MusicBrainz/Server/Controller/Report.pm
The previous patch for this (https://github.com/metabrainz/musicbrainz-server/pull/2021) stopped it ISEing, but was still passing the wrong args. Now everything should work.
> MBS-11531 (II): Pass $c to load_filtered call

- lib/MusicBrainz/Server/Controller/Role/Load.pm
- lib/MusicBrainz/Server/Data/Relationship.pm
- lib/MusicBrainz/Server/Sitemap/Overall.pm
Amends 12b43e8330b0feda64c636665735c7c3c931b7b5
Based on feedback, this increases the initial table size for each link type group from 25 to 100. Testing this against London Symphony Orchestra shows a ~1.67x slowdown from 2.193s to 3.664s.
The page size of the paged pages has been increased from 100 to 250. Testing against /artist/38712b4c-0fd4-4c65-8c7a-45676fecc973/relationships?direction=1&link_type_id=150&page=3 shows a slowdown of ~2.06x from 1.145s to 2.361s.
> Increase the default relationship page limit sizes

- root/components/RelationshipsTable.js
These need to be sorted by target type, otherwise the different sections jump around the page on every reload.
Tested and it seems to work - Flow hates this though, I need help fixing it. @mwiencek? :)
> MBS-11566: Ensure consistent ordering of appearances sections

- lib/MusicBrainz/Server/Edit.pm
- root/edit/CannotApproveEdit.js
- root/edit/CannotCancelEdit.js
- root/edit/NoteIsRequired.js
- root/edit/components/EditSidebar.js
- root/edit/components/EditSummary.js
- root/main/error/Error500.js
- root/static/scripts/common/utility/entityHref.js
- root/types.js
We were always expecting an ID, but edit previews don't yet have an edit ID. Since having separate types for edits and previews would probably be too complicated (many places use ...EditT and whatnot) we just make id possibly null and ensure we specify it is being passed where we use it and know for sure we are passing it.
Warning: 
`[warning] POST https://musicbrainz.org/ws/js/edit/preview caused a warning: Use of uninitialized value in addition (+) at lib/MusicBrainz/Server/Edit.pm line 330, <$fh> line 1.`
> Fix Catalyst warning: id is missing in edit previews

- lib/MusicBrainz/Server/Data/CritiqueBrainz.pm
CB supports rating-only reviews (without a review text). Those have an undef body, but we're still passing that through `markdown()`, causing warnings.
Warnings:
```
[warning] GET http://localhost:5000/release-group/cc053745-c447-3566-8f27-bed5438c9133 caused a warning: Use of uninitialized value $self in string ne at /home/reosarevok/perl5/lib/perl5/Text/Markdown.pm line 190.
[warning] GET http://localhost:5000/release-group/cc053745-c447-3566-8f27-bed5438c9133 caused a warning: Use of uninitialized value $text in substitution (s///) at /home/reosarevok/perl5/lib/perl5/Text/Markdown.pm line 270.
[warning] GET http://localhost:5000/release-group/cc053745-c447-3566-8f27-bed5438c9133 caused a warning: Use of uninitialized value $text in substitution (s///) at …
```
> Fix Catalyst warning: don't pass undef review text to markdown

- lib/MusicBrainz/Server/Data/Relationship.pm
12b43e8330b0feda64c636665735c7c3c931b7b5 added some caching for the number of relationships for a given entity & link type, so that we don't have to recount them on every page load. While that commit made sure to invalidate the cached entries on relationship updates and deletions, it forgot to do so for insertions. This commit does that.
> MBS-11563: Invalidate entity_link_type_counts on relationship inserts

- lib/MusicBrainz/Server/Controller/ReleaseGroup.pm
- lib/MusicBrainz/Server/Data/Artwork.pm
Tested with /release-group/2139ac67-3b29-4e1b-9568-2968f3ef38d6 - darkened status there is incorrect, as it was when we looked into https://github.com/metabrainz/musicbrainz-server/pull/1914, but it works for testing. We really need to also fix MBS-6567 soonish though.
> MBS-11581: Don't try to display / offer darkened art as RG cover art

- lib/MusicBrainz/Server/Edit/Release/AddCoverArt.pm
- root/edit/details/AddCoverArt.js
It's probably better not to pass the GID here (even though we have it stored) because the presence of a GID will cause the release to be displayed with a link that goes nowhere (since the release has since been removed).
Taking the GID off from the release passed to Artwork would also break the display of artwork and filename for removed releases. Given that the artwork for a removed release should have been removed itself (CAA-126), this is probably not a big issue, but just in case this passes a separate release entity with a GID to Artwork.
There's also no reason that I can see to form the filename on the edit itself rather than using artwork.filename, so I changed that to no longer depend on the release GID on display_data.
> MBS-11500: Do not pass GID of removed release to avoid linking

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
commons.nicovideo links are separate from the general nicovideo system and should not be autoselected as streamingfree (if they should be autoselected at all then probably as downloadfree, but that is an issue for a future PR). They also shouldn't be blocked, which is what the cleanup code was currently doing.
For now, this patch just makes the system ignore them so that they can be entered as needed.
> MBS-11564: Don't block Niconi Commons links with Nicovideo cleanup

- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Release.pm
Some top level formats (like SACD) have no parent format, yet don't appear on the medium format map since they aren't supported by the schema.org enum (https://schema.org/MusicReleaseFormatType). As such, we were trying to access the map with an undef parent format id.
> Fix Catalyst warning: ensure parent format id is not undef

- lib/MusicBrainz/Server/Edit/Relationship/Create.pm
Entities that haven't been created yet and are only being previewed lack both gid and id, but we were trying to use the result of gid_or_id to access a $loaded entry. That will never work and results in a warning, so this just makes sure to only do that if gid_or_id has a result.
Warning:
```
[warning] POST http://localhost:5000/ws/js/edit/preview caused a warning: Use of uninitialized value in hash element at lib/MusicBrainz/Server/Edit/Relationship/Create.pm line 184, <$fh> line 1.
[warning] POST http://localhost:5000/ws/js/edit/preview caused a warning: Use of uninitialized value in hash element at lib/MusicBrainz/Server/Edit/Relationship/Create.pm line 189, <$fh> line 1.
```
> Fix Catalyst warning: don't try using undef to access hash

- lib/MusicBrainz/Server/Edit/Relationship/Delete.pm
Some link types in edits only have entity0_type and entity1_type. In those cases, we shouldn't be using the nonexistent id field to access the loaded hash. It will never work + causes a warning.
Example edit: http://localhost:5000/edit/19292557
> Fix Catalyst warning: don't try undef linktype id to access $loaded

- root/static/scripts/guess-case/MB/GuessCase/Main.js
This is needed for alias sortname guessing, which just breaks completely otherwise. Also replacing the comment with something a bit more useful.
> MBS-11582: Add a sortname method for instrument guess case

- lib/MusicBrainz/Server/Entity/Artwork.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Utils.pm
- root/components/Artwork.js
- root/release/CoverArt.js
- root/types.js
- t/lib/t/MusicBrainz/Server/Controller/Release/CoverArt.pm
Seems the IA has triggered a reindex to get all 1200px thumbnails generated (see CAA-88), so it seems like a good time to add this.
I expect we still want large-thumbnail, not huge-thumbnail, in root/static/scripts/common/coverart.js for the thumbnail URL, but added it everywhere else we have thumbnails - including to data as huge-thumbnail in case userscripts or whatnot want to use it.
> MBS-9631: Add 1200px to available image sizes

- lib/MusicBrainz/Server/Controller/Collection.pm
- lib/MusicBrainz/Server/Form/Collection.pm
When creating a collection from an entity sidebar, we allowed selecting any collection type for it, even though an entity (of a specific entity type that might not match the collection type) was going to be added to it anyway.
This adds two blocks to that behaviour. First, it loads only the type values that match the entity type passed to the form.
Additionally, it only adds the entity that was seeded if the entity type of the final created collection is the same as the one originally passed to make sure there's no possible case we've missed where an entity would still get added to a collection of the wrong entity type.
> MBS-11569: Limit entity types when creating collection from sidebar

- root/components/list/RecordingList.js
This is probably using defaultContext since it doesn't have access to CatalystContext. It should only need SanitizedCatalystContext anyway, since that's all it has access to client side, so we just use the SanitizedCatalystContext to begin with.
> MBS-11583: Use sanitized context in hydrated component

- lib/MusicBrainz/Server/Constants.pm
- lib/MusicBrainz/Server/Entity/Editor.pm
- root/utility/sanitizedEditor.js
EditorT expects privileges to be passed, and there's no real reason why we shouldn't do this anyway.
> Pass public editor privs when converting editor to JSON

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
RA has over 500 entries on their RA Exchange podcast series, under /exchange (we have three of them in the DB right now). These shouldn't be blocked, and should autoselect to show notes.
Since we don't support autoselecting to two different types for the same entity, this excludes them from the main RA cleanup and adds a separate cleanup entry for them, to be merged with MBS-9902.
Additionally, made some more capturing groups non-capturing (noticed the issue because it caught me when originally adapting the RA cleanup).
> MBS-11546: Allow Resident Advisor /exchange URLs for releases 

- lib/MusicBrainz/Server/Data/URL.pm
- root/static/scripts/common/constants.js
There's only one residentadvisor.net URL left, and it is an ended biography page (so it won't be on the sidebar anyway). Everything else is now ra.co.
> Remove now unneeded old RA checks

- lib/MusicBrainz/Server/Controller/CDTOC.pm
When a user tries to attach an invalid CD TOC, just telling them that it is invalid isn't very useful. They probably didn't generate it themselves and have no idea what to do with this info. If they even report it then they're likely to report it to MBS, but it's most likely an issue with the software they used to generate the CD TOC in the first place. This makes the error message hopefully more useful.
Also, the /move action also had the same error message, but no CD TOC is provided to the action to begin with, just a (Medium) CD TOC id. Changed the error message to specify that the id is what is invalid.
> MBS-1588: Better errors for invalid CD TOC

- root/account/register.tt
- root/static/scripts/register.js
- root/static/styles/forms.less
- webpack.client.config.js
While a user should be able to use an email address string as their username if they so desire, they should only do it if they are sure it's ok with them for it to be public.
This adds a warning for that scenario.
> MBS-11571: Warn about e-mail as a username

- root/main/ConfirmSeed.js
- root/static/scripts/common/components/PostParameters.js
- root/static/scripts/confirm-seed.js
- root/static/scripts/user/login.js
- root/static/styles/forms.less
- root/user/Login.js
Hydrated components don't get translated unless they are under static/scripts, apparently.
.pot files also need to be regenerated.
> MBS-11550: Move PostParameters to static/scripts for translation

- root/edit/details/AddMedium.js
- root/edit/details/RemoveMedium.js
There seems to be no reason not to display exactly the same on removal edits as we do in add edits.
> MBS-11559: Specify tracklist is empty in Remove medium edits

- root/release/edit/tracklist.tt
- root/static/scripts/release-editor/trackParser.js
This covers the most basic bits of how to use the track parser, and can be toggled on and off with the same "(help)" link we use elsewhere in the RE.
> MBS-9259: Add help section for the track parser

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
They don't have trailing slashes in cases where they don't append names to the URLs (e.g. https://ocremix.org/remix/OCR00002) so it might be sensible to do the same.
This would probably cause the risk of duplicate links though, so we might want to do a MBBE cleanup if we merge this? :)
> MBS-11611: Do not keep/add trailing slash in OC ReMix URLs

- lib/MusicBrainz/Server/Controller/Genre.pm
- lib/MusicBrainz/Server/Data/Genre.pm
MBS-10830 stopped showing removal links on the sidebar unless the entity can be deleted, but genres didn't have a can_delete method. I could just hardcode genres to always pass can_delete true or skip the can_delete check for genres, but in case we decide to add blocks to deletion later, maybe it's better to just do this like for other entities.
> MBS-11612: Restore link to genre/delete to genre sidebar

- root/edit/details/AddCoverArt.js
- root/edit/details/RemoveCoverArt.js
RemoveCoverArt used to show '(none)' when either types or comment were blank. AddCoverArt used to show nothing for either case.
Arguably every cover art piece should have types, so them being missing is quite relevant to an AddCoverArt edit too. Having no comment is not really strange nor problematic. As such, this standardizes the display by not showing empty comments in either edit, and showing empty types on both.
> MBS-11590: Standardize display of empty fields in cover art edits

- lib/MusicBrainz/Server/Controller/ReleaseEditor.pm
- lib/MusicBrainz/Server/Data/ArtistCredit.pm
- lib/MusicBrainz/Server/Data/Utils.pm
- lib/MusicBrainz/Server/Edit/Generic/Edit.pm
This causes warnings once it gets passed to NFC. If $t is empty, I expect there's no need to do any of the sanitizing / trimming anyway, so we might as well just return it unchanged.
This is triggered at least by _clean_link_attribute with no credit or text value, but looking at logs, I think it's triggered elsewhere too.
> Fix catalyst warning: don't try to trim/sanitize undef "strings"

- lib/MusicBrainz/Server/Data/Editor.pm
- root/admin/EmailSearch.js
These are often used by spammers to get "new" emails for more accounts, since many providers (such as Gmail) allow to add periods and/or +tags to the address to create aliases for the same account. We don't want to fully block this (many people use email+musicbrainz@provider to receive their MB emails, for example) but it should be easy to find people using it for nefarious purposes.
Also made the results show up to the *newest* 100 editors that match, rather than the oldest.
> MBS-11619: Ignore periods and +tags in e-mail admin searches

- root/edit/search.tt
- root/edit/search_macros.tt
- root/edit/search_results.tt
This adds some help text to the top of edit searches that directs users to a how to page for using the search (in the works) and informs them that the searches can be bookmarked to save them.
> MBS-9376: Indicate that edit searches can be bookmarked + link docs

- lib/MusicBrainz/Server/Entity/Artwork.pm
- root/types.js
AFAICT this happens if the file has been removed from CAA. The thumbnails still work, at the moment, but I think that's just because of a bug where deleted images won't get purged from the IA.
This also removes a concatenation-with-undef Catalyst warning.
> MBS-11598: Do not generate image link if we don't have a suffix

- admin/sql/CreateViews.sql
- admin/sql/DropViews.sql
- admin/sql/updates/20200914-oauth-pkce.sql
- admin/sql/updates/20201028-mbs-1424-fks.sql
- admin/sql/updates/20201028-mbs-1424.sql
- admin/sql/updates/20210215-mbs-11268.sql
- admin/sql/updates/schema-change/26.slave.sql
- admin/sql/updates/schema-change/26.standalone.sql
- lib/MusicBrainz/Server/Controller/Release.pm
- lib/MusicBrainz/Server/Data/Medium.pm
- lib/MusicBrainz/Server/Entity/Medium.pm
- lib/MusicBrainz/Server/Entity/MediumCDTOC.pm
- root/release/discids.tt
- t/lib/t/MusicBrainz/Server/Controller/Label/Show.pm
- t/lib/t/MusicBrainz/Server/Controller/Release/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Show.pm
- t/lib/t/MusicBrainz/Server/Data/Medium.pm
- t/lib/t/MusicBrainz/Server/Entity/Medium.pm
- upgrade.json
This adds a view (MBS-11463) that allows us to access the durations of medium tracks without having to load all the data for every track in Moose.
Using this view, I re-implemented MBS-11268 (which seems to work fine now).
I also implemented MBS-11349 by replacing the complicated calculation of medium length based on either loaded tracks or discIDs with a calculation based on the values in this view.
A good place to test both of these seems to be http://localhost:5000/release/ab9e6f50-b248-4ed2-a591-1f175e609e44 (in the sample data).
NB: I wouldn't be surprised if there are some places where we loaded tracks or discIDs only to get medium durations, and if so those loads could now be removed. If you can think of any, do let me know! Guess there's no good way to find this programmatically.
> MBS-11268 / MBS-11349 / MBS-11463: Improvements related to medium duration

- admin/sql/CreateConstraints.sql
- admin/sql/CreateViews.sql
- admin/sql/DropViews.sql
- admin/sql/updates/20210507-mbs-11652-artist-series-fks.sql
- admin/sql/updates/20210507-mbs-11652-artist-series.sql
- admin/sql/updates/schema-change/26.slave.sql
- admin/sql/updates/schema-change/26.standalone.sql
- entities.json
- t/script/CheckSchemaMigration.sh
- t/sql/initial.sql
- upgrade.json
MBS-11652: Add support for artist series
Add `artist_series` view and appropriate series types (“Artist series” and “Artist award”).
1. Make updated WikiDocs pages visible on MusicBrainz website: https://musicbrainz.org/doc/Series
> MBS-11652: Add support for artist series

- root/collection/CollectionMerge.js
Whoops, my bad. I only renamed this on the Perl side, so unsurprisingly it does nothing. Found on test.mb.
> Fix partially renamed variable

- lib/MusicBrainz/Server/Controller/CDTOC.pm
These are usually only loaded with `load_for_releases`, but they are obviously also needed on the `/cdtoc` page for the `is_perfect_match` comparison to work.
> MBS-11676: Load durations for mediums on /cdtoc

- root/layout/components/ExternalLinks.js
- root/utility/isDisabledLink.js
We used to disable any link marked as ended, even if the end date was in the future. This doesn't make much sense, so I made it so isDisabledLink actually checks for the end date too.
This also uses isDisabledLink, rather than just ended, to decide whether to display a link on the sidebar. I think it makes sense that we would also explicitly stop showing any links marked with isGreyedOut on the sidebar, so it seems like a win-win.
> MBS-11643: Don't disable links that haven't ended yet

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
While the https variant of these links are available nowhere on the DNB site, they are the version provided by Wikidata, meaning that we will be getting these a fair amount and should avoid just blocking them as incorrect.
> MBS-11628: Accept and cleanup https "permalinks" for DNB

- root/static/scripts/release-editor/edits.js
There is at least one case where the edits.releaseGroup array is empty: when the release group has been renamed elsewhere after the editor opened this release editor session to the same name the editor is trying to apply here. As such, we try to access edit_type of an undefined edit. This just uses optional chaining to avoid that attempted call entirely.
> MBS-11630: Do not break on empty edits array

- root/static/scripts/guess-case/utils.js
- root/static/scripts/tests/GuessCase.js
Rather than fiddle with checkSpecialCase, which currently only works by overriding the entire track title, this just adds 'unknown' and 'untitled' to the list of words lowercased when in brackets (square brackets also count).
> MBS-11662: Lowercase untitled/unknown if in brackets

- root/static/scripts/edit/externalLinks.js
As the domain suggests, this seems to be just a link aggregator.
> MBS-11673: Block smart links to myurls.bio

- admin/BuildMaterializedTables
Right now, if one of the tables fails to build for some reason, you have to repeat the whole script again (instead of just specifying the ones that failed). This can be quite an annoyance, as I recently found out in the prod migration, because the tables take a long time to build.
This builds each table in a separate transaction, and defaults to the MAINTENANCE database to guarantee session-related settings (statement_timeout).
> BuildMaterializedTables: use separate transactions

- root/static/scripts/tests/utility.js
- root/utility/formatUserDate.js
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/hourCycle
This seems to have broken with the upgrade to Node v16.
(I've honestly never seen 1-24 before so don't know why that's a default for en.)
> MBS-11671: force hourCycle: 'h23' for %H in formatUserDate

- admin/ExportAllTables
- lib/MusicBrainz/Script/JSONDump.pm
- lib/MusicBrainz/Script/JSONDump/Full.pm
- lib/MusicBrainz/Script/JSONDump/Incremental.pm
- lib/MusicBrainz/Script/MBDump.pm
The production JSON dumps deployment currently hangs indefinitely with the following type of message:
> File '/tmp/mbscript-xxx/json-dump-xxx/MD5SUMS.asc' exists.
> Overwrite? (y/N)
This may be due to a gpg upgrade in the recent switch to Ubuntu 20.04.
To resolve this, for one, I'm adding `--batch --yes` to the gpg command to always overwrite existing .asc files.
Secondly, I'm fixing the code to not run `write_checksum_files` multiple times per dump.
> Fix double JSON dump gpg-signing

- lib/MusicBrainz/Server/Data/Editor.pm
- root/admin/EmailSearch.js
- t/lib/t/MusicBrainz/Server/Data/Editor.pm
Editor search by email (for admin) was failing at removing more than one period `.` from email search and addresses despite the `g` flag because it relied on capture group `()` that would be processed only once. That is why only one period `.` was removed from user info part.
This patch fixes it by splitting email over `@` symbol, for processing user info (removing `+suffix` and periods `.` used for aliases) and host name (not removing anything as these are not for aliases) separately, then contatenating both parts again using `||`.
It also requires admin to not include `+suffix` and periods `.` in user info parts of its regular expression search. This is because it is not possible to programmatically distinguish user info parts in complex regular expression that may include several user …
> MBS-11660: Fix ignoring several periods in admin search by email

- root/components/GroupedTrackRelationships.js
This extends the existing check to skip showing work parts to all other current work-work rels, in the direction that is irrelevant to the recording in question: if the recording is of an arrangement or medley we care about the original works, but if, say, this work has been arranged elsewhere, we don't care about that.
Note: the previous code only applied to the inline view of the release page (on bottom view the parts are currently shown, see https://musicbrainz.org/release/316ffa1c-0bd8-4a54-9bc8-c28da0e01bf1 for an example). We might want to do the same in both places (but I'd rather only implement it for bottom-credits once we convert it to React, to avoid duplicating the code).
If this seems sensible, we might want to do the same for MBS-7859 (the recording equivalent). I started …
> MBS-9419: Hide more irrelevant work rels from GroupedTrackRels

- root/report/components/ArtistUrlList.js
- root/report/components/LabelUrlList.js
- root/report/components/ReleaseGroupUrlList.js
- root/report/components/ReleaseUrlList.js
- root/report/components/UrlRelationshipList.js
On reports about URLs, it makes sense to always link to the URL entity (since that's where you can fix the problems). It still makes sense to have a link to the actual destination though.
At the moment UrlRelationshipList showed URLs in the same way as elsewhere on the site (destination link on click + [info] link to the entity) while the other lists being changed here only linked to the entity but did not allow following the link.
This makes both of these show both the URL link and a link to the URL entity (shown as the MBID), which allows visiting both links as needed without having to click the tiny info link that moves line by line depending on URL length.
> MBS-11337: Always link to URL entity page and link on URL reports 

- lib/MusicBrainz/Server/Controller/Relationship/LinkAttributeType.pm
- lib/MusicBrainz/Server/Data/LinkAttributeType.pm
- lib/MusicBrainz/Server/Data/LinkType.pm
- lib/MusicBrainz/Server/Data/Role/OptionsTree.pm
- lib/MusicBrainz/Server/Entity/LinkAttributeType.pm
- root/relationship/linkattributetype/RelationshipAttributeTypeIndex.js
- root/relationship/linkattributetype/RelationshipAttributeTypesList.js
- root/server/components.js
- t/lib/t/MusicBrainz/Server/Controller/Relationship/LinkAttributeType/Create.pm
- t/lib/t/MusicBrainz/Server/Controller/Relationship/LinkAttributeType/Edit.pm
- t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
There's no good reason why we don't have these, and it would be good if relationship-attribute/$gid wasn't an error.
If we have them, it makes sense to go to them and not the main list after creating or adding an attribute, so I made that change too, and linked to them from the attributes list.
On top of https://github.com/metabrainz/musicbrainz-server/pull/1451
> MBS-10107: Add overview page for rel attributes

- root/layout/components/BottomMenu.js
This was removed in ad98fdd6f9e3f11b524ef077a83a1b52ec9ed9d0 but neither commit, ticket nor PR have any explanation about why.
It makes sense to re-add it IMO as a clear pointer to what we do remove (birth dates, sometimes legal names) and what we do not remove (pretty much anything else). I reworded the linked page a bit to clarify that, see MBS-11657.
> MBS-10205: Readd link to the Data Removal Policy to the menu

- root/static/scripts/edit/externalLinks.js
- t/selenium/External_Links_Editor.json5
MBS-11688: The external link section will disappear once any link starts with //
Fix `isValidURL` to correctly validate links starting with "//"
> MBS-11688: The external link section will disappear once any link starts with //

- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Artist.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/Show.pm
The code used to squash all "member of" rels between a group and a person into one relationship for JSON-LD, whether that made sense or not (for example, it'd happily squash two relationships into "start date 2020, end date 2010").
We talked to Google people and they said they thought having one role entry per date set was better, so this code does that. We still group several relationships from the same date (to display "guitar, piano" together if the same member played both with the same dates).
> MBS-11371: Group members in JSON-LD by date, do not squash

- babel.config.js
- lib/MusicBrainz/Server/Entity/Event.pm
- lib/MusicBrainz/Server/Filters.pm
- root/event/EventIndex.js
- root/static/scripts/common/utility/formatSetlist.js
- root/static/scripts/tests/utility.js
This is only used on the React layer anyway (for display), and having it be JS will later make it easier to generate a preview client-side from a not-yet-submitted setlist (MBS-8085).
> MBS-11430: Convert format_setlist to Javascript

- lib/MusicBrainz/Server/Report/WorkReport.pm
- lib/MusicBrainz/Server/Report/WorkSameTypeAsParent.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/ReportsIndex.js
- root/report/WorkSameTypeAsParent.js
- root/report/components/WorkList.js
- root/server/components.js
There's plenty of cases where new users add every movement of a concerto (or sonata, or whatever) with the same type as the parent work.  That's pretty much never correct.
This shouldn't have many (if any) false positives from popular music, since part of work relationships are very uncommon there, and even then it seems unlikely that "Song is part of Song" is correct. We could always disable this for "Song" if needed, but that would also hide correct hits where someone has, say, selected "Song" for a parent "Song-Cycle" work so I'd rather avoid it unless users complain.
On top of #1787
> MBS-11290: Report of works of type X part of another work of type X 

- admin/sql/CreateFunctions.sql
- admin/sql/updates/20210606-mbs-11682.sql
- upgrade.json
`TRUNCATE` requires an `ACCESS EXCLUSIVE` lock on the target table. This means it will block on any concurrent operation on the table (which, for the `artist_*_pending_update` tables, means `INSERT` and other `TRUNCATE` statements).
A deadlock may occur as follows:
1. Txn 1 does `INSERT INTO artist_release_group_pending_update` (e.g. in the `a_del_release` trigger).
2. Txn 2 does `INSERT INTO artist_release_group_pending_update`.
3. Txn 2 does `TRUNCATE artist_release_group_pending_update` in the deferred "apply" trigger. This blocks on the `INSERT` from txn 1.
4. Txn 1 does `TRUNCATE artist_release_group_pending_update` in the deferred "apply" trigger. This blocks on txn 2.
5. Deadlock.
I'm resolving this by using `DELETE` instead, which I believe works because in this case it only …
> MBS-11682: Fix deadlocks in apply_artist_*_pending_updates

- lib/MusicBrainz/Server/Controller/Artist.pm
- lib/MusicBrainz/Server/Controller/WS/js/Recording.pm
- lib/MusicBrainz/Server/Data/Recording.pm
- root/artist/ArtistRecordings.js
- root/components/list/RecordingList.js
- root/static/scripts/common/components/ReleaseGroupAppearances.js
- root/types/recording.js
- t/lib/t/MusicBrainz/Server/Data/Recording.pm
https://tickets.metabrainz.org/browse/MBS-4826
https://tickets.metabrainz.org/browse/MBS-4881
A popular artist's recording list is usually a lot of the same name with only a length to differentiate them. This makes it so that the release groups each recording appears in are also shown, making it easier to figure out if they're different recordings (e.g. album vs live bootleg) or whether maybe they should be looked into for merging.
> MBS-4826: Show RGs for recordings in artist list

- lib/MusicBrainz/Server/Data/Search.pm
This reverts commit 6a49115d488c6de7c11f454981c5b8a101e0b913.
Rationale: Direct search queries frequently exceed `log_min_duration_statement` and spam our PG logs. I was trying to find out why, and discovered that the `OR name = ?` bits of the query cause a much slower plan to be used. Testing against an artist search, on the order of 2200 ms down to sub-300 ms with the condition removed.
Additionally, a condition like:
```
mb_simple_tsvector(name) @@
plainto_tsquery('mb_simple', mb_lower('姫咲ゆずる'))
```
still returns exacts matches for '姫咲ゆずる' or any other name I've tried.
The original commit message didn't provide any reasoning for this change, so since it has a very negative impact on performance, I'm reverting it.
> Revert "When doing a direct database search, also do an exact full text search too"

- lib/MusicBrainz/Server/Edit/Historic/RemoveDiscID.pm
- root/edit/components/EditNote.js
- root/types/edit.js
See commit messages. Both bugs apply on edit 531554.
> MBS-11700: Do not assume cdtoc_id exists

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
These three at least have the same format as standard Twitter usernames, but redirect to documentation pages. There might be more, these are the three I found right now.
> MBS-11696: Disallow Twitter documentation links

- lib/MusicBrainz/Server/Data/Relationship.pm
- lib/MusicBrainz/Server/Entity/Relationship.pm
- lib/MusicBrainz/Server/Entity/RelationshipLinkTypeGroup.pm
- root/components/GroupedTrackRelationships.js
- root/components/RelationshipsTable.js
- root/static/scripts/common/components/Relationship.js
- root/static/scripts/edit/ExampleRelationships.js
- root/static/scripts/relationship-editor/common/dialog.js
- root/static/scripts/relationship-editor/common/viewModel.js
- root/static/scripts/relationship-editor/generic.js
- root/static/scripts/tests/guessFeat.js
- root/static/scripts/tests/relationship-editor.js
- root/types/relationship.js
- root/utility/groupRelationships.js
- t/lib/t/MusicBrainz/Server/Controller/WS/js/Release.pm
We often need to know whether a relationship is backward (meaning: its target is entity0), and have a lot of `direction === "backward"` checks throughout the code. It would be much simpler to replace these with a boolean, as we don't support more than two directions anyway.
> Replace direction prop with backward

- lib/MusicBrainz/Server/Data/Search.pm
For some reason, while the other searches grouped to get the max rank, the release/recording/RG search did not - it selected distinct on all values, including rank. This leads to releases being returned several times if they appear on multiple rows with different ranks, messing up (for example) some cdtoc release search results.
Do let me know if there's a reason I'm missing why this *should* work differently - it seems it has worked like this since the start of direct search, so maybe there is a reason.
> MBS-11702: Group results also for release/recording/RG search

- root/edit/components/EditNote.js
`expand2react` is intended to expand our i18n syntax, so if it encounters a `{`, it expects it to be the start of a variable substitution. Edit notes are not translated strings; the HTML we're given from the server should be displayed as-is, so we should be using `dangerouslySetInnerHTML` here.
> MBS-11709: Beta: Edit notes with { show raw HTML

- lib/MusicBrainz/Server/Edit/Artist/Merge.pm
- lib/MusicBrainz/Server/Edit/Role/IPI.pm
- lib/MusicBrainz/Server/Edit/Role/ISNI.pm
- po/mb_server.pot
We were missing the appropriate no-op functions on some of these, so they were never extracted into the POT files.
The IPI/ISNI ones have to be done outside of the localized_note call because the way the plural string is passed doesn't match the function signature of N_ln.
I've regenerated the POT files so that you can see the changes.
> Wrap all localized_note strings in N_l or N_ln

- root/static/scripts/relationship-editor/common/entity.js
57263549bd0ec4e0b44756ac822c6dedaed4bad3 replaced direction with a boolean backward, but this still used a comparison with direction 'backward' / 'forward' instead.
> Fix getDirection -> isBackward to match other direction changes

- lib/MusicBrainz/Server/Controller/Relationship/LinkAttributeType.pm
- lib/MusicBrainz/Server/Data/LinkAttributeType.pm
- lib/MusicBrainz/Server/Edit/Relationship/AddLinkAttribute.pm
- lib/MusicBrainz/Server/Edit/Relationship/EditLinkAttribute.pm
- lib/MusicBrainz/Server/Form/Admin/LinkAttributeType.pm
- lib/MusicBrainz/Server/Plugin/FormRenderer.pm
- root/edit/details/AddRelationshipAttribute.js
- root/edit/details/EditRelationshipAttribute.js
- root/relationship/linkattributetype/form.tt
Since adding/removing free_text would probably make a mess of existing attribute uses, we disable that if the attribute is in use.
Same for removing creditable (since we wouldn't want to accidentally break existing attribute credits) - adding creditable should always be safe unless I'm missing something.
Tested by hand by adding and removing them locally from newly created attributes, and by trying to remove them from existing ones (Task should be in use in sample data).
> MBS-9695: Allow editing LinkAttributeType creditable/free_text via UI

- root/release/edit/recordings.tt
Apparently it's fairly common for editors to just create a new recording rather than reusing the existing one whenever the system unsets the previous recording for a duration change, since they do not realize that the listed (old) duration for the recording will get changed once their edit passes.
If you feel this is too TL;DR, I'd be happy to get better ideas - I'm not super happy with it but also not sure how to explain it more shortly.
> MBS-11342: Add message about track durations and recording reusing

- root/static/styles/layout.less
Exact same `padding: 0.2em 0.4em;` is already set on
[`table.tbl td`](https://github.com/metabrainz/musicbrainz-server/blob/ea59e1c57a1d66b57f3f14d4d96df957d666b9b0/root/static/styles/layout.less#L697) and [`table.tbl th`](https://github.com/metabrainz/musicbrainz-server/blob/ea59e1c57a1d66b57f3f14d4d96df957d666b9b0/root/static/styles/layout.less#L668) in this same `layout.less` file.
Remove it from [`table.tbl td.even td, table.tbl td.even th`](https://github.com/metabrainz/musicbrainz-server/blob/ea59e1c57a1d66b57f3f14d4d96df957d666b9b0/root/static/styles/layout.less#L728).
After this removal, as it's a redundant style, nothing changes in the display of odd/even table.tbl (tested on my local docker server).
I thought it would be good to clean this up.
> Remove redundant style

- lib/MusicBrainz/Server/Controller/CDTOC.pm
- root/cdtoc/move_search.tt
MBS-7473 / https://github.com/metabrainz/musicbrainz-server/pull/1387, but for moving rather than attaching a new CD TOC.
> MBS-11644: Allow specifying a release MBID when moving a CD TOC

- lib/MusicBrainz/Server/Constants.pm
- lib/MusicBrainz/Server/Edit/Historic/EditReleaseAttrs.pm
- lib/MusicBrainz/Server/Edit/Historic/Utils.pm
- lib/MusicBrainz/Server/Edit/ReleaseGroup/Create.pm
- lib/MusicBrainz/Server/Edit/ReleaseGroup/Edit.pm
- lib/MusicBrainz/Server/Entity/ReleaseGroupType.pm
- root/edit/details/AddReleaseGroup.js
- root/edit/details/EditReleaseGroup.js
- root/edit/details/historic/EditReleaseAttributes.js
- root/types/releasegroup.js
Old release group (and even older release) edits that involved one of the primary types that became secondary types with the NGS change were not showing the types, or even the change at all in some cases.
Luckily, we had a perfectly good map of type ids to names in the seemingly unused Server/Release.pm file, so I could use that to restore the information enough to actually display something useful.
I added the list to Server/Constants.pm since we might want to remove Server/Release.pm anyway, unless I'm missing something.
Just the types not having a gid seemed like a perfectly valid way of distinguishing these "mocked up" old types, so I haven't bothered trying to figure out any other option.
Testing edits, with pink data: edit/11088448 - edit/16294643/ - edit/8137486
> MBS-11697: Show historical primary types on old RG edits

- root/components/VotingPeriod.js
It's quite misleading to say "closes in 6 days" as soon as an edit is entered, given that it's really 6 days, 23 hours and 50-something minutes. Yes, we have a tooltip with the date, but still.
Instead of using floor, this uses round - it seems more sensible to say 7 days when it's more than 6 and a half, etc.
I start displaying hours once they hit 23 (rounded, so at 23 h and 30 minutes left), rather than still saying 1 day until there's only 12 hours left like elsewhere.
> MBS-9826: Show more realistic edit closing time overviews

- lib/MusicBrainz/Server/Data/Event.pm
It seems like the main use of an area events tab is to see what events are happening on that area - but most of those will be linked to places in the area, not to the area itself. As such, it makes sense to also show those.
Tested by visiting (using `pink`) http://localhost:5000/area/ad9aa625-4b82-47f2-b4a7-c467429fb31c/events (which had nothing listed before) and http://localhost:5000/area/74e50e58-5deb-4b99-93a2-decbb365c07f/events
At first I thought we should add a filter "only on this area" vs "everywhere", but we already don't have that for "only on this area" vs "on child areas", so not sure if it's needed at all.
> MBS-8070: Show Events in contained places in area events tab

- lib/MusicBrainz/Server/Controller/Area.pm
- lib/MusicBrainz/Server/Controller/Artist.pm
- lib/MusicBrainz/Server/Controller/Label.pm
- lib/MusicBrainz/Server/Controller/Place.pm
- lib/MusicBrainz/Server/Controller/Recording.pm
- lib/MusicBrainz/Server/Controller/Release.pm
- lib/MusicBrainz/Server/Controller/ReleaseGroup.pm
- lib/MusicBrainz/Server/Controller/Work.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Area.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Artist.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Label.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Place.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Recording.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Release.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/ReleaseGroup.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Role/Genre.pm
- lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Work.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/Show.pm
This uses only the genres on top_tags (so, the ones that would be displayed on the sidebar). This sounds sensible enough to me, since if someone has added 100 genres to an artist we probably don't want to show them all.
https://schema.org/genre specifically allows only Text or URL for genre, so I went with URL to at least be able to pass an MBID for it. Ideally we would serialize a genre object with ID and name, but that doesn't seem to be supported.
I've never knowingly touched JSON-LD stuff before, so do let me know if something here seems dumb :)
> MBS-8700: List genres in JSON-LD

- lib/MusicBrainz/Server/WebService/Validator.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRecording.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRecording.pm
Currently, you can do a query including recording-rels for an artist, or a work, but the returned related recordings will not include their artist credit. You also can't just add artist-credits to the inc, because the validator rejects that.
This isn't reasonable - it's perfectly legitimate to ask for artist-credits when requesting recording, release or release group rels, since all of those have artist credits.
> MBS-5680: Allow inc=artist-credits in combination with rels incs that have ACs

- lib/MusicBrainz/Errors.pm
- lib/MusicBrainz/Server/Controller/WS/js.pm
- root/static/scripts/edit/MB/CoverArt.js
Recently the "we don't own the associated item" message has been triggering for users when it's not true. This error can erroneously occur if the IA metadata API returns an empty response, which just means we need to wait for it to populate.  We can return a different message in this case asking the user to retry later, rather than the current, incorrect message.
While I was trying to debug this, I added some logging to Sentry which I've kept in case it's useful in the future.
> MBS-11737: Return different error if IA metadata is empty

- root/static/styles/entity.less
By using table-row / table-cell here, we allow the full dates to be selected easily by triple-clicking and we stop double-clicking on the year from also selecting the country code.
Solution suggested by @mwiencek.
> MBS-11744: Make it easier to mouse-select release dates in tables

- root/static/scripts/edit/MB/Control/ArtistEdit.js
It seems this broke during the conversion to React (MBS-11195), since the selectors changed. Tested, and this change seems to work both for collapsible and non-collapsible editor sections.
> MBS-11753: Fix selectors for RangeSelect in ArtistEdit

- lib/MusicBrainz/Server/Report/FeaturingRecordings.pm
- lib/MusicBrainz/Server/Report/FeaturingReleaseGroups.pm
- lib/MusicBrainz/Server/Report/FeaturingReleases.pm
These are currently skipping stuff like "Feat." and "Duet With". There seems to be no good reason for that - the guessFeat function, for example, is case insensitive.
> MBS-11773: Make "featuring in title" reports case insensitive

- root/static/scripts/release/components/MediumTable.js
- root/utility/mediumHasMultipleArtists.js
It's intended that we don't store or modify the medium itself in state, as this would lead to a lot of unnecessary updates due to how `React.memo` works.  We try to keep object references the same at all costs and only store the bits of information that actually change in state.
We weren't following this correctly with the `mediumHasMultipleArtists` call.  It was memoized based on the medium, but that reference doesn't change.  The tracks do, so modify the function to accept tracks and memoize based on that reference instead.
> MBS-11767: Show track-level artists on loaded mediums

- root/static/scripts/release/components/MediumTable.js
We used to have this before the React conversion, and it is used by some userscripts which don't really have a great substitute. This used to be in a div inside the td, but that div didn't seem to have any use other than it being easy to append with JQuery. Hopefully just having it on the td itself works as well.
> MBS-11776: Readd "loading-message" class to the medium loading message

- lib/MusicBrainz/Server/Entity/URL/CDJapan.pm
They seem to pretty consistently use CDJapan, with a couple exceptions that look like mistakes rather than them not caring, so we should do the same.
> MBS-11757: CD Japan -> CDJapan

- lib/MusicBrainz/Server/Report/WikidataLinksWithMultipleEntities.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/ReportsIndex.js
- root/report/WikidataLinksWithMultipleEntities.js
- root/server/components.js
Chose to implement one big report rather than one per entity because a common use case of this will be "same link for type: single RG and work", because of how WD works or used to work.
On top of https://github.com/metabrainz/musicbrainz-server/pull/1787 and https://github.com/metabrainz/musicbrainz-server/pull/1869
> MBS-11335: Report for reused Wikidata items

- root/components/GroupedTrackRelationships.js
- root/static/scripts/release/components/TracklistAndCredits.js
Expands MBS-9419 to also work with a release's bottom credits. Worth keeping in mind that there is another big difference this doesn't yet deal with - bottom credits display URL rels, while inline ones do not. Not sure whether those are desired or should also be dropped.
> MBS-11782: Hide more irrelevant work rels from release's bottom credits

- lib/MusicBrainz/Server/Data/Release.pm
- t/lib/t/MusicBrainz/Server/Data/Release.pm
- t/lib/t/MusicBrainz/Server/Edit/Release/Merge.pm
- t/sql/release.sql
If a release has two mediums, each with 1 track, and another has two mediums, one empty and one with 1 track, we should allow merging the empty one into the non-empty one. After all, that data doesn't mean the medium actually has 0 tracks, just that we don't have enough info about the tracks on that medium.
Merging the other way around (into the release with the 0-track medium) should still fail, but with a more explanatory error message.
> MBS-11614: Allow merging releases when a medium is empty

- lib/MusicBrainz/Server/Report/ShouldNotHaveDiscIDs.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/components/EntityTabs.js
- root/report/ReportsIndex.js
- root/report/ShouldNotHaveDiscIds.js
- root/server/components.js
Tested locally with sample data by changing hybrid SACD to not allow discids and then checking release/ca9de00b-3934-431b-809c-e07347f99801 and release/e7502670-ca88-4ec3-aa1b-eb5cba687d54
> MBS-11664 / MBS-11666: Enable discID tab for releases that wrongly have discids + add report

- lib/MusicBrainz/Server/Controller/Role/Load.pm
- root/components/RelationshipsTable.js
Sometimes a link to a specific relationship type group page might become outdated, if all relationships have been moved away from it. Right now, we just detach 400, which seems unfair - the request is not bad, there's just nothing to show.
> MBS-11711: Show informative error if no relationships in group

- lib/MusicBrainz/Server/EditSearch/Query.pm
- root/edit/search_macros.tt
I'm specifically excluding edits where the max is null, since those are very old anyway (so, generally irrelevant to a query for latest edit notes) but were sorting above the ones with dates.
I'm expecting this will time out on large queries, but that's already the case for a lot of edit searches. Seems to work, otherwise.
> MBS-11443: Add option to sort edits by edit note date

- lib/MusicBrainz/Server/EditSearch/Predicate/EditNoteContent.pm
- lib/MusicBrainz/Server/EditSearch/Query.pm
- root/edit/search_macros.tt
- root/static/scripts/common/MB/edit_search.js
This seems kinda-sorta slow but probably not insanely so (no timeout), and given we have no other way to do anything like it, users probably will be willing to wait a bit for results.
For an example of usage I could imagine, something like http://localhost:5000/search/edits?auto_edit_filter=&order=desc&negation=0&combinator=and&conditions.0.field=edit_note_content&conditions.0.operator=includes&conditions.0.args.0=fuck+you&conditions.8.field=vote_count&conditions.8.vote=0&conditions.8.operator=%3E&conditions.8.args.0=0&conditions.8.args.1= (on the mirror DB in pink) will show 12 edits that got downvotes *and* have edit notes including "fuck you", so would be useful for the community manager to review.
> MBS-8371: Add searching in edit notes to the edit search

- root/edit/details/RemoveReleaseLabel.js
- root/edit/details/edit_release.tt
- root/edit/details/edit_release_label.tt
These will always apply to the release currently being edited if seen as a preview. Changing these to show only if the edit is not a preview, matching what AddReleaseLabel already does.
> MBS-11747: Hide release details on edit preview

- root/static/scripts/edit/utility/guessFeat.js
- root/static/scripts/tests/guessFeat.js
I could add relatedArtists to ReleaseGroup in entity.js, but none of the artist relationship types seem relevant at all to a featured artist. Given we already have problems with this being overzealous elsewhere (MBS-10477), it seems sensible to be conservative here.
> MBS-11775: Do not break if relatedArtists is undefined

- lib/MusicBrainz/Server/Controller/User.pm
- lib/MusicBrainz/Server/Email.pm
- lib/MusicBrainz/Server/Form/User/Report.pm
- root/user/ReportUser.js
This allows a reporter to save a copy of the reports they have sent, if so desired. That might be helpful to, for example, remember if you have already reported a user recently but the report still hasn't been acted on, and as such avoid sending another report on the same issue.
Tested only by printing the email to be sent with Data::Dumper, since I don't have email sending set up locally. All of the headers seemed correct to me though. If any of you do have this set up, can you test the actual email sending?
> MBS-10367: Allow requesting copy of sent report when reporting

- root/layout/index.js
- root/static/scripts/common/banner.js
This uses a similar system as the birthday banner, but it shows on the editor's MusicBrainz registration anniversary (also known as "Cake Day" by Reddit people).
Since member_since is not a partial date, this is calculated in a somewhat different, more complicated way, but it seems to work just fine. It seems interesting to tell the editor how many years they have been with MB - I expect some will be surprised about how long it has been!
> MBS-11679: Wish editors a happy MB anniversary

- root/components/list/ArtistList.js
- root/components/list/EventList.js
- root/components/list/LabelList.js
- root/components/list/PlaceList.js
- root/components/list/RecordingList.js
- root/components/list/ReleaseGroupList.js
- root/components/list/ReleaseList.js
- root/components/list/WorkList.js
- root/utility/tableColumns.js
The ratingsColumn implementation was always expecting ratings to exist on the entity itself, but for release they exist only on the release group. As such, we need to change ratingsColumn into a function that allows passing an accessor to the appropriate entity that has the ratings.
This has probably been broken all the way since ff8bdcdc9a93682d27b49ebc5715f0571362bc80 :(
> MBS-11761: Properly display ratings on release lists

- root/static/scripts/edit/components/URLInputPopover.js
- root/static/scripts/edit/externalLinks.js
- root/static/styles/forms.less
- t/selenium/External_Links_Editor.json5
- t/selenium/release-editor/Seeding.json5
MBS-11391: Show changes made to external link when editing URL relationship
Implemented a popover for URL editing, which contains two fields - raw URL and clean URL.
Links aren't added to list automatically, users will have to press enter or let the input box blurred.
> MBS-11391: Show changes made to external link when editing URL relationship

- root/static/scripts/common/components/Autocomplete2.js
- root/static/scripts/common/components/Autocomplete2/reducer.js
- root/static/scripts/tests/autocomplete2.js
Fixes some issues I found while I was trying to figure out if MBS-11588 was an issue in Autocomplete2. Which I'm still not sure about, but that's a different question (@mwiencek, do you know the answer?).
> Autocomplete2 editor fixes

- lib/MusicBrainz/Server/Data/EntityTag.pm
For the general (not user-based) tag lists, there is no reason to show entities where the tag has a global count of 0 or less. That literally means the community *disagrees* that this tag applies to that entity.
> MBS-11808: Don't show tags in lists where vote count < 1

- root/utility/groupRelationships.js
As far as I can tell, this code was written for relationships that apply to one entity only (one recording, one release...). As such, there was never a need to check for more than "are the rels related, and are the attributes the same".
But this now also used for grouped display of medium relationships under a release, and that involves relationships from different tracks. Nothing in the code checked whether the tracks actually matched before they got combined - one of the sets of tracks
would just get dropped when combining the two relationship groups. This now makes sure that the tracks also match, if they exist, before allowing a merged display of the relationship.
> MBS-11806: Don't group relationships for different track sets

- lib/MusicBrainz/Server/Controller/Role/WikipediaExtract.pm
Obviously, if someone has marked a relationship as ended then we shouldn't be using that relationship to display an abstract - either it will not show anything, or it will show the wrong thing.
> MBS-11793: Don't fetch Wikipedia abstract when URL is ended

- lib/MusicBrainz/Server/Edit/Relationship/EditLinkType.pm
While the edit itself does not require a LinkType to exist (in the case of removed link types), the examples do. This adds a mock LinkType for that purpose.
> MBS-11802: Add mock LinkType for examples

- root/static/scripts/edit/components/GuessCaseOptions.js
- root/static/scripts/edit/components/GuessCaseOptionsPopover.js
- root/static/scripts/guess-case/MB/Control/GuessCase.js
- root/static/scripts/guess-case/MB/GuessCase/Handler/Area.js
- root/static/scripts/guess-case/MB/GuessCase/Handler/Artist.js
- root/static/scripts/guess-case/MB/GuessCase/Handler/Base.js
- root/static/scripts/guess-case/MB/GuessCase/Handler/Label.js
- root/static/scripts/guess-case/MB/GuessCase/Handler/Place.js
- root/static/scripts/guess-case/MB/GuessCase/Handler/Release.js
- root/static/scripts/guess-case/MB/GuessCase/Handler/Track.js
- root/static/scripts/guess-case/MB/GuessCase/Handler/Work.js
- root/static/scripts/guess-case/MB/GuessCase/Input.js
- root/static/scripts/guess-case/MB/GuessCase/Main.js
- root/static/scripts/guess-case/MB/GuessCase/Output.js
- root/static/scripts/guess-case/flags.js
- root/static/scripts/guess-case/modes.js
- root/static/scripts/guess-case/types.js
- root/static/scripts/guess-case/utils.js
- root/static/scripts/tests/GuessCase.js
The main goal of this is to add flow types to guess case, and fix any issues that surfaces, which I expect will be a bunch. Also fixing smaller eslint issues and whatnot as I see them.
> MBS-11805 (I): Flow types and refactoring for guess case code (first half)

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
The ticket specifically asked to disable /accounts which seems to have gotten added a bunch of times. Just in case I'm also disabled a few other internal links that I found with a quick check.
> MBS-11798: Disallow Instagram internal links

- lib/MusicBrainz/Server/Controller/Release.pm
- root/release/add_cover_art.tt
- root/release/reorder_cover_art.tt
While generally you can see the types and comment for a specific image when hovering over the image, that's not too clear in general and it doesn't help at all when the thumbnail hasn't been generated yet (since there's no image to hover over).
This adds an information icon that displays the data on hover, and also shows if there's no thumbnail yet.
Additionally, we weren't loading types for add_cover_art.
Sample:
> MBS-11267: Always show artwork info when adding/reordering

- root/static/scripts/statistics.js
This was only dealing with "even", but that meant that some rows ended up with both "even" and "odd" classes, while some that should be "odd" ended with nothing. This makes it all work more like the actual loopParity function, where you either have "odd" or "even".
> MBS-11861: improve loopParity classes for tablesorter

- root/components/relationship-editor.tt
- root/static/scripts/relationship-editor/common/dialog.js
This adds a bit of documentation about how to indicate a relationship happened in one day (or month/year) only and about the ended checkbox.
Only adding it to the relationship editor and not DateRangeFieldset since it seems mostly relationship specific (does not apply much to aliases, for example).
> MBS-2221: Add date docs to relationship editor

- lib/MusicBrainz/Server/Email.pm
This risks leaking the reporter id in the In-Reply-To: header value and is almost certainly not needed - it seems unlikely that the same editor will be reported twice on the same second, so reported editor id and timestamp seem more than enough.
No ticket because there's no particular need to advertise this.
> Remove reporter id from report message-id

- lib/MusicBrainz/Server/Entity/CoverArtType.pm
The Add Cover Art page currently uses a knockout form that is sorted by ID (notice CoverArtFields is display: none). The Edit Cover Art page uses the CoverArtFields display that is sorted by l_name. This is actually one of the rare cases where an ID sort seems preferable, since that ensures Front, Back and Booklet (the most relevant and common types) are sorted first whatever the language. As such, this forces sort by ID for the CoverArtType OptionsTree.
> MBS-11825: Use same order for art types when editing vs adding

- lib/MusicBrainz/Server/Controller/Edit.pm
- lib/MusicBrainz/Server/Controller/Relationship/LinkType.pm
- lib/MusicBrainz/Server/Data/LinkType.pm
We've historically just removed link types once we no longer wanted them used and they had 0 uses, but that is a bad idea. It means the historical edits automatically show less info, since there's no type to load anymore, and it's just an unwanted loss of historical data.
As such, this allows us to keep them in the database, but not show them except when there's something to gain from doing so: for type editing / documenting, and for the edit search.
> MBS-11862: Do not show deprecated relationship types with 0 uses

- root/layout.tt
- root/layout/components/Footer.js
- root/static/styles/layout.less
By following the same general style as in the header menu, adding color, making them bold and adding a bit more space between them, these links will hopefully stand out a bit more.
This also moves all the explanatory text for slaves/staging servers to the right paragraph to let the links stand alone on the left, although that shouldn't be a problem in production anyway.
> MBS-11850: Make footer links more visible 

- lib/MusicBrainz/Server/Data/LinkType.pm
- t/selenium/External_Links_Editor.json5
- t/sql/selenium.sql
This test broke with ec722a87b939d4d113e8b44ee1c5bb17c981f39c because MusicMoz, having zero uses, is now not shown for selection.
This adds one use for that to make sure it can still be found, and a description so that we don't need to artificially enable
the selector like we were doing.
It also adds one new link type which is deprecated and has zero uses, to test it doesn't show up at all.
> Fix deprecated link type tests

- root/components/GroupedTrackRelationships.js
- root/static/scripts/release/components/TracklistAndCredits.js
Similar to what MBS-9419 did for works, there's a lot of recording relationships that do not really have any relevance to a release display. For example, there's very little use to seeing every recording that mashes up the one on the release (potentially a huge list).
Tested with `release/dcb09143-f938-3381-bd4e-94034cc40d34` and `release/6c3cf9d8-88a8-43ed-850b-55813f01e451` as suggested on the ticket - I think I got all the relationship directions right, but feel free to double/triple check! :)
> MBS-7859: Hide irrelevant recording rels from release view

- lib/MusicBrainz/Server/Report/ReleasesWithAmazonCoverArt.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/ReleasesWithAmazonCoverArt.js
- root/report/ReportsIndex.js
- root/server/components.js
Since we want to drop Amazon cover art, this will help users ensure the albums they care about keep a front cover.
> MBS-11848: Add report for releases with Amazon cover art without CAA cover

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
When we decided to block these we didn't yet have a way to indicate why we were blocking it in the error message, but we specifically suggested in the forums we should add that info once it was possible. Then... we forgot about it. This adds that info.
I checked in case the situation got better in the meantime and we should allow the links instead, but it doesn't seem to be the case.
> MBS-11693: Give useful message when rejecting Musixmatch /album links

- HACKING.md
If I've understood this right, then we do not need to copy the DBs like this, but we can just run the create_test_db script with SELENIUM to create the appropriate DB.
> Update HACKING to create the SELENIUM DB directly

- root/release/edit/tracklist.tt
- root/static/scripts/release-editor/actions.js
- root/static/scripts/release-editor/bindingHandlers.js
Even when a user has closed (collapsed) a certain medium in the release editor, running a batch-change action such as global guess case or changing all matching artist credits still changes the track data for that medium. This can be very confusing, since the editor does not see the changes at all unless they either reopen the medium or pay close attention to the edit previews on the Edit Note tab.
As such, this changes the way those calls work so that they will ignore any medium that is collapsed at the time
the change is made. This was already the case for media which were never expanded in the first place, although that's only because there were no loaded tracks to modify. This only added to the confusion, since there is no good way to see at a glance whether a medium has been loaded …
> MBS-11811: Do not batch-change track data for collapsed media

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/edit/components/HelpIcon.js
- root/static/scripts/edit/components/RemoveButton.js
- root/static/scripts/edit/components/URLInputPopover.js
- root/static/scripts/edit/externalLinks.js
- root/static/styles/forms.less
- t/selenium/External_Links_Editor.json5
- t/selenium/release-editor/Seeding.json5
The current external links editor has the following drawbacks:
* It does not make obvious a URL can be pasted a second time to add another relationship type
* It is not easy to find if a URL has been pasted already (except when using the same relationship type)
* It requires double editing to change a URL having two relationships
* Error’s position is the same for both relationship type and URL, it isn’t always obvious which field must be edited to fix the error.
MBS-11680: Group editing URL relationships by external link
Implement a new UI for external links editor, where links with the same URL are grouped together, relationship types are shown under the URL as a list, and URLs are numbered for reference in error messages.
* Additional relationship can be added in two different ways:
* …
> MBS-11680: Group editing URL relationships by external link

- lib/MusicBrainz/Server/Report/FeaturingRecordings.pm
- lib/MusicBrainz/Server/Report/FeaturingReleaseGroups.pm
- lib/MusicBrainz/Server/Report/FeaturingReleases.pm
See commit messages. Tested by running the reports locally and comparing them.
> MBS-11824 / MBS-11833: Featured reports regex improvements

- lib/MusicBrainz/Server/Form/Role/UserProfile.pm
- root/static/scripts/account/components/EditProfileForm.js
Users are apparently often selecting "basic" when it seems incorrect, probably because it is selected by default. "Arabic" is also selected by default, and we seem to have 900+ users with "Arabic (basic)". This might be true, but I find it unlikely.
> MBS-11722: Don't preselect basic as language proficiency

- lib/MusicBrainz/Server/Controller/Admin.pm
- lib/MusicBrainz/Server/Data/Editor.pm
- lib/MusicBrainz/Server/Form/Admin/LockedUsernameSearch.pm
- root/admin/LockedUsernameSearch.js
- root/admin/LockedUsernameUnlock.js
- root/layout/components/TopMenu.js
- root/server/components.js
- t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
Tested locally by adding and deleting some accounts, then searching for / unlocking the appropriate usernames.
Search page:
Unlock page:
> MBS-11828 / MBS-9426: UI to find and unlock locked usernames

- root/static/scripts/edit/externalLinks.js
After MBS-11680, Enter key is used for submitting links in URL input box, hence users can no longer submit the form from external links editor when they only want to add a single link.
Redirect focus to the next item in external links list (either link or input), and prevent default onKeyDown handler only when the field is not empty, therefore users can follow the following steps to submit the form:
1. Paste a URL
2. Press Enter, this submits the link and jumps to the next empty input box
3. Press Enter again, the form is submitted
> Beta: Allow submitting form from empty URL input

- root/static/styles/layout.less
This was set to word-break: break-all to avoid long one-word tags such as weird URLs. That actually means all tags with normal words break weirdly. @mwiencek proposed overflow-wrap: anywhere to cater to both of these issues, and that seems to work - the only worry is that this is not supported in older browsers.
> MBS-11823: Don't break tags and genres mid-word

- root/static/scripts/edit/components/URLInputPopover.js
- root/static/scripts/edit/externalLinks.js
Long URLs in ExternalLinks and URLInputPopover cause text overflow and width change.
Update `overflow-wrap` to `anywhere` instead of `break-word`.
> Beta: Fix text overflow caused by long URL

- lib/MusicBrainz/Server/Controller/ReleaseGroup.pm
- root/release_group/ReleaseGroupIndex.js
Right now, there's no way to see if a release inside a release group has a different artist credit than the release group itself.
This adds a release artist column to that view. It also adds an "artist-credit-variation" class for cases where the release and release group artist credits differ, to help userscript users highlight that (matching what we do for track artists on recording pages).
> MBS-11846: Display release artist on release group view

- lib/MusicBrainz/Server/Report/ReleasesWithUnlikelyLanguageScript.pm
Braille is specifically meant to be used as a script for many languages and as such it shouldn't be considered as unlikely in combination with them.
> MBS-11875: Don't consider Braille an unlikely script

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
We shouldn't really autoselect-validate these; while we still don't have a streaming page for labels, this seems like a good indication we could use one. But this adds cleanup for now.
> MBS-11622: Clean up Apple Music label URLs

- lib/MusicBrainz/Server/Controller/User.pm
- lib/MusicBrainz/Server/Data/Editor.pm
- root/user/UserProfile.js
It seems interesting to see a sum of tags (up- and downvoted) and ratings for each user, if they are public (or the user's own). Ideally this could also show a count of CB reviews (MBS-11653).
Tested with `pink` data, logged in vs out, modifying preferences to make sure that works as it should. I can't guarantee this doesn't cause a slowdown though.
> MBS-11650: Add tag and rating statistics to profile page

- root/layout.tt
- root/main/index.js
Convert HTTP link to HTTPS.
Sorry for double commit. Couldn't find a way to edit multiple files into one commit from the GitHub website itself.
> MBS-11891: Use https when linking to jira

- root/static/scripts/alias/AliasEditForm.js
- root/static/scripts/edit/MB/edit.js
- root/static/scripts/edit/components/DateRangeFieldset.js
- root/static/scripts/edit/components/ExternalLinkAttributeDialog.js
- root/static/scripts/edit/externalLinks.js
- root/static/scripts/edit/utility/copyFieldData.js
- root/static/styles/forms.less
- t/selenium/External_Links_Editor.json5
Display date period next to relationship name, add a popover for setting begin and end dates of URL, enabling date period editing for entity edit pages other than URL.
> MBS-3774: Add URL with begin and end dates

- root/static/scripts/common/constants.js
- root/static/scripts/edit/components/FormRowSortNameWithGuessCase.js
- root/static/scripts/guess-case/MB/GuessCase/Main.js
Reverts the parts of 5f1b33c that removed the typeID, which is needed for person sort names to be guessed correctly.
> MBS-11890: Beta: Fix alias "guess sort name" for persons

- root/static/scripts/edit/externalLinks.js
Currently, link type update accidentally modified old links.
When updating link states, a cloned object should be used to avoid modification to the exising object in old links.
> MBS-11898: Beta: Can't change type of existing URL relationship

- root/release/add_cover_art.tt
I accidentally added these with 1b625f2903f2f82e680fd10cc6f636df07893aa8 but it doesn't do anything here.
> Remove useless arrows on add_cover_art images

- lib/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm
- root/edit/details/EditReleaseLabel.js
This hides "Date:" if there's no date at all to show (which was meant to happen already, but we were passing an empty string as the date in that situation), fixes a regression where we wouldn't show the label diff if the label was being removed (because it was detecting a new label being missing as the label just not changing), and fixes hiding the label and catno sections when they are empty, rather than just unchanged.
> Improvements to Edit Release Label edits

- root/components/UserAccountTabs.js
- root/user/UserProfile.js
We show a lot of general tabs on deleted users' profile pages (Subscribers and Collections always, and Subscriptions, Tags, Ratings unless the editor marked them as private before removal). We also show subscriber info on the profile index.
Deleted profiles should never have any of these things, so there's no reason to show them - they're just a potential source of wasted clicks.
> MBS-11924: Hide useless tabs / subscribers section from deleted profiles

- lib/MusicBrainz/Server/Edit/Historic/AddRelease.pm
- root/edit/details/historic/AddRelease.js
We already implemented this for AddReleaseGroup, so it makes sense to also make use of it in here, and it seems to work fine.
> MBS-11922: Show historical (now secondary) types for old Add Release edits

- lib/DBDefs/Default.pm
- lib/MusicBrainz/Server/Renderer.pm
- lib/MusicBrainz/Server/View/Base.pm
- lib/MusicBrainz/Server/View/Node.pm
If `RENDERER_SOCKET` is empty, MBS will now avoid communicating with the template renderer at all. This will prevent socket timeouts ("Couldn't connect to the renderer") from occurring if certain non-WS requests leak into our WS containers in production (as these containers don't have any renderer process).
A blank response is returned if this happens, because it's not an error that's even intended to be /allowed/ to be triggered normally (and I don't suspect anyone will use this flag outside of us), but I improved the logging to include the URL that triggered it. (You can already find which URLs are causing this in Sentry.)
> Allow disabling the template renderer

- root/layout/components/ExternalLinks.js
It makes sense to specify the credits for URL rels on the sidebar. On one hand, it helps find them to fix them when they are unwanted results from a merge. On the other hand, it shows the differences between, say, several Discogs pages for the same MB artist under different aliases.
For now, these credits can only be added when editing a URL or automatically through a merge, but I expect @y-young's work on better editing for URLs on the entity pages will make credits more available elsewhere too :)
> MBS-11799: Display "credited as" field in sidebar external links

- lib/MusicBrainz/Server/Report/LinksWithMultipleEntities.pm
I forgot these existed when I wrote the report, whoops.
> MBS-11932: Also exclude work licenses from LinksWithMultipleEntities

- admin/cron/daily.sh
- entities.json
- lib/MusicBrainz/Script/RemoveEmpty.pm
- lib/MusicBrainz/Server/Data/URL.pm
- t/lib/t/MusicBrainz/Script/RemoveEmptyURLs.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/EditExternalLinks.pm
- t/sql/url.sql
- t/tests.t
While most of these get removed with triggers, in some cases (e.g. having open edits) unused URLs can remain behind as orphans. This ensures the daily cron will remove them like other unused entities. Since we don't usually leave edits when URLs are autoremoved by triggers, we also don't create an edit here.
Tested by running it locally and seeing it did remove one URL (in test data but it might have been one that I accidentally orphaned), at least. It did not remove the URLs I just inserted to test, which makes sense because it does have a "last_updated over a day ago" check...
> MBS-9454: Autoremove unused urls with daily.sh

- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/AnnotationsEvents.js
- root/report/ReportsIndex.js
- root/report/components/EventList.js
- root/report/types.js
- root/server/components.js
AnnotationReports already supported this, even, but for some reason we didn't have it yet. Not sure how useful these annotation reports actually are, but we should make them consistent at least.
> MBS-11843: Add report for "Events with annotations"

- lib/MusicBrainz/Server/Controller/WS/2/Release.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/BrowseRelease.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseReleases.pm
- t/sql/webservice.sql
I can see no reason why we would prefer users to make one extra call per release rather than requesting this via browse when they need it. Recording already supports work-level-rels in browse, too, so this adds consistency.
Added tests too.
> MBS-6140: Allow (recording|work)-level-rels for release browse

- lib/MusicBrainz/Server/Controller/WS/2/Release.pm
- lib/MusicBrainz/Server/WebService/WebServiceInc.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelease.pm
- t/sql/webservice.sql
This is particularly useful to know if a release's release group is part of a release group series.
On top of https://github.com/metabrainz/musicbrainz-server/pull/2173
> MBS-8098: Allow release-group-level-rels in release lookup

- root/artist_credit/ArtistCreditLayout.js
- root/report/components/ArtistCreditList.js
- root/static/scripts/common/components/ArtistCreditLink.js
- root/static/scripts/common/components/ArtistCreditUsageLink.js
- root/static/styles/tooltip.less
This only shows it when requested, since it doesn't make sense everywhere `ArtistCreditUsageLink` is used (such as on every tab of `ArtistCreditLayout`.
@mwiencek: there's an issue here where `Tooltip` is inside the `h1` for the `ArtistCreditLayout` header, meaning the text in the tooltip is also at h1 size and doesn't really work well. This seems like a more widespread issue with `Tooltip`, in that it probably doesn't make sense that it takes on the style of its container. What do you suggest for this? A `tooltip` class that overrides it?
Specifically added to `artist-credit/$id` (on the header) and `report/ArtistCreditsWithDubiousTrailingPhrases` (and any other AC reports)
> MBS-11717: Also show edits pending in ArtistCreditUsageLink

- root/artist/ArtistRelationships.js
- root/components/Relationships.js
- root/label/LabelRelationships.js
For an artist that only has event relationships (or, I assume, a label that only has relationships of a type that gets filtered out by groupRelationships), the relationships tab is currently just empty.
This changes it so that Relationships displays an informative message if all existing relationships have been filtered out. While at it, I also got rid of the separate "no rels" message on ArtistRelationships and LabelRelationships, and moved that to Relationships as well.
Tested locally by creating the appropriate situations (artist without any rels, artist with only event rels) and navigating around to see that the changes didn't seem to affect other relationship displays.
> MBS-8820: Show explanation if relationships tab shows no rels

- lib/MusicBrainz/Server/Controller/User.pm
- root/user/UserProfile.js
As an admin, it's useful to know how an account has been used before deleting it. If no oAuth authorizations nor applications exist, then there's no worries that deleting it might cause issues elsewhere nor that there's spam somewhere else we have not yet seen.
Ideally we would also link to the user's BB, LB and CB profiles, at least, but right now that's not trivial at all since for example BB does not currently allow finding users by MB username nor MB user id.
> MBS-11819: Show to admins whether account has oAuth uses

- root/entity/Subscribers.js
- root/static/scripts/common/utility/isSpecialPurpose.js
While special entities don't show the subscribers link on the sidebar, it's still possible to navigate to /subscribers manually. There, a "Subscribe" link that did nothing could be found.
This makes it so that entities that do not support subscribing just state that on that page instead.
NB: A lot of the changes here are just extra indent.
> MBS-11130: Clarify it's not possible to subscribe to VA / [no label]

- admin/BundleSearchIndexesDump
- admin/RunJSONDump
- admin/RunSearchIndexesDump
- lib/DBDefs/Default.pm
- lib/MusicBrainz/Script/MBDump.pm
To compress JSON dumps (using `xz`) and search index dumps (using `zstd`), the number of threads is currently not limited so dumps can be made available faster. However, it now has detrimental impacts to the server’s availability when dumps are built.
This patch adds the key `DUMP_COMPRESSION_THREADS` to the configuration so it can be changed at deployment time. It doesn’t change the default though.
1. Set the value for `DUMP_COMPRESSION_THREADS` key to `4` in docker server configs for both `musicbrainz-json-dump` and `musicbrainz-search-indexes-dump`.
> Allow limiting compression threads from config

- root/static/scripts/edit/externalLinks.js
Without this, the seeded URL is stored and can be submitted, but it does not get displayed to the user, which seems less than ideal.
On a second commit, I make it so seeded links always come after existing ones.
Tested with the seeding options suggested on the ticket, plus with a couple extra links (just the URL, just the type) to make sure multi-seeding works.
> MBS-11960: Also assign seeded URL to rawURL

- lib/MusicBrainz/Server/Entity/EditNote.pm
- root/edit/components/EditorTypeInfo.js
- root/types/edit.js
When trying to approve an edit with a No vote + note, we load edit notes for the edit (to see if one of the editor_ids matches the approver's) but we do not load the actual editors themselves.
On doing TO_JSON for edit when passing it to NoteIsRequired, we were (correctly) running to_json_array on the edit notes, and this was running TO_JSON directly on the note's editor, which, of course, had not been loaded. This changes it to run to_json_object, which is smarter and actually ensures TO_JSON can be called before calling it.
To test, create an open edit with one editor, vote No and leave a note with a second editor, and then try and approve the edit with a third editor. Of course, editor 2 will need to be allowed to vote/leave notes (so, not a beginner) which can be annoying to trigger …
> MBS-11852: Only call TO_JSON on editor if it exists

- lib/MusicBrainz/Server.pm
https://tickets.metabrainz.org/browse/MBS-11970
While we are currently following what https://developers.google.com/recaptcha/docs/faq#im-using-content-security-policy-csp-on-my-website.-how-can-i-configure-it-to-work-with-recaptcha says to use, at least one person couldn't register an account because https://www.recaptcha.net/recaptcha/ isn't whitelisted, and the FAQ says in a separate answer to "please use 'www.recaptcha.net' in your code in circumstances when 'www.google.com' is not accessible."
> MBS-11970: Add recaptcha.net to script-src CSP

- root/edit/search_macros.tt
This just does not select any sort when the 'rand' order is selected.
PSQL docs used to say "If sorting is not chosen, the rows will be returned in random order" but that's misleading and has since been corrected to "the rows will be returned in an unspecified order". For at least some queries, the unspecified order is literally "ordered by ID", which means people will be confused about the clear non-randomness.
Actually making this random seems to have little use, and makes things very slow (see https://github.com/metabrainz/musicbrainz-server/pull/2043). Since the most useful thing about the current option is that skipping sorting sometimes makes things quite a bit faster, this just renames the option to be less misleading.
> MBS-11961: Rename "random" in edit search since it's not random

- lib/MusicBrainz/Server/Data/Language.pm
- lib/MusicBrainz/Server/Edit/Work/Create.pm
- lib/MusicBrainz/Server/Edit/Work/Edit.pm
- root/edit/details/AddWork.js
- root/edit/details/EditWork.js
- root/static/scripts/common/MB/Control/Autocomplete.js
- root/static/scripts/common/components/Autocomplete2/formatters.js
- root/static/scripts/common/components/WorkListEntry.js
- root/static/scripts/common/i18n/localizeLanguageName.js
- root/utility/tableColumns.js
This was causing issues when both work and release edits were being loaded, in that releases would appear with the language
[No lyrics]. Now that all relevant edits are React anyway, there's no need to massage the work on the Perl level at all. Instead, this just passes the languages (rather than their names) to JS and lets localizeLanguageName change the displayed name only.
Tested this by visiting add work / edit work edits, work searches, artists' work pages.
I didn't change the calls for l_languages for release/stats stuff right now, although I guess we could if that seems more consistent / better :)
> MBS-10902: Stop changing zxx language name at the Perl level

- lib/MusicBrainz/Server/Data/Recording.pm
This is needed so that RGs with pending edits are actually highlighted as such on the ArtistRecordings page. I can't imagine it will make things particularly slower.
Tested manually by opening edits in one RG in sample data and checking it was highlighted in the relevant artist's recordings tab.
> MBS-11973: Also load edits_pending for appears_on

- lib/MusicBrainz/Server/Controller/Role/Alias.pm
We already do this for add_alias and edit_alias, but I guess we forgot to do it for delete_alias, and that is causing an error when loading the layout on React.
Why we use "rg" I don't know, but in any case it seems sensible to have all of these work until we maybe decide to change it.
> MBS-11989: Also correct rg to release_group for delete_alias

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
This ensures the permalinks to Worldcat identities pages include the ending slash, since that's their default.
Additionally, wcidentities pages get converted into identities pages (as far as I can tell they are both the same content with a slightly different design).
> MBS-11941: Normalize Worldcat identities URLs

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
Twitch allows both but automatically redirects. We had 5 of these in the DB right now, which I fixed by hand (including the test example).
> MBS-11957: Clean up twitch.com to twitch.tv

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
Since RYM doesn't seem to otherwise have recording level data, this specifically limits recording links to music videos (which have recently been added).
> MBS-11959: Allow RYM links for music video recordings

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/edit/externalLinks.js
MBS-11977: Mismatched entity type in external links editor doesn't trigger the appropriate error message
(see the ticket for details)
Fix targeting `ENTITY` for URL relationship error.
It also required adding a generic error message for `ENTITY` error target (which was associated to custom error message only so far).
Further improvement would be to specify which entity type should be linked to the entered URL, and which URL pattern would be suitable for the current entity, as proposed in “Implementation notes” of the ticket. Actually, it is probably worth a separate ticket.
> MBS-11977: Fix targeting ENTITY for URL relationship error

- lib/MusicBrainz/Server/Entity/URL/CDJapan.pm
- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
CDJapan has detailview.html URLs that seem to just redirect to the product ones, but have been added a few times and are not currently detected at all by the code. This changes the CDJapan autoselect to detect them and clean them to their final product page form.
Since this takes care of the only kind of http URLs we still were getting for CDJapan, it should be safe to remove the http override too (existing ones are being fixed by hand).
> MBS-11975: Clean up CDJapan detailview URLs

- root/static/scripts/edit/externalLinks.js
MBS-12000: "This URL is not allowed for works." when trying to add a Napster (track) URL to a release (single)
Switch case fall-throughs introduced in MBS-11977 (#2280) cause all error message to be 'This URL is not allowed for works.'
Add `break`s to all cases.
> Beta: MBS-12000: Fix error msg for incompatible entity

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
It's not fully clear to me whether these can only be purchase for mail order, can also be a download, or maybe even more options, so for now this just avoids cleaning them up / selecting any specific type for them
> MBS-11981: Don't break Ko-fi shop URLs get in URL cleanup

- root/static/scripts/edit/externalLinks.js
- t/lib/t/MusicBrainz/Server/Controller/RelationshipEditor.pm
- t/lib/t/MusicBrainz/Server/Controller/URL/Edit.pm
- t/lib/t/MusicBrainz/Server/Data/CoverArt.pm
- t/lib/t/MusicBrainz/Server/Data/URL.pm
- t/selenium/External_Links_Editor.json5
MBS-11979: The previous example `google.com` was a valid URL but search pages are not actually wanted to link to any MB entity.
This patch replaces it with `example.com` to get rid of this ambiguity in both editing UI and tests. It also tries to improve the phrasing and the formatting.
> MBS-11979: Improve example URL

- root/layout/components/sidebar/SidebarTags.js
We already hid these when logged in, but we were not filtering them out at all when the user is logged out and we simply use `TagList`.
Tested by hand with Ed Sheeran, which has some tags with 0 votes such as 'ed sheeran does not make sillyname tracks ಠ_ಠ'' which were still showing on the sidebar.
> MBS-12019: Do not list downvoted tags on sidebar when logged out

- root/static/scripts/guess-case/modes.js
- root/static/scripts/tests/GuessCase.js
We do this for stuff like iPad, so we might as well do it for YouTube.
When adding a test I used "youtube" twice, and was confused when it didn't pass; then I noticed that all of these words should be marked `/g` or they will only be corrected the first time they appear on a title, so I amended the rest of the ones that seemed relevant with the second commit here.
> MBS-12017 / MBS-12018: Correctly capitalize YouTube on guess case and set /g

- lib/MusicBrainz/Server/Controller/Role/Load.pm
This is needed in order for them to still show on the sidebar for pages like /artist/mbid/relationships?link_type_id=168
that would otherwise only load that specific link type. The issue was introduced by https://github.com/metabrainz/musicbrainz-server/pull/1953/commits/12b43e8330b0feda64c636665735c7c3c931b7b5
Tested manually on the page listed on the ticket.
> MBS-11971: Always load URL rels when loading paged subsets

- lib/MusicBrainz/Server/Data/Relationship.pm
The subtable got renamed, but I missed renaming these.
> MBS-12067: Actually use link_type_filtered on SELECT columns

- lib/MusicBrainz/Server/Controller/Artist.pm
This was passing Perl data without converting it to JSON, causing an ISE.
> MBS-12078: Pass JSON artist to CannotSplit also when empty

- root/cdtoc/attach_list.tt
- root/cdtoc/list.tt
- root/components/common-macros.tt
- root/components/list/RecordingList.js
- root/components/list/ReleaseList.js
- root/edit/details/AddRelease.js
- root/edit/details/EditReleaseLabel.js
- root/edit/details/MergeReleases.js
- root/edit/details/SetCoverArt.js
- root/layout/components/sidebar/ReleaseSidebar.js
- root/layout/components/sidebar/WorkSidebar.js
- root/recording/RecordingHeader.js
- root/recording/RecordingIndex.js
- root/release/ReleaseHeader.js
- root/release/ReleaseIndex.js
- root/release_group/ReleaseGroupIndex.js
- root/search/components/RecordingResults.js
- root/search/components/ReleaseResults.js
- root/server/components.js
- root/static/scripts/common.js
- root/static/scripts/common/components/AttributeList.js
- root/static/scripts/common/components/CollapsibleList.js
- root/static/scripts/common/components/ReleaseEvents.js
- root/static/scripts/common/components/WorkArtists.js
- root/static/scripts/common/components/WorkListEntry.js
- root/static/styles/entity.less
- root/statistics/Countries.js
- root/statistics/LanguagesScripts.js
- root/utility/tableColumns.js
- webpack/client.config.js
Since users have started adding codes for every PRO under the sun, some of these lists have gotten quite unwieldy, with 30+ entries. It makes sense to collapse them, in the same way we do for work artists and release events.
Tested with the entities mentioned on the ticket, work/be15e96f-b967-3d39-bed6-194a9e836338 / artist/4853b4f9-bcd6-4663-86bd-36d1270c6a3b/works
Not changing it for edits because there we should see all new added codes IMO.
> MBS-11537: Collapse work attributes when there are too many (but for edits)

- lib/MusicBrainz/Server/Controller/Artist.pm
- lib/MusicBrainz/Server/Controller/Collection.pm
- lib/MusicBrainz/Server/Controller/Search.pm
- lib/MusicBrainz/Server/Controller/Series.pm
- lib/MusicBrainz/Server/Data/ReleaseGroup.pm
- lib/MusicBrainz/Server/Data/Search.pm
- lib/MusicBrainz/Server/Entity/Release.pm
- lib/MusicBrainz/Server/Entity/ReleaseGroup.pm
- root/components/list/ReleaseGroupList.js
- root/search/components/ReleaseGroupResults.js
- root/static/scripts/common/components/EntityLink.js
- root/types/releasegroup.js
- t/lib/t/MusicBrainz/Server/Data/CoverArt.pm
Similar to https://github.com/metabrainz/musicbrainz-server/pull/1866
We don't have a great way currently to check whether a RG has cover art without loading it. If loading the cover art for all RGs in, say, a page of search results or an artist index seems like a problem we could always add a separate query that checks existence only.
> MBS-11059: Indicate which release groups have CAA art in listings

- root/components/list/EventList.js
- root/components/list/ReleaseList.js
- root/components/list/WorkList.js
- root/report/components/EventList.js
- root/report/components/WorkList.js
- root/search/components/EventResults.js
- root/static/scripts/common/components/ArtistRoles.js
- root/static/scripts/common/components/WorkListEntry.js
- root/utility/tableColumns.js
- webpack/client.config.js
This applies to artists for events and to writers for works.
On top of https://github.com/metabrainz/musicbrainz-server/pull/2024
For a works example, see artist/164f0d73-1234-4e2c-8743-d77bf2191051/works and for an events example, area/525d4e18-3d00-31b9-a58b-a146a916de8f/events
> MBS-11756: Collapse artist roles when there are too many

- root/static/scripts/edit/externalLinks.js
- t/selenium/External_Links_Editor.json5
We currently have 32 of these for google.com, but I'm pretty sure that's because a lot of them get removed soon after they're added - I've certainly seen this happen.
> MBS-12060: Block google.com/search URLs on URL relationships

- lib/MusicBrainz/Server/Data/Alias.pm
- t/lib/t/MusicBrainz/Server/Data/Alias.pm
We used to do this with triggers, but that was problematic so we got rid of them. But we forgot to actually change the insert/update code to adapt to that, so they kept hitting ISEs because the old `primary_for_locale` flag was not being unset before they tried to set it for the alias in question.
Tested locally, plus test added.
> MBS-12021: Properly override primary aliases in code

- root/entity/Details.js
The details link was broken for JSON for (at least) genres, because they have no default includes but we were using `&` for `fmt`.
This just builds an `URL` object, which seems like the safest option.
>  MBS-12084: Use URL to build the details API links

- root/edit/details/EditMedium.js
For some reason, we did this check for track changes (so, when a new recording is assigned to an existing track) but not for new track adds that create a new recording.
> MBS-12001: Use allowNew for recording links when adding a new track

- root/components/common-macros.tt
- t/selenium.js
- t/selenium/CD_Lookup.json5
- t/sql/selenium.sql
`TaggerIcon` was updated to take entity type and MBID instead of an entity, but the TT `tagger_icon` macro wasn't updated for it, so it was linking to `?id=undefined`
Tested on the URL mentioned on the ticket.
> MBS-12087: Fix TT TaggerIcon call

- lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
- lib/MusicBrainz/Server/Validation.pm
- root/release/edit/editnote.tt
- root/static/scripts/release-editor/init.js
- root/static/scripts/tests/release-editor/seeds/useless_edit_note.html
- t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
- t/selenium.js
- t/selenium/release-editor/MBS-12077.json5
This does the same for release adds which we already did for all other edits that require edit notes: it enforces not only that there is a note at all, but also that it's not clearly useless.
> MBS-12077: Also block useless edit notes on the release editor

- root/static/scripts/artist/components/ArtistCreditRenamer.js
This is now used in exactly the same way in two places (here and in ArtistCreditList). We could turn it into its own component but I'm not sure if it makes sense yet. Let me know what you think! :)
> MBS-11991: Add links for uses of artist credits in entity editor

- script/update_containers.sh
Depends on https://github.com/metabrainz/docker-server-configs/pull/190
If we put a service into maintenance mode, the gateway will stop forwarding requests to it. If we then wait the full duration of the configured max request time, any request that hit the container before going into maintenance mode will be fully handled and we can stop the container.
There's no need to have separate timeouts configured for prod and beta because `DETERMINE_MAX_REQUEST_TIME` is the same for both.
After restarting a container, we run `curl` against the service until it comes back up before disabling maintenance mode.
> Try to eradicate 5xx errors during deployment

- lib/MusicBrainz/Server/Report/MediumsWithOrderInTitle.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/MediumsWithOrderInTitle.js
- root/report/ReportsIndex.js
- root/server/components.js
This checks for any releases that have mediums where the name is "CD n", "Disc n" or similar, with n being
the medium position. These should only very, very rarely be correct, and only if they can be proven to really be intended as a disc *title*.
> MBS-11917: New report: Releases with "Disc n" medium titles

- root/release/edit/tracklist.tt
- root/static/scripts/release-editor/fields.js
Users keep entering CD X or Disc X as medium titles, despite that being generally useless. This tries to avoid that.
Tested by adding a release with the appropriate medium name and seeing that it does get pre-approved when editing, errors when changed, and is still approved when changed back to the original.
I would appreciate two reviews here, just in case :)
> MBS-12034: Require confirmation to enter a "Disc n" medium title

- lib/MusicBrainz/Server/Controller/User/Subscriptions.pm
- lib/MusicBrainz/Server/Controller/User/SubscriptionsRole.pm
- root/components/UserAccountTabs.js
- root/static/styles/layout.less
- root/static/styles/release-editor.less
- root/user/UserSubscriptions.js
- root/utility/buildTab.js
- t/lib/t/MusicBrainz/Server/Controller/User/Subscriptions.pm
@Freso asked for an easier way to see if a sockpuppet editor subscribes to other editors (in order to find more sockpuppets).
They specifically asked for a way to know the tab contains private data and should not be open when streaming so I added a class (to be able to hide it) and a warning / highlight.
They also specified they did not want to be able to see any other subscriptions, so this hides even the summary
from the user subscription page in this case.
Also, since the /artists page is private, we need to specifically make the tab lead to /editors in this case.
> MBS-12055: Allow admins to see private editor-editor subscriptions

- script/update_containers.sh
The specification of the script `set_maintenance_mode.sh` is changing to address a bug as it needs registered port rather than internal port.
This patch follows these changes.
> Fix setting maintenance mode for deployment

- lib/MusicBrainz/Server/Entity/ReleaseGroup.pm
This broke in 7d28f5c7efb224b670ee3853c1336ad3e1c53abc (https://github.com/metabrainz/musicbrainz-server/pull/1868) since I changed the meaning of has_cover_art but did not change this check to still use the original variable.
> MBS-12102: Fix cover art check on RG TO_JSON

- lib/MusicBrainz/Server/Controller/User.pm
- root/user/UserProfile.js
The whole point of blocking notes is to block abusive communication, which obviously also includes possible abusive emails.
> MBS-12105: Block editors from sending messages if they are blocked from adding notes

- HACKING.md
HACKING.md has two main titles ("Code standards" and "Porting TT to React") formatted with lees importance than they should.
I edited those titles to make them more relevant / section separators.
> Edit title hierarchies at HACKING.md

- lib/MusicBrainz/Server/Report/CatNoLooksLikeASIN.pm
- lib/MusicBrainz/Server/Report/CatNoLooksLikeISRC.pm
- lib/MusicBrainz/Server/Report/CatNoLooksLikeLabelCode.pm
- lib/MusicBrainz/Server/Report/DuplicateReleaseGroups.pm
Once we changed these to not use double quotes, it seems the escaping slash before $ became unneeded, and it apparently was actually stopping these from returning some results (the catno ones weren't returning any results at all).
Tested by regenerating the reports with sample data and seeing hits appear again (and one extra pair appear for the DuplicateReleaseGroups one which wasn't empty).
> MBS-12112: Remove unneeded escape for $

- root/user/UserProfile.js
We already have the number anyway (it's just a sum of the different categories) so I see no reason not to show this and save people the effort of summing it themselves. Moved the (view) link from the header to this row, since it makes no sense to duplicate it IMO.
> MBS-12097: Show total edit count on user pages

- root/components/UserAccountTabs.js
The recent change to allow admins to see editor subscriptions did not take into account that it's still useless to show "editor subscriptions" once the editor has been deleted. `viewingOwnProfile` shouldn't be a problem, since well, a deleted user isn't going to be viewing anything.
> MBS-12115: Don't show deleted users' Subscription tab to admins

- lib/MusicBrainz/Server/Report/MediumsWithOrderInTitle.pm
- root/static/scripts/release-editor/fields.js
This is a reasonably common use, even if it's not as common as "Disc", so it makes sense to check for it too in the release editor and for the report.
Tested by hand (using it and seeing it was detected in the RE, then detected by the report).
> MBS-12114: Account for the "Disk" alternative spelling to "Disc"

- lib/MusicBrainz/Server/Controller/Account.pm
If a user gets deleted after they get send a verification link, but before they click on it, the email is added to the now-deleted user. This is certainly not intended, so this checks the user is not deleted before actually updating anything.
This isn't tested because I can't actually send verification emails from my local system, but I don't see why it wouldn't work. Scream if I did a dumb.
> MBS-11942: Deleted users can still use pending verification links

- lib/MusicBrainz/Server/Data/Relationship.pm
This takes forever unless cached, so we should cache it and avoid everyone suffering that pain every time.
@mwiencek: I haven't used cache much before, so I tried to copy the way `get_all` responses get cached. Please do let me know if I (probably) did a dumb.
> MBS-12083: Add caching to get_types_for_timeline

- root/static/styles/layout.less
This broke when I moved it from release-editor.less to layout.less because jquery-ui took over. By specifying the extra classes this takes over and is again considered more relevant, see https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity
Also changed the background position for the non-release-editor tabs because those are smaller and as such the image needs smaller margins to be centered.
> MBS-12117: Use CSS specificity to fix error highlighting in RE tabs

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
This has been wanted forever, but now the restrict tool finally allows us to do it. For now, this just allows paid streaming, paid download or a combination of both for all entities (artist, label, recording, release). If we eventually decide to allow for Apple Music relationships for artists and/or labels, this should be modified accordingly.
I also readded the validation that got dropped with https://github.com/metabrainz/musicbrainz-server/pull/1643
On top of https://github.com/metabrainz/musicbrainz-server/pull/2339 (which allows testing it).
> MBS-9375: Restrict Apple Music to paid streaming and/or purchase 

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
Soundcloud shouldn't be used for license nor crowdfunding relationships (nor, probably, any other that gets added
further down the line). This restricts it to only allow "get the music" relationships (all of them, because apparently some stuff on SoundCloud requires a SoundCloud Go+ subscription, whatever that involves  - not available in my country).
On top of https://github.com/metabrainz/musicbrainz-server/pull/2339 (which used to be part of this PR)
> MBS-7727: Restrict Soundcloud to only "get the music" rels

- root/static/scripts/tests/Control/URLCleanup.js
We should ensure we are returning the expected errors for tests that we expect to fail, including both specific message (when given) and target.
This just uses a substring, rather than the whole error message, because it seems like overkill otherwise and it's easier for oneswe expand with arguments.
Adds a new optional test property `expected_error`. This requires one of `input_relationship_type` or `expected_relationship_type` (since the error might vary depending on the relationship selected) and `input_entity_type` (since the same URL might be allowed for one entity type but not another).
This adds two examples:
One for our block of Wikipedia pages as discography entries for releases, testing a specific error message and `input_relationship_type`.
One for blocking non-specific 45cat …
> MBS-11995: Test error messages in external links editor

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
I didn't find any URL like this when originally writing the validation, but they do use % for escaping and those URLs are currently deemed invalid.
> MBS-12133: Allow % in jazzmusicarchives URLs

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
Sadly these can't be massaged into the real link like some other ones can, so we need to just block them and ask the user to follow the redirect.
On top of https://github.com/metabrainz/musicbrainz-server/pull/2347 for the Apple links.
> MBS-10715 / MBS-10716: Block Amazon and Apple redirect links

- root/user/UserSubscriptions.js
Other subscribe / unsubscribe links go back to the same page, but this was going to the front page. Returning here seems a lot more user-friendly.
> MBS-12167: Use returnToCurrentPage in UserSubscriptions action

- root/edit/details/EditRelationshipType.js
- root/types/edit_types.js
This was actually passing `parent`, not `parentId`, so the previous setup didn't work at all. `parent` seems better anyway (if we can show a link why not show a link), so this just actually uses it.
Tested by just checking the edit search for Edit relationship type changes.
> MBS-12121: Actually show parent changes in EditRelationshipType

- lib/MusicBrainz/Server/Controller/Tag.pm
- root/components/PaginatedResults.js
- root/tag/TagCloud.js
Fixes two places that used `toLocaleString()` (always using English number formatting) rather than using the actual selected locale via `formatCount`.
> MBS-12142 / MBS-12164: Use formatCount in more places

- lib/MusicBrainz/Server.pm
- lib/MusicBrainz/Server/Controller/User.pm
- lib/MusicBrainz/Server/Data/Editor.pm
- lib/MusicBrainz/Server/Entity/Editor.pm
- lib/MusicBrainz/Server/Entity/Preferences.pm
- lib/MusicBrainz/Server/Filters.pm
- lib/MusicBrainz/Server/Form/User/Preferences.pm
- root/components/UserAccountLayout.js
- root/components/common-macros.tt
- root/static/scripts/account/components/PreferencesForm.js
- root/static/scripts/common/components/EditorLink.js
- root/static/scripts/tests/autocomplete2.js
- root/static/styles/edit.less
- root/static/styles/layout.less
- root/types/editor.js
- root/utility/activeSanitizedEditor.js
- root/utility/hydrate.js
- root/utility/sanitizedEditor.js
- t/lib/t/MusicBrainz/Server/Controller/Area/Users.pm
- t/lib/t/MusicBrainz/Server/Controller/OAuth2.pm
Related to MBS-9725.  Gravatar was scraped and email address hashes were cracked.  We should migrate away from their service.
I left in support for avatars in the codebase to minimize the amount of work required to add in support for Discourse avatars in the future.
> MBS-12137: Remove Gravatar

- lib/MusicBrainz/Server/Controller/Root.pm
- t/lib/t/MusicBrainz/Server/Controller/Errors.pm
If someone submits a ton of requests with invalid `musicbrainz_server_session` cookies, each request will trigger an internal server error (due to an exception being thrown by Catalyst).  We'd rather respond to these with Bad Request, while still logging them to Sentry, so they at least don't trigger any 5xx alerts.
> Respond with Bad Request for "invalid session ID"

- docs/CODE_OF_CONDUCT.md
This seems like an outdated copy of the org's CoC that adds nothing.
Removing so this uses the default .github repo one that is kept up to date.
Feel free to reject this PR if you want to keep a separate one for some reason, rather than this being a historical artifact :)
> Delete CODE_OF_CONDUCT.md and use org default

- package.json
- yarn.lock
Some isolated JS dependencies have security updates, that doesn’t affect MusicBrainz Server though.
* Bump [ShellJS to v0.8.5](https://github.com/shelljs/shelljs/releases/tag/v0.8.5)
* Bump [shell-quote to v1.7.3](https://github.com/substack/node-shell-quote/compare/v1.7.2...1.7.3)
* Bump [cookie to v0.4.1](https://github.com/jshttp/cookie/releases/tag/v0.4.1)
> Bump some isolated JS dependencies

- root/static/scripts/edit/URLCleanup.js
These have their own barcodes, so users feel they should be added as releases.
For the future, it would be good if `only_valid_entity_types` could also be validated against all options in `limited_link_type_combinations`.
> MBS-12132: Allow Apple Music music-video links for releases

- lib/MusicBrainz/Server/Sitemap/Incremental.pm
Incremental sitemaps ingest replication packets and follow the tables therein to find changes to pages in the sitemaps.  If a type table is updated, like release_group_primary_type for example, we'd end up trying to fetch every page for every release group using a modified type.  (It doesn't matter which columns were changed.)  I can't think of a situation where changing a type would significantly affect the content of so many pages that we'd want search engines to re-index them all, so I'm having the code skip these type tables entirely.
> Don't follow type tables for incremental sitemaps

- lib/MusicBrainz/Server/Form/Field/Text.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/AddAnnotation.pm
`MusicBrainz::Server::Form::Field::Text` was completely replacing `sub validate` from the `HTML::FormHandler::Field::Text` package it extends. This means the checks for both `maxlength` and `minlength` were not running, making `maxlength` in `Form::Annotation`'s changelog completely useless.
> MBS-12161: Expand, not replace, FormHandler Text's validate

- lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Utils.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupTagsRatings.pm
- t/sql/webservice.sql
These are already filtered out in `_serialize_user_tag` and `_serialize_user_genre` in `XMLSerializer`, but they were not being looked into in the JSON serializer. This just adds an extra `grep` for `is_upvote` to `serialize_tags` to effectively do the same there.
For some reason, we had no tests at all for JSON user-tags, too. Added a JSON version of some of the ones we have for XML, and modified the test data so that it will fail if this bug is broken again.
> MBS-12155: Filter out downvoted tags from JSON WS user-tags/genres

- root/static/scripts/release/components/TracklistAndCredits.js
The order in this row was switched for (I assume) readability (track_count first like elsewhere), but for some reason < turned into >=. We do not want to show there are unloaded tracks if the track count is exactly the same as the amount of loaded tracks though!
> Fix regression in medium track count comparison

- lib/MusicBrainz/Server/Constants.pm
- lib/MusicBrainz/Server/Controller/Admin.pm
- lib/MusicBrainz/Server/Controller/User.pm
- lib/MusicBrainz/Server/Data/Editor.pm
- lib/MusicBrainz/Server/Entity/Editor.pm
- lib/MusicBrainz/Server/Form/Admin/EditUser.pm
- root/admin/edit_user.tt
- root/constants.js
- root/static/scripts/common/utility/privileges.js
- root/user/Login.js
- root/user/UserProfile.js
- t/lib/t/MusicBrainz/Server/Controller/User/Login.pm
For now this blocks the user from editing and leaving notes (a combo of editing disabled and notes disabled) and from logging in once logged out.
Future improvements:
It was suggested to block profile pages as a 403 but that kinda suggests that there's an issue with the user viewing it - maybe instead detach to a "this user was blocked as spam" template if not account admin? Something like "This user was blocked and their profile is hidden because they were deemed to be spamming. If you see spam in MusicBrainz, please do let us know by reporting the spammer from their user page.".
> MBS-11986 / MBS-12128: New account flag: Spammer

- .circleci/config.yml
- t/lib/t/MusicBrainz/Server/Data/Recording.pm
- t/sql/recording.sql
We've been getting spurious failures on CircleCI which I have a feeling are due to running certain tests in parallel; usually it's one of the dump scripts under t/script/ that fail, but I'm not sure which tests are conflicting with them.  Let's try disabling this and seeing if it significantly affects the run-time.
> Remove parallel processing on prove

- root/static/scripts/common/entity.js
This is typed as always an array, but `entity.js` was potentially passing undefined instead, breaking the check in `localizeAreaName`. We now pass an empty array in that case for parity with the usual `TO_JSON`.
> MBS-11532: Don't pass undef ISO variable to localizeAreaName

- lib/MusicBrainz/Server/Form/Collection.pm
- lib/MusicBrainz/Server/Form/Role/UserProfile.pm
This is the same as what we already do for annotations, which had the same problem (https://github.com/metabrainz/musicbrainz-server/pull/1160/). Tested by hand.
> MBS-12168: Avoid breaking list formatting on user bios and collections

- root/static/scripts/release-editor/fields.js
This was only checking if latest_annotation existed before happily using 'text', but 'text' is actually nullable. It seems like emptying an annotation through the release editor will not null it, but emptying it through the usual edit annotation page will. As such, the release editor will replace the null annotation with an empty string one, in what is a completely pointless exercise.
It might be preferable to just make annotation NOT NULL and always ensure it's an empty string when blanked.
> MBS-2313: Avoid pointless empty annotation edits

- lib/MusicBrainz/Server/Controller/Admin.pm
- root/admin/EmailSearch.js
Currently there's no clear way to differentiate an empty search from a not-yet-submitted one - both just show the email address in the form. This makes it so that after a search that returned no results a message stating that fact is shown.
> MBS-12147: State that an email search had no results

- lib/MusicBrainz/Server/Controller/Edit.pm
'`canonical`' ensures the JSON is sorted by key. This makes things relatively slower, but it makes it easier to compare different edits' data and to figure out if something is missing or weird. Since the main target of the edit data page are humans, it makes sense IMO to make it easier for them to use by adding this consistency, even if speed goes down a bit.
> MBS-12160: Use 'canonical' to display sorted edit data JSON

- root/release/merge.tt
This wasn't working because hydration also requires the `script_manifest` line in addition to the `React.embed`.
> MBS-12187: Load ReleaseEvents with manifest in release merges

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
These exist, as per the added example, so we should support them.
> MBS-12188: Allow SNAC links for places

- lib/MusicBrainz/Server/Controller.pm
- lib/MusicBrainz/Server/Controller/Role/Alias.pm
Errors weren't being shown when a required edit note was missing, since the form was always being serialized before validation. This moves serialization to always happen after validation, but before the function returns.
> MBS-12092: Serialize edit_action form after errors are added 

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
DAHR now has a permalink with the `/names` prefix for artists. It also has a new `/mastertalent` prefix for artists, which they
redirect to, but they do not call a permalink. As such, this accepts both, but cleans `/mastertalent` to `/names`.
> MBS-12189: Support "names" prefix for DAHR artists

- root/user/UserProfile.js
- t/lib/t/MusicBrainz/Server/Controller/User/Show.pm
I blocked these a bit too well, to the point where Freso himself cannot see them either anymore.
This allows admins to see the page, but adds a visible warning that they are already banned so that they don't have to go check the flags to make sure.
> MBS-12191: Allow admins to see spammer profiles

- lib/MusicBrainz/Server/WebService/Validator.pm
We were requiring auth for anything related to the tag resource, but as per `WS::2::Tag` only `tag_lookup` and `tag_submit`
should require auth (since they actually interact with the user's own tags). Tag search, which just searches for tag names matching a string, should not require any sort of authentication, since it's equivalent to other public searches.
Tested by actually going to both `/ws/2/tag/?query=shoegaze` and `/ws/2/tag?id=ed35bc92-2b5a-4ddf-96d2-51af9ab239e7&entity=artist` and making sure the first no longer requires logging in, while the second still does.
> MBS-12162: Do not require auth for non-private tag WS queries

- .eslintrc.unfixed.yaml
- .eslintrc.yaml
- root/static/scripts/common/components/TagEditor.js
- root/static/scripts/edit/components/PossibleDuplicates.js
- root/static/scripts/edit/components/RemoveButton.js
- root/static/scripts/edit/externalLinks.js
We might still want to convert a bunch more that *do* use state to use hooks (is there a rule for that?) but this at least allows us to move one more rule to the fixed folder, AFAICT.
> Eslint fixes: react/prefer-stateless-function

- lib/MusicBrainz/Server/Controller/ReleaseEditor.pm
- root/types/medium.js
* cdtocs is outputted as an array of strings
* cdtocs is not a count
It doesn't seem like either of these lines caused an issue in practice.
> cdtocs type fixes

- package.json
- root/static/scripts/account/components/ApplicationForm.js
- root/static/scripts/account/components/EditProfileForm.js
- root/static/scripts/account/components/PreferencesForm.js
- root/static/scripts/common/components/Collapsible.js
- root/static/scripts/common/components/TagEditor.js
- yarn.lock
In some class-based components, we use a technique where we bind certain methods to `this` in the constructor so that we can pass them as event handlers directly.
Flow doesn't like how we're doing this anymore.  For one, we previously had to declare the method signature again to be able to assign it in the constructor; Flow now sees this as a duplicate member declaration and errors.  But even once that's fixed, it also doesn't like `this.foo.bind(this)` anymore where `this.foo` is a method, because it views it as unbinding it from the class context (which isn't really true).
We could use `$FlowIssue` comments for these, but it's easier to just change them to arrow functions, and give a different name to the bound functions (I appended `Bound` to all of the names).
Some of these bound …
> Upgrade to Flow 0.171.0

- HACKING-PROD.md
This is for stuff that is not private (so should not be on syswiki) but is also not relevant for most local users of MBS, just for running our production setup.
I was doing this today with help from @mwiencek for one of my PRs and I thought we could document it properly so I don't have to ask again next time :)
> Add a HACKING-PROD file and document cpanfile updates

- lib/MusicBrainz/Server/Entity/URL/AmazonMusic.pm
We don't use these in any of the other pretty names that include countries (Apple and Napster just do "Site CountryCode", and ASIN does CountryCode: ASIN). As such, it seems more consistent to drop them from here too.
> MBS-12138: Drop parens from Amazon Music pretty name

- root/static/scripts/tests/Control/URLCleanup.js
This adds a large, detailed comment on top of the URLCleanup tests file that specifies what each property means and how they can be combined. Happy to improve it further with any suggestions :)
While writing this I noticed a small bug with `expected_error` and that the `limited_link_type_combinations` properties were not ordered  as expected, fixed in a separate commit for each.
> Improve URLCleanup test docs

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
YouTube has channels using /user, /channel, /c and no prefix. No idea *why*, but in any case while you can remove /c
you can't remove /channel, for example. So to be safe I just deal with them separately here. While for /channel, like for /user, it's probably fine to just remove anything at the end, for the ones with the username only it's harder to be confident on a wide regex, so just removing the main tabs from the YouTube channel page.
> MBS-11742: Also clean non-/user YouTube channels

- cpanfile
- lib/MusicBrainz/Server/CoverArt.pm
- lib/MusicBrainz/Server/CoverArt/Provider.pm
- lib/MusicBrainz/Server/CoverArt/Provider/RegularExpression.pm
- lib/MusicBrainz/Server/CoverArt/Provider/WebService/Amazon.pm
- lib/MusicBrainz/Server/Edit/Alias/Delete.pm
- lib/MusicBrainz/Server/Edit/Alias/Edit.pm
- lib/MusicBrainz/Server/Edit/Generic/Create.pm
- lib/MusicBrainz/Server/Edit/Generic/Delete.pm
- lib/MusicBrainz/Server/Edit/Generic/Edit.pm
- lib/MusicBrainz/Server/Edit/Generic/Merge.pm
- lib/MusicBrainz/Server/Edit/Historic.pm
- lib/MusicBrainz/Server/Edit/WithDifferences.pm
According to the documentation at https://metacpan.org/pod/MooseX::ABC,
> This module is almost certainly a bad idea. You really want to just be using a role instead!
In most cases we can't easily convert ABC packages into roles, because they extend `MusicBrainz::Server:Edit`, which would also have to become a role.  But then we run into issues where required methods are provided by adjacent roles (triggering compile-time errors), and where attributes can no longer be extended with `+` (common for `data`), which is not possible in a role.
So instead, in most cases I've replaced `required` method lists with stubs that die.  However this means that it's no longer checked that these methods are implemented by the non-abstract classes at compile-time, only at run-time.
This patch incidentally …
> Remove MooseX::ABC

- lib/MusicBrainz/Server/Controller/Series.pm
We already filter out part-of rels, so there's no good reason not to show any entities here which have non part-of rels to series. Right now that seems to be RG and Work. Recording only has a relationship hidden by cardinality from the series page, but also preemptively allowing it.
> MBS-12201: Show any non-part-of rels on series page

- lib/MusicBrainz/Server/Data/Search.pm
This was just creating a generic entity based on indexed data, but that means we lack a lot of useful info, such as sort names for artists. As such, this now loads the entity if possible and only shows the mock version if we cannot find more.
This also effectively resolves MBS-12216, an old search ticket that called for the entity disambiguation being displayed.
Not sure if results for deleted entities should actually be returned (that's a separate open search ticket) but I guess that even then, there's likely to be a few cases where the index hasn't caught up with an entity removal yet.
> MBS-12215 / MBS-12216: Load annotation entity when possible on search results

- lib/MusicBrainz/Server/Edit/Annotation/Edit.pm
- root/edit/details/AddAnnotation.js
- root/types/edit_types.js
- t/lib/t/MusicBrainz/Server/Controller/Artist/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/Label/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/Recording/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/Release/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/Series/AddAnnotation.pm
- t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
- t/lib/t/MusicBrainz/Server/Controller/Work/AddAnnotation.pm
- t/selenium/release-editor/The_Downward_Spiral.json5
We call everything "AddAnnotation", since they add a new revision of the annotation, but there's quite a big difference between cases where an annotation replaces another, deletes it, or adds one where nothing existed.
This makes it so that a diff is shown when modifying an existing annotation, similarly to the annotations-differences page.
> MBS-12183: Display previous value of annotation in AddAnnotation edits

- lib/MusicBrainz/Server/EditSearch/Predicate/EditSubscription.pm
- lib/MusicBrainz/Server/EditSearch/Query.pm
- root/edit/search_macros.tt
- root/static/scripts/common/MB/edit_search.js
This is one of the last (the last?) options that has a dedicated page, but cannot be used in edit searches, meaning we can't actually refine the edit lists on the /subscribed page using edit search.
This search checks (AFAICT) every single condition that /subscribed does: artist, label and series subscriptions, and all the possible collection subscriptions. It does *not* check editor subscriptions, which have a separate page (/subscribed_editors), and can already be searched within the edit search separately.
Tested by creating a bunch of collections locally, and by checking my current subscriptions in pink to see the results seemingly match /subscribed (keep in mind that page is ordered with oldest edits from the last two weeks first, newest last).
The query doesn't seem slower than …
> MBS-7912: Add edit search option "edit [not] in subscriptions"

- app.psgi
As noted in https://github.com/metabrainz/syswiki/pull/45/files#r781430759, it's often helpful to see the last request preceding an error or warning in production.  Or the last request before a plackup process became stuck.
The AccessLog middleware is normally only enabled in development; if you use plackup in development, you should be used to seeing requests logged.  This enables the same logging in production.
This will increase the amount of logs generated by the website and web service containers by quite a lot.  However, assuming we aggressively fix spammy warnings and set the appropriate log-opts on the containers, this patch would help make debugging alerts much easier.
> Enable Plack::Middleware::AccessLog in production

- lib/MusicBrainz/Server/EditSearch/Predicate/EditSubscription.pm
Somehow I managed to miss that I hadn't actually implemented the negative predicate here.
An entity is not in subscriptions only if every single one of these predicates is false.
> Implement "not in my subscriptions" predicate

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
See https://tickets.metabrainz.org/browse/MBS-12226
Add allowed prefix of niconico video ID to regular expression.
currently, video that have a these prefix can be watch.
- sm
- so
- nm
- ax
- ca
- cw
- cw
- nl
- /z[a-d]/
other prefix also exist, but they are not available to watch currently.
(mostly due to channel that owns video are closed)
> MBS-12226: Add allowed prefix of niconico video ID

- admin/sql/updates/20211216-mbs-12140-12141.sql
* We need to explicitly delete empty_tag_ids from the tag table in case
they were already unreferenced before the script ran (in which case
delete_unused_tag won't trigger).
* We now handle cases where a cleaned-up tag name already exists.  This
code path likely won't be hit in the production upgrade, because only
the two blank/empty tags that would be deleted via above would
otherwise hit it.  But the schema upgrade should generally work no
matter what the database contents are; this includes standalone
databases which may have unclean data.  And there is a small chance
that a bug in musicbrainz-server will allow someone to tag " rock" or
"rock " in the meantime.
* Existing control_for_whitespace and only_non_empty constraints are
now dropped first, since we'll be running this script in …
> Fixes/improvements to the MBS-12141 upgrade script

- lib/MusicBrainz/Server/Edit/Annotation/Edit.pm
Previews are allowed to have no entity, but we were unconditionally trying to call for its id, which unsurprisingly fails.
> MBS-12231: Don't try to load last annotation if there's no entity

- lib/MusicBrainz/Server/Controller/Admin.pm
- lib/MusicBrainz/Server/Controller/User.pm
- lib/MusicBrainz/Server/Data/Editor.pm
- lib/MusicBrainz/Server/Form/Admin/PrivilegeSearch.pm
- root/admin/PrivilegeSearch.js
- root/layout/components/TopMenu.js
- root/server/components.js
- root/static/styles/forms.less
- t/lib/t/MusicBrainz/Server/Controller/Admin/PrivilegeSearch.pm
- t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
- t/sql/privileges.sql
This gives admins a good way to, for example, find all users who have been blocked from editing. Since I saw no reason to limit the amount of searchable flags, this includes all of them.
> MBS-12125: Allow admins to see all users with specific privileges

- lib/MusicBrainz/Server/Edit/Medium/Delete.pm
- root/edit/details/RemoveMedium.js
- t/lib/t/MusicBrainz/Server/Edit/Medium/Delete.pm
This shows the current tracklist (and a warning) if there are significant changes between the current tracklist for the medium being removed and the tracklist that got stored when entering the removal edit. These are only shown if the edit is open, since otherwise there's probably no real use to them.
Tested with https://musicbrainz.org/edit/78642529 and https://musicbrainz.org/edit/78629796 + a search of open removal edits (but those edits might no longer be open depending on when the testing happens). For testing with local data, just try to enter remove medium edits and then add / remove tracks from the tracklist, add/remove the tracklist completely, and change the tracklist titles or whatnot.
> MBS-11558: Show current tracklist data on removal edits

- lib/MusicBrainz/Server/Controller/Ajax.pm
- lib/MusicBrainz/Server/Controller/Artist.pm
- lib/MusicBrainz/Server/Data/ReleaseGroup.pm
- lib/MusicBrainz/Server/Data/Work.pm
- lib/MusicBrainz/Server/FilterUtils.pm
- lib/MusicBrainz/Server/Form/Filter/Generic.pm
- lib/MusicBrainz/Server/Form/Filter/Recording.pm
- lib/MusicBrainz/Server/Form/Filter/Release.pm
- lib/MusicBrainz/Server/Form/Filter/ReleaseGroup.pm
- lib/MusicBrainz/Server/Form/Filter/Work.pm
- root/artist/ArtistWorks.js
- root/static/scripts/common/components/FilterForm.js
- t/lib/t/MusicBrainz/Server/Controller/Artist/Filtering.pm
- t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
- t/selenium.js
- t/selenium/FilterForm.json5
- t/selenium/Redirect_Merged_Entities.json5
- t/sql/filtering.sql
First commit adds basic filters on work name and work type.
Second adds an option to filter performers vs writers.
Third fixes a small preexisting translation bug that I accidentally copied to works too.
Fourth adds basic secondary type filtering to RG filters.
Fifth stops a warning.
Sixth allows filtering by type = none.
> MBS-5747 / MBS-5997 / MBS-7029 / MBS-11122 / MBS-11294: Add filtering to artists' works tab + filtering improvements

- lib/Catalyst/Plugin/Session/Store/MusicBrainz.pm
- lib/MusicBrainz/DataStore.pm
- lib/MusicBrainz/DataStore/Redis.pm
- lib/MusicBrainz/DataStore/RedisMulti.pm
- lib/MusicBrainz/Redis.pm
- lib/MusicBrainz/Server/Context.pm
- t/lib/t/MusicBrainz/DataStore/RedisMulti.pm
- t/tests.t
If the `DataStore::RedisMulti` module is active, then `DATASTORE_REDIS_ARGS` may return an array ref of connection details. (How do you know if it's active? grep for `DataStore::RedisMulti->new`. We may revert back to plain-old `DataStore::Redis` if multiple instances aren't needed.)
This module is useful when Redis service needs to be migrated to a new server. We'll attempt to read from each connection in order (returning the first non-empty result), and also distribute writes to all connections. This allows time to copy any keys that don't exist on the new instance from the old instance.
> Add DataStore::RedisMulti

- root/static/scripts/edit/externalLinks.js
These can be shortlinks or geolinks, but in either case we should not link to them: https://blog.found.ee/en/articles/4202319-make-a-shortlink-or-a-geolink
> MBS-12243: Block smart links: found.ee

- lib/MusicBrainz/Server/Data/Alias.pm
- t/lib/t/MusicBrainz/Server/Data/Alias.pm
The primary for locale alias should by definition be the main alias for a specific locale. As such, it makes sense that once grouped by locale, the next alias sorting will be so that the primary alias sorts first in that group.
> MBS-12251: Sort primary alias before others for same locale

- lib/MusicBrainz/Server/Entity/URL/VIAF.pm
This was always showing as `VIAF: $id`, which makes sense on the sidebar but looks a bit ridiculous elsewhere when the full display is `VIAF ID: VIAF: $id`. Changing it to only add `VIAF: ` for the sidebar, as `URL::Wikidata` already does.
> MBS-12263: Only display "VIAF: " on VIAF pretty links when on sidebar

- root/edit/components/ListEdit.js
This was causing a broken class name that meant the buttons were no longer centered as intended, but left-aligned.
> MBS-12264: Re-add missing space before editStatusClass

- root/edit/details/ReorderRelationships.js
- root/static/styles/layout.less
Because we set the width of `table.details` headers to 240px by default, this was getting unnecessarily compressed. The relationship column contents are often very long, while the other two columns are specifically set to be as narrow as they can. As such, we should let the relationships column take as much space as it needs. Added a `wide` class, as a companion to the existing `narrow`, because I expect we might need this in a few other places at some point anyway.
The example on the ticket would now look like this in my screen, which seems a lot better:
> MBS-11904: Use all available space on "reorder relationships" edits

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
There is no situation where these are a wanted link, so we might as well block them. I made a generic, reusable error string because I'm sure there are more of these.
We have 2 of the FB one only, but we seem to have dozens of the YouTube ones.
> MBS-12260 / MBS-12262: Block Facebook and YouTube search URLs

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
These were happily getting matched as ASIN, but that does not seem correct at all. AFAICT, these shouldn't be added to MB at all anyway, so this blocks them and gives the user a hopefully useful message.
> MBS-12244: Block Amazon customer video URLs

- lib/MusicBrainz/Server/Controller/Tag.pm
- lib/MusicBrainz/Server/Data/Tag.pm
- root/static/styles/layout.less
- root/tag/TagCloud.js
See commit messages for details. Tested manually with `pink` data.
> MBS-11655 / MBS-12136: Separate tag cloud into genre and non-genre tags, and add a text list

- lib/MusicBrainz/Server/Data/Statistics.pm
They are also not deleted, so this also doesn't list them as such. They'll just be "in limbo" and not get counted at all.
Since we don't currently count stuff as a percentage of all editors, the numbers not quite matching should not be a problem.
> MBS-12227: Don’t include spammer editors in "valid" statistics

- lib/MusicBrainz/Server/Form/Series.pm
- root/series/edit_form.tt
Adding a series defaults to RG, and clearly many people are wrongly adding RG series when they want something else. We know this because they keep then hitting ISEs trying to add releases to them (different bug, MBS-9125, but clear indicator).
> MBS-9234: Don't select a default type when adding new series

- root/static/scripts/edit/components/edit/DiffSide.js
Splitting a string by `''` to get an array of characters doesn't work here, because it splits the string by UTF-16 code units, not characters. Adding the `u` flag to our split `RegExp` tells it to handle 4-byte characters properly.
> MBS-12272: Split unicode text properly in DiffSide

- root/components/relationship-editor.tt
- root/static/scripts/relationship-editor/common/dialog.js
- root/static/scripts/series/edit.js
This was crashing because we now do not select a type by default (even though a type is eventually still required).
I amended the check to disallow *all* part of series reltypes if there's no series type selected, and I'm also adding an explanatory message saying the user can't add parts until they select a type.
Also made changes to avoid a similar crash on `updateAllowedTypes`.
> MBS-12289: Avoid crashing on untyped series form

- root/static/scripts/common/artworkViewer.js
This was looking only for `#sidebar` or `#content`, but edit lists wrap the components in `#edits` instead, so the images on those pages were not getting a viewer, just getting loaded in-page when clicked.
> MBS-12294: Also run artworkViewer on edit lists

- lib/MusicBrainz/Server/Controller/Collection.pm
- t/lib/t/MusicBrainz/Server/Controller/Collection/AddAndRemove.pm
I don't think there's a point creating a specific `NotFound` template for this; it's a fairly rare situation, and I think giving the user an understandable error message is good enough here.
> MBS-11879: Fail better when trying to add deleted entity to collection

- admin/sql/updates/20210702-mbs-11760.sql
- admin/sql/updates/schema-change/27.standalone.sql
This crashed for me locally during the schema change because I already had created the triggers locally for testing. Since these have been merged for a while and IIRC it's even already created in production, we will probably need this anyway for release.
> Delete new triggers if exist before creating

- root/edit/details/AddAnnotation.js
There's no reason to stick all the data into the first column when having a Diff element adds a second one. The easiest solution seems to be to just add a colspan of 2; even when the Diff is not present, all shows as normal since everything then has the same colspan.
> MBS-12303: Display non-diff annotation data over all columns 

- root/static/scripts/edit/utility/guessFeat.js
It's pointless to try to guess feat artists from an empty name, since it will obviously not contain any artist names.
This also avoids a warning when the name field is undefined, rather than an empty string (e.g. when a blank release editor is created and nobody has typed on the release name field).
> MBS-12304: Only run guess feat on nonempty names

- lib/MusicBrainz/Server/Sitemap/Overall.pm
- package.json
- root/edit/details/AddAnnotation.js
- root/static/scripts/edit/components/edit/DiffSide.js
- root/static/scripts/edit/utility/editDiff.js
- t/lib/t/MusicBrainz/Server/Controller/Artist/AddAnnotation.pm
- yarn.lock
Large annotation diffs like for edit #80101929 push the limits of generic-diff, which isn't really designed to diff arrays of thousands of characters.  It's so slow at doing this that edits like the one referenced will simply error due to the template renderer socket timing out and returning incomplete JSON.
The generic-diff README recommends fast-diff for efficient diffing of text.  This is very fast as the name suggests, but doesn't allow for custom "split" props, e.g. "\s+" for word diffing.  So we fall back to fast-diff if the text to be diffed is greater than some arbitrary "large string" length.  I picked 256 characters.
It also makes sense to use fast-diff if the "split" prop is an empty string, since we only perform character diffing in that case.
> MBS-12302: Speed up large annotation diffing

- root/layout/components/BottomMenu.js
As said at https://tickets.metabrainz.org/browse/MBS-12313 a lot of users don't realise we have an 'advanced search'.
'Search entity' just duplicates what the search at the top right is doing, without indicating further functionality.
Happy for feedback, will adjust as needed, just wanted to try submitting another pull request ;)
> MBS-12313: clarified advanced search items

- admin/sql/CreateFunctions.sql
- admin/sql/DropFunctions.sql
- admin/sql/ReplicationSetup.sql
- admin/sql/updates/20220426-mbs-12131.sql
- admin/sql/updates/schema-change/27.standalone.sql
- upgrade.json
This patch contains the schema changes required for PostgreSQL 14 to
work.  Note that these changes are also compatible with PostgreSQL 12.
For context, refer to the first incompatibility listed under
https://www.postgresql.org/docs/release/14.0/.
Because anycompatiblearray doesn't exist in v12, the ideal solution (and
the one used here) is to use more specific types.
* The _median function is only used by the median aggregate, which is
only used to calculate median recording lengths -- an integer value.
* The array_accum aggregate was added in 33bd14e for tracklist_index, a
table which was removed years ago.  The aggregate is unused and can
be removed too.
* array_cat_agg is only used internally by dbmirror.  (See
https://github.com/metabrainz/dbmirror/blob/ca536c7/pending.c#L405.)
Since …
> MBS-12131: PostgreSQL 14 compatibility

- root/admin/delete_user.tt
Deleting a user with many tags (10k or more) can be very slow and even time out for the craziest amounts. This lets the user know, and asks them to contact us if the deletion fails.
We're hoping to eventually do this with a cron job instead, so leaving a TODO to remove the warning if that happens.
> MBS-12380: Warn user about possible slow deletion

- lib/MusicBrainz/Server/Constants.pm
Although this table is empty and seems to be currently unused (see MBS-8287 for context), it should at least be included in the private dump so that if we start using it a backup exists.
> Add editor_collection_deleted_entity to @PRIVATE_TABLE_LIST

- admin/sql/dbmirror2/MasterSetup.sql
- admin/sql/dbmirror2/README
- admin/sql/updates/20220328-mbs-12250-master.sql
- admin/sql/updates/schema-change/27.master_only.sql
The README should make it self-explanatory that I'm just copying MasterSetup.sql from the dbmirror2 repository.
The only change from there is https://github.com/metabrainz/dbmirror2/commit/7ba642243b34ac22e02fd2a0a15eaf1543386a35.
> Update dbmirror2 MasterSetup.sql with warning fix

- admin/run
`admin/run` prints command arguments only.
Save the command itself in a variable before shifting arguments, then use it when printing the command to be run.
> Fix echoing the command to be run

- root/server/components.js
We reverted the removal of this but we never added it back to components.js so it's not being built.
> Readd missing report ReleasesWithAmazonCoverArt

- admin/ExportAllTables
- lib/MusicBrainz/Script/DatabaseDump.pm
- script/reset_selenium_env.sh
- t/script/ExportAllTables.t
- t/sql/initial.sql
https://tickets.metabrainz.org/browse/MBS-12400
Due to the `$table_noschema` addition in https://github.com/metabrainz/musicbrainz-server/commit/0d3866005f7abdf4f1bc59d31ae5a6c4cba4a162, we were failing to include the schema prefix in any dumped tables' file names.  Because MBImport.pl expects the file names to match the table names as specified in `@FULL_TABLE_LIST` (which includes schemas for non-musicbrainz-schema tables), this causes the import to fail at finding data files for those schemas.
The faulty change referenced above also has the side effect of causing tables with the same names in different schemas to clobber each other in the dumps.  For example, the cover-art-archive dump's art_type file would contain rows from the event_art_archive.art_type table instead!
The only …
> MBS-12400: fix non-musicbrainz-schema dumps

- lib/MusicBrainz/Server/Controller/Ajax.pm
- lib/MusicBrainz/Server/Controller/Artist.pm
- lib/MusicBrainz/Server/Data/Event.pm
- lib/MusicBrainz/Server/FilterUtils.pm
- lib/MusicBrainz/Server/Form/Filter/Event.pm
- root/artist/ArtistEvents.js
- root/static/scripts/common/components/FilterForm.js
- t/lib/t/MusicBrainz/Server/Controller/Artist/Filtering.pm
- t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
- t/sql/filtering.sql
First commit adds basic filters on event name and event type.
Second adds an option to filter based on setlist content
> MBS-12212: Add filtering to artists' events tab 

- root/static/scripts/common/MB/Control/Autocomplete.js
The artist credit is useful in the inline search results whether or not the release group has a type, so something should still be displayed when there's no `typeName`. I went with just "Release group by {artist}" since that seems the simplest while still not being misleading.
> MBS-12347: Also show RG artist in autocomplete if type is null

- lib/MusicBrainz/Server/Report/CatNoLooksLikeASIN.pm
- root/static/scripts/release-editor/bubbles.js
ASINs can be B plus any 9 letters or numbers, but doing this creates a crazy amount of false positives because it matches the catno layout of several labels, including UMG. The best we can probably do is this: B + 0 (still by far the most common) + 8 letters and digits, of which at least one is a letter (since that still includes most ASINs but excludes the UMG catnos).
Changed the catno in the release editor code to match and added comments to keep them in sync.
> MBS-8875: Improve CatNoLooksLikeASIN regexp

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
These seem to just give the visitor a popup to follow the profile, seem otherwise trivial to clean up to the profile itself.
> MBS-11694: Cleanup /intent/user Twitter URLs

- lib/MusicBrainz/Server/Controller/Account.pm
- root/account/Donation.js
The donation check page can be reached as a tab from your own user page, but didn't itself contain the user header and tab navigation, so the user couldn't continue navigating elsewhere from it as expected. Having the header doesn't add much complexity, so we might as well.
We were just detaching to 500 with no info if hitting the MeB donations endpoint failed. It seems a lot more sensible to give the user a proper warning instead.
> MBS-4960 / MBS-12361: Allow navigation from donation check page and improve error handling

- root/static/styles/layout.less
There's no real reason why we should not wrap anything that overflows anywhere in `<body>`. This includes very long URLs in edits, and also very long symbols-only names on entities.
This wasn't originally added to body because we were not sure whether it'd work, but testing a bit it does seem to do the trick anywhere where I've found this to be a problem in the past.
> MBS-8193 / MBS-12332: Wrap absurdly long lines

- lib/MusicBrainz/Script/Role/IncrementalDump.pm
These cause the incremental JSON dumps process to hang if they're not skipped.
When upgrading the musicbrainz_json_dump DB to schema 27 yesterday, I discovered that it didn't have any foreign keys (or at least all the tables I checked were missing them), which might be why this didn't cause an issue before. It must have had them at some point, and I don't know when or how they were dropped. musicbrainz_json_dump is a replicated mirror, but requires foreign keys in order for the incremental JSON dumps script to find links between tables.
> JSON dumps: ignore more useless primary/foreign keys

- script/create_test_db.sh
- t/script/ExportAllTables.t
Although the tests in ExportAllTables.t don't test dbmirror2 packets (t/script/dbmirror2.t exists for that), it's useful to have them enabled in order to check that having them enabled doesn't interfere with the production of old packets.
Note that removing the flag from ExportAllTables doesn't actually produce v2 packets in this test, because the v1 packets are created by manually inserting rows into the dbmirror_pending* tables, not via replication triggers (so there is no data to be dumped from the dbmirror2 schema).  This is why I've kept the --nodbmirror2 flag on the LoadReplicationChanges invocation: there is no v2 packet to load here.
> ExportAllTables.t: remove --nodbmirror2 flags

- lib/MusicBrainz/Server/Data/WikiDoc.pm
As suggested by the previous error message!
While this was triggered by someone trying to access `DatabaseDownload“` which was not a legitimate page, there's no reason why a page name would not contain these characters. As such, we should support escaping them.
Tested by making sure we could now properly load my new test page https://wiki.musicbrainz.org/DatabaseDownload%E2%80%9C%E2%80%9C
> MBS-12413: Use uri_escape_utf8 on Data::Wikidoc

- package.json
- yarn.lock
This fixes a warning about incorrect peer dependencies since upgrading React to v18.
Reviewing the react-table changelog, I didn't spot any breaking changes. Mostly just bug fixes and feature improvements.
> Bump react-table to 7.8.0

- root/static/scripts/edit/components/ExternalLinkAttributeDialog.js
- root/static/scripts/edit/components/URLInputPopover.js
It's not always clear what the pencil means, especially when there's one for the URL itself and one for each relationship the URL is used in. This adds the titles directly to the popover/dialog files, since they are only used for this.
> MBS-12387: Add titles to URL editor edit buttons

- lib/MusicBrainz/Server/Controller/Release.pm
This would ISE if the user requested an ID that could not be found by the `first{}` call, since we later tried to access `$artwork->types`.
This fails more gracefully now, like we already did when the release had no artwork at all; I also added specific messages for the 404 page for both cases.
> MBS-12412: Fail gracefully if requesting an invalid ID in edit-cover-art 

- upgrade.sh
I see no reason why replication triggers should be re-enabled *before* the .standalone.sql file is run.  If the standalone file happens to modify data in replicated tables, then the current order causes those changes to be logged in the dbmirror pending tables, which is not ideal. I've fixed the order so that replication is re-enabled only after all migration SQL is run.
> Run all sql before enabling replication triggers

- root/static/scripts/edit/externalLinks.js
These are the same people we were already blocking as amu.se. They claim to also run a label, so not blocking stuff outside the share. subdomain in case they actually eventually have legit pages.
> MBS-12333: Block smart links: share.amuse.io

- lib/MusicBrainz/Server/EditSearch/Predicate/Set.pm
- t/lib/t/MusicBrainz/Server/EditSearch/Predicate/Set.pm
We always want an integer here (they're mostly rowIDs, except for privileges and data quality which are also ints). Default data quality is -1, so we can't restrict to *positive* integers.
Notice from the test that for some reason we semi-supported passing the arguments in a comma-only list ('4,5' rather than two arguments 4 and 5). That *did* get the intended results returned from the DB, but it breaks display (no actual values are shown as selected in the search form) and it seems like a huge hack, so I'm disallowing it with this rather than special-casing it.
> MBS-12336: Validate that Predicate::Set is being passed integers

- root/entity/Edits.js
- root/static/scripts/common/artworkViewer.js
This got fixed with MBS-12294 (https://github.com/metabrainz/musicbrainz-server/pull/2474) by also checking for artwork inside #edits but it turns out a bunch of pages have both #content and #edits, leading to images being loaded into boxes twice. On a quick check, it seems entity/Edits is the only edit list missing #content anyway, for no clear reason, so it seems a lot easier to just add a #content div to it and revert the previous patch.
> MBS-12328: Add #content to entity/Edits for artwork display

- lib/MusicBrainz/Server/EditSearch/Predicate/EditIDSet.pm
- lib/MusicBrainz/Server/EditSearch/Predicate/Set.pm
- lib/MusicBrainz/Server/EditSearch/Query.pm
- root/edit/search_macros.tt
- t/lib/t/MusicBrainz/Server/EditSearch/Predicate/EditIDSet.pm
This was removed as a hack, but it was actually intended; it was only intended for edit type searches though, where the same edit type can have one current and one or more historical IDs and we want to search them as a group.
As such, rather than re-allow it for every set, I made a separate predicate for edit types. This still makes sure that either integers or comma-separated integers are passed.
> MBS-12420: Support comma-separated IDs for edit search types again

- root/static/scripts/common/MB/Control/Autocomplete.js
- root/static/scripts/edit/check-duplicates.js
- root/static/scripts/edit/components/ArtistCreditEditor.js
- root/static/scripts/edit/components/forms.js
- root/static/scripts/edit/externalLinks.js
- root/static/scripts/release-editor/bindingHandlers.js
- root/static/scripts/work/edit.js
- root/utility/hydrate.js
React v18 uses a new method of rendering that can be interrupted and doesn't block the page from performing other work. This can make updates appear laggy where we're trying to render many successive roots -- there is a noticeable delay between rendering each root where React yields its time. (In the case of MBS-12424, each "root" would be a track artist credit container.) This isn't really a problem with React, but a side effect of how we're gluing it into non-React code. Normally we wouldn't have so many roots.
In order to make our haphazard way of rendering things into non-React pages appear more snappy, I'm wrapping all calls to `render` and `hydrateRoot` with `flushSync`, which causes all pending updates to the DOM to occur immediately. This keeps that behavior in line with how React …
> Use flushSync to avoid render lag (fixes MBS-12424)

- root/components/EntityHeader.js
- root/edit/details/EditUrl.js
- root/static/scripts/common/components/EntityLink.js
- root/static/styles/layout.less
Still a bunch of things are wrapping that probably should not, so let's do this the other way around and start from the minimum
amount of wrapped things. This wraps only entity headers (where anything too long will break the interface for no good use), and URL entity links, which can get really long, both on EntityLink and in the Edit URL edit display.
Edit note texts and tags on tag lists already wrap in what seems to be a useful way without complaints, so leaving those in too.
Examples that *should* still wrap: 
* https://musicbrainz.org/edit/78435051 (edit URL display with a very long URL)
* https://musicbrainz.org/edit/87598821 (remove URL rel display, with long URL that has been removed)
* https://musicbrainz.org/release/77b12c1f-9fa7-4985-b291-9b717b7454b8 (release page with an …
> MBS-12437 / MBS-12438: Limit overflow-wrap even more

- lib/MusicBrainz/Server/Controller/Series.pm
We now allow area-series "held in", but the rels won't be displayed once it gets used without this change.
> MBS-12447: Also show area-series rels on series page

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
This makes an exception for search/tags pages since we want to keep the ? there to drop them more easily. Otherwise, these seem to be all tracking fluff.
> MBS-12417: Update Soundcloud cleanup to remove ? parameters

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
People seem to add quite a few of this as discography entry, or as a free download link if there is any link from the page to a place where it can be downloaded (or, sometimes, even if there isn't any).
> MBS-12419: Block Genius.com links at release level

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
The subdomain is apparently just for display language and whatnot but does not change the content nor block it, so we should
standardize to the www. default.
It seems that no ? parameters are useful (seem to be for tracking only) so we should drop them too.
> MBS-9188: Improve LinkedIn URL cleanup

- lib/MusicBrainz/Server/Report/VideosInNonVideoMediums.pm
- lib/MusicBrainz/Server/ReportFactory.pm
- root/report/ReportsIndex.js
- root/report/VideosInNonVideoMediums.js
- root/server/components.js
This will help find both videos that have been wrongly reused in audio-only releases, and stuff like video CDs marked as just "CD". I hand-picked a list of formats that do not support video rather than a list of those that can because I'd rather have missing entries if we add a new format that doesn't support video than false positives if we add a new format that does.
> MBS-12395: Report for videos in mediums that shouldn't support video

- admin/sql/InsertTestData.sql
- t/lib/t/MusicBrainz/Server/Controller/Area/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/AddAlias.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/DeleteAlias.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/EditAlias.pm
- t/lib/t/MusicBrainz/Server/Controller/Label/AddAlias.pm
- t/lib/t/MusicBrainz/Server/Controller/Label/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/Label/DeleteAlias.pm
- t/lib/t/MusicBrainz/Server/Controller/Label/EditAlias.pm
- t/lib/t/MusicBrainz/Server/Controller/Place/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/Recording/AddAlias.pm
- t/lib/t/MusicBrainz/Server/Controller/Recording/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/Recording/DeleteAlias.pm
- t/lib/t/MusicBrainz/Server/Controller/Recording/EditAlias.pm
- t/lib/t/MusicBrainz/Server/Controller/Release/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/Series/AddAlias.pm
- t/lib/t/MusicBrainz/Server/Controller/Series/Aliases.pm
- t/lib/t/MusicBrainz/Server/Controller/Series/DeleteAlias.pm
- t/lib/t/MusicBrainz/Server/Controller/Series/EditAlias.pm
- t/lib/t/MusicBrainz/Server/Controller/Work/Aliases.pm
- t/sql/area.sql
- t/sql/controller_artist.sql
- t/sql/controller_work.sql
- t/sql/place.sql
- t/sql/recording.sql
- t/sql/series.sql
I'm changing a lot of tests that we already had for several entities, because it seems a lot easier to see all the updates to them in one commit each rather than slowly doing them per entity.
> Improve test documentation (VII): Shared tests (Aliases)

- lib/MusicBrainz/Server/Controller/Role/Annotation.pm
- root/annotation/AnnotationComparison.js
- root/annotation/AnnotationRevision.js
- root/static/scripts/annotation/AnnotationHistoryTable.js
- root/static/scripts/common/components/Annotation.js
- root/types/annotation.js
This fixes two issues (including MBS-12453) with the React implementation (which weren't problems with TT because TT just didn't care), and two issues (MBS-12455 and MBS-12456) that already existed before the React move. See commit comments for more details.
Example of empty annotation revision page:
> MBS-12453 / MBS-12455 / MBS-12456: Annotation react fixes

- root/utility/hydrate.js
Currently it's difficult for userscripts to determine when hydration is completed so that it's safe to modify the page.  This adds a custom mb-hydration event that scripts can listen for.
Based on a suggestion by @ROpdebee in https://github.com/jesus2099/konami-command/issues/596#issuecomment-1154386261
I tested this by creating a new Greasemonkey script with the following code and observing that several events were logged.
```JS
document.addEventListener('mb-hydration', (event) => {
console.log('Got mb-hydration event:', event);
});
```
> Add custom hydration event for userscripts

- lib/MusicBrainz/Server/Controller/Role/Annotation.pm
The code was more than happy to load whichever annotation the passed ID was for, and then present it as if it was an annotation for the entity in question. This actually checks that the requested annotation is in the annotation history for that entity, and returns a bad request error otherwise.
I also added an actual message to the not found error returned if the ID does not exist, since the default "message: $id" was useless.
> MBS-12458: Error if trying to load annotation for wrong entity

- t/lib/t/MusicBrainz/Server/Controller/Area/Tags.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/Ratings.pm
- t/lib/t/MusicBrainz/Server/Controller/Artist/Tags.pm
- t/lib/t/MusicBrainz/Server/Controller/Instrument/Tags.pm
- t/lib/t/MusicBrainz/Server/Controller/Label/Ratings.pm
- t/lib/t/MusicBrainz/Server/Controller/Label/Tags.pm
- t/lib/t/MusicBrainz/Server/Controller/Recording/Ratings.pm
- t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Ratings.pm
- t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Tags.pm
- t/lib/t/MusicBrainz/Server/Controller/Series/Tags.pm
- t/lib/t/MusicBrainz/Server/Controller/Work/Ratings.pm
- t/lib/t/MusicBrainz/Server/Controller/Work/Tags.pm
- t/sql/controller_artist.sql
- t/sql/controller_ratings.sql
I'm changing a lot of tests that we already had for several entities, because it seems a lot easier to see all the updates to them in one commit each rather than slowly doing them per entity.
> Improve test documentation (VIII): Shared tests (Tags/Ratings)

- root/components/RelatedWorks.js
Not sure what was the reason to restrict it to these `targetEntityTypes` but it probably makes sense to list event here, if only for premiered at
> MBS-12464: Also display event-work rels in Related Works

- lib/MusicBrainz/Server/Edit/Annotation/Edit.pm
Annotation text is stored as `Maybe[Str]` in the model `Entity/Annotation.pm` thus returning as undefined if blank. This triggered the following warning when displaying annotation edits:
Use of uninitialized value $old_annotation in concatenation (.) or
string at lib/MusicBrainz/Server/Edit/Annotation/Edit.pm line 81.
This patch appropriately defines `$old_annotation` so that it can be directly used as a string in the rest of the subroutine.
> Fix warning when displaying blank annotation text

- lib/MusicBrainz/Server/Controller/Statistics.pm
- lib/MusicBrainz/Server/Data/Statistics.pm
- root/statistics/stats.js
See commit messages. No getting back the 10 years of lost stats, but...
The number collected in the meantime is not 0 because I guess there's some languages `WHERE l.iso_code_2t IS NOT NULL OR l.frequency > 0` which do not have an `iso_code_3` but still have releases or works using them? Didn't look too deep into it, but maybe we should.
> MBS-12470: Fix broken unknown language statistics

- root/layout/components/sidebar/GenreSidebar.js
I put the relationship editor check on the wrong level originally. Compare with `AreaSidebar`.
> MBS-12472: Show genre edit history links for all users

- root/static/scripts/timeline.js
Timeline custom tooltips are very nice but they are always partially covered by my mouse cursor.
I have noticed that the timeline custom tooltips were closer to the mouse than were the native tooltips (`<*** title="native tooltip">`).
See [MBS-12459](https://tickets.metabrainz.org/browse/MBS-12459) for before/after photos on Windows 10.
I changed the timeline.js custom tooltip position offset to match the position, relative to mouse cursor, of the native tooltip.
> MBS-12459: Mimic native tooltip position offset

- root/components/Aliases/index.js
Genre aliases page is showing edit links to non-privileged editors
Update the React component `Aliases` to handle genre the same as instrument.
> MBS-12484: Fix genre alias edit links display

- root/layout/components/sidebar/AreaSidebar.js
- root/layout/components/sidebar/EditLinks.js
- root/layout/components/sidebar/GenreSidebar.js
- root/layout/components/sidebar/InstrumentSidebar.js
Since the vast majority of editors can't edit areas, genres or instruments when logged in, it seems better not to show "Log in to edit" when logged out in those entity types that require privileges. Privileged editors will know how to log in elsewhere anyway.
> MBS-12477: Hide "Log in to edit" for privileged editor-only entities

- lib/MusicBrainz/Server/Controller/Area.pm
- root/static/scripts/common/entity.js
- root/static/scripts/relationship-editor/common/viewModel.js
This allows using https://musicbrainz.org/relationship/25ed73f8-a864-42cf-8b9c-68db198dbe0e (which can only be added / edited from the area side at the moment, but that is ok since anyway both are privilege-editor only)
> MBS-12480 / MBS-12481: Support area-genre relationships

- root/edit/details/AddAnnotation.js
- root/static/styles/layout.less
This is a problem both in annotation pages and in annotation edits, so adding `"annotation-body"` to the annotations in edits
and just adding `overflow-wrap` to that. `position: relative` and `overflow: auto` don't seem to be problematic for the edit display.
> MBS-12457: Wrap overly long words in annotations

- root/static/scripts/common/utility/formatSetlist.js
- root/static/scripts/tests/utility.js
I think having no "Artist:" nor `<strong>` for artist lines unless there is an MBID link was actually not really intended, and in any case it seems silly - it means that unless a link is added, there's literally no point in adding `@ ` vs `* ` in the setlist.
This makes it so that artist lines are always displayed starting with "Artist: " and in bold.
> MBS-12418: Also format artists in setlists if there's no MBID link

- admin/CopyReplication
This was suggested by @mayhem in
https://github.com/metabrainz/metabrainz.org/pull/387.
Replication packets are now organized into subdirs as follows:
* replication/v1 -> current dbmirror packets
* replication/v2 -> dbmirror2 packets
Within these, packets are placed into nested subdirs based on their
leading three digits.  For example, given
"replication-12345-v2.tar.bz2", this file would be placed under
replication/v2/1/2/3/.  (Packets with less than three digits would be
placed higher up -- e.g. the first replication packet would go under
replication/v1/1/, but this only matters for when we move all of the
existing ones.)
Packets are still placed directly under replication/.  So they are
copied to two places (or three counting the backup dir).  This is until
we can move all existing …
> CopyReplication: Organize packets into subdirs

- lib/MusicBrainz/Script/EntityDump.pm
This was crashing on genres (now that they have relationships so this code can get run on them) since they don't have a _gid_redirect table, but the code assumed they all had. Changed to do the same kind of check we do for meta_table.
> MBS-12515: Check _gid_redirect table exists before trying to use it

- lib/MusicBrainz/Script/JSONDump.pm
- lib/MusicBrainz/Script/JSONDump/Incremental.pm
- lib/MusicBrainz/Script/Role/IncrementalDump.pm
- lib/MusicBrainz/Server/Controller/WS/2/Release.pm
- lib/MusicBrainz/Server/JSONLookup.pm
The following changes have been running in the production
musicbrainz-json-dump container, but weren't synced to git:
* Documentation tables are ignored.
* Tag tables are not followed for changes.  It's been determined that
the current JSON dumps implementation can't keep up with the number
of entities linked to these on an hourly basis.
* The 500-track limit on recording relationships is disabled for JSON
dumps.  This fixes an issue where we were hitting said limit for each
batch of releases that exceeded 500 recordings in the batch.
* The batch size is scaled down from 500 to 100 to help account for any
increase in recording relationships for release batches.
* Relationships for each release batch are loaded 500 entities at a
time.
> Sync JSON dump container fixes to git

- lib/MusicBrainz/Server/Edit/Annotation/Edit.pm
When implementing this I forgot that if an entity is removed, so are all annotations for it, so the old annotation call on the edit will return undef.
I considered giving a different "This annotation was removed" message in this case, but honestly it does not seem useful for the editor since there's no diff to check anyway.
> MBS-12520: Don't fail on removed annotations

- root/edit/components/ListHeader.js
[MBS-12506](https://tickets.metabrainz.org/browse/MBS-12506): Reorder quick links in more intuitive order
Please look at the header ***Quick links*** link list in any basic edit list page (user, collection or entity edit history, for instance):
> **Quick links:**
> (1) Search for edits
> (2) Refine this search
> (3) All/Open edits for user/collection/entity
> (4) Open edits
> (5) All/Open edits for your subscribed entities/editors
> (6) Voting suggestions
Preview (current):
> **Quick links:** [Search for edits](https://musicbrainz.org/search/edits) | [Refine this search](https://musicbrainz.org/search/edits?conditions.0.name=David+Bowie&auto_edit_filter=&conditions.0.args.0=956&form_only=yes&order=desc&combinator=and&conditions.0.field=artist&negation=0&conditions.0.operator=%3D) | …
> MBS-12506: Reorder quick links in more intuitive order

- root/annotation/EditAnnotation.js
Sometimes you want to provide a source for some data you add to the annotation, or a detailed reason why you're changing something; the changelog (which is supposed to be a short thing anyway) does not seem too appropriate for this.
More generally, I do wonder whether we should drop the changelog completely; almost nobody uses it anyway AFAICT as anything else than a place to put sources, which can now be put on the edit note.
On top of https://github.com/metabrainz/musicbrainz-server/pull/2491
> MBS-12042: Allow providing an edit note when editing annotation

- INSTALL.md
- bin/sucrase-node
- root/utility/sucraseLoader.mjs
- root/utility/sucraseLoader.pre_v16_LTS.mjs
https://tickets.metabrainz.org/browse/MBS-12525
The bin/sucrase-node script added in 6aefc88 doesn't work in versions of Node.js prior to 16.12.0.  (16.13.0 was the first LTS release, and from the changelog appears to be identical to 16.12.0.)  This is because the ESM loader hooks API changed.
Since our INSTALL guide doesn't specify that you need an LTS release of v16, we should support older versions too.  A fallback loader using the pre-v16.12 API has been added for this cause.
I tested this inside a musicbrainz-docker dev container which still has Node v16.1.0 installed by simply running `./script/compile_resources.sh`.
> MBS-12525: Add fallback sucrase loader for Node.js < 16.12.0

- root/search/components/PaginatedSearchResults.js
This currently loads the page and just says "no results", which is quite misleading and also useless. We have all the info to show something useful, so we should do that and at least tell the user which page is the last they can go to.
> MBS-10478: Show useful message if too large search result page requested

- entities.json
- entities.mjs
- flow-typed/npm/canonical-json_v0.0.4.js
- flow-typed/npm/deep-freeze-strict_v1.x.x.js
- lib/MusicBrainz/Server/Constants.pm
- package.json
- root/annotation/AnnotationComparison.js
- root/annotation/AnnotationHistory.js
- root/artist_credit/ArtistCreditIndex.js
- root/components/EntityTabs.js
- root/components/RemoveFromMergeTableCell.js
- root/edit/components/ListHeader.js
- root/entity/Details.js
- root/static/scripts/common/components/Autocomplete2.js
- root/static/scripts/common/constants.js
- root/utility/getSortName.js
- root/utility/tableColumns.js
- script/generate_entities_json.mjs
- yarn.lock
Importing entities.json into a JS file using Flow produces an any-typed
value.  Defining a Flow type for this JSON and keeping it up-to-date is
much harder than just defining the ENTITIES structure in JS and letting
Flow create a literal object type for it.  We can then generate
entities.json (which is still used by the Perl) from this file using an
added script.
> Add entities.mjs & generate entities.json from it

- root/static/scripts/edit/externalLinks.js
https://mez.ink/ - doesn't seem needed as a host either.
> MBS-12516: Block smart links: mez.ink

- admin/sql/updates/20220720-mbs-12508.sh
The script for MBS-12508 didn't take into account that a tag's ID may change if the last usage is removed and then re-added.  To handle this, the `ON CONFLICT` specifier is changed to `(name)` rather than `(id)`, and if there's a conflict we take the ID associated with that name in the temporary table (which is assumed to be up-to-date from replication).  To avoid any ID conflicts as before, a separate `DELETE` is performed first.
Second issue: MBImport.pl by default will update `replication_control.current_replication_sequence` with the value stored in the dump, but in this case that value will be older than the existing replication sequence.  Pass the appropriate flag to disable this behavior and avoid already-applied packets from being processed again, thereby causing uniqueness …
> MBS-12548: Handle conflicting tag names and avoid updating current_replication_sequence in MBS-12508 script

- root/static/scripts/edit/externalLinks.js
https://linkfly.to/ - doesn't seem needed as a host either.
> MBS-12435: Block smart links: linkfly.to

- root/server/response.mjs
https://tickets.metabrainz.org/browse/MBS-11758
The Node template renderer currently sets its locale from the lang
cookie.  This may conflict with the locale set by Perl, which would not
be based on the lang cookie if it's not set, but rather the
Accept-Language header.  We should respect the locale determined and set
by Perl, which it stores in current_language in the stash.
This fixes an issue where certain strings (anything rendered by Node)
would be displayed in English even if the browser locale was not
English.
> MBS-11758: Use current_language instead of lang cookie in Node.js

- lib/MusicBrainz/Server/Controller/Root.pm
MBS-8876: The translation hint in the banner message was not shown in the newly selected UI language.
Split the banner message into two parts:
- The language change notice, still shown in the previously used language
* Additionally add a direct link for the user to revert the change in case of mistake
- The translation hint, in the newly selected UI language
* Additionally hide this message when the selected UI language is English (since it is also the source language for translations).
Note: Changes are easier to read with hidden whitespace.
* updating source messages in `po/mb_server.pot`
* translating messages in `po/mb_server.*.po`
* installing translations with `cd po && make install`
* Switching UI language from the front page and from the editor profile
> MBS-8876: Fix the banner message on UI language switch

- root/static/scripts/common/components/CollapsibleList.js
- root/static/scripts/common/components/IsrcList.js
- root/static/scripts/common/components/IswcList.js
In previous implementation of MBS-12334 by pull request #2500, ISRCs/ISWCs “(show ... more)” - which is displayed to shorten a long list of ISRCs/ISWCs - was rendered as a `p` element in the sidebar causing unintentional extra space under it.
This patch uses `div` instead which better fits in a definition list.
> Fix the spacing below ISRCs/ISWCs (show ... more)

- root/static/scripts/edit/URLCleanup.js
- root/static/scripts/tests/Control/URLCleanup.js
User: pages are not really articles. Since the namespace is language-dependent, this will only block enwiki user pages, but that's probably most of them anyway.
> MBS-12558: Block linking to Wikipedia User: pages
