metabrainz/musicbrainz-server

lib/MusicBrainz/Server/Edit/Annotation/Edit.pm, t/lib/t/MusicBrainz/Server/Edit/Artist/AddAnnotation.pm
Right now you can go to /edit_annotation and just re-enter the form as-is and it will create an edit. That doesn't match what we do elsewhere and it's also not useful in any way (even adding a changelog means nothing if nothing was changed).
As such, this blocks entering the edit if the text is the same as the text from the last annotation (regardless of whether a changelog or edit note is added).
Tested locally, plus added a test.
=> MBS-12556: Don't enter annotation edits unless text changes

root/static/scripts/edit/externalLinks.js, root/static/scripts/edit/utility/isShortenedUrl.js, root/static/scripts/tests/utility.js
https://tickets.metabrainz.org/browse/MBS-12566
As the ticket explains, our RegExps should escape their dots (t.co
should not match taco), and also match the hostname correctly (t.co
should not match t.co.example).
=> MBS-12566: Fix incorrect URL shortener detection

lib/MusicBrainz/Server/Controller/Work.pm
[MBS-12562](https://tickets.metabrainz.org/browse/MBS-12562): Work row ID URL is not redirected to GID (MBID) URL
All entities are using `LoadWithRowID` except works.
https://github.com/metabrainz/musicbrainz-server/search?q=LoadWithRowID
[lib/MusicBrainz/Server/Controller/Role/LoadWithRowID.pm](https://github.com/metabrainz/musicbrainz-server/blob/master/lib/MusicBrainz/Server/Controller/Role/LoadWithRowID.pm) allows redirection from row ID entity URL to GID (MBID) entity URL.
So, before this commit, https://musicbrainz.org/work/12431696 did display Ricochet work but it did not change URL to https://musicbrainz.org/work/3ba92b70-ef66-48b5-9c14-18ed6aa8afcc as it does for all other entity types.
I just link `LoadWithRowID` in `lib/MusicBrainz/Server/Controller/Work.pm` as is already done …
=> MBS-12562: Redirect row id url to gid url for works too

docker/scripts/compile_resources_for_image.sh, docker/templates/macros.m4
* CSS is generated via webpack/server.config.mjs.
* 8ef906fb40b4d2b8edc20e026e99229a574fc5c6 changed our image build steps so that server resources are no longer built.  The consequence is that CSS is no longer synced to the gateways.
* 8ef906fb40b4d2b8edc20e026e99229a574fc5c6 is reverted and a script is added to run the server build with lib/DBDefs.pm.sample instead.
=> Fix building CSS in production Docker images

lib/MusicBrainz/Server/ControllerUtils/CDTOC.pm
Solution suggested by @mwiencek. See the docs: https://perldoc.perl.org/perlrebackslash#All-the-sequences-and-escapes
=> MBS-12588: Escape user-provided disc ID in regex

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
These now include a language code in the subpath (en/ or fr/). The previous version without the code redirects, and seems preferable to me, so I'm just adapting the clean up to accept and strip the code.
=> MBS-12586: Adapt Brahms/IRCAM cleanup to new link style

lib/MusicBrainz/Server/Controller/Search.pm
https://tickets.metabrainz.org/browse/MBS-12589
Return early if an existing Internal Server Error occurs within the direct/external search methods, instead of attempting to render the results page with an undef pager, triggering another error.
This also ensures a "Request Timed Out" page is shown to the user instead of "Internal Server Error" in cases where a statement timeout occurs, since it doesn't get confused by multiple errors in `$c->error`.
=> MBS-12589: Return if direct search query times out

root/static/scripts/edit/utility/isShortenedUrl.js
=> MBS-12563: Block smart links: strm.to

lib/MusicBrainz/Server/Controller/CDStub.pm, lib/MusicBrainz/Server/Entity/CDStub.pm, lib/MusicBrainz/Server/Entity/CDStubTrack.pm, root/cdstub/CDStubHeader.js, root/cdstub/CDStubIndex.js, root/cdstub/CDStubInfo.js, root/cdstub/CDStubLayout.js, root/cdtoc/CDTocInfo.js, root/server/components.mjs, root/static/scripts/common/utility/calculateFullToc.js, root/types/cdstub.js
On top of my CD TOC work from https://github.com/metabrainz/musicbrainz-server/pull/2627 since it uses a shared function.
Tested manually with /cdstub/BjDm_3hGVComa8hVLX_zXF6fWb0- (single artist) and /cdstub/90F2R5UAcfzzrD7u4TuEdvQU2SA- (VA)
=> MBS-12580 / MBS-12581 / MBS-12582: Convert cdstub/index to React

root/relationship/linktype/RelationshipTypeIndex.js
Since we now have pages for the attributes, it seems useful to link to them. At the very least, this provides an easy way to get the attribute MBID if someone wants to use it.
I also changed the formatting a bit because having `<h3>` inside a `<p>` seemed odd (is that even valid?). It should make more sense now.
=> MBS-12335: Link to attribute docs from reltype docs

root/static/scripts/common/components/Autocomplete2/formatters.js
No description means a relationship type is a grouping one that cannot be selected and only helps organize the tree. As such, it's useless to display the link phrases for these, since they're not meant to be selected. The phrases are also usually effectively placeholders since they never get used anyway.
=> MBS-12628: Hide phrases for unselectable reltypes in inline search

root/static/scripts/relationship-editor/components/DialogPreview.js, root/static/scripts/relationship-editor/components/DialogSourceEntity.js, root/static/scripts/relationship-editor/components/RelationshipDialogContent.js, root/static/scripts/relationship-editor/utility/getBatchSelectionMessage.js, root/static/scripts/release/components/ReleaseRelationshipEditor.js
https://tickets.metabrainz.org/browse/MBS-12595
Instead of showing "This entity will be created by this edit," which isn't true, show the "{n} recordings/works selected" message we already use elsewhere.
=> MBS-12595: Set deletedCaption for batch relationship preview

root/static/scripts/common/components/DescriptiveLink.js, root/static/scripts/release/components/TrackRelationshipEditor.js
https://tickets.metabrainz.org/browse/MBS-12598
I added 'target' to the list of shared props in DescriptiveLink, so that setting target="_blank" also applies it to any artist credit links. Then I changed the relationship editor's TrackLink component to make use of DescriptiveLink instead of re-implementing the artist credit display on top of EntityLink.
=> MBS-12598: In relationship editor, open track ACs in new tab

root/static/scripts/common/components/ArtistCreditLink.js
https://tickets.metabrainz.org/browse/MBS-12612
As far as I can tell, this was the behavior prior to 536a5e89c47f494a48e33eb0ecfede5797240300
=> MBS-12612: Default showDisambiguation to false in ArtistCreditLink

root/static/scripts/release/components/ReleaseRelationshipEditor.js
https://tickets.metabrainz.org/browse/MBS-12599
Factor out the code that builds the edits for submission into `getAllRelationshipEdits`, so we can check if any changes actually exist without submitting them.  The new function is a generator, so we can bail out after one edit is seen and not have to build the whole lot.
=> MBS-12599: Relationship editor no longer warns of losing changes

root/static/styles/layout.less
88a1a97b0709233f1919a217fc33a7fa381a98dc changed the medium table header styling to not apply to sub-tables (like `.rel-editor-table`).  However it ignored that there may be `<th>` elements under `<tbody>`, not just `<thead>`. While I don't like using the `>` selector liberally, this might be the simplest way to get the previous behavior.
=> MBS-12611: Fix medium table heading alignment

root/static/scripts/common/components/Autocomplete2/reducer.js, root/static/scripts/relationship-editor/components/RelationshipPhraseGroup.js, root/static/scripts/relationship-editor/components/RelationshipTargetTypeGroups.js, t/selenium/Release_Relationship_Editor.json5
https://tickets.metabrainz.org/browse/MBS-12616
The issue here was it trying to execute `ADD_NEW_ENTITY_TITLES.release()`, which doesn't exist.  I've made it check that that's a function first, and additionally changed `determineIfUserCanAddEntities` to always return `false` for releases.
=> MBS-12616: Fix crash in relationship dialog searching for release

root/static/scripts/common/components/Autocomplete2.js, root/static/scripts/common/components/Autocomplete2/reducer.js, root/static/scripts/common/components/Autocomplete2/types.js
https://tickets.metabrainz.org/browse/MBS-12620
Previously we weren't using the returned number of pages in the results. I also fixed a minor issue where the highlighted index isn't preserved after clicking "Show more."
=> MBS-12620: Autocomplete2: "Show more" missing

root/static/scripts/common/components/Autocomplete2/formatters.js
https://tickets.metabrainz.org/browse/MBS-12604
It seems in the relationship editor at least we already set the autocomplete's work language item name appropriately, but we aren't using the item name for the generic formatter (skipping it for the non-customized entity name -- `item.entity.name`, where `item.entity` is the `LanguageT`, vs. `item.name`).  Since the item name should be set to the entity name anyway if it has no other changes, I can't see any reason to not always use the item name here.
=> MBS-12604: Autocomplete2: Show '[No lyrics]' for work language

root/static/scripts/relationship-editor/components/DialogAttributes.js, root/utility/compactEntityJson.js, t/selenium.mjs, t/selenium/Artist_Edit_Form.json5
https://tickets.metabrainz.org/browse/MBS-12615
`compactEntityJson` is used to minify the relationship editor state before putting it into sessionStorage during submission.
If you create a new entity from an autocomplete search, the returned entity object's constructor will be from a different document (the iframe), so we can't compare it by reference to our `Object`.  To determine if something is a plain object, we need another way.  The simplest is to check if the constructor function converted to a string matches our `Object` converted to a string.
=> MBS-12615: Fix compactEntityJson for other-document data

root/static/scripts/relationship-editor/components/RelationshipDialogContent.js
https://tickets.metabrainz.org/browse/MBS-12610
When changing the target entity type in the relationship editor dialog, discard the link type name if it belonged to a selection.  If there wasn't a selection, assume it may have been user-entered and preserve it.
=> MBS-12610: Discard selected link type name when changing entity type

root/components/UserAccountLayout.js
Making the editor icon match the size of the other entity icons, at least until we get avatar support.
=> MBS-12623: Editor icon is too large

lib/MusicBrainz/Server/Data/EntityAnnotation.pm, t/lib/t/MusicBrainz/Server/Edit/Release/Merge.pm
The entity merge system was trying to merge the annotations in entities, but if all entities had the same annotation already, it still tried to enter an edit, triggering the `NoChanges` exception added by MBS-12556.
There seems to be no reason why we would even try to enter an edit in this case, since the annotation won't change. I'd also argue it's misleading to claim it's the "Result of `$type` merge" since it's just the same as before. This just checks the current annotation in the target entity, and skips entering an edit if the annotation resulting from the merge process would have the same text.
Also added a test for the case.
This needs to mostly be put on the cron container for now, so pointing it to beta, we can merge there and patch cron, as suggested by @yvanzo.
=> MBS-12550: Don't enter useless annotation edit in merge

root/static/scripts/relationship-editor/utility/splitRelationshipByAttributes.js, root/static/scripts/release/components/ReleaseRelationshipEditor.js, t/selenium.mjs, t/selenium/Relationship_Seeding.json5, t/selenium/Release_Relationship_Editor.json5
https://tickets.metabrainz.org/browse/MBS-12626
`splitRelationshipByAttributes`, which implements MBS-1377 at the UI-level, was not assigning new IDs to the cloned (split) relationships, creating a conflict during submission.
I've also improved the error handling in the first commit so that the submission doesn't spin forever.
=> MBS-12626: Fix error submitting multiple instrument relationships

root/genre/types.js, root/static/scripts/alias/AliasEditForm.js, root/static/scripts/genre/components/GenreEditForm.js
Genre names should always be lowercased, so it'd be nice to have a guess case button to click rather than fiddling with the name by hand.
=> MBS-12645: Add guess case to genre edit form

lib/MusicBrainz/Server/Data/Instrument.pm, lib/MusicBrainz/Server/Data/LinkType.pm, t/lib/t/MusicBrainz/Server/Data/Instrument.pm
https://tickets.metabrainz.org/browse/MBS-12629
I found some related issues with `Data::LinkType` and `Data::Instrument`, so fixed those too.
=> MBS-12629: Adding new instrument doesn't clear type-info cache

root/static/scripts/relationship-editor/utility/prepareHtmlFormSubmission.js, root/static/scripts/relationship-editor/utility/splitRelationshipByAttributes.js, root/static/scripts/tests/relationship-editor.js, root/static/scripts/tests/relationship-editor/constants.js, t/selenium.mjs, t/selenium/Event_Edit_Form.json5
The first issue here was that in `pushRelationshipHiddenInputs`, we weren't outputting attribute data for existing attributes that had changed text values.  Now we output all new attributes unconditionally. (Attributes are only removed by specifying a 'removed' flag.)
The second issue was that in `splitRelationshipByAttributes`, we were resetting the ID on existing relationships, which actually caused it to submit a new relationship instead of editing the existing one.
Test cases have been added for both issues.
=> MBS-12646: Can't change time on artist-event relationship

root/static/scripts/relationship-editor/components/RelationshipDialogContent.js, root/static/scripts/relationship-editor/components/RelationshipEditor.js
* Expose the `getRelationshipStateId` function so that new relationships can be created without ID conflicts.
* Trigger an `mb-close-relationship-dialog` event whenever the dialog is closed.  The event has two custom properties added:
* `closeEventType`: either 'accept' or 'cancel'
* `dialogState`: the dialog state when it was closed
=> Help userscripts integrate with the relationship editor, pt. 2

flow-typed/npm/redux_v4.x.x.js, package.json, root/static/scripts/work/edit.js, yarn.lock
The currently used `redux` 3.6.0 depends on vulnerable `lodash-es`: SEC-674, SEC-707, SEC-708
Note: It is very likely that none of these vulnerabilities actually affect MusicBrainz Server.
Update to the latest `redux` 4.2.0.
Note: The `createStore` API is now deprecated. Not sure whether it is worth moving to Redux Toolkit or if any Redux dependency should be dropped eventually.
=> Bump Redux version to 4.2.0

bin/sucrase-node
Currently I cannot compile static resources with Node.js v18+ installed.  This changes how we handle such version numbers in bin/sucrase-node to be more tolerant.
=> Handle versions of Node.js > 16 in bin/sucrase-node

root/static/scripts/common/utility/groupRelationships.js
https://tickets.metabrainz.org/browse/MBS-12640
The `LinkAttrT` type has optional `credited_as` and `text_value` fields.  In some cases, empty values will be undefined, and in other cases they'll be an empty string.  In the first case, fall back to an empty string before performing a comparison when calculating changes for previews.
=> MBS-12640: Preview always on for instrument relationships

root/static/scripts/common/components/Autocomplete2.js, root/static/scripts/edit/components/Multiselect.js, root/static/scripts/relationship-editor/components/DialogAttribute/BooleanAttribute.js, root/static/scripts/relationship-editor/components/DialogAttribute/MultiselectAttribute.js, root/static/scripts/relationship-editor/components/DialogAttribute/TextAttribute.js, root/static/scripts/relationship-editor/components/DialogAttributes.js, root/static/scripts/relationship-editor/components/DialogDatePeriod.js, root/static/scripts/relationship-editor/components/DialogEntityCredit.js, root/static/scripts/relationship-editor/components/DialogLinkOrder.js, root/static/scripts/relationship-editor/components/DialogLinkType.js, root/static/scripts/relationship-editor/components/DialogPreview.js, root/static/scripts/relationship-editor/components/DialogTargetEntity.js, root/static/scripts/relationship-editor/components/DialogTargetType.js, root/static/scripts/relationship-editor/hooks/useEntityNameFromField.js, root/static/scripts/relationship-editor/types/actions.js
This also sets to strict files that depended only on this change.
I expect it's safe to ignore the 'any' issues since it is done elsewhere in the relationship editor code.
=> Make Autocomplete2 flow strict

lib/MusicBrainz/Server/Entity/CDStub.pm, root/static/scripts/common/utility/calculateFullToc.js, root/types/cdstub.js, t/selenium.mjs, t/selenium/CD_Stub_Search.json5
Search results do not contain offset data, which was causing a warning for the `0 + leadout_offset` sum, and an ISE when trying to use a null `track_offset` as an array.
=> MBS-12674: Don't assume offset data exists

lib/MusicBrainz/Server/Entity/Alias.pm, lib/MusicBrainz/Server/Entity/Application.pm, lib/MusicBrainz/Server/Entity/Area.pm, lib/MusicBrainz/Server/Entity/Artist.pm, lib/MusicBrainz/Server/Entity/Collection.pm, lib/MusicBrainz/Server/Entity/CoreEntity.pm, lib/MusicBrainz/Server/Entity/Event.pm, lib/MusicBrainz/Server/Entity/Genre.pm, lib/MusicBrainz/Server/Entity/Instrument.pm, lib/MusicBrainz/Server/Entity/Label.pm, lib/MusicBrainz/Server/Entity/Language.pm, lib/MusicBrainz/Server/Entity/Medium.pm, lib/MusicBrainz/Server/Entity/Place.pm, lib/MusicBrainz/Server/Entity/Recording.pm, lib/MusicBrainz/Server/Entity/Release.pm, lib/MusicBrainz/Server/Entity/ReleaseGroup.pm, lib/MusicBrainz/Server/Entity/Role/Name.pm, lib/MusicBrainz/Server/Entity/Script.pm, lib/MusicBrainz/Server/Entity/Series.pm, lib/MusicBrainz/Server/Entity/Tag.pm, lib/MusicBrainz/Server/Entity/Track.pm, lib/MusicBrainz/Server/Entity/URL.pm, lib/MusicBrainz/Server/Entity/Work.pm
As part of MBS-12552, it has been decided to uniformize “core” (entity type) to “relatable” = “linkable”. The current Moose class `CoreEntity` doesn’t follow this meaning thus needing some refactoring.
Note: There still are other occurrences of “core”, only the ones in Moose classes are examined in this part I.
* Move `name` Moose attribute from `CoreEntity` class to `Name` role;
* Also fix the name of the Moose role for pending edits by renaming it from `Editable` to `PendingEdits`;
* Remove collection and track from core entities in Moose as these are not relatable;
* Add the role `Linkable` to `CoreEntity` class as core entities are relatable;
* Add the role `LastUpdated` to `CoreEntity` as core entities are editable;
Incidentally fix the bug MBS-12661 in URL’s sidebar.
(Possibly …
=> MBS-12552 (I),MBS-12661: Refactor Moose CoreEntity and fix URL last updated display

root/static/scripts/edit/externalLinks.js, t/selenium/External_Links_Editor.json5
See commit messages.
Talked with @Aerozol, he thought these seem like reasonable improvements.
Proposed change:
Current:
I decided against changing the label of the checkbox to "has video" or "contains video" because we just show the attribute name elsewhere AFAICT, but I'm happy to change that if we decide it's worth it.
=> MBS-12666: Better edit display for stream for free external links

.circleci/config.yml, .perlcriticrc, HACKING-PROD.md, cpanfile, cpanfile.snapshot, docker/Dockerfile.tests
We don't have anything hitting this now, but it seems like a good thing to keep in mind and a good introduction for Critic::Moose.
Eventually we'll probably want to look into https://metacpan.org/pod/Perl::Critic::Policy::Moose::ProhibitMultipleWiths and possibly some other rules in https://metacpan.org/pod/Perl::Critic::Moose
=> Use Perl::Critic::Moose::ProhibitNewMethod

root/layout/components/sidebar/SidebarTags.js, root/static/scripts/common/components/TagEditor.js, root/static/styles/layout.less
Some people were confused because Genres and Other tags were both top level headings on the sidebar, but only Other tags had a field to enter tags. This makes it so that the sidebar tag component has a Tags header, under which smaller Genres and Other tags subheaders appear.
When logged out:
When logged in:
I used `h3` as it's the obvious next step from `h2` - ~~that's currently orange, while the mockup was black. We can change the color of these if that seems helpful~~ and made it black so that it's more clearly different from the top headers.
=> MBS-12673: Make it clearer that genres are added as tags

lib/MusicBrainz/Server/Edit/Event/DeleteAlias.pm, lib/MusicBrainz/Server/Edit/Genre/DeleteAlias.pm, lib/MusicBrainz/Server/Edit/Instrument/DeleteAlias.pm, lib/MusicBrainz/Server/Edit/Label/DeleteAlias.pm, lib/MusicBrainz/Server/Edit/Series/DeleteAlias.pm, lib/MusicBrainz/Server/Entity/Subscription/Artist.pm, lib/MusicBrainz/Server/Entity/Subscription/Label.pm, lib/MusicBrainz/Server/Entity/Subscription/Series.pm
I think the lack of a `use MusicBrainz::Server::Entity::Types` call on `Genre::DeleteAlias` is what was causing an error when running Selenium tests: `The type constraint 'Genre' has already been created`.
Moose seems to generate a constraint based on `isa => 'Genre'` calls, which then clashes with the one in `Types`, or at least that is my understanding from https://stackoverflow.com/questions/41550691/the-type-constraint-xyz-has-already-been-created
=> Fix Perl type constraint issues in Selenium tests

package.json, yarn.lock
For website rendering nodemon@2.0.19 was used, which depends on vulnerable minimatch@3.0.4 (CVE-2022-3517).
Even though it seems unlikely that it might affect the MusicBrainz website, upgrading to nodemon@2.0.20 makes it use the fixed minimatch@3.1.2 instead.
Other dependencies to minimatch@3.0.4 are used in a development context only (even glob@7.0.0 via @babel/cli@7.14.8 and shelljs@0.8.5).
=> SEC-900: Upgrade nodemon to use fixed minimatch

lib/MusicBrainz/Server/Data/Area.pm, lib/MusicBrainz/Server/Data/Artist.pm, lib/MusicBrainz/Server/Data/Collection.pm, lib/MusicBrainz/Server/Data/CoreEntity.pm, lib/MusicBrainz/Server/Data/Event.pm, lib/MusicBrainz/Server/Data/Genre.pm, lib/MusicBrainz/Server/Data/Instrument.pm, lib/MusicBrainz/Server/Data/Label.pm, lib/MusicBrainz/Server/Data/Medium.pm, lib/MusicBrainz/Server/Data/Place.pm, lib/MusicBrainz/Server/Data/Recording.pm, lib/MusicBrainz/Server/Data/Release.pm, lib/MusicBrainz/Server/Data/ReleaseGroup.pm, lib/MusicBrainz/Server/Data/Role/EntityModelClass.pm, lib/MusicBrainz/Server/Data/Role/GID.pm, lib/MusicBrainz/Server/Data/Role/GIDEntityCache.pm, lib/MusicBrainz/Server/Data/Role/GIDRedirect.pm, lib/MusicBrainz/Server/Data/Role/MainTable.pm, lib/MusicBrainz/Server/Data/Role/Name.pm, lib/MusicBrainz/Server/Data/Role/Relatable.pm, lib/MusicBrainz/Server/Data/Series.pm, lib/MusicBrainz/Server/Data/Track.pm, lib/MusicBrainz/Server/Data/URL.pm, lib/MusicBrainz/Server/Data/Work.pm, t/lib/t/MusicBrainz/Server/Data/Role/GIDEntityCache.pm, t/lib/t/MusicBrainz/Server/Data/Role/Name.pm
As part of MBS-12552, it appears that the current class `CoreEntity` in data layer isn’t about relationships, it is rather mostly about GID/MBID.
* Split `CoreEntitty` class into roles, `GIDRedirect`, `MainTable`, `Name`, `Relatable` in the data layer
* Rename `CoreEntittyCache` role to `GIDEntityCache` in the data layer
* Having moved from a class to a role makes mandatory to add explicit `requires`.
* Should the `CoreEntity` entity class be renamed as `PermanentEntity` too? It involves undoing some changes from <https://github.com/metabrainz/musicbrainz-server/pull/2681>.
- Pros:
* Restore a close mapping between Entity classes and Data classes.
* Free the term “core” to keep its use for public domain data as in [MusicBrainz Database](https://musicbrainz.org/doc/MusicBrainz_Database) / …
=> MBS-12552 (II): Refactor CoreEntity in data layer

lib/MusicBrainz/Server/Entity/CoreEntity.pm, lib/MusicBrainz/Server/Entity/Relationship.pm, lib/MusicBrainz/Server/Entity/Role/Relatable.pm, lib/MusicBrainz/Server/Entity/Types.pm
Linkable is used in entityHref.js only and in a way broader meaning, whereas Relatable is used in a lot of files (including the very central Constants.pm and entities.mjs) and in the same meaning as in this role: “that can have relationships”.
Move Entity role Linkable to Relatable
=> MBS-12552 (III): Move Entity::Role::Linkable to Relatable

lib/MusicBrainz/Server/Constants.pm
These were missing, so they were not being exported in data dumps.
=> MBS-12703: Add genre l_ tables to @CORE_TABLE_LIST

package.json, yarn.lock
For website rendering babel-loader@8.2.2 was used, which depends on vulnerable loader-utils@1.4.0 ([CVE-2022-37601](https://nvd.nist.gov/vuln/detail/CVE-2022-37601)).
I did not investigate how it might affect the MusicBrainz website exactly but it is used in production.
Upgrading to babel-loader@9.1.0 makes it not to use loader-utils anymore.
From changes at https://github.com/babel/babel-loader/releases the new requirements by the v9 are already met by MBS. (In details: babel version, node version, and webpack version. There is no breaking change otherwise.)
=> SEC-904: Upgrade babel-loader to drop loader-utils

lib/MusicBrainz/Server/Entity/Tag.pm
Follow-up to a case that was missed in a7d71920e6723be81b04abfb3551f026a4120078.
The PruneCache error is triggered randomly, but it's possible to reproduce by running the script in a loop.  I confirmed that this commit fixes the error, because the script will loop indefinitely, whereas normally it will fail in under a minute.
=> Add another missing Types module import for Genre

lib/Plack/Middleware/Debug/DAOLogger.pm
We had a bunch of uninitialized values here, and they were triggering warnings I did not see earlier because I don't usually run `CATALYST_DEBUG`.
=> Fix warnings in DAOLogger

root/static/scripts/relationship-editor/components/DialogAttribute/MultiselectAttribute.js, root/static/scripts/relationship-editor/components/DialogAttributes.js, root/static/scripts/relationship-editor/utility/compareRelationships.js, root/static/scripts/relationship-editor/utility/splitRelationshipByAttributes.js, root/static/scripts/tests/relationship-editor.js
* MBS-9417: It's now allowed to add the same instrument or vocal multiple times with different credits.  (These can't exist on the same relationship per our database schema, but they will be split into separate relationships by `splitRelationshipByAttributes`).
* MBS-12680: A duplicate relationship is no longer added when changing an instrument or vocal attribute on an existing relationship.
=> MBS-9417 / MBS-12680: Fix some multiselect attribute bugs in the relationship editor

root/static/scripts/common/MB/Control/Autocomplete.js, t/selenium.mjs, t/selenium/Recording_Edit_Form.json5, t/sql/selenium.sql
The issue stems from the recording AC still using the old Autocomplete component, which pushes a class instance (Artist, from root/static/scripts/common/entity.js) onto the recent items cache (which is shared with Autocomplete2).
Selecting this recent item causes the class instance to wind up in the relationship editor state, which is expected to only contain plain objects.  Later, when the state is serialized to sessionStorage before submission, `compactEntityJson` throws an error upon seeing the class instance, which it doesn't know how to convert to JSON.
=> MBS-12694: Fix error submitting a recording artist relationship

lib/MusicBrainz/Server/Controller/Dialog.pm, t/selenium/Artist_Edit_Form.json5
This was a regression introduced by 1786909dd2aa2a082a63b5dd6704eb21e8c71d69.  Fix it by decoding the path's query_form before forwarding it to the dialog action.
=> MBS-12695: Fix encoding issue in "Add a new entity" dialog

root/static/scripts/relationship-editor/components/DialogAttributes.js, root/static/scripts/relationship-editor/components/DialogLinkType.js, root/static/scripts/relationship-editor/components/RelationshipDialogContent.js
This commit ensures that attributes in the relationship editor dialog are properly updated when:
* The dialog opens and a link type is pre-selected (for cases where it's the only link type available).
* The target entity type is changed.
=> MBS-12679: Refresh dialog attributes when entity type changes

docker/musicbrainz-tests/DBDefs.pm, docker/musicbrainz-tests/add_mbtest_alias.sh, lib/MusicBrainz/Server.pm, lib/MusicBrainz/Server/Controller/Root.pm, t/lib/t/MusicBrainz/Server/Controller/Errors.pm
If a request contains an invalid (as in malformed) session ID cookie paired with a `beta=on` cookie, the request will die before the beta redirect response is returned and result in a closed connection on the gateway.
In daf0647c3fdeebd1cc857c14678a619ebd04a3cf we started catching "invalid session ID" errors in `Controller::Root::begin` and logging them to Sentry.  The `beta=on` issue arises because a redirect is issued immediately instead of dispatching the request through `Controller::Root`.
The potential for an invalid ID to be returned is now handled at the source by wrapping `get_session_id`.  Since this is called very early in the dispatch process, we can't render an HTML bad-request page because there's no view available, so a text/plain error is returned instead. This is fine …
=> Validate invalid session ID cookies earlier

lib/MusicBrainz/Server/WebService/Serializer/JSON/LD.pm, t/lib/t/MusicBrainz/Server/Controller/Area/Aliases.pm, t/lib/t/MusicBrainz/Server/Controller/Area/Show.pm, t/lib/t/MusicBrainz/Server/Controller/Artist/Aliases.pm, t/lib/t/MusicBrainz/Server/Controller/Artist/Recordings.pm, t/lib/t/MusicBrainz/Server/Controller/Artist/Relationships.pm, t/lib/t/MusicBrainz/Server/Controller/Artist/Show.pm, t/lib/t/MusicBrainz/Server/Controller/Label/Aliases.pm, t/lib/t/MusicBrainz/Server/Controller/Label/Show.pm, t/lib/t/MusicBrainz/Server/Controller/Place/Aliases.pm, t/lib/t/MusicBrainz/Server/Controller/Place/Show.pm, t/lib/t/MusicBrainz/Server/Controller/Recording/Aliases.pm, t/lib/t/MusicBrainz/Server/Controller/Recording/Show.pm, t/lib/t/MusicBrainz/Server/Controller/Release/Aliases.pm, t/lib/t/MusicBrainz/Server/Controller/Release/CoverArt.pm, t/lib/t/MusicBrainz/Server/Controller/Release/Show.pm, t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Aliases.pm, t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Show.pm, t/lib/t/MusicBrainz/Server/Controller/Work/Aliases.pm, t/lib/t/MusicBrainz/Server/Controller/Work/Show.pm
In order to make `@context` properly machine-readable, we should be pointing at the actual JSON-LD context file, as per https://schema.org/docs/developers.html
I'm keeping the link as HTTP because that's what we do all over our JSON-LD and schema.org say it's fine.
=> MBS-12716: Output the right JSON-LD @context

lib/MusicBrainz/Server/Data/Rating.pm, t/lib/t/MusicBrainz/Server/Controller/Rating.pm
With the previous implementation, we first checked inside a transaction whether a rating existed, then we tried to insert it if not. While that seemed sensible, it was causing issues when concurrent transactions happened - both would check that the rating did not yet exist, then one would insert it, and the second would ISE because it now existed.
To avoid this (and limit the number of queries while at it) this does an `INSERT ON CONFLICT DO UPDATE` instead - we always want to either `INSERT` or `UPDATE` anyway, so we don't need to check anything in advance. This should ensure that if two requests are sent in quick succession, the first inserts the rating and the second seamlessly updates it.
Added a basic test for the `/rate` page while at it, since we didn't seem to have a test that …
=> MBS-12685: Avoild ISE because of concurrent rating transactions

lib/MusicBrainz/Server/Data/Vote.pm, lib/MusicBrainz/Server/Edit.pm, root/user/UserProfile.js, root/utility/edit.js, t/lib/t/MusicBrainz/Server/Controller/Edit/Show.pm
As agreed on the 2022-11-07 team meeting.
These restrictions were introduced before we had a proper reporting / moderation system, and hopefully they are not needed anymore. They also make life a lot harder as a good beginner editor.
The restrictions that still allow for beginner editors after this are the following:
a) They are not allowed to disable banner alerts when they receive new edit notes on their edits. This seems sensible, since we want to train beginners to be responsive to edit notes.
b) Their bio and URL are hidden from logged-out users to limit spam effectiveness.
In addition, edits can still be filtered by whether the editor is a beginner and the editor report for admins still works.
While doing this I also simplified the description for beginners in …
=> MBS-10614: Remove edit note / vote restrictions for beginners

lib/MusicBrainz/Server/Entity/URL/Audiomack.pm
ISE when displaying a page with Audiomack URL in the sidebar
Amend #2743 by importing the missing `l` sub from `Translation` package.
=> Fix an ISE when displaying Audiomack link in the sidebar

lib/MusicBrainz/Server/Data/Area.pm
For some reason we were checking for open edits on `can_delete` for areas. This is what we do for entities that are autoremoved when empty, but areas are not one of those. In fact, this being here was blocking area removals entirely AFAICT, since any removal edit would be rejected because that same edit was open at the time of the `can_delete` check.
=> MBS-12778: Don't block area removal based on open edits

lib/MusicBrainz/Server/Edit/Relationship/Create.pm, root/edit/details/AddRelationship.js, root/types/edit_types.js
This was checking for the `entity0` and `entity1` passed outside the `relationship` itself - which we were also adding to the relationship data for display. But we were only passing this if the ID was not defined in the first place, so this check was nonsensical AFAICT. In fact, I cannot find any reason to pass `entity0` and `entity1` outside the `relationship`, since we're already passing them inside it.
I'm also removing the `source_type` and `target_type` that I had added in 9b0eae3e837e848c5eecb71b574185a37a2e9387 since AFAICT we're again not using those, but the ones inside the `relationship` object.
I tested this with `/edit/92070356` (the one where both sides were removed that triggered the ticket), with a new URL being added to a new release (to make sure release preview *does* …
=> MBS-12780: Fix allowNew check for AddRelationship

root/release/edit/tracklist.tt
For some reason we were missing the "`error`" class on these, meaning they just showed as a normal black text line that was very easy to miss.
Tested the parse error manually - not sure how to trigger the search one, but it should work in the same way.
=> MBS-12784: Mark more tracklist errors as such

root/static/scripts/relationship-editor/components/RelationshipItem.js, root/static/scripts/relationship-editor/utility/prepareHtmlFormSubmission.js
The overconfident check we had was hitting issues for recordings creating during the NGS migration which had the same rowid as the associated works.
We have a perfectly working `isRelationshipBackward` check, so this just changes the code to use it.
Tested manually with the examples on the ticket.
=> MBS-12737: Properly check backwardness with isRelationshipBackward

root/static/scripts/relationship-editor/utility/splitRelationshipByAttributes.js, root/static/scripts/tests/relationship-editor.js
Fixes https://tickets.metabrainz.org/browse/MBS-12787
If a "members" relationship is added without any instruments, submitted, and then edited to add instruments, then the relationship will be duplicated for each instrument (or vocal) instead of adding at least one to the existing relationship.  ("members" is just an example, as this could apply to any relationship type supporting instruments or vocals.)
The solution is, if the existing relationship has no instruments or vocals, to take the first new instrument or vocal that would otherwise be split, and merge it into the existing relationship's attributes.
The "first" instrument or vocal chosen is the one with the lowest link attribute type ID, hence why the added test expects vocals to be chosen for merging over drums.
=> MBS-12787: Editing a relationship to add instruments causes duplication

root/static/styles/relationship-editor.less
It seems `.rel-editor-dialog` is now `.relationship-dialog`, but we forgot to update the CSS accordingly.
=> MBS-12817: Fix selector for relationship dialog warnings

lib/MusicBrainz/Server/Edit/Historic/RemoveDiscID.pm, root/static/scripts/common/components/CDTocLink.js, root/types/edit_types_historic.js
We were trying to build a new CDTOC from the discid alone, which actually goes against our definition of a `CDTOC` entity. This was now breaking in `TO_JSON` since it now expects a `track_offset`.
Rather than making that optional everywhere, I'm just passing a "minimal-cdtoc" JSON object with the data we have and allowing `CDTocLink` to use it - it does not need anything else, in any case.
=> MBS-12809: Pass minimal existing data for Historic/RemoveDiscID

root/static/scripts/relationship-editor/components/DialogAttribute/MultiselectAttribute.js
Having no label in some cases is breaking the display of the + icon. Even without that, having a generic label is a lot easier to understand than having none.
=> MBS-12820: Add default label for attribute multiselects

root/static/scripts/relationship-editor/components/RelationshipPhraseGroup.js
While it's generally fairly useful to preload a new relationship with the attributes of the existing one, this is never the case with series part numbers - you almost always want each relationship to have a different number. As such, this stops them from being preloaded.
=> MBS-12709: Do not copy series part number with "Add another [entity]"

root/static/scripts/common/components/Autocomplete2.js, root/static/scripts/common/components/Autocomplete2/formatters.js, root/static/scripts/common/components/Autocomplete2/reducer.js, root/static/scripts/common/components/Autocomplete2/types.js, root/static/scripts/relationship-editor/components/DialogLinkType.js, root/static/styles/widgets.less
This fixes MBS-12630 by adding a "Show/hide descriptions" action at the end of link type and link attribute type (including instrument) autocomplete menus.  This preference is stored as a cookie so that it doesn't need to be constantly toggled off (as it defaults to true).
The above change by itself makes the menus a lot more compact, but in addition, I've also changed how link type results are displayed based on feedback from Aerozol by just showing "Forward link phrase / reverse link phrase" (so, no longer showing the actual type name, and no longer showing the "Forward link phrase:" and "Backward link phrase:" labels). Additionally, if the reverse link phrase is identical to the forward one once translated and stripped of attributes, only the forward one is shown.
=> MBS-12630: Make the relationship type autocompletes more compact

root/static/scripts/relationship-editor/components/RelationshipDialogContent.js
This follows the most natural-language-y flow (at least for English): "Entity Type" "Source" "Rel Type" "Target"
(e.g. "Artist Foo studied at Bar")
This does mean the attributes do not immediately follow the rel type even though they depend on it; had a discussion with @mwiencek and @aerozol and we all agreed that having the target further up is more important for clarity.
=> MBS-12693: Select relationship type before target

lib/MusicBrainz/Server/Data/Editor.pm, lib/MusicBrainz/Server/Form/Utils.pm, t/lib/t/MusicBrainz/Server/Controller/User/Register.pm
Fixes https://tickets.metabrainz.org/browse/MBS-12827
This shows an error on the registration form (and should also show one on the admin edit user form) if the name doesn't match the sanitized version of the name.  I imagine this will mostly be accidentally triggered by people adding extraneous whitespace characters. Suggestions for how to best word the error message are appreciated.
If an unsanitized username somehow makes it past our form validation, the editor data layer performs the same check and possibly dies.
=> MBS-12827: Run our sanitize function on new usernames

admin/sql/InsertTestData.sql, t/lib/t/MusicBrainz/Server/Controller/Artist/AddAnnotation.pm, t/lib/t/MusicBrainz/Server/Controller/Artist/Details.pm, t/lib/t/MusicBrainz/Server/Controller/Label/AddAnnotation.pm, t/lib/t/MusicBrainz/Server/Controller/Label/Details.pm, t/lib/t/MusicBrainz/Server/Controller/Recording/AddAnnotation.pm, t/lib/t/MusicBrainz/Server/Controller/Recording/Details.pm, t/lib/t/MusicBrainz/Server/Controller/Release/AddAnnotation.pm, t/lib/t/MusicBrainz/Server/Controller/Release/Details.pm, t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/AddAnnotation.pm, t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Details.pm, t/lib/t/MusicBrainz/Server/Controller/Series/AddAnnotation.pm, t/lib/t/MusicBrainz/Server/Controller/Series/Details.pm, t/lib/t/MusicBrainz/Server/Controller/Work/AddAnnotation.pm, t/lib/t/MusicBrainz/Server/Controller/Work/Details.pm, t/sql/series.sql
I'm changing a lot of tests that we already had for several entities, because it seems a lot easier to see all the updates to them in one commit each rather than slowly doing them per entity.
=> Improve test documentation (IX): Shared tests (Annotation/Details)

t/lib/t/MusicBrainz/Server/Controller/Area/Create.pm, t/lib/t/MusicBrainz/Server/Controller/Artist/Create.pm, t/lib/t/MusicBrainz/Server/Controller/Instrument/Create.pm, t/lib/t/MusicBrainz/Server/Controller/Label/Create.pm, t/lib/t/MusicBrainz/Server/Controller/Place/Aliases.pm, t/lib/t/MusicBrainz/Server/Controller/Place/Create.pm, t/lib/t/MusicBrainz/Server/Controller/Place/Show.pm, t/lib/t/MusicBrainz/Server/Controller/Series/Create.pm, t/lib/t/MusicBrainz/Server/Controller/Series/Show.pm, t/lib/t/MusicBrainz/Server/Controller/Work/Create.pm, t/sql/place.sql
I'm changing a lot of tests that we already had for several entities, because it seems a lot easier to see all the updates to them in one go each rather than slowly doing them per entity.
For some reason, a bunch of entities are completely missing Create tests. Documenting it for now, we can add them later when we get to the specific folders.
=> Improve test documentation (X): Shared tests (Create)

t/lib/t/MusicBrainz/Server/Controller/Area/Edit.pm, t/lib/t/MusicBrainz/Server/Controller/Artist/Edit.pm, t/lib/t/MusicBrainz/Server/Controller/Instrument/Edit.pm, t/lib/t/MusicBrainz/Server/Controller/Label/Edit.pm, t/lib/t/MusicBrainz/Server/Controller/Place/Edit.pm, t/lib/t/MusicBrainz/Server/Controller/Recording/Edit.pm, t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Edit.pm, t/lib/t/MusicBrainz/Server/Controller/Series/Edit.pm, t/lib/t/MusicBrainz/Server/Controller/URL/Edit.pm, t/lib/t/MusicBrainz/Server/Controller/Work/Edit.pm, t/sql/mbs-8636.sql
I'm changing a lot of tests that we already had for several entities, because it seems a lot easier to see all the updates to them in one go each rather than slowly doing them per entity.
=> Improve test documentation (XI): Shared tests (Edit)

HACKING.md
We no longer pass `$c` to every top component, as HACKING still claimed, so reworded that a bit in a way that I think is correct.
=> Update the ways to access $c from JavaScript

root/static/scripts/relationship-editor/components/DialogPreview.js
Showing disambiguation comments is disabled when previewing relationships in the relationship editor. 
I'm not sure why this was actively disabled here (the commit history shows nothing about it) but it certainly seems useful to see the disambiguations in the preview. There's at least two cases where this can be very useful:
1) When the two entities have the same or a very similar name, so the disambiguation is the main way to understand the selected order.
2) When the editor misclicked and picked another entity with the same name as the intended one, having the disambiguation here makes it easier to notice and fix immediately.
Just remove the parameter disabling disambiguations.
Tested manually. Since this is the default mechanism for `EntityLink`, I understand there's no need to create …
=> MBS-12831: Don't hide disambiguations in relationship previews

entities.json, entities.mjs, lib/MusicBrainz/Server/Controller/WS/js.pm
When using recent entities in an autocomplete search, the data returned is sometimes not enough to be sure of which entities they actually are. This is specially true of areas and places, which have containment info when you search for them, but no longer have it when loaded as part of the list of recent entities.
Additionally, in beta, a regression has been added where the entity type is also not saved (or rather, not loaded) in the recent entities list.
Since beta uses the `WS::js` `/entities` endpoint to load all the recent items from their ID, I added a few extra conditional loads there, for entity types on all entities with them and for area and containment for areas/places.
Manually, by searching for items in Add relationship popups and then reloading the page and checking what data …
=> MBS-12857 / MBS-12858: Details for recent entities in autocompletes

root/static/scripts/common/components/ButtonPopover.js, root/static/scripts/relationship-editor/hooks/useRelationshipDialogContent.js, root/static/scripts/release/components/RelationshipEditorBatchTools.js, t/selenium/Release_Relationship_Editor.json5
Likely fixes MBS-12860
This reverts commit 6230a40b799f0879408fe03d79d8fce83293c0d3.
That commit caused new relationship IDs to become reused by memoizing the initial relationship data seeded to dialogs.  It can be safely reverted in full because it was an unnecessary optimization in the first place.
You can trigger the reported error by adding two area relationships to any entity in the release relationship editor.  You can trigger it for target types other than area too, but the catch is that the memoized ID only changes when the target type changes, *after* the dialog is closed. So to trigger it for artist relationships from a fresh page, you'd have to add three artist relationships to the same entity.
While I can't be 100% certain this is the only cause of the key error, it seems …
=> MBS-12860: Fix "Two relationships with the same key" error

root/static/scripts/common/utility/natatime.js, root/static/scripts/release/components/ReleaseRelationshipEditor.js
Prior to this commit, the release relationship editor would group edit submission requests by entity, and submit them at a rate of one entity per second; so if you made 100 edits to one recording it would submit them all in one request, but if you made 1 edit each to 100 recordings it would take roughly 100 seconds to complete.
("Per second" is a rough estimate, since what it actually does is wait for each request to complete before starting the next one, and additionally wait 500 ms before each request.)
The implementation in this commit is more consistent and much faster in the average case.  Requests are no longer grouped by entity; we simply submit 25 edits per request, for all requests.
I made 100+ edits to a release locally and watched the network request log in the browser …
=> MBS-12832: Improve edit submission batching in the release relationship editor

root/static/styles/forms.less
Cover art checkboxes are now left-aligned, while they used to be aligned centrally like "comment" below them.
I found out that the styling for `form fieldset.row legend` was dropped with 165f7c7f727969d796ae73ec0b30d83dccd363f9 - this seems to only be used in one place (here) so that's probably why it was overlooked.
I could use `label` instead of `legend` rather than restoring this extra option, but `legend` is AFAIK more correct for `fieldset`s.
Manually, on `/release/25a5a840-37bc-4c7c-800b-babca39d71cb/edit-cover-art/34816166820` (`pink` data)
=> MBS-12880: Support fieldset.row legend styling again

root/static/scripts/relationship-editor/components/DialogEntityCredit.js, root/static/scripts/relationship-editor/components/DialogPreview.js, root/static/scripts/relationship-editor/components/RelationshipDialogContent.js, t/selenium.mjs, t/selenium/MBS-12859.json5
The new relationship editor ignores / silently drops entity credits for relationships when they match the name. This is a break with the way the previous relationship editor worked, and it was a feature, not a bug: it was being intentionally used before to ensure credits remained as printed even if the artist name itself changed (for example, a Russian orchestra credited by a Latin name, where we want the printed Latin credit to stay the same even if someone correctly improves the artist name to the original Russian later).
A minor secondary issue found while testing the change is that https://github.com/metabrainz/musicbrainz-server/pull/2805 only applied to entities without a credit, since `EntityLink` hides the disambiguation when custom content is passed unless explicitly told not to …
=> MBS-12859: Allow relationship credit to be the same as name 

root/static/styles/relationship-editor.less, root/static/styles/tooltip.less
This fixes the tooltip positioning in the external links editor and relationship dialog. An override has been added for the batch tool buttons, to keep the existing 50% positioning, since 100% makes it possible for the last button's tooltip to clip outside the viewport.
=> MBS-12863: Tooltips too far to the left

root/static/scripts/common/components/Popover.js
Pressing tab on the last element inside a Popover or shift-tab on the first element will close the dialog.
Sets the Dialog trapFocus prop to true in the Popover component so that tab/shift-tab cycles.
Tested manually only.
Note that unlike the Modal component, clicking outside the Popover will not return focus to it, so you can still click on links etc. outside of it if needed.
=> MBS-12870: Trap focus inside the Popover component

root/static/scripts/common/utility/isDateEmpty.js, root/static/scripts/edit/components/DateRangeFieldset.js, root/types/entity.js
Currently, when using the copy date button to copy a date (for example in the alias editor), the "Ended" checkbox is not checked.
This is mostly just a visual issue, since having an end date implies ended and the checkbox is actually checked when removing the new date (this last bit might be unintentional though). In any case, it'd still a lot more clear if the (automatically disabled) ended checkbox is shown as checked rather than unchecked while frozen.
In the reducer, I added the same check and dispatch call for `set-ended` on `case 'copy-date'` that we already had in the manual change dispatch, `case 'update-end-date'`.
I noticed while doing this that the check was broken, in that `isDateEmpty` would still claim the date is not empty for a case such as `{year: ''}`. I improved the …
=> MBS-12888: Check ended when copying end date

root/admin/components/UserList.js
It's trivial to find out (with the IP lookup) what users share an IP with a known spammer. But the information on that view is pretty useless to figure out if any of those accounts are themselves spammers. Compared with the (much more useful) beginner editor report, the main things missing there are the user bio and website.
This adds the bio and website to the `UserList` component used by `IpLookup`, `EmailSearch` and `PrivilegeList`. While the info is probably less obviously useful in the last two, I don't think it ever hurts, and it can sometimes still help, so I am not restricting it to `IpLookup` only.
Manually, from the `EmailSearch` component (since I don't have IPs stored locally) - since the code used is the same, it should work on the other two as well.
=> MBS-12901: Show user website and bio on the admin user views

root/static/scripts/common/components/Autocomplete2/formatters.js
Labels and genres with disambiguation comments do not show it when searching in an autocomplete2 inline search (for example to add relationships).
Running the labels and genres through `formatGeneric` will give them the bare minimum that they should have: disambiguation and primary alias when relevant. We could also add types to labels (and artists) but that's not a regression so it can be done later.
Manually, with **PMDC** for label search (easy from a release) and **bolero** for genre search (easy from an instrument).
=> MBS-12890: Show disambiguation in label/genre autocompletes

lib/MusicBrainz/Server/Controller/WS/js/Artist.pm, lib/MusicBrainz/Server/Controller/WS/js/Label.pm, root/static/scripts/common/components/Autocomplete2/formatters.js, t/lib/t/MusicBrainz/Server/Controller/WS/js/Autocomplete.pm
Inline search for labels and artists often offers frustratingly little info, especially when compared with something like a work search. Often knowing the type or the dates for an artist / label will automatically make it obvious it's the right choice or, at the very least, disqualify it from the possibilities, meaning there's one less entry the editor needs to check more carefully - but neither of these are present, while they are for other kinds of entities.
This adds both artist/label dates and type, when present, in a new row for Autocomplete2.
If all we know is an artist/label is ended, this currently doesn't indicate anything. If you think it should, we can make the change!
By hand, with both direct and indexed search, searching artists and labels and making sure they show the info …
=> MBS-12891 / MBS-7971: Show more info for inline artist/label search 

lib/MusicBrainz/Server/Controller/WS/js.pm
Autocomplete2 loads useful additional data for works (related artists), recordings (ISRCs and RGs), releases (labels and release events) and events (related artists and places) when searching, but this data is missing from the recent entries when pasting an MBID and/or when reloading the page.
This makes sure the data is also loaded on those two cases.
By hand, with sample data, searching for "a" and picking some of the first results that have the extra data to be tested (since the data is always shown on first search, it's easy to find good testing cases).
=> MBS-11770: Always list autocomplete additional data for all entities

root/static/scripts/relationship-editor/components/DialogEntityCredit.js, root/static/scripts/relationship-editor/components/DialogSourceEntity.js, root/static/scripts/relationship-editor/components/DialogTargetEntity.js, root/static/scripts/relationship-editor/components/RelationshipDialogContent.js, root/static/scripts/relationship-editor/components/RelationshipEditor.js, root/static/scripts/relationship-editor/components/RelationshipItem.js, root/static/scripts/relationship-editor/components/RelationshipLinkTypeGroup.js, root/static/scripts/relationship-editor/components/RelationshipPhraseGroup.js, root/static/scripts/relationship-editor/components/RelationshipTargetTypeGroup.js, root/static/scripts/relationship-editor/components/RelationshipTargetTypeGroups.js, root/static/scripts/relationship-editor/hooks/useRelationshipDialogContent.js, root/static/scripts/relationship-editor/types.js, root/static/scripts/release/components/MediumRelationshipEditor.js, root/static/scripts/release/components/RelationshipEditorBatchTools.js, root/static/scripts/release/components/ReleaseRelationshipEditor.js, root/static/scripts/release/components/TrackRelationshipEditor.js, root/static/scripts/release/components/TracklistAndCredits.js, root/static/scripts/tests/relationship-editor/dialog.js
Since the new React implementation of the release relationship editor avoid loading all the tracks for the big releases by default, the batch tools for changing credits in relationships (MBS-12873) and for linking to recordings and works (MBS-12875) don’t work nicely as described and as it used to be in the previous implementation of release relationship editor.
Disable every checkbox related to these tools until all the related tracks have been loaded. Accompany such disabled checkbox with an help message.
It just uses a computation of the loading status already used for the release overview page.
The release relationship editor is expected to re-render only one more time after having loaded all the missing tracks.
The longer-term solution is to load all tracks when ticking such checkbox …
=> MBS-12873, MBS-12875: Avoid unloaded tracks when batch editing release relationships

root/static/scripts/common/utility/areDatesEqual.js, root/static/scripts/tests/utility.js
See the attached gif in MBS-12882.
This was due to `areDatesEqual` not treating `null` and `{year: null, month: null, day: null}` as both being empty partial dates.
Modify `areDatesEqual` to use `isDateEmpty`, which fixes the issue.
Tested manually by repeating the same action as in the referenced gif.  Added some basic unit tests for `areDatesEqual` which cover the failure.
=> MBS-12882: Adding & removing a relationship date shows pending edits

root/static/scripts/common/components/Autocomplete2.js, root/static/scripts/relationship-editor/components/DialogLinkType.js, root/static/scripts/relationship-editor/components/DialogTargetEntity.js, root/static/scripts/relationship-editor/components/DialogTargetType.js, root/static/scripts/relationship-editor/components/RelationshipDialogContent.js, root/static/scripts/relationship-editor/components/RelationshipItem.js, root/static/scripts/relationship-editor/components/RelationshipPhraseGroup.js, root/static/scripts/relationship-editor/components/RelationshipTargetTypeGroups.js, root/static/scripts/relationship-editor/hooks/useRelationshipDialogContent.js, root/static/scripts/release/components/RelationshipEditorBatchTools.js, root/static/scripts/release/components/TrackRelationshipEditor.js, root/static/scripts/tests/relationship-editor/dialog.js, t/selenium.mjs, t/selenium/MBS-12641.json5
When opening the relationship editor dialog (whether for a new or existing relationship), we sometimes focus fields that are pre-filled and unlikely to be changed.  (See MBS-12641 and also [salo.rock's comment on the forums](https://community.metabrainz.org/t/help-test-the-relationship-editor-on-beta-musicbrainz-org/621824/34).)
We now choose which field to initially focus based on the following priorities:
* If no target type is preselected, focus that.
This is not the same as the field being empty, since you can't empty the target type field. It's about whether the target type is determined by the type of dialog being opened.
I renamed `defaultTargetType` to `preselectedTargetType` in the code to make this clearer.
* If no link type is preselected, focus that.
* Otherwise, focus the …
=> MBS-12641: Relationship dialog initial focus improvements

root/static/scripts/common/components/Autocomplete2/formatters.js, root/static/scripts/common/components/Autocomplete2/recentItems.js, root/static/scripts/relationship-editor/components/DialogLinkType.js, root/static/scripts/relationship-editor/components/RelationshipDialogContent.js, root/static/scripts/relationship-editor/utility/getDialogLinkTypeOptions.js
When you select a link type in the relationship dialog, we set the autocomplete input value to the link type name rather than the phrases we showed in the menu. For example, if you select "recording engineer for / recording engineer," we set the input value to just "recording."
When a selection is made, the input value is now the same "forward phrase / reverse phrase" text we showed in the menu.
I decided not to change the input value based on the direction of the relationship, because the forward/reverse link phrases aren't meant to be read in sentence order like the long link phrases are, so I don't think it makes the selection easier to understand. It's also harder to implement.
Tested manually both by searching for a link type and selecting it from the results, and selecting a link …
=> MBS-12829: Use link type phrases in autocomplete input value

root/static/lib/jquery.ui/ui/jquery-ui.custom.js, root/static/scripts/relationship-editor/components/RelationshipEditor.js, t/selenium.mjs, t/selenium/MBS-12904.json5
You can reproduce MBS-12904 as follows:
1. Open /recording/create and enter a title.
2. Search for a recording artist that isn't already in the recent entities list, and select it.
3. Add a relationship to the same artist you selected, choosing it from the recent entities list.
4. Enter an edit note and submit the form.
The recording will be submitted, but the relationship you added won't.
This issue is very similar to [MBS-12694](https://tickets.metabrainz.org/browse/MBS-12694), but involves selecting the recording artist from a search first in order to push it onto the recent entities list.
The issue was that, when displaying search results, jQuery UI would modify the entity JSON to add undefined `label` and `value` properties as part of its "normalization" process. These undefined …
=> MBS-12904: Fix another error submitting a recording artist relationship

lib/MusicBrainz/Server/Validation.pm, t/lib/t/MusicBrainz/Server/Validation.pm
A user recently entered an all-zeros IPI in [edit #96404467](https://musicbrainz.org/edit/96404467), possibly in order to fill the field with *something*. I'm pretty sure it is not a valid IPI, so we should probably just block it in the future
Add a check to `is_valid_ipi` to return false if the IPI is all zeros. Since `format_ipi` specifically zero-fills the IPI to 11 digits, we can be sure it should always be 11.
Added a new check to the `is_valid_ipi` test.
=> MBS-12853: Disallow IPI that is all zeros

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
The DNB regex has been problematic for a while. It used to be too wide, and we tried to standardize it following the regex Wikidata uses, but it turns out that is instead too strict and is blocking some valid links, such as https://d-nb.info/97248485X
outsidecontext got in touch with DNB and asked for better clarity on what the IDs can look like. The answer wasn't super clear, but the best we got from it is that it's probably safe to assume 9 or 10 character long IDs containing digits, hyphen or X, so that's what I'm implementing here. It could be possible to be more specific, maybe, but we've already been bitten by that, and honestly I think this is probably good enough for our needs.
All the current tests pass, plus added a new one for the previously blocked URL.
=> MBS-12665: Widen DNB regex

root/static/scripts/common/components/Autocomplete2.js, root/static/scripts/relationship-editor/components/DialogPreview.js, root/static/styles/forms.less, root/static/styles/relationship-editor.less
In https://community.metabrainz.org/t/help-test-the-relationship-editor-on-beta-musicbrainz-org/621824 the discussion about how required fields should be displayed seemed to settle around showing both a red highlight (already done) and an asterisk (implemented in this commit, for color blind users if nothing else).
Before:
After:
I checked the display in Firefox, Safari, and Chromium on macOS, and it seemed fine in all of them.
=> Relationship editor required field style redux

root/user/UserProfile.js
Right now, visiting the user page for a spammer editor will clearly identify them as spammers, but someone who has just had their edit or edit notes privileges disabled, or is set as untrusted, is not visible to the admin until they go to the edit user page. 
Added a second `Warning` for admins in the same place as the spammer one which specifies which restrictions a given user has (editing disabled, notes disabled, untrusted).
Manually, by changing the privs of a random editor in the sample data.
=> MBS-12896: Show admins whether user is banned from profile

root/static/scripts/relationship-editor/components/RelationshipPhraseGroup.js, t/sql/initial.sql
When adding events and creating a new artist relationship based on an existing one that has the attributes "cancelled" and/or "time", those get prefilled for the new relationship. This is usually a desired behaviour, but it's unlikely that most artists will be performing at the same time and one being cancelled doesn't mean others are likely to be, so these two are likely to mostly get in the way.
When cloning the relationship data, drop these two attributes.
Manually, from `/event/create`.
=> MBS-12908: Do not reuse "cancelled"/"time" for artist-event rels

root/static/scripts/common/entity.js, root/static/scripts/edit/components/forms.js, root/static/scripts/edit/utility/getRelatedArtists.js, root/static/scripts/edit/utility/guessFeat.js, root/static/scripts/edit/utility/isEntityProbablyClassical.js, t/selenium.mjs, t/selenium/MBS-11529.json5
An exception is thrown on beta if you try to use the "Guess feat. artists" button outside of the release editor (MBS-12903).
Additionally, if we fix the exception then it has weird behavior (MBS-11529) where it removes the primary artist.
The exception is fixed by making sure the `guessFeat` module is using the same source entity object as `initializeArtistCredit`.
The weird behavior is fixed by syncing the knockout and React state correctly.
Tested manually on recording pages. A Selenium test has been added for MBS-11529 (which would have also failed due to MBS-12903 in either case).
Also quickly checked that the "guess feat." button still works in the release editor for the release title and track titles.
=> Fix MBS-11529 / MBS-12903: "Guess feat. artists" issues

lib/MusicBrainz/Server/Controller/WS/js.pm
I missed work languages in https://github.com/metabrainz/musicbrainz-server/pull/2843. We show these for direct search results and when pasting an MBID, but we were not loading them for recent entries on reload.
Also load work languages in the `/entities` endpoint.
Manually by searching, selecting a work with a language, and then reloading to make sure the language still shows.
=> MBS-11770 (erratum): Load work languages for recently used works

root/static/styles/extra/wikidocs.less
It's often unclear where a direct link to a fragment is pointing when opening a doc page, especially when the page
is short enough the browser does not load the linked section at the top of the window. For example, following https://musicbrainz.org/doc/Style/Relationships/URLs#When_to_remove in my computer shows the following, which does not suggest at all the user should be looking at "When to remove":
I added a CSS highlight in `wikidocs.less` so that the target element will be highlighted in `@highlight-table-row` yellow (like highlighted edit notes with direct links).
This at least highlights the header for that section; sadly, in order to highlight more than that we'd probably need to either change the HTML to have the fragment ids on a `<section>` surrounding the heading + …
=> MBS-12816: Highlight doc header when linking to fragment

lib/MusicBrainz/Server/Entity/Release.pm, root/layout/components/sidebar/ReleaseSidebar.js, root/static/scripts/common/entity2.js, root/types/release.js, t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
The new "Play on ListenBrainz" button is appearing on every MusicBrainz release, even those which have no tracks at all. This just wastes the user's time if they click it (plus LB returns an ISE at the moment, but even if they returned a better "this is empty" page it would still be useless).
I couldn't find any good, straightforward way to check for emptiness with the current code, so I added a new `has_no_tracks` method that just checks whether mediums exist at all, and if they do, whether all have 0 tracks.
This still shows the button if at least one medium on the release has tracks, since that should still be playable (it currently isn't because of a LB-side error which hopefully will be resolved soon).
Tested with `/release/8a5285e9-4ce6-4aef-b77b-458d8f25f00f`, …
=> MBS-12806: Do not show "Play on LB" button for empty releases

root/static/scripts/relationship-editor/hooks/useRelationshipDialogContent.js, t/selenium/Release_Relationship_Editor.json5
If you haven't previously added a relationship in the current editing session, the add-relationship dialog will default to selecting the first target entity type in the list, which can vary depending on the UI language. In production we default to "artist."
If artist is available, default to that or otherwise use the first item.
Tested manually in the release relationship editor.
=> MBS-12915: Default to 'artist' in the add-relationship dialog

root/static/scripts/common/components/Autocomplete2.js, root/static/scripts/common/components/Autocomplete2/reducer.js, t/selenium.mjs, t/selenium/MBS-12921.json5, t/selenium/MBS-12922.json5, t/sql/selenium.sql
Clicking "Add related work" and attempting to search for the pre-filled work name does not work in most cases.
The Autocomplete2 component was attempting to show recent items instead of performing a search, because of an incorrect check where it assumed recent items would show even if the input was non-empty (they won't).
The reason the issue only manifests in the "Add related work" dialog is because we pre-fill the input value with the recording name there.
I've also changed the set-menu-visibility action to only open the menu if there are actually items; prior to this commit you could see an empty "menu" open (i.e. a gray line) beneath the input, and hitting arrow-down to move the item position would throw an exception because there are no items to highlight.
Added a Selenium test which …
=> MBS-12921: Can't search for works in the "Add related work" dialog

lib/MusicBrainz/Server/Data/Artist.pm, root/static/scripts/common/components/Autocomplete2/searchItems.js, t/lib/t/MusicBrainz/Server/Controller/Instrument/Artists.pm
When searching for relationship types in the new relationship editor, the search results display indented based on the level of that specific result in the relationships tree. Level indents make sense when displaying the whole set of results as a static list (since then you can see that, say, "instrument" is a child of "performer"). But when filtering the list, if "instrument" is still indented, it will look like it's a child of whatever happened to be on top of it, which is at best useless and at worst makes the user think it's really connected to the previous result in the list.
I made `getItem` always drop `item.level`, since I am fairly sure there's no case where we could want a search result to be indented. We already remove `item.level` for recent items for the same reason.
I …
=> MBS-12926: Remove indents from Autocomplete search results

root/static/scripts/common/components/Autocomplete2/recentItems.js
Work language `[No lyrics]` shows correctly on the main list, but it regresses to `No linguistic content` for recent entities on reload.
This uses `localizeLanguageName` when formatting recent items for `Autocomplete2`. Luckily, we know when something is set to the key `language-lyrics` so we don't need to work too hard to figure it out.
Using `localizeLanguageName` here also means languages in the dropdown are actually translated also when they're in recent entities after a reload, which AFAICT they were not before.
Manually, by picking the `[No lyrics]` language on the batch-create works dialog, reloading, and making sure it still shows the right name (and also when using the French translation).
=> MBS-12932: Always show [No lyrics] in work languages

root/static/scripts/relationship-editor/components/RelationshipDialogContent.js, root/static/scripts/relationship-editor/hooks/useDialogEnterKeyHandler.js, root/static/scripts/release/components/BatchCreateWorksDialog.js, root/static/scripts/release/components/EditWorkDialog.js
Most pop-up dialogs in the release relationship editor can be submitted with Enter without issues, but that is not the case for the work dialogs (batch-create and edit), where pressing Enter does nothing.
This follows the example of `RelationshipDialogContent` by submitting on pressing Enter unless it is pressed while on a button (to avoid an Enter press on "Cancel" submitting the form).
I turned the batch-create fragment into a `div` to support `onKeyDown`; I added the `"form"` class because it seemed sensible for parity.
This means Enter no longer opens the dropdowns for work types, but that's already the case for the target type dropdowns in the other dialogs, so it does not seem problematic to me (if anything, it's more consistent). Space still opens them fine.
Tested manually, while …
=> MBS-12925: Allow submitting work dialogs with Enter

root/static/scripts/release/components/ReleaseRelationshipEditor.js
If the editor accidentally submits the release relationship editor without actually changing anything, it correctly disables the submit button and shows "Submitting edits..." while it deals with the submission, then it shows an alert that the user changed nothing. It never actually re-enables the submit button so we can actually make changes, though.
This just sends a `stop-submission` dispatch at the end of the edit submission process, to clear the `submissionInProgress` state and re-enable the submission controls.
Manually, with a random release relationship editor instance: first I clicked Submit, checked that after dismissing the alert that I added nothing the site enabled submission again. Then I actually made a change and submitted it to make sure the subsequent submission still …
=> MBS-12923: Stop submission when no changes made

lib/MusicBrainz/Server/Form/Field/Relationship.pm
When seeding a relationship without a type (for example, by clicking Add work on an artist's sidebar), we were showing an error on the JS level saying that a type was missing, so the user would add it before submission. Because the submit button is a buggy knockout mess and does not get disabled properly, it is still possible to try to submit the form without selecting the type as long as all the mandatory fields are filled, which then causes an ISE. 
This adds Perl-level validation to properly detect that the type is missing and blocks the form from submitting (reloads the page and form). I don't think the error here is currently being shown on the browser, but since it's the same string as for the JS one, it should be fine.
We generally want to have multi-level validation in forms …
=> MBS-12930: Validate relationship fields on Perl level

root/static/scripts/relationship-editor/components/RelationshipDialogContent.js, root/static/scripts/relationship-editor/components/RelationshipItem.js, root/static/scripts/relationship-editor/utility/getOpenEditsLink.js
In the previous relationship editor, we used to show (previous) pending edits by highlighting the entity in orange, but that's now how changes made during the active editor session are shown so that doesn't work anymore. We should still have some way of showing the users that edits are pending for the rel, so they can check them before they accidentally delete it, for example (right now they will get notified of pending changes if they open the edit relationship popup, but not if they just enter a removal).
I decided to show a small warning sign, with the same pending edits link on hover as we use once you in the relationship editing popup:
Manually, as per above example.
=> MBS-12919: Show warning icon when rel has pending edits

root/static/scripts/common/components/EntityLink.js
Since the refactoring commit a252f37bd1de585cf3f87660cc5bee44eaea80e0 in beta only, the title shown on hover every link to any entity credited under a different name and rendered with React is broken, wrongly showing sort name for artist and nothing for entity of other type.
- Improve test conditions instead of setting a default value to `nameVariation`
- Report any misuse of `nameVariation` depending on `content`’s type
Tested reproducing the bug in a work relationship editor
Noticed that React links to credited entities have been fixed in many other parts of the website
Agreed on not adding further test for this specific issue as it would be reported in development or through Sentry at least.
=> MBS-12917: Fix title of credited entity’s link

t/selenium.mjs
It's not always clear whether a Selenium test failure is due to a legitimate exception (although they are much less flaky lately in my experience).
Logging the browser console will help the pull request author determine if an actual exception occurred.
Tested manually with the steps in https://github.com/metabrainz/musicbrainz-server/pull/2859#discussion_r1114643305
Here's an example of what is logged for that failure:
```log
not ok 3 caught exception: TimeoutError: Waiting for element to be located By(xpath, //input[@id = 'change-matching-artists']) Wait timed out after 30161ms at /home/michael/code/musicbrainz-server/node_modules/selenium-webdriver/lib/webdriver.js:841:17 at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5)
---
operator: …
```
=> Log browser console after each Selenium test

root/static/scripts/relationship-editor/components/RelationshipDialogContent.js, root/static/scripts/tests/relationship-editor/dialog.js
In the React relationship editor, when selecting a new type of target entity, the previous credit string was wrongly used for relationship preview in the case where the target entity does not support credit.
Reset the credit string when updating target type.
Tested manually by following the steps provided in the ticket.
Added a CI test on dialog state.
=> MBS-12918: Reset credit string when updating target type

root/static/scripts/relationship-editor/components/DialogTargetEntity.js, root/static/scripts/relationship-editor/utility/updateWorkStates.js, root/static/scripts/release/components/ReleaseRelationshipEditor.js, t/selenium.mjs, t/selenium/MBS-12911.json5
See the description of MBS-12911.
Newly-created works don't have gids, so we have to compare by id instead in order to avoid "entities in a relationship cannot be the same."
Fixing this also revealed another situation where the "two relationships with the same key" error can be triggered; in order to resolve that, we have to keep track of the new relationship states as they are updated in the update-submitted-relationships action, so that subsequent updates to the same relationship are operating on the latest version of its state.
Added a Selenium test that links two newly-created works together with the "later version" AR, and checks that all edits are submitted successfully.
=> MBS-12911, MBS-12928: Can't link two new works together

docker/musicbrainz-tests/run_selenium_tests.sh, lib/MusicBrainz/Server.pm, lib/MusicBrainz/Server/Entity.pm, root/layout/components/Head.js, root/static/scripts/common.js, root/static/scripts/common/components/Autocomplete2.js, root/static/scripts/common/components/Autocomplete2/reducer.js, root/static/scripts/common/components/Autocomplete2/types.js, root/static/scripts/common/utility/setInputValueForReact.mjs, root/static/scripts/edit/utility/guessFeat.js, root/static/scripts/selenium.js, root/static/scripts/tests/autocomplete2.html, t/selenium.mjs, t/selenium/MBS-12911.json5, t/selenium/Release_Relationship_Editor.json5, webpack/client.config.mjs
Selecting a link type in the relationship dialog on Android freezes the page.
The `set-recent-items` dispatch causes an infinite loop of re-renders in Chrome on Android. Delaying the dispatch fixes it. I haven't determined why this doesn't occur on desktop, because the React internals are quite opaque to me.
The `cancelled` addition isn't strictly needed, but it's always a good idea to clean up your effects.
Tested manually in the Android Emulator.
=> MBS-12924: Fix page freeze after selecting a link type on Android

root/static/scripts/common/components/Autocomplete2.js, t/selenium.mjs, t/selenium/Autocomplete2.json5
See the description of MBS-12936.
In d4b15e9de756331755850ee6fb8479c0f42be14b I had intended to fix an issue where highlighting an item lower down in the list (thereby updating the scroll position), closing the menu (e.g. by hitting escape), and then re-opening the menu would not bring the scroll position back to the top of the list.  While I did fix that, there were some unintended effects when using a mouse: hovering over any item would cause the menu to scroll towards that item.
The actual intent is that we should only update the scroll position when using the arrow keys or when opening the menu. Obviously if a user can mouseover an item, then it's already in view, and we don't need to mess with their manual scrolling.
Tested manually with a trackpad.  Added a Selenium test.
=> MBS-12936: Don't update Autocomplete2 scroll position on item mouseover

root/static/scripts/relationship-editor/components/RelationshipEditor.js, root/static/scripts/tests/relationship-editor.js
Ticking "Change credits for other ... relationships on the page" and submitting the dialog has no effect unless you make other changes to the relationship.
Fixes the check in `update-relationship-state` to proceed with updating entity credits even if the source relationship did not change.
Tested manually and added a unit test.
=> MBS-12937: Changing credits should work without modifying the source relationship

root/static/scripts/relationship-editor/components/RelationshipPhraseGroup.js
When creating a new work for an artist, the relationships group editor is pre-filled with a relationship to the artist, but the relationship type is not selected. This is up to the user to select it. There is no point to allow adding a relationship of the same type if it isn’t defined yet, as there already is a button to add a new relationship of any type.
This issue has been uncovered by invariant error message in development mode.
Just hide the (+) button as long as no relationship type is selected.
Tried to reproduce it with the same steps as in the ticket.
Played with the relationship editor a bit.
=> MBS-12931: Hide (+) button if no relationship type

root/static/scripts/relationship-editor/components/RelationshipPhraseGroup.js, root/static/scripts/relationship-editor/hooks/useRelationshipDialogContent.js
See https://github.com/metabrainz/musicbrainz-server/pull/2867#issuecomment-1443779955
This fixes the underlying cause of MBS-12931 by converting linkTypeIDs stored as 0 to null before constructing the relationship state sent to the dialog.
It also adds some Sentry logging in case we see a link type of 0 in `useRelationshipDialogContent` again, though I think the previous fix for MBS-12931 (hiding the '+' button when there is no type) makes that very unlikely.
I tested this by reverting https://github.com/metabrainz/musicbrainz-server/pull/2867 locally and checking that an exception was not thrown if I added another relationship via clicking "+" next to a "no type" section. It correctly added the new relationship into a different section.
=> Convert 0 linkTypeIDs to null for the relationship dialog

root/server/response.mjs, root/static/scripts/common/components/EntityLink.js
It was reported in IRC that `captureMessage` doesn't include a stack trace.
Additionally, the events logged by Sentry for the template renderer aren't very useful, because they don't include the component or URL being rendered.
Change `captureMessage` to `captureException` in `EntityLink`.
Add `component` and `url` tags to Sentry events from the template renderer.
I tested that pages across the site still render (whether logged in or logged out), so the Sentry API calls don't cause any issue, though I haven't tested that the additional data is actually logged to Sentry properly. I can put this on test.mb to make sure.
=> Sentry template renderer logging improvements

root/static/scripts/edit/externalLinks.js
https://sentry.metabrainz.org/organizations/metabrainz/issues/1075744/?project=12
88a1a97b0709233f1919a217fc33a7fa381a98dc wrapped the ExternalLinksEditor component in `withLoadedTypeInfo`, which ensured that link_type and link_attribute_type data are loaded asynchronously before the component renders.
If the user happened to submit the form before `withLoadedTypeInfo` completed, then an invariant violation would be triggered due to the component ref being null.
Since there's no other case where this ref should be null, and since we know the user didn't intend to submit any link changes (otherwise they would have waited for the component to finish loading), we can just ignore the situation. If there was another error that somehow caused the ExternalLinksEditor to become unmounted, it …
=> Fix invariant violation submitting external links

root/static/scripts/edit/components/edit/ReleaseEventsDiff.js
https://sentry.metabrainz.org/organizations/metabrainz/issues/1078098/?project=12
Add the missing `nameVariation` prop to `ReleaseEventsDiff`. It's always `false` because the underlying content is `sideACountry.name` in either case.
I'm not 100% sure if this fixes every event logged to Sentry.
Tested by loading /edit/97380335 with my local server connected to floyd.
=> ReleaseEventsDiff: Add missing nameVariation prop

root/static/scripts/edit/components/HelpIcon.js, root/static/scripts/edit/components/Tooltip.js, root/static/styles/forms.less, root/static/styles/tooltip.less
The pending edits tooltip on artist credits was showing twice and weirdly broken. On checking it a bit more, I found out it was a hydration error: `Expected server HTML to contain a matching <div> in <span>`. Apparently, `ArtistCreditLink` was trying to put the `Tooltip` `<div>` inside a `<span>`. This is invalid HTML, and React was not happy.
I made `Tooltip` accept a `ContainerElement` prop like `CollapsibleList` does, where we can specify we want `Tooltip` to use `<span>` containers when we are using it in an inline situation.
While `externalLinks` (via `HelpIcon`) and `RelationshipItem` were not currently causing issues, both of them had `Tooltip` inside inline elements (`<label>` and `<span>` respectively) so I also changed it to use `<span>`s there.
The tooltip content needs to …
=> MBS-12946: Don't put Tooltip div inside span

lib/MusicBrainz/Server/Edit.pm, root/edit/components/EditHeader.js, root/utility/edit.js, t/lib/t/MusicBrainz/Server/Controller/Edit/Show.pm, t/sql/vote.sql
For some reason, editors without a confirmed email cannot leave notes, but they can vote. I'm pretty sure this was an oversight rather than an intended ability, and it was made visible by us removing the beginner restrictions, which would have blocked most editors without an email from voting since it's hard to get 10 accepted edits when you cannot enter any.
This specifically checks for `email_confirmation_date` when checking if a user may vote, both on the Perl level (actually blocking the votes being submitted) and on the JS level (hiding the interface to submit votes).
I'm also blocking the "My vote" info on edit list headers for editors who cannot vote, since it makes no sense for them. This is consistent with the `EditIndex` page, where we already hid it.
Manually with a newly …
=> MBS-12958: Block voting without a confirmed email

root/components/Artwork.js, root/components/common-macros.tt
Our current fallback message if a CAA image fails to load is "_Image not available yet, please try again in a few minutes._"
A lot of the times, the image is not actually going to appear in a few minutes, but having that in the text makes people think the longer delay is uncommon and needs reporting. Sadly, it isn't.
This changes the "in a few minutes" wording to the more realistic "later". This will hopefully limit user's optimism and thus limit the amount of reports we have to answer with "shrug, it's the IA".
Since this message is also shown when images have been processed, but the IA is down, this also removes the "yet", which is weird when shown for an image that already worked before.
None, since it's a string change.
=> MBS-11565: Use less hopeful image not available message

lib/MusicBrainz/Server/Entity/CDTOC.pm
Some historic edits (such as the Move Disc ID edit `/edit/12446292`) don't have any other info for the `CDTOC` than the `discid` string itself. Trying to calculate the `track_offset` (which is unneeded there anyway) was causing an ISE.
It seems fine to have it return an empty array when missing, just like `track_details` already did, so I just made it do `@{ $self->track_offset // [] }`.
Manually in the given edit.
=> MBS-12962: Don't ISE on undef track_offset

lib/MusicBrainz/Server/Controller/WS/2/Artist.pm, lib/MusicBrainz/Server/WebService/Validator.pm
The `various-artists` include is used to request only releases where the artist is in the tracks but not the release (so, generally VA or featured releases). As such, it only makes sense if releases are being requested to begin with. Currently, `various-artists` was being accepted as an include even without the accompanying `releases` include, but was then silently ignored, which is not good UX.
This treats `various-artists` as an `extra-inc` for `releases`, meaning we only accept passing it if it will actually do something (i.e., if `releases` is also passed), and we reject it with some more info otherwise.
Locally by calling the API with/without `releases`, plus made sure the `LookupArtist` tests using `various-artists` still pass.
=> MBS-12848: Reject inc=various-artists without inc=releases

.flowconfig, package.json, root/components/RelationshipsTable.js, root/components/TagEntitiesList.js, root/edit/details/MergeReleases.js, root/layout/components/Search.js, root/static/scripts/common/components/AcoustIdCell.js, root/static/scripts/common/components/PostParameters.js, root/static/scripts/common/components/TagEditor.js, root/static/scripts/common/constants.js, root/static/scripts/common/i18n/expand2react.js, root/static/scripts/common/linkedEntities.mjs, root/static/scripts/common/utility/_cookies.js, root/static/scripts/edit/URLCleanup.js, root/static/scripts/edit/components/EnterEdit.js, root/static/scripts/edit/components/EnterEditNote.js, root/static/scripts/edit/components/FormRowCheckbox.js, root/static/scripts/edit/components/PartialDateInput.js, root/static/scripts/edit/components/edit/RelationshipDiff.js, root/static/scripts/edit/externalLinks.js, root/static/scripts/release/components/WorkLanguageMultiselect.js, root/static/scripts/release/components/WorkTypeSelect.js, root/utility/compactEntityJson.js, script/generate_edit_data_flow_type.mjs, yarn.lock
First step to getting Flow up-to-date.
0.197.0 is the first version where `inference_mode=lti` is available in a non-experimental form, but I haven't enabled it in this PR because it'll require a lot more changes.
=> Upgrade Flow to 0.197.0

root/artist_credit/ArtistCreditIndex.js, root/artist_credit/EntityList.js, root/collection/CollectionIndex.js, root/components/Aliases/AliasTable.js, root/components/Aliases/AliasTableBody.js, root/components/Aliases/AliasTableRow.js, root/components/Aliases/ArtistCreditList.js, root/components/Aliases/index.js, root/entity/Aliases.js, root/entity/alias/AddOrEditAlias.js, root/entity/alias/DeleteAlias.js, root/layout/components/sidebar/CollectionLinks.js, root/layout/components/sidebar/CollectionList.js, root/static/scripts/alias/AliasEditForm.js, root/types/entity.js
In preparation for MBS-12552, many occurrences of generic types such as `CoreEntityT` are abusively used. It’s better than `any` but it can be refined.
- Introduce `EntityWithAliasesT` and `EntityWithArtistCreditsT`;
- Replace some (but not all) occurrences of `CoreEntityTypeT` with these;
- Drop unneeded `Core` from `CollectableCoreEntityT`.
Not needed but ESLint and Flow, as just changing types.
=> MBS-12552 (pre): Refine some Flow.js types

.eslintrc.yaml
We have JSX in several `.mjs` files, and this was triggering an eslint error.
Tell `jsx-filename-extension` that it is ok to have JSX in `.mjs` files.
I also changed the formatting of one rule because VSCode was telling me it was incorrect YAML formatting - although it did seem to still work anyway?
The errors went away.
=> Allow for JSX in .mjs files 

lib/MusicBrainz/Server/Data/Editor.pm, t/lib/t/MusicBrainz/Server/Data/Editor.pm
While technically email addresses are [meant to be case-sensitive](https://blog.teknkl.com/email-addresses-case-sensitive-but-anyway/) the whole internet treats them as if the were not. Just today I was going to answer to a user who wanted to be deleted that we did not have them on the DB to begin with, until I realized they had typed their email with different caps in different places and I notice we do check our emails case-sensitively in `search_by_email`. We don't elsewhere (our `is_email_used_elsewhere` comparison does `lower()` for comparison).
Turn the regex matching in `search_by_email` to case-insensitive.
Manually, making sure a search for my email but CAPITALIZED still matches my user(s) now. Also added a test case to Data::Editor.
=> MBS-12994: Treat email as case-insensitive for admin email search

lib/MusicBrainz/Server/Data/Vote.pm, lib/MusicBrainz/Server/Edit.pm, lib/MusicBrainz/Server/Entity/Editor.pm, root/edit/EditIndex.js, root/edit/components/EditHeader.js, root/edit/components/Vote.js, root/utility/edit.js
It seems sensible to hide the "My vote" header from users who are not verified and cannot participate in the voting system, but my previous implementation accidentally hid the vote info also from verified editors checking closed edits, since they unsurprisingly cannot vote on them either. Whoops.
This makes it do the thing I actually intended: hide this for editors who don't have the right to vote, but still show it for others.
I separated "Cannot vote" and "Cannot vote on this specific edit" as per @mwiencek's suggestion below, since sometimes (like here) we want to hide stuff from all non-voters, but sometimes (like when showing voting buttons) we care specifically about whether they can vote *here*.
Manually, by checking my own old votes and seeing it shows the right thing now.
=> MBS-12959: Only hide My vote in header for non-voting editors

lib/MusicBrainz/Server/Controller/WS/js.pm
`_detach_with_temporary_delay` incorrectly invokes `detach_with_error` by not wrapping the error key/value pairs in a hash ref.  In Perl, `=>` is the same as a comma except it auto-quotes bare words on the LHS.  So the result was that `'message'` was being passed as `$error`, and the `l(...)` string as `$status`.  This malformed `$status` value triggers a warning:
```
Argument "We\x{2019}ve hit a temporary del..." isn't numeric in numeric lt (<)
at /home/musicbrainz/carton-local/lib/perl5/Catalyst/Plugin/Cache/HTTP.pm line 228.
Argument "We\x{2019}ve hit a temporary del..." isn't numeric in numeric ge (>=)
at /home/musicbrainz/carton-local/lib/perl5/Plack/Middleware/FixMissingBodyInRedirect.pm line 18.
```
...and causes MBS to return an empty response and a 502 on the gateway server.
=> Fix empty response when hitting a temporary IA delay

lib/MusicBrainz/Server/Controller/Admin.pm, lib/MusicBrainz/Server/Data/Editor.pm, root/admin/EmailSearch.js, root/admin/IpLookup.js, t/lib/t/MusicBrainz/Server/Data/Editor.pm
In some cases, there's over 100 accounts using a dodgy IP or the same email pattern. In those cases, we want admins to be able to see (and possibly ban) them all, but the searches are currently limited to 100 results.
This adds pagination to both email and IP lookup. The IP pagination is fairly trivial. The email one is more complicated, since the email address is posted when submitting the form. We need to store it somewhere (I put it in `$c->session` at the suggestion of @mwiencek) and use it when navigating through the pages, since otherwise the results will be lost as soon as we navigate to page 2.
Email search tested manually with a specific user email (one result shows correctly, no pagination UI is shown) and with a wider search (`mailbox\.org`) with 10 pages of results (pagination …
=> MBS-12902: Add pagination to admin email/IP search

lib/MusicBrainz/Server/Edit/Historic/Relationship.pm
https://beta.musicbrainz.org/edit/11760720 was giving a malformed JSON ISE.
Actually set a `source_type` (and `target_type`, just in case) on `Edit::Historic::Relationship::_display_relationships`.
These being missing was causing a beta ISE when combined with commit 268d6e51db045be90b3b2ec49d28190d2cfb1fe5 - which makes us a lot more demanding wrt what we send to `linkedEntities`. For some reason, despite the fact that `Entity::Relationship` theoretically requires a `source_type`, this wasn't causing any Moose errors (I keep getting the feeling that Moose types are fucking useless).
Basically, the `TO_JSON` method for `Entity::Relationship` adds the rel source to linkedEntities using the source ID, the source itself, but for some reason the `source_type` for the relationship entity rather …
=> MBS-13001: Actually set source_type and target_type for historic rels

lib/MusicBrainz/Server/Edit/Medium/SetTrackLengths.pm, t/lib/t/MusicBrainz/Server/Controller/CDTOC/SetDurations.pm, t/sql/controller_cdtoc.sql
If a medium edit changes the duration of a recording, it is shown on the recording's edit history. If a discID does (with a set track lengths edit), it does not, so it becomes hard to see where the set duration came from.
This will add the set track lenghts edit to the history of all recordings which are linked to a track that is changing duration.
=> MBS-11393: Show SetTrackLengths edit in recording edit history

lib/MusicBrainz/Server/WebService/JSONSerializer.pm, root/collection/types.js, root/static/scripts/collection/components/CollectionEditForm.js, root/static/scripts/common/components/Autocomplete2.js, root/static/styles/forms.less, t/lib/t/MusicBrainz/Server/Data/Collection.pm
The autocomplete input is very short, so it doesn't make sense for `form-row-add` to use a full standard `form-input-width` here. Since we already have `form-input-width-short` which fits better, I'm just adding a `form-row-add.short` combo to match.
=> MBS-12614: Better placement for Add collaborator button

lib/MusicBrainz/Server/Entity/Medium.pm, root/static/scripts/relationship-editor/components/RelationshipEditor.js, root/static/scripts/relationship-editor/utility/comparators.js, root/static/scripts/relationship-editor/utility/updateReleaseRelationships.js, root/static/scripts/relationship-editor/utility/updateWorkStates.js, root/static/scripts/release/components/ReleaseRelationshipEditor.js, root/static/scripts/tests/relationship-editor.js, root/static/scripts/tests/relationship-editor/constants.js, root/types/medium.js
See the steps in MBS-12976, though you may not always be able to reproduce it: it depends on the relative sort orders of the names and IDs of the works you choose.
This was caused by d95b3d3769dc2f494df2751988b8e3bee2c5fcf1. There were other comparators used for updating the `relatedWorks` entries besides that one. I've tried to make them call each other here to avoid other issues in the future.
Added a unit test which reproduced the duplication issue.
=> MBS-12976: Changing a work can cause duplication/key errors

root/static/scripts/relationship-editor/components/RelationshipEditor.js, root/static/styles/relationship-editor.less
The "Relationships" heading when editing an entity is indented further right than all other `fieldset` legends.
These legends are all supposed to be aligned, but the `padding` being applied to the whole `fieldset` was moving this one further right. I was planning to just add `padding` to the `table` inside, but I guess it would also make sense to keep errors padded, so I added an extra `div` for it.
Manually, just making sure the alignment is correct.
=> MBS-12990: Don't pad the legend relationship editor fieldset

lib/MusicBrainz/Server/Data/WikiDoc.pm
When a wiki page contains a WikiLink to a page that doesn’t exist yet, such as `Category:Relationship_Type` in the page `Terminology`, the class `new` is set for this link which contains text only.
I overlooked this case in commit 45288c8b merged with pull request #2894 to address MBS-12984, leading to ISE on `tag` method not found.
This patch fixes that by checking that the content is an element first.
After flushing the cache, tested by opening the reported page `/doc/Terminology` and the 172 currently transcluded pages to check that nothing wrong would show up in browser and in server logs.
<details>
<summary>See the full list of transcluded pages</summary>
* `/doc/About`
* `/doc/About/Data_License`
* `/doc/About/History`
* `/doc/About/Logos`
* `/doc/About/Press`
* …
=> MBS-13007: Fix a regressive ISE on broken WikiLink

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Genie is a Korean music streaming platform that also allows purchasing albums for download. The URL cleanup rules remove unnecessary segments and convert mobile URLs to their desktop counterparts. Album URLs, artist and song pages are supported and validated. Search results will explicitly be prevented from being added.
Since it may happen that albums are only for streaming, we keep the option to set just the streamingpaid relationship to be on the safe side.
Closes MBS-13008.
=> MBS-13008: Add URL cleanup for Genie

root/artist/edit_form.tt
Most entity editors with dates (such as label) mark the ended checkbox when you enter an end date, but the artist editor does not.
Other entity editors use `date_range_fieldset` which already calls `initializeToggleEnded`, but artist has a custom one because of the begin/end areas. As such, we need to actively call `initializeToggleEnded` there too.
We could consider also setting ended when an end *area* is set, but for now this just brings it to parity with other editors.
Manually - it now checks the checkbox as expected.
=> MBS-12963: Also run initializeToggleEnded for artists

lib/MusicBrainz/Server/Report/NonBootlegsOnBootlegLabels.pm, lib/MusicBrainz/Server/ReportFactory.pm, root/report/NonBootlegsOnBootlegLabels.js, root/report/ReportsIndex.js, root/server/components.mjs
Bootleg labels pretty much only put out bootlegs. As such, this report lets editors find non-bootleg releases which have a bootleg label as a release label, which should almost always be wrong in some way.
With sample data, which had a few matches already.
=> MBS-12939: Report for non-bootleg releases with bootleg label

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
`spotify.link` links are just shortened redirects to a specific Spotify page, so we should do the same with them as we do with all other redirect shorteners like Amazon's and Apple's: block, and ask the user to follow the redirect.
As above :) 
Added a test - I also had to fix the error checking code to support React errors.
=> MBS-13011: Block short links: spotify.link

root/components/CritiqueBrainzLinks.js, root/components/EntityHeader.js, root/edit/details/EditUrl.js, root/layout/components/sidebar/ReleaseSidebar.js, root/static/scripts/common/components/EntityLink.js, root/static/styles/layout.less
The release sidebar has two places where an entity name in `EntityLink` can be huge and cause the sidebar to grow to fairly unreasonable sizes: the label name (under **Labels**) and the release group name (for the CritiqueBrainz **Release group reviews**).
Other entity links on the sidebar are controlled by us (language and script names, release countries) so probably do not risk being a problem with this, and tags already wrap.
This makes sure sidebar label and CB release group name can always wrap as needed by setting an appropriate CSS class. Rather than adding a third class name that does the same as `entityheader` and `url-entity-link`, I just changed all of them to a very explicit "`wrap-anywhere`".
The implementation is fairly conservative in the spirit of …
=> MBS-12785: Wrap things sensibly on release sidebar

lib/MusicBrainz/Server/Controller/Edit.pm, root/edit/components/EditList.js, root/edit/components/ListHeader.js, root/edit/search_results.tt
The quick links section has a few issues:
* The refine search link on the subscribed editors page does not set the "I haven't voted" predicate (MBS-12989)
* The edit search pages are not supposed to link to themselves, but they do (no ticket)
* The quick links sometimes (like for Open edits) start with a stray | separator (MBS-12998)
The first commit adds the missing predicate to the `refine_url_args` of `subscribed_editors`.
The second commit sets `isSearch` when calling `EditList` from `search_results.tt`, which I think was always supposed to happen - we literally didn't set `isSearch` anywhere at the moment.
The third commit builds an array of any appropriate quick links, then joins them with the | separator as needed, as we do with `FooterSwitch` in `ArtistIndex`, rather than trying …
=> MBS-12989 / MBS-12998: Edit list quick links improvements

lib/MusicBrainz/Script/RemoveEmpty.pm, lib/MusicBrainz/Script/RemoveUnreferencedRows.pm
Most entities get autoremoved in 24 hours, but merging them keeps them around for a minimum of 48 hours. As such, if you want to get rid of something as an autoeditor, it's very tempting to empty it and let it be autoremoved, while a merge would be preferable.
Additionally, it's not uncommon for people to add artists for their release or whatnot, get sidetracked, and find out they've been autoremoved by the time they try to finish the whole thing the next day. Or a relationship gets removed, and suddenly the entity is empty, and gets autoremoved before the editor can react (even if the editor who removed the relationship is nice and leaves a note!).
Relatedly, but on the other direction, we have had reports that incorrect artists are buggy because they do not get autoremoved. The reason …
=> MBS-10861: Change time before auto-deletion to 48 hours

root/edit/SubscribedEdits.js
This seems to confuse people, who wonder how edits for entities they are not subscribed to (directly) end up in this list.
=> MBS-12309: Clarify /edit/subscribed also includes collection edits

root/static/styles/favicons.less
Utaten favicons are broken.
We had a 32 px link but we had not specified 32 on favicons.less, so we were trying to link to a -16.png file. This just specifies that.
Manually by checking the favicon now appears when adding a random link to https://utaten.com/lyric/mi23041713/ to a work in sample data.
=> MBS-13041: Fix broken Utaten favicon

root/user/UserProfile.js
We blank tags and ratings as part of the user deletion process, so showing stats for their ratings and tags is useless in any case. I'd argue it's also kind of misleading, since it might give the impression they had never tagged/rated before (since their added entity data for example still shows the correct numbers on the adjacent statistics table).
As suggested by @Aerozol, rather than deleting the whole table, we specify that the data is deleted:
Tested manually: both that a deleted editor, `/user/Deleted%20Editor%20%23667117`, shows no stats and says "Deleted", and that a non-deleted editor, `/user/reosarevok`, does still show them.
=> MBS-12851: Hide ratings/tags stats for deleted users

root/static/scripts/edit/externalLinks.js
Since we link to CB automatically from the Reviews tab, there's no point on letting users manually link to the reviews.
I expected that doing the string like that will ensure that the Reviews tab name uses whatever translation we already have, but I tried with Italian and it still showed "Reviews" despite us having a translation - is my understanding of how it should work wrong, or does it only work if the main string is translated? :)
=> MBS-12782: Block adding CritiqueBrainz links

root/release/edit/information.tt, root/release/edit/tracklist.tt, root/static/scripts/release-editor/fields.js, root/static/scripts/release-editor/init.js, root/static/scripts/tests/release-editor/validation.js
Beginners keep getting confused by "artist is missing" errors in the release editor, because they have typed an artist, so clearly it is not missing! They don't really understand the artist needs to be selected from the DB.
This adds errors that specify what exactly means to select an artist.
I couldn't see any reason why we combine missing title and missing artist, which are very different issues with very different solutions. As such, I split the error into two to give a properly useful error message for each.
Tested manually in the release editor by leaving titles empty and artists unselected and making sure I got the correct errors.
=> MBS-12308: Clarify the missing artist errors

admin/InitDb.pl, admin/replication/ImportReplicationChanges, admin/replication/LoadReplicationChanges, admin/replication/ProcessReplicationChanges, lib/DBDefs/Default.pm, t/script/dbmirror2.t
* `REPLICATION_USE_DBMIRROR2` has been flipped to `1` in lib/DBDefs/Default.pm, which (1) enables dumping of v2 packets by default in ExportAllTables, and (2) enables the downloading of v2 packets by default in LoadReplicationChanges.
* Scripts that accept a `--dbmirror2` flag (ImportReplicationChanges, InitDb.pl, ProcessReplicationChanges) now have that flag default to true. `--nodbmirror2` can be specified where it needs to be disabled. (Currently the JSON dumps and sitemaps generation still use the old packets.)
=> MBS-12107: Enable replication with dbmirror2 by default

docker/config/services/dev.musicbrainz-server.json, docker/musicbrainz-test-database/DBDefs.pm, docker/musicbrainz-tests/DBDefs.pm, docs/database_schema_diagrams/write_graphs.pl, lib/DBDefs.pm.sample, lib/DBDefs/Default.pm, t/script/CheckSchemaMigration.sh
`DB_SCHEMA_SEQUENCE` should point to 28 following the schema change today.
`ACTIVE_SCHEMA_SEQUENCE` is currently unused, but should also point to 28.
Bump both of these values to 28.
Last year's commit is at https://github.com/metabrainz/musicbrainz-server/commit/0b7ff5556524e68371a38734eee6d86d18ceffee in case you want to compare.
No testing was done.
=> Bump DB_SCHEMA_SEQUENCE, ACTIVE_SCHEMA_SEQUENCE to 28

root/components/forms.tt
Minor display regression since `v-2023-05-02`: A code comment is wrongly displayed in the form to remove entities.
Fix the comment syntax by moving the template directive end tag marker `-%]` to the next line.
Tested manually by opening the removal form for a recording from the sample database: http://localhost:5000/recording/11e9d7dd-0ca9-42aa-bd2d-7b69ecd12003/delete
=> MBS-13083: Fix code comment

lib/MusicBrainz/Server/Data/WikiDoc.pm
The doc images in https://musicbrainz.org/doc/Release/Packaging are split between Commons-hosted ones and MeB Wiki-hosted ones. The zoomable thing to be able to see the images properly (added with https://github.com/metabrainz/musicbrainz-server/pull/2894) is working great with Commons images, but the MeB ones are being sent to links like `https://musicbrainz.org/-/images/a/a5/Packaging-Book2CD.jpg` rather than the wiki.
We fix up the image links to point to the wiki as part of the wikidoc process (`sub _fix_html_links`). A regex there was assuming `/thumb` would be in all wiki image URLs, but at least the ones in `/doc/Release/Packaging` did not have it. It might be an SVG only thing? In any case, given we want to link to the full image, we can just keep removing it if there and ignore …
=> MBS-13047: Do not assume every wiki image has /thumb

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Apparently some languages are now adding a segment like intl-de or intl-it to the Spotify URLs. These redirect to the basic URL if the site is set to English, and the basic URL to them if not. As such, the easiest way to deal with them seems to be to just drop them in cleanup.
This just drops the new path segments in cleanup, We need to also support them when checking whether a URL is `spotify` or `spotifyuseraccount`, of course.
Added / modified a test for `spotify` and one for `spotifyuseraccount`.
=> MBS-13052: Support intl-XX/ path segment in Spotify URLs

root/static/scripts/edit/components/ReleaseMergeStrategy.js
We were just printing "`was medium 1 on release Whatever`" on the UI for picking medium positions and titles when merging releases and appending mediums. This means release disambiguations were not shown here, even though they can be useful when merging different releases of the same or a similar title.
This patch changes the text name to an `EntityLink` for the release, which both shows disambiguations and provides
an actual link to the release itself in case the user wants to reopen it to check something.
Manually, to make sure the disambiguation now appears (compare below).
Old:
New:
=> MBS-7385: Use EntityLink over release name in medium append UI

root/user/ReportUser.js
We have a "Reveal your email" checkbox when reporting users, but the people who get this report have access to your email anyway, so this is misleading.
Improved the wording as suggested by @Aerozol.
Manually (trivial change).
=> MBS-13085: Clarify "share email" report checkbox 

root/static/scripts/common/entity.js
To make sure you didn't pick the wrong area of the same name, it'd be very helpful to actually have the containment shown in the "You selected AreaName" bubble. Right now, it only shows the name as a link, so you still need to open the link to actually check whether it's the area you wanted.
I just used `DescriptiveLink` here, which we already do for release group bubbles and seems by far like the simplest option. I made sure to keep the `target="_blank"` we already had.
Manually, by just selecting an area with containment:
=> MBS-8774: Show containment for selected area in area bubble

lib/MusicBrainz/Server/Controller/Edit.pm, lib/MusicBrainz/Server/Controller/EditNote.pm, lib/MusicBrainz/Server/Data/EditNote.pm, lib/MusicBrainz/Server/Data/EditNoteChange.pm, lib/MusicBrainz/Server/Data/Utils.pm, lib/MusicBrainz/Server/Entity/EditNote.pm, lib/MusicBrainz/Server/Entity/EditNoteChange.pm, lib/MusicBrainz/Server/Entity/Types.pm, lib/MusicBrainz/Server/Form/EditNoteDelete.pm, lib/MusicBrainz/Server/Form/EditNoteModify.pm, root/constants.js, root/edit/DeleteNote.js, root/edit/ModifyNote.js, root/edit/NotesReceived.js, root/edit/components/EditNote.js, root/edit/components/EditNoteHelp.js, root/edit/components/EditNoteListEntry.js, root/edit/components/EditNotes.js, root/layout.tt, root/layout/index.js, root/server/components.mjs, root/static/styles/edit.less, root/static/styles/forms.less, root/types/edit.js, t/lib/t/MusicBrainz/Server/Controller/Edit/ChangeNote.pm, t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm, t/lib/t/MusicBrainz/Server/Data/EditNote.pm, t/sql/change_edit_note.sql, t/sql/edit_note.sql
There is no way for users to delete or fix their edit notes. While obviously this is not desirable all the time, it would be great to have a way for editors to delete or change an edit note if they, say, immediately notice they pasted the wrong thing (even more so if it's for example private data).
There's also no way for *admins* to delete or amend edit notes, which means notes with spam such as [this one](https://musicbrainz.org/edit/96631022#note-96631022-1) cannot be acted on.
This adds a new table `edit_note_change` to track changes to edit notes.
Admins can edit or delete an edit note at any time of their choosing. For anyone else, the following conditions must apply:
1) the edit note is by the user (obviously)
2) the edit note hasn't already been deleted
3) the edit note isn't …
=> MBS-4685 / MBS-13084: Allow modifying and removing edit notes

lib/MusicBrainz/Server/Data/Artist.pm, t/lib/t/MusicBrainz/Server/Controller/Artist/EligibleForCleanup.pm, t/sql/artist_cleanup.sql
Unused artist credits are no longer automatically removed, so an artist can be "in use" in an AC which is itself scheduled for autoremoval. In this case, we should consider the artist empty and in risk of cleanup.
On top of https://github.com/metabrainz/musicbrainz-server/pull/1538
=> MBS-12692: Also consider artist empty if used in unused AC

root/admin/attributes/Attribute.js
We have MBIDs in the DB for all attributes under `/admin/attributes` except for language and script, but we do not  currently display them anywhere on the website (we do use them in the API). It is weird to hide these, and it recently made me have to query for the MBIDs from the DB when I wanted to update some tests with real data.
Added an MBID column to the attribute tables.
These Attribute pages are also going to be made public (without the admin bits) at some point with MBS-11178 (https://github.com/metabrainz/musicbrainz-server/pull/2480), and then it would make sense to make it so that `mbid/$attribute_mbid` would redirect to the appropriate attributes page (MBS-13067).
Manually, checking that all attribute types in the list now show MBIDs except for language and script (which as …
=> MBS-13060: Display attribute MBIDs on attribute tables

root/release/ChangeQuality.js
Right now there's no explanation when editing of what data quality means. This contributes to users relatively often still confusing this with the quality of the music itself (especially artists who often like to set this to High for their music). Changing the name from "quality" to "data quality" helped, but hopefully adding an actual explanation would help more.
This takes the first line from [Release#Data quality](https://musicbrainz.org/doc/Release#Data_quality) and adds it to the change date quality edit page. Rather than hardcoding the definition of each quality level here, those are kept on the doc page where they can easily be improved later.
Manually (links work).
=> MBS-10759: Explain release data quality in editor

lib/MusicBrainz/Server/Data/Event.pm, lib/MusicBrainz/Server/Data/Place.pm, lib/MusicBrainz/Server/Data/Work.pm
A place with a URL relationship gets detected as empty.
I enclosed `$used_in_relationship` in parens when used alone. `$used_in_relationship` is actually a bunch of clauses like: `EXISTS (...) OR EXISTS (...)` - without this being enclosed in parens, it's actually doing `AND NOT EXISTS (first set) OR EXISTS (second set)` and returning `is_empty` as `true` if any relationships exists for all but the first clause.
Manually, checking the place for which the bug was reported now shows properly.
=> MBS-13089: Properly enclose $used_in_relationship in parens

root/static/scripts/common/entity.js
Area bubbles for artists (and I assume label too) are crashing when trying to fill them using the area data stored in the form since that is missing `iso_3166_1_codes`.
Using `{this}` rather than `{this.toJSON()}` meant we were hitting the issue why we originally added the `iso_3166_1_codes` assignment to `toJSON`, so use `this.toJSON()` instead. In order to be able to display containment with `toJSON` we need to actively set it in `toJSON` as well.
Manually with [the case reported by CatQuest](https://tickets.metabrainz.org/browse/MBS-8774?focusedCommentId=68134&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-68134) plus making sure the rest of areas (e.g. when searching) still worked fine.
=> Avoid area bubble crashing on missing iso_3166_1_codes

lib/MusicBrainz/Server/Controller/Series.pm, root/series/edit_form.tt, root/static/scripts/series/edit.js
The bubble for series types doesn't even appear at first as it should, and eventually appears empty.
Rather than fidgeting with the non-standard implementation we had for series, I just changed it to match the other type bubbles (based it on `place`).
Manually, by going to `/series/create` and checking the type docs appear.
=> MBS-13088: Standardize series type bubble

root/report/components/ArtistUrlList.js, root/report/components/LabelUrlList.js, root/report/components/ReleaseGroupUrlList.js, root/report/components/ReleaseUrlList.js, root/report/components/RemovedUrlRow.js
`UrlList` reports were working as expected when the non-URL entity was gone, but were crashing when the URL itself was gone. 
For a case where there's no URL, there's no point on showing the entity grouping at all, so this just returns the new `RemovedUrlRow` component in those cases.
Manually, ensuring the reported `/report/DiscogsLinksWithMultipleArtists?filter=0&page=2` page now loads:
=> MBS-12211: Avoid crash when URL has been removed

entities.json, entities.mjs, root/components/EntityDeletionHelp.js, root/static/scripts/common/entity.js, root/types/area.js, root/types/artist.js, root/types/entity.js, root/types/event.js, root/types/genre.js, root/types/instrument.js, root/types/label.js, root/types/place.js, root/types/recording.js, root/types/release.js, root/types/releasegroup.js, root/types/series.js, root/types/url.js, root/types/work.js
In preparation for MBS-12552, a few occurrences of the generic types `Core*T` still remain.
Finally drop these after being discussed at yesterday’s team meeting.
Also add a note to the JS class `CoreEntity` which will disappear along with knockout.js.
Rely on CI Flow tests only.
=> MBS-12552 (pre): Nail last "core" Flow.js types

lib/MusicBrainz/Server.pm, t/lib/t/MusicBrainz/Server/Controller/OAuth2.pm
staticbrainz.org now redirects to static.metabrainz.org, which breaks CSP on "secure" forms (e.g. the login page). A side effect of that is that CSS, JS, and images can't load on these pages without fixing the header.
This doesn't adjust any irombook code for now.  As part of merging this, we should also update docker-server-configs to use `static.metabrainz.org` for `STATIC_RESOURCES_LOCATION`; but for now both domains are whitelisted in the header so that either case works while the configuration is being updated.
=> Add static.metabrainz.org to CSP header

root/report/components/CDTocReleaseList.js, root/utility/tableColumns.js
When [converting the `CDTocReleaseList` file to react-table](https://github.com/metabrainz/musicbrainz-server/commit/3b774087d2fd041c8b2ff0bb72f38a1aa4ff632b#diff-f01992fd268330fa3a22c46f93677e325f1f1e98a5a7a53742f3c41fc8966530), it seems I accidentally missed the part where it sent the `anchorPath` parameter to indicate the exact release in the disc ID page, so it currently just links to the disc ID page without any specific anchors. The anchor link was meant to help users figure out which release is the unapplied one in `/report/CDTOCNotApplied` when there's more than one.
This re-adds the anchor link, by adding an optional `getAnchor` function that can be passed to `defineCDTocColumn`.
Tested the anchor is now shown in the `/report/CDTOCNotApplied` page, and that the cdtoc links still …
=> MBS-13119: Readd anchor link to CDTocReleaseList

lib/MusicBrainz/Server/Report/InstrumentsWithoutAnImage.pm, root/static/scripts/common/components/IrombookImage.js, root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
We've changed the way the static resources work, so we need to update the expected URLs. The already existing URLs will be updated separately with a one-off bot run (MBBE-80).
Just the basic (updated) URL test.
=> MBS-13131: Move staticbrainz to static.metabrainz for instruments

lib/MusicBrainz/Server/Data/Vote.pm, lib/MusicBrainz/Server/Entity/Editor.pm, root/utility/edit.js, t/lib/t/MusicBrainz/Server/Controller/Edit/Show.pm, t/lib/t/MusicBrainz/Server/Data/EditNote.pm, t/lib/t/MusicBrainz/Server/Data/Vote.pm, t/sql/edit_note.sql, t/sql/vote.sql, t/sql/vote_stats.sql
There's been too many sockpuppets created just for voting since we removed the requirement. We need to have some way to discourage this.
We might want to adapt how beginner editorship works later on (one idea I have is MBS-13132), but for now this just blocks voting again for beginner editors, since that's the easiest fix.
Added back a test testing beginner editors cannot vote, but the test now checks they can indeed post a note since we haven't removed that permission.
=> MBS-13100: Readd beginner voting restrictions

t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm, t/sql/initial.sql
- Like `[Artificial (Other)]` (`qaa`)
- Like `[Multiple languages]` (`mul`)
- Like `[No lyrics]` (same `zxx`)
`No linguistic language` (`zxx`) should be renamed to `[No linguistic language]` (`zxx`) and should thus appear in release language list (select combo) after ~~`[Multiple languages]` (Frequently used)~~ `[Artificial (Other)]`, instead of between `Niuean` and `Nogai`.
I guess it also requires a Database edit of the stored label in languages table.
Maybe I am missing some files.
=> Special purpose language: No linguistic content (zxx)

lib/MusicBrainz/Server/Entity/Medium.pm
Since the commit e38d8e95e6ab06888c956df668a4cb5617a3b4ea (pull request #2902) is in prod (`v-2023-06-07`), search queries are triggering two warnings for each result in logs, that is up to 200 log lines for each query, resulting in needless GBs of logs.
This patch simply checks if defined before enforcing integer conversion, that is the same approach for `position` and `release_id` as for `format_id` and `track_count`, thus stopping the log flood.
However by doing so, it partly reverts the commit e38d8e95e6ab06888c956df668a4cb5617a3b4ea as it unsyncs the Flow type `MediumT` for its `position` and `release_id` properties. It is unclear whether these should be nullable or if a new type should be used instead since these are null only for search results. Beyond Flow types, the property …
=> Beta: Fix log flood regression since #2902

root/static/scripts/guess-case/modes.js, root/static/scripts/guess-case/utils.js, root/static/scripts/tests/GuessCase.js
The words "remaster" ("remastered") and "refix" are pretty much always ETI and should be treated as such by guess case. Same for "re-edit", which we already try to cover, but buggily.
While looking into these I also noticed we don't use global regexes enough, causing issues if the same word appears twice (uncommon, but not impossible).
I added all of the new words to the list of words which are put into parens if seen at the end of the title, and lowercased if in parens.
I fixed the re-edit check and made it behave differently inside and outside parens.
I made the a cappella and OC ReMix checks global so that it checks more than once per title.
Added a basic test for each case.
=> MBS-13149 / MBS-13153 / MBS-13156 / MBS-13157: More guess case changes

root/annotation/EditAnnotation.js, root/static/scripts/edit/components/EnterEdit.js
Having the preview button go first is more likely to encourage people to use it (and make sure the annotation looks right) before submitting. Ran this through @Aerozol to confirm it seemed good.
Implemented by just having a boolean to say whether children buttons for `EnterEdit` should be before or after the submit button (we have Cancel buttons to the right when present, and we haven't had any talk of moving those).
Manually
=> MBS-13115: Move annotation preview button to the left of Enter

lib/MusicBrainz/Server/Controller/Artist.pm, root/artist/ArtistIndex.js
We renamed the relationship text for "performs as" with STYLE-2328 but the display on the artist overview page was still hardcoded to "Legal name".
This renames the hardcoded text to "Performance name of" (as in the relationship) in the case where we follow this relationship (which no longer mandates it must be a legal name). "Legal name" is kept for actual legal name alias display.
I wasn't sure what'd be a good name for the no-longer-`legalName`, ended up going with `baseName` since it's the base of the grouping of names for the artist.
Manually, on the artist from the ticket.
=> MBS-13160: Rename "legal name" on artist page to "performance name of"

root/elections/ElectionDetails.js, root/elections/ElectionVoting.js, root/elections/Show.js
The list of who has voted and when (even if with votes marked as "Private") being shown during the voting period has no actual benefit, and the drawback of allowing people who can see the vote tally (proposer, seconders and candidate) to figure out who voted what by comparing the vote tally with the vote list repeatedly upon changes (there's 4 Yes votes, then on refresh there's 4 Yes and 1 No, clearly the latest voter voted No).
The only real usefulness I can see in showing the voter list during the election period is that it allows voters to see what they have voted in case they want to change it, so that needs to be kept somehow.
Edit: another useful point was brought up in a ticket comment: since we don't show the total number of voters nor the number of abstentions in the tally, the …
=> MBS-13111 / MBS-13116: Hide list of autoeditor election voters during vote

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Bandcamp publishes interviews with artists seemingly quite often, but we were automatically selecting "bandcamp" for those.
This moves `daily.bandcamp` URLs to a separate handling section, so we can deal with them more properly and select interview when appropriate.
While doing this I noticed that newer album reviews are no longer listed under the date as we expected, but under an `album-of-the-day` path. As such, I made both interview and review support these sorts of paths.
Finally, since we are no longer doing any RG-level selecting on the standard bandcamp handling, non-daily bandcamp URLs need to be blocked separately on RGs. AFAICT no non-daily bandcamp URL would be acceptable for RG (and the previous setup blocked them all) so this is a blanket ban.
Added a test for the interviews, …
=> MBS-13173: Also allow daily.bandcamp.com interviews

lib/MusicBrainz/Server/Data/EditorOAuthToken.pm, root/account/applications/Index.js
It seems useful to know when was the last time a specific application / scope had a token granted; that is likely to help users revoke unneeded ones (I for example currently seem to have 7 ListenBrainz tokens, some of which were granted in 2015).
This adds a column in the authorized applications table for the `granted` token column, which displays the last time a token was granted for this specific application + scope combo. I stopped returning the `refresh_token` here since it seems we do not use it at all.
Manually.
=> MBS-13167: Show last granted token date for auth applications

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
We were blocking song links for Apple Music, but I can't see any real reasons to. There's two kinds of song links - one that selects the track on an album (kind of like our track links in MB) and one that goes to a /song page for the track itself.
This allows entering `/song` links on recordings, and converts `/album/albumid?i=trackid` links to /song ones, since there's no reason not to convert them and allow them, as far as I can tell.
I split the regexes a bit more for clarity.
URL tests added.
=> MBS-13092: Support Apple Music song links

lib/MusicBrainz/Server/Controller/Admin/Attributes.pm, lib/MusicBrainz/Server/Data/Language.pm, lib/MusicBrainz/Server/Data/Script.pm, t/lib/t/MusicBrainz/Server/Controller/Admin/Attributes/Delete.pm, t/sql/attributes.sql
Trying to delete any language caused an ISE, because it was trying to check the no longer existing `language` column of the `work` table. Trying to delete any script not in use caused a different ISE (this ISE also applied to languages but was hidden there by the first one) since the code expected a non-existing `has_children` method.
Fix the language `in_use` query to actually look at the `work_language` table. Add dummy `has_children` methods for language and script (which always return false).
Manually, plus I added reasonably exhaustive tests for all three cases of language, script and standard attribute (the latter had no ISEs right now, but we might as well).
=> MBS-13105 / MBS-13106: Fix ISEs on attribute deletion pages

root/relationship/linkattributetype/RelationshipAttributeTypeIndex.js
When editing a relationship attribute such as https://musicbrainz.org/relationship-attribute/a40b43ed-2722-4b4a-98a5-478283cdf8df a relationship editor can modify two checkboxes: "This attribute supports free text credits" and "This attribute uses free text values". The value of these is not actually shown in any way in the main attribute page though AFAICT, meaning non-admins have no way of telling from the docs whether a specific attribute supports free text in any way.
This adds lines at the bottom of the attribute description section if the attribute supports free text, with the same strings as the checkboxes themselves.
Manually, by visiting pages for attributes with different settings: neither (`/relationship-attribute/4485dfdb-6000-4602-8b18-5f84e34d8aed`), text values …
=> MBS-13113: Show in attribute page if it supports free text

lib/MusicBrainz/Server/Controller/Label.pm, root/components/RelationshipsTable.js
Label-Event relationships are not shown anywhere on the label page. 
Label-Event rels were already being loaded (unpaged), but not being shown since `Relationships.js` did not use them. This was not a problem until recently because we didn't have any. Since the only one we now have is `label presents event`, which seems more akin to recording/release rels with cardinality 1:0 than the other rels we show outside the rels table, I'm moving this to load them as a paged subset and showing them in `RelationshipsTable.js` instead. 
I considered a separate events page but events are nowhere near as relevant to most labels as to artists, so I think the generic rels table is more than good enough. 
Manually, with the label provided in the ticket …
=> MBS-13177: Show label events on label rels page

lib/MusicBrainz/Server/Controller/EditNote.pm, lib/MusicBrainz/Server/Data/EditNoteChange.pm, lib/MusicBrainz/Server/Entity/EditNoteChange.pm, root/edit/components/EditNote.js, root/edit_note/EditNoteChange.js, root/edit_note/EditNoteHistory.js, root/server/components.mjs, root/static/styles/entity.less, root/types/edit.js, t/lib/t/MusicBrainz/Server/Controller/EditNote/ChangeNote.pm, t/lib/t/MusicBrainz/Server/Controller/EditNote/NoteHistory.pm, t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm, t/sql/edit_note_history.sql
Admins should be able to see the edit history for any edit, since otherwise a user could, for example, insult another and then edit the note so that the email is sent but others don't see.
This mostly follows what we do for annotations, but most of it does not support translated strings since it's admin-only. Translations are added for stuff that will show in otherwise translated pages.
Manually navigating around after changes, plus added a test file checking that the pages are blocked for non-admins and show the expected data for admins.
=> MBS-13094: Allow admins to browse edit note changes

lib/MusicBrainz/Server/Controller/Role/WikipediaExtract.pm, t/lib/t/MusicBrainz/Server/Controller/Role/WikipediaExtract.pm
Allow ListenBrainz to easily use Wikipedia extracts retrieved by MusicBrainz server.
Supporting CORS is one way out, it doesn’t require tinkering with Redis cache.
1. Ping LB team when available
=> MBS-13183: Add CORS support to Wikipedia extracts

lib/MusicBrainz/Server/Data/Statistics.pm, root/statistics/Index.js, root/statistics/stats.js
For some reason, while we were calculating no-type stats for other types we were not doing it for RG primary nor secondary types.
This just follows the general style we use for other entity types (more specifically, I based it on area_type).
Generated stats locally. For secondary types, where the query is less obvious, I made sure the "None" result in a sample db matched the result of:
```
SELECT count(*) FROM release_group rg WHERE NOT EXISTS (
SELECT 1 FROM release_group_secondary_type_join rgj WHERE rgj.release_group = rg.id
)
```
=> MBS-13079: Add statistics for release groups with no type set

admin/replication/ProcessReplicationChanges
Some variable names are not really telling much about this piece of code, leading sometimes to confusion. For example, see https://github.com/metabrainz/musicbrainz-server/pull/2919#discussion_r1183566776.
In [`ProcessReplicationChanges`](https://github.com/metabrainz/musicbrainz-server/blob/v-2023-05-15-schema-change/admin/replication/ProcessReplicationChanges), rename the variables:
=> Refactor ProcessReplicationChanges

lib/MusicBrainz/Server/Controller/Release.pm, root/release/add_cover_art.tt, t/selenium/CAA.json5
Update MusicBrainz::Server::Controller::Release's add_cover_art() method to pass query parameters to the form's process() method when handling GET requests so that the edit note textarea and make-votable checkbox can be seeded via add-cover-art.edit_note and add-cover-art.make_votable, respectively.
This matches what MusicBrainz::Server::Controller's edit_action() method does for other forms that are seedable via query params.
Also update add_cover_art.tt to remove query parameters from the form's "action" URL so that they won't be double submitted in the query string and the request body.
---
This was definitely at the upper end of the time-spent-to-lines-of-code ratio. 😬 I haven't written any Perl in a long time and haven't used Catalyst/HTML::FormHandler/etc. before, so it took me a …
=> MBS-13098: Process cover art params for seeding

lib/MusicBrainz/Server/Data/Role/Area.pm
In commit 42cd50fc0f7c17b3940fa4911ec0eb17acaf7480 (pull request #2554) the variable `extra_conditons` wasn’t initialized when used most of the time, triggering the following warning very frequently (currently ~4K times per week):
Use of uninitialized value $extra_conditions in concatenation (.) or
string at lib/MusicBrainz/Server/Data/Role/Area.pm line 25.
This patch just initializes this variable to the empty string.
=> Fix warning after pull request #2554

root/static/styles/layout.less
Remove the 'outline-style: none' CSS rule on a:hover to allow the UA to draw focus indicators on links. This was added by 2f155ec2 in 2010, but it impairs keyboard accessibility for the site and it's unclear why it was needed.
=> MBS-11947: Stop hiding focus indicators on links

admin/functions.sh, lib/MusicBrainz/Script/JSONDump.pm
In Perl `$!` is a short name for `$OS_ERROR` and the linter doesn’t allow short names, breaking CI tests.
It happened because I did not rebase the pull request #2350 on `master` before merging, and the Perl linter setup changed in the meantime in `master` branch, thus the CI tests did pass for this pull request even though they would not have if rebased.
Replace all instances of Perl `$!` with its long name `$OS_ERROR`; See https://perldoc.perl.org/perlvar#$OS_ERROR
- `admin/functions.sh` is not tested as it is a Bash file embedding a Perl snippet; Seems worth replacing too.
- `script/reset_selenium_env.sh` uses `$!` but it is a Bash variable for the PID of last executed background task.
=> Fix CI tests: Replace Perl short `$!` with long `$OS_ERROR`

root/components/GroupedTrackRelationships.js
Avoid displaying "music quoted in" work-work relationships in tracklists. Works linked by these relationships are typically unrelated to the track in question, and other similar relationships (based on, arrangements, medleys, etc.) are already omitted.
=> MBS-13227: Omit "music quoted in" rels in tracklists

lib/MusicBrainz/Server/Controller/User.pm, t/lib/t/MusicBrainz/Server/Controller/User/Login.pm
This should not be accessible to JavaScript and is prone to XSS attacks otherwise.
Note: Once this is deployed, existing `remember_login` cookies will be overridden once the current session expires (which I believe only lasts 3 hours), so no other action needs to be taken on those.
=> MBS-12720: Set the remember_login cookie to HttpOnly

root/static/scripts/edit/MB/Control/Bubble.js, root/static/scripts/release-editor/bubbles.js
Prevent the focus from getting incorrectly reassigned to the recording name text field whenever a radio button is selected at /release/add#recordings.
The RecordingBubble was passing a stealFocus argument around internally but then ignoring it in its show() method and not passing it to its parent class BubbleDoc (which also ignored it). Make sure that the argument makes it all the way up to the BubbleBase class.
=> MBS-13207 (I): Make release recording input not steal focus

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Twitch mobile links (such as https://m.twitch.tv/marimbamatt913) are rejected.
These mobile links equivalent to the usual www. links (such as https://www.twitch.tv/marimbamatt913) and should just be converted into them, so this just does that.
Added a test.
=> MBS-13237: Clean up Twitch mobile links

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
IdRef URLs can actually end on X, but we're expecting only digits.
Wikidata suggests it's always 8 digits, then a digit or X: https://www.wikidata.org/wiki/Property:P269
That said, because we've been burned before when trusting WD too much, I'm just allowing any number of digits and Xs - I don't expect this has much of a chance to lead to false positives unless someone starts making up IdRef IDs for some reason.
Added a small test with an url with X ending.
=> MBS-13165: Allow X ending for IdRef IDs

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
A link without an ending slug, such as `https://openlibrary.org/works/OL20723256W?edition=`, does not get cleaned up. Same for any `/publishers` link (valid for labels, for example publishing audiobooks).
No validation happens at all for any of these links either.
The first ticket here makes it so that cleanup does not depend on whether a slash appears after the OL ID, since that does not seem relevant to anything really (in fact, it seems some places, like the IA site, specifically link to pages without an ending slash and that might be a slightly preferable permalink).
The second ticket also allows cleaning up publisher links. Those don't use OL IDs for some reason, just plain text slugs, but they can certainly still be useful (some audiobook publishers have hundreds of entries).
The …
=> MBS-13214 / MBS-13238: Improve Open Library handling

root/components/GroupedTrackRelationships.js, root/components/RelationshipTargetLinks.js, root/medium/MediumTracklist.js, root/static/scripts/common/components/AreaWithContainmentLink.js, root/static/scripts/common/components/DescriptiveLink.js, root/static/scripts/relationship-editor/components/DialogPreview.js, root/static/scripts/relationship-editor/components/DialogSourceEntity.js, root/static/scripts/relationship-editor/components/NewWorkLink.js, root/static/scripts/relationship-editor/components/RelationshipItem.js, root/static/scripts/release/components/MediumTrackRow.js, root/static/scripts/release/components/TrackRelationshipEditor.js
There's a ton of places in the release display page and release relationship editor where long names fail to wrap and cause scroll / escape their dialog (see commits for details on each).
Use class `wrap-anywhere` (as introduced by https://github.com/metabrainz/musicbrainz-server/pull/2782) in these places.
Added a release, track/recording and work all called "fdjfdjjgjkfdgjdfjkghfjkgfhgjkfhgkfjghdkfldkflskfjsfkdjflfĺksaĺkslkdlaskdĺsadlskaldksḱdĺaskdlksaldksaldkskdlśakdñḱasĺdkaskdaskdĺkksaḱśkldksldklskdksdksaḱdśkdsldksld" and saw what happened before/after. That includes using the batch-add works option to test `NewWorkLink`, adding and displaying relationships (including recording-work). Also tested adding a recording relationship to an artist and using the same string as the artist …
=> MBS-12948 / MBS-13051: Wrap more long stuff in release pages

root/main/ConfirmSeed.js, root/static/scripts/main/components/ConfirmSeedButtons.js
When /release/add is being seeded via a cross-site POST request, automatically submit the "Confirm Form Submission" form if the request included a "skip_confirmation" query parameter set to "1". This allows editors to go straight to the seeded "Add Release" page without needing an extra click.
Users need to click through an extra "Confirm Form Submission" interstitial whenever they seed a release via a POST request to `/release/add`. This page still needs to be loaded to ensure that the `session` and `remember_login` cookies are passed (due to `SameSite=strict` being used), but making the user interact with it seems unnecessary for preventing CSRF attacks since the actual edit submission happens via a different `/ws/js/edit/create` path.
The form can automatically submit itself when it's …
=> MBS-13225: Allow skipping Confirm Form Submission page

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
The Internet Archive and OL itself seem to prefer the no trailing slash format, so it probably makes sense for us to do the same.
Modified the tests as needed.
=> MBS-13214 (II): Clean Open Library URLs with no trailing slash

root/static/scripts/common/constants.js, root/static/scripts/relationship-editor/components/RelationshipDialogContent.js, t/selenium.mjs, t/selenium/MBS-2604.json5
Make the relationship editor automatically infer the link direction for certain artist-artist relationships between individuals and groups (including orchestras and choirs).
For example, when a "member of" relationship with a person target is added to a group artist, it is automatically reversed.
This is intended to reduce the need to click the "Change direction" button and to make errors less common. Editors are still free to manually change the link direction before saving the relationship.
Artist-artist relationships often default to being in the wrong direction. For example, when editing a group to add a "member of" relationship with a person as the target, the link direction needs to be manually reversed. Editors frequently forget to do this, resulting in incorrect data being …
=> MBS-2604: Infer link direction between people and groups

root/static/scripts/main/components/ConfirmSeedButtons.js
I'm not sure if it has any effect in practice, but fix an oversight from 6f0b967e3d2f.
---
It looks like I forgot to amend my commit to include a change suggested by @mwiencek, namely passing a dependency list to the `React.useEffect()` call that clicks the submit button. I'm including the original ticket in the commit title, although I'm not sure if it's necessary (or desirable). I had already manually tested this locally.
=> MBS-13225: Add deps to useEffect call in ConfirmSeedButtons.

root/static/styles/release-editor.less
Set "vertical-align: top" on the tracklist table rows at /release/add#recordings to prevent the "Edit" button from shifting vertically depending on the height of the track and recording titles, which was causing the bubble that contains the recordings list also shift vertically.
Also set "vertical-align: top" on the recording rows since it looks odd when the artist name and duration aren't aligned with the top of a multiline recording title and disambiguation.
The bubble that lists recordings often moves vertically when a recording is clicked, which can be disorienting. This happens because the bubble is aligned with the "Edit" button, which is vertically centered within its row, and the row's height can increase when the selected recording has a long title or disambiguation.
The vertical …
=> MBS-13241: Prevent recording bubble from shifting.

.circleci/config.yml, INSTALL.md, docker/Dockerfile.tests, docker/musicbrainz-tests/chrome.service, docker/templates/macros.m4, lib/MusicBrainz/Server/Data/Collection.pm, lib/MusicBrainz/Server/Edit/Release/ReorderMediums.pm, package.json, yarn.lock
From the ticket: "MusicBrainz Server depends on Node.js 16 which is currently still an LTS in maintenance phase. Its EOL is the 11th September 2023. So it should be replaced with the next active LTS which is Node.js 18."
Since we plan to require v20 when that reaches LTS, and given the short notice, I haven't updated the requirements in INSTALL.md yet (though I've noted that we run v18 in production); I've also modified the CircleCI config to run tests against the previous musicbrainz-tests image which contains Node.js v16 in order to avoid any breakage in the meantime.
=> MBS-13260: Upgrade Node.js to v18

root/static/scripts/common/utility/formatSetlist.js, root/static/scripts/tests/utility/formatSetlist.js
After a setlist was added to an event, it started crashing with an error about trying to run `replace` on `undefined`.
I found that this was caused by the setlist linking to works without work titles like this:
` * [58b51a5a-279b-476d-b27e-f44402faa675]`
We do explicitly support empty content, so this was just a bug - this just makes it so we don't try to run `replace` on `undefined` content.
Added one row like this to the test setlist in our `formatSetlist` test.
=> MBS-13250: Don't crash on missing text content on setlist

root/user/UserSubscriptions.js
Unlike most other tables with selectable checkboxes on the site, the ones to select and unsubscribe from subscriptions do not currently have a "select all" checkbox on the table header.
There seems to be no good reason why we do not have this (shift-clicking works, but we offer both options in other places). Just following the same pattern as elsewhere including `className` over the previous `style` object.
Manually with my test data, including that selecting all and then clicking unsubscribe works, and that selecting all, then unselecting all, then clicking unsubscribe does nothing as expected.
=> MBS-3629: Add check/uncheck all option to subscription pages

root/user/UserProfile.js, t/lib/t/MusicBrainz/Server/Controller/User/Show.pm
We have for a long time chosen not to show whether a user was blocked from editing or leaving edit notes publicly in order to avoid publicly shaming editors.
Sadly, this means already banned editors get reported again, kind of wasting the time of both re-reporters and admins.
Additionally, it's unfair to the user *not* to display this info, since other editors can demand the user react to their edit notes without knowing they cannot.
This shows active editing/voting an edit note restrictions for the user to other logged in users only and only when they visit their profile, which is the least shaming way of doing it but still visible if someone is thinking of re-reporting.
The "Untrusted" restriction is explicitly not shown to other users. "Untrusted" is usually set as a "hidden" "minor" …
=> MBS-13224: Show edit/note restrictions from user profile

admin/run, docker/scripts/create_log_directories.sh, docker/templates/Dockerfile.json-dump.m4, docker/templates/Dockerfile.production-cron.m4, docker/templates/Dockerfile.search-indexes-dump.m4, docker/templates/Dockerfile.sitemaps.m4
sitemaps cron has not been running for quite some time.  I'm not sure for how long, but at some point the logs volume was cleared, which breaks admin/run.
To check what was failing, I ran this inside the container:
```sh
root@0ca0886613a0:/home/musicbrainz/musicbrainz-server# ./admin/run admin/cron/daily-sitemaps.sh
run: '/root/log/daily-sitemaps' doesn't exist
Make sure to run in the appropriate container.
```
This is odd to me because the script is supposed to `sudo` as the musicbrainz user if it exists.  In that case it should also use /home/musicbrainz as the log path, since that's the user it's invoking the passed-in script as.
Next, I tried the same command as the musicbrainz user:
```sh
root@0ca0886613a0:/home/musicbrainz/musicbrainz-server# su musicbrainz …
```
=> admin/run: fix log path and automatically create it

lib/MusicBrainz/Server/Data/EditorOAuthToken.pm
The current sort of the authorized applications list (by application ID) means nothing to users, so it feels effectively random. 
The two best options seemed to be granted token time (does not require extra joins, but keeps similar applications separate) or application name (groups similar applications; needs one extra join).
It feels to me that the benefit of name is worth the join on this table since it shouldn't add a significant delay (application is relatively small). I'm doing a second level of sorting on token date (newest first) since it seems to also make the table nicer when there's several entries for a name.
Manually with my own authorized apps (which include duplicate app names)
=> MBS-13195: More useful sort for applications list

lib/MusicBrainz/Server/Controller/Artist.pm, lib/MusicBrainz/Server/Data/Recording.pm, root/artist/ArtistIndex.js, t/lib/t/MusicBrainz/Server/Controller/Artist/Filtering.pm
When we fall back to showing recordings for an artist overview, we still use the release group filter, which unsurprisingly is useless.
This makes it so that if the artist has no RGs, the filter loaded becomes the recording one, which actually filters the returned list of standalone recordings as well.
Manually, with the artist mentioned in the ticket (`/artist/c48c24dd-d3d5-4021-9098-6ef2190d8351`) for recordings and Nine Inch Nails to make sure it still works for RGs.
=> MBS-13244: Add standalone recording filter to artist index 

lib/MusicBrainz/Server/Controller/Label.pm, lib/MusicBrainz/Server/Entity/LabelType.pm, root/label/edit_form.tt, root/static/scripts/label/edit.js, webpack/client.config.mjs
People are using the wrong label types relatively often (see MBS-13277 for an example); while it's probably not only because descriptions are missing, it certainly wouldn't hurt to have them and might avoid a fair amount of the misuse.
This just uses the same `typeBubble` solution we already use for other entities; the main reason we didn't implement it here before is that we don't actually have descriptions for any of the types, which we need to add (little by little probably as to avoid overwhelming sir as much as possible).
1. Add descriptions to all label types
Manually, on test data where I added a few descriptions.
=> MBS-13278: Show label type descriptions on edit form

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Apparently people keep insisting on adding VGMdb links to RGs as either standalone sites or reviews, but VGMdb doesn't actually have anything that matches our RG level and these should never be added to RGs.
Just block VGMdb links on RGs entirely like we already did with Bandcamp links.
I also deleted the 9 still existing RG links by hand - they were all seemingly already present at the release level as well anyway. 
Added one basic test.
=> MBS-12423: Block VGMdb links from release groups

lib/MusicBrainz/Server/Report/LowQualityReleases.pm, lib/MusicBrainz/Server/ReportFactory.pm, root/report/LowQualityReleases.js, root/report/ReportsIndex.js, root/server/components.mjs
There's no easy way for a user to find all low quality releases for entities in their subscriptions in order to help improve them.
This adds a report listing all low quality releases, which as usual can be filtered to show only releases for entities in the user's subscriptions.
This existing should also make it less stressful to just mark something as low quality if an editor has no time or skill to fix it, since now they will know other users (or even themselves when they have the time) will be able to find it and hopefully work on it.
By hand, running the report and checking that the releases in it (for the sample data) are all low quality.
=> MBS-11920: Report for releases with low data quality

lib/MusicBrainz/Server/WebService/Validator.pm, t/lib/t/MusicBrainz/Server/Controller/WS/2/Collection.pm, t/lib/t/MusicBrainz/Server/Controller/WS/2/Validator.pm
We were not testing this at all, AFAICT - if we test some bits somewhere it's certainly not in a consistent way.
This adds a set of tests for most of the validation checks made by the WS validator.
I could not figure out a way to test `validate_required` (thought `/ws/2/tag?id=1946a82a-f927-40c2-8235-38d64f50d043` without `entity` would do, and it might actually hit this, but because there's no actual error messaged linked, it looks the same as if I passed a random `a=b` parameter instead of `id`).
I'm also not sure how `validate_linked` works - I understand it's used for collections, is it what checks that you're not requesting areas for a release collection? If so, we already test that on `Controller::WS::2::Collection`.
=> Test WS validation

admin/sql/InsertTestData.sql, lib/MusicBrainz/Server/Data/Role/Area.pm, t/lib/t/MusicBrainz/Server/Controller/Area/Events.pm, t/lib/t/MusicBrainz/Server/Controller/Area/Places.pm, t/lib/t/MusicBrainz/Server/Controller/Event/Show.pm, t/lib/t/MusicBrainz/Server/Controller/Event/Tags.pm, t/sql/event.sql
Since @amCap1712 put together some basic event test data for Sir, I thought I might as well use it to write a few event and event-adjacent tests. It's not a full suite of tests for event or anything, but it's a bit better than nothing at all.
=> Add basic event-related tests

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
CD Baby is gone anyway, so added URLs nowadays will be from old data. As mentioned in our forum
(https://community.metabrainz.org/t/cd-baby-store-closes-on-31-march/467757/12) we often could benefit from not cleaning those since the cleanup can make it harder to find archived versions of the data, and the "cleaned" URL is also broken by now anyway.
This removes cleanup/validation, but keeps the autoselection of the cdbaby reltype for artists.
None, other than keeping the cdbaby artist test but only with autoselection testing.
=> MBS-13268: Stop cleaning up CDBaby links

lib/MusicBrainz/Server/Report/ShowNotesButNotBroadcast.pm, lib/MusicBrainz/Server/ReportFactory.pm, root/report/ReportsIndex.js, root/report/ShowNotesButNotBroadcast.js, root/server/components.mjs
Show notes is a relationship meant to link podcasts and similar broadcast releases to their, well, show notes. Users do seem to use it quite a bit to link to anything that has anything to do with any release, whether it is a podcast or not, probably because it sounds more generic than other choices. This should make it easier for editors to find these bad edits, fix them, and maybe let the user know so they stop doing it.
Ran the report against the sample DB, found a few cases, all seemingly correct(ly incorrect).
=> MBS-13252: Report: Show notes links on non-Broadcast releases

lib/MusicBrainz/Server/Controller/User.pm
After a report is sent the user profile is loaded, but the URL stays as `/user/X/report` (and for some reason the report link moves on the page as described by the ticket).
Doing just `detach` here was causing the issues. I don't think that was intentional in any way, and we generally use `response->redirect` elsewhere, so I do that here too, which also stops the link moving.
Manually, by reporting a user.
=> MBS-13192: Redirect to profile post report rather than detach

lib/MusicBrainz/Server/Controller/Role/Collection.pm, lib/MusicBrainz/Server/Data/Collection.pm, root/layout/components/sidebar/CollectionLinks.js, root/layout/components/sidebar/CollectionList.js
We currently require login to see any data about collections for a specific entity, even when the entity is in a public collection that can otherwise be seen when logged out.
I don't think this is really intentional, but more of a side effect of the way the collections page / sidebar got implemented. I asked @Aerozol and he also suggested that this data should be shown to everyone, since it's interesting to showcase.
This shows only the "in X collections" link on the sidebar for logged out users (all others seem irrelevant). It also allows them to see the `/collections` page for the entity, showing only public collections.
We still want to pass `show_private_only` for `_all_non_visible_collections` when there's no user, since otherwise it will not restrict it to non-visible collections, …
=> MBS-13145: Also show collection tab to logged out viewers

RELEASING.md
It was previously unclear where update_pot.sh should be run now, and how .pot changes would reach beta.
=> Clarify translation steps for beta release

root/static/scripts/common/utility/releaseLabelKey.js, root/static/scripts/tests/release-editor/validation.js
`releaseLabelKey` automatically defaults to '' as the label key if no ID exists, meaning two labels such as "A" and "B" get seen as a dupe until an actual label with an ID is selected. This has confused users in the past, since as far as they could tell the labels are different.
This just makes it so that a label name is also taken into account when calculating the key. I chose to add a `name-` prefix to it to avoid the very unlikely but possible situation where a "label name" that matches the other label's row ID would trigger a "duplicate" error.
Manually, by entering two labels (A and B) without selecting a search result and checking the duplicate is no longer shown, but checking it's still shown if I enter A twice. Also added test cases (and improved the relevant test a bit).
=> MBS-13155: Don't consider all unselected labels dupes

lib/MusicBrainz/Server/Data/Editor.pm, t/lib/t/MusicBrainz/Server/Data/Editor.pm
Spammers cannot log in and cannot edit, so processing their subscriptions is a waste of time. Additionally, it seems some use the subscription email to know if their spam is being deleted, and create a new account to readd it. It would seem sensible to just not send them any subscription emails.
This explicitly excludes spammer editors when loading all editors we are going to process for mailing in `editors_with_subscriptions`.
Added a small section to the appropriate `Data::Editor` test. The `SubscriptionEmails` test uses mocks so this probably cannot be tested from there, but making sure the editor is not available to the script for processing should be enough.
=> MBS-13275: Don't send subscription emails to spammers

lib/MusicBrainz/Server/Entity/Editor.pm
We use `has_email_address` as a way to see whether the user has an email set that we can write to, but it's currently a Moose predicate for `email`. This means that if `email` is set to *anything*, it will return true, including the empty string (which we have for a couple thousand accounts) and, theoretically at least, `undef`. See https://metacpan.org/dist/Moose/view/lib/Moose/Manual/Attributes.pod#Predicate-and-clearer-methods
I changed this to just use the predicate as the first check; if email is set it will make sure it's defined and not the empty string.
Manually, checking the user mentioned on the ticket now shows `(none)` for their email.
=> MBS-13279: Don't consider the empty string an email address

lib/MusicBrainz/Server/Controller/AutoEditorElections.pm, lib/MusicBrainz/Server/Entity/Editor.pm, root/utility/voting.js
It is currently possible to nominate an editor for autoeditorship even if they have no verified email address, but an autoeditor who cannot enter edits is useless. It would limit clutter on the user profiles to not allow these nominations and not show the nomination link.
This checks for `has_confirmed_email_address` both to show the nominate link and to actually allow the nomination page to load (with `can_nominate`).
Manually with a newly-created (non-verified) user. Navigating to `/elections/nominate/username` gave a 404 which seems wrong, changing to 403 in a second commit.
=> MBS-13280: Block nominating unconfirmed editors

root/edit/details/EditRecording.js
If an edit such as `/edit/99374885` only makes subsecond changes to a recording's length, nothing at all is shown in the edit, since we diff on seconds and as such the diff is empty. That means it's entirely unclear what the edit even tries to do.
This shows an informative message equivalent to the one in `edit/details/SetTrackLengths`, since we seem to consider subsecond changes not worth displaying.
Manually, on the given edit.
=> MBS-13072: Notify on subsecond recording edit lengths

lib/MusicBrainz/Server/Entity/Editor.pm, lib/MusicBrainz/Server/Report/LimitedEditors.pm, root/layout.tt, root/layout/index.js
Checking for email confirmation in `is_limited` probably made sense when we called this "Limited user" (unconfirmed users are quite limited) but it doesn't make sense now that we explicitly use `is_limited` for beginners and claim everywhere the user is "new to MusicBrainz", since a user can remove their email even with thousands of edits.
This just removes the no `email_confirmation_date` condition for `is_limited`. `editorMayVote` already checks for `email_confirmation_date` separately. Elsewhere, we seem to be using `is_limited` just for beginner checks. `Predicate::Role::User` already was not looking at mail confirmation.
Tested with user `test`, which now shows as "Normal User"
=> MBS-13281: Don't check for mail confirmation for beginners

contrib/slowdown.psgi, contrib/ssssss.psgi, lib/MusicBrainz/Server/Controller/Admin/Attributes.pm, lib/MusicBrainz/Server/Controller/Role/Load.pm, lib/MusicBrainz/Server/Controller/Search.pm, lib/MusicBrainz/Server/Controller/WS/2/Tag.pm, lib/MusicBrainz/Server/Controller/WS/js/Edit.pm, lib/MusicBrainz/Server/Data/Relationship.pm, lib/MusicBrainz/Server/Data/Search.pm, lib/MusicBrainz/Server/Data/Utils.pm, lib/MusicBrainz/Server/Edit/Alias/Edit.pm, lib/MusicBrainz/Server/Edit/Area/Edit.pm, lib/MusicBrainz/Server/Edit/Artist/Edit.pm, lib/MusicBrainz/Server/Edit/Event/Edit.pm, lib/MusicBrainz/Server/Edit/Genre/Edit.pm, lib/MusicBrainz/Server/Edit/Label/Edit.pm, lib/MusicBrainz/Server/Edit/Place/Edit.pm, lib/MusicBrainz/Server/Edit/Recording/Edit.pm, lib/MusicBrainz/Server/Edit/Relationship.pm, lib/MusicBrainz/Server/Edit/Release/Edit.pm, lib/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm, lib/MusicBrainz/Server/Edit/ReleaseGroup/Edit.pm, lib/MusicBrainz/Server/Edit/Series/Edit.pm, lib/MusicBrainz/Server/Edit/URL/Edit.pm, lib/MusicBrainz/Server/EditSearch/Predicate/AppliedEdits.pm, lib/MusicBrainz/Server/EditSearch/Predicate/ID.pm, lib/MusicBrainz/Server/EditSearch/Predicate/Role/Subscribed.pm, lib/MusicBrainz/Server/Entity/Series.pm, lib/MusicBrainz/Server/Plugin/Diff.pm, script/dump-entities-sql.pl
The smartmatch operator (`~~`) and switch feature (`given`/`when`) are both deprecated as of Perl 5.38.
https://perldoc.perl.org/perl5380delta#Switch-and-Smart-Match-operator
=> Remove all uses of the smartmatch operator and switch feature

root/static/scripts/common/MB/Control/Autocomplete.js, root/static/scripts/release-editor/edits.js, t/selenium.mjs, t/selenium/MBS-8952.json5
If you select any recording which was obtained from the search server in a "Suggested recordings:" list in the release editor, then updating the recording autocomplete text will allow you to change the recording's name and unintentionally submit edits doing the same.
I was able to reproduce this using the steps in https://tickets.metabrainz.org/browse/MBS-13021.
The primary issue is that recordings from the search server don't include a database row ID, so the `if (currentSelection.id)` check modified here didn't clear the selection when modifying text. The `else` branch updated the recording name with the entered text and notified all subscribers of the autocomplete observable.
Checking for `currentSelection.gid` there fixes the bug. I also changed the edit generation code to revert any …
=> MBS-8952: Can rename recordings via autocomplete

admin/ExportAllTables, docs/database_schema_diagrams/write_graphs.pl, lib/MusicBrainz/Server/Data/Artist.pm, lib/MusicBrainz/Server/Data/Edit.pm, lib/MusicBrainz/Server/Sitemap/Builder.pm, lib/MusicBrainz/Server/Translation.pm, lib/MusicBrainz/Server/Validation.pm, t/hydration_i18n.t
The new `contains_string` and `contains_number` functions added by https://github.com/metabrainz/musicbrainz-server/pull/3048 are way more readable than an `any { $_ eq whatever }` call so replacing the straight equivalents when possible.
None other than CI for now.
=> Use new contains_ functions in more places

root/release/edit/information.tt, root/static/scripts/release-editor/bubbles.js
It's not particularly obvious when adding or editing a release that the content of the language/script fields should be the language/script of the track titles rather than the lyrics or the liner notes. The info is in the release guidelines, but most new users are not going to get there for quite a while.
This adds a bubble for the language and script fields, with a sentence for each based on the wording in the Style/Release guideline.
Manually, from `/release/add`.
=> MBS-13319: Show help bubble for language/script on release editor

admin/replication/LoadReplicationChanges, admin/replication/ProcessReplicationChanges
Fixed packets will be published in conjunction with this commit.
`--ignore-conflicts` is needed for people with aborted loads, since adding broken packet numbers to `$known_broken_sequences` has the effect of truncating the currently-loaded data.
=> MBS-13333: Replication is blocked by tag duplicates

root/artist/edit_form.tt, root/event/edit_form.tt, root/label/edit_form.tt, root/place/edit_form.tt, root/recording/edit_form.tt, root/release_group/edit_form.tt, root/series/edit_form.tt, root/static/scripts/edit/components/forms.js, root/work/edit_form.tt, t/selenium/Artist_Credit_Editor.json5, t/selenium/Check_Duplicates.json5, t/selenium/External_Links_Editor.json5, t/selenium/MBS-9941.json5
Install a beforeunload event listener on the artist, event, label, place, recording, release group, series, and work edit pages that prompts the user if any of the form's inputs have been changed.
One limitation of the approach used here is that it doesn't detect relationship changes.
Note that the release editor already displays a prompt if the page is unloaded with unsubmitted changes.
If an editing page is accidentally closed or navigated away from by a user before it's been submitted, data entered in JavaScript-dependent fields like Area, Relationships, and External Links are lost.
Listen for `change` events within `form` elements and install a `beforeunload` handler that prompts the user if the page is being unloaded after changes have been made. I added a small …
=> MBS-13320: Prompt before unloading modified forms

lib/MusicBrainz/Server/Data/Editor.pm, t/lib/t/MusicBrainz/Server/Data/Editor.pm
We just had a support case where the user already had an account, but `lost_username` claimed the email was not in use. When the user, confused, tried to create a new account, he got an email (using `is_email_used_elsewhere`) saying that the email is already in use. It seems the issue was due to capitalization differences (the email was stored in the DB with some capitalized letters)
We had a better query in `is_email_used_elsewhere` so this just reuses effectively the same query for `find_by_email`.
Using `_get_by_keys` ran `load_preferences`, which this does not. Since we don't seem to use the preferences for our use of `find_by_email` I did not bother loading them with the new method.
Added tests for these two email checks, and I improved and documented the `Data::Editor` test while at …
=> MBS-13334: Also find emails with capitalization differences in find_by_email

root/static/scripts/edit/components/forms.js, t/selenium/MBS-12641.json5
Make the `beforeunload` listener installed by `MB.installFormUnloadWarning` additionally use CSS selectors to check for pending relationship or URL changes.
Previously, only changes to input elements were detected.
#3054 only warns when navigating away from edit forms if a `change` event has been observed. This detects changes to text fields or checkboxes, but it doesn't catch relationship or URL changes. As a result, editors could still lose work if they accidentally closed or navigated away from forms when making relationship or URL edits.
@jesus2099 pointed out that the relationship editor uses `rel-add`, `rel-edit`, and `rel-remove` CSS classes when relationships are being changed. This change queries for those classes in the `beforeunload` handler to additionally detect relationship …
=> MBS-13320 (II): Warn on form unload with rel changes

root/static/scripts/common/components/ArtistCreditLink.js, root/static/scripts/edit/components/EntityPendingEditsWarning.js, root/static/scripts/edit/components/RelationshipPendingEditsWarning.js, root/static/scripts/relationship-editor/components/RelationshipDialogContent.js
"pending edits" are, in the way we are using the term, exactly the same as "open edits". As such, this normalizes the user-facing strings so that we always use "open edits" when we mean that.
We could arguably use "pending edits" for edits that still have not been entered, like the ones that will be created by an open release editor or relationship editor session.
That would seem like a much better use of the term, but sadly might require a huge refactoring since we use "edits_pending" in our schema for open edits.
None, but this changes strings only. I made sure this should be all of the translatable "pending" strings with a Weblate search.
=> Normalize "pending edits" to "open edits" in UI

admin/cleanup/FixTrackLength.pl, root/cdtoc/AttachCDTocConfirmation.js, root/cdtoc/list.tt, root/release/discids.tt, root/release/edit/tracklist.tt, root/report/CDTocNotApplied.js, root/static/scripts/tests/release-editor/trackParser.js, t/lib/t/MusicBrainz/Server/Edit/Medium/Delete.pm
There seems to be no difference between "duration" and "length" for track times. As such, this normalizes the user-facing strings so that we always use "track lengths"; it should be more clear and easier to translate.
None, but this changes strings only. I made sure this should be all of the translatable "track duration" strings with a Weblate search.
=> Normalize "track duration" to "track length" in UI

lib/MusicBrainz/Server/Form/Field/URL.pm
We correctly use `URL` in all user-facing strings except this one, which uses `url`. Standardizing it.
=> Capitalize URL in user-facing string

CONTRIBUTING.md, HACKING-PROD.md, HACKING.md, INSTALL.md, admin/InitDb.pl, lib/MusicBrainz/Server/Form/Field/URL.pm, po/README, root/artist/ArtistMerge.js, root/report/DuplicateReleaseGroups.js, root/report/InstrumentsWithoutAnImage.js, root/report/MediumsWithSequenceIssues.js, root/report/RecordingsWithFutureDates.js, root/report/TracksNamedWithSequence.js, root/report/TracksWithSequenceIssues.js, root/static/scripts/artist/components/ArtistCreditRenamer.js, root/user/PrivilegedUsers.js
As per the [design system guidelines](https://github.com/metabrainz/design-system/blob/master/guidelines/style-guidelines.md) we should not be using `i.e.` and `e.g.` since they are not as clear as "that is" and something like "such as" or "for example", respectively.
Changed all user-facing places I saw except for some API error strings using `e.g.` in case someone actually depends on the text of those for validation.
Separately changed all appearances I saw on other translatable places, such as relationship descriptions; appearances of `e.g.` on entity type descriptions left untouched for now to avoid causing issues with SIR.
None, but these are string changes only.
On top of https://github.com/metabrainz/musicbrainz-server/pull/3058 where `e.g.` was brought up.
=> Remove unneeded abbreviations

lib/MusicBrainz/Server/Controller/Collection.pm, root/edit/search_macros.tt, root/mbid/NotFound.js, root/relationship/linkattributetype/RelationshipAttributeTypeInUse.js, root/relationship/linktype/RelationshipTypeInUse.js, root/release/edit/tracklist.tt, root/static/scripts/common/MB/Control/EditSummary.js, root/user/UserProfile.js
We generally use "remove" for things like entities, and "delete" (which is almost the same but has a slightly stronger vibe) for editors only. This changes a few translatable "delete" strings that were actually meant for non-editors, so should probably use "remove".
None, but this changes strings only.
=> Use "remove" consistently for non-editor cases

package.json, script/xgettext.js, yarn.lock
xgettext-js uses @babel/parser, which doesn't support new Flow syntax, and I'm not sure it (Babel) will be updated any time soon.
Replace xgettext-js with a forked copy that uses hermes-parser instead.
=> Replace xgettext-js with forked copy using hermes-parser

root/release/edit/recordings.tt, root/static/scripts/tests/release-editor/seeds/mbs-13207.html, t/selenium.mjs, t/selenium/release-editor/MBS-13207.json5
Make "Add a new recording" appear above suggested recordings rather than below them in the release editor. This is intended to make it possible to select recordings using the keyboard (which is currently challenging due to W3C-mandated radio button focus behavior).
When adding a release, it's currently very difficult to assign existing recordings to tracks using only the keyboard.
After opening the recording-selection bubble, the focus is initially assigned to the search input. The Tab key cannot be used to advance the focus to an existing recording's radio button. Instead, the user must advance the focus through all of the recording, artist, and release group links before focusing the "Add a new recording" radio button (currently at the bottom of the table), at which point they can use …
=> MBS-13207 (II): Move "Add a new recording" above suggestions

lib/MusicBrainz/Server/Controller/Statistics.pm, lib/MusicBrainz/Server/Data/Statistics.pm, root/static/scripts/statistics.js, root/statistics/Countries.js, root/statistics/stats.js
While events and places are very directly associated to the areas they happen in, our country stats page at [`/statistics/countries`](https://musicbrainz.org/statistics/countries) has no country level stats for them. This seems like it would be interesting data to see.
While testing the code, I found a bug with release counts for countries with 0 releases, where the country would be skipped in the results rather than return 0 like for other entity counts. This is probably only an issue with sample data, since I'm pretty sure the production database has releases for all countries.
I added both of the entity types to the stats. Place is a trivial implementation since they work in the same way as artists and labels. For events I copied the relevant parts of the query we use to get events …
=> MBS-12852 / MBS-12893: Add events and places to country stats page

lib/MusicBrainz/Server/Data/Search.pm, lib/MusicBrainz/Server/Data/Tag.pm
While using genre aliases for actual genre tagging requires quite a bit of effort, mostly to come up with a sensible UI, there's no reason I can see why we shouldn't be showing the tag/genre associations from aliases on search results and the `/tag` page.
`/search?query=rap&type=tag` shows "hip hop" as the genre, `/tag/rap` shows "This tag is associated with the genre [hip hop](http://reolappy:5000/genre/52faa157-6bad-4d86-a0ab-d4dec7d2513c)."
=> MBS-12727: Show genre alias connections for tags

.eslintrc.yaml, package.json, root/report/CatNoLooksLikeLabelCode.js, root/report/RecordingsWithFutureDates.js, root/static/scripts/edit/components/ArtistCreditBubble.js, root/static/scripts/guess-case/utils.js, root/static/scripts/release-editor/duplicates.js, root/static/scripts/release/components/ReleaseRelationshipEditor.js, root/static/scripts/work/edit.js, root/user/ContactUser.js, root/utility/hydrate.js, yarn.lock
The last version of `newline-after-import` in `eslint-plugin-import 2.29.0` allows to actually specify the amount of lines as an exact count, not just a minimum, by setting `exactCount` to `true`. I also had to use `considerComments` so it would look at comments after import blocks as also needing to be separated with one blank line.
I ran the rule until it was happy. Does not change actual code bits.
=> Use exactCount for newline-after-import eslint rule

root/static/scripts/release-editor/validation.js
The release editor bubble showing other releases with the same barcode as entered does not show all matching releases, causing people to enter duplicates. 
While the code here speaks of multiple releases and is clearly meant to support more than one result, we were making the search with limit 1. I checked the original PR and did not find a reason why, other than it seems to have been part of my code suggestion (good job me). This just removes the limit.
Manually with full data tunnel, with the same barcode as in the ticket which does correctly show two releases now.
=> MBS-13350: Return all barcode matches in release editor

root/edit/components/EditList.js, root/static/styles/layout.less
Add a second "Submit votes & edit notes" button near the top of the /edits page so that users don't need to scroll to the end of a long page when voting and commenting on recent edits.
When viewing an entity's list of edits, the open edits are at the top of the page. It's unintuitive and a bit tedious to need to scroll all the way to the bottom of the page to submit votes and comments on open edits.
Add a second button near the top of the page. I had to move the `form` element outside of `PaginatedResults` in order for the button to be a child of the form.
I verified that both the top and bottom buttons work when viewing edits while logged in, and that the page renders as before when not logged in.
N/A
=> MBS-5987: Add "Submit votes & edit notes" to top

lib/MusicBrainz/Server/EditSearch/Predicate.pm, lib/MusicBrainz/Server/EditSearch/Predicate/RelationshipType.pm, lib/MusicBrainz/Server/EditSearch/Query.pm
MBS-13347
The use of `LIMIT 500` inside an edit search sub-query using the Relationship Type predicate causes PostgreSQL to ignore `edit_data_idx_link_type` and make use of a much less efficient query plan.
This commit adds a flag to `EditSearch::Predicate` which can be used to disable the addition of `$LIMIT_FOR_EDIT_LISTING` if the given predicate is present.
=> MBS-13347: Relationship Type edit search times out

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
LibraryThing uses -1, -2, etc. after the author name for authors of the same name (such as https://www.librarything.com/author/alexandermichelle-1). We currently (accidentally) block these.
It seems sensible and safe to allow hyphens alongside the already allowed numbers and letters, so this just does that.
Added a test with the URL given above.
=> MBS-13349: Support LibraryThing disambiguation URLs

admin/sql/CreateIndexes.sql, admin/sql/updates/20231005-edit-data-idx-link-type.sql, upgrade.json
MBS-13348
The query in the edit search that is supposed to make use of this index was changed in b21e5c579d0201325f5fbe385a51b663ae6caa69, but the actual index was never updated to match (so it could not be used).
This patch provides an upgrade script to run during the next schema change.
Note: This was already fixed in production.
=> MBS-13348: Fix edit_data_idx_link_type

lib/MusicBrainz/Server/Controller/WS/js/Edit.pm, t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
MBS-13309
/ws/js/edit is prone to CSRF attacks that could be used to trick editors into submitting edits without their review.
Restrict submissions from external origins to bot accounts.
=> MBS-13309: Restrict cross-origin requests to /ws/js/edit

admin/RebuildIndexesUsingCollations.pl
MBS-13336
Provide a script should be run after a system upgrade whenever the versions of libc/icu have changed, in order to avoid index corruption.
A future improvement may be to allow specifying which collation to rebuild indexes for, but it doesn't hurt to rebuild all of them (except for taking longer).
=> MBS-13336: Add a script to rebuild all indexes using collations

INSTALL.md, MAINTENANCE.md, admin/RebuildIndexesUsingCollations.pl
* Adds some flags to the script: `--database`, `--[no]concurrently`, and `--help`.
* Refreshes the "musicbrainz" collation version at the end of the script.
* Adds documentation in MAINTENANCE.md, referenced from INSTALL.md.
=> RebuildIndexesUsingCollations.pl improvements

lib/MusicBrainz/Server/Form/Field/URL.pm
Two different messages were used for the same error in two different forms, needlessly requiring an extra translation.
This patch makes the URL entity editor use the same error message as the external link field in the other entity editors.
The only display difference is that no HTML formatting is supported at the moment.
=> Use the same error message for all URL fields

lib/MusicBrainz/Server/Form/Application.pm
* `<code>` was wrongly displayed in the error messages for the callback URL when registering an application as a developer.
* The example URL was needlessly part of the message to be translated.
* Replace `<code>` with double quotes.
* Use a variable placeholder for the example URL.
=> Fix formatting OAuth URI error messages

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Spotify prerelease URLs were unknowingly blocked from being added to the external links of upcoming releases.
Note: Prerelease Spotify URLs point to countdown pages until the time the album is released, then it redirects to the album, so they allow streaming the music of the album once the countdown is reached.
For reference: https://artists.spotify.com/blog/countdown-pages-get-fans-hyped-for-your-new-album-spotify-stream-on
Auto-selecting the streaming relationship type for Spotify streaming URLs, as it eventually allows to stream it.
Ideally the relationship begin date should be set to the countdown date.
=> MBS-13362: Handle Spotify prerelease URLs

root/static/scripts/common/immutable-entities.js, root/static/scripts/release-editor/init.js, root/static/scripts/tests/common/immutable-entities.js, root/static/scripts/tests/release-editor/seeds/mbs-13273.html, t/selenium.mjs, t/selenium/release-editor/MBS-13273.json5
When release artist credits are updated, also update track credits that start with the old release credits (instead of only ones that exactly match the release credits).
For example, if the release credits are changed from "A" to "B", a track that was credited to "A feat. C" will be updated to "B feat. C".
When updating the artist credits on a release, track credits that exactly match the old release credits are automatically updated to use the new credits, but tracks that also include featured artists are not updated.
It's easy for an editor not to notice that some of the tracks weren't updated if the old and new artists have the same name. For example, see [edit #103710653](https://musicbrainz.org/edit/103710653) (later fixed by [edit …
=> MBS-13273: Update track credits with matching prefixes

HACKING.md, webpack/exec.mjs
Sometimes I want to write a quick, one-off script that imports some of our JavaScript modules and executes some functions in them. This is very difficult because the modules probably rely on Flow syntax and Webpack auto-imports.
Adds webpack/exec.mjs which can be used for this. Documents it and ./bin/sucrase-node (which is actually used to execute webpack/exec.mjs) in HACKING.md.
=> Add a tool that can execute any file via Webpack

admin/DisableAllTriggers, admin/InitDb.pl, admin/psql, lib/MusicBrainz/Server/DatabaseConnectionFactory.pm
Sometimes it's necessary to connect to the database specified by `MAINTENANCE` or `READWRITE` using `SYSTEM` credentials (because certain objects owned by a superuser need to be updated).
This is now possible by connecting to `SYSTEM_MAINTENANCE`, `SYSTEM_READWRITE`, or any variant of `SYSTEM_FOO`, where `FOO` is the name of a database defined in lib/DBDefs.pm.
This magic is only performed if `SYSTEM_FOO` isn't otherwise defined.
* Tested the InitDb.pl changes by running `dropdb -U postgres musicbrainz_test && ./script/create_test_db.sh`.
* Tested the psql changes by running `./admin/psql --system MAINTENANCE`.
* ~Did not test the DisableAllTriggers changes.~ [See below](#issuecomment-1798292409).
=> Allow connecting to any database with SYSTEM credentials

root/artist/edit_form.tt, root/components/forms.tt
"Sort name" is a non-obvious field. Recently we've seen people reading it as "short name", but even without that, it's often filled wrong.
There seems to be entirely no downsides to adding a bubble with a short explanation and a link to the guidelines, so I'm doing that and hoping it's enough to clarify the usage.
Manually, just to make sure the bubble appears and goes away as expected.
=> MBS-13326: Add documentation bubble for the artist sort name field

admin/config.incremental-json-dump.sh
The IP address of the SSH server used to sync incremental JSON dumps could not be changed without changing it in the current container, and ultimately in the source code/image.
This patch instead uses the hostname `mbincrementaljson.local` that must be defined in the container, for example by using the option `--add-host` of `docker run`.
It follows the same approach as for full export dump.
It intentionally targets the branch `production` for a deployment today as the SSH server will be moved.
1. Make sure to set `mbincrementaljson.local` through `--add-host` before deploying a new `json-dump` container.
=> Drop hard-coded IP address for incrental JSON dump

root/static/scripts/edit/externalLinks.js, t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Create.pm, t/selenium.mjs, t/selenium/MBS-9396.json5
Seeding URLs for the release group editor was not working at all - no error, nothing, just ignored completely. This has apparently been broken since at least 2017.
I figured out that the seeded links for RGs were not getting parsed at all right now because of the wrong sourceType string expectation. This is yet another victim of the "release_group" vs "release-group" clash, where we need to special-case everything. Sigh. I added such special-casing now.
Manually, by comparing `/release-group/create?edit-release-group.url.0.text=http://www.example.com/&edit-release-group.url.0.link_type_id=1` with `/artist/create?edit-artist.url.0.text=http://www.example.com/&edit-artist.url.0.link_type_id=1` and checking the seeding result is the same for both now.
Added a basic RG creation test to match …
=> MBS-9396: Properly parse seeded release group URLs

lib/MusicBrainz/Server/Data/ArtistCredit.pm, t/lib/t/MusicBrainz/Server/Data/ArtistCredit.pm
MBS-13310
When artists are merged, `Data::ArtistCredit::merge_artists` is called, which inserts new artist credits: each appearance of the old artist is replaced by the new one.  If the old AC had no references, it will have had an entry in the `unreferenced_row_log` table already; we should make sure to update that to point to the new AC, if the new one also has no references.
In `_swap_artist_credits`, update `unreferenced_row_log` to point to the new AC if it's unreferenced.
Remember that because artist credits have MBIDs, we'd like to preserve them from deletion where possible: there's a 2-day delay before we cleanup empty ACs, allowing time for them to be re-used with their original MBIDs intact. This applies to redirected MBIDs too; so while inserting empty artist credits may seem …
=> MBS-13310: Add new empty artist credits to unreferenced_row_log

lib/MusicBrainz/Server/Data/Edit.pm, lib/MusicBrainz/Server/Data/EditNote.pm, t/lib/t/MusicBrainz/Server/Data/EditNote.pm, t/sql/edit_note.sql
Whether notes can be added was being checked only at the `insert_votes_and_notes` level, but the equivalent `enter_votes` checks at a lower level, which seems a lot safer (we have plenty of calls for `add_note` outside of that method). Just in case ModBot is not otherwise considered able to add notes for whatever reason, this gives ModBot free pass (since we very often call `add_note` for ModBot directly).
Added a test for add_note specifically, made sure other tests still pass.
On top of https://github.com/metabrainz/musicbrainz-server/pull/2966 since that significantly changes the relevant test file.
=> Block notes on add note

root/edit/details/EditMedium.js
While this data is obviously less important here than on a general edit listing, since we know at least what the release is, it seems like a good idea to still show what edit preview applies to what medium, especially for multi-medium releases.
I couldn't think of any single good reason to drop this in previews (it doesn't even take much space) so I just dropped the difference entirely.
Manually.
=> MBS-13366: Also show medium data on Edit medium preview

lib/MusicBrainz/Server/Controller/Role/Alias.pm, t/lib/t/MusicBrainz/Server/Controller/Artist/DeleteAlias.pm, t/lib/t/MusicBrainz/Server/Controller/Label/DeleteAlias.pm, t/lib/t/MusicBrainz/Server/Controller/Recording/DeleteAlias.pm, t/lib/t/MusicBrainz/Server/Controller/Series/DeleteAlias.pm
This was originally added on my request over 10 years ago, but while it makes sense to require a note for all entity removals and other similarly destructive edits, alias removals just drop an MBID-less text field that is trivial to re-add, and is not significantly different from dropping a disambiguation or other similar text field.
Just drop the `requires_edit_note` argument from `delete_alias`.
Amusingly, we had more tests checking for this edit note requirement than most other more important ones...
I removed most, but left one testing it's no longer required.
=> MBS-13284: Don't require edit note for alias removals

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Currently, music videos from Bugs! are only allowed on recordings.
Like YouTube videos, it would make sense to be able to add them to releases as well.
=> MBS-13369 (1/3): Also allow Bugs! MV links on releases

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Currently, music videos on Melon are unsupported due to the existing link validation.
This patch adds support to add those links to releases and recordings.
=> MBS-13369 (2/3): Add support for Melon MV links

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Currently, music videos on Genie are unsupported due to the existing link validation.
This patch adds support to add those links to releases and recordings.
=> MBS-13369 (3/3): Add support for Genie MV links

lib/MusicBrainz/Server/Data/URL.pm, t/lib/t/MusicBrainz/Server/Data/URL.pm
MBS-13372
An unused URL that has a GID redirect cannot be deleted due to the foreign key reference.
Delete URL GID redirects in `Data::URL::delete`, the same as we do for other entities.
Just the added automated test.
=> MBS-13372: Unused URL with gid redirect cannot be deleted

lib/MusicBrainz/Server/Data/Release.pm, t/lib/t/MusicBrainz/Server/Edit/Release/Edit.pm
MBS-13300
If a release group has manually set cover art, and the release from which the cover art was taken is moved to another RG, then the leftover entry in the `release_group_cover_art` table which we fail to delete prevents the otherwise-empty RG from being deleted.
Delete unused rows from the `release_group_cover_art` table in `Data::Release::update`.
Just the added automated test.
=> MBS-13300: Delete RG cover art if release is moved

lib/MusicBrainz/Script/RemoveUnreferencedRows.pm
We have the following useless warnings in our daily cron log:
```
2023-11-18T00:16:37.053937Z Use of uninitialized value $ref_count in numeric eq (==) at
/home/musicbrainz/musicbrainz-server/admin/cleanup/../../lib/MusicBrainz/Script/RemoveUnreferencedRows.pm line 94.
```
If `$ref_count` is `undef`, then it means the row was already removed. This may be normal, as in the case of artist credits, but it's safe to skip here in any case. Log a message about it just in case it helps with debugging something later.
=> RemoveUnreferencedRows: Silence warning for already-deleted rows

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Genie has multiple tabs on their artist pages, the main artist page uses the format https://genie.co.kr/detail/artistInfo?xxnm=81599561, while other pages showing albums, songs and MVs differ slightly (e.g., https://genie.co.kr/detail/artistAlbum?xxnm=81599561).
They should be rewritten to the (canonical) main artist page so that relationship types are auto-selected.
Closes MBS-13370.
Added an extra test case that rewrites the albums page for an artist to their main page.
=> MBS-13370: Rewrite more artist pages for Genie

lib/MusicBrainz/Server/Report/ReleasesWithoutCAA.pm, lib/MusicBrainz/Server/ReportFactory.pm, root/report/ReleasesWithoutCaa.js, root/report/ReportsIndex.js, root/server/components.mjs
This report lists all releases that have no images in the Cover Art Archive at all. In its default state that's a ton (around 1.5 million), but this is mostly useful when filtered for subscriptions, allowing users to quickly find all the music by their favourite artists or labels that is missing cover art.
I tested locally (on sample) that the report runs and displays fine. That does not have CAA set up, but I quickly tested the query on jimmy to make sure it seemed sensible there and it gave a number of results similar to substracting total releases vs releases with cover art in our statistics from yesterday :)
=> MBS-11934: Add report for releases without CAA

lib/MusicBrainz/Server/Data/Alias.pm, lib/MusicBrainz/Server/Data/LinkAttributeType.pm, lib/MusicBrainz/Server/Entity/LinkAttributeType.pm, root/types/relationship.js, t/lib/t/MusicBrainz/Server/Data/Alias.pm, t/script/BuildSitemaps.t, t/sql/initial.sql
MBS-13375 - Load instrument aliases onto our LinkAttributeType objects
In order to implement MBS-13367, we will have to load instrument aliases onto our LinkAttributeType objects in order to output the aliases in our internal JSON format.
However, since this changes the format of cached data, it must be deployed on both the production and beta servers at the same time before we can deploy #3093 to beta.
Cherry-picks only the `LinkAttributeType` changes from https://github.com/metabrainz/musicbrainz-server/pull/3093 to target the production branch.
=> MBS-13375: Load instrument aliases onto our LinkAttributeType objects

po/Makefile
There is a persistent issue where running `./po/update_pot.sh` on different machines will re-wrap the strings to different page widths.
This hardcodes `-w` on both msgcat and msguniq to 79, which seemed to produce the least number of changes when I re-ran `./po/update_pot.sh`.
However, I'm not sure if this actually resolves the issue, because there may be other tools and variables affecting things, and I'm only able to test it on my machine.
Ran `./po/update_pot.sh` locally.
=> Set -w (page width) on msgcat and msguniq

lib/MusicBrainz/Server/Data/Area.pm, lib/MusicBrainz/Server/Data/Artist.pm, lib/MusicBrainz/Server/Data/Collection.pm, lib/MusicBrainz/Server/Data/Editor.pm, lib/MusicBrainz/Server/Data/Event.pm, lib/MusicBrainz/Server/Data/Genre.pm, lib/MusicBrainz/Server/Data/Instrument.pm, lib/MusicBrainz/Server/Data/Label.pm, lib/MusicBrainz/Server/Data/LinkAttributeType.pm, lib/MusicBrainz/Server/Data/LinkType.pm, lib/MusicBrainz/Server/Data/Place.pm, lib/MusicBrainz/Server/Data/Recording.pm, lib/MusicBrainz/Server/Data/Release.pm, lib/MusicBrainz/Server/Data/ReleaseGroup.pm, lib/MusicBrainz/Server/Data/Series.pm, lib/MusicBrainz/Server/Data/URL.pm, lib/MusicBrainz/Server/Data/Work.pm
Some of these were just stupid (having a map for same-name keys, then having some other same-name keys outside the map). Some were mostly fine but inconsistent - I though I would just make it so that the ones that already followed a mostly equal pattern would actually be equivalent.
FWIW, a lot of this seems kinda redundant with `_column_mapping` - it might be possible to just make it simpler using that.
=> Make _hash_to_row methods more consistent

root/static/scripts/relationship-editor/utility/compareRelationships.js, root/static/scripts/tests/index-web.js, root/static/scripts/tests/relationship-editor/utility/compareRelationships.js
We were only performing special series checks in compareRelationships in cases where the series entity is the source. This means entering relationships to series from other entities was entirely skipping this mechanism, so that different numbers for the same series got blocked as a duplicate relationship.
This commit makes it so that the same mechanism is used if both targets are the same series, and the other conditions apply.
Manually. We don't seem to have any tests for rejecting duplicate relationships (just for merging them); we probably should. @mwiencek, you might be a lot faster writing these than I would, could I convince you to?
=> MBS-13368: Properly compare series relationships if series is target

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
As far as I can tell, YouTube Music uses mostly five kinds of URLs:
1) watch (YouTube videos) for tracks
2) playlist for releases (and also other playlists)
3) channel for artists
4) search for search
5) browse for things like discography lists and, apparently, users' own videos and private stuff.
This supports watch for recording, playlist for release, channel for artist, and does not support browse or search links at all.
I didn't find label, series, etc channels, so I didn't touch those.
I added a new YouTube Music relationship for artists to avoid users having to check for each artist whether there's some paid content or all is free (which might anyway change later).
Label reltypes are not affected at all rn, meaning that streamingfree.label is technically still allowed. We could …
=> MBS-11556: Standardise / clean up YouTube Music URLs

root/static/scripts/edit/components/ReleaseMergeStrategy.js, root/static/scripts/edit/utility/isUselessMediumTitle.js, root/static/scripts/release-editor/fields.js, root/static/scripts/tests/edit/utility/isUselessMediumTitle.js, root/static/scripts/tests/index-web.js
MBS-12034 made it mandatory to provide a confirmation when adding a "Disc 1" style medium name when editing a release. I did not remember, when implementing it, that there is a second place where you can set medium names: the release merge page. Right now, nothing blocks adding those from that page nor warns the user it might be a bad idea.
I just implemented a basic warning, which is probably enough. We could also disable submission unless they confirm, by erroring at the Perl level, but this is less intrusive and hopefully does the trick still, since it appears just below the name row as soon as the user enters the triggering name.
Tested manually when merging two random releases, since the testing is only dependent on the entered medium name.
=> MBS-12801: Warn users about "Disc n" titles on release merge

lib/MusicBrainz/Server/Report/ArtistsThatMayBeGroups.pm, lib/MusicBrainz/Server/Report/ArtistsThatMayBePersons.pm, root/report/ArtistsThatMayBePersons.js
The ArtistsThatMayBe(Persons|Groups) reports are kind of a mess. They have a fair amount of false positives and do not cover a lot of the relationships and artist types added in the last few years.
This updates the reports to check for (or ignore) additional relationship types, plus it makes it so that the Persons report does not try to turn all characters into people. See each commit message for additional details.
Tested with sample data to check the new results of the reports seem to make sense.
=> MBS-12318 / MBS-12323 / MBS-12324: Improvements to ArtistsThatMayBe reports

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
The three sister sites progarchives.com / jazzmusicarchives.com / metalmusicarchives.com support video links, which we had missed before so we were blocking. It makes sense to allow these to be linked to recordings.
Documented with https://wiki.musicbrainz.org/index.php?title=Other_Databases_Relationship_Type%2FWhitelist&type=revision&diff=77212&oldid=77195 (we don't have per-entity info for progarchives).
Added tests for these as usual.
=> MBS-13397: Support video pages for jazzmusic/metalmusic/progarchives

HACKING.md, root/static/scripts/tests/examples/todo-list/README, root/static/scripts/tests/examples/todo-list/Todo.js, root/static/scripts/tests/examples/todo-list/TodoList.js, root/static/scripts/tests/examples/todo-list/index.html, root/static/scripts/tests/examples/todo-list/index.js, webpack/tests.config.mjs
We are lacking developer documentation on how to best manage React state for complex pages.  This can also help in understanding how existing code, like the relationship editor, is structured.
Adds a section about React state management to HACKING.md and an example component in root/static/scripts/tests/examples/todo-list/.  I'm not sure if the example is helpful or necessary -- if not we can just remove it.
=> Document React state management

lib/MusicBrainz/Server/Controller/Recording.pm
[MBS-12560](https://tickets.metabrainz.org/browse/MBS-12560): Stop using track ID for recording ID URL
In MB, if you call the `/entity/id` URL, it will redirect to the matching `/entity/gid` URL.
But it is broken for recording:
NGS has now separate track and recording ID, but pre-NGS, there was some
redirection necessary or something: 7acea69a042a4f50f759199fe661e736cee208a4
Example: https://musicbrainz.org/recording/272811 should lead to [recording with ID 272811](https://musicbrainz.org/search/edits?auto_edit_filter=&order=desc&negation=0&combinator=and&conditions.0.field=recording&conditions.0.operator=%3D&conditions.0.name=with+ID+272811&conditions.0.args.0=272811&conditions.1.field=type&conditions.1.operator=%3D&conditions.1.args=72%2C204%2C245).
Not to unrelated recording with ID …
=> MBS-12560: Stop using track ID for recording ID URL

lib/MusicBrainz/Server/Data/EditNote.pm, lib/MusicBrainz/Server/Data/Editor.pm, lib/MusicBrainz/Server/Entity/Preferences.pm, lib/MusicBrainz/Server/Form/User/Preferences.pm, root/static/scripts/account/components/PreferencesForm.js, root/static/scripts/tests/utility/constants.js, root/types/editor.js, t/lib/t/MusicBrainz/Server/Data/EditNote.pm, t/sql/edit_note.sql
Our entire preference system for mailing editors is a horrible buggy mess. `email_on_notes` wrongly determines whether the original editor gets mailed, `email_on_vote` is completely unused and votes also depend on `email_on_notes`, and we have an undocumented hardcoded feature changing the way the email works on abstain for three specific editor IDs.
The first commit ensures the original editor is *always* emailed notes on their edits. 
The second commit splits the checks for `email_on_notes` and `email_on_vote` so they actually affect notes and votes respectively.
The third commit gets rid of the hardcoded IDs "preference" for abstain notifications and adds an actual preference that anyone can actually use, so that editors can choose whether they want to use abstain to wait and see what …
=> MBS-13364 / MBS-13377 / MBS-13378: Fixes / improvements for editor mailing preferences 

root/static/scripts/edit/externalLinks.js, root/static/scripts/relationship-editor/components/RelationshipEditor.js, root/static/scripts/relationship-editor/utility/prepareHtmlFormSubmission.js, t/selenium.mjs, t/selenium/MBS-13392.json5
MBS-13392 - External links editor changes are lost if the form reloads
MBS-13393 - Can't update relationships or external links for entities with a lot of them
For MBS-13392, instead of using `MB.formWasPosted`, which no longer exists, we can check the request method on the Catalyst context object instead.
For MBS-13393, see the associated commit.
Tested manually. (I temporarily commented out some lines in validation.js to make submitting invalid forms easier.) Added a Selenium test for MBS-13392.
=> MBS-13392 / MBS-13393: Restore the external links editor submission upon form reload, and reduce the relationship data stored in sessionStorage

root/area/edit_form.tt, root/components/common-macros.tt, root/edit/search_macros.tt, root/genre/CreateGenre.js, root/genre/DeleteGenre.js, root/genre/EditGenre.js, root/instrument/edit_form.tt, root/relationship/linkattributetype/create.tt, root/relationship/linkattributetype/edit.tt, root/relationship/linkattributetype/form.tt, root/relationship/linktype/create.tt, root/relationship/linktype/edit.tt, root/relationship/linktype/form.tt, root/static/scripts/genre/components/GenreEditForm.js
Implement (more of) MBS-13117
A few admin-only files (mostly TT ones) were forgotten with https://github.com/metabrainz/musicbrainz-server/pull/3091 so this makes those also untranslatable. I also found one admin-only string in an otherwise standard file so I used `l_admin` for that one.
Some manual testing to make sure the changes to the instrument page and the `l_admin` call both work.
=> MBS-13117 (II): Make more admin strings untranslatable

root/static/scripts/release-editor/init.js, root/static/scripts/tests/release-editor/seeds/mbs-13273.html, t/selenium/release-editor/MBS-13273.json5
Fix a bug introduced by 2d82124e where tracklist artist credits could be duplicated when changing release artists.
When changing release credits to "A & B" while a track was already credited to "A feat. B", the track credits would be changed to "A & B feat. B". This change sets track credits to the new release credits (i.e. "A & B") if they already contain the same artists as the new release credits.
As described at [this comment](https://tickets.metabrainz.org/browse/MBS-13273?focusedCommentId=70393&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-70393), 2d82124eb732026305d74cb0074888ee460c4aa7 could result in secondary artists getting duplicated in cases where the release and track artists didn't match.
Specifically, the change was (by design) updating …
=> MBS-13404: Avoid duplicating feat. artists

root/relationship/linkattributetype/DeleteRelationshipAttributeType.js, root/relationship/linkattributetype/RelationshipAttributeTypeInUse.js, root/relationship/linkattributetype/RelationshipAttributeTypesList.js, root/relationship/linktype/DeleteRelationshipType.js, root/relationship/linktype/RelationshipTypeInUse.js, root/relationship/linktype/RelationshipTypePairTree.js
Messages which are exclusively addressed to relationship type editors (who are required to speak English to some extent anyway) do not need to be translated in several languages and to increase the burden on translators.
This has been mostly resolved with the pull request #3120 but a few files have been left behind.
- Drop `l` calls from files addressed to relationship type editors only
- Use `l_admin` in files addressed to normal editors too
- Use `exp.l_admin` (or `texp.l_admin`) when needed for cleanup and interpolation
=> Avoid translating more messages for relationship type editors

root/cdstub/BrowseCDStubs.js, root/report/ReportsIndex.js, root/static/scripts/account/components/EditProfileForm.js, root/statistics/timeline.tt, t/lib/t/MusicBrainz/Server/Controller/CDStub/Browse.pm
A few string changes in the pull request #3083 have not been applied to all occurrences, creating duplicates in translation.
=> Amend previous string changes

lib/MusicBrainz/Server/Form/Field/ArtistCredit.pm, lib/MusicBrainz/Server/Form/Merge.pm, lib/MusicBrainz/Server/Form/Role/CSRFToken.pm, lib/MusicBrainz/Server/Form/User/Login.pm, lib/MusicBrainz/Server/Form/User/Register.pm, lib/MusicBrainz/Server/Form/Utils.pm, lib/MusicBrainz/Server/Form/Work.pm
Trying to submit (or seed, reportedly, haven't tested that directly) an artist credit field where there's a string with brackets as either the artist credit (with the artist field empty) or the artist (unlinked) raises an error telling the user that's wrong, as expected (e.g. `Artist "[whatever]" is unlinked, please select an existing artist.`) . FormHandler passes that to maketext, which chokes on the brackets (a restricted notation for it, see https://perldoc.perl.org/Locale::Maketext#BRACKET-NOTATION) and ISEs.
I generalized the override we used elsewhere to skip `maketext` as `localize_error`, and then used it for artist credits as well.
While I was here, I simplified the check that raises the errors, since `$name` always exists if `$artist_name` does.
Manually. You can try to add a …
=> MBS-12802: Use localize_error for artist credit errors

lib/MusicBrainz/Server/Data/Track.pm
There's currently no way to see whether the releases a recording appears on are high, low or normal data quality from the recording page. This would be a useful way to see what releases might, for example, have the recording assigned wrongly.
This loads data quality on `Track::find_by_recording`, allowing us to display the correct data quality icon in the recording index page.
Manually, with `/recording/01a066a8-f4ec-4261-bf3e-0453c76d20b7` in main DB, which has one release with low data quality and one with normal/default data quality.
=> MBS-13401: Also load data quality for track releases

lib/MusicBrainz/Server/Data/Statistics.pm, root/statistics/stats.js
`count.edit.evalnochange` is hardcoded as "0" in the statistics table, and doesn't appear to have any use. The string "Evalnochange edits" is confusing to translators, because it doesn't correspond to anything that exists.
I found this mention of it from 2003-12-08 (happy belated birthday!):
```
<djce> ruaok: hmmm... somehow your server has heard about
ModDefs::STATUS_EVALNOCHANGE, even though it doesn't exist any more,
and isn't in the codebase.
```
=> Remove bogus evalnochange stats

root/static/scripts/relationship-editor/components/RelationshipDialogContent.js, t/selenium/Artist_Edit_Form.json5, t/selenium/MBS-2604.json5
When adding a new artist, infer the correct direction for an individual-to-group relationship from the target artist's type.
54f9433c39c73c4390fcca9c525789db4dc21df1 made the "Edit artist" form infer the correct direction for individual-to-group artist relationships (e.g. member-of/members) based on the types (e.g. Person, Group, etc.) of the source and target entities. This didn't work when adding a new artist, since the source type is null.
Even if the source type is unknown, it's possible to infer the correct direction based on the target entity's type. For example, a "member of" relationship is probably correct if the target is a group, and a "members" relationship is probably correct if the target is a person.
I did some manual testing, but more is always appreciated.
I also updated …
=> MBS-13405: Also infer rel dirs when adding artists

lib/MusicBrainz/Server/Data/Event.pm, lib/MusicBrainz/Server/Data/Recording.pm, lib/MusicBrainz/Server/Data/Release.pm, lib/MusicBrainz/Server/Data/ReleaseGroup.pm, lib/MusicBrainz/Server/Data/Work.pm, lib/MusicBrainz/Server/Form/Filter/Event.pm, lib/MusicBrainz/Server/Form/Filter/Generic.pm, lib/MusicBrainz/Server/Form/Filter/Recording.pm, lib/MusicBrainz/Server/Form/Filter/Release.pm, lib/MusicBrainz/Server/Form/Filter/ReleaseGroup.pm, lib/MusicBrainz/Server/Form/Filter/Work.pm, root/artist/ArtistEvents.js, root/artist/ArtistIndex.js, root/artist/ArtistRecordings.js, root/artist/ArtistReleases.js, root/artist/ArtistWorks.js, root/static/scripts/common/components/FilterForm.js, t/lib/t/MusicBrainz/Server/Controller/Artist/Filtering.pm, t/sql/filtering.sql
This adds two new filtering options: video/not video for recordings and disambiguation for all entities.
It also makes the flow typing more robust and organizes the code a bit more (I don't dare say simplifies it, but it's less spaghettish at least).
By hand (mostly on Nine Inch Nails recordings), plus added tests.
=> MBS-12799 / MBS-7028: Extra options for filters

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Bandcamp `/tag` links now redirect to a revamped `/discover` page, links which we don't currently support.
This cleans up `/tag` links and drops unwanted extras from `/discover` ones (see test).
Added one test for `/discover`, changed the existing `/tag` one to check the redirect.
=> MBS-13420: Support Bandcamp /discover tag links

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
x.com URLs are simply redirects to the equivalent twitter.com URL, so we might as well clean them up.
Added one test
=> MBS-13414: Normalize x.com URLs to twitter.com

lib/MusicBrainz/Server/Email/Subscriptions.pm
Subscription emails are missing a space between names and disambiguation comments of deleted entities and contain an extra space after comments, e.g.
`Artist "Name"(comment)  - merged by edit #...`
Fix the spacing.
---
I didn't bother with filing an issue or filling out the PR template since this is a trivial change, but let me know if I should've.
`t/lib/t/MusicBrainz/Server/Email/Subscriptions.pm` seems like it didn't catch this since it only looks at a deleted collection.
=> Fix deleted entity spacing in subscription email

root/static/scripts/common/i18n/expand2react.js, root/static/scripts/common/i18n/expand2text.js, root/statistics/Countries.js, root/statistics/CoverArt.js, root/statistics/Editors.js, root/statistics/Edits.js, root/statistics/Formats.js, root/statistics/Index.js, root/statistics/LanguagesScripts.js, root/statistics/MusicBrainzHistory.js, root/statistics/NoStatistics.js, root/statistics/Relationships.js, root/statistics/stats.js, root/statistics/utilities.js, root/vars.js, script/xgettext.js, webpack/providePluginConfig.mjs
Text that needs to be expanded - because it contains either variables or HTML tags - is incidentally not translated when rendering statistics pages.
This is because it was using `exp.l` or `texp.l` which match the translation domain `server` instead of `statistics`.
From a discussion on IRC, I found some additional issues with rendering translations from the statistics domain.
Add `l_statistics` and `ln_statistics` to `exp` and `texp`, auto-import these new functions, parse these for string extraction, and use these instead of `l` and `ln` under `root/statistics/`.
Make use of it for rendering event descriptions.
Fix rendering translations in MusicBrainz history and statistics timeline.
=> MBS-13431: Fix using translations for expanded strings in statistics

root/static/scripts/edit/utility/guessFeat.js, root/static/scripts/release-editor/recordingAssociation.js, root/static/scripts/release-editor/utils.js, root/static/scripts/tests/index-web.js, root/static/scripts/tests/release-editor/recordingAssociation.js, root/static/scripts/tests/release-editor/utils.js
MBS-13327
When deciding whether to unlink a recording, compare track names with featured artists removed.
Since `extractFeatCredits` is a heavy function to run each time a track name is modified (and is useless except when the title contains featured artists), I added `featQuickTestRegex` so that it can bail out early if it's sure there will be no matches.
Tested locally with http://localhost:5000/release/f04eef04-06b7-498c-ae69-9a41e4d1686c/edit (on master, it unlinks the recordings).
Also added some tests for `similarTrackNames` and `watchTrackForChanges`.
=> MBS-13327: Don't unlink recording from track when removing feat. artists

admin/RunIncrementalJSONDump, admin/config.default.sh, admin/config.incremental-json-dump.sh, docker/templates/Dockerfile.json-dump.m4
Currently, when incremental JSON dumps are generated, they are (1) copied to a local "FTP directory" (which, confusingly, is not our actual FTP server; it's just a local volume), and (2) rsynced to a (possibly) remote volume on the same host as the metabrainz.org container.
There is not really any reason to do (1) if (2) is succesful, because we presumably backup (2) already with borgmatic; there is no need to store these in three places.
This is more relevant now, because the incremental JSON dumps are being moved to hendrix, which is also where the metabrainz.org container is hosted. So without these changes, we'd be storing them twice on the same host!
This updates admin/RunIncrementalJSONDump to NOT copy any dumps from the temporary dump directory to any local volume, only rsync the …
=> Don't store incremental JSON dumps in a local volume

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
We got a report that we were mangling Bandcamp `/videoframe` links, since the cleanup was removing the video ID from them.
On researching it, yvanzo found that these seem to be intended as Bandcamp's inner working links, as they are, as far as we have found, meant to be shown in an `iframe` in `/track` pages (notice that the links are not even listed under the appropriate artist.bandcamp.com subpage).
Since linking to the `/track` page seems a lot better, this blocks adding `/videoframe` pages and suggests using the `/track` link instead.
I shortcut the cleanup code when these links are found so that we don't run it and remove the query parameter needed for accessing it, since that's quite confusing. I considered cleaning them up to HTTPS but since we're blocking them anyway, I guess it …
=> MBS-12879: Block Bandcamp /videoframe links 

root/event/edit_form.tt
The documentation for setlist formatting in the event edit form contains the following very useful line:
`If needed, the characters "[", "]", and "&" can be escaped using the HTML entities "[", "]", and "&" respectively.`
Clearly, something went wrong with the escaping.
This turns `&lsqb;` into `&amp;lsqb;`, and so on for the others, which makes the line appear as intended:
`If needed, the characters "[", "]", and "&" can be escaped using the HTML entities "&lsqb;", "&rsqb;", and "&amp;" respectively.`
It also encloses the entities in `<code>` for consistency with the similar string in `root/annotation/EditAnnotation.js`.
Manually, by loading the page and making sure it displays the HTML fine, and also by copy-pasting the HTML and using it in a setlist as `&lsqb;testy&rsqb;` to ensure it …
=> MBS-13443: Properly display HTML setlist codes

.circleci/config.yml, docker/musicbrainz-tests/DBDefs.pm, docker/musicbrainz-tests/chrome.service, docker/musicbrainz-tests/run_circleci_tests.sh, docker/musicbrainz-tests/run_selenium_tests.sh, lib/MusicBrainz/Server.pm, lib/MusicBrainz/Server/Translation.pm, root/futureColumnLabels.js, root/server/gettext/poFile.mjs, root/static/scripts/edit/URLCleanup.js, root/static/scripts/relationship-editor/utility/compareRelationships.js, root/static/scripts/tests/Control/URLCleanup.js, root/static/scripts/tests/relationship-editor/utility/compareRelationships.js, t/selenium/MBS-9669.json5, webpack/babel-ignored.cjs, webpack/client.config.mjs
Before the commit a0b56e9f8f9729f1e0c33df799ddbdaf29d0a44b the commands in the `js-perl-and-pgtap` test were ran with these shell options:
* `-e` to exit on error status code of any command,
* `-o pipefail` to exit on error status code of any piped sub-command.
See https://circleci.com/docs/configuration-reference/#default-shell-options
However the new script didn’t have these options enabled, causing failures from `flow` (among others) to go unnoticed.
This patch restores the previous/wanted behavior by enabling these in the script.
I built and uploaded a new pair of test images with the version [`v-2024-01.419`](https://hub.docker.com/r/metabrainz/musicbrainz-tests/tags?page=1&name=v-2024-01.419).
I also resolved the failures that went unnoticed so far:
- ESLint errors
- Genie and Bugs! …
=> Restore failing CircleCI tests on error

lib/MusicBrainz/Server/Entity/Barcode.pm, root/static/scripts/release-editor/fields.js, root/static/scripts/release-editor/validation.js, root/static/scripts/tests/release-editor/validation.js
GTIN-14 identifiers ("barcodes") seem to be becoming more common in digital storefronts and the like. Since these are the identifiers sent by the distributors, we should keep them, even they are generally just zero-padded EANs. Right now the release editor considers these invalid and asks the user to check the box though.
`is_valid_ean` on the Perl side already accepts GTIN-14 so nothing to change there - this mostly just changes the release editor validation and adds a basic test for it.
I added a `GTIN` type to `Entity::Barcode` since I guess it cannot hurt. Not sure if we use these at all but :)
Manually in the release editor, plus added a test.
=> MBS-13346: Support GTIN-14 barcodes

lib/MusicBrainz/Server/Data/Utils.pm, lib/MusicBrainz/Server/Form/Role/EditNote.pm, lib/MusicBrainz/Server/Form/Vote.pm, lib/MusicBrainz/Server/Validation.pm, root/static/scripts/release-editor/init.js, t/lib/t/MusicBrainz/Server/Validation.pm, t/selenium.mjs, t/selenium/Vote_And_Note_Submission.json5, t/sql/vote_and_note_selenium.sql
Our useless edit note checks (`is_valid_edit_note` and `invalidEditNote`) only check edit notes that are required (so, release adds and destructive edits mostly), and they don't check for formatting characters, which means it's very easy to enter useless notes whether by mistake or, like in the case that prompted the ticket, as a strange attempt at vandalism.
Three commits here that fix different parts of the problem:
The first makes the edit note checks ignore formatting characters when trying to determine whether a note contains any useful content or not. The affected characters are `ZERO WIDTH SPACE`, `SOFT HYPHEN` and the categories [`Cc`](https://www.compart.com/en/unicode/category/Cc), [`Cf`](https://www.compart.com/en/unicode/category/Cf) and …
=> MBS-13432: Ignore format chars when checking for useless notes and check them in more places

lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
When trying to unset work orders by unchecking the "These relationships have a specific ordering" checkbox in the release relationship editor, it triggers the error `EDIT_RELATIONSHIPS_REORDER: invalid link_order`.
Unsetting ordering sets orders to 0, but this only accepted positive integers with `is_database_row_id`. We could use `is_non_negative_integer` but I guess it was intentional to limit this to at most `MAX_POSTGRES_INT`, so this just allows 0 in addition to `is_database_row_id`.
Manually, making sure the orders can now be unset (and set again).
=> MBS-13402: Unbreak unsetting work order in release rel editor

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
We supported Qobuz URLs inasmuch as we showed them on the sidebar with their favicon, but we were not autoselecting them, since we couldn't until recently allow more than one option, and as such we were not validating them, since that was not possible without the selection.
Now we can offer the following options for selection: paid streaming (always available) or both paid streaming and download purchase (available in some markets, but not in LATAM for example).
We can also validate per entity: artists get /interpreter, labels get, well, /label, and releases get /album.
Added some tests, plus some manual testing too ensuring the autoselection for streaming works and download is still available to select on top of it.
=> MBS-13438: Restrict and validate Qobuz URLs

root/static/scripts/edit/components/ArtistCreditBubble.js
Artist credits are not only for collaborations, so the current help is misleading rather than useful. @Aerozol proposed adding "name variations" which I guess would now cover most cases at least.
None, but this is just a string change.
=> Improve AC bubble wording

lib/MusicBrainz/Script/RemoveUnreferencedRows.pm, t/lib/t/MusicBrainz/Script/RemoveUnreferencedRows.pm, t/sql/artistcredit.sql
We do not want an unreferenced artist credit to be removed if there's any pending edits editing them - that will fail the edit and go against the intent of letting people reuse credits.
For `artist_credit` table ids, we also check `edits_pending` and skip the id, without removing it from the table, if it has open edits. Whenever it no longer has open edits, it will either be deleted as empty, or dropped from the table if it now has a `ref_count`.
There's a second issue which probably cannot be solved in a trivial way, of artist credits not being edited themselves but being used in open edits. Is there even a way to check this without looking through all the `edit_data` for any edits which might use ACs? We could of course use `edits_pending` here too if we made these edits affect the AC's …
=> MBS-12636: Do not remove unreferenced ACs with pending edits

root/artist_credit/ArtistCreditIndex.js, root/static/scripts/edit/components/ExternalLinkAttributeDialog.js, root/static/scripts/edit/components/UrlRelationshipCreditFieldset.js, root/static/scripts/edit/externalLinks.js, t/selenium/External_Links_Editor.json5
URL relationships can have credits for the non-URL entity, if it is of a creditable type, but there is no way currently to change the credit from the entity page (only from the URL `/edit` page). This is confusing, and we really should allow editing this data from the page URL rels are most commonly edited, same as we now do for relationship dates.
This makes it possible to change the credited entity in the same popup where we currently change the dates.
Note that this doesn't implement any changes in the release editor since release-url rels are not currently creditable - if that changes then [we should] make relevant changes to `externalLinkRelationship` in `root/static/scripts/edit/MB/edit.js`
Tested manually by adding, editing and removing a credit for the artist for a URL …
=> MBS-11910: Allow editing rel credits in the external links editor

root/edit/components/EditSummary.js, t/selenium/Vote_And_Note_Submission.json5
In edit summaries, the "Add note" / "Remove note" toggle button is not reachable with keyboard navigation (it's completely skipped when tabbing).
Since this is an `<a>` without href, it was being skipped by the tabindex, but we want it to be tabbable. There seems to be no reason why this should not be `<button>` instead, which makes it tabbable by default. It also means it responds to Enter and Space keypresses, which is nice.
Manually, by tabbing around a list of open edits and ensuring the button is reachable and pressing Enter opens/closes the note field.
=> MBS-13413: Allow using "Add/Remove note" with keyboard

lib/MusicBrainz/Server/Controller/WS/2/Release.pm, lib/MusicBrainz/Server/Entity/Barcode.pm, lib/MusicBrainz/Server/Validation.pm, lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Release.pm, root/static/scripts/release-editor/fields.js, root/static/scripts/release-editor/validation.js, root/static/scripts/tests/release-editor/validation.js, t/lib/t/MusicBrainz/Server/Controller/Release/Aliases.pm, t/lib/t/MusicBrainz/Server/Controller/Release/Show.pm, t/lib/t/MusicBrainz/Server/Controller/WS/2/SubmitRelease.pm, t/lib/t/MusicBrainz/Server/Validation.pm
A number of issues related to GTIN (EAN/UPC) barcodes have been noticed while reviewing the initial implementation of MBS-13346 with PR #3078:
1. The barcode submission API and the release editor aren’t validating the same types of barcode.
2. The JSON-LD property [`gtin14`](https://schema.org/gtin14) is misused for barcode in release’s JSON-LD serialization.
3. GTIN-14 is mistaken for fully zero-padded 14-digit GTIN, whereas GTIN-14 doesn’t start with a 0 and is for shipment only.
4. GINC/GSIN/SSCC are validated whereas these are for shipment only.
5. GTIN-8 (EAN-8) is validated by the barcode submission API only.
6.  2/5-digit add-ons (EAN-2/EAN-5) aren’t taken into account.
7. Tests are sometimes missing some real data examples.
8. Barcode documentation isn’t up-to-date.
After checking …
=> MBS-13346 (amend): Improve GTIN barcode handling

root/cdtoc/CDTocInfo.js, root/components/list/EventList.js, root/edit/details/EditEvent.js, root/event/edit_form.tt, root/layout/components/sidebar/EventSidebar.js, root/main/error/components/ErrorEnvironment.js, root/report/components/EventList.js, root/search/components/EventResults.js
At least in Spanish, the time of an event would generally be translated in a significantly different way than the timecodes in a CDTOC.
=> Add context to "Time" strings

root/components/common-macros.tt, root/static/scripts/common/components/EntityLink.js
We had context for the "cancelled" string for edits, but not for events (the only uses left without context).
=> Add context to "cancelled" for events

lib/MusicBrainz/Server/Controller/Role/EditRelationships.pm, root/layout/components/sidebar/SidebarEndDate.js, root/static/scripts/common/utility/formatEndDate.js, root/static/scripts/relationship-editor/components/DialogPreview.js, root/static/scripts/relationship-editor/components/DialogSourceEntity.js
This is needed to use the right gender in translations. For date ones we can be specific. For the entity ones, all we can say is that it's for a generic entity for now (we could later decide to separate these into strings for every entity type based on context though).
=> Add context to [unknown] strings

lib/MusicBrainz/Server/Entity/Barcode.pm, root/static/scripts/common/utility/formatBarcode.js
We already have context for [none] strings for different entity types, but not when used to indicate no barcode.
=> Add context to [none] barcodes

lib/MusicBrainz/Server/Controller/Account.pm, root/main/error/Error401.js, root/user/Login.js
We generally use `support@metabrainz` now, but in any case most of our strings direct people to the contact us page instead. Doing the same with these four stragglers. I also somewhat simplified the strings while at it, and changed some text that seemed to suggest the `account/edit` page would show the entered email (it does not, until it is verified).
=> Drop contact email from strings

root/artist/edit_form.tt, root/edit/details/AddAnnotation.js, root/event/edit_form.tt, root/label/edit_form.tt, root/layout/components/sidebar/CollectionSidebar.js, root/layout/components/sidebar/ReleaseGroupSidebar.js, root/layout/components/sidebar/ReleaseSidebar.js, root/layout/components/sidebar/SidebarType.js, root/place/edit_form.tt, root/release/edit/information.tt, root/search/components/SearchForm.js, root/series/edit_form.tt, root/static/scripts/common/components/Autocomplete2/formatters.js, root/static/scripts/common/components/FilterForm.js, root/static/scripts/common/components/MediumDescription.js, root/work/edit_form.tt
We already have a lot of Type strings without colons and these do not mean different things in different places.
=> Remove colons from Type strings

lib/MusicBrainz/Server/Data/Artwork.pm, t/lib/t/MusicBrainz/Server/Data/Artwork.pm, t/sql/initial.sql
MBS-13465
If a release group does not have cover art explicitly set, then we select the first front image from the earlier release in the RG, including "Raw/Unedited" images.
Before sorting by date, sort by the presence of "Raw/Unedited" in the cover art types, preferring front covers that do not have this type.
Note: A similar PR is needed for the artwork-redirect API (though it doesn't matter which is deployed first).
Added an automated test.
=> MBS-13465: Prefer non-raw images when displaying front release group cover art

lib/MusicBrainz/Server/Edit/Relationship/RemoveLinkType.pm, lib/MusicBrainz/Server/Edit/Release/Create.pm, root/components/common-macros.tt, root/edit/details/EditAlias.js, root/edit/details/SetTrackLengths.js, root/static/scripts/common/components/EntityLink.js, root/static/scripts/common/i18n/localizeLanguageName.js, root/static/scripts/edit/components/Multiselect.js
This is needed to be able to use the right gender and number in translations. There's a few uses where we don't know what is going to be used for (different entities for example have different genders), so this at least specifies this is generic usage so translators can choose to use a generic string here if available.
=> Add context to [removed] strings

lib/MusicBrainz/Server/Report/BootlegsOnNonBootlegLabels.pm, lib/MusicBrainz/Server/ReportFactory.pm, root/report/BootlegsOnNonBootlegLabels.js, root/report/NonBootlegsOnBootlegLabels.js, root/report/ReportsIndex.js, root/server/components.mjs
Non-bootleg labels pretty much never put out bootlegs. As such, this report lets editors find bootleg releases which have a non bootleg label as a release label, which should almost always be wrong in some way.
[no label] can of course also apply to bootlegs, so it is ignored.
This is basically the opposite of https://github.com/metabrainz/musicbrainz-server/pull/2874
With sample data, which had 31 matches.
=> MBS-13463: Report for bootleg releases on non-bootleg label

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
junodownload links with spaces (`+`) were blocked as invalid because we didn't count on them using that rather than `-` for separating words on some names (label and artist, at least, such as https://www.junodownload.com/artists/Kurwastyle+Project/).
This just allows `+` as part of the id on the validation so that the otherwise already valid link is accepted.
Changed a test to use the artist with a space linked above.
=> MBS-13473: Don't block junodownload links with spaces (+)

flow-typed/npm/react-dom_v18.x.x.js, root/static/scripts/common/utility/focusManagement.js, root/static/scripts/edit/components/FormRowNameWithGuessCase.js, root/static/scripts/release/components/ReleaseRelationshipEditor.js, root/static/scripts/work/edit.js, root/utility/hydrate.js
The react-dom libdef was missing a declaration for `flushSync`, which required a `$FlowIgnore` on the import, and an additional ESLint ignore for the `$FlowIgnore`. 
I submitted a declaration upstream and synced the changes here.
Ran `./node_modules/.bin/flow`.
=> Update react-dom libdef with flushSync type

root/static/scripts/common/immutable-entities.js, root/static/scripts/edit/utility/getUpdatedTrackArtists.js, root/static/scripts/release-editor/init.js, root/static/scripts/tests/edit/utility/getUpdatedTrackArtists.js, root/static/scripts/tests/index-web.js
Move the release editor code that updates track credits when a release's credits are changed into a new standalone getUpdatedTrackArtists function, and add unit tests for it.
No functional changes are intended, but this should make it easier to make future improvements as discussed in MBS-13273.
I'm planning to work on MBS-13273 some more, but testing the many edge cases via Selenium is painful.
This change moves code for updating track credits out of the release editor's `init.js` file and into a separate Flow-checked utility file that can be unit-tested.
I added a unit test that exercises a bunch of different cases. The existing release editor Selenium tests will hopefully pass, too.
=> Move track-artist-updating code into testable function

lib/MusicBrainz/Server/Data/Artist.pm, lib/MusicBrainz/Server/Data/ReleaseLabel.pm, lib/MusicBrainz/Server/Data/Role/EntityCache.pm, lib/MusicBrainz/Server/Edit/Artist/Merge.pm, lib/MusicBrainz/Server/Edit/Release/AddReleaseLabel.pm, lib/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm, lib/MusicBrainz/Server/Entity/Release.pm, t/lib/t/MusicBrainz/Server/Data/Artist.pm, t/lib/t/MusicBrainz/Server/Data/ArtistCredit.pm, t/lib/t/MusicBrainz/Server/Data/Release.pm, t/lib/t/MusicBrainz/Server/Data/ReleaseLabel.pm, t/lib/t/MusicBrainz/Server/Data/Role/Collection.pm, t/lib/t/MusicBrainz/Server/Edit/Relationship/Create.pm, t/lib/t/MusicBrainz/Server/Edit/Relationship/Delete.pm, t/lib/t/MusicBrainz/Server/Edit/Relationship/Edit.pm
MBS-13481, plus another (pretty much harmless) issue with bogus keys being added to the cache.
See associated commits for further details.
Added some automated tests.
=> MBS-13481: Invalidate release on label changes

lib/MusicBrainz/Server/Entity/URL/Spotify.pm, root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Much like Bandcamp, Spotify also allows selling merch now, including both physical and digital music, under https://shop.spotify.com/ (that link by itself doesn't work though, example from the ticket is https://shop.spotify.com/en-US/artist/4O15NlyKLIASxsJ0PrXPfz/store).
Only allowing these for releases and recordings since those seem like the most obviously useful options, and allowing either mail order or download purchase but not both since each item seems to be one or the other anyway.
Added a test.
=> MBS-13424: Allow Spotify shop links

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
We were turning these into profile links, but actually there's a fair amount of "TikTok music" being created that originates in and is mostly streamed at TikTok itself.
As such, it makes sense to allow linking recordings to `/video` TikTok links (/music links, which are used for videos that use licensed music, do not seem to belong in MusicBrainz).
Added a test, plus checked manually that the links are blocked and allowed as expected.
=> MBS-13474: Allow TikTok videos on recordings

root/static/scripts/tests/edit/utility/getUpdatedTrackArtists.js
Test more edge cases, particularly when the track credits are visually identical to the release credits but reference different entities.
---
There are lots of weird edge cases not exercised by the existing test that I added in #3168. I'd like to add coverage for some of these before making any changes to `getUpdatedTrackArtists`.
=> Add more unit test cases for getUpdatedTrackArtists

lib/MusicBrainz/Server/Data/ArtistCredit.pm, lib/MusicBrainz/Server/Data/Event.pm, lib/MusicBrainz/Server/Data/Release.pm, lib/MusicBrainz/Server/Data/ReleaseGroup.pm, lib/MusicBrainz/Server/Data/ReleaseLabel.pm, lib/MusicBrainz/Server/Data/Role/EntityCache.pm, lib/MusicBrainz/Server/Data/Role/GIDRedirect.pm, lib/Sql.pm, t/lib/t/MusicBrainz/Server/Data/Release.pm, t/lib/t/MusicBrainz/Server/Data/ReleaseLabel.pm, t/lib/t/MusicBrainz/Server/Data/Role/GIDEntityCache.pm
After searching for issues similar to [MBS-13481](https://tickets.metabrainz.org/browse/MBS-13481) (where we load additional data onto an entity which is then entered into the cache, but where changes to that additional data do not invalidate the entity's cache entry), I believe that there are simply far too many uncovered cases which we'd have to handle.
While storing more data in the cache and having intelligent invalidation logic for all the linked data sounds desirable, it's too many changes to manage for now, so we need to restore the previous behavior.
This partially reverts https://github.com/metabrainz/musicbrainz-server/commit/82c79f531edad396c20a2fceb45a37de9035e055 and https://github.com/metabrainz/musicbrainz-server/commit/42be4bcf01f198530789772629093d1b69b853c5.
I realized …
=> Don't delay cache additions until after the transaction ends

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
RA also has localized links (see test for an example) which we were entirely ignoring. It seems that it is just a translation for the interface rather than a separate site, so it should be fine to just clean it up to the generic ra.co version.
Changed a label link on the automated tests to the Spanish version to make sure it still gets cleaned up properly.
=> MBS-13441: Also accept localized ra.co links

lib/MusicBrainz/Server/Report/ReleasesWithoutCAA.pm, root/constants.js, root/release/CoverArt.js
Our [guidelines](https://musicbrainz.org/doc/Style/Specific_types_of_releases/Pseudo-Releases) say pseudo-releases shouldn't generally get cover art (the only exception is if there's no official release and it helps figure out what the official release should be, after which they should be deleted from the pseudo-release). Despite that, we were still showing pseudo-releases in the "Releases without any art in the Cover Art Archive" report, suggesting cover art should be uploaded, and we had no way for users to know this was not the case without them going searching for a fairly obscure guideline.
This does two things: it makes it so pseudo-releases no longer show in the report, and it adds a line to their cover art tab when there's no cover art yet specifying that cover art should …
=> MBS-13486 / MBS-13487: Small CAA for pseudo-releases improvements

lib/MusicBrainz/Server/Edit/Medium/Delete.pm, lib/MusicBrainz/Server/Edit/Release/Delete.pm
For some reason, when we delete a medium or a release (including all its mediums) we are not actually displaying those edits in the history of the recordings that appear on the affected mediums. Admittedly, in many cases this will lead to the recording being subsequently removed anyway and there will be no history to see, but especially for orphaned recordings which had relationships and were kept behind this would be good info to have.
This just does the same when deleting a medium as we already do when adding and editing it, making the edits appear in the history of both the recordings in the medium and the artists in the track ACs.
For Remove release, this loads all the mediums in the release and does the same as the medium edit for each of the mediums, since it's effectively …
=> MBS-13328: Remove medium / release edits missing from recording edit history

lib/MusicBrainz/Server/Data/ReleaseGroup.pm
The RG diambiguation filter tries to access a non-existent `rg` table when filtering in fast mode (using `artist_release_group`).
Just set `$needs_rg_table` to `1`, as we do with other similar filters but seemingly I just forgot to do here.
Manually with r-o main db access with and without this (testing with a local sample db works either way since it uses the slow mode with the `release_group` table).
=> MBS-13495: Use RG table for RG disambiguation filter

root/static/styles/extra/wikidocs.less
Restrict MediaWiki content width to the viewport width to make it somewhat usable on mobile devices.
Documentation pages set `min-width: 780px;` on `<body>`, which results in content being unusable on mobile devices with narrow screens -- the text is either tiny when zoomed out or multiple screen-widths wide when zoomed in. See the screenshots at <https://community.metabrainz.org/t/making-documentation-pages-usable-on-mobile-devices/602956>.
Set `max-width: calc(100vw - 32px);` on the content so that it's limited to the viewport width even when the page itself is much wider (to accommodate the header).
Documentation pages look the same as before in wide windows, but the content is wrapped at the viewport width on mobile (in both Chrome dev tools and on a Pixel 7a).
=> Limit documentation content to viewport width

docker/musicbrainz-tests/run_circleci_tests.sh
Since PR #3091, CircleCI tests output contains:
```
fatal: detected dubious ownership in repository at '/home/musicbrainz/musicbrainz-server'
To add an exception for this directory, call:
git config --global --add safe.directory /home/musicbrainz/musicbrainz-server
```
This is because `git grep` is run as `root` whereas the [files are owned by `musicbrainz`](https://github.com/metabrainz/musicbrainz-server/blob/v-2024-02-16/.circleci/config.yml#L27).
Run as `musicbrainz` just like for all other test commands.
Tested through SSH in CircleCI by running this modified command against `root/statistics` and `root/event`.
New test images must be build to make use of this change.
However, this change alone is not worth building new test images.
=> Amend #3091: Prevent git warning for ownership

root/layout/components/sidebar/ReleaseSidebar.js, root/static/scripts/common/components/EntityLink.js
We hide disambiguations for labels on the release sidebar (I assume because of the lack of space) but this can be useful to quickly check if the right label is selected, so we should at least show it on hover.
This adds a `showDisambiguationOnHover` option to `EntityLink`, which will either show the disambiguation as the whole hover if there's nothing else there or append it in brackets if there is (for the current use case `hover` should be always empty AFAICT).
Manually, making sure the disambiguation shows if there's one, and no empty hover tooltip shows otherwise.
=> MBS-13476: Show release label disambiguations on hover

lib/MusicBrainz/Server/Controller/Collection.pm
Areas were not being loaded for events displayed in the collection view.
Just load the areas. We don't need to load types, performers and locations separately since they're already loaded as part of `load_related_info` so this drops those as well.
Manually, with the collection shown in the ticket.
=> MBS-13507: Load areas for events in collections

root/report/ReleasesWithoutCaa.js
@Aerozol pointed out that I forgot to explain that pseudo-releases won't appear on the CAA report as part of the description of the report, which seems useful to avoid confusing people, so this adds the info.
None
=> MBS-13486 (II): Explain the report change on the report text

lib/MusicBrainz/Server/Sitemap/Incremental.pm, lib/MusicBrainz/Server/Sitemap/Overall.pm
MBS-12239
If the incremental sitemaps have not run for some time, then many changes can accumulate which are too numerous to bundle into a single sitemap without exceeding `$MAX_SITEMAP_SIZE`.
I implemented batching code for the incremental sitemaps which is mostly copied from the overall sitemaps code.
I copied these changes into the production musicbrainz-sitemaps container and ran the hourly script. It appears to have resolved the errors.
=> MBS-12239: Fix "too many URLs" in incremental sitemaps

flow-typed/npm/po2json_v1.x.x.js, package.json, root/server/gettext/poFile.mjs, yarn.lock
"DeprecationWarning: Invalid 'main' field" has been fixed for years since https://github.com/mikeedwards/po2json/pull/97 but there was never a release.
This just installs the latest version from a git hash.
I reviewed the changelog and the diff since v0.4.1. There was one breaking change: `format: 'jed1.x'` is now `format: 'jed'`. Other than that, I didn't notice any issues compiling resources or browsing the website locally with translations enabled.
As po2json appears to be abandonware, perhaps we will have to fork it eventually, but it still works perfectly fine in the state it was left in, so I don't think there is a need yet.
=> Install po2json from git to silence warning

root/static/scripts/common/constants.js, root/static/scripts/relationship-editor/utility/splitRelationshipByAttributes.js, root/static/scripts/tests/relationship-editor.js, t/sql/initial.sql
Task attributes, like instruments and vocals, should lead to split relationships, rather than be kept on new split relationships. This is needed for STYLE-2445 to lead to results that make sense.
If we add a new "member of" relationship with attributes "task: dancer", "instrument: piano" and "vocals: lead vocals":
* Currently, we end up with two split relationships, "task: dancer and piano" and "task: dancer and lead vocals".
* We want to end up with three split relationships, "task: dancer", "piano" and "lead vocals".
Just add task to the list of things that we check for in `isInstrumentOrVocal` (which is changed to `isSplittableAttribute` because `isInstrumentOrTaskOrVocal` seemed too silly).
Added a test for this case to the existing `splitRelationshipByAttributes` tests.
Once this is …
=> MBS-13505: Split relationships on task attributes

root/admin/components/UserList.js
When looking at lists of users from an admin interface (for example, when looking at users who use email providers known to be mostly spam-infested), I have a lot of data on them, enough generally to let me know if they should be banned. What I don't have is any information about whether I have already banned them or not, which means I annoyingly often open a profile to find out it's already banned anyway.
This adds a column to `UserList` that shows the restrictions for the user (shortly and untranslated since it's just for admin use). 
`Untrusted` is admin-only knowledge, but only admins get to see `UserList` anyway (it already shows private emails, so showing `Untrusted` is comparatively tame).
Manually, with a live DB tunnel, to make sure users show their restrictions as expected …
=> MBS-13512: Show user restrictions in admin user views

lib/DBDefs.pm.sample, lib/DBDefs/Default.pm
TLS is legitimately enforced for OAuth2 from `musicbrainz.org`  since Jan 2013,
but it isn’t enforced from `beta.musicbrainz.org` which has been introduced in Feb 2013,
likely an oversight.
Enforce TLS not only from non-staging (production) server, but also from beta server.
Server logs have to be checked when deploying to `beta.musicbrainz.org`.
=> Enforce TLS for OAuth2 from beta.mb.o too

package.json, root/admin/attributes/Language.js, root/admin/attributes/Script.js, root/components/list/ReleaseGroupList.js, root/static/scripts/relationship-editor/components/DialogAttribute/MultiselectAttribute.js, root/static/scripts/statistics.js, root/static/scripts/tests/edit/utility/linkPhrase.js, root/types/languageandscript.js, yarn.lock
Mostly trivial updates, 0.224.0 and 0.226.0 required small changes (see commit messages).
Latest version 0.231.0 causes a lot of errors, so let's do these, then that in a separate PR.
=> Update Flow to version 0.230.0

root/static/scripts/edit/MB/Control/ArtistEdit.js
We had added context to these in one place but left them with a colon and no context in other. This reuses the new variants with context in `Control/ArtistEdit`.
=> Make duplicated artist begin/end labels consistent

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Bandsintown also has `/f` (festival) links that should be allowed for events.
Just allow `/f` as well as `/e` for events. I didn't find any examples of the style using the whole "festival" name, like the ones we have for other types of links, so not allowing those for now.
Added a test for an example of this.
=> MBS-13515: Support Bandsintown festival links

root/artist/utils.js, root/static/scripts/edit/MB/Control/ArtistEdit.js
There's no difference between these and the existing labels that don't have a colon.
=> Drop duplicate "Begin/End area:" colon strings

root/relationship/linkattributetype/RelationshipAttributeTypeIndex.js
This is not a relationship, it's an attribute, but [the doc page](https://musicbrainz.org/relationship-attribute/0abd7f04-5e28-425b-956f-94789d9bcbe2) confusingly says "The possible values for this relationship".
=> Fix instrument attribute doc wording

lib/MusicBrainz/Server/Controller/WS/js.pm, lib/MusicBrainz/Server/Controller/WS/js/Edit.pm, t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm, t/lib/t/MusicBrainz/Server/Controller/WS/js/CheckLogin.pm
Quoting @amCap1712 AKA lucifer from IRC:
"[W]e intend to add a /oauth2 route to MB.org (exact path of the route yet to be decided). [G]ateways will route requests on this path to a new MeB.org container and that will handle OAuth stuff. It will read the cookies set by MB and then use it to determine the current user to perform relevant actions."
"We need to do this because if we run the OAuth stuff under MeB.org, they will need to have a MeB.org account and login there to perform any OAuth2 related actions, which would still be fine for creation and modification of applications but having users do that to approve access to applications would be cumbersome."
To help resolve this, I'm exposing an endpoint, /ws/js/check-login, which can be called by the new MeB container internally with the …
=> Add /ws/js/check-login endpoint

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Operabase now redirects their artist URLs to the form `https://www.operabase.com/<name>-a<id>/<lang>`, which our validation rejects. Work and venue pages have not (yet?) changed their URLs.
The id (as `a<id>`) is all that is needed for the URL to work, so it is probably the best option to clean up to. As such this updates the cleanup to strip everything else from both old and new artist URL styles.
Added a `URLCleanup` test.
*  Existing URLs can, luckily, be cleaned up with relative ease - added MBBE-85 for that.
=> MBS-13524: Update Operabase handling for new artist URLs

lib/MusicBrainz/Server/Report/ReleasesSameBarcode.pm
The "Releases with same barcode in different RGs" report is missing positives for two reasons:
* It skips releases with status unset
* It doesn't see different zero-padding (EAN vs UPC) as the same
Use `lpad` to compare barcodes after zero-padding them, and fix the bootleg skipping code to not also skip null values. See commit messages for details.
Manually, by creating duplicate barcode releases and making sure they appear in the report:
* When one has no status set
* When one has extra zero padding
* When both are the same, but larger than 14 chars (made up barcode `12345615095201225`)
=> MBS-13522 / MBS-13523: ReleasesSameBarcode report improvements

README.md, root/static/scripts/common/utility/createFastObjectCloneFunction.js, webpack/server.config.mjs
The required version of Node.js has been bumped to 20 since MBS-13261 last November as announced in our [blog post](https://blog.metabrainz.org/2023/09/04/musicbrainz-website-mirror-will-require-node-js-20-starting-from-november-13-2023/), but the previously required version 16 has been forgotten in a couple of files.
These oversights are likely due to the fact that the version 18 has been used but not required in the meantime.
The recent upgrade of imports-loader version to 5.0.0 requires Node.js v20 as experienced in [MBVM-95](https://tickets.metabrainz.org/browse/MBVM-95).
Complete the previous pull request #3065 as follows:
* Bump the required version of Node.js to 20 in the main `README.md` (it had been changed in the file `INSTALL.md` only).
* Bump the target version of Node.js to …
=> Amend pull request #3065: Upgrade Node.js to v20

root/static/scripts/common/components/Autocomplete2.js, root/static/scripts/common/constants.js, root/static/scripts/common/utility/isGuid.js, root/static/scripts/tests/utility/isGuid.js
Update MBID_REGEXP and isGuid() to additionally match UUIDs containing uppercase letters (as recommended by RFC 4122). Previously, Autocomplete 2 would fail to extract MBIDs containing uppercase letters within pasted URLs.
As discussed in https://community.metabrainz.org/t/boom-boom-not-recognized-as-a-work-when-pasting-in-add-relationship-dialog-on-add-standalone-recording/690757, the relationship editor doesn't recognize MBIDs with capital A-F within pasted URLs.
(This seems like a minor issue since the MBS always lowercases MBIDs, as far as I can tell, but URLs like https://musicbrainz.org/artist/65F4F0C5-EF9E-490C-AEE3-909E7AE6B2AB work and don't get redirected or rewritten automatically.)
Per https://datatracker.ietf.org/doc/html/rfc4122#section-3, uppercase letters should be …
=> MBS-13541: Accept uppercase MBIDs in JavaScript

root/static/scripts/edit/utility/getUpdatedTrackArtists.js, root/static/scripts/tests/edit/utility/getUpdatedTrackArtists.js
Rework getUpdatedTrackArtists() to make the release editor update track credits in a few additional cases where featured artists are present.
There are a few cases where tracks with featured artists inconsistently still don't automatically get updated:
* The release was credited to multiple artists and the credited-as text for one of them is changed.
* The track credit is rendered identically to the old release credit but uses different underlying entities (possibly even a different number of entities).
`getUpdatedTrackArtists()` tries harder to find a prefix of the track credits that match the old release credits. Failing that, it checks if the track credits use the same entities as the new release credits (to handle credited-as and join phrase changes).
The existing unit tests for …
=> MBS-13540: Update track credits in a few more cases

lib/MusicBrainz/Server/Controller/User.pm, t/lib/t/MusicBrainz/Server/Controller/User/Login.pm
Currently if the user is already logged in, url redirects from the login page using the returnto query parameter don't work. This breaks certain workflows in the new OAuth testing.
MBS-13548
Fixing it by obeying returnto for logged in users as well. If returnto is missing, fallback to existing redirect to user's profile.
Add a perl test to make sure the added redirect behavior works and also did testing for the same on local server.
=> MBS-13548: obey returnto for already logged in users

lib/MusicBrainz/Server/Controller/Artist.pm, lib/MusicBrainz/Server/Controller/Search.pm, lib/MusicBrainz/Server/Controller/Series.pm, lib/MusicBrainz/Server/Data/Artist.pm, lib/MusicBrainz/Server/Data/Search.pm, lib/MusicBrainz/Server/Data/Utils.pm, lib/MusicBrainz/Server/Entity/Artist.pm, lib/MusicBrainz/Server/WebService/JSONSerializer.pm, root/static/scripts/common/components/EntityLink.js, t/selenium.mjs, t/selenium/MBS-7646.json5, t/sql/selenium.sql
Try to find artists' primary aliases in the user's locale and display them alongside disambiguation comments in search results and artist pages.
Editors argue about whether Latin-script versions of artist names should be included in disambiguations (see e.g. https://musicbrainz.org/edit/109219215). Even when this is done, it's not a great approach since it doesn't help editors who are using UI languages based on other scripts. Without being able to see localized names in search results, editors either look at sort names (if they know about them) or end up creating duplicate entities.
Localized versions of artist names are already stored as aliases, so automatically display those in italicized text at the beginning of the disambiguation comment when possible, e.g.
> Пётр Ильич Чайковский …
=> MBS-7646: Show localized artist aliases in more places

lib/MusicBrainz/Server/Data/Artwork.pm
Release group pages should prioritize non-bootleg album art
[MBS-13533](https://tickets.metabrainz.org/browse/MBS-13533)
Since we need to prioritize non-bootleg album art, we can order the Artwork we get from `load_for_release_groups` method, wrt `release_status`, the order being:
Since the query in the method has a `DISTINCT ON (release.release_group)` expression, we will get the top result from the order by `release.status` clause, hence official artwork will get more priority. 
Tested manually on multiple release groups. Got no errors on different RGs.
=> MBS-13533: Fix order of cover art in release group artwork

lib/MusicBrainz/Server/Data/Search.pm, lib/MusicBrainz/Server/Entity/Artist.pm
MBS-13560
`Entity::Artist` is missing a couple Moose attributes that were added to the beta code.  Entities that are cached on production but loaded on beta will be missing these, and cause beta to crash.
The relevant changes have been synced from https://github.com/metabrainz/musicbrainz-server/commit/d981ba8c4517c88bb749119f12950cbac565dfe5.
Just the existing automated tests.
=> MBS-13560: Sync `Entity::Artist` with beta

lib/MusicBrainz/Server/Controller/Collection.pm
Make Controller::Collection pass an array ref rather than an array when calling Data::Artist's implementation of load_related_info.
Also pass the UI language so that localized primary aliases can be loaded for artists.
`Controller::Collection` was using the same call signature for all entity types when calling `load_related_info`. d981ba8c4517c88bb749119f12950cbac565dfe5 made `Data::Artist`'s implementation take an array ref rather than an array, which caused a crash:
```
Not an ARRAY reference at lib/MusicBrainz/Server/Data/Artist.pm line 472. at lib/MusicBrainz/Server/Data/Artist.pm line 472
MusicBrainz::Server::Data::Artist::load_related_info(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, …
```
=> MBS-13570: Avoid crash in artist collection load_related_info

root/static/scripts/common/components/Autocomplete2/formatters.js
Make the Autocomplete2 component italicize primary aliases and sort names to match d981ba8c4517's display of aliases in EntityLink for MBS-7646. Also add "Primary alias" and "Sort name" title text that gets shown on hover.
It's hard to tell what's part of the disambiguation comment and what came from the primary alias or sort name in the rows displayed by the `Autocomplete2` component; it's all formatted as regular text.
Wrap the primary alias and sort name in `<i>` elements, similar to how #3191 made `EntityLink` display primary aliases. Also add `Primary alias` and `Sort name` title text.
Went to the add release page and checked that primary aliases and sort names are italicized when I search for artists with non-Latin entity names.
=> MBS-13563: Italicize aliases and sort names in Autocomplete2

docker/templates/Dockerfile.tests.m4
mb-solr is being upgraded to Solr 9.4.0 and Java 17, hence update the tests dockerfile to use the same versions. Using the same JDK variant we use in mb-solr (eclipse temurin jdk17).
=> Update Java and Solr versions in Dockerfile.tests

admin/InitDb.pl, admin/UpdateDatabasePrivileges.pl, docker/musicbrainz-tests/run_circleci_tests.sh, lib/MusicBrainz/Server/Constants.pm, t/script/UpdateDatabasePrivileges.t, upgrade.sh
MBS-11962
When new tables or schemas are added, production database users like `musicbrainz_ro` may not be granted access to them.
Adds a new script, admin/UpdateDatabasePrivileges.pl, which is invoked from upgrade.sh and updates privileges for the following users if they exist:
* `musicbrainz_ro`
* `caa_redirect`
* `sir`
The script works by revoking all write privileges from `musicbrainz_ro`, and then granting `USAGE` on all schemas, and `SELECT` privileges on all tables in those schemas.
Next, for the last two schemas, it revokes all privileges from them (including `SELECT` and `USAGE`), and then simply grants them membership in the `musicbrainz_ro` role.
I added the three roles in question to my local database and ran admin/UpdateDatabasePrivileges.pl. I observed that each of the three …
=> MBS-11962: Update privileges for all database users on schema changes

package.json, yarn.lock
For some reason, installing node modules using Node.js 20.13.0 that brings Yarn 4.0.1 would fail with the following error message:
xgettext-js@https://github.com/metabrainz/xgettext-js.git#commit=0301681a479c1796ff6850c9bd2a169074386d92: The remote archive doesn't match the expected checksum
It is unclear which version(s) and on which platform(s) would fail here. (It fails in macOS and Docker Composed Ubuntu Jammy, but it works in ArchLinux and CircleCI Dockerized Ubuntu Jammy.) When failing, the following key was added to xgettext-js’ package.json:
"packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e"
It seems that it was the only difference in the installed files, thus …
=> Fix installing our xgettext-js fork using Yarn v4

root/user/UserProfile.js
There's no great reason to have two strings, 'view list' and 'see list'. This was probably separate because we only show the count on viewingOwnProfile but there's no reason we can't just do like I do here instead. Suggested by @kellnerd.
=> Reuse same 'view list' string everywhere

root/static/scripts/edit/components/ArtistCreditNameEditor.js
This got added after I added context to [removed] recently, it seems.
=> Add context to newly added [removed]

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
For LiveNation, I did not find links with `_` nor `-` when implementing this originally, but clearly they exist, as the example in the ticket (now added to the test) shows. We were breaking these with the cleanup. 
For Ticketmaster, there seems to be a second, less common type of links that can use all uppercase and lowercase letters in the IDs, which again I had not found when implementing this and was being rejected by the cleanup.
Just accept `_` and `-` on LiveNation identifiers, and allow all of `\w` on Ticketmaster ones.
Added the previously breaking example links to the automated tests.
=> MBS-13572 / MBS-13573: Don't break on more LiveNation and Ticketmaster links

INSTALL.md, docker/templates/macros.m4, lib/DBDefs.pm.sample, lib/DBDefs/Default.pm
_When switching to a language on test server to the one that's not officially supported yet it stayed with English._
This was due to some missing language packs for the test instance.
Actually, the installed language packs were matching translations in beta, even for the main instance.
* Install extra languages packs only if `GIT_BRANCH` matches either `beta` or `test`.
* It installs all the missing language packs for test.mb.o.
* It installs only the needed language packs for the main mb.o.
* Add a NOTE anchor for reference from our deployment repository about keeping it in sync.
Installed additional language packs in the `test` branch, and it resolved the issue at https://test.musicbrainz.org.
Tested the macros locally by changing either `beta` or `test` to `fix-language-packs` and …
=> MBS-13584: Fix installing language packs in deployment

admin/cron/hourly-sitemaps.sh, docker/templates/macros.m4
* The hourly cron jobs for the JSON dumps and sitemaps are currently failing with:
> ./script/create_test_db.sh: No such file or directory
* The sitemaps container connects to our main PostgreSQL cluster, which doesn't have access to a `musicbrainz_test` database configured in pg_hba.conf.
* For the first problem, add this script to the Dockerfile. That's not the only script missing, though: we also need script/dump_foreign_keys.pl, plus script/database_exists and t/sql/initial.sql. (The latter two are required by create_test_db.sh.)
* For the second, use the `READONLY` database instead.
I haven't tested building or deploying the image.
=> Add missing scripts required by JSON dumps/sitemaps

root/static/scripts/common/components/EntityLink.js, root/static/styles/layout.less
This fixes [MBS-13263](https://tickets.metabrainz.org/browse/MBS-13263) - that releases without cover art were misaligned in release group listings. 
This adds a blank space the size of the icon before releases without cover art, to align them properly. To do that, it also adds a `blank-icon` class. It also moves data quality indicators to the right
I visually inspected the changes at `/release-group/6c08878c-d6a1-37b6-84c3-9566748545c1`, `/release-group/16a9cef3-b470-3ae1-bf10-cc04232d3e21` and `/artist/c0a1179b-b14a-4d68-a3c1-1fdab16ed602/releases` using the sample database. 
These changes should not impact the documentation.
=> MBS-13263: Align release titles despite indicators for cover art and data quality

lib/MusicBrainz/Server/Report/ArtistsThatMayBeGroups.pm, root/report/ArtistsThatMayBeGroups.js
The ["Renamed into" relationship](https://musicbrainz.org/relationship/9752bfdf-13ca-441a-a8bc-18928c600c73) is meant to generally be used for groups, but it gets used to link performance names instead of the correct "performs as" relatively often. There's no good way to find the misuses at the moment.
This adds the non-group uses of "renamed into" to the `ArtistsThatMayBeGroups` report, so that they can be found and fixed as needed. It can cause false positives for cases where a character was renamed, but that should be very rare and it seems like an acceptable level of false positives. I expanded the text for the report a bit (since it only mentioned members but it hasn't been for members only for quite a while now).
Tested with sample data, where the report goes from 27 to 29 artists …
=> MBS-13581: Check "renamed into" in ArtistsThatMayBeGroups

lib/MusicBrainz/Server/Report/VideoRelationshipsOnNonVideos.pm, lib/MusicBrainz/Server/ReportFactory.pm, root/report/ReportsIndex.js, root/report/VideoRelationshipsOnNonVideos.js, root/server/components.mjs
People often misuse video related relationships in non-video recordings - possibly more common still is the case where the recording is indeed a video but has not been marked as one. There's currently no great way to find either.
This adds a report that shows any recordings that have relationships specifically meant for videos. This allows users to find and fix both cases mentioned above.
Tested with sample data, which contains a bunch of directed by credits.
=> MBS-13585: Report for non-video recordings with video relationships

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
We currently block (don't handle) `/o` links for Operabase. These are organization pages, which are used for things such as orchestras and opera companies (still artists in MB terms).
Allow `o` prefix for artists as well as the already handled `a` prefix. Split the old-style artist links to a separate regex cleanup to make things clearer.
Added a test case to the cleanup tests.
=> MBS-13589: Handle Operabase /o links

lib/MusicBrainz/Server/Data/Release.pm, lib/MusicBrainz/Server/Form/Filter/Release.pm, t/lib/t/MusicBrainz/Server/Controller/Artist/Filtering.pm, t/sql/filtering.sql
While we allow filtering release groups or works without a type, there's no way right now to filter for releases without a status or country.
This adds the option to search for releases with no status, country or label when filtering an artist's release page, in the same way we already allowed searching for empty values for some work and release group filter options. Label wasn't actually requested, but it makes sense anyway.
Added test cases for all of these to our `Filtering` test.
=> MBS-13577 / MBS-13578: Release filtering for missing data

docker/musicbrainz-tests/DBDefs.pm, lib/DBDefs.pm.sample, lib/DBDefs/Default.pm, lib/MusicBrainz/Server/Data/Search.pm, lib/MusicBrainz/Server/Data/WebService.pm, script/purge_solr_cores.sh
When the traffic between the MusicBrainz web server and its search server is traveling over external interfaces, it can be intercepted by anyone, as MusicBrainz Server is currently querying its search server using the unencrypted HTTP scheme (even though it doesn’t contain any credentials and it has limited access).
Allow using another scheme than HTTP to query the search server through `SEARCH_SCHEME` definition. More specifically, allow for using HTTPS when the search server isn’t deployed in the same infrastructure.
Just tested that it still works in local development setup. No change is expected unless `SEARCH_SCHEME` is specifically set in your `lib/DBDefs.pm`.
The plan is to set `SEARCH_SCHEME` to `https` for querying the new SolrCloud 9 instance.
=> MBS-13599: Support any search server scheme

t/lib/t/MusicBrainz/Server/Controller/User/Login.pm
da9a19b4f01f89ab6137cee16d79ebe29180bcb4 added a test to ensure that `/login?returnto=` is obeyed if the user is already logged in. The `returnto` page used in the test is a `/doc/` page, which actually depends on the production Wiki server and may fail if it's under maintenance.
This commit just changes the page to one that doesn't require any production service to be available.
Ran the modified test locally.
=> Replace /doc page query in Perl test

contrib/ssssss.psgi, lib/MusicBrainz/Server/Controller/WS/js.pm
We've currently hardcoded the email address `caa@musicbrainz.org` for verifying the owner of items.
Now we check `eventartarchive@metabrainz.org` instead for events.
I changed the uploader used by ssssss.psgi and only check that one in development.
This is a prerequisite of IMG-84.
Only the existing Selenium tests which make use of ssssss.psgi.
=> Add support for checking the owner of EAA items

.circleci/config.yml, contrib/ssssss.psgi, docker/musicbrainz-tests/DBDefs.pm, docker/musicbrainz-tests/artwork-indexer-config.ini, docker/ssssss/DBDefs.pm, docker/templates/Dockerfile.tests.m4, lib/DBDefs.pm.sample, lib/DBDefs/Default.pm, lib/MusicBrainz/Server/Controller/Role/Art.pm, lib/MusicBrainz/Server/Controller/WS/js.pm, lib/MusicBrainz/Server/Data/CoverArtArchive.pm, lib/MusicBrainz/Server/Data/EventArtArchive.pm, lib/MusicBrainz/Server/Data/Role/ArtArchive.pm, t/selenium/CAA.json5, t/selenium/EAA.json5
This follows https://github.com/metabrainz/artwork-indexer/pull/2 which is a prerequisite of IMG-84.
The CAA and EAA actually use different IA credentials to manage their collections.
This splits the current configuration options into per-project ones.
Just the existing CAA/EAA tests.
=> Support separate CAA and EAA access keys

admin/InitDb.pl, admin/SetLanguageFrequencies, admin/cleanup/FixTrackLength.pl, lib/DBDefs.pm.sample, lib/DBDefs/Default.pm, lib/MusicBrainz/Script/RemoveEmpty.pm, lib/MusicBrainz/Script/RemoveUnreferencedRows.pm, lib/MusicBrainz/Server.pm, lib/MusicBrainz/Server/Connector.pm, lib/MusicBrainz/Server/Context.pm, lib/MusicBrainz/Server/Data/Role/PendingEdits.pm, lib/MusicBrainz/Server/Data/Role/QueryToList.pm, lib/MusicBrainz/Server/Data/Role/SelectAll.pm, lib/MusicBrainz/Server/Data/Role/Sql.pm, lib/MusicBrainz/Server/Data/Statistics.pm, lib/MusicBrainz/Server/Database.pm, lib/MusicBrainz/Server/DatabaseConnectionFactory.pm, lib/MusicBrainz/Server/EditQueue.pm, lib/Sql.pm, script/database_exists
We don't have any consistent way to make use of our standby for read-only queries; initially this was intended for background tasks (MBS-13337), but it could be used for all types of read-only server queries.
This adds an `ro_connector` to the server context which is intended to be used to distribute read-only queries to our standby in production.
It requires a `READONLY` database configured. In production, `READONLY` will likely point to the `pgbouncer-any` (haproxy) service, which connects to either the primary or standby. `SET TRANSACTION READ ONLY` is always set on the `ro_connector` (which is desirable in case it connects to the primary).
It must be enabled via `USE_RO_DATABASE_CONNECTOR`; more information can be found in lib/DBDefs/Default.pm.
The `prefer_ro_*` methods were added to …
=> MBS-13337: Use standby Postgres instances for read-only queries

lib/MusicBrainz/Server/Controller/Search.pm, lib/MusicBrainz/Server/Data/Search.pm, root/components/list/EventList.js, root/components/list/ReleaseGroupList.js, root/components/list/ReleaseList.js, root/release_group/ReleaseGroupIndex.js, root/search/components/EventResults.js, root/search/components/ReleaseGroupResults.js, root/search/components/ReleaseResults.js, root/static/scripts/common/components/EntityLink.js, root/static/styles/layout.less, root/utility/tableColumns.js
This mirrors what we already do for releases and release groups, showing whether a particular event has event art in both event lists and event search results by displaying a small image icon by its name.
I made the variables and classes generic wherever it simplifies the code, since there's no reason to prefer CAA/EAA over artwork in cases like these.
Tested locally with live data, with `/artist/b0109715-ff87-4546-b1e2-08a78c60329a/events`, `search?query=Fueu%21%09&type=event&limit=25&method=indexed` and `search?query=Fueu%21%09&type=event&limit=25&method=direct`
=> MBS-13600: Display event art indicator for events

root/static/scripts/common/components/Autocomplete2/recentItems.js, root/static/scripts/edit/components/ArtistCreditEditor.js, t/selenium.mjs, t/selenium/MBS-13604.json5, t/selenium/Series_Relationship_Editor.json5
MBS-13598: Beta: recent items menu doesn't show sometimes
MBS-13604: Show recent track artists after clearing release AC
See commits for details.
I tested the changes manually on my local development server, and added a Selenium test for MBS-13604. I tried adding one for MBS-13598 too, but couldn't reproduce the issue in the Selenium test environment, so got frustrated and gave up.
=> MBS-13598, MBS-13604: Recent items menu fixes

root/edit/details/BetaOnlyEdit.js
The link to beta in `BetaOnlyEdit` includes any search parameters present on the page that shows it. Since this is intended a s a direct link to the edit in question, there would seem to be no benefit in including any search parameters in it. This is especially silly when getting to the edit from edit searches, since the link will currently contain the whole edit search query parameter group.
Actively blank the search portion of the edit URL while creating it.
Manually, with `/search/edits?auto_edit_filter=&order=desc&negation=0&combinator=and&conditions.0.field=id&conditions.0.operator=%3D&conditions.0.args.0=112144836&conditions.0.args.1=&unset_beta=1`
=> MBS-13606: Drop search parameters in BetaOnlyEdit

lib/MusicBrainz/Server/Data/Search.pm
In commit https://github.com/metabrainz/musicbrainz-server/commit/d981ba8c4517c88bb749119f12950cbac565dfe5 from the pull request https://github.com/metabrainz/musicbrainz-server/pull/3191 for MBS-7646 released in `v-2024-05-13-schema-change`, one of the two calls to the new subroutine `find_best_primary_alias` wasn’t checking if the second parameter was defined, causing the warnings below to be triggered (tens of thousands of times a day) in website logs:
Use of uninitialized value $lang in substr at lib/MusicBrainz/Server/Data/Utils.pm line 779.
Use of uninitialized value $lang in string eq at lib/MusicBrainz/Server/Data/Utils.pm line 785.
This patch fixes that to follow the other call. The behavior is to skip searching for any aliases when the user interface language is undefined.
Just …
=> Fix warnings logged from artist search for autocompletion

root/components/ArtFields.js, root/event/EventArtFields.js, root/event/add_event_art.tt, root/release/CoverArtFields.js, root/release/add_cover_art.tt
Currently, only the error-related `chooseMessage` suggests that more than one type of artwork can be selected for the same file. It would seem checkboxes would make it obvious but it's not - many people still don't select, say, "spine" for files that show both the spine and another part of the art.
The hope is that these changes, agreed with Aerozol, will make it more obvious that it's fine to select several types by changing "Type" to "Type**s**" and adding it explicitly to the doc line under the type selection.
Checked manually that the new strings show fine.
=> MBS-13612: Clarify you can add several art types to a file

root/release_group/set_cover_art.tt
MBS-13618
This was broken by 3fb6b951e65071a8b87a4d4520d6a655c6f2bad9; though given that it previously used `image.types`, I don't think they were translated previously either, which they are now.
Loaded the page in the ticket on my local dev server (via hendrix).
=> MBS-13618: Beta: Fix types display on release group "set cover art" page

RELEASING.md, root/account/Register.js, root/layout.tt, root/layout/components/Footer.js
We've moved to use Matrix as our main chat platform, so this changes references to IRC to point to our new generic page.
=> Update IRC references to (live) chat

lib/MusicBrainz/Server/Edit/Role/RemoveArt.pm
MBS-13629
The code was trying to access `entity_model` on `$self`, which is the edit class, where it should be trying to access it on `$art_archive_model`.
This only affected edits where the release (or event, in the case of "Remove event art" edits) was removed.
Tested loading http://localhost:5000/edit/112358221 via hendrix.
=> MBS-13629: Beta: ISE loading "Remove cover art" edit for removed release

root/elections/ElectionVoting.js
Nobody can vote on a closed election. As such, it makes sense to check for a closed election first, and always display "Voting is closed" when that's the case regardless of whether something else (like being a seconder) would also block voting for that editor.
Checked manually that a more sensible reason is now shown for why I cannot participate in `/election/307`. This works for me - for other testers, you'll need to check elections where you are involved directly - or, as a non-autoeditor, see if "Voting is closed" is shown since I think earlier all you got was "You cannot vote for this candidate, because you are not an auto-editor"
=> MBS-13630: Prioritize "Voting is closed" as no vote rights reason in AE elections

po/extract_pot_db
The EAA types are currently missing from the translation source strings.
This extracts the name and description of event art types from the database for translation, similar to the cover art types in the line above.
Tested `./po/update_pot.sh` locally.
=> Add `event_art_archive.art_type` to extract_pot_db

lib/MusicBrainz/Server/Data/Role/ArtType.pm
Cannot remove a cover art or event art type, because of an ISE in the `in_use` check because of a badly built query.
This was failing because `$type_table` already contains the schema so the query ended up with a broken duplicate schema. So I just removed the unneeded `$schema` variable.
Manually, to make sure the query resolves now and the deletion page loads.
=> MBS-13638: Remove duplicate schema on in_use query

lib/MusicBrainz/Server/Controller/Statistics.pm, lib/MusicBrainz/Server/Data/Statistics.pm, root/statistics/Images.js, root/statistics/Index.js, root/statistics/stats.js
This copies some of the CAA statistics for events:
* events with "front" for the main stats
* art pieces per event (max 15, I expect less per entity than CAA)
* art pieces by event type
* art pieces by event art type
Not adding the per-event-art-type stats to the `stats.js` file since it seems we already don't do that for cover art type stats; if we want to change that we can do both at once with another commit.
Some basic manual testing that the pages load and the stats generate, but only based on 0 pieces of event art since I have no event art locally to test with.
=> MBS-13640: Add more event art stats

root/static/scripts/common/constants.js, root/static/scripts/relationship-editor/utility/compareRelationships.js, root/static/scripts/tests/relationship-editor/utility/compareRelationships.js
Relationships with different times should be by definition different, so we do not want them to be considered as duplicates of each other.
This is especially important in concerts where the same artist plays at least twice.
This uses code similar to the one we use to check for series numbering and split rels based on it. Since I cannot think of any case where we would *not* want to accept multiple rels with different times, I apply this to all relationships, same as with dates.
Added a few test cases to the `compareRelationships` test, plus did some basic manual testing.
=> MBS-13174: Split relationships on different time

root/static/scripts/edit/utility/getUpdatedTrackArtists.js, root/static/scripts/tests/edit/utility/getUpdatedTrackArtists.js
The changes to the artist credit copying mechanism that keeps ACs in sync between releases and tracks mean the system is always keeping the original join phrase at the end of the replaced AC section. This makes sense in most cases, but not when the whole AC is being replaced, in which case keeping any potential trailing phrases from the replacement AC makes a lot more sense.
This checks whether the whole AC is being replaced, and in that case it skips the step setting the old join phrase back.
Added a couple tests to `getUpdatedTrackArtists`.
=> MBS-13631: Keep trailing join phrase on release -> track AC change

lib/MusicBrainz/Server/Controller/Edit.pm, lib/MusicBrainz/Server/Controller/Statistics.pm, lib/MusicBrainz/Server/Edit.pm, lib/MusicBrainz/Server/Edit/Event/AddEventArt.pm, lib/MusicBrainz/Server/Edit/Event/EditEventArt.pm, lib/MusicBrainz/Server/Edit/Event/RemoveEventArt.pm, lib/MusicBrainz/Server/Edit/Event/ReorderEventArt.pm, lib/MusicBrainz/Server/Edit/Release/AddCoverArt.pm, lib/MusicBrainz/Server/Edit/Release/EditCoverArt.pm, lib/MusicBrainz/Server/Edit/Release/RemoveCoverArt.pm, lib/MusicBrainz/Server/Edit/Release/ReorderCoverArt.pm, lib/MusicBrainz/Server/Edit/ReleaseGroup/SetCoverArt.pm, root/doc/EditTypeList.js, root/edit/CancelEdit.js, root/edit/EditData.js, root/edit/components/EditHeader.js, root/edit/components/EditNoteListEntry.js, root/statistics/Edits.js, root/types/edit.js
The translated names for edit types are not showing, even though the types are certainly translated in Spanish, French and Italian at least.
We were not actually using the contexts we added when showing translations, so these were mostly just not working at all.
Since contexts vary per edit type, this sets a default context of `'edit type'` and allows overriding it for the few edits that change it (adding `'singular'` or `'plural'`).
In `statistics/Edits` I chose to pass `l_edit_name` rather than passing the context and translating on the JS side because the whole thing is a construct for display so we might as well simplify it. This is the same that is already done for `EditTypeList`.
Manually, by visiting `/edit/open`, `/statistics/edits`, `/doc/Edit_Types` and `/edit/notes-received`
=> MBS-13645: Fix translations of edit type names

lib/MusicBrainz/Server/Controller/EditNote.pm, root/edit/components/EditNote.js, root/entity/NotFound.js, t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
We are always using the index to create an anchor link when linking to a permalink for a specific edit note from the note's timestamp, but in many cases (such as when we are editing a note or loading just the one note for the edit in `notes-received`) we don't even know what the right index would be and were always passing `0`. This meant that the note linked was always the first for the edit in those cases, which often was not the right one.
This creates a new `edit-note/id` endpoint that just redirects us to the right edit note anchor in the appropriate edit, and which we use instead of the anchor itself everywhere except when we are already on the edit page.
Manually from an edit listing and from `notes-received`, making sure the link is correct and redirects to the appropriate edit …
=> MBS-13626: Always link to correct edit note from timestamp 

root/cdtoc/lookup.tt
The "Possible mediums" table when attaching a discID matching a CD stub has wrong (outdated?) headers. It has country and date headers separately, despite the table combining them in a single data column, meaning everything to the right of these is off by one. Additionally, an optional final Tagger header was missing, despite `release_info()` supporting it (see the image on the ticket for an example).
With ro connector, see `/cdtoc/attach?toc=1%2010%20134955%20182%2014600%2026792%2042652%2058232%2074430%2083807%2097782%20108047%20118067`
=> MBS-13623: Fix headers for CD stub possible mediums

root/user/UserProfile.js
I missed testing this last time since I tested while logged out, so I didn't notice there's an extra edit search link when logged in that was broken. Now tested properly.
=> Beta: Fix event art user stats search

lib/MusicBrainz/Server/Data/Statistics.pm, root/statistics/Index.js, root/statistics/stats.js
Yet another set of stats I missed entirely while writing a feature - wish there was a way to be reminded that some stats might be missing :sweat_smile: 
Tested locally by adding a genre collection to the sample then running the stats.
=> MBS-13582: Add statistics for genre collections

po/statistics.pot, root/static/scripts/common/i18n/expand2react.js, root/static/scripts/common/i18n/expand2text.js, root/vars.js, script/xgettext.js, webpack/providePluginConfig.mjs
At some point we missed `lp_statistics` in gettext / webpack, so our `.pot` files were missing all strings using `lp_statistics`.
=> Fix missing lp_statistics translations

admin/run
Previously, the ran command was just printed on the standard output and not in the log file, which is fine for cron scripts but was quite embarrassing when occasionally running a specific command.
Log the command (with arguments) to run in the same file as its output.
Manually tested in the current cron container.
=> Make admin/run log the (full) command it ran

admin/UpdateDatabasePrivileges.pl, lib/MusicBrainz/Server/Report.pm, upgrade.sh
While testing MBS-13639 I wanted to a way to control exactly what changes UpdateDatabasePrivileges.pl makes: what schemas it applies it (in this case just `report`), and whether or not it grants privileges, revokes privileges, or both.
I also thought the logging was not clear enough about what it was actually doing. So now it just logs exactly what queries are being run.
=> More UpdateDatabasePrivileges.pl improvements

lib/MusicBrainz/Server/Controller/Rating.pm
An existing rating can be removed from the sidebar. But a rating added in the same page load cannot, unless the page is reloaded.
The jQuery used to update ratings was expecting rating to be sent as a number by the API, but for some reason we were sending it as a string. This caused the comparison in the jQuery to fail, meaning the rating could no longer be removed without a refresh. This just makes sure the API returns a number as expected.
Manually, by adding and removing the same rating multiple times.
=> MBS-13667: Return rating as number in JSON rating API

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
The first commit cleans up (new?) country subdomains for RYM, which seem to make no real changes and be safe to just remove.
The second commit drops query parameters (such as the ones left by Cloudflare protection) and anchors (such as the ones to select specific sections of a work page) from RYM URLs. I checked for any current uses in the DB, I found none for anchors, and 18 for query parameters - all of them either Cloudflare-related or incorrectly linked backend pages, such as https://rateyourmusic.com/artist/profile_details?id=848742 - I fixed those by hand.
Amended RYM handling tests to cover the relevant changes.
=> MBS-13679: RYM cleanup improvements

RELEASING.md, po/list_translators, script/list_code_contributors, script/tag.sh
Since the last schema change 2024 Q2 that features MBVM-42, the releasing instructions were outdated.
It requires changing our workflow a bit and also the way we used to set Git tags.
Also, some clarifications about handling translations from Weblate have been asked in the meantime.
Update the releasing documentation about:
* Preparing tickets and version in Jira earlier
* Prebuilding Docker image for mirrors
* Handling translations
Change the Git tagging script to:
* Link to the MBS version in Jira (instead of the blog post directly)
* Follow the same tag format as other MetaBrainz projects do (as a bonus)
Additionally:
* Clarify steps to draft and publish the blog post
* Add scripts to list code contributors and translators
* Add Jira queries to list ticket reporters
See commit messages …
=> Releasing with prebuilt Docker image for mirrors

root/layout/components/sidebar/ReleaseGroupSidebar.js, root/layout/components/sidebar/ReleaseSidebar.js, root/static/scripts/common/coverart.js, root/static/styles/layout.less
Set a min-height for the div used to display cover artwork in the release and release group sidebars to avoid a big layout shift when the image is eventually loaded.
The release and release group sidebars don't reserve any space for cover artwork, so their content shifts down when the artwork is eventually loaded. The shift usually happens a second or two after layout, so I find that it frequently causes me to click in the wrong place when I'm trying to e.g. subscribe, merge, or add to a collection. (I attached an animated GIF to MBS-13644 showing the shift.)
Make `ReleaseSidebar` and `ReleaseGroupSidebar` set a new `present` class on `<div class="cover-art">`, and add a CSS ruleset that sets `min-height: 218px` (which I think is the height that a square image will end up with). There can …
=> MBS-13644: Reduce sidebar artwork layout shift

root/static/scripts/release-editor/edits.js, root/static/scripts/tests/release-editor/seeds/mbs-13579-part1.html, root/static/scripts/tests/release-editor/seeds/mbs-13579-part2.html, root/static/scripts/tests/release-editor/seeds/mbs-13579-part3.html, root/static/scripts/tests/release-editor/seeds/mbs-13579-part4.html, root/static/scripts/tests/release-editor/seeds/mbs-13579-part5.html, root/static/scripts/tests/release-editor/seeds/mbs-13579-part6.html, root/types/release.js, t/selenium.mjs, t/selenium/release-editor/MBS-13579.json5, t/sql/selenium.sql
MBS-13579
Prior to this commit, if you seeded a release label to an existing release that duplicated an existing release label on that release, the release editor would throw an error upon submission, as it would be trying to submit data that already exists.
This patch preserves the existing release label (and its database row ID), discarding the seeded one. Note that a "release label" is a label and catalog number pair, meaning the catalog number is included for de-duplication purposes.
The ticket presents three use cases. The first one is still possible, the second one is still impossible, and the third one is now possible. An alternative implementation would be to concatenate the seeded release labels with the existing ones (discarding any duplicates, like here), and adding a `removed` …
=> MBS-13579: Preserve existing release labels duplicated by seeded ones

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
I approved and merged the pull request #3328 too quickly without noticing that tests were failing.
Further strengthen the validation of e-onkyo URLs by:
* blocking search URLs with an explanatory error message,
* blocking e-onkyo URL for other entity types than release,
* converting /sp path to the redirect target path /album,
* fixing and updating tests accordingly.
Tested locally and waited for [CI build-and-test 11846](https://app.circleci.com/pipelines/github/metabrainz/musicbrainz-server/11846) to succeed.
Self-approving and merging ASAP to fix CI tests in the branch `master`.
=> Fixes and improvements for e-onkyo URL validation

root/components/forms.tt, root/release/edit/tracklist.tt, root/static/scripts/alias/AliasEditForm.js, root/static/scripts/edit/components/FormRowNameWithGuessCase.js, root/static/scripts/edit/components/FormRowSortNameWithGuessCase.js, root/static/scripts/edit/components/FormRowText.js, root/static/scripts/guess-case/MB/Control/GuessCase.js, root/static/scripts/release-editor/actions.js, root/static/scripts/release-editor/fields.js, root/static/styles/colors.less, root/static/styles/forms.less, root/static/styles/release-editor.less, t/selenium/Artist_Edit_Form.json5, t/selenium/Recording_Edit_Form.json5, t/selenium/release-editor/The_Downward_Spiral.json5
When the user hovers over a "Guess case" button, display a preview of the updated name.
It's hard to predict how names or titles will be changed when clicking "Guess case" or "Aa" buttons, and impossible to undo unwanted changes.
In a wide browser window, it's also difficult to see which track will be affected by a given "Aa" button in the tracklist editor.
Display updated strings with a gray background while the user is hovering over the buttons. When the mouse exits the button, restore original values.
I updated various "Guess case" implementations:
* `root/release/edit/tracklist.tt`, `root/static/scripts/release-editor`: Knockout implementation used for the release editor's tracklist tab.
* `root/components/forms.tt`, `root/static/scripts/guess-case/MB/Control/GuessCase.js`: …
=> MBS-8217: Show preview on hover over guess case

root/components/list/EventList.js, root/components/list/ReleaseGroupList.js, root/components/list/ReleaseList.js, root/release_group/ReleaseGroupIndex.js, root/search/components/EventResults.js, root/search/components/ReleaseGroupResults.js, root/search/components/ReleaseResults.js
[MBS-13676](https://tickets.metabrainz.org/browse/MBS-13676): #3256 added a blank icon to the left of titles of releases that don't have cover art to fix the alignment issue described in [MBS-13263](https://tickets.metabrainz.org/browse/MBS-13263).
However, the extra spacing looks strange when none of the releases in a list have cover art.
in `EventList.js`, `ReleaseGroupList.js` and `ReleaseList.js`, do not show cover art indicators, and therefore spacers, if none of the listed entities have cover art.
In `ReleaseGroupIndex.js`, `EventResults.js`, `ReleaseGroupResults.js` and `ReleaseResults.js`, do the same, but curry `buildResult` to pass the data down.
Tested on the following URLs on a sample database:
- http://127.0.0.1:5000/artist/109958eb-a335-4c5e-907e-597ff4c6af46
- …
=> MBS-13676: Remove alignment spacing when there is no cover art indicator

root/static/scripts/edit/components/FormRowNameWithGuessCase.js, root/static/scripts/edit/components/FormRowSortNameWithGuessCase.js, root/static/scripts/guess-case/MB/Control/GuessCase.js, root/static/scripts/release-editor/actions.js
Make the FormRowNameWithGuessCase and
FormRowSortNameWithGuessCase components, the GuessCase control, and the tracklist editor code avoid showing previews if a button is held while the mouse enters a "guess case" or "guess sort name" button.
Otherwise, it's easy to clear the user's selection if they accidentally mouse over the button while dragging to select text.
See [this comment](https://tickets.metabrainz.org/browse/MBS-8217?focusedId=72891&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-72891). If you accidentally overshoot the text field while dragging to the right, displaying the guess case preview clears the selection.
Don't show the preview if a mouse button is held in the `mouseenter` event.
Manually tested that previews aren't shown while dragging …
=> MBS-8217 (II): Don't show guess case preview while dragging

lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Utils.pm, t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupArtist.pm, t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupArtist.pm, t/sql/webservice.sql
We show these for all events on the XML API, but we were serializing them only for toplevel events in JSON. This brings parity to both APIs in this regard.
Tested manually with the `/ws/2/artist/7dc8f5bd-9d0b-4087-9f73-dc164950bbd8?inc=aliases+artist-rels+place-rels+event-rels+series-rels&fmt=json` URL listed in the ticket.
=> MBS-13683: Always show event dates on JSON API

root/release/edit/tracklist.tt, root/static/scripts/release-editor/actions.js, root/static/scripts/release-editor/fields.js, root/static/styles/colors.less, root/static/styles/forms.less, root/static/styles/release-editor.less, t/selenium/release-editor/The_Downward_Spiral.json5
Use a light gray background for medium and tracklist name inputs in the release editor after they've been updated using a "guess case" button. The background is cleared after the inputs are focused.
After clicking a "guess case" button in the tracklist editor, it can be hard to tell what was changed, especially if all of the media/tracks don't fit onscreen (so that changes can't be seen in the preview when hovering over the button).
Make updated medium and track name inputs use a light gray background color after they're updated by a "guess case" button:
The background is reset after an input is focused.
Manually tested that medium and track name inputs behave as expected. Also updated `t/selenium/release-editor/The_Downward_Spiral.json5` to check that the new CSS class is added and …
=> MBS-8217 (III): Highlight tracklist names after guess case

t/selenium/release-editor/The_Downward_Spiral.json5
Specify the click target using the 'css=' syntax rather than a document.querySelector() call.
=> Fix test failure from 434684613971

root/static/scripts/release-editor/edits.js, t/selenium.mjs, t/selenium/release-editor/MBS-13692.json5
If a release has at least one existing label, and you add a duplicate of it (triggering visible error messages adjacent to the fields), and then edit both of them, then it's expected that this would produce two edits: one to modify the existing release label, and one to add a new one. Instead, f0613577fd0e58060417afd3ce46a718f8baeb8e introduced a regression whereby the same release label is edited twice, causing the second edit to immediately trigger a failed dependency error.
This patch tracks which existing release labels have already been modified, so that we don't attempt to reuse the same one twice when producing edits.
Added a new Selenium test which reproduced the issue prior to the patch being applied.
=> MBS-13692: Beta: release editor edits the same release label twice

lib/MusicBrainz/Server/Data/Language.pm, lib/MusicBrainz/Server/Data/Work.pm, lib/MusicBrainz/Server/FilterUtils.pm, lib/MusicBrainz/Server/Form/Filter/Work.pm, root/static/scripts/common/components/FilterForm.js, t/lib/t/MusicBrainz/Server/Controller/Artist/Filtering.pm, t/sql/filtering.sql
This allows filtering an artist's works by the lyrics language. Since giving all languages as options would be overwhelming and not very useful, this looks at what languages are actually used and offers any of these or [none] for works with no languages set. It's implemented in a very similar way to the existing release label filter.
Manually. Left to do:
=> MBS-13682: Add language filter to Works tab

lib/MusicBrainz/Server/Controller/WS/js/Edit.pm, lib/MusicBrainz/Server/Data/Utils.pm, lib/MusicBrainz/Server/Validation.pm, root/static/scripts/release-editor/init.js, t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm, t/lib/t/MusicBrainz/Server/Validation.pm
People are using Hangul fillers to circumvent the edit note requirement. Also, while 63898c73fe4482688bee7c57e937035ad5c76b0a wanted to check all edit notes, we forgot that some places that go through `ws/js` are not affected by it.  
HANGUL FILLER is a character often used to have "empty usernames" and similar things since it's an empty space but not considered a space char. This considers it, together with other similar Hangul fillers, insufficient for a valid note.
While testing in the release editor I noticed something was weird since Hangul-filler only edit notes were not getting rejected. The second commit here fixes that bug (we were not checking the right variable).
The third commit makes it so that invisible characters are not actually stripped by `sanitize`, since they can have …
=> MBS-13528 / MBS-13696: Calculate invalid edit notes in more places and with more invisible characters

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
#3328 added e-onkyo link validation/cleanup/etc., and #3329 further improved upon it, but it turns out that neither accounted for a special case I came upon today, where numbers come earlier in the final chunk of the URL than were previously expected.
If I paste `https://www.e-onkyo.com/music/album/ve5hd43611/` into a release's links section, MB currently cuts it off at `https://www.e-onkyo.com/music/album/ve5/` because the regex isn't built to handle a number surrounded by letters in the final section.
This PR lightly generalizes e-onkyo's validation/cleanup regex to account for edge cases like this, and adds a new test accordingly.
Tested the new regex with both non-edge-case and edge-case release URLs in regex101 and it seemed to handle both without a problem.
=> Adjust e-onkyo validation/cleanup regex for special case

lib/MusicBrainz/Server/Data/Search.pm
Cover art presence is not actually displayed for release group indexed searches (all release groups show as not having cover art).
This was loading the artwork (which we don't actually need) but not actually updating the `has_cover_art` flag we actually care about for displaying the icon.
I probably broke this when I introduced `load_has_cover_art` and forgot to use it here? In any case, that's what we need here. Should also make searches slightly faster, I expect.
Manually, with `/search?query=arvo+part&type=release_group&limit=25&method=indexed&page=3` with live data
=> MBS-13677: Show cover art presence in indexed searches

root/static/scripts/artist/components/ArtistCreditRenamer.js
The `ArtistCreditRenamer` component doesn't display on development servers.
React [runs effects twice](https://react.dev/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development) in development. Prior to this patch, the `installedArtistNameEvent` check would prevent reinstalling the event after the cleanup function first runs. It serves no actual purpose in production or development.
This removes it entirely.
=> Fix showing `ArtistCreditRenamer` in development

admin/sql/updates/20240726-mbs-9373.sql, lib/MusicBrainz/Server/Constants.pm, lib/MusicBrainz/Server/Controller/Admin.pm, lib/MusicBrainz/Server/Controller/Edit.pm, lib/MusicBrainz/Server/Data/Editor.pm, lib/MusicBrainz/Server/Edit.pm, lib/MusicBrainz/Server/Entity/Editor.pm, lib/MusicBrainz/Server/Form/Admin/EditUser.pm, lib/MusicBrainz/Server/Form/Admin/PrivilegeSearch.pm, root/admin/EditUser.js, root/admin/PrivilegeSearch.js, root/admin/components/UserList.js, root/constants.js, root/layout.tt, root/layout/index.js, root/static/scripts/common/utility/privileges.js, root/user/UserProfile.js, root/utility/edit.js, t/lib/t/MusicBrainz/Server/Data/Editor.pm
I have had several times where I would have liked to block someone from voting, at least temporarily, but not from editing.
That's not currently possible, so this splits the editing and voting privileges into two flags.
A one-off script (to be added) should be ran to add voting blocks to all editors that previously had the editing/voting combined flag.
Manually (including trying to submit votes from JS and ensuring Perl blocks it), plus any existing tests that already check for limited votes.
=> MBS-9373: Split voting and editing privilege revoking

eslint.config.mjs, package.json, yarn.lock
https://github.com/jsx-eslint/eslint-plugin-react/releases/tag/v7.35.0
This adds a new rule which we don't fail against.
It also adds support for eslint9 (still missing from eslint-plugin-import though so we can't move up to that yet).
=> Update eslint-plugin-react to 7.35.0

root/static/scripts/guess-case/utils.js, root/static/scripts/tests/GuessCase.js
Update the guess case titleString() function to avoid uppercasing typically-lowercased ETI words like "mix" that are also Roman numerals.
The word "mix" is a frequent occurrence in extra title information ("extended mix", "club mix", etc.), but "MIX" is also 1009 in Roman numerals. When "Uppercase Roman numerals" is checked in the guess case options, "MIX" is always capitalized, resulting incorrect e.g. "extended MIX" ETI.
Avoid capitalizing "mix" when it appears in parentheses/brackets. I'm actually ignoring Roman numerals whenever `flags.isInsideBrackets() && isLowerCaseBracketWord(lowercase)` is true since that feels cleaner than introducing a new list, even though I think that "mix" is the only problematic word here.
Manually tested, plus added unit test cases verifying that "mix" is …
=> MBS-12523: Don't treat "mix" ETI as Roman numerals

root/components/RelationshipsTable.js
The first row(s) in `RelationshipTable` weren't getting all needed columns after 7072352ad4084e6bd21ef6249520c276998f7737 removed the nested component, which means it probably only worked before because of things getting re-rendered.
The actual right way to do this would seem to be to calculate it once per relationship group, since we want it to apply to the whole group anyway.
Manually, with the work given on the ticket (`/work/9abc3eb0-e541-4342-aed3-1040d91525a4`) and a full server tunnel.
=> MBS-13707: Calculate needed columns first in getRelationshipRows

lib/MusicBrainz/Server/Data/Editor.pm, lib/MusicBrainz/Server/EditSearch/Predicate/Role/User.pm
The edit search filter for edit notes by a beginner editor was returning edits which did not have an edit note at all.
On inspection of the code, I found that we were completely replacing the search condition in `Predicate::Role::User` when the operator was `limited`, so this search was becoming simply "Editor is a beginner".
Originally I just added a new operator `beginner_note_author` and added a new `elsif` to handle it, but @mwiencek suggested in a comment a way we'd be able to use the passed template clauses, which seems to work nicely, so I ended up using that.
Tested by hand only.
We don't seem to currently have any decent tests for edit search ensuring the correct results are returned (only some tests that check validation of fields). Ideally we'd change that, although a proper …
=> MBS-10609: Actually check for edit notes by beginners

lib/MusicBrainz/Server/EditSearch/Predicate/Role/User.pm, root/edit/search_macros.tt, root/vote/VotingIndex.js
On top of https://github.com/metabrainz/musicbrainz-server/pull/2808 to avoid possible conflicts.
Edits without notes are a common mark of either beginners not quite sure of what they are doing (common risk of human error) or expert editors a bit too sure of what they are doing (also a common risk of human error). Despite that, we do not currently have any way to search for them specifically, AFAICT.
This adds an option under "Edit Note Authors" (seemed the best fit) with the wording "do not exist (edit has no notes)". It might read a bit strangely, but it's the best I could think of - improvement suggestions welcome.
It also adds a new vote suggestion for beginner edits without notes, and another for destructive edits without notes. These seem like the most obvious use cases where a …
=> MBS-12847: Allow searching for edits without any notes 

lib/MusicBrainz/Server/EditSearch/Predicate/Role/User.pm, root/edit/search_macros.tt
On top of https://github.com/metabrainz/musicbrainz-server/pull/2813 to limit conflicts.
There is currently no way to explicitly look for edits by non-beginner editors, but some editors had requested this to be made possible. The main goal was to search for edits by non-beginners with notes by beginners, which is going to be possible again with MBS-10614 (in beta now).
I added a `not_limited` equivalent to the existing `limited` check as part of the `User` predicate role, which is only made available for `predicate_user`s other than `edit_note_author` (so, effectively, only for `editor`).
This is our fourth different check for beginner status (fifth once the fix for MBS-10609 is merged). Ideally we would be having this check at the database level and just be able to query …
=>  MBS-10610: Search for edits made by non-beginners 

lib/DBDefs/Default.pm, lib/MusicBrainz/Server/Authentication/Store.pm, lib/MusicBrainz/Server/Authentication/Utils.pm, lib/MusicBrainz/Server/Authentication/WS/Store.pm, lib/MusicBrainz/Server/Constants.pm, lib/MusicBrainz/Server/Controller/OAuth2.pm, t/lib/t/MusicBrainz/Server/Controller/OAuth2.pm
https://tickets.metabrainz.org/browse/MBS-13703
Tokens issued by the new MeB OAuth provider (prefixed with `meba_`) should be authenticated using the provider's introspect endpoint.
Adds a new utility, `find_oauth_access_token`, which either introspects `meba_` tokens on the new provider, or fetches them directly from the MB database.
Tested manually by fetching an access token from the new provider, and passing it via `Authorization` header to a web service request requiring authentication. I noted that the scope was correctly validated, too.
=> MBS-13703: Recognize tokens issued by the MeB OAuth Provider

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Genius artist pages have optional subpages such as `/songs` which we were leaving unchanged and then rejecting.
This drops anything after the artist name section so we get the URL form we all know and love.
Edited one of the URLCleanup tests to include `/songs`.
=> MBS-13714: Clean up Genius artists links

root/static/scripts/common/i18n/expand2.js
The `getKey` method added in 6f57c167a3996f35cb1012d05f93e709f66cbdd6 doesn't prevent conflicts in cases like this example (pulled from externalLinks.js):
typeDescription = exp.l('{description} ({url|more documentation})', {
description: expand2react(l_relationships(linkType.description)),
url: '/relationship/' + linkType.gid,
});
This is because the inner `expand2react` call does not share a `VarArgs` instance with the `exp.l` call, so separate `nextKey` counters are used. Thus the first link in the `description` will get the key "a-1", and so will the link generated for `url`.
We can avoid this by just using a global counter for `nextKey`. This is not entirely ideal, because changing the key on every render prevents React's reconciliation algorithm from reusing the same elements. I'd …
=> Completely avoid conflicting keys in `VarArgs.prototype.getKey`

app.psgi
It's difficult to determine which requests are leading to increased response times from the plackup logs.
This copies the "combined" plackup log format and appends the value of the `X-Runtime` header which is injected by `Plack::Middleware::Runtime`.
Note that the modified log format is only used in production. (The `AccessLog` middleware is enabled by default in development, though I didn't find out how to change the log format used in that case.)
This is currently running on hip; I'll copy it to other servers with spikes in response time too.
=> Log plackup response time

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
We supported `/recordings/artists` links for thesession.org, but we didn't currently support the equivalent `/tunes/composers` links, such as https://thesession.org/tunes/composers/897 - we should accept those too.
Added an `URLCleanup` test for this.
=> MBS-13718: Support The Session composer pages

root/static/scripts/edit/components/ArtistCreditBubble.js, root/static/scripts/edit/components/ArtistCreditEditor.js, root/static/scripts/edit/components/ArtistCreditEditor/types.js, root/static/scripts/edit/components/ArtistCreditNameEditor.js, root/static/styles/forms.less, script/reset_selenium_env.sh, t/selenium/Artist_Credit_Editor.json5
Add up and down buttons next to artist credits that can be used to reorder them, similar to how mediums and tracks can be reordered.
There's currently no easy way to reorder artist credits (e.g. when the order in MusicBrainz doesn't match what's on an album's packaging).
Add up and down buttons to the right of each credit that can be used to move it up or down:
Join phrases keep their original positions when reordering. For example, pressing the first credit's down button in the above example produces `Metallica & Megadeth` rather than `MetallicaMegadeth & `.
These buttons are patterned after the medium up/down and track up/down icons in the tracklist editor: the first credit has an up button and the last item has a down buttons even though they don't do anything. Let me know if it'd be …
=> MBS-3255: Support reordering artist credits

root/release/edit/tracklist.tt, root/static/scripts/release-editor/actions.js
Make the up and down arrow keys move the focus between adjacent tracks' number, title, and length fields in the tracklist editor.
Only do this when the cursor is already at the beginning or end of the input to avoid overriding the browser's default text-editing shortcuts.
Fixing multiple track titles or editing durations requires either switching frequently between the keyboard and mouse or pressing the Tab key six times to move down to the next row.
Make the up and down arrow keys move the focus to the corresponding input in the previous or next row.
The default behavior on all (I think) platforms is for these keys to move the caret to the beginning or end of the current input, so this change only moves the focus when the caret is already at the beginning or end of the input.
I tested …
=> MBS-13724: Make up/down keys move between tracklist inputs

root/static/scripts/common/i18n/expand2.js, root/static/scripts/common/i18n/expand2react.js, root/static/scripts/edit/components/ReleaseMergeStrategy.js, root/statistics/StatisticsLayout.js, root/types/forms.js, root/types/i18n.js
https://tickets.metabrainz.org/browse/MBS-13729
The commit "New way of assigning React keys to variables substitutions" addresses the issue that broke the "mb. MERGE HELPOR 2" script.
The commit "MBS-13729: Handle missing `medium_positions` on release merge" prevents a stack trace from being shown to the user.
Only manual testing on my local development server.
=> MBS-13729: `TypeError` while trying to merge releases

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
When implementing MBS-13438 it was thought that Qobuz always has a streaming option, but some releases are available for download only which isn’t currently allowed in the external links editor.
Just allow "download"-only additionally to the already allowed "streaming"-only (auto-selected) and "download"+"streaming".
Additionally, now that download-only is an option, the streaming relationship type is no longer a subset of all possible options. It would be misleading to keep auto-selecting the streaming relationship type for Qobuz URLs. Therefore this patch also disables auto-selecting relationship type for Qobuz URLs.
Tested locally in a release editor and updated CI tests.
=> MBS-13723: Allow "download"-only relationships to Qobuz URLs

root/static/scripts/release-editor/fields.js, t/selenium/release-editor/The_Downward_Spiral.json5
Update the release editor to avoid showing the "Update the recording title to match the track title" checkbox when the recording search input differs from the track title but an existing recording hasn't been selected.
1. Start adding a new release that isn't based on an existing one.
2. On the recordings tab, click a track's "Edit" button and then type something into the "Search" field.
The "Update the recording title to match the track title" checkbox is shown even though there's no existing recording to update.
Update the `Track` class's `titleDiffersFromRecording` method to return false if there's no existing recording. The `artistDiffersFromRecording` method already did this.
I manually tested locally that the checkbox is now only shown after an existing recording (with a different …
=> MBS-13744: Avoid showing "Update title" without a recording

lib/MusicBrainz/Server/Controller/WS/js/Area.pm, lib/MusicBrainz/Server/Controller/WS/js/Artist.pm, lib/MusicBrainz/Server/Controller/WS/js/Editor.pm, lib/MusicBrainz/Server/Controller/WS/js/Event.pm, lib/MusicBrainz/Server/Controller/WS/js/Genre.pm, lib/MusicBrainz/Server/Controller/WS/js/Instrument.pm, lib/MusicBrainz/Server/Controller/WS/js/Label.pm, lib/MusicBrainz/Server/Controller/WS/js/Place.pm, lib/MusicBrainz/Server/Controller/WS/js/Release.pm, lib/MusicBrainz/Server/Controller/WS/js/ReleaseGroup.pm, lib/MusicBrainz/Server/Controller/WS/js/Role/Autocompletion.pm, lib/MusicBrainz/Server/Controller/WS/js/Series.pm, lib/MusicBrainz/Server/Controller/WS/js/Work.pm, root/release/edit/information.tt, root/static/scripts/release-editor/actions.js, root/static/scripts/release-editor/duplicates.js, root/static/scripts/release-editor/init.js, root/static/scripts/tests/release-editor/seeds/mbs-9479.html, root/static/styles/release-editor.less, t/selenium.mjs, t/selenium/release-editor/MBS-9479.json5
Update the release editor to search for release groups credited to any of the current artists with similar names and display them in a list.
When adding new releases, it's easy for editors to accidentally create duplicate release groups, particularly when the discography is spread over multiple pages or when the existing RG has an unexpected secondary type that makes it get listed in a lower section.
Perform a search for similarly-named release groups when the release name or credited artists change and display the results in a list to make it easier for the editor to choose an existing RG.
Manual testing on my local MBS instance using production search, plus a new Selenium test.
=> MBS-9479: Warn about duplicate release groups

root/release/edit/information.tt, root/static/scripts/release-editor/actions.js, root/static/scripts/release-editor/init.js, root/static/styles/release-editor.less, t/selenium/release-editor/MBS-9479.json5
Make the release editor display a "Failed loading existing release groups" error and retry link when a request to load possibly-duplicate release groups fails.
#3359 made the release editor query for release groups with names similar to the release's, but it didn't display an error if the request failed due to network or server issues.
Display a "Failed loading existing release groups." message and a "Retry" link:
I moved the lookup code from `init.js` to `actions.js` so it can be called from the retry link.
Manually tested using my local dev server. (I think I'm unable to test the no-error path now, since I think I can't make cross-origin calls to the `/ws/js/release-group` endpoint due to CORS restrictions.)
=> MBS-9479 (II): Show errors for dupe RG failures

root/statistics/layout.tt, root/statistics/macros-footer.tt, root/statistics/macros-header.tt, root/statistics/timeline.tt
Several parts of the timeline page were using the `mb_server` translation domain, but clearly should be using the `statistics` one. This means the tabs were untranslated, and so were the legend entries that were hardcoded in TT.
Get rid of the mostly useless by now `macros-header.tt` and `macros-footer.tt` processes, and calling `USE Translation` in more places to set the right translation domain.
Manually, ensuring the right French translations appear now for the tabs and strings like "Rate of change graph" on the legend.
=> MBS-13697: Use right domain more in timeline page

root/vote/VotingIndex.js
Event artwork edits are ignored in the voting suggestion destructive list.
This adds the "Remove event artwork" edit to the list of destructive edits, but also refactors the way these are built (having separate constants for all the edit type groupings) so that they're easier to understand and maintain. While doing that I noticed a few weird kinks and straight issues with the types used, so those are fixed in separate commits.
I thought I'd also add some specific artwork vote suggestions since beginners often do artwork and often badly, so this does that by adding one artwork removal search and one beginners-editing-artwork search.
Manually by visiting the different links and ensuring the right edit types are selected for each.
=> MBS-13693: Improve voting suggestions for artwork edits

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
RYM has now implemented `/song` pages that have performer and engineer info and link the song to different releases it appears on, such as [this one](https://rateyourmusic.com/song/rick-astley/never-gonna-give-you-up/). This is separate from previously existing `/work` pages (mostly for classical). The best fit seems to be the recording level.
Support `/song` for recordings, move the check that says only video releases are allowed to actually appear only if the user tries to add a non-video `/release` link.
Added a new test for this. Manually tested the right error is still shown for non-video release links on recording pages.
=> MBS-13725: Support RYM song pages for recordings

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
This supports Amazon's new `/tracks` links, which display track info rather than album one as a priority (similarly to Spotify track links).
The code handling the old style of links, that redirected to the album, is untouched, so those still get cleaned to the album link.
Added a test to `URLCleanup`.
=> MBS-13732: Handle Amazon Music track links

root/release/edit/recordings.tt, root/static/scripts/release-editor/actions.js, root/static/scripts/release-editor/fields.js
Update the release editor so that individual tracks' checkboxes to update recording titles or artists can be unchecked after the "copy all" checkboxes have been checked.
Updating most (but not all) of the recording titles/artists on a release (common when fixing compilations) currently requires a bunch of clicking. There's no way to uncheck individual tracks after clicking one of the "copy all" checkboxes, so you need to individually click each of the tracks whose recordings should be updated. It's easy to make mistakes here since each track may have two checkboxes with similarly-worded text (for updating the title vs. artist).
Stop disabling the per-track checkboxes when a "copy all" checkbox is checked, and make the "copy all" checkboxes use computed values so they can be updated in …
=> MBS-13757: Support unchecking recordings to update

root/static/scripts/common/components/Autocomplete2.js, t/selenium.mjs, t/selenium/release-editor/MBS-13715.json5
MBS-13715
Stops propagation for the enter (and tab) keys on the artist input fields within the track AC bubble.
Tested manually + added a Selenium test.
=> MBS-13715: Pressing enter on track AC search dropdown should not move to the next track

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
We are "cleaning up" links such as https://twitter.com/i/user/19373710 to `https://twitter.com/i` and then accepting them as a "username" but in reality these are redirects to a normal Twitter/X link.
I blocked these redirects like we do for Spotify ones, where we request the editor to follow the link and provide the final one instead - the same error string is reused.
Manually, plus I added a test case to `URLCleanup`.
=> MBS-13761: Reject Twitter id redirects instead of breaking them

root/release/add_cover_art.tt
We are seeing plenty of issues with users carelessly uploading cover art to the wrong release, or uploading "improved" cover art (square versions of non-square covers, AI "improvements", removing "uglier" bits of the cover such as parental advisory marks, etc). Most of this is probably due to the fact that the page gives them no help, and most beginners are not going to find https://musicbrainz.org/doc/Cover_Art on their own.
This presents users with some basic indication about what *not* to upload to the CAA, in hopes that they will actually avoid adding these sorts of images instead of them needing to be voted down.
Manually, to ensure the string appears as expected.
=> MBS-13759: Add info about do-nots in add_cover_art

root/static/scripts/release-editor/init.js
When a new release is being added, update the state of the "Existing release groups with similar names" radio buttons when the user selects a release group using the autocomplete field.
#3359 added radio buttons listing potentially-duplicate release groups, but the radio buttons weren't updated if the user instead searched for and selected an existing release group using the autocomplete field. This could result in a confusing state where the autocomplete field would show one release group, while the radio button corresponding to a different release group or to "Add a new release group" would remain selected.
Listen for changes to the chosen release group and update the radio buttons correspondingly:
* If the chosen RG is in the list, check the corresponding radio button.
* If the chosen …
=> MBS-13777: Update RG selection when autocomplete is used

lib/MusicBrainz/Server/Controller/Role/Art.pm, root/main/ImageEditingUnavailable.js, root/server/components.mjs, t/selenium.mjs, t/tests.t
Users can still submit edits to images which cannot be properly reviewed.
I guess it will still be some time before Internet Archive services are fully restored. I expect read-only access to come first.
Temporarily disable image editing while the IA works to restore their services. This just adds a temporary error page which shows the user a message explaining the reason.
Loaded the relevant endpoints locally.
=> Temporarily disable image editing

.well-known/funding-manifest-urls
Related to https://github.com/metabrainz/metabrainz.org/pull/487 -- we need to have an indication in our repo to give permission for metabrainz.org/funding.json to speak for MB.
=> Add needed file for the funding.json system to know that it can speak

root/static/scripts/guess-case/modes.js, root/static/scripts/tests/GuessCase.js
Introduce a regular expression matching common words to exclude from "Guess case" when "Uppercase Roman numerals" is checked.
"Mi" is a common word in Spanish (and likely other languages) but also an uncommon (in album and song titles) number in Roman numerals. When "Guess case" is used while the "Uppercase Roman numerals" option is checked, titles like "Mi amor" are changed to "MI amor".
Add a regular expression matching common words that are also matched by the expression for matching Roman numerals. It currently matches "mi" and "mix" (the latter of which was already excluded from uppercasing when used in ETI).
Added a unit test case and manually tested in the edit-release form.
=> MBS-13806: Avoid uppercasing "mi" and "mix" as Roman numerals

lib/DBDefs.pm.sample, lib/DBDefs/Default.pm, lib/MusicBrainz/Server/Controller/User.pm, lib/MusicBrainz/Server/Email.pm, t/lib/t/MusicBrainz/Server/Email.pm
This is the start of enabling `mb-mail-service` incrementally, as a broken-down version of #3363. 
This adds the configuration option `MAIL_SERVICE_BASE_URL` in DBdefs, and replaces `send_message_to_editor` (aka `/user/<id>/contact`) with the new template.
This has been manually tested. 
1. Ensure beta.musicbrainz.org is configured correctly before deploying
2. Once this has seen some success, enable more new templates
3. Write replacement tests for the new code
=> MBS-13719: Enable sending contact emails through new service

babel.config.cjs
MBS-13799
Per https://babel.dev/docs/babel-preset-env
"It is recommended to specify the minor version otherwise "3" will be interpreted as "3.0" which may not include polyfills for the latest features."
That would appear to be the case for `Object.hasOwn` at the very least, as specifying the corejs version causes its polyfill to be injected (in addition to other polyfills that weren't being included -- although `Object.hasOwn` is the only one which I see errors on Sentry for).
I don't have access to a browser that doesn't support `Object.hasOwn` to begin with, but I compared the un-minified common-chunks.js output before and after this patch.
=> MBS-13799: Resolve "TypeError: Object.hasOwn is not a function"

lib/MusicBrainz/Server/Report/EmptyReleaseGroups.pm, lib/MusicBrainz/Server/ReportFactory.pm, root/report/EmptyReleaseGroups.js, root/report/ReportsIndex.js, root/server/components.mjs
Empty release groups are low quality data that is usually actionable. This adds a report that gives users a good way to find them for some often relatively simple data improvement.
I ran the report with the sample data, and found 677 results (a lot more than I expected, but I checked a bunch and they did seem genuinely empty).
=> MBS-13828: Add report for empty release groups

lib/MusicBrainz/Server/Email.pm, t/lib/t/MusicBrainz/Server/Email.pm
[MBS-13830](https://tickets.metabrainz.org/browse/MBS-13830)
Originally reported by chaban at https://community.metabrainz.org/t/email-redesign/700833/9:
>    I also noticed some other changes, like the From header always saying “MusicBrainz Server” rather than the username. And not using Sender anymore.
> 
>    Now one will have to search the entire subject to find and sort messages by a certain user.
We now set the `from` parameter using the `_user_address` function with `$hidden` set, which produces the no-reply email with the username as the address name (phrase?).
We also set the `sender` parameter to `$EMAIL_NOREPLY_ADDRESS`, matching the original behaviour. This requires mb-mail-service v0.4.0 to take effect (https://github.com/metabrainz/mb-mail-service/commit/da4ce0d31b8ad56cd50b1 …
=> MBS-13830: Use username in From header on user contact email

lib/MusicBrainz/Server/Controller/Role/Art.pm
We forgot to import `l` before using it in `Controller::Role::Art`. This was unsurprisingly causing an ISE.
Import `l`
=> MBS-13834: Load l() in Role::Art

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
For single releases, it seems Audiomack uses `/song` URLs, but these are only allowed at the recording level at the moment.
Allow `/song` for releases as well as recordings.
Changed the existing test to make sure both options are supported.
=> MBS-13829: Also support Audiomack "song" for releases

root/account/Register.js, root/layout.tt, root/layout/components/Footer.js
[MBS-13820](https://tickets.metabrainz.org/browse/MBS-13820)
- Removed the Twitter URL from the footer
- Added links to Mastodon and Bluesky in the footer
These were just minor cosmetic changes and they work fine on my test environment.
=> MBS-13820: Added links to Mastodon and Bluesky in the footer

lib/MusicBrainz/Server/Data/Editor.pm, t/lib/t/MusicBrainz/Server/Data/Editor.pm
Canceling edits in `cancel_edits_and_votes` is supposed to happen in the opposite order as the edits were entered but sorting by `open_time` alone does not consistently work - edits 118415049 (Add series) and 118415050 (Add rel to the series) have the exact same open time since they were opened as a set, and the code tries to close the series first causing an ISE. This only breaks for series AFAICT, since for other stuff we actually remove the entity even if it has relationships.
Just sorting by ID would probably be enough, but just to play it extra safe, this keeps the sort by time first, then ID if time is the same.
Changed the spammer test to specifically test for this case.
=> MBS-13839: Also sort by ID in cancel_edits_and_votes

root/artist/utils.js, root/static/scripts/edit/MB/Control/ArtistEdit.js
We changed this for sidebar display for `Created` a while ago, but I missed the artist editor, and area should use `Created in` for consistency.
This keeps the standard end date / end area strings; that section will eventually be hidden for characters with https://github.com/metabrainz/musicbrainz-server/pull/3402 but for now keeping it as default seems best.
Manually.
=> MBS-13802: Always use "Created (in)" for characters

lib/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm
Change EditReleaseLabel's "This release label no longer exists." failure message to "This label is no longer associated with the release." to make it clearer that the issue is that the release-to-label association no longer exists, and not necessarily that the label entity itself has been deleted.
When an "Edit release label" edit fails due to the original label no longer being associated with the release, the ModBot failure message can be misinterpreted as saying that the label entity itself no longer exists.
Reword the message in an attempt to make it clearer that it's just the release-to-label association that doesn't exist.
Checked the new message locally:
1. Created votable edits to add a new release with a label.
2. Created a votable edit to change the release to use a different …
=> MBS-13854: Reword release label edit failure message

lib/MusicBrainz/Server/Controller/Role/EditRelationships.pm, lib/MusicBrainz/Server/Controller/WS/js/Edit.pm, root/static/scripts/relationship-editor/components/DialogPreview.js, root/static/scripts/relationship-editor/components/RelationshipItem.js, root/static/scripts/relationship-editor/utility/prepareHtmlFormSubmission.js, root/static/scripts/release/components/ReleaseRelationshipEditor.js, t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm, t/sql/ws_js_edit.sql
We keep having issues where people will hit an ISE after changing from a relationship type with dates (such as member) to one without (such as founder), because the dates are still stored and submitted with the relationship even though it doesn't make sense.
It's even more confusing with the new editor because the relationship preview will still show the dates, even though the type does not support them, and even though the user has no way to actually change them anymore.
Since we do not want to lose the dates in a situation where the user ends up selecting a second type that does support them, I was originally stashing and blanking them if a type without dates is selected, and restoring them if a type with dates was selected again …
=> MBS-9063: Ignore dates in rels editor for rel types without them

lib/MusicBrainz/Server/Controller/Role/Rating.pm, root/entity/Ratings.js
While we block seeing the profiles of spammer users, their ratings are still visible. For cases where the user was specifically spamming ratings, this makes marking them as spammers kinda useless.
We also use the spammer ratings in the calculation of the average community rating, which is not ideal.
Sadly, it turns out we will need a schema change (MBS-12794) to stop using spammer ratings (and tags) when calculating community results.
For now, this at least hides links to spammer profiles from the ratings page and makes it clear to users viewing from that page that the ratings might be dodgy. There's no indication of that on the sidebar, sadly, but it's something, and it probably doesn't make sense to write code to check for spammer ratings on all pages with sidebars if we plan to stop …
=> MBS-12792: Hide ratings by spammer users

lib/MusicBrainz/Server/Edit/Relationship/Create.pm, lib/MusicBrainz/Server/Edit/Relationship/Delete.pm, lib/MusicBrainz/Server/Edit/Relationship/Edit.pm, lib/MusicBrainz/Server/Entity/Relationship.pm, t/lib/t/MusicBrainz/Server/Edit/Relationship/Create.pm, t/lib/t/MusicBrainz/Server/Edit/Relationship/Delete.pm, t/lib/t/MusicBrainz/Server/Edit/Relationship/Edit.pm
Some `entity0` are not being loaded for add/edit/delete relationship edits in beta, leading to the entity being shown greyed out as if it had been removed.
When both entities had the same type, I was overwriting the keys for entity 0 instead of adding the entity 1 ones alongside them.
This could be avoided, but since we don't actually need to be careful with this anymore since I figured out how to use `load_subobjects` to only try to look at ACs where they exist, the easiest way to avoid the issue is to revert the changes to the edit files.
Manually by checking the reported edits (`/edit/119271964` and `/edit/119174960`) and edit searches for artist-artist and recording-recording relationship types such as [this one](http://reolappy:5000/search/edits?auto_edit_filter=&order=desc&negation=0 …
=> MBS-13862: Unbreak rel foreign keys for entities of same type

root/layout/components/sidebar/ArtistSidebar.js, root/layout/components/sidebar/PlayOnListenBrainzButton.js, root/layout/components/sidebar/ReleaseGroupSidebar.js, root/layout/components/sidebar/ReleaseSidebar.js, root/release_group/ReleaseGroupIndex.js, root/release_group/ReleaseGroupLayout.js
We now have entity pages for artists and RGs ("albums") in ListenBrainz, but we still link only to BrainzPlayer playlists.
This changes the LB buttons to link to entity pages when possible.
Release links redirect to release groups, so the LB team advised to just link to RGs directly. Since the pages cannot be played if empty, we don't change the existing behaviour where we hide the buttons if no releases exist in an RG
or no tracks exist on a release. We no longer care about the first release's MBID for RGs, just that it exists, so this simplifies that parameter to be boolean.
Also adding links for artists since those are now available. I did not skip "empty" artists (with no releases nor recordings) because we only have this data from the artist index but we want the buttons to appear on …
=> MBS-13416: Link to entity pages from LB buttons

root/static/scripts/common/components/EntityLink.js
In beta, the new code showing the primary alias looks a bit dumb for relationships where the relationship credit is itself already the same as the alias, such as "Lan Shui (_Lan Shui_)" in [this recording](https://beta.musicbrainz.org/recording/905b6a88-7303-4020-a501-19cf5f930347).
In cases where we have a relationship credit, for example, it doesn't make sense to repeat the alias if it matches the credit. On the other hand, it actually *does* seem to make sense to show the alias if it doesn't match the credit even if it does match the name - an editor checking a Japanese or Russian release might appreciate knowing who a Western artist shown under a local credit is. This changes the name === alias check to check the actual content to be displayed rather than the entity name. If we feel …
=> MBS-13863: Compare alias with content, not entity name

lib/MusicBrainz/Server/Controller/Artist.pm
I forgot to load primary aliases for RGs on artist pages.
To load primary aliases for RGs on artist pages.
Manually, with the artist from the ticket (`/artist/5837fcae-b639-41db-ae1d-87fa9141509c`) using a full data tunnel.
=> MBS-13867: Display RG primary alias in artist overview

lib/MusicBrainz/Server/Controller/WS/2/Area.pm, lib/MusicBrainz/Server/Controller/WS/2/Instrument.pm
This removes two definitions that were neither browse nor lookup, but a seemingly useless mix of the two we do not actually use. It also adds the lookup `action` to instrument, which was missing it.
=> Remove useless API definitions

root/static/scripts/common/components/ArtistCreditLink.js, root/static/scripts/common/components/EntityLink.js, t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
This shows multiple right-to-left artist credits correctly
This fixes MBS-13749, where multiple right-to-left artist credits are not rendered correctly
Wrap the entire `ArtistCreditLink` in `<bdi>` tags.
Had to remove `<bdi>` tags from the `EntityLink` parts so that the entire credit text will be taken into account when calculating the directionality of the text, instead of just the join phrase.
- Tested release [81d3646a-c1d4-4807-80b7-25d0380ffb0a](https://beta.musicbrainz.org/release/81d3646a-c1d4-4807-80b7-25d0380ffb0a) which has multiple such credits on a dev server. 
- Verified that left-to-right credits are not affected.
- ran JavaScript unit tests
=> MBS-13749: Wrap artist credit links in bdi

lib/MusicBrainz/Server/Controller/Artist.pm, lib/MusicBrainz/Server/Controller/Root.pm, lib/MusicBrainz/Server/Controller/Tag.pm, lib/MusicBrainz/Server/Controller/User.pm, lib/MusicBrainz/Server/Data/Editor.pm
I had loaded aliases here for some cases, but not most - this should now cover all pages (user tag and user tag by entity, and user rating and user rating by entity).
I also noticed while testing that I wasn't loading aliases on artist merge pages, so a separate commit does that now.
Manually, with `/user/reosarevok/tag/nyū%20myūjikku` / `/user/reosarevok/tag/nyū%20myūjikku/artist` and `/user/dragonzeron/ratings` / `/user/dragonzeron/ratings/artist` - and by merging some artists with aliases.
=> MBS-13872: Show primary alias in user tags and ratings

root/static/scripts/edit/URLCleanup.js
Valid dribbble.com links are being rejected.
We were validating with `artstation.com`... clearly nobody has tried to use this in years. Just change it to `dribbble.com`.
Manually. We don't currently have a way to automate-test that a link is *not* blocked, I think, other than checking what entities are accepted - I guess we could set the valid entities to all relevant ones on all cases where we don't actually close any options when validating?
=> MBS-13891: dribbble.com URLs are wrongly blocked

lib/MusicBrainz/Server/Data/WikiDoc.pm, t/lib/t/MusicBrainz/Server/Data/WikiDoc.pm
Wiki links that are returned as relative links (such as pages listed inside a category in `Category:X` links) are not being detected as such, and not being turned into `/doc/` links, leading to broken links to `mb.org/DocPage`. See https://musicbrainz.org/doc/Category:How_To for an example.
Also recognize relative links as wiki links and turn them into `/doc/` links as part of `_fix_html_links`
Manually (by disabling the cache and checking the new version did have working links), plus I extended the existing Data::WikiDoc to have a relative link for the test to check.
=> MBS-13888: Also convert relative wiki links to /doc

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
We currently blocking edit submission when a Bandcamp user link is added, but nothing is shown to the user - the submit button is just greyed out. MBS-12408 asks to allow these (separate from artist links) but in any case as long as we keep blocking them we should show the error so it is clear what's going on.
The reason no error message was displayed is simply that no target was given, so this adds a target (`ENTITY` since that's what we already used for the equivalent label check).
Added a test to make it clear that this blocking is (currently) intentional, at least.
=> MBS-13591: Show error when blocking Bandcamp user page

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Threads links are not cleaned of useless parameters, and the new format for posts is unsupported.
Dropping the useless URL params, and accepting and cleaning the new threads/posts format. I'm still cleaning to the `/t/post_id` format (which still works) since it seems like it might be more persistent since it doesn't depend on the name not changing
Added cleanup tests.
=> MBS-13855 / MBS-13887: Threads handling improvements

lib/MusicBrainz/Server/Controller/WS/2/Genre.pm, t/lib/t/MusicBrainz/Server/Controller/WS/2/BrowseGenres.pm, t/lib/t/MusicBrainz/Server/Controller/WS/2/Collection.pm, t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseGenres.pm, t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/Collection.pm, t/sql/webservice.sql
We added the feature in the last schema change but I completely forgot the WS side of it. This implements it, plus some tests.
Manually, and I added `BrowseGenres` tests. AFAICT this is the only collection browse JSON test, too.
=> MBS-13781: Support browsing genres by collection in the API

lib/MusicBrainz/Server/Controller/Role/Load.pm, root/components/RelationshipsTable.js
Trying to access a paged relationships list with a non-existing link type, such as `/work/8dcffe3f-cb5c-3459-b6d7-0558a2174808?direction=2&link_type_id=277&page=1`, causes a JS `TypeError`. Found in Sentry.
I assume someone was just playing around with the URL params and I cannot think of any other way of getting here than the user fiddling like that. As such, it seems to make sense to block this at the controller level and a 400 BAD REQUEST seems like a good fit.
Manually, on the URL above.
=> MBS-13886: Don't crash on wrong link_type for paged rels

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
This is a database of audiovisual work, including music videos. They have entries for artists, companies (labels) and videos (recordings). Sadly, we cannot determine the entity type from the URL. All languages seem equivalent, so this standardizes to `/en` to avoid duplicates.
Removing the entity name and leaving the numeric ID, tempting as it is, does not work.
Added some tests checking the language standardization, dropping extra crap, and the usual http/www.
=> MBS-13895: Allow Crew United links as otherdbs

lib/MusicBrainz/Server/Data/Editor.pm, lib/MusicBrainz/Server/Data/Utils.pm, lib/MusicBrainz/Server/Form/Utils.pm, t/lib/t/MusicBrainz/Server/Controller/User/Register.pm
There's recently been a bunch of abusive character creation involving the use of unicode tag characters to create multiple accounts with visually the same name. Additionally, we have blocked some other invisible characters from edit notes, but we still allow them in usernames - these can have the same effect.
This moves from simply using `sanitize` to block invalid characters in names to a new `sanitize_username` method, that also runs the pre-existing method `remove_invisible_characters` and a new `remove_tag_characters` method on the username on top of `sanitize`.
Two tests (one per commit / set of characters) have been added to the `User::Register` test.
=> MBS-13857 / MBS-13893: Block invisible characters from usernames

lib/MusicBrainz/Server/Data/Recording.pm, lib/MusicBrainz/Server/Form/Filter/Recording.pm, root/static/scripts/common/components/FilterForm.js, t/lib/t/MusicBrainz/Server/Controller/Artist/Filtering.pm, t/sql/filtering.sql
This allows filtering an artist's recording list by whether the recordings have at least one work linked to them, or they have none.
This is admittedly mostly useful for editing, but it can be *very* useful for that, allowing users to easily find recordings that still need work relationships - it would make it much easier to improve the discographies of prolific classical performers, such as orchestras and conductors, and probably be of use also for popular music.
I did consider making it more complicated (to allow filtering by writer of the linked works, for example) but that's a lot more work and I was afraid that it would get crazy and unwieldy anyway for something like the Berliner Philharmoniker (which is the kind of artist where it could theoretically be useful). So for now, this is …
=> MBS-13870: Add filter for recordings unlinked to works

root/static/scripts/common/components/CommonsImage.js, root/static/scripts/common/components/WikipediaExtract.js
This turns the `WikipediaExtract` file (and the mostly deprecated `CommonsImage` one) from classes to React components, and moves from jQuery to `useCallback`/`useEffect` hooks.
Manually, by loading some files with both in a dev setup, such as `/artist/ae0b2424-d4c5-4c54-82ac-fe3be5453270`
=> Convert Wikimedia classes to components

root/user/UserProfile.js
This fixes anchor links to editor types from editor pages (such as `/user/reosarevok`), which had broken when @Aerozol changed the headers on the doc from plural to singular. It also adds links to missing (now documented) types, "Bot", "Beginner" and "Account admin" (the last of which wasn't even indicated on the page yet for some reason, but really should be).
Manually, by checking my own page (all privs except beginner and bot) and creating a new account locally (beginner) and setting it as a bot.
=> MBS-13896 / MBS-13897: User type link improvements

lib/MusicBrainz/Server/Data/Alias.pm, t/lib/t/MusicBrainz/Server/Data/Alias.pm
Attempting to change the locale of an alias marked as primary to one which already has a primary alias crashes with an ISE.
I noticed the issue is that we were not clearing the previous primary value first for this case, since we were only looking for a changed `primary_for_locale`. In this case the `locale` changes, not the `primary_for_locale` flag. This change ensures `primary_for_locale` is cleared upon either `primary_for_locale` or `locale` changes if `primary_for_locale` is being set or if it was already set and was not overriden by the row changes.
Manually, plus I added a test to Data::Alias. I'm also making Data::Alias less of a mess in a subsequent commit.
=> MBS-13564: Correctly override primary on alias locale change

root/search/components/ReleaseGroupResults.js, root/search/components/ReleaseResults.js
Any combined release group types (such as "Album + Live") show untranslated on release and release group search result pages.
We were only translating expecting primary types, but these are actually combined types. This just uses `l_type_name`, which is what we already use on sidebars to display translations for the same combined types.
Manually, with `/search?query=ticheli&type=release_group&method=indexed` (and the same search for releases).
=> MBS-13866: Show translated RG types on search results

lib/MusicBrainz/Server/Controller/CDTOC.pm
Prior to #2642, the presence of `medium_has_cdtoc` in the stash was used to show this error message. In the new React template, this variable is named `associatedMedium`, but it wasn't being set anywhere.
Tested a real CD lookup on my local development server.
=> MBS-13903: Fix "CDTOC is already attached" error

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Apparently Discogs *also* uses labels for events, on top of places and series. And I thought we did too many things with labels!
Added a Discogs event relationship, and this adds support for it and validates it as needed.
Added an event example as a test, and made sure label links are valid only for the four label-ish entities.
=> MBS-13907: Support Discogs label URLs for events

root/static/scripts/tests/Control/URLCleanup.js
Bluesky has a second type of more permanent, but also more hidden, links. See https://docs.bsky.app/docs/advanced-guides/resolving-identities
Our implementation already supports these (by accident) but this adds a test so that we don't later accidentally break support. These could cause an artist to get duplicate Bluesky links, but given how non-trivial these are to find, the most likely source is something like Wikidata rather than user action. It doesn't feel good to outright block them either since they are more permanent than the default links, so this "sure, I guess you can add them" implementation seems fine enough to me.
The whole point is to add a test
=> MBS-13902: Add test for persistent (did:plc) Bluesky links

lib/MusicBrainz/Server/Report/LonelyPseudoReleases.pm, lib/MusicBrainz/Server/ReportFactory.pm, root/report/LonelyPseudoReleases.js, root/report/ReportsIndex.js, root/server/components.mjs
A pseudo-release should never be in a release group by itself or only with other pseudos.
Made this a release report, rather than RG, to allow it to be filtered by subscriptions.
=> MBS-12708: Report for lonely pseudo-releases

root/cdtoc/AttachCDTocToRelease.js
The release search when trying to attach a CDTOC is limited to the 300 releases best matching the entered name and only from those does it look for mediums with the right number of tracks. This can be confusing: see MBS-12971 where the editor knew the release existed, and did not understand why the search was not returning it.
This changes the message to a more concrete one that specifies users should be as specific as possible, and also directs them to an indexed search they can refine if needed.
Manually to ensure the search link works properly.
=> MBS-13035: Better "no results" message for CDTOC release search

root/static/scripts/edit/utility/diffArtistCredits.js
MBS-13908: Right-to-left credit rendering still broken in medium edits
call `isolateText` on each side of the diff
- edited multiple artists release, see ticket
- ran JS tests
=> MBS-13908: isolate artist credentials in edit diff

root/static/scripts/alias/AliasEditForm.js
Some users seem to just check primary for every alias they add, whether it makes sense or not. It doesn't seem they understand what the field is for. This was always bad, now it's more visible since the wrong aliases end up displayed by the entity name.
This adds a link to the [specific guidelines for when to mark an alias as primary](https://musicbrainz.org/doc/Style/Aliases#Localised_names) to the "This is the primary alias for this locale" checkbox label, in the hopes that it will make users check before using the checkbox. At the very least it will be easier to point out that they should have read them before doing the wrong thing...
Manually visited the alias form and clicked through.
=> MBS-13918: Link to docs from primary alias checkbox label

lib/MusicBrainz/Server/Entity/URL/Bluesky.pm
Since `did:plc` links are just a code, such as "`@did:plc:vqm2zcwhku3u7schrnrh74hb`", it isn't super useful to show it on the sidebar. Just showing "Bluesky" is also more consistent with persistent YouTube channel links, which are shown as just "YouTube" (as opposed to channel names, which are shown by name).
Manually, on `artist/ec972f65-58d5-4d2b-bfff-4011316ec742` (who has a `did:plc` link)
=> MBS-13912: Show just "Bluesky" on sidebar for did:plc links

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Currently, URL relationships for [Naver Vibe](https://vibe.naver.com) aren't validated nor cleaned up to a standard format.
Implement URL cleanup code for Naver Vibe, ensure that links are only added to their respective allowed entities, and rewrite legacy Naver Music links to the new Vibe format.
Tested locally by adding various types of Naver Vibe links to artists and releases. Additionally, unit tests have been written.
Currently, the unit tests fail due to a timeout, I'm not sure what is causing that, since it also says that all tests passed.
=> MBS-13922: Add URL cleanup and validation for Naver Vibe

package.json, script/xgettext.js, yarn.lock
Installing it from git is very likely to be the cause of issues such as https://github.com/metabrainz/musicbrainz-docker/issues/295 which are outside of our control, as we cannot guarantee that yarn will generate an identical tarball on all platforms.
I've published our fork of xgettext-js to the metabrainz org on npm, and have updated our code to reference that instead.
The only change I made to the fork in the meantime was bumping the version of hermes-parser used.
=> Install xgettext-js from org-scoped package rather than git

root/static/scripts/release-editor/fields.js
Make the release editor display an error (and checkbox to bypass) when featured artists appear in seeded track titles. Previously, the error and checkbox were only displayed for manually-entered titles.
The release editor incorrectly treats featured artists as already having been present in seeded track titles. As a result, editors can skip the warning without needing to confirm that the titles are deliberate when seeding releases.
Update `Track`'s constructor to first check that the track already has an ID before treating the supplied title as original for the purposes of initializing the `hasFeatOnOrigTitle` field. Also update `Medium`'s constructor to use `hasOrigFeatOnTitle` rather than `hasFeatOnTitle()` when choosing the initial state for `confirmedFeatOnTrackTitles`.
Manually …
=> MBS-13920 (II): Detect feat. artists in titles when seeding

lib/MusicBrainz/Server/Controller/OtherLookup.pm
CRD 3443 is a valid catalog number we should support, and in fact our search supports it. But by sending 'catno:CRD 3443' we actually search 3443 as a title!
Since there's one use case that quotes break (searching for a regex, where the string must start and end with slashes), we avoid quoting any query that starts and ends with slashes.
=> MBS-6502: Surround catno search with quotes

root/static/scripts/release-editor/fields.js
Add an errorField() call to the release editor to block edit submission if the user didn't click the checkbox to confirm that the appearance of featured artists in track titles was intentional. I think that this was accidentally omitted from ca19708d61a47b29d53991801632db3f6df73dd4.
An error is displayed if the user doesn't confirm that they meant to list a featured artist in a track title, but unlike all of the other errors in the tracklist editor, it doesn't block edit submission.
Add an `errorField` call to register an error if any of the mediums contain unconfirmed appearances of featured artists in track titles.
Checked locally that the "Enter edit" button is now disabled before I check the checkbox (but still enabled after).
=> MBS-13920 (I): Make feat. artist errors block submission

lib/MusicBrainz/Server/Report/KaraokePlusInstrumentalRecordings.pm, lib/MusicBrainz/Server/ReportFactory.pm, root/report/KaraokePlusInstrumentalRecordings.js, root/report/ReportsIndex.js, root/server/components.mjs
A recording should never be marked both karaoke and instrumental: lyrics are relevant for karaoke recordings, and proper instrumental recordings should not be linked as karaoke. This is a relatively common mistake though, and we currently have no good way to find it when it happens.
This adds a report for users to be able to clean up these (it usually requires figuring out which of the options is correct in a case by case basis so a report is a good fit).
By hand, running the report and checking that the recordings in it (for the sample data) seem to fit the requirements indeed.
=> MBS-11916: Report for recordings marked both karaoke and instrumental

flow-typed/npm/react-table_v7.x.x.js, root/hooks/useTable.js
Fixes the following kinds of warnings on pages using `useTable`:
```
Warning: A props object containing a "key" prop is being spread into JSX:
let props = {key: someKey, role: ..., children: ...};
<td {...props} />
React keys must be passed directly to JSX without using spread:
let props = {role: ..., children: ...};
<td key={someKey} {...props} />
```
I did check that react-table assigns its own keys in all of these cases on `/report/KaraokePlusInstrumentalRecordings`.
=> Avoid spreading `key` props in `useTable` hook

root/static/scripts/edit/utility/linkPhrase.js, root/static/scripts/tests/edit/utility/linkPhrase.js
MBS-13925
This was due to `_getRequiredAttributes` inappropriately caching its result when `attributesByRootName` was specified. Results should only be cached when root attributes are being returned.
I've removed the `attributesByRootName` argument altogether and now just merge the relationship-specific attribute names within `getPhraseAndExtraAttributes` instead.
Manual testing + unit tests added in root/static/scripts/edit/utility/linkPhrase.js.
=> MBS-13925: Instrument name erroneously displayed in link type autocomplete

lib/MusicBrainz/Server/Controller/Ajax.pm, lib/MusicBrainz/Server/Controller/Artist.pm, lib/MusicBrainz/Server/Controller/Label.pm, lib/MusicBrainz/Server/Controller/Role/Filter.pm, lib/MusicBrainz/Server/Data/ArtistCredit.pm, lib/MusicBrainz/Server/Data/Label.pm, lib/MusicBrainz/Server/Data/Recording.pm, lib/MusicBrainz/Server/Data/Release.pm, lib/MusicBrainz/Server/FilterUtils.pm, lib/MusicBrainz/Server/Form/Filter/Release.pm, lib/MusicBrainz/Server/Form/Filter/ReleaseForArtist.pm, lib/MusicBrainz/Server/Form/Filter/ReleaseForLabel.pm, root/label/LabelIndex.js, t/lib/t/MusicBrainz/Server/Controller/Label/Filtering.pm, t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm, t/sql/filtering.sql
We have very useful filter tools for all sort of artist pages that have long and unwieldy tables. Another thing that is long and unwieldy: label pages with sometimes thousands of releases. And we cannot filter those.
This extends the release filter from the artist releases page to label index pages, which have very similar lists. Most of the code can be reused, so I moved some into roles.
The only real difference with the artist forms are that ACs are taken for all the releases in the label and that "no label exists" is not a filter option for labels, for obvious reasons.
Tests added, with very small changes from the artist release ones.
While testing this locally I saw we were getting a warning due to the new code to keep ACs when moving around in filters, so I deal with that in the …
=> MBS-13597: Add release filter to label index pages 

admin/MBImport.pl
I'm running a setup to deploy the server docker using helm and using the previous Ubuntu version. I currently get the error when running the createdb.sh 
`mbdump/artist_alias_type
tar: mbdump/artist_alias_type: Cannot change ownership to uid 1000, gid 1000: Operation not permitted`.
More on the issue [here](https://superuser.com/questions/1435437/how-to-get-around-this-error-when-untarring-an-archive-tar-cannot-change-owner)
Added the `--no-same-owner` option to the tar command
I tested this by running the the createdb.sh again and the import tar command was successful.
=> add --no-same-owner option to tar

lib/MusicBrainz/Server/Controller/Statistics.pm, lib/MusicBrainz/Server/Data/Statistics.pm, root/statistics/Editors.js, t/lib/t/MusicBrainz/Server/Data/Statistics.pm
We've gotten requests for "top for last year" editor stats and it seems sensible; one week is for big editing spurts only, and top of all time is basically impossible for anyone who hasn't been editing for 15 years and/or is kinda crazy in the coconut to get a good position on.
This adds `top_yearly` for both editing and voting. For editing, this counts only applied edits (same as yearly and unlike weekly) since a year is a long enough period that the open edits should not make that much of a difference (and if they do, they won't a week later).
Manually, plus I added a test for each to `Data::Statistics` (basically copying the existing ones and fiddling a bit with the edit dates/values).
=> MBS-13763: Add past year stats to the editors statistic page

lib/MusicBrainz/Server/EditSearch/Predicate/Voter.pm
A link such as `/search/edits?conditions.0.args=&conditions.0.field=voter&conditions.0.name=aerozol&conditions.0.operator=%3D&conditions.0.voter_id=463559` causes an ISE when logged in - it seems to be caused by the empty `conditions.0.args=` leading to an empty `WHERE ()` in the query. It seems this can probably only be hit by manually editing the URL (since just deselecting all the vote options removes `args` entirely and was already being caught as invalid).
It seems any argument that is not a valid vote option or "no" (which we use for searching for lack of votes) should just be deemed invalid and reject the search, so this checks the arguments against the valid list and rejects any that don't match.
Manually.
=> MBS-13914: Validate vote arguments for voter edit search

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
VIAF seems to now support language codes for their data URLs. We should not reject them as we do now, but clean them up into the same permalinks we are already using; language is irrelevant for the URI.
Changed a couple of the URLs in the existing tests to include language codes.
=> MBS-13938: Don't reject VIAF links with language code

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
BNF seems to now support language codes for their data URLs. We should not reject them as we do now, but clean them up into the same permalinks we are already using; language is irrelevant for the URI.
Updated two of the existing testing URLs to include language codes - one for each kind of URL in the `clean` method.
=> MBS-13939: Don't reject BnF links with language code

lib/MusicBrainz/Server/Entity/URL/Spotify.pm, root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
We've got several requests to support Spotify songwriter links such as https://artists.spotify.com/songwriter/4wmgHQAAzg3gbnQWSyoMZp
These seem useful but belong separately from usual Spotify links. Other databases seems like the best fit, so using that. Wasn't sure what to use for the sidebar, settled on "Songwriter info at Spotify" but improvements welcome.
Manually (for sidebar text testing) plus added an automated test.
When releasing, transclude the [doc change](https://wiki.musicbrainz.org/index.php?title=Other_Databases_Relationship_Type%2FWhitelist&type=revision&diff=78241&oldid=78211).
=> MBS-13929: Add Spotify songwriter pages to otherdbs whitelist

lib/MusicBrainz/Server/Entity/Work.pm
We need the production server to support the same fields than beta will be adding for works, in order to avoid clashing redis entries causing crashes (this caused issues while releasing beta that meant I had to revert it).
https://github.com/metabrainz/musicbrainz-server/pull/1171
=> MBS-13917: Add new properties to avoid crashes

lib/MusicBrainz/Server/Report/KaraokePlusInstrumentalRecordings.pm
The new `KaraokePlusInstrumentalRecordings` report (https://musicbrainz.org/report/KaraokePlusInstrumentalRecordings) does not support filtering. There's no reason for this, except that I just missed adding it originally.
Use `FilterForEditor::RecordingID` here as with all other recording reports not about Various Artists.
Manually, by subscribing to an artist with recordings in the report and making sure the filter works normally.
=> MBS-13951: Allow filtering KaraokePlusInstrumentalRecordings

root/release/edit/tracklist.tt, root/static/scripts/release-editor/fields.js
Reword tracklist editor warning strings from "used Various Artists **on** some tracks" to "used Various Artists **for** some tracks" and from "featured artists **on** the track titles" to "featured artists **in** the track titles".
Also rename a few variables for consistency.
=> Update prepositions in tracklist editor warnings

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
We already support Utaite/Touhou/VocaDB pages for most other entities (they're closely related sites so we handle them all in the same way), but we did not support their tag (`/T`) links for genres. This just adds that support.
Added a `/T` link to the automated test list.
=> MBS-13950: Support Utaite/Touhou/VocaDB tag pages for genres

lib/MusicBrainz/Server/Controller/Collection.pm, lib/MusicBrainz/Server/Controller/Search.pm, lib/MusicBrainz/Server/Controller/Series.pm, lib/MusicBrainz/Server/Data/Search.pm, lib/MusicBrainz/Server/Data/Series.pm, lib/MusicBrainz/Server/Entity/Series.pm, root/components/list/SeriesList.js, root/layout/components/sidebar/SeriesSidebar.js, root/search/components/SeriesResults.js, root/types/series.js, root/utility/tableColumns.js, t/lib/t/MusicBrainz/Server/Controller/Series/Show.pm, t/lib/t/MusicBrainz/Server/Data/Search.pm, t/lib/t/MusicBrainz/Server/Data/Series.pm
Right now there's no good way of knowing how many items are in a series, other than just counting them by hand. This can be quite annoying for any series with more than a few entries. This is useful for a general idea of how big a series is (in a search for example it helps see what are popular/large series), and for a specific series of known real world size (such as a catalogue) it also can give a general idea of how much content is still missing from the MB entry.
This reuses the general idea of `entity_count` we already had for collections. The `entity_count` for a series is calculated based on the `${entity_type}_series` views. See additional details on the commit messages.
Manually, by checking series sidebars, creating a small series collection and making sure the counts appear, …
=> MBS-13075: Indicate the number of items in a series

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
We only allow `/musicvideo` links from Rate Your Music on recordings because I never knew they had two different URL subpaths for videos depending, I guess, on whether it's an "official music video" sort of thing or just a video with music (`/video`, like the live example from the ticket I added to the test). Both of these make equal sense on MB recordings.
Added one of these to the automated tests.
=> MBS-13960: Allow rateyourmusic /video links on recordings

admin/sql/InsertTestData.sql, lib/MusicBrainz/Server/Controller/Role/EditRelationships.pm, lib/MusicBrainz/Server/Data/Relationship.pm, root/static/scripts/common/utility/doOrLogError.js, root/static/scripts/common/utility/getScriptArgs.js, root/static/scripts/common/utility/storage.js, root/static/scripts/edit/externalLinks.js, root/static/scripts/relationship-editor/components/RelationshipEditor.js, root/static/scripts/relationship-editor/utility/prepareHtmlFormSubmission.js, root/static/scripts/work/edit.js, t/lib/t/MusicBrainz/Server/Controller/Artist/EditExternalLinks.pm, t/lib/t/MusicBrainz/Server/Controller/Artist/EditRelationships.pm
MBS-13959
The simplified cause of this issue was that all relationship/external link editor forms shared the same `sessionStorage` keys. Normally that wasn't a problem, because the keys were only read on POST and overwritten on form submission. The problem occurred when a POST happened with no form submission, while at the same time `sessionStorage` still had data from a previous form. (One way that could happen was being logged out, as the login form performs a POST to the destination endpoint.)
This commit adds a number of mitigations for this issue on both the client and server side:
* On the client side, we now use separate keys for each entity, and make sure to clear them whenever we can. (That's actually a bit more important now that the number of keys could otherwise grow …
=> MBS-13959: Prevent submitting relationships for a different source entity

lib/MusicBrainz/Server/Controller/Edit.pm, lib/MusicBrainz/Server/EditSearch/Predicate/AreaType.pm, lib/MusicBrainz/Server/EditSearch/Predicate/ArtistType.pm, lib/MusicBrainz/Server/EditSearch/Predicate/EventType.pm, lib/MusicBrainz/Server/EditSearch/Predicate/InstrumentType.pm, lib/MusicBrainz/Server/EditSearch/Predicate/LabelType.pm, lib/MusicBrainz/Server/EditSearch/Predicate/PlaceType.pm, lib/MusicBrainz/Server/EditSearch/Predicate/ReleaseGroupPrimaryType.pm, lib/MusicBrainz/Server/EditSearch/Predicate/ReleaseGroupSecondaryType.pm, lib/MusicBrainz/Server/EditSearch/Predicate/Role/EntityType.pm, lib/MusicBrainz/Server/EditSearch/Predicate/SeriesType.pm, lib/MusicBrainz/Server/EditSearch/Predicate/WorkType.pm, lib/MusicBrainz/Server/EditSearch/Query.pm, root/edit/search_macros.tt
This adds a way to filter edit searches by entity type. I implemented this because of a request to filter by the primary type of release groups, but since it's a trivially reusable role, and this seems like a useful filter for every entity type with types, I am adding it for every entity with types. RG secondary types don't use the role (they could in a similar way to `EntityArea`, but I did not see the point of complicating the role significantly for a one-off) but other than that work the same as all other types.
Manually, searching for edits with all kinds of type filters and making sure the results seem sensible.
=> MBS-13771: Filter edit search by entity type

.circleci/config.yml, docker/templates/Dockerfile.tests.m4, root/components/Paginator.js, root/hooks/useTable.js, root/static/scripts/common/components/Filter.js
Our existing HTML validator image is very old, and does not support `rel` for `form`, which I need for https://github.com/metabrainz/musicbrainz-server/pull/3474
Sadly, updating the validator brings with it a bunch of (mostly legit) new issues it finds, so we need to fix those too.
This fixes different issues found by the latest validator, until we hopefully pass all tests.
=> Update HTML validator image and fix newly found issues

root/static/scripts/edit/utility/diffArtistCredits.js
Several elements in `diffArtistCredits` were missing keys and triggering React warnings. I fixed all the ones I saw while testing with some local edits, at least - but I think this might be all of them now anyway.
=> Fix key warnings in diffArtistCredits

lib/MusicBrainz/Server/Data/Release.pm, lib/MusicBrainz/Server/Data/Series.pm
MBS-12826 - Anything that would reorder large release series causes timeouts
Moves some data loading calls out of `Data::Release::series_ordering`, which heavily contributed to the extremely poor performance here.
This patch doesn't exactly make release series reordering fast, but it should prevent timeouts.
I wrote a script that reorders the "Apple Digital Masters" series to test this:
* On test.mb, reordering that series dropped from 87s to 14s.
* On prod.mb, it went from 73s to 11s.
The script:
```Perl
#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/lib";
use Data::Dumper;
use Time::HiRes qw( gettimeofday tv_interval );
use MusicBrainz::Server::Context;
my $c = MusicBrainz::Server::Context->create_script_context(
database => 'READWRITE',
);
my …
```
=> MBS-12826: Speed up release series reordering

lib/MusicBrainz/Server/Data/Utils.pm, t/lib/t/MusicBrainz/Server/Data/Utils.pm
Some low-hanging fruit I found while profiling a release index page. The current implementation of `ref_to_type` is so shockingly inefficient that I can't believe how long it's been like this, considering the impact it has (it had the highest inclusive/exclusive time of any subroutine in the profiling data).
It should be obvious why it was slow, but to show how slow it was, I wrote a script that pushes an instance of every subclass of `MusicBrainz::Server::Entity` onto a list, and then calls `ref_to_type` on all of those instances 1000x each.
Before this commit:
$ ./ref_to_type_perf.pl
14.310254 seconds
After this commit:
$ ./ref_to_type_perf.pl
0.142224 seconds
Now consider that the release page I was profiling from the sample database, dceb6a01-3431-36af-b2e1-6462193bd67c, calls …
=> Speed up `Data::Utils::ref_to_type`

root/components/common-macros.tt
Update the doc_link Template Toolkit macro to concatenate "/doc/" and the supplied argument instead of letting uri_for join them into a path.
This convinces uri_for to not perform URL-escaping, which was breaking URLs with fragments like
/doc/Style/Unknown_and_untitled/Special_purpose_artist#List_of_official_SPAs.
Linking to a specific section of a documentation page doesn't work. The server encodes `#` as `%23`, e.g. <https://musicbrainz.org/doc/Style/Unknown_and_untitled/Special_purpose_artist%23List_of_official_SPAs>.
Surprisingly to me, the server still returns the correct wiki page, but it has a messed-up title (e.g. "Style / Unknown and untitled / **Special purpose artist#List of official SPAs**") and the browser doesn't jump to the requested section.
Make the `doc_link` TT macro …
=> MBS-13967: Make doc_link macro pass literal path

root/release/edit/tracklist.tt, root/static/scripts/common/constants.js, root/static/scripts/release-editor/fields.js, root/static/scripts/release-editor/init.js
Make the tracklist editor display a warning if a track title appears to contain ETI with an incorrectly-capitalized non-title word, e.g. "Remix" or "Version". If the user is a beginner, a checkbox is displayed for them to confirm that the usage is correct.
This check is skipped for releases that are set to a language other than English and for Japan-only releases.
Many new editors are unfamiliar with the style guidelines, creating cleanup work for other editors.
Make the tracklist editor display a warning pointing to the [ETI guidelines](https://musicbrainz.org/doc/Style/Titles#Extra_title_information) if a track title contains ETI ending in "Instrumental", "Live", "Mix", "Remix", or "Version".
If the editor is a beginner, also display a checkbox to make sure that they at least read the …
=> MBS-13711 (I): Warn about improperly-capitalized ETI

lib/MusicBrainz/Server/Connector.pm
We are getting wide error ISEs that hide the real errors sometimes when there are PSQL problems.
While the idea in https://github.com/metabrainz/musicbrainz-server/commit/20640deaa0841d7d55533dc3e7c8a8cbe2722fc1 was correct, the change was too wide in application; it was also decoding errors that did not need it, causing a wide character ISE because of the double decoding.
mwiencek looked into the root causes and said: "We do always get a UTF-8 string. But sometimes it's just a raw byte string (with no UTF8 flag set), and other times it's already been decoded (UTF8 flag on)."
So this checks whether the flag is on, and only decodes the string if it is not.
Manually.
This specific issue can be triggered for testing by changing the host in `DBDefs` to something dumb and utf8ish. I used …
=> MBS-13453: Avoid double-decoding some errors

lib/MusicBrainz/Server/Data/Area.pm, lib/MusicBrainz/Server/Data/Artist.pm, lib/MusicBrainz/Server/Data/ArtistCredit.pm, lib/MusicBrainz/Server/Data/Event.pm, lib/MusicBrainz/Server/Data/Instrument.pm, lib/MusicBrainz/Server/Data/Label.pm, lib/MusicBrainz/Server/Data/Place.pm, lib/MusicBrainz/Server/Data/Recording.pm, lib/MusicBrainz/Server/Data/Release.pm, lib/MusicBrainz/Server/Data/ReleaseGroup.pm, lib/MusicBrainz/Server/Data/Role/GID.pm, lib/MusicBrainz/Server/Data/Role/GIDRedirect.pm, lib/MusicBrainz/Server/Data/Role/Relatable.pm, lib/MusicBrainz/Server/Data/Series.pm, lib/MusicBrainz/Server/Data/URL.pm, lib/MusicBrainz/Server/Data/Work.pm, root/release/edit/tracklist.tt, root/static/scripts/release-editor/fields.js, root/static/scripts/tests/release-editor/actions.js, root/static/scripts/tests/release-editor/common.js, root/static/scripts/tests/release-editor/dialogs.js, root/static/scripts/tests/release-editor/edits.js, root/static/scripts/tests/release-editor/fields.js
Make the tracklist editor display a warning if an apparently-English title capitalizes a short word that should be lowercased. "and", "of", "or", "to", and "the" are checked. A confirmation checkbox is displayed for beginner editors.
Beginner editors often import releases from Discogs (where the [First Letter Of Each Word Is Capitalized](https://support.discogs.com/hc/en-us/articles/360005006334-Database-Guidelines-1-General-Rules#Capitalization_And_Grammar)) without updating titles to follow [MusicBrainz's language-specific guidelines](https://musicbrainz.org/doc/Style#Language_specific_guidelines). This creates cleanup work for other editors.
Use a similar approach to #3504 to display a warning pointing to the English style guidelines if any of the above words appear in the middle of a …
=> MBS-13711 (II): Warn about capitalized short words in titles

lib/MusicBrainz/Server/Controller/Area.pm, lib/MusicBrainz/Server/Controller/Artist.pm, lib/MusicBrainz/Server/Controller/Label.pm, lib/MusicBrainz/Server/Controller/Place.pm, lib/MusicBrainz/Server/Controller/Recording.pm, lib/MusicBrainz/Server/Controller/Release.pm, lib/MusicBrainz/Server/Controller/ReleaseGroup.pm, lib/MusicBrainz/Server/Controller/Role/Tag.pm, lib/MusicBrainz/Server/Controller/Work.pm, lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Role/Genre.pm, root/layout/components/sidebar/SidebarTags.js
Another small thing I noticed while profiling the Nine Inch Nails artist page from the sample database. It saves around 16ms per request there locally, but that may vary depending on the number of tags/genres the artist has.
1. `user_tags_json` was unused.
2. We don't have to load genres on the tags, because we can access them via `genre_map` in the stash.
I tested browsing various entity pages that have tags/genres in the sidebar. Also made sure the automated tests for JSON-LD still pass.
=> Remove some unnecessary code from `Controller::Role::Tag`

root/components/forms.tt
Update the type_bubble TT macro to say "If the entity doesn't seem to match any type" rather than "If the work ...", since it's used for many non-work entity types.
=> Make type_bubble() refer to "entity" rather than "work"

root/layout/components/sidebar/ReleaseSidebar.js
The loadArtwork.js script wasn't added to the `ReleaseSidebar` component in 81eb6ffc74cdd7294ed151aceab1db0b509922e8.
Tested locally. I previously had custom DBDefs settings for local artwork display, so didn't notice it before.
=> MBS-13978: Fix cover art display in the release sidebar

root/static/styles/forms.less
Update the CSS for documentation bubbles to reduce min-height and remove first paragraphs' top margins and final paragraphs' bottom margins.
There's excess blank padding at the bottom of documentation bubbles, especially when they just contain a single line of text. Some bubbles (e.g. sort name on `/artist/create`) also have excess top padding.
Shrink bubbles' `min-height` from 64px to 54px (a minimum height is still needed to ensure the bubble extends all the way down to its arrow), and set `margin-top` to 0 for the first paragraph child in the bubble and `margin-bottom` to 0 for the final one.
**Before (single line):**
**After (single line):**
**Before (multiple paragraphs):**
**After (multiple paragraphs):**
Manually checked appearance of bubbles in the artist and release forms.
=> Decrease excess vertical padding in documentation bubbles

lib/MusicBrainz/Server/Controller/Role/Create.pm, lib/MusicBrainz/Server/Controller/Role/Edit.pm, root/release_group/edit_form.tt, t/selenium.mjs, t/selenium/Release_Group_Edit_Form.json5
The `$model eq 'Recording'` checks added in 020bcef06bb0c7886378beb737f413f1086ae965 were clearly insufficient as recordings are not the only entity with artist credits.
Added a t/selenium/Release_Group_Edit_Form.json5 test, since we were apparently lacking coverage in this area. (It also tests the `Controller::Role::Create` case by triggering a form error, and ultimately checking that the AC is preserved.)
=> MBS-13979: Beta: Artist data lost when editing release group

lib/MusicBrainz/Server/Controller/Release.pm, lib/MusicBrainz/Server/Controller/Role/Merge.pm, lib/MusicBrainz/Server/Form/Merge/Release.pm, root/release/ReleaseMerge.js, root/types/forms.js, t/lib/t/MusicBrainz/Server/Controller/Release/Merge.pm
We used to have a checkbox before NGS came which allowed editors to enter a merge for the associated release groups when merging releases, and I still don't know why it was removed. I *think* it's because ocharles thought it was better to just let orphaned RGs get autoremoved, but that goes against the whole merge rather than delete ethos.
Readding the checkbox would allow editors to stop leaving orphaned RGs behind, without them having to go merge them by hand separately (which is enough effort to often think "you know what, whatever, they'll be garbage-collected anyway").
This (re-)adds a checkbox "Also merge the associated release groups" when merging releases. If selected, a second "Merge release groups" edit will be entered when submitting the "Merge releases edit" (under the …
=> MBS-2349: Allow merging RGs when merging releases

lib/MusicBrainz/Server/Data/Relationship.pm, lib/MusicBrainz/Server/Report/SeriesContainingDuplicates.pm, lib/MusicBrainz/Server/ReportFactory.pm, root/report/ReportsIndex.js, root/report/SeriesContainingDuplicates.js, root/report/types.js, root/server/components.mjs, root/utility/tableColumns.js
On top of https://github.com/metabrainz/musicbrainz-server/pull/1659 
This adds a report for duplicate items inside series. In order to determine duplicates, the link order is ignored, but the number attribute is not. As such, this shows either entities which are in a series twice with the same number attribute, or without a number attribute at all.
Manually with sample data (manipulated to add more dupe entities).
=> MBS-13957: Add a report for duplicate items in series 

root/cdtoc/AttachCDTocConfirmation.js, root/components/common-macros.tt, root/static/scripts/common/components/MediumDescription.js, root/static/scripts/common/entity.js, root/static/scripts/common/hooks/usePagedMediumTable.js, root/static/styles/layout.less
The current way (CD 1, DVD 2) kinda makes it sound like there should be a DVD 1.
For release tracklists, this just shows the medium position at the beginning of the header, then shows only medium format and name after the expand/collapse arrow.
Everywhere else, such as on edits, or on the relationship lists under the release, `Medium 1 (CD)`, `Medium 2 (DVD)`, etc. seems a lot less confusing and not too repetitive / silly.
=> MBS-11129: Display mediums as Medium # (Format)

lib/MusicBrainz/Server/Test/HTML5.pm, root/layout/components/sidebar/RecordingSidebar.js, root/layout/components/sidebar/WorkSidebar.js, root/medium/tracklist.tt
For now a draft to see how much if any test screaming this still causes.
=> Don't ignore disallowed children HTML errors

admin/config.search-indexes-dump.sh
The path for collections backup in SolrCloud is not the same for the versions 7 and 8/9/10, thus preventing to use the same key to query both versions for backup during the upcoming transition period related to SEARCH-685.
Separate keys for each version. This is only for a transition period. Using a temporary name for the old version.
Manually deployed to the production `search-indexes-dump` container.
1. It goes with deployment pull requests.
=> Separate SolrCloud 7 key

root/artist/edit_form.tt, root/components/forms.tt, root/label/edit_form.tt, root/place/edit_form.tt, root/release/edit/information.tt, root/static/scripts/artist/edit.js, root/static/scripts/edit/MB/Control/Area.js, root/static/scripts/edit/MB/Control/ArtistEdit.js, root/static/scripts/edit/MB/Control/Bubble.js, root/static/scripts/label/edit.js, root/static/scripts/place/edit.js, t/selenium/MBS-9941.json5
Update the artist, label, and place editing forms to display documentation bubbles for all fields.
Also update the initializeArea function and the area_bubble macro so that multiple area bubbles can be used in a single page.
#3510  updated the release editor's information tab to display documentation bubbles for all fields, but many other forms still lack documentation bubbles.
Add missing bubbles to the artist, label, and place forms.
The only tricky part of this was accommodating forms (artist and place) that have multiple area fields that should display different documentation. These forms previously used a single bubble for all their area fields, and the `initializeArea` function didn't support showing an initial documentation string before any area has been selected. I renamed the …
=> MBS-13980: Add artist, label, and place doc bubbles (I)

lib/MusicBrainz/Server/Data/Work.pm
Work authors and artists in inline search have no primary alias displayed. This is annoying for stuff like Russian composers.
For work authors, this just displays the (already loaded) author primary alias in a parens.
Work artists are artist credits, not artist entities, so we would need to extract the artists instead and display those (this is still not done, and moved to MBS-13991).
Manually
=> MBS-13985: Show inline primary alias for work authors 

root/release/edit/tracklist.tt
**finalsummer** requested to indicate to beginner users some of the most common exceptions to the capitalization guideline, for cases where they might otherwise be prompted by the new warning to change things incorrectly
@Aerozol proposed a simple new line, "Common exceptions are artist intent and Japanese releases," with the relevant links. This is short enough not to distract the users too much while still giving them enough info when relevant.
Manually, checked it shows properly and links work.
=> Add short note about exceptions to new capitalization warning

root/release_group/ReleaseGroupIndex.js, root/utility/tableColumns.js
Releases and RGs with overlong symbol names cause awful horizontal scroll, for example with `/release-group/3c2b9f73-9ff6-4b87-a52f-4ee8e1803a5a` and `/artist/ab2d7e75-dbaa-45f7-97df-1ebbd6475fb9`.
Use the existing class `wrap-anywhere` in `defineNameColumn` for tables using `react-table`, and also in `ReleaseGroupIndex` which does its own thing for now. This solves the horizontal scroll issues in these pages, and hopefully neither of these will lead to over the top wrapping anywhere else than on very small screens, in which case our display is going to suck either way.
We have had two-steps-forward-one-step-back situations on wrapping quite a bit (https://github.com/metabrainz/musicbrainz-server/pull/2561) and ideally we'd have something like "wrap only if a word is longer than X chars" …
=> MBS-13982: Wrap overlong release and release group titles in tables

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
We were only dropping "global" here but there's not only that but also all sort of other country codes such as "us" that can appear here. In fact, we tested and you can write literally anything there, even with multiple slashes (see last test example) and it happily gives us the same result. As such, this just drops any text before the relevant code section.
Added a couple extra tests with different extra sections.
=> MBS-13977: Ignore country codes in yesasia.com links

root/static/scripts/edit/externalLinks.js, root/static/scripts/tests/release-editor/seeds/mbs-13993.html, t/selenium.mjs, t/selenium/MBS-13993.json5
MBS-13993
Group the existing links (ones with a relationship ID) by type-url pairs, and filter out any seeded links (ones without a relationship ID) that duplicate an existing type-url pair.
Only the added Selenium test.
=> MBS-13993: Ignore seeded external links that duplicate existing ones

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
Apparently Patreon adds a `/c/` segment to the URLs when logged in, which meant we were actually cleaning those up to just `https://www.patreon.com/c` and dropping the actual username.
This just drops `/c/` from the URLs if present.
Added a test, also checked just in case that we don't break `https://www.patreon.com/c` if someone *does* want to link to that guy.
=> MBS-13989: Drop /c/ Patreon URL segment

script/reset_selenium_env.sh
* If a Selenium test's SQL script fails, it currently does so silently without causing the test to fail immediately.
* When this happens, it also doesn't roll back the changes.
Adds two flags to the `psql` call:
* `-v ON_ERROR_STOP=1` 
* `--single-transaction`
Running `./admin/psql SELENIUM -- --single-transaction -v ON_ERROR_STOP=1 < t/sql/mbs-10510.sql` locally and checking the exit code when the script has or doesn't have errors.
=> Propagate `EXTRA_SQL` failures in script/reset_selenium_env.sh

lib/MusicBrainz/Server/Report/DuplicateEvents.pm
The DuplicateEvents report only looks at matching start dates, not matching end dates, so it is currently suggesting festivals as duplicates of the first day of the same festival.
There's no great reason why we would not look at end date as well, so this just does that. The only reason would be for cases where a beginner adds a duplicate *and* doesn't set an end date, but that's two mistakes in one and adding the end date is trivial with the copy button, so hopefully it's not too common (and there's a lot of these false positives in the report at the moment).
Manually locally by adding these sorts of "duplicate" events and checking they disappear from the report after the changes.
=> MBS-13997: Check both start and end date in DuplicateEvents 

root/components/forms.tt, root/recording/edit_form.tt, root/release/edit/information.tt, root/release_group/edit_form.tt, root/series/edit_form.tt, root/static/scripts/artist/edit.js, root/static/scripts/edit/MB/Control/Bubble.js, root/static/scripts/label/edit.js, root/static/scripts/place/edit.js, root/static/scripts/recording/edit.js, root/static/scripts/release-group/edit.js, root/static/scripts/series/edit.js, root/static/scripts/work/edit.js, root/work/edit_form.tt
Update the recording, release group, series, and work editing forms to display documentation bubbles for all fields.
Some entity editing pages were still missing documentation bubbles for most or all of their inputs.
Add bubbles using the strings that @reosarevok, @Aerozol, and I worked out in a shared doc.
I also added a new `initializeExternalLinksBubble` helper function for attaching a bubble to the external links component, and updated `edit/MB/Control/Bubble.js` to include `jquery-ui.custom.js` since it depends on it for positioning bubbles and the recording page wasn't including it otherwise.
Loaded all the forms and checked that bubbles are displayed when inputs are focused.
=> MBS-13980: Add recording, RG, series, and work bubbles (II)

root/artist/edit_form.tt
Prevent the artist form's begin/end date and area doc bubbles from having a margin above the first paragraph.
#3509 tried to remove extra padding at the top of bubbles, but I just noticed that it didn't affect some of the bubbles later added by #3516:
Put all of the alternate strings inside of spans nested within the same paragraph so the `p:first-child` selector will work even when the first string isn't selected:
Manually checked that the bubbles look less ugly now.
=> Remove extra top margin in artist begin/end bubbles.

admin/sql/CreateFunctions.sql, admin/sql/CreateMirrorOnlyTriggers.sql, admin/sql/CreateTriggers.sql, admin/sql/updates/20250408-mbs-13964-all.sql, admin/sql/updates/schema-change/30.all.sql, t/pgtap/first_release_dates.sql, upgrade.json
MBS-13964
When releases are merged with the "append" strategy, then mediums are moved by updating their `release` column. (See the `Data::Release::merge` method.)
Since this affects the releases a recording appears on, we need a trigger on the `medium` table to update `recording_first_release_date` whenever a `medium.release` column is updated.
Adds the necessary trigger. The upgrade script also takes care of truncating all existing data in the materialized table, so that it can be recalculated via the admin/BuildMaterializedTables script.
* Updated t/pgtap/first_release_dates.sql.
* Ran t/script/CheckSchemaMigration.sh per HACKING.md.
=> MBS-13964: Some recordings are missing a first release date

root/area/AreaArtists.js, root/area/AreaEvents.js, root/area/AreaLabels.js, root/area/AreaPlaces.js, root/area/AreaReleases.js, root/artist/ArtistEvents.js, root/artist/ArtistIndex.js, root/artist/ArtistRecordings.js, root/artist/ArtistReleases.js, root/artist/ArtistWorks.js, root/instrument/InstrumentArtists.js, root/instrument/InstrumentRecordings.js, root/instrument/InstrumentReleases.js, root/isrc/Index.js, root/iswc/Index.js, root/label/LabelIndex.js, root/place/PlaceEvents.js, root/release_group/ReleaseGroupIndex.js, root/report/DuplicateArtists.js
This reverts commit 9b47fff01877ffb2cd3c9255f056737c5e81e127. The `returnTo` is useless for *working* merges, but it still has some use when cancelling a merge and when only one entity is selected so a merge cannot yet happen.
The same page will effectively end up open twice if the merge was opened on a new tab, but it doesn't feel like the alternative (the new tab ending in `/search` or the front page) is any better anyway.
Manually, did not test all pages but it should be straightforward.
=> MBS-14002: Fall back to the same page on incomplete merges

root/static/styles/widgets.less
This CSS was being overriden by `table.row-form label` now that it was no longer just added inline to the autocomplete, meaning the label was shown in places where we don't want it.
It seems `row-form` is a rare class and the only affected case of the label being overriden is `#ac-source-single-artist-label`, so we can just use the id selector directly and avoid the issue.
Manually, both on `/release/add` (which should not have a label but did) and `/account/edit` (where the label should still appear for the `Location` field).
=> MBS-14001: Avoid Autocomplete2 CSS being overriden

admin/sql/CreateFunctions.sql, admin/sql/updates/20250425-mbs-13966.sql, admin/sql/updates/schema-change/30.all.sql, t/pgtap/first_release_dates.sql, upgrade.json
MBS-13966
The `set_release_group_first_release_date` function has been modified to select from `release_group` first, and then `LEFT JOIN` with release, in order to include RGs with no releases. I believe this is only triggered when the last release is moved out of an RG. (There should be no such issue when deleting the last release, since that implies its release events will be removed *first*, and the RG won't be empty yet.)
Note: The `artist_release_group` table depends on these values, but we're already clearing that table as part of MBS-9253, and will require users to run admin/BuildMaterializedTables again after upgrade.sh has completed.
There is a constraint trigger, `apply_artist_release_group_pending_updates`, on `release_group_meta` which calls …
=> MBS-13966: Calculate first release dates for empty release groups

lib/MusicBrainz/Server/Data/WikipediaExtract.pm, lib/MusicBrainz/Server/Filters.pm, root/static/scripts/common/i18n/expand2react.js, t/lib/t/MusicBrainz/Server/Controller/User/Edit.pm, t/lib/t/MusicBrainz/Server/Data/WikipediaExtract.pm, t/lib/t/MusicBrainz/Server/Filters.pm
MBS-14000: annotation right-to-left rendering
Wrap content in <bdi> tags for bidirectional text handling
Verified bidirection text is rendered correctly in a local dev server.
Added unit tests.
=> MBS-14000: support bidrectional text in annotations and wikipedia extracts

admin/sql/updates/20241125-mbs-13832.sql, admin/sql/updates/schema-change/30.all.sql
The upgrade script for MBS-13832 currently aborts with the following error when run against the production schema:
ERROR:  cannot change name of view column "approved" to "filesize"
HINT:  Use ALTER VIEW ... RENAME COLUMN ... to change name of view column instead.
This is due to MBS-14014.
Any database created on/after schema 25 (which was in 2017) will have these filesize columns in the view already. Since this view is for internal use, the best option is to simply drop and recreate it. (It can't be replaced without dropping it first, as view columns can't be changed that way.)
CheckSchemaMigration.sh
=> MBS-14014: Drop and recreate `cover_art_archive.index_listing`

admin/BundleSearchIndexesDump, admin/BundleSolrBackup, admin/RunSolrBackup, admin/config.default.sh, admin/config.solr-backup.sh, admin/cron/daily-solr-backup.sh, bin/rsync-solrcloud-backups, docker/musicbrainz-solr-backup/crontab, docker/scripts/create_log_directories.sh, docker/templates/Dockerfile.solr-backup.m4, lib/DBDefs/Default.pm
With SEARCH-685 (Upgrade to Solr 9), a new format is required for backing up collections with SolrCloud for initializing with MusicBrainz mirrors.
This patch allows to make SolrCloud 8.9+ collections (formerly named as search indexes) backups available for use with MusicBrainz live mirrors. It mainly adapts the container and scripts that were used to dump Solr 7 search indexes.
The main differences are:
* Naming (from "search index dump" - which was often mixed with Postgres terms - to "collection backup" - which comes from the SolrCloud docs.)
* ZooKeeper information are made available in the  `zk_backup` directory (information about nodes are already available through public Grafana.)
* Files hierarchy within the archive:
* SolrCloud backup directory
(named after entity type)
(contains …
=> Backup SolrCloud 9 collections for live mirrors

admin/sql/updates/20250425-mbs-13966.sql, admin/sql/updates/schema-change/30.all.sql
MBS-14032
A query in the upgrade script for MBS-13966 performs a join with `release_first_release_date`, but this table may not have any contents, as it's an optional build step (via admin/BuildMaterializedTables).
While running admin/BuildMaterializedTables beforehand is a possible workaround, it's better if upgrade.sh doesn't have any other external requirements. The solution here is to build a temporary copy of the table (which is dropped on commit). In production, building this table only takes around 8s.
In addition, truncate the `artist_release_group_pending_update` table, because the entries are pointless (we require users to rebuild this table in full after the upgrade anyway).
I tested the new script locally and against the production DB (in a ROLLBACK commit); the final `UPDATE` …
=> MBS-14032: Build temporary `release_first_release_date` table for MBS-13966

docker/config/services/dev.musicbrainz-server.json, docker/musicbrainz-test-database/DBDefs.pm, docker/musicbrainz-tests/DBDefs.pm, docs/database_schema_diagrams/write_graphs.pl, lib/DBDefs.pm.sample, lib/DBDefs/Default.pm, t/script/CheckSchemaMigration.sh
We forgot for the third time in a row that:
`DB_SCHEMA_SEQUENCE` should point to 30 following the schema change today.
`ACTIVE_SCHEMA_SEQUENCE` is currently unused, but should also point to 30.
* Bump both of these values to 30.
Untested changes copied from the pull request https://github.com/metabrainz/musicbrainz-server/pull/3276 copied from the pull request https://github.com/metabrainz/musicbrainz-server/pull/2940 copied from the commit https://github.com/metabrainz/musicbrainz-server/commit/0b7ff5556524e68371a38734eee6d86d18ceffee.
Checked that other occurrences of `28` and `29` are valid (excepted for diagrams which should be updated through MBS-14037).
* Added this task to the checklist we used this year and which is usually copied for the next year, so that, hopefully, it should …
=> MBS-14031: Bump DB_SCHEMA_SEQUENCE, ACTIVE_SCHEMA_SEQUENCE to 30

admin/BundleSearchIndexesDump, admin/BundleSolrBackup
The `MBDump` package doesn't use `Exporter`.
--
This should fix the `Undefined subroutine &main::gpg_sign called at ./admin/BundleSearchIndexesDump line 188.` failure seen in `~/log/daily-search-indexes-dump/2025-05-24T16\:10\:01Z.log` in musicbrainz-search-indexes-dump.
`gpg_sign` should probably be moved to `Script::Utils`, but this change was easier to test.
@yvanzo I noticed the musicbrainz-solr-backup container already had these changes, but not musicbrainz-search-indexes-dump (until I applied them manually). Not sure if there are other local changes there we should commit properly.
=> Fix `gpg_sign` function calls

lib/MusicBrainz/Server/Data/Utils.pm
An ended alias is no longer current, and as such it should not be chosen by `find_best_primary_alias` even if it is marked as a primary alias for a relevant locale.
We might want to make it so that setting ended unsets primary, since ended aliases probably should not be considered primary at all, but even if we do that having this as a fallback still makes sense. I opened MBS-14049 (and a forum discussion) for that potential change.
Manually, making sure that the fallback is still shown after marking the otherwise most appropriate alias as ended. Also added MBS-14050 to add some proper tests for `find_best_primary_alias`, since it seems to have none at the moment.
=> MBS-14041: Don't display ended primary alias by entities

lib/MusicBrainz/Server/Controller/Role/Alias.pm, lib/MusicBrainz/Server/Form/Alias.pm
As far as I can tell this is entirely unused since 10 years ago with commit 4762b076d36ec786d2156ec4958d1cf061d0be68
=> Remove unused model_to_search_hint_type_id

lib/MusicBrainz/Server/Controller/Artist.pm, lib/MusicBrainz/Server/Controller/Label.pm, lib/MusicBrainz/Server/Controller/Place.pm, lib/MusicBrainz/Server/Controller/Work.pm, root/static/scripts/common/components/Relationships.js
We had never updated the list of entity types that are displayed in many places where we have restrictions, so genre relationships for artist, label and place ("named after" ones) were not being displayed. 
Add `genre` to the list of related entity types loaded / displayed for artist, label, place and work (I expect we will add "named after" to works eventually and I see no reason why we would want to require another patch for *those* to show).
Manually, checking that the example relationships for `/relationship/cac1064d-1605-4d41-ac6d-040915480eb5`, `/relationship/b80f8b51-2212-415a-9ed1-bb5636b96d02` and `/relationship/ee182e02-eef7-43ae-b99c-eee1ed60ebc2` appear on the relevant entity pages.
=> MBS-14024: Show genre rels on more places

lib/MusicBrainz/Server/Report/PseudoReleasesWithCoverArt.pm, lib/MusicBrainz/Server/ReportFactory.pm, root/report/PseudoReleasesWithCoverArt.js, root/report/ReportsIndex.js, root/server/components.mjs
Pseudo-releases should never have cover art permanently - only until an official release has been added. This just lists any pseudo-releases with cover art, since the art always needs to be removed, moved to an existing official release, or moved to an official release after adding it.
Tested the query on `isaac` to make sure it works, since I have no CAA on my local setup.
=> MBS-14021: Report for pseudo-releases with cover art

package.json, yarn.lock
On top of https://github.com/metabrainz/musicbrainz-server/pull/3489
https://github.com/facebook/flow/releases/tag/v0.266.0 causes a lot of errors again so updating as far as is trivial.
=> Update Flow to 0.265.3

lib/MusicBrainz/Server/Data/Utils.pm, lib/MusicBrainz/Server/Validation.pm, root/static/scripts/edit/utility/isInvalidEditNote.js, root/static/scripts/release-editor/init.js, root/static/scripts/release/components/ReleaseRelationshipEditor.js
There's already a check at the `FormHandler` level which means trying to submit the relationship editor with an invalid edit note is blocked, but the error is returned as an alert popup (which is not super user-friendly) and ends up spamming sentry.
This reuses the same code we use in the release editor to block the submission at the Javascript level, so that the error is shown in a more reasonable way and already before the user tries to submit.
In a separate commit, I actually block submission on the release editor as well in any cases where the edit note is invalid. We were doing this only for adds but not edits so far because we implemented it the same way as we do for missing edit notes (which are only required for adds).
Manually, both on the release editor and the relationship …
=> MBS-14048: Block relationship editor submission if note is invalid 

lib/MusicBrainz/Server/Controller/OAuth2.pm, t/lib/t/MusicBrainz/Server/Controller/OAuth2.pm
The oauth implementation already accepts any localhost callback if the app is of type "installed application". Extend this to also support the IPv4/IPv6 addresses for the loopback device.
Background: Picard 3 will consistently use 127.0.0.1 for the local server access. Currently it is a mix of localhost and 127.0.0.1 depending on use case. See also https://github.com/metabrainz/picard/pull/2656
Treat `localhost`, `127.0.0.1` and `[::1]` as equivalent in the callback URI check for app type "installed application".
This is unrelated to any future change to the new MB oauth system. We will do this switch for Picard once the new oauth2 URLs are considered stable and will not change anymore.
=> oauth2: accept loopback IPs for installed applications

root/static/scripts/guess-case/utils/titleString.js, root/static/scripts/tests/GuessCase.js
Most English style guides seem to specifically say that words such as 'Em and 'Til *should be uppercased* since they are contractions of words that would themselves be uppercased. People in the community have asked to change this often, and there's no reason that I can find why we do it (we've just always done it for at least the last 15 years).
Remove the special-casing for *'em*, *'til*, *'way*, *'round*. Additionally, this drops the one-letter *'s* and *'d* checks from the regex since they should never be hit, we already lowercase all one-letter words after apostrophes in the previous check.
I added a couple tests to make it harder for us to re-break these in the future. Didn't test manually further than that.
=> MBS-3193: Simplify after-apostrophe guess case

admin/RemoveEmptyAccounts.pl, admin/cron/monthly.sh
This allows removing editors who haven't logged in for over a year, have no verified email, and have never used
pretty much anything in the DB. There's around 700k of those, so a very significant chunk of our users, and many might be dormant spammers.
=> MBS-9356: Add script to remove completely empty editors

root/layout.tt, root/layout/components/Footer.js
It seems sensible in order to always have a place to check whether there is something being tested in beta, even if the user has dismissed the banner. This adds a small `See all tickets in beta testing.` link (pointing to https://tickets.metabrainz.org/issues/?filter=10715) when `IS_BETA` is set.
Manually, in the front page (React) and Add artist (TT), with `IS_BETA` set and unset in `DBDefs`.
=> MBS-14006: Link to tickets in review in beta footer

lib/MusicBrainz/Server/Controller/Admin.pm
MBS-14081
As the title says, we're not terminating any existing Discourse sessions after a user is marked as a spammer.
Calls the `/discourse/log_out` endpoint if the spammer flag was set in the `/admin/user/edit` form values.
Mostly untested, as it requires an actual Discourse setup. However, I did verify that the `$form_values->{spammer}` condition is met when the flag is set.
=> MBS-14081: Log out accounts from Discourse after they've been marked as spam

root/static/scripts/label/index.js
The label filter button does nothing
Just add `components/Filter` to `scripts/label/index.js`, which either I had somehow missed last time or we broke later.
Manually, making sure the filter now shows and works.
=> MBS-14100: Properly hydrate label filter

lib/MusicBrainz/Server/Data/Release.pm, t/lib/t/MusicBrainz/Server/Controller/Release/Merge.pm, t/sql/release.sql
We are blocking unambiguous recording merges as ambiguous. The error reported was on a SACD release where the same recording appears on both the CD and the SACD layers. Despite the fact that both were going to be merged into a single other recording (itself also appearing on both layers on the destination CD), the merge was detected as ambiguous.
AFAICT we were giving the `ambiguous_recording_merge` error in every case where the same recording would get merged into two tracks in the destination release, regardless of whether the two tracks shared a recording so there was no actual ambiguity.
This checks that there's actually more than one recording ID among the destination recordings before screaming. 
Added two tests, one for each case, to `Controller::Release::Merge`.
=> MBS-14104: Check if merge recordings are really ambiguous

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
New IRCAM work links are just `/work/$work_name` (e.g. https://brahms.ircam.fr/fr/work/luci) and were being blocked by our current code. This detects them and cleans them up as work links.
Added a test to the list and made sure old links still work since they can still be found as search results and whatnot and there's no trivial way to convert one to the other (they don't even redirect yet).
=> MBS-14107: Support new style Brahms/IRCAM work links

lib/MusicBrainz/Server/Controller/User.pm
When we rename a user, their remember_login cookie still points to their old, no longer existing username. That means we were trying to log a non-existing user if their session had expired, causing an ISE.
This makes sure the user we're trying to log in actually exists. Renamed users with expired sessions will still have to log in again, but at least they won't get an ISE before that; logging in again is not a big issue anyway since that's the first thing I would tell them to do to propagate the change to LB anyway.
Manually, by logging in with a random use with "remember me" checked in my local server, deleting the user's session cookie by hand, then renaming the user in incognito and reloading the page the user was on.
=> MBS-14110: Don't try to log in using outdated username

lib/MusicBrainz/Server/Data/Event.pm
The most interesting events for most users are usually the ones in the near future or at least the ones that happened fairly recently. This sorts the events by descending date and time, ensuring that the ones without any date still sort last.
Checked `/area/74e50e58-5deb-4b99-93a2-decbb365c07f/events` (which includes a null-date event and is the reason I went with `NULLS LAST`) and some artists and places clicking through from there.
=> MBS-14084: Sort event lists by newest first

lib/MusicBrainz/Server/Report/ReleasedTooEarlyDigital.pm, lib/MusicBrainz/Server/ReportFactory.pm, root/report/ReleasedTooEarlyDigital.js, root/report/ReportsIndex.js, root/server/components.mjs
This adds a report for digital releases released before 1999. The cut year is picked because it's the year Sony launched the first major-label backed digital store.
1999 is not a good fit for the earliest date at the medium format level, since we do know that digital releases existed before that. But it seems like a good enough limit for a report under the assumption that most entries will be wrong but some will be correct.
The goal of this report is to help find and fix digital imports that are filed under the year of their original physical release, which is not rare; plenty of Spotify releases "from the 1960s" exist.
Manually, making sure that quite a few results come up even with the sample data.
=> MBS-14114: Report: Digital releases released too early

lib/MusicBrainz/Server/Controller/Search.pm, lib/MusicBrainz/Server/Data/Area.pm, lib/MusicBrainz/Server/Data/Search.pm, root/search/components/PlaceResults.js
Place search results only provide the basic area for the place. In many cases, this is not super useful information to be sure the place is the right one. For example, the MBS-14005 example is in "York" - not UK, but a district of Toronto. But nothing about Toronto or Canada is shown in the search results, so a user might well skip it thinking it has nothing to do with what they are looking for.
For inline search, our code already tried to load the containment - but we had broken it in a previous commit so that nothing was ever loaded. The first commit just fixes that.
For normal search, this just loads the data for both direct and indexed search results and changes the area column to display containment.
Manually in both inline and normal search, both indexed and direct.
=> MBS-14005 / MBS-14079: Show containment for place areas in search (inline and not) 

.github/workflows/ci.yml, package.json, root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js, yarn.lock
The current code used to match a URL to a particular cleanup entry is quite inefficient: it works by testing the URL against every possible `match` RegExp in every entry, instead of doing that on only the entries that are relevant. We currently have 219 cleanup entries, many with multiple `match` RegExps.
This inefficient matching routine is performed (1) multiple times per keystroke, and (2) for every single link in the external links editor, during every state change, even for links that aren't modified. For example, clicking on an 'x' to remove a relationship will cause a state change that ultimately constructs a new `URLCleanup.Checker` instance for every link in the list. While this redundant work could be prevented on its own without improving the matching performance, I believe …
=> MBS-14119: Improve URL cleanup matching performance

docker/musicbrainz-tests/run_selenium_tests.sh, package.json, t/sql/filtering.sql, t/sql/mbs-10188.sql, t/sql/selenium.sql, t/sql/vote_and_note_selenium.sql
t/selenium/Vote_And_Note_Submission.json5 is broken (along with a couple other tests), and the failures are not being reported by GitHub Actions.
This fixes the exit code propagation in run_selenium_tests.sh, and then fixes some problematic SQL under t/sql/.
CI
=> Break and unbreak selenium

lib/MusicBrainz/Server/Controller/Release.pm, t/lib/t/MusicBrainz/Server/Controller/Release/Merge.pm
When someone merged several releases in the same RG into another in a second RG and selected "merge RGs",
the RG would be added to the merge once for each release.
This actually makes sure the `old_entities` we are merging are unique, on top of the existing check to make sure they are different from the RG we are merging into.
Added a test merging two releases in  the same RG into a third in a second RG and ensuring that only one RG is being listed in the merge from section in the edit.
=> MBS-14124: Only try to merge each RG once

root/static/scripts/edit/URLCleanup.js, root/static/scripts/tests/Control/URLCleanup.js
MBS-14130: ACUM albums should link to release group instead of releases
move ACUM album links to release groups
JS unit tests
=> MBS-14130: ACUM albums should link to release group instead of releases

lib/MusicBrainz/Server/Report/ReleasedTooEarly.pm, lib/MusicBrainz/Server/Report/ReleasedTooEarlyDigital.pm, lib/MusicBrainz/Server/Report/ReleasedTooEarlyForLabel.pm, lib/MusicBrainz/Server/ReportFactory.pm, root/report/ReleasedTooEarlyDigital.js, root/report/ReleasedTooEarlyForLabel.js, root/report/ReportsIndex.js, root/server/components.mjs
This adds a new report that shows releases with a release date that predates the start date for one of their release labels. By definition something is wrong here, be it the release label, the release date or the label date.
Tested with sample data and it already found 140 hits, so this seems surprisingly common. Checked a bunch of them and the query seems to be working fine, and the data is indeed bad.
=> MBS-14133: Report for releases older than label start 

.github/workflows/ci.yml, bin/ts, docker/templates/Dockerfile.tests.m4, docker/templates/macros.m4
Fetching https://git.joeyh.name/index.cgi/moreutils.git/plain/ts?h=0.69 now returns a 503 response containing an HTML page with the text "Please Wait...", likely as a form of aggressive rate-limiting. It eventually loads the correct page in-browser.
I've copied the 0.70 version of the script into our repository. A diff of 0.69..0.70 is below (no breaking changes).
```diff
--- bin/ts-0.69 2025-08-28 15:52:36
+++ bin/ts-0.70 2025-08-28 15:45:09
@@ -66,7 +66,7 @@
"i" => \$inc,
"s" => \$sincestart,
"m" => \$mono
-) || die "usage: ts [-r] [-i | -s] [-m] [format]\n";
+) && @ARGV <= 1 or die "usage: ts [-r] [-i | -s] [-m] [format]\n";
if ($rel) {
eval q{
@@ -110,7 +110,7 @@
}
-while (<>) {
+while (<STDIN>) {
if (! $rel) {
if ($hires) {
my $f=$format;
```
=> Unbreak ts install

lib/MusicBrainz/Server/Data/Role/QueryToList.pm, t/lib/t/MusicBrainz/Server/Controller/Artist/Filtering.pm, t/lib/t/MusicBrainz/Server/Controller/Label/Filtering.pm, t/sql/filtering.sql
We are getting ISEs when trying to search for non-ASCII names in release list filters from label pages. The same happens with `find_by_artist_slow`, but since we use `find_by_artist_fast` in prod it hadn't been reported until the label filtering was put out.
Turns out this wasn't even about the filters themselves: `md5` is unhappy with being passed UTF8 arguments without encoding them first, so the arguments for the queries in `query_to_list_limited` cache need to be encoded.
Manually, plus changed one of the filtering test release titles to be Japanese.
=> MBS-14145: Encode utf8 args for md5

lib/MusicBrainz/Server/Controller/WS/js/Edit.pm, lib/MusicBrainz/Server/Edit/Relationship/Create.pm, lib/MusicBrainz/Server/Edit/Relationship/Delete.pm, lib/MusicBrainz/Server/Edit/Relationship/Edit.pm, lib/MusicBrainz/Server/Edit/Relationship/Reorder.pm, lib/MusicBrainz/Server/Edit/Role/EnteredFrom.pm, lib/MusicBrainz/Server/Edit/Types.pm, lib/MusicBrainz/Server/Edit/Work/Create.pm, root/edit/EditIndex.js, root/edit/components/EditEnteredFrom.js, root/edit/components/ListEdit.js, root/static/scripts/release/components/ReleaseRelationshipEditor.js, root/static/styles/edit.less, root/types/edit_types.js, root/types/wsjs.js, t/selenium/MBS-12911.json5, t/selenium/MBS-12921.json5, t/selenium/MBS-12922.json5, t/selenium/MBS-13615.json5, t/selenium/Release_Relationship_Editor.json5
It's often quite hard to figure out the specific source for an edit entered through the relationship editor (especially when a recording is shared between multiple releases), and yet many editors (me included!) tend to forget about it and just enter notes like "See booklet on CAA" or the like.
This makes it so that edits entered from the release relationship editor get a new `entered_from` piece of data, allowing us to always specify what release the edit was, well, entered from.
Manually, plus updated the release editor selenium tests.
=> MBS-14120: Indicate the edited release on edits entered from the relationship editor
